Add is_closed() method to Queue
tensorflow/tensorflow pull request #10175
Opened 2017-05-24 20:55 UTC by a-lattas

to show if a Queue of any type is closed or not, mainly for debugging purposes. Fixes #7355.

2017-05-26 16:03 UTC, maciekcc commented
Jenkins test this please.

2017-05-31 21:44 UTC, a-lattas commented
@girving, you may also be interested to take a look since you discussed this on #7355

2017-05-31 21:55 UTC, girving requested changes

2017-05-31 21:55 UTC, girving commented on tensorflow/core/framework/queue_interface.h
> +  virtual bool closed() = 0;
Should probably be const.

2017-05-31 21:55 UTC, girving commented on tensorflow/core/kernels/queue_ops.cc
> +// the queue is closed.
Remove this comment: the REGISTER_OP documentation should cover this.  This kind of comment is in danger of going out of date.

2017-06-01 15:53 UTC, a-lattas commented on tensorflow/core/framework/queue_interface.h
> +  virtual bool closed() = 0;
done.

2017-06-01 15:53 UTC, a-lattas commented on tensorflow/core/kernels/queue_ops.cc
> +// the queue is closed.
done.

2017-06-01 16:00 UTC, girving requested changes

2017-06-01 16:00 UTC, girving commented on tensorflow/core/framework/queue_interface.h
> +  virtual const bool closed() = 0;
Should be

    virtual bool closed() const = 0;

Making return values const doesn't do anything in C++.

2017-06-01 16:38 UTC, a-lattas commented on tensorflow/core/framework/queue_interface.h
> +  virtual const bool closed() = 0;
done.

2017-06-01 16:58 UTC, girving commented
Jenkins, test this please.

2017-06-01 17:57 UTC, girving commented
@cwhipkey Looks like the tests failed for tool reasons.  Should I ping you or someone else?

2017-06-01 18:27 UTC, gunan commented
Both failures seem to be issues on infra side.
I took the bad machines offline. now should be better.

Jenkins, test this please.

2017-06-01 19:50 UTC, girving approved these changes

2017-06-01 19:51 UTC, girving commented
@martinwicke Who merges these days?

2017-06-01 20:26 UTC, martinwicke commented
This week, @andrewharp.

2017-06-01 20:27 UTC, martinwicke commented
Should get API review.

2017-06-12 23:12 UTC, josh11b commented on tensorflow/core/framework/queue_interface.h
> +  virtual bool closed() const = 0;
For consistency, this should be "is_closed", not "closed"

2017-06-12 23:12 UTC, josh11b commented
This is fine for API review assuming that one change is made.

2017-06-13 07:07 UTC, a-lattas commented on tensorflow/core/framework/queue_interface.h
> +  virtual bool closed() const = 0;
done.

2017-06-13 07:22 UTC, martinwicke commented
Jenkins, test this please.

2017-06-13 15:09 UTC, girving commented
Looks ready to merge.

2017-06-13 15:10 UTC, girving commented
Jenkins, test this please.

2017-06-13 15:54 UTC, a-lattas commented
The two tests failing are the api-compatibility-test and sparse_ops_test.py.
They have also failed other PRs, as seen in #10671 and #10673 6 hours ago.

2017-06-13 15:59 UTC, girving commented
The API test is failing because you changed the API.  Please follow the instructions to make it pass:

    If this test fails, it means a change has been made to the public API. Backwards
    incompatible changes are not allowed. You can run the test as follows to update
    test goldens and package them with your change.

        $ bazel build tensorflow/tools/api/tests:api_compatibility_test
        $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test \
              --update_goldens True

2017-06-13 18:23 UTC, a-lattas commented
@girving Done. Could you please confirm that this is what is needed?

2017-06-13 18:25 UTC, girving approved these changes

2017-06-13 18:25 UTC, girving commented
@a-lattas Yep, that's perfect.

Jenkins, test this please.

2017-06-13 19:41 UTC, girving commented
@martinwicke The API compatibility test still fails, but it looks a lot like the update script was correctly run.  The update script only changed the `QueueBase` API, though, the errors are for the derived queue classes:

    ERROR:tensorflow:5 differences found between API and golden.
    ERROR:tensorflow:Issue 1	: Change detected in python object: tensorflow.PaddingFIFOQueue.
    ERROR:tensorflow:Issue 2	: Change detected in python object: tensorflow.PriorityQueue.
    ERROR:tensorflow:Issue 3	: Change detected in python object: tensorflow.RandomShuffleQueue.
    ERROR:tensorflow:Issue 4	: Change detected in python object: tensorflow.QueueBase.
    ERROR:tensorflow:Issue 5	: Change detected in python object: tensorflow.FIFOQueue.

Is this a bug in the update script or test?

2017-06-13 19:41 UTC, girving commented
Hmm, sorry, I'm wrong: the failure is also for `QueueBase`.  Not sure what's happening then.

2017-06-14 03:27 UTC, martinwicke commented
@gunan do you know what could be wrong here?

2017-06-14 04:03 UTC, martinwicke commented
Jenkins, test this please.

2017-06-14 21:27 UTC, gunan commented
Is it possible the PR authors local version is out of sync with the master?
Maybe a pull is needed first?

2017-06-14 21:42 UTC, a-lattas commented
@gunan Done.

2017-06-14 21:49 UTC, gunan commented
Jenkins, test this please.

2017-06-14 22:03 UTC, martinwicke commented
@gunan, no luck.

2017-06-14 22:13 UTC, a-lattas commented
If I have understood the `api-compatibility-test` correctly, it will fail at any change on the API, except when it is told to update the goldens. Following the instructions in its `README`, I ran the command locally and that should allow only the next `api-compatibility-test` to succeed with API changes, by creating a temporary text file in the same folder. My question is, is the CI aware of this? 

Also note that I added `is_closed` to `Queue_Base` goldens myself. It was not updated automatically. Any thougths?

2017-06-14 22:29 UTC, martinwicke commented
The pbtxt files that it generated should be included in the change --
that's how the CI gets to know about it.

2017-06-14 22:34 UTC, a-lattas commented
I updated (hardcodded) myself the pbtxt file for QueueBase only. Running 
```
    $ bazel build tensorflow/tools/api/tests:api_compatibility_test
    $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test \
          --update_goldens True
```
did not update them. Should I update it for all Queue Types or all should be updated automatically?

2017-06-14 22:53 UTC, martinwicke commented
If they are not updates that is a sign that there is either something wrong
with the test, or your changes don't actually result in API changes (which
in your case, would be troubling).

2017-06-14 23:04 UTC, a-lattas commented
Thank you for the feedback. I will look into it and come up with an answer shortly.

2017-06-16 04:08 UTC, gunan commented
I think The problem is still related to syncing.
I checked out your branch, and the test is failing the same way for me.
I think what you needed to do was, first fetch and merge all changes from tensorflow/tensorflow:master. You did this. But you needed to rerun api compatibility test and update goldens again. I can confirm that, when I run api compatibility test on your branch, I see this failure:
```
ERROR:tensorflow:Issue 1	: Change detected in python object: tensorflow.PaddingFIFOQueue.
ERROR:tensorflow:Issue 2	: Change detected in python object: tensorflow.PriorityQueue.
ERROR:tensorflow:Issue 3	: Change detected in python object: tensorflow.RandomShuffleQueue.
ERROR:tensorflow:Issue 4	: Change detected in python object: tensorflow.QueueBase.
ERROR:tensorflow:Issue 5	: Change detected in python object: tensorflow.FIFOQueue.
```
Then I ran update goldens script. Which made the following modifications:
```
	modified:   tensorflow/tools/api/golden/tensorflow.-f-i-f-o-queue.pbtxt
	modified:   tensorflow/tools/api/golden/tensorflow.-padding-f-i-f-o-queue.pbtxt
	modified:   tensorflow/tools/api/golden/tensorflow.-priority-queue.pbtxt
	modified:   tensorflow/tools/api/golden/tensorflow.-queue-base.pbtxt
	modified:   tensorflow/tools/api/golden/tensorflow.-random-shuffle-queue.pbtxt
```
Then rerunning api compatibility test returns success.
```
Ran 2 tests in 1.080s

OK
```

2017-06-26 18:52 UTC, drpngx commented
@a-lattas any luck with that?

2017-06-26 19:13 UTC, a-lattas commented
I apologise for the delay, I am away from home for a few days.

I can see on @gunan 's post that the `api-compatibility-test` is failing and running it with `update-goldens` let's it progress.

However, when running 
```
    $ bazel build tensorflow/tools/api/tests:api_compatibility_test
```
I get something like
```
Ran 2 tests in 0.080s (skipped 1)
OK
```
with no failure message and 
```
    $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test \
          --update_goldens True
```
does not make any chaninges to the goldens.

I have not found the reason why. `skipped 1` could mean that it is skipping the test? Also, I am not using Docker, as it is not described as necessary. Any ideas?

2017-06-26 19:18 UTC, gunan commented
It is certainly possible.
Api compatibility test runs on Linux and python 2 only, as different versions of dependencies can trigger failures in the api object names. Is it possible you are on a macbook, or using python3?

2017-06-26 19:37 UTC, a-lattas commented
I suppose this is the issue then. I am using Ubuntu, but with python 3.

I will run the test soon with python 2 and inform you about its result.

Thank you.

2017-06-27 11:32 UTC, a-lattas commented
@gunan Thanks! 
I did with python2 . Everything worked as expected and goldens got automatically updated. It should be ready for testing.

2017-06-27 14:11 UTC, girving commented
Jenkins, test this please.

2017-06-27 15:31 UTC, girving commented
The only failure looks unrelated.  @drpngx: Ready for merge!

2017-06-28 18:09 UTC, merged