MKL_INSTALL_PATH should not be clear when given
tensorflow/tensorflow pull request #10180
Opened 2017-05-25 03:07 UTC by Earthson

I'm  trying to build tensorflow from source, just found configure will clear my MKL_INSTALL_PATH

2017-05-25 03:10 UTC, Earthson commented
I signed it!

2017-05-25 05:35 UTC, Earthson commented
I signed it!

2017-05-26 21:40 UTC, jhseu requested changes
This patch does the wrong thing in the ./configure script

Are you sure this is clearing your MKL_INSTALL_PATH? It's not modifying environment variables outside of the ./configure script because it's not calling export.

2017-05-28 01:14 UTC, Earthson commented
@jhseu I means this script overwrite the MKL_INSTALL_PATH out side configure, which is expected to working inside.

I'm trying to build a auto compile script like:

```bash
... \
MKL_INSTALL_PATH=$DEST \
... \
./configure
```

2017-05-30 04:35 UTC, Earthson commented
@jhseu You misunderstood my intention. I'm trying to make the MKL_INSTALL_PATH configurable outside configure file.

2017-05-30 23:50 UTC, jhseu commented on configure
>        MKL_INSTALL_PATH=$default_mkl_path
This overwrites the `read` above.

2017-05-31 02:43 UTC, Earthson commented
@jhseu Thank you for the review. That's my mistake.
I think it works now :)

2017-05-31 02:47 UTC, Earthson commented
@jhseu Is `$fromuser` set right?  I'm a little confused about it.

2017-05-31 17:28 UTC, jhseu approved these changes
The fromuser part is unnecessary, but since it exists in the old code, no need to fix it here.

2017-06-05 11:50 UTC, fayeshine commented
@jhseu Any status on this?

2017-06-05 21:19 UTC, jhseu commented
Jenkins, test this please

2017-06-06 03:09 UTC, Earthson commented
```bash
//tensorflow/python:rmsprop_test                                         PASSED in 30.6s
//tensorflow/python:saver_test                                           PASSED in 33.5s
//tensorflow/python:session_benchmark                                    PASSED in 20.0s
//tensorflow/python:session_manager_test                                 PASSED in 91.6s
//tensorflow/python:slot_creator_test                                    PASSED in 24.9s
//tensorflow/python:special_math_ops_test                                PASSED in 25.5s
//tensorflow/python:split_benchmark                                      PASSED in 21.3s
//tensorflow/python:tensorboard_logging_test                             PASSED in 19.3s
//tensorflow/python:timeline_test                                        PASSED in 26.6s
//tensorflow/python:training_ops_test                                    PASSED in 26.8s
//tensorflow/python:transpose_benchmark                                  PASSED in 18.5s
//tensorflow/python/kernel_tests:stage_op_test                          TIMEOUT in 1 out of 2 in 329.1s
  Stats over 2 runs: max = 329.1s, min = 35.4s, avg = 182.2s, dev = 146.8s
  /var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/testlogs/tensorflow/python/kernel_tests/stage_op_test/shard_1_of_2/test.log

Executed 311 out of 311 tests: 310 tests pass and 1 fails locally.

Parameterized build ends with FAILURE at: Mon Jun  5 22:01:34 UTC 2017 (Elapsed time: 2508 s)
Build step 'Execute shell' marked build as failure
[Set GitHub commit status (universal)] ERROR on repos [] (sha:2dc13c0) with context:tensorflow-pull-requests-gpu
Unable to get pull request builder trigger!!
Setting status of c6e36aa11089ab7283a8a421016c86d191f1220c to FAILURE with url https://ci.tensorflow.org/job/tensorflow-pull-requests-gpu/5116/ and message: 'FAILURE
 '
Using context: Linux GPU
Finished: FAILURE
```

I have no idea about the failure

2017-06-06 03:11 UTC, Earthson commented
Jenkins, test this please

2017-06-06 07:05 UTC, Earthson commented
@jhseu

2017-06-06 07:17 UTC, Earthson commented
Jenkins, test this please

2017-06-06 22:53 UTC, jhseu commented
Jenkins, test this please

2017-06-07 01:00 UTC, merged