Fix comments error in mnist_replica.py where only one ps is used with…
tensorflow/tensorflow pull request #10312
Opened 2017-05-31 10:16 UTC by cxxgtxy

… two works by default.

2017-05-31 13:39 UTC, caisq requested changes

2017-06-01 01:49 UTC, cxxgtxy commented
I have changed the format.

2017-06-01 02:04 UTC, caisq commented
Thanks, @cxxgtxy !

2017-06-01 02:04 UTC, caisq approved these changes

2017-06-01 02:04 UTC, merged