[XLA] Add a 'custom' fusion op type
tensorflow/tensorflow pull request #10319
Opened 2017-05-31 13:46 UTC by DavidNorman

This allows backends that may have fusions that are not included in the main enumeration.

2017-06-14 00:06 UTC, martinwicke commented
@eliben are you reviewing this?

2017-06-14 19:02 UTC, eliben requested changes

2017-06-14 19:02 UTC, eliben commented on tensorflow/compiler/xla/service/hlo_instruction.h
> +    kCustom,              // Custom fusions.
Can you elaborate a bit more in this comment, mentioning backend-specific fustions

2017-06-15 11:56 UTC, eliben approved these changes

2017-06-16 20:16 UTC, martinwicke commented
Jenkins, test this please.

2017-06-19 08:43 UTC, DavidNorman commented
cool - thanks

2017-06-21 09:20 UTC, DavidNorman commented
@martinwicke Hi there.  Could this be merged now?  Cheers

2017-06-26 18:54 UTC, merged