Update the instruction for building a minimal xla benchmark
tensorflow/tensorflow pull request #10387
Opened 2017-06-02 06:54 UTC by freedomtan

1. the instruction for building lstm_layer_inference_benchmark doesn't work.
2. the "cc_target_os" in "android_armeabi" is an unknown option

2017-06-14 17:47 UTC, tatatodd requested changes
Thanks for the PR @freedomtan !

2017-06-14 17:47 UTC, tatatodd commented on tensorflow/BUILD
> +        "crosstool_top": "//external:android/crosstool",
While this is indeed what we want the BUILD file to look like, this isn't the correct way to make this change.

You haven't done anything wrong; we just have a separate (internal) mechanism to deal with BUILD file differences between internal and open-source builds.

The easiest way forward is for you to revert the change in this file, but keep the change in the other file.  I'll fix up the internal mechanism.  Thanks!

2017-06-15 01:03 UTC, freedomtan commented on tensorflow/BUILD
> +        "crosstool_top": "//external:android/crosstool",
Thanks for the review. Rebased and removed this.

2017-06-15 01:15 UTC, tatatodd commented
Jenkins, test this please.

2017-06-15 01:15 UTC, tatatodd approved these changes
Great, thanks @freedomtan !

2017-06-15 15:43 UTC, tatatodd commented
Jenkins, test this please.

2017-06-15 17:01 UTC, tatatodd commented
@martinwicke Can you merge this PR?  Thanks!

2017-06-15 21:20 UTC, merged