add metric op
tensorflow/tensorflow pull request #10400
Opened 2017-06-02 17:05 UTC by astorfi

This pull request is aimed to create a metric_op for TF-Slim learning to be able to show the streaming metrics(accuracy,...) for the training phase.
The op reset the total and count local variables defined by streaming_metric(if it is streaming_accuracy ,...) per each epoch of training so the accumulative accuracy per epoch can be represented.

2017-06-11 20:38 UTC, sguada commented
Please revert all the indentation changes, use 2 spaces per indentation level.

2017-06-11 20:40 UTC, sguada requested changes
Revert all the indentation changes, currently it is hard to see what you actually change.
Use 2 spaces indentation.

2017-06-11 20:40 UTC, sguada commented on tensorflow/contrib/slim/python/slim/learning.py
> +import tensorflow as tf
Don't import tensorflow directly only what is needed.

2017-06-26 18:57 UTC, drpngx commented
@astorfi could you rebase and push again?

2017-06-26 19:02 UTC, astorfi commented
@drpngx There were some issues regarding my pool request. I am trying to solve them yet.

2017-07-24 18:41 UTC, vrv commented
Ping for @astorfi ...

2017-07-24 18:46 UTC, closed without merging