Implemented sinh and cosh
tensorflow/tensorflow pull request #10427
Opened 2017-06-04 11:30 UTC by lakshayg

These commits contains the implementation of the sinh and cosh functions for CPU and GPU with gradients. The supported datatypes are float, double, complex64 and complex128.

Compilation went through successfully on my system (CPU only) and the following test script seems to be running fine on Python 2.7

```python
from __future__ import print_function
import tensorflow as tf
import numpy as np

x = tf.placeholder(shape=[None, 5], dtype=tf.float32)
y = tf.placeholder(shape=[None, 5], dtype=tf.float32)

W = tf.Variable(tf.random_uniform(shape=[5,5], dtype=tf.float32))
w = tf.cosh(W)
error = tf.reduce_mean((tf.matmul(x, w) - y)**2)
train = tf.train.GradientDescentOptimizer(1e-2).minimize(error)

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
for i in range(100):
    tmp_x = np.random.rand(10, 5)
    tmp_y = np.random.rand(10, 5)

    sess.run(train, feed_dict={x:tmp_x, y:tmp_y})
print(sess.run(W))
```

2017-06-06 19:52 UTC, rmlarsen requested changes
Looks really good!

2017-06-06 19:52 UTC, rmlarsen commented on tensorflow/core/ops/math_grad_test.cc
> +
Add tests for complex.

2017-06-06 19:53 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-06-06 20:56 UTC, rmlarsen commented on tensorflow/cc/gradients/math_grad_test.cc
> +    return dy * conjugate(std::cos(x));
Ah, it looks like you need to replace cos with cosh here to fix the broken test.

2017-06-06 20:57 UTC, rmlarsen commented
@lakshayg It looks like there's a bug in the C++ complex gradient for sinh: [ RUN      ] CWiseUnaryGradTest.Sinh_Complex
2017-06-06 20:16:34.833848: E tensorflow/core/framework/tensor_testutil.cc:34] x = Tensor<type: complex64 shape: [2,3,2] values: ? ? ?...>
2017-06-06 20:16:34.833874: E tensorflow/core/framework/tensor_testutil.cc:35] y = Tensor<type: complex64 shape: [2,3,2] values: ? ? ?...>
2017-06-06 20:16:34.833936: E tensorflow/core/framework/tensor_testutil.cc:36] atol = 1e-06 rtol = 1e-06 tol = 9.1994e-06
tensorflow/core/framework/tensor_testutil.cc:38: Failure
Value of: false
  Actual: false
Expected: true
0-th element is not close (-8.1365184783935547,1.0135481357574463) vs. (2.779362678527832,-0.21568894386291504)
2017-06-06 20:16:34.834010: E tensorflow/core/framework/tensor_testutil.cc:34] x = Tensor<type: complex64 shape: [2,3,2] values: ? ? ?...>
2017-06-06 20:16:34.834015: E tensorflow/core/framework/tensor_testutil.cc:35] y = Tensor<type: complex64 shape: [2,3,2] values: ? ? ?...>
2017-06-06 20:16:34.834021: E tensorflow/core/framework/tensor_testutil.cc:36] atol = 1e-06 rtol = 1e-06 tol = 4.45043e-06
tensorflow/core/framework/tensor_testutil.cc:38: Failure
Value of: false
  Actual: false
Expected: true
1-th element is not close (-1.5430805683135986,3.0861611366271973) vs. (-0.54030227661132812,1.0806045532226562)

2017-06-07 03:20 UTC, lakshayg commented on tensorflow/core/ops/math_grad_test.cc
> +
@rmlarsen I am not sure how to implement the tests for complex here as no other functions like sin, cos, tan, tanh do not implement such test. Also, I implemeted the test for complex in ` tensorflow/cc/gradients/math_grad_test.cc`. Did you mean this file?

2017-06-07 05:43 UTC, lakshayg commented
@rmlarsen I am also working on implementing the inverse hyperbolic functions and having some issues with understanding the code. It would be great if you could help me by answering the question at https://stackoverflow.com/questions/44389994/making-sense-of-gradforunarycwise-in-tensorflow

2017-06-07 20:35 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-06-07 20:36 UTC, rmlarsen commented on tensorflow/core/ops/math_grad_test.cc
> +
I think it's OK. You have test coverage in several other places.

2017-06-08 07:11 UTC, lakshayg commented
I thinks this is somewhat strange. Of the 4 tests which failed, 3 ran successfully (Windows Cmake Tests, Linux GPU, Linux CPU Tests) before the last revision. Since the last revision involved correcting one of the test functions (changing `std::cos(x)` to `std::cosh(x)`), it surprises me that tests in unrelated files are failing.

I ran the following commands on my machine and the tests were successful

1. bazel test //tensorflow/python/kernel_tests:check_ops_test 
2. bazel test //tensorflow/python/kernel_tests:embedding_ops_test
3. bazel test //tensorflow/contrib/seq2seq:beam_search_decoder_test
4. bazel test //tensorflow/python/kernel_tests:sparse_ops_test
5. bazel test //tensorflow/contrib/seq2seq:basic_decoder_test
6. bazel test //tensorflow/contrib/layers:embedding_ops_test

2017-06-08 23:43 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-06-08 23:43 UTC, rmlarsen commented
@lakshayg I think the test failures are unrelated to your change.

2017-06-08 23:44 UTC, rmlarsen approved these changes

2017-06-09 03:16 UTC, merged