Add link that helps explain feed_dict parameter
tensorflow/tensorflow pull request #10637
Opened 2017-06-11 17:30 UTC by DanCard

The current tutorial mentions using feed_dict parameter, but there is not further mention.  The example code does not explain where feed_dict is used.  By linking to the run documentation, the reader can see it is the second parameter to the run command.

2017-06-11 18:07 UTC, caisq requested changes

2017-06-11 18:07 UTC, caisq commented on tensorflow/docs_src/get_started/get_started.md
>  evaluate this graph with multiple inputs by using the feed_dict parameter to
s/parameter/argument/

2017-06-11 18:07 UTC, caisq commented on tensorflow/docs_src/get_started/get_started.md
> +the [run operation](https://www.tensorflow.org/api_docs/python/tf/Session#run)
s/operation/method/

2017-06-11 18:07 UTC, caisq commented on tensorflow/docs_src/get_started/get_started.md
> +to specify Tensors that provide concrete values to these placeholders:
s/to specify Tensors that provide concrete values to these placeholders/to feed concrete values to the placeholders/

2017-06-11 19:32 UTC, DanCard reviewed
Done.

2017-06-11 21:15 UTC, DanCard reviewed
Done

2017-06-12 13:21 UTC, caisq approved these changes

2017-06-12 13:21 UTC, merged