added blocks option for lstm2d
tensorflow/tensorflow pull request #10692
Opened 2017-06-14 07:29 UTC by johnsmithm

2017-06-15 03:15 UTC, lukaszkaiser requested changes
Just a few style nits (space around operators). All looks fine otherwise, thanks!

2017-06-15 03:15 UTC, lukaszkaiser commented on tensorflow/contrib/ndlstm/python/lstm2d.py
> +    if height%kernel_size[0] != 0:
Could you add a space before and after "%"?

2017-06-15 03:15 UTC, lukaszkaiser commented on tensorflow/contrib/ndlstm/python/lstm2d.py
> +    h, w = int(height/kernel_size[0]), int(width/kernel_size[1])
Same for "/", or maybe just use "//"?

2017-06-15 03:15 UTC, lukaszkaiser commented on tensorflow/contrib/ndlstm/python/lstm2d.py
> +    if width%kernel_size[1] != 0:
Here too.

2017-06-15 03:15 UTC, lukaszkaiser commented on tensorflow/contrib/ndlstm/python/lstm2d.py
> +                                kernel_size[1]-(width%kernel_size[1]),
And here, for "-" too.

2017-06-15 07:00 UTC, johnsmithm commented
thanks for review, maybe someone should add these rule in pylint too

2017-06-22 11:44 UTC, johnsmithm commented
Waiting for review!

2017-06-23 01:15 UTC, lukaszkaiser approved these changes
Looks good, sorry for the delay!

2017-06-26 21:52 UTC, drpngx commented
Jenkins, test this please.

2017-06-26 23:13 UTC, merged