Padding queue support for tf.estimator generator input pipeline
tensorflow/tensorflow pull request #10732
Opened 2017-06-15 12:47 UTC by Scitator

So, as I desrcibe [here](https://github.com/tensorflow/tensorflow/issues/10680), there is no padding possibilities in current estimator's input pipelines.

For now I added simple possibility to you data have dynamic shape over last axis. 
If such solution looks good, then I am looking forward for next contributing steps.

2017-06-15 12:50 UTC, Scitator commented
I signed it!

2017-06-22 16:53 UTC, martinwicke requested changes
This is nice, but I would like some test coverage for all the new code you're adding. You're doing some fragile index things, so without comprehensive tests we cannot trust that it works in all cases.

2017-06-22 16:53 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +  from itertools import izip_longest as zip_longest
What's the reason for this? Could it be avoided by using six?

2017-06-26 16:40 UTC, drpngx commented
@Scitator can you use six instead?

2017-06-27 06:48 UTC, Scitator commented
Six done. What test are required?
Will be tests for `_fill_array` and `_pad_if_needed` enough?

2017-06-29 00:45 UTC, drpngx commented
Yes, these are the new functions to be tested.

Ideally, `_get_integer_next_batch` will also be exercised.

2017-07-24 19:03 UTC, vrv commented
Ping for @Scitator !

2017-08-09 17:20 UTC, rmlarsen commented
@Scitator one more ping

2017-08-10 17:25 UTC, Scitator commented
@rmlarsen @vrv @drpngx 
Sorry guys, was out of the internet for about a mount (even now my connection is very slow).
Add docs and some tests.

2017-08-10 17:44 UTC, rmlarsen commented
@Scitator Thanks! 
@drpngx @martinwicke could you take another look, please?

2017-08-10 17:44 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-10 18:33 UTC, martinwicke requested changes
Please add another test that tests that the top level function (generator_input_fn) does the right thing if pad_data=True. 

You write nice tests for the utility functions, the only piece that is missing is to verify that all that is actually used when pad_data=True.

More interesting question: What happens when the data type of x is not numeric? I believe it won't work, but you should check (and if it doesn't work, either fix it, or raise an informative error). Also you may consider changing pad_data to pad_value and allowing the user to set a value instead of forcing it to 0.

2017-08-10 18:33 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +from six.moves import zip_longest
Can you access this below as six.moves.zip_longest instead of adding the import here? We try to only import full modules.

2017-08-10 18:33 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +    fillvalue: Defaulf fillvalue to use.
"Default"

2017-08-10 18:33 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +        "for now, there is now way to pad and shuffle data at the same time")
Please change the error message to "Padding and shuffling at the same time is not implemented."

2017-08-10 18:33 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions_test.py
> +          np.ones(shape=[32, 36], dtype=np.int32).tolist()
Please don't use \ continuation, simply indent next line by four (two less than you have)

2017-08-10 18:33 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions_test.py
> +          np.ones(shape=[8, 8, 8, 8, 36], dtype=np.int32).tolist()
here too

2017-08-10 18:33 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions_test.py
> +    expected[:32, 32:] = 0
Can you test (either here or even better in a separate test case) that a value other than 0 is actually used if specified?

2017-08-11 18:05 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-11 18:25 UTC, Scitator commented
@martinwicke 
So, add additional tests (bug found) + change logic for `pad_value` usage.  With changed logic code sometimes looks a bit ugly. 

Main functionality have no tests yet (but works it my personal projects). By the way, where are all generator input pipeline tests?

2017-08-15 00:35 UTC, martinwicke commented
Jenkins, test this please.

2017-08-15 00:41 UTC, martinwicke requested changes
Testing FTW!

Thanks! Some minor formatting things left, otherwise looks good.

2017-08-15 00:41 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +                 for key, item in list(list_dict.items())}
can you fix the indentation here? Should be at the level of the opening `{` +1

2017-08-15 00:41 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +      feed_dict = {key: np.asarray(item)
same here

2017-08-15 00:41 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions_test.py
> +        np.ones(shape=[32, 36], dtype=np.int32).tolist())
add one space to the indent here

2017-08-15 00:41 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +        "padding and shuffling data at the same time is not implemented")
plus two spaces to indent here

2017-08-15 00:41 UTC, martinwicke commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +        "padding is only available with generator usage")
+2 space to indent here

2017-08-15 14:39 UTC, Scitator commented
@martinwicke Update indents and generator IO, tested on my [repo](https://github.com/Scitator/YATS2S/blob/versions/tf_1.2/seq2seq_example.ipynb)

2017-08-15 20:11 UTC, martinwicke commented
Jenkins, test this please.

2017-08-16 16:11 UTC, Scitator commented
@martinwicke Finally, all check have passed.

2017-08-16 16:25 UTC, martinwicke commented
Jenkins, test this please.

2017-08-16 16:26 UTC, martinwicke approved these changes
Great!

2017-08-16 18:19 UTC, Scitator commented
@tensorflow-jenkins test this please.

2017-08-16 21:22 UTC, merged