[OpenCL] Fixes device name comparison stage_op_test
tensorflow/tensorflow pull request #10760
Opened 2017-06-16 11:11 UTC by jwlawson

Changes the fixed '/device:GPU:0' expected device name string to the name returned by 'test/gpu_device_name()', as the device name could be '/device:SYCL:0' or '/device:GPU:0'.

Resubmission of #10682

2017-06-20 21:34 UTC, yifeif approved these changes
Approve as the same change has been approved in https://github.com/tensorflow/tensorflow/pull/10682. cc: @benoitsteiner

2017-06-20 21:34 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-06-21 19:15 UTC, benoitsteiner requested changes

2017-06-21 19:15 UTC, benoitsteiner commented on tensorflow/python/kernel_tests/stage_op_test.py
> +        self.assertEqual(y.device, gpu_dev)
This cause the following test failure on gpu:
======================================================================
FAIL: testColocation (__main__.StageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-gpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local_linux-opt/bin/tensorflow/python/kernel_tests/stage_op_test.runfiles/org_tensorflow/tensorflow/python/kernel_tests/stage_op_test.py", line 105, in testColocation
    self.assertEqual(y.device, gpu_dev)
AssertionError: u'/device:GPU:0' != u'/gpu:0'

2017-06-26 16:50 UTC, drpngx commented
@jwlawson any luck with the test failure?

2017-06-29 16:24 UTC, benoitsteiner approved these changes

2017-06-29 16:24 UTC, benoitsteiner commented
Jenkins, test this please.

2017-07-02 05:32 UTC, merged