Refactor and implementation of the camera API 1, it fixes #8736
tensorflow/tensorflow pull request #10771
Opened 2017-06-16 17:38 UTC by osdamv

As detailed in #8736, the legacy devices should work with the Camera API 1, the detector demo would need even more refactor in order to work

2017-06-16 17:44 UTC, osdamv commented
I signed it!

2017-06-20 21:38 UTC, yifeif commented
For the CLA issue, @BrianOn99 are you okay with your commit being included in this PR?
@osdamv could you resolve the conflict? Thanks!

2017-06-21 02:34 UTC, BrianOn99 commented
Sure.

2017-06-21 02:38 UTC, BrianOn99 commented
I think my PR could be closed as @osdamv 's approach looks better (less code duplication).  Thanks for the improvement!

2017-06-21 08:09 UTC, BrianOn99 commented
Confirmed to be working except the detector demo.  However the debugging info is not visible in the classify demo.  Or is it removed from the master branch recently?

2017-06-21 19:41 UTC, osdamv commented
@yifeif I just fixed the conflicts

2017-06-22 16:55 UTC, yifeif commented
Thanks @osdamv and @BrianOn99. 
@andrewharp could you take a look? Thanks!

2017-06-22 19:02 UTC, andrewharp requested changes
Thanks for doing this! Mostly formatting things, but I do have questions about the existence of separate image handling methods in each activity.

2017-06-22 19:02 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +
extra linebreak

2017-06-22 19:02 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +  /*
misalignment

2017-06-22 19:02 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +
extra linebreak

2017-06-22 19:02 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +  protected abstract void processImageRGBbytes(byte[] luminance) ;
I'm not sure I understand the purpose of this method as opposed to onImageAvailable() -- I can't see that luminance is ever filled in or used? Was this the missing functionality?

2017-06-22 19:02 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +    processImageRGBbytes(new byte[bytes.length * 2/3]);
Where does the 2/3 come from?

2017-06-22 19:08 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/LegacyCameraConnectionFragment.java
> +  private Camera mCamera;
I didn't know, the next time doesn't gonna happen

2017-06-22 19:09 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +  /*
D:, I need to get use to androis studio, my editor of choice is vim ...

2017-06-22 19:10 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +
ok

2017-06-22 19:10 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +
ok

2017-06-22 19:11 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +    processImageRGBbytes(new byte[bytes.length * 2/3]);
that is a good question, in the original PR from @BrianOn99, used that value, I am not sure why ?

2017-06-22 19:15 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +  protected abstract void processImageRGBbytes(byte[] luminance) ;
it was supposed to be used with Detector demo, because it requires the luminance to draw the squares, TBH I left that thing mistake

2017-06-22 19:23 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +  protected abstract void processImageRGBbytes(byte[] luminance) ;
Ok, I think I understand the intention now. Can you please remove luminance (I'll add it back later), and make rgbBytes private and pass it as the parameter to the processRGBBytes() method?

2017-06-22 19:31 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +  protected abstract void processImageRGBbytes(byte[] luminance) ;
sure !!

2017-06-23 15:30 UTC, BrianOn99 commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +  /*
There is a vim plugin for andriod studio which which is fantastic.  But I still miss vim sometimes.

2017-06-26 21:56 UTC, drpngx commented
Jenkins, test this please.

2017-06-26 23:14 UTC, drpngx commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +        rgbBytes = new int[previewWidth * previewHeight];
Did you address @andrewharp comments? It looks like this is still there.

2017-06-28 15:25 UTC, andrewharp commented
Jenkins, test this please.

2017-06-28 23:45 UTC, drpngx commented
@osdamv to be clear, this is ready to be reviewed?

2017-06-28 23:58 UTC, osdamv commented
Yeah, I hope there is no more sanity issues

2017-06-29 01:00 UTC, drpngx commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +        rgbBytes = new int[previewWidth * previewHeight];
@osdamv Please, do address all @andrewharp comments before requesting a new review.

2017-07-01 04:50 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +        rgbBytes = new int[previewWidth * previewHeight];
@drpngx  should I refactor that too?

2017-07-06 20:33 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
> +        rgbBytes = new int[previewWidth * previewHeight];
@osdamv You could add a check to see if rgbBytes == null before initializing. Right now it looks like onPreviewSizeChosen will be called every frame.

2017-07-14 19:01 UTC, osdamv commented
Hi, I was too busy the last to weeks(I was studying for a Facebook interview!!) in order to make the requested changes. Hopefully this commit pass the review :).

2017-07-14 19:11 UTC, drpngx commented
Hope it went well! Looking forward to the update.

On Jul 14, 2017 12:03 PM, "osdamv" <notifications@github.com> wrote:

Hi, I was too busy the last to weeks(I was studying for a Facebook
interview!!) in order to make the requested changes. Hopefully this commit
pass the review :).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/10771#issuecomment-315441091>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AT_SbRofqHlznMLzZL5Y5PRxO2G-uCqhks5sN7tygaJpZM4N8vJo>
.

2017-07-14 21:03 UTC, andrewharp reviewed
Looks pretty good! Could you please make a pass over and ensure that:
 lines are no longer than 100 characters
 there are spaces after //s
 indents are 2 inside {}s, but 4 for parens

2017-07-18 17:20 UTC, andrewharp commented
@tensorflow-jenkins Test this, please.

2017-07-18 19:57 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java
> +      LOGGER.i(
Not sure I understand github's behavior here -- is this method actually removed? Why does it still show up here when viewing "all commits", but not when I try to edit/view the file by itself?

@osdamv The log message should be indented 4 spaces here.

@drpngx If I can see all the cumulative commits together in the "files changed" view, do you know why I can't directly edit the latest version of it in the branch here? "View" and "edit" show me a different file than the side-by-side view.

2017-07-18 19:57 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java
> +      frameToCropTransform =
4 space indentation on continuation of statement until sequence point (we don't use 8 space indentations anywhere)

2017-07-19 17:44 UTC, osdamv commented on tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java
> +      LOGGER.i(
Done

2017-07-19 19:17 UTC, andrewharp commented on tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java
> +      LOGGER.i(
After your last commit I could see the changes in the edit view, strange!

2017-07-19 19:17 UTC, andrewharp approved these changes

2017-07-19 22:11 UTC, jhseu commented
Jenkins, test this please

2017-07-24 19:05 UTC, merged

2017-07-24 19:17 UTC, andrewharp commented
@osdamv Thank you for the contribution!

2017-07-24 21:11 UTC, osdamv commented
@andrewharp  Your welcome!! Any thing else I can do please let me know