fix error string format
tensorflow/tensorflow pull request #10948
Opened 2017-06-21 10:09 UTC by dgboy2000

I just got this helpful error message, and I'm submitting a fix for the format.

ValueError: ('num_outputs should be int or long, got %s.', <tf.Tensor 'mul:0' shape=() dtype=int32>)

becomes

ValueError: num_outputs should be int or long, got Tensor("mul:0", shape=(), dtype=int32).

2017-06-21 12:53 UTC, caisq requested changes

2017-06-21 12:53 UTC, caisq commented on tensorflow/contrib/layers/python/layers/layers.py
> +        'num_outputs should be int or long, got %s.' % (num_outputs,))
There is no need for the brackets and comma here, since there is only one item.

2017-06-21 23:15 UTC, dgboy2000 commented
What if num_outputs is a tuple? Then you'd get an obscure TypeError: not
all arguments converted during string formatting. This ValueError is only
raised if the type is wrong in the first place (as I experienced), so in my
opinion it's helpful to be robust to this case.

What do you think?

On Wed, Jun 21, 2017 at 5:56 AM, Shanqing Cai <notifications@github.com>
wrote:

> *@caisq* requested changes on this pull request.
> ------------------------------
>
> In tensorflow/contrib/layers/python/layers/layers.py
> <https://github.com/tensorflow/tensorflow/pull/10948#discussion_r123238498>
> :
>
> > @@ -1445,7 +1445,8 @@ def fully_connected(inputs,
>      ValueError: If x has rank less than 2 or if its last dimension is not set.
>    """
>    if not isinstance(num_outputs, six.integer_types):
> -    raise ValueError('num_outputs should be int or long, got %s.', num_outputs)
> +    raise ValueError(
> +        'num_outputs should be int or long, got %s.' % (num_outputs,))
>
> There is no need for the brackets and comma here, since there is only one
> item.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/10948#pullrequestreview-45421383>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AARY4YqFQVjfuazpkMQ_H8NfFWTu0J2oks5sGRL6gaJpZM4OAvgW>
> .
>

2017-06-21 23:15 UTC, dgboy2000 commented on tensorflow/contrib/layers/python/layers/layers.py
> +        'num_outputs should be int or long, got %s.' % (num_outputs,))
What if num_outputs is a tuple? Then you'd get an obscure TypeError: not
all arguments converted during string formatting. This ValueError is only
raised if the type is wrong in the first place (as I experienced), so in my
opinion it's helpful to be robust to this case.

What do you think?

2017-06-22 01:37 UTC, caisq commented on tensorflow/contrib/layers/python/layers/layers.py
> +        'num_outputs should be int or long, got %s.' % (num_outputs,))
OK. That makes sense.

2017-06-22 01:38 UTC, caisq approved these changes

2017-06-22 01:38 UTC, caisq commented
@tensorflow-jenkins test this please

2017-06-22 13:23 UTC, caisq commented
Test failure is unrelated. Merging PR.

Thanks, @dgboy2000 !

2017-06-22 13:23 UTC, merged