Support specify the user name when writing data to HDFS。 You can spec…
tensorflow/tensorflow pull request #11009
Opened 2017-06-23 10:21 UTC by Yiran-wu

When I write data to HDFS I can not specify username
This scenario is used by multiple users using the same client as a local user.

You can specify the environment variable （TF_HDFS_USER） to modify the write username.

 e.g:
export TF_HDFS_USER="username"

2017-06-23 10:24 UTC, Yiran-wu commented
I signed it!

2017-06-26 06:51 UTC, yifeif commented
Thanks @Yiran-wu! @jhseu could you take a look? Thanks!

2017-06-26 16:59 UTC, drpngx approved these changes

2017-06-26 16:59 UTC, drpngx commented
Jenkins, test this please.

2017-06-26 18:34 UTC, jhseu requested changes
Does HADOOP_USER_NAME not work?

If not, can you set it using that environment variable, since that's more standard?

2017-06-27 03:51 UTC, Yiran-wu commented
I use the following script to test it, HADOOP_USER_NAME can not work, we still need to modify the code.

```
# import MNIST
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

import tensorflow as tf
import os

os.environ['HADOOP_USER_NAME'] = 'test001'
# set parameters
learning_rate = 0.01
training_iteration = 30
batch_size = 100
display_step = 2


# TF graph input
x = tf.placeholder("float", [None, 784])
y = tf.placeholder("float", [None, 10])

# create a model

# set model weights
# 784 is the dimension of a flattened MNIST image
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

with tf.name_scope("Wx_b") as scope:
    # construct linear model
    model = tf.nn.softmax(tf.matmul(x, W) + b) #softmax

# add summary ops to collect data
w_h = tf.summary.histogram("weights", W)
b_h = tf.summary.histogram("biases", b)

with tf.name_scope("cost_function") as scope:
    # minimize error using cross entropy
    cost_function = -tf.reduce_sum(y*tf.log(model))
    # create a summary to monitor the cost function
    tf.summary.scalar("cost_function", cost_function)

with tf.name_scope("train") as scope:
    # gradient descent
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost_function)

init = tf.global_variables_initializer()

# merge all summaries into a single operator
merged_summary_op = tf.summary.merge_all()

# launch the graph
with tf.Session() as sess:
    sess.run(init)

    # set the logs writer to the folder /tmp/tensorflow_logs
    summary_writer = tf.summary.FileWriter('hdfs://172.16.141.90:8020/tmp/tensorflow_logs', graph=sess.graph)

    # training cycle
    for iteration in range(training_iteration):
        avg_cost = 0.
        total_batch = int(mnist.train.num_examples/batch_size)
        # loop over all batches
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            # fit training using batch data
            sess.run(optimizer, feed_dict={x: batch_xs, y: batch_ys})
            # compute the average loss
            avg_cost += sess.run(cost_function, feed_dict={x: batch_xs, y: batch_ys})/total_batch
            # write logs for each iteration
            summary_str = sess.run(merged_summary_op, feed_dict={x: batch_xs, y: batch_ys})
            summary_writer.add_summary(summary_str, iteration*total_batch + i)
        # display logs per iteration step
        if iteration % display_step == 0:
            print("Iteration:", '%04d' % (iteration + 1), "cost= ", "{:.9f}".format(avg_cost))

    print("Tuning completed!")

    # test the model
    predictions = tf.equal(tf.argmax(model, 1), tf.argmax(y, 1))
    # calculate accuracy
    accuracy = tf.reduce_mean(tf.cast(predictions, "float"))
    print("Accuracy:", accuracy.eval({x: mnist.test.images, y: mnist.test.labels}))


print("Success!")
```

2017-06-27 03:52 UTC, Yiran-wu commented
Jenkins, test this please.

2017-06-27 06:31 UTC, closed without merging