Sort shuffled indices before indexing NumpyFeed
tensorflow/tensorflow pull request #11010
Opened 2017-06-23 11:21 UTC by swook

It is possible to use `h5py` datasets with `tf.estimator.inputs.numpy_input_fn` as there is a high level of compatibility.

However, with `shuffle=True`, one can no longer do so due to the following error:

    TypeError: Indexing elements must be in increasing order

This small change allows for one to use large HDF5 datasets via `h5py` with shuffled batch indices.

2017-06-23 13:13 UTC, swook commented
I signed it!

2017-06-26 17:00 UTC, drpngx commented
Jenkins, test this please.

2017-06-26 22:11 UTC, drpngx commented
That seems to make a lot of tests fail. Could you take a look?

2017-06-27 13:45 UTC, swook commented
@drpngx I believe this now allows tests to pass.

However, I'm unsure if the tests should be adjusted instead.

2017-06-27 15:12 UTC, drpngx commented
Jenkins, test this please.

On Jun 27, 2017 6:48 AM, "Seonwook Park" <notifications@github.com> wrote:

> @drpngx <https://github.com/drpngx> I believe this now allows tests to
> pass.
>
> However, I'm unsure if the tests should be adjusted instead.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/11010#issuecomment-311362785>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT_SbTjPtyKZMwpfwaTj3T4PwSys345aks5sIQgJgaJpZM4ODcnM>
> .
>

2017-06-27 20:04 UTC, drpngx commented
Now passes the tests.

@xiejw would have cycles to take a look?

2017-07-11 00:24 UTC, frankchn commented
ping @xiejw

2017-07-17 05:20 UTC, xiejw commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +    # Get sorted indices and remember how to reorder output.
The code looks good. But can you add a comment to briefly explain why this is required?

2017-07-17 05:20 UTC, xiejw commented
Sorry for the delay. Just a nit.

2017-07-17 14:00 UTC, swook commented
@xiejw thanks for reviewing this PR. I've added a line to explain why sorting is necessary.

2017-07-17 16:48 UTC, xiejw approved these changes

2017-07-17 16:48 UTC, xiejw commented
Thanks for the contribution!

2017-07-18 23:37 UTC, jhseu commented
The timeseries failures look related. Allen, thoughts?

2017-07-18 23:58 UTC, allenlavoie commented
Just so I'm clear, this change should ideally only be affecting the order in which the Numpy arrays are indexed, but should be returning the same values as before down the line in TensorFlow land?

I can dig into them to figure out how exactly, but I think those test failures are indicating that with shuffle=False this PR is changing the output of the op (i.e. it's no longer returned in the input order). Probably indicates a bug?

2017-07-19 17:06 UTC, xiejw commented on tensorflow/python/estimator/inputs/queues/feeding_functions.py
> +        column[sorted_integer_indexes][reorder_indexes]
After digging into details, I think this line has a bug. You meant to put the elements into position reorder_indexes, but instead, here it is getting the elements from position reorder_indexes. I should catch this earlier. Sorry.

(I was also worrying about performance if this line does the expected assigning). 

One mini example could be:

>>> a = np.array([10, 20, 30, 40])
>>> i = [0, 1, 2, 3, 0, 1, 2, 3]                                                                                                                                                                                                                                                                                              
>>> a[i]
array([10, 20, 30, 40, 10, 20, 30, 40])
>>> sorted_integer_indexes, reorder_indexes = zip(*sorted([(value, index) for index, value in enumerate(i)]))
>>> sorted_integer_indexes = list(sorted_integer_indexes)
>>> reorder_indexes = list(reorder_indexes)
>>> reorder_indexes
[0, 4, 1, 5, 2, 6, 3, 7]
>>> a[sorted_integer_indexes][reorder_indexes]
array([10, 30, 10, 30, 20, 40, 20, 40])

2017-07-19 17:08 UTC, xiejw requested changes
I should catch this bug earlier. Sorry for that.

2017-07-20 09:20 UTC, swook commented
@xiejw thanks for catching the bug out. I have committed a fix to make the tests pass. I have confirmed that tests pass on my end by rebasing on upstream.

Your concern on performance is something I agree with however...

If I understand right.. this issue occurs when wrapping around datasets to return to index 0. Perhaps it's better to split the indexing operations to allow for this.

Or dismiss this PR as it could be argued that it's a bug in `h5py`.

I leave the decision to you, the maintainers.

2017-07-20 15:58 UTC, xiejw commented
For now, I think you can convert the h5py as numpy which is one time cost. If this has more cost than expected or it is extremely inconvenient, we can revisit this PR and propose some new ideas. 

With that said, I will close this PR and please reopen if anything changed in future. 

Thanks for your contribution!

2017-07-20 15:58 UTC, closed without merging

2017-07-20 16:03 UTC, swook commented
I understand. Not to re-open the issue, but I'd just like to mention that I'm using `h5py` for large input data which cannot be held in memory. While one could write their own pre-processing routine using tensorflow queues, using the numpy feeding functions with hdf5 structures is very convenient.

I attach the explanation for future reference.