Update head.py
tensorflow/tensorflow pull request #11159
Opened 2017-06-30 02:08 UTC by printdhruv

Switching to tf.summary.scalar

2017-06-30 02:48 UTC, drpngx requested changes

2017-06-30 02:48 UTC, drpngx commented on tensorflow/contrib/learn/python/learn/estimators/head.py
> -from tensorflow.python.ops import logging_ops
please remove entirely if not needed.

2017-06-30 02:48 UTC, drpngx commented on tensorflow/contrib/learn/python/learn/estimators/head.py
> +from tensorflow.python import summary as logging_ops
please use summary not logging_ops

2017-06-30 05:35 UTC, printdhruv commented on tensorflow/contrib/learn/python/learn/estimators/head.py
> -from tensorflow.python.ops import logging_ops
Hi,
       Thanks for correction. Please review it.

2017-07-01 17:25 UTC, drpngx commented
Jenkins, test this please.

2017-07-01 17:25 UTC, drpngx approved these changes

2017-07-01 17:45 UTC, drpngx commented
```
==================== Test output for //bazel_pip/tensorflow/contrib/learn:head_test:
2017-07-01 17:37:31.975956: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-01 17:37:31.976063: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-01 17:37:31.976098: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-01 17:37:31.976113: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-01 17:37:31.976119: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:Casting <dtype: 'float32'> labels to bool.
WARNING:tensorflow:Casting <dtype: 'float32'> labels to bool.
/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-py3-opt/bin/bazel_pip/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/bazel_pip/tensorflow/contrib/learn/python/learn/estimators/head_test.py:717: DeprecationWarning: Please use assertEqual instead.
  k: v[0] for k, v in six.iteritems(model_fn_ops.output_alternatives)
F..--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

2017-07-02 23:37 UTC, printdhruv commented on tensorflow/contrib/learn/python/learn/estimators/head.py
> -from tensorflow.python.ops import logging_ops
I tried to use assertEqual but 46 tests are failing. head_test.py is outdated. Would you like to give some suggestions?

2017-07-07 02:55 UTC, printdhruv commented
@drpngx  I compiled and ran successfully head_test.py with a minor fix in `JetBrains PyCharm 2017.1.4` with `Python 3.6` and showed status `All 83 tests passed`. I am wondering how can I verify with Jenkins from my end so that I don't waste resources here.Please share me possible ways to verify changes check for all OS.

2017-07-08 02:39 UTC, drpngx commented
Jenkins, test this please.

2017-07-08 02:41 UTC, drpngx commented
@printdhruv thank you for being thoughtful! Jenkins tests different platforms, and it's good to check on your end as you do. For other platforms, if you want to go the extra mile, you can try docker.  The docker platforms are [checked in](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker). But it's fine for us to test the build as long as you tested your main platform.

2017-07-10 17:44 UTC, alanyee commented
On line 1483, you are still using logging_ops.scalar_summary.

2017-07-10 19:27 UTC, frankchn commented
Jenkins, test this please.

2017-07-11 00:23 UTC, frankchn commented
`//tensorflow/contrib/learn:head_test` is failing. Sample logs:

```FAIL: testMultiClassWithLabelKeysEvalAccuracy1 (__main__.MultiClassHeadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head_test.py", line 1444, in testMultiClassWithLabelKeysEvalAccuracy1
    _assert_summary_tags(self, ["loss"])
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head_test.py", line 90, in _assert_summary_tags
    test_case.assertItemsEqual(expected_tags or [], actual_tags)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'loss'
First has 0, Second has 1:  u'multi_class_head/loss'```

2017-07-15 23:51 UTC, printdhruv commented
@frankchn @alanyee @drpngx 
I replaced `logging_ops.scalar(
          _summary_key(head_name, mkey.LOSS), weighted_average_loss)		          _summary_key(head_name, mkey.LOSS), weighted_average_loss)`
 
with the following statement.

 `tensorflow.summary.scalar(
        name=_summary_key(head_name, mkey.LOSS), tensor=weighted_average_loss,collections=None)`

What I think the` AssertionError: Element counts were not equal:` is generated is due to the eval and loss is in the different graph according to author's comment on line `623-624`.
```

# Uses the deprecated API to set the tag explicitly.
# Without it, training and eval losses will show up in different graphs.

```
If I am wrong then please give your suggestions.

2017-07-16 00:00 UTC, frankchn commented
@printdhruv, can you make @alanyee's change first and rebase to master? `logging_ops` is still used on line 1483.

2017-07-16 00:06 UTC, printdhruv reviewed
Updated

2017-07-16 00:08 UTC, frankchn commented
Jenkins, test this please.

2017-07-17 07:00 UTC, closed without merging

2017-07-17 07:01 UTC, printdhruv commented
Resolved [https://github.com/tensorflow/tensorflow/pull/11526](https://github.com/tensorflow/tensorflow/pull/11526)

2017-07-17 07:29 UTC, alanyee commented
@printdhruv I haven't fixed the deprecated tf.summary yet.