Remove type constraint on shape_invariants
tensorflow/tensorflow pull request #11179
Opened 2017-06-30 15:33 UTC by TheButlah

This PR fixes the unnecessarily strict type checking addressed in issue #11115. Turning type checking off for the shape_invariants parameter in tf.while_loop will allow the parameter to be more easily used when, for example, trying to provide an invariant for an LSTMStateTuple variable.

2017-06-30 17:57 UTC, drpngx requested changes
Could you add a test to check that behavior?

2017-07-06 19:15 UTC, caisq commented
@TheButlah ping regarding @drpngx's request for tests?

2017-07-07 18:02 UTC, TheButlah commented
I'll try to write some tests for it eventually; this is my first open source contribution and I need to read up on how to do that exactly.

2017-07-24 20:08 UTC, vrv commented
Any updates @TheButlah ?  Thanks for the contribution!

2017-08-09 17:17 UTC, rmlarsen commented
@TheButlah ping?

2017-08-24 05:35 UTC, jhseu commented
Closing this out due to being stalled for a while. Feel free to reopen or send a new pull request if you'd like to submit this change with the test.

2017-08-24 05:35 UTC, closed without merging