Support placeholder for parameter k in tf.nn.in_top_k
tensorflow/tensorflow pull request #11197
Opened 2017-06-30 22:37 UTC by yongtang

This fix tries to address the issue raised in #9717 where it was not possible to have tensor for k in nn.in_top_k.

This fix adds the implementation of InTopKV2Op, adds addition test cases, and following similiar workflow in #10840:
1. Register new kennel InTopKV2Op
2. Hide InTopK and InTopKV2 in python (tensorflow/python/ops/hidden_ops.txt)
3. Add a wrapper in_top_k (in tensorflow/python/ops/nn_ops.py) pointing to gen_nn_ops._in_top_k

Another PR will be created after 3 weeks once this PR is merged:
1. Change the implementation of the wrapper in_top_k (in tensorflow/python/ops/nn_ops.py)
pointing to gen_nn_ops._in_top_kv2

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-06-30 22:55 UTC, drpngx commented on tensorflow/core/ops/nn_ops.cc
> +    .Attr("T: {int32, int64} = DT_INT32")
I think you need `.HostMemory("k")`

2017-07-02 14:37 UTC, yongtang commented on tensorflow/core/ops/nn_ops.cc
> +    .Attr("T: {int32, int64} = DT_INT32")
Thanks @drpngx for the review. I am still trying to be familiar with the codebase of tensorflow., though it looks like `InTopK` and `InTopKV2` kernel are only registered with CPU. Not sure if  `HostMemory` is needed?

2017-07-02 21:07 UTC, drpngx commented on tensorflow/core/ops/nn_ops.cc
> +    .Attr("T: {int32, int64} = DT_INT32")
We are working on a GPU version.

2017-07-05 15:34 UTC, girving requested changes

2017-07-05 15:34 UTC, girving commented on tensorflow/core/kernels/in_topk_op.cc
> +class InTopKV2 : public OpKernel {
No need to rename the class.

2017-07-05 15:34 UTC, girving commented on tensorflow/core/kernels/in_topk_op.cc
> +class InTopKV2 : public OpKernel {
Especially since the rename makes no sense as it also does V1.

2017-07-05 15:34 UTC, girving commented on tensorflow/core/kernels/in_topk_op.cc
> +      k_val = k_in.scalar<int>()();
This will crash if k_in is int64, as is explicitly allowed by the op registration.  If it didn't crash, it would silently truncate to 32 bits.

2017-07-05 15:34 UTC, girving commented on tensorflow/core/ops/nn_ops.cc
> +precision: Computed Precision at `k` as a `bool Tensor`.
Why is precision capitalized?

2017-07-07 10:08 UTC, yongtang commented on tensorflow/core/ops/nn_ops.cc
> +    .Attr("T: {int32, int64} = DT_INT32")
Thanks @drpngx The PR has been updated with HostMemory added.

2017-07-07 10:09 UTC, yongtang commented on tensorflow/core/kernels/in_topk_op.cc
> +class InTopKV2 : public OpKernel {
Thanks @girving. The PR has been updated with name intact.

2017-07-07 10:09 UTC, yongtang commented on tensorflow/core/kernels/in_topk_op.cc
> +      k_val = k_in.scalar<int>()();
Thanks @girving The issue has been addressed.

2017-07-07 10:09 UTC, yongtang commented on tensorflow/core/ops/nn_ops.cc
> +precision: Computed Precision at `k` as a `bool Tensor`.
Thanks. Fixed.

2017-07-07 10:10 UTC, yongtang commented
@drpngx @girving Thanks for the review. The PR has been updated. Please take a look.

2017-07-07 14:54 UTC, girving approved these changes
Looks good, though all of @drpngx's HostMemory changes seem unnecessary.  I'll let you two sort that out, though.

2017-07-14 18:14 UTC, drpngx commented
Jenkins, test this please.

2017-07-19 21:33 UTC, drpngx approved these changes
As per geoffreyi's comment

2017-07-19 21:34 UTC, merged