Add scaffolding to allow XLA unit tests to run for other devices
tensorflow/tensorflow pull request #11262
Opened 2017-07-04 06:29 UTC by DavidNorman

This is an indentical change to the one in the compiler/tests directory.  It allows devices other than the CPU and GPU to be available targets when running the tests in compiler/xla/tests.

2017-07-04 17:22 UTC, drpngx commented
Jenkins, test this please.

2017-07-04 17:43 UTC, drpngx commented
@tatatodd WDYT?

2017-07-04 21:34 UTC, DavidNorman commented
Hi,

I'd like to think that the failure in a python3 front end test isn't anything to do with my change. 

Perhaps we can test again, or see if other public pull requests are suffering from the same problem?

2017-07-04 21:42 UTC, DavidNorman commented
So, in terms of the effectiveness of this change, I think it is quite important to have a way for non-CPU/GPU devices to be tested against all of XLA.    My device actually fails quite a few of the tests because they are written with the assumption that devices support the full intersection of CPU/GPU types (which out device currently does not).  I will extend type support on our device to unsigned integer types, eliminating most of the problems, but I will probably have to submit another pull request in the future that allows devices to opt out of double precision float tests.  While our compiler supports doubles, it isn't on the timeline to support them in the graph framework.

2017-07-04 21:42 UTC, drpngx commented
Yes, it seems unrelated to your change.

2017-07-06 17:23 UTC, tatatodd requested changes

2017-07-06 17:23 UTC, tatatodd commented on tensorflow/compiler/xla/tests/plugin.bzl
> +#  "poplar": {
Minor suggestion: Perhaps change `poplar` to `foo`, to make it more clear this is the thing you're supposed to fill in.

2017-07-06 17:23 UTC, tatatodd commented on tensorflow/compiler/xla/tests/plugin.bzl
> +#      "//tensorflow/compiler/plugin/poplar:poplar_lib",
Ditto, if you change the above, change this to:
```
  "//tensorflow/compiler/plugin/foo:foo_lib",
```

2017-07-06 17:24 UTC, tatatodd commented
@DavidNorman Looks good to me, thanks for the PR!

Just some minor comments; I'll approve and kick off new tests once those are in.

2017-07-06 18:25 UTC, DavidNorman commented
thanks - will do ASAP

2017-07-06 18:28 UTC, DavidNorman commented
@tatatodd Done - cheers

2017-07-06 18:31 UTC, drpngx commented
Jenkins, test this please.

2017-07-06 19:25 UTC, tatatodd approved these changes
@DavidNorman Looks great!

2017-07-06 20:44 UTC, merged