Minor fix typo
tensorflow/tensorflow pull request #11323
Opened 2017-07-06 11:19 UTC by ScorpioCPH

Minor fix comments typo.

2017-07-06 13:44 UTC, caisq requested changes

2017-07-06 13:44 UTC, caisq commented on tensorflow/core/lib/gtl/array_slice.h
> -  // comparisons.  Array slices are equal iff their size is the same
This is not a typo. "Iff" means "if and only if".
https://www.merriam-webster.com/dictionary/iff

2017-07-06 13:44 UTC, caisq commented on tensorflow/core/protobuf/worker.proto
> -  // True iff the graph (before partitioning) contains control flow nodes.
Same as above.

2017-07-07 04:18 UTC, ScorpioCPH commented on tensorflow/core/lib/gtl/array_slice.h
> -  // comparisons.  Array slices are equal iff their size is the same
ok, i will revert it.

2017-07-07 04:19 UTC, ScorpioCPH commented
@caisq ping.

2017-07-07 14:02 UTC, caisq requested changes

2017-07-07 14:02 UTC, caisq commented on tensorflow/core/lib/gtl/array_slice.h
> +  // std::vector<T> relational operators: they do deep (element-wise)
I think this line is moved to the wrong place.

2017-07-07 14:53 UTC, ScorpioCPH commented on tensorflow/core/lib/gtl/array_slice.h
> +  // std::vector<T> relational operators: they do deep (element-wise)
You are right, fix it by amend last commit :)

2017-07-07 14:56 UTC, caisq approved these changes

2017-07-07 14:56 UTC, merged