Third-party Scala API Links in the Documentation
tensorflow/tensorflow pull request #11397
Opened 2017-07-09 18:43 UTC by eaplatanios

I added a couple links to my Scala API repository in the documentation pages. I'm not sure if it's in the expected format, but feel free to rephrase if needed.

It would be great if we could also add a link in the following page (I could not find it in the documentation sources): https://www.tensorflow.org/api_docs/.

Thanks!

2017-07-10 20:22 UTC, asimshankar requested changes

2017-07-10 20:22 UTC, asimshankar commented on tensorflow/docs_src/extend/index.md
> +[Scala](https://github.com/eaplatanios/tensorflow_scala), and
Let's revert the change in this file. The languages listed here are maintained by members of the TensorFlow github organization, just don't get the same level of support. I'd like for documentation to be clear between bindings maintained by (and for which support can be expected from) the TensorFlow organization and those owned, maintained and supported by others.

2017-07-10 20:22 UTC, asimshankar commented on tensorflow/docs_src/programmers_guide/faq.md
> +An experimental Scala API that replicates a lot of the Python API functionality using the C API is located at [eaplatanios/tensorflow_scala](https://github.com/eaplatanios/tensorflow_scala).
Here too I'd like to ensure that the reader is clear about the distinction between bindings that are maintained by (and for which they can expect support for) by the TensorFlow organization and those owned, maintained and supported by others.

How about the following instead:

Bindings for various other languages (such as [C#](https://github.com/migueldeicaza/TensorFlowSharp), [Julia](https://github.com/malmaud/TensorFlow.jl), [Ruby](https://github.com/somaticio/tensorflow.rb) and [Scala](https://github.com/eaplatanios/tensorflow_scala)) created and supported by the opensource community build on top of the [C API](https://www.tensorflow.org/code/tensorflow/c/c_api.h) supported by the TensorFlow maintainers.

2017-07-10 21:41 UTC, eaplatanios commented
@asimshankar I made the changes you requested. Thanks for clarifying which part of the documentation refers to officially maintained libraries and third-party ones. :)

2017-07-11 00:55 UTC, asimshankar approved these changes
Thanks!

2017-07-11 00:55 UTC, asimshankar commented
Jenkins, test this please

2017-07-11 18:45 UTC, merged