modify SaverDef default version with v2
tensorflow/tensorflow pull request #11406
Opened 2017-07-10 07:42 UTC by horance-liu

SaverDef V1 has been deprecated, so modify default version with V2.

2017-07-10 18:21 UTC, frankchn requested changes

2017-07-10 18:21 UTC, frankchn commented on tensorflow/core/protobuf/saver.proto
> +    //Current format: more efficient.
Nit, a space between `//` and `Current`

2017-07-11 06:14 UTC, horance-liu commented on tensorflow/core/protobuf/saver.proto
> +    //Current format: more efficient.
@frankchn Sorry, I have modified to commit it, please review again.

2017-07-11 06:23 UTC, frankchn commented
Can you rebase to master and then apply your changes rather than merging from master? Right now it shows that you are merging in a bunch of changes that are irrelevant to you.

2017-07-11 10:59 UTC, closed without merging