Enable building label_image with jpeg/gif/png decoder for Android.
tensorflow/tensorflow pull request #11451
Opened 2017-07-12 10:42 UTC by qjivy

This PR adds the Android platform building of the  jpeg, gif and png decoder to the C++ image classification demo "label_image". 
It enables the evaluation of practical dataset such as ImageNet on Android platform devices, for both model precision, and hardware performance.

2017-07-12 10:53 UTC, qjivy commented
Perhaps Andrew Harp andrewharp@google.com<mailto:andrewharp@google.com> or Peter Warden petewarden@google.com<mailto:petewarden@google.com>.

Hi Peter and Andrew,
Not quite sure if you can help to review this PR.
Thank you so much!

Ji
-------------------------------------------------------------------------------------------------------------------------------------
THIS E-MAIL INCLUDING ANY ATTACHMENTS CONTAINS SPREADTRUM’S PROPRIETARY CONFIDENTIAL INFORMATION THAT IS HIGHLY CONFIDENTIAL AND PRIVILEGED.

From: Tensorflow Jenkins [mailto:notifications@github.com]
Sent: Wednesday, July 12, 2017 6:44 PM
To: tensorflow/tensorflow
Cc: Ji Qiu (邱吉); Author
Subject: Re: [tensorflow/tensorflow] Enable building label_image with jpeg/gif/png decoder for Android. (#11451)


Can one of the admins verify this patch?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tensorflow/tensorflow/pull/11451#issuecomment-314724530>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AXR6uuI3ISZMtEqOvME2PJXJyN0_k_YEks5sNKNYgaJpZM4OVcc_>.

2017-07-12 17:43 UTC, frankchn commented
Jenkins, test this please.

2017-07-12 23:57 UTC, petewarden requested changes
I'm a bit wary of this change because it will pull in several potentially large dependencies on Android, and this could impact the binary size. Is it possible to break out the image decoders as a separate library that label_image relies on for Android, so that typical users don't have to pull it in?

2017-07-13 10:53 UTC, qjivy commented
Hi Pete, 
I can fully understand your concern. Please review the new PR #11475.
Thank you!


Ji

2017-07-24 21:46 UTC, closed without merging