Print default when CUDA and CuDNN versions are not specified
tensorflow/tensorflow pull request #11460
Opened 2017-07-12 17:12 UTC by yifeif

Fix #10456.

2017-07-12 17:23 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-07-12 19:50 UTC, gunan commented
I am OOO, but @caisq should be a better reviewer than me for any bash code.

2017-07-13 00:19 UTC, caisq requested changes

2017-07-13 00:19 UTC, caisq commented on configure
> +  if [ -z "$TF_CUDA_VERSION" ]; then
Can be simplified as:
TF_CUDA_VERSION=${TF_CUDA_VERSION:-8.0}

2017-07-13 00:19 UTC, caisq commented on configure
> +  if [ -z "$TF_CUDNN_VERSION" ]; then
As above, can be simplified as:
TF_CUDNN_VERSION=${TF_CUDNN_VERSION:-6}

2017-07-13 01:06 UTC, caisq approved these changes

2017-07-13 01:06 UTC, caisq commented
@tensorflow-jenkins test this please

2017-07-13 18:32 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-07-13 21:23 UTC, yifeif commented
the xla failure is irrelevant, here is a passing run https://ci.tensorflow.org/job/tensorflow-pull-requests-xla/1743/

2017-07-13 21:23 UTC, merged