Fix broken AttentionMechanism docstrings
tensorflow/tensorflow pull request #11464
Opened 2017-07-12 21:43 UTC by jagthebeetle

Currently, for all AttentionMechanisms, the `memory_sequence_length` arg does not get formatted correctly in the docs, making it easy to miss. 

I believe this is because the `(optional)` modifier is not preceded by a colon, as in the other (working) args.

2017-07-12 21:58 UTC, frankchn requested changes

2017-07-12 21:58 UTC, frankchn commented on tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
> +      memory_sequence_length: (optional): Sequence lengths for the batch entries
Can you remove the `:` after `(optional)` as well?

2017-07-12 21:58 UTC, frankchn commented on tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
> +      memory_sequence_length: (optional): Sequence lengths for the batch entries
ditto

2017-07-12 21:58 UTC, frankchn commented on tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
> +      memory_sequence_length: (optional): Sequence lengths for the batch entries
ditto

2017-07-13 18:48 UTC, jagthebeetle reviewed
I found further instances of colons after `(optional)`, see next commit.

2017-07-13 20:42 UTC, frankchn approved these changes

2017-07-13 20:42 UTC, frankchn commented
Jenkins, test this please.

2017-07-13 22:10 UTC, frankchn commented
Jenkins, test this please.

2017-07-14 22:06 UTC, frankchn commented
@jagthebeetle Can you rebase to the latest master and apply your commit on top of that? Github is showing thousands of commits right now. I think it is better to create a new PR for this rather than reusing this.

2017-07-14 22:06 UTC, closed without merging