Add SquaredDifference gradient
tensorflow/tensorflow pull request #11530
Opened 2017-07-16 07:18 UTC by DimanNe

I added gradient function for the [SquaredDifference](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/squared-difference) and test case.

2017-07-16 17:46 UTC, frankchn commented
Jenkins, test this please.

2017-07-16 18:08 UTC, drpngx requested changes
Thanks! The main issue is py/c++ compatibility.

2017-07-16 18:08 UTC, drpngx commented on tensorflow/cc/gradients/math_grad_test.cc
> +    // All data & info have been collected => run test itself:
remove. This should be straightforward from the code and is vulnerable to getting stale after refactorings.

2017-07-16 18:08 UTC, drpngx commented on tensorflow/cc/gradients/math_grad_test.cc
> +    auto check = [&scope](const Output& actual_gradient,
const auto tensor_expect_close

2017-07-16 18:08 UTC, drpngx commented on tensorflow/cc/gradients/math_grad.cc
> +Status SquaredDifferenceGrad(const Scope& scope, const Operation& op,
While this seems right, this is not what the [python](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_grad.py#L826) does, right?

The C++ and python bindings have to match.

2017-07-16 18:09 UTC, drpngx commented
/CC @asimshankar

2017-07-19 08:23 UTC, DimanNe commented
I noticed that they in [python](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_grad.py#L826) have over a dozen(!) of instances of copy-pasted lines for reshaping gradients due to broadcasting feature, and decided to make a helper class `ReshapeGradientsWRTBroadcasting` that will make everything for me.

2017-07-19 21:18 UTC, drpngx requested changes

2017-07-19 21:18 UTC, drpngx commented on tensorflow/cc/gradients/math_grad.cc
> +class ReshapeGradientsWRTBroadcasting {
Probably ReshapGradientsForBroadcast is a better name.

2017-07-19 21:18 UTC, drpngx commented on tensorflow/cc/gradients/math_grad.cc
> +  ReshapeGradientsWRTBroadcasting(const ::tensorflow::Scope& scope,
It's fine to use just `const Scope& scope`.

2017-07-19 21:18 UTC, drpngx commented on tensorflow/core/lib/random/random.cc
> +namespace {
This should be split into another PR

2017-07-24 22:11 UTC, vrv commented
@DimanNe friendly ping!  Thanks

2017-07-25 08:46 UTC, DimanNe commented
I forgot to squash commits while merging, sorry.

@vrv  As far as I understood this PR was blocked by [this PR](https://github.com/tensorflow/tensorflow/pull/11634), so I could not do anything here.

2017-07-26 07:56 UTC, DimanNe commented
Did something go wrong with Sanity Checks? Or have I done something wrong?

2017-08-08 19:36 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-08 19:38 UTC, rmlarsen commented
@drpngx Did @DimanNe address your comments? 
@vrv Don't we need to also define the second derivative as well when moving something like this to a C++ kernel?

2017-08-08 19:44 UTC, vrv commented
Yes, if you add a new op that fuses existing python ops, you need to add the gradient for the fused op.

2017-08-10 17:39 UTC, rmlarsen commented
@DimanNe Can you please add a gradient op for the new (gradient) op?

2017-08-10 17:51 UTC, DimanNe commented
@rmlarsen Yes, sure, I will do that.

2017-08-10 18:07 UTC, rmlarsen commented
@DimanNe thanks!

2017-08-10 20:31 UTC, DimanNe commented
@rmlarsen Sorry for bothering, but I realized that I had misunderstood something. Can you, please, clarify where I should add gradient operation for the new gradient operation(s) `+-2(x-y)`?

For example, in order to make gradient op for the **named** operation `"SquaredDifference"`, I registered a C++ function using macro `REGISTER_GRADIENT_OP`, but how am I supposed to register function computing gradient for two **unnamed** functions `+-2(x-y)`? Or perhaps there is any example of doing it?

If it is not difficult, could you please take a step backward and elucidate why do we need at all gradient op for gradient? What is the rationale behind having hand-written second-order derivatives/gradients? Would not it be enough to have only first-order gradients and do everything else with automatic differentiation?

2017-08-10 20:50 UTC, rmlarsen commented
@DimanNe My apologies. You are indeed just creating a composite op using the C++ interface. What I was referring to what cases in the past where people would add a specialized C++ kernel for computing a gradient, in which case the automatic differentiation would have no way of acting on it.

I think what you have here is fine. @skye can you confirm this?

2017-08-15 10:26 UTC, DimanNe commented
@rmlarsen , @skye I understand that you are busy, and probably do not want at all to make C++ interface of TensorFlow great again. So, can I do anything to help you and/or to expedite merging the PR?

2017-08-15 16:07 UTC, skye commented
Hey sorry, I meant to ping @suharshs but forgot!

2017-08-16 18:25 UTC, DimanNe commented
@suharshs any news/thoughts?)

2017-08-16 19:09 UTC, suharshs commented
Ah, unfortunately it looks like someone recently just submitted this gradient :(
https://github.com/tensorflow/tensorflow/commit/293020e83df4fdaa8bfb59275cf05028609b92cd
Thanks so much for implementing this though, and let us know if you see anything wrong with what was submitted.

2017-08-16 19:30 UTC, closed without merging