add recovery_wait_secs option for MonitoredTrainingSession
tensorflow/tensorflow pull request #11533
Opened 2017-07-16 10:01 UTC by horance-liu

In order to reduce the sleep time by worker to wait for a model to be initialized or restored , 
，we add  recovery_wait_secs option for MonitoredTrainingSession，and we are able to start distributed training faster.

2017-07-16 17:47 UTC, frankchn commented
Jenkins, test this please.

2017-07-17 20:49 UTC, jhseu commented
Let's wait for @ispirmustafa to return to review, since he owns this class. Might take a few weeks.

2017-08-08 19:35 UTC, rmlarsen commented
@ispirmustafa could you take a look, please?

2017-08-08 19:52 UTC, ispirmustafa requested changes
Thank you!
One small doc change, otherwise LGTM.

2017-08-08 19:52 UTC, ispirmustafa commented on tensorflow/python/training/monitored_session.py
> +    recovery_wait_secs: Number of seconds between checks that the model is ready.
here it needs better documentation. we should mention that this is used by worker jobs to check whether chief initialized/restored session or not.

2017-08-10 11:33 UTC, horance-liu commented on tensorflow/python/training/monitored_session.py
> +    recovery_wait_secs: Number of seconds between checks that the model is ready.
Thanks, I have appended more comment for this parameter.

2017-08-10 16:25 UTC, rmlarsen approved these changes

2017-08-10 16:25 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-10 17:04 UTC, ispirmustafa approved these changes

2017-08-10 17:37 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-10 19:53 UTC, rmlarsen commented
@martinwicke looks like this is good to go, pending API review.

2017-08-11 08:51 UTC, martinwicke submitted a review, later dismissed
One little docs change, otherwise good.

2017-08-11 08:51 UTC, martinwicke commented on tensorflow/python/training/monitored_session.py
> +    recovery_wait_secs: Number of seconds that this is used by worker jobs to
remove "this"?

2017-08-11 08:52 UTC, martinwicke commented
LG for API once docstring is fixed.

2017-08-16 05:57 UTC, horance-liu commented on tensorflow/python/training/monitored_session.py
> +    recovery_wait_secs: Number of seconds that this is used by worker jobs to
I'm sorry, I have fixed it.

2017-08-19 07:09 UTC, horance-liu commented
@rmlarsen I have fixed it for comment.

2017-08-22 00:10 UTC, jhseu commented
Jenkins, test this please

2017-08-22 00:50 UTC, jhseu commented
Jenkins, test this please

2017-08-24 04:53 UTC, jhseu commented
Mind updating the goldens? See the failing test. Thanks!

2017-08-25 00:56 UTC, horance-liu commented
I run the test as follows to update test goldens, but nothing changed.

    $ bazel build tensorflow/tools/api/tests:api_compatibility_test
    $ bazel-bin/tensorflow/tools/api/tests/api_compatibility_test --update_goldens True

![image](https://user-images.githubusercontent.com/13819195/29695085-27a0b376-8973-11e7-94e3-3c3266487e09.png)

What should I do next?  Thanks

2017-09-04 06:49 UTC, martinwicke commented
@gunan Can you see what went wrong here?

2017-09-04 07:23 UTC, gunan commented
You need to run the api compatibility test with python 2. Are you using python3, by any chance?

2017-09-04 16:27 UTC, martinwicke commented
We should probably point that out explicitly in the failure message if it
doesn't already.

2017-09-17 01:38 UTC, drpngx commented
FTR, the error is:
```
ERROR:tensorflow:2 differences found between API and golden.
ERROR:tensorflow:Issue 1	: Change detected in python object: tensorflow.train.WorkerSessionCreator.
ERROR:tensorflow:Issue 2	: Change detected in python object: tensorflow.train.
F.
```

@horance-liu did you run the golden generator? Did you run it in python2 or python3?

2017-09-26 20:54 UTC, sb2nov commented
@horance-liu ping

2017-10-03 23:27 UTC, horance-liu commented
I have run the golden generator in python2, but nothing changed. See [](https://user-images.githubusercontent.com/13819195/29695085-27a0b376-8973-11e7-94e3-3c3266487e09.png)

2017-10-03 23:28 UTC, horance-liu commented
I have run the golden generator in python2, but nothing changed. See https://user-images.githubusercontent.com/13819195/29695085-27a0b376-8973-11e7-94e3-3c3266487e09.png

2017-10-30 21:32 UTC, gunan commented
Sorry for incomplete instructions. You need to be on Linux, and python2 to regenerate goldens. I will look into what we need to also include windows and macos in the OS side.
If you are working on a macos system, you may use docker to do the golden update.

2017-11-07 00:35 UTC, martinwicke commented
@asimshankar @josh11b This is the same change we just reviewed... we said back then it was ok. Didn't make the connection until now. Same question applies -- why is there a timeout at all?

2017-12-18 20:55 UTC, martinwicke commented
I think this has since been independently added (albeit with a radically different default). I'll close this PR.

2017-12-18 20:55 UTC, closed without merging