https://github.com/tensorflow/tensorflow/issues/9481
tensorflow/tensorflow pull request #11562
Opened 2017-07-17 23:03 UTC by HectorSVC

Descrition:
Fix the bug that Tensorflow on Windows running into issues when there's UTF8 encoded characters in the file path.
Solution:
Switch to use WideChar API calls for Windows, like the CreateFileW,FindFirstFileW,FindNextFileW, LoadLibraryExW.
Test:
Install Tensorflow on Windows with path have Chinese characers in it. No issue.
Run command "from tensorflow.contrib.rnn.python.ops.gru_ops import *" No issue.

2017-07-18 20:18 UTC, mrry requested changes
This is looking great, thanks! I just have a few style-related nits.

2017-07-18 20:18 UTC, mrry commented on tensorflow/core/platform/windows/windows_file_system.h
> +  std::wstring Utf8ToWideChar(const string& utf8str) {
Could this be defined as `static`?

2017-07-18 20:18 UTC, mrry commented on tensorflow/core/platform/windows/windows_file_system.h
> +  string WideCharToUtf8(const std::wstring &wstr) {
Could this be `static` as well?

2017-07-18 20:18 UTC, mrry commented on tensorflow/python/lib/io/file_io_test.py
> +  def testUTF8StringPath(self):
I'm not sure if I'm reading [PEP 263](https://www.python.org/dev/peps/pep-0263/) correctly, but I think we'll need `# coding=UTF-8 ` near the top of the file. (IIUC, without such a comment, it'll be treated as ASCII.)

2017-07-20 21:28 UTC, HectorSVC commented on tensorflow/python/lib/io/file_io_test.py
> +  def testUTF8StringPath(self):
updated

2017-07-20 21:29 UTC, HectorSVC reviewed
update code according to review comments

2017-07-20 21:29 UTC, HectorSVC commented on tensorflow/core/platform/windows/windows_file_system.h
> +  std::wstring Utf8ToWideChar(const string& utf8str) {
updated

2017-07-20 22:07 UTC, mrry approved these changes
Looks good to me! I'll run the tests and this should be good to merge.

2017-07-20 22:07 UTC, mrry commented
Jenkins, test this please!

2017-07-21 14:05 UTC, mrry commented
@tensorflow-jenkins test this please.

2017-07-21 20:09 UTC, jhseu commented
@HectorSVC mind checking the test failures?

2017-07-21 22:04 UTC, HectorSVC commented
looking

2017-07-21 23:13 UTC, HectorSVC commented
@jhseu Could you run the test again? I passed these test locally. No clue how it relate to my changes.

2017-07-21 23:41 UTC, jhseu commented
Jenkins, test this please

2017-07-24 22:18 UTC, vrv commented
@tensorflow-jenkins test this please

2017-07-27 18:08 UTC, vrv commented
@tensorflow-jenkins test this please

2017-07-28 22:12 UTC, vrv commented
@tensorflow-jenkins test this please

2017-07-29 01:57 UTC, vrv commented
@tensorflow-jenkins test this please

2017-08-04 22:50 UTC, HectorSVC commented
found more place need to be changed

2017-08-05 08:30 UTC, KrisRoofe commented on tensorflow/python/lib/io/file_io_test.py
> +    file_path = os.path.join(self._base_dir, "UTF8测试_file")
file_path = os.path.join(self._base_dir, "UTF8_test_file")

2017-08-07 16:25 UTC, HectorSVC commented on tensorflow/python/lib/io/file_io_test.py
> +    file_path = os.path.join(self._base_dir, "UTF8测试_file")
It's by purpose, to test the file path with utf-8 encoding, to verify the bug fix.

2017-08-08 01:03 UTC, HectorSVC commented
@tensorflow-jenkins test this please

2017-08-08 01:06 UTC, mrry commented
@tensorflow-jenkins test this please.

2017-08-08 01:16 UTC, HectorSVC commented
@mrry, Is there something wrong with Jenkins?

2017-08-08 01:23 UTC, mrry commented
Jenkins seems to be working, but I think the code is broken for non-Windows platforms:

https://github.com/tensorflow/tensorflow/blame/dbb9040ca31e25d81482559130e68ca928b19a6c/tensorflow/core/platform/env.cc#L35

This line seems to be including Windows-specific FS code unconditionally into cross-platform code. You probably need to wrap that `#include` in an `#if defined(PLATFORM_WINDOWS)`/`#endif` pair.

2017-08-08 02:21 UTC, mrry commented
@tensorflow-jenkins test this please.

2017-08-08 02:41 UTC, LF-DevJourney approved these changes

2017-08-08 19:30 UTC, merged

2017-08-26 07:06 UTC, micklexqg commented
tf.gfile.FastGFile(r'F:\train\Rubus_pedatifolius_Genév\4000.jpg', 'rb').read() failed...

2018-12-21 21:41 UTC, amapic commented
This correction has been made in which version of tensorflow ?