Add more coverage of file_io methods in gcs_smoke tests.
tensorflow/tensorflow pull request #11827
Opened 2017-07-27 21:30 UTC by sumitgouthaman

Add more coverage of file_io methods in gcs_smoke tests.

Also adds some missing assertions in existing test cases.

2017-07-27 22:31 UTC, rinugun approved these changes

2017-07-27 22:31 UTC, rinugun commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  # Create a files of 2 different patterns in this directory.
Typo: "create a files"

2017-07-27 22:38 UTC, sumitgouthaman commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  # Create a files of 2 different patterns in this directory.
Fixed

2017-07-28 02:27 UTC, caisq requested changes

2017-07-28 02:27 UTC, caisq commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  # Test directory creation
nit: end comments with period.

2017-07-28 02:27 UTC, caisq commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  starttime = int(round(time.time() * 1000))
rename to starttime_ms to be explicit about the time unit?

2017-07-28 02:27 UTC, caisq commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  elapsed = int(round(time.time() * 1000)) - starttime
same as above. rename to elapsed_ms to be explicit about time unit. same below.

2017-07-28 02:27 UTC, caisq commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
>    # List contents of just created directory.
Update comment to "Create some contents in the just created directory and list the contents."

2017-07-28 02:27 UTC, caisq commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  new_dir_name = "%s/new_dir" %dir_name
nit: missing space after the percent character.

2017-07-28 15:35 UTC, sumitgouthaman commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  # Test directory creation
Fixed

2017-07-28 15:36 UTC, sumitgouthaman commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  starttime = int(round(time.time() * 1000))
fixed

2017-07-28 15:37 UTC, sumitgouthaman commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  elapsed = int(round(time.time() * 1000)) - starttime
fixed

2017-07-28 15:37 UTC, sumitgouthaman commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
>    # List contents of just created directory.
fixed

2017-07-28 15:37 UTC, sumitgouthaman commented on tensorflow/tools/gcs_test/python/gcs_smoke.py
> +  new_dir_name = "%s/new_dir" %dir_name
fixed

2017-07-28 19:44 UTC, caisq approved these changes

2017-07-28 19:45 UTC, merged