[XLA] RNG root instruction can be fused as it effectively has one user
tensorflow/tensorflow pull request #11849
Opened 2017-07-28 14:20 UTC by DavidNorman

The existing test checks for a single user when trying to fuse a random number generator instruction.   This is because if it is fused but has multiple users, the value may be generated an incorrect number of times.  (multiple users should receive the same random number, not different ones).

The test checks for users() length == 1.  This ignores the case there the instruction is the root, where users() length == 0, but there is effectively one user.

2017-07-28 21:37 UTC, blakehechtman requested changes
I do not think this will break anything, but it it would be nice to see a test where Rng is both the root of a computation and is fused to make sure nothing breaks.

2017-07-31 08:57 UTC, DavidNorman commented
@blakehechtman done.

i tried adding a death test for the 2+ case, but the testing framework complains that death tests are unstable with multiple threads.

2017-08-04 17:15 UTC, blakehechtman approved these changes

2017-08-05 10:15 UTC, DavidNorman commented
cheers :)

2017-08-05 10:15 UTC, DavidNorman commented
@vrv @blakehechtman 

I think you need to do the 'test this' command to get the tests to run.

2017-08-05 17:23 UTC, vrv commented
@tensorflow-jenkins test this please

2017-08-05 18:15 UTC, DavidNorman commented
Thanks.  The failure in the windows build is this:

```
10:23:57 error: cannot lock ref 'refs/remotes/origin/pr/5992/head': Unable to create 'c:/tf_jenkins/home/workspace/tensorflow-pr-win-cmake-py/.git/refs/remotes/origin/pr/5992/head.lock': File exists.
```

Think it is a different problem - maybe even a CI system issue.

2017-08-05 18:21 UTC, vrv commented
Yup, seems like a flaky failure that can be ignored!  This is ready to merge (I'm not on merge rotation this week so I don't want to screw anything up)

2017-08-06 08:18 UTC, DavidNorman commented
:)  sure thing

2017-08-08 16:24 UTC, DavidNorman commented
@blakehechtman @vrv 

Hi gues.  Do you think we could get this merged?  I have quite a few outstanding merge requests and it is making me nervous that our repo is drifting away from the public one.

2017-08-08 16:31 UTC, vrv commented
ping @rmlarsen

2017-08-08 19:01 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-08 22:12 UTC, merged