Increase docstring consistency
tensorflow/tensorflow pull request #11932
Opened 2017-08-01 07:27 UTC by taehoonlee

This PR considers the following six main items:
- Adjusting indents of markdown code blocks
- Adding language identifiers on markdown code blocks
- Replacing `Return` with `Returns` (The frequencies over all python codes: 2 vs. 3369)
- Replacing `Arguments` with `Args`
(`Args` is a consistent word over all python codes except `tensorflow/contrib/keras` and `tensorflow/python/layers`)
- In `tensorflow/python/framework/tensor_shape.py`, removing ` ``` ` for consistency on the file
- In `tensorflow/python/ops/array_ops.py` and `math_ops.py`, revising python code blocks to make them more concrete
  - I think it is better to replace `==>` with `#` because `==>` is not a python keyword.
  - For each operation, two styles (with and without `tf.`) are mixed. I think it is better to make them as `tf.operation` not `operation`.
  - For more concrete examples, I think it is better to write down real tensors not pseudo. (e.g.,`# 'x' is [1, 4]` is replaced by `x = tf.constant([1, 4])`.)

2017-08-02 20:19 UTC, MarkDaoust requested changes
I like these changes. Making things more consistent, and making examples more directly runnable is very nice.

Most of my attached comments are just farther consistency improvements.

But please revert the two spots where you changed the code at the same time.

Thanks.

2017-08-02 20:19 UTC, MarkDaoust commented on tensorflow/python/layers/base.py
>      >>> _unique_layer_name('dense')
In the rest of the examples we have no carets, and the result in an inline comment.

You could do the same thing here.

2017-08-03 14:25 UTC, taehoonlee commented
I agree with the feedback, thank you @MarkDaoust! I reflected all the comments.

2017-08-03 16:51 UTC, MarkDaoust commented
I am happy with this.

It will also fixes a bunch of inline examples that weren't rendering on the website.  

I've re-checked the PR. It is now a pure docs-only change. 
All my comments are resolved.
I've added a couple of tiny fixes to some broken examples.

(It could have been a little easier to review the update if you had just added the commit instead of squashing them together.)

Thanks!

2017-08-03 16:52 UTC, MarkDaoust approved these changes

2017-08-08 18:54 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-08 22:15 UTC, merged