[OpenCL] Fix allocator destruction race condition (#136)
tensorflow/tensorflow pull request #11968
Opened 2017-08-02 14:36 UTC by lukeiwanski

* [OpenCL] Changes SYCL Interface construction

Uses C++11 static initialisation to provide singleton instance, rather
than a mutex and pointer.

* [OpenCL] Adds const to SYCL Interface methods

* [OpenCL] Fix allocator destruction race condition

A Tensor's allocator must outlive it, however there is no easy way to
determine whether an Allocator has any Tensors still alive, and so we
cannot know when it is safe to destroy an allocator. The CPU allocator
gets round this by being deleted, so we adopt this convention here.

* [OpenCL] Reformats SYCL code

* [OpenCL] Fixes SYCL comments

* [OpenCL] Tidies SYCL device description

Adds check for whether the QueueInterface pointer is valid, as this
may not always be the case.

* [OpenCL] Adds nullptr checking to SYCL allocator

* [OpenCL] Adds const specifier to SYCL Interface

2017-08-07 17:41 UTC, rmlarsen commented on tensorflow/core/common_runtime/sycl/sycl_allocator.h
> +    delete sycl_device_;
Should this be protected by a mutex. Might it now race with some of the if (sycl_device_) usage above?

2017-08-07 17:41 UTC, rmlarsen commented on tensorflow/core/common_runtime/sycl/sycl_allocator.cc
> +SYCLAllocator::SYCLAllocator(Eigen::QueueInterface* queue)
In the future, please keep large formating changes and functional changes in separate PRs.

2017-08-07 17:51 UTC, lukeiwanski commented on tensorflow/core/common_runtime/sycl/sycl_allocator.cc
> +SYCLAllocator::SYCLAllocator(Eigen::QueueInterface* queue)
Ok sorry :)

2017-08-07 19:56 UTC, lukeiwanski commented on tensorflow/core/common_runtime/sycl/sycl_allocator.h
> +    delete sycl_device_;
Fixed in d75b94f3e42eb88c4f0428499be11cce13abe87a

2017-08-07 22:49 UTC, rmlarsen requested changes

2017-08-07 22:49 UTC, rmlarsen commented on tensorflow/core/common_runtime/sycl/sycl_allocator.h
> +  Eigen::SyclDevice* sycl_device_;  // owned
Move down and decorate with GUARADED_BY(mu_) ?

2017-08-07 22:49 UTC, rmlarsen commented on tensorflow/core/common_runtime/sycl/sycl_allocator.h
> +      mutex_lock lock(mu_);
This only helps if all the reads and uses of sycl_device_ are guarded by the mutex. For example 

Thread 1 calls, e.g., Synchronize, reads non-zero sycl_device_ in  line 40.
Thread 2 calls ClearSYCLDevice, deletes the object, sets sycl_device_ = nullptr;
Thread 1 Tries to call sycl_device_->synchronize()
Boom!

I'm not sure if this is a scenario that we need to guard against?

2017-08-08 20:08 UTC, lukeiwanski commented
Thanks for the feedback we will apply it ASAP

2017-08-09 14:38 UTC, lukeiwanski commented on tensorflow/core/common_runtime/sycl/sycl_allocator.h
> +      mutex_lock lock(mu_);
Fixed in: 8070cad

2017-08-09 14:38 UTC, lukeiwanski commented on tensorflow/core/common_runtime/sycl/sycl_allocator.h
> +  Eigen::SyclDevice* sycl_device_;  // owned
Fixed in 8070cad

2017-08-09 15:49 UTC, rmlarsen approved these changes

2017-08-09 15:49 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-09 17:07 UTC, merged