Implement CRF decode (Viterbi decode) for tensors
tensorflow/tensorflow pull request #12056
Opened 2017-08-05 18:56 UTC by betterenvi

Currently, Tensorflow doesn't support CRF decoding (Viterbi decode) for tensors. Although `tf.contrib.crf.viterbi_decode` function can do CRF decoding, it can only be used at test time, since it accepts Numpy arrays as inputs.

Implementing CRF decoding for tensors benefits us a lot, as this make our model more portable (e.g. we can freeze model, save it to a `.pb` file and then load it in `Golang` in test time.)

This PR implements CRF decoding for tensors and adds test code for it.

2017-08-05 19:04 UTC, betterenvi commented
I signed it!

2017-08-07 17:12 UTC, rmlarsen commented
@drpngx do you feel like reviewing this?

2017-08-07 17:29 UTC, drpngx requested changes
Nice! I haven't looked at the logic yet, but here are some comments.

2017-08-07 17:29 UTC, drpngx commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +      '''This is a function for numpy arrays.
Use double quotes for consistency.

Here and  below, please backtick symbols, e..g `[B, T, num_tags]`.

2017-08-07 17:29 UTC, drpngx commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +        potentials: [B, T, num_tags]
We need more text

2017-08-07 17:29 UTC, drpngx commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    # np.random.seed(1)
I would suggest leaving that in. It's easier to debug if the tests are deterministic.

2017-08-07 17:29 UTC, drpngx commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    # decode using numpy version.
Here and below: capitalize. ("Decode").

2017-08-07 17:29 UTC, drpngx commented on tensorflow/contrib/crf/python/ops/crf.py
> +    "viterbi_decode", "crf_decode", "CrfDecodeForwardRnnCell",
I think the naming scheme is a bit confusing. There's already a `viterbi_decode` that appears to be working on numpy data structures. In any case, I think we should update the top comment of the module to explain the interface better.

2017-08-07 17:29 UTC, drpngx commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    def np_crf_decode(potentials, transition_params, seq_lens):
Can we check against `viterbi_decode`?

2017-08-07 17:29 UTC, drpngx commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    def calc_accuracy(pred_tags, gold_tags, seq_lens):
That's fine. Usually, I like to have a toy, deterministic example that can be worked out by hand. Would you mind adding that?

2017-08-07 23:24 UTC, betterenvi commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    def np_crf_decode(potentials, transition_params, seq_lens):
I think it's fine. If `viterbi_decode` has been tested (and is correct) and tensor version has same result with it, we know tensor version is correct too.

2017-08-07 23:29 UTC, betterenvi commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    def calc_accuracy(pred_tags, gold_tags, seq_lens):
Then do I need to remove current example? Or just adding another one?

2017-08-07 23:33 UTC, betterenvi commented on tensorflow/contrib/crf/python/ops/crf.py
> +    "viterbi_decode", "crf_decode", "CrfDecodeForwardRnnCell",
Sure, I will do it soon.

2017-08-07 23:57 UTC, betterenvi commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +      '''This is a function for numpy arrays.
Fixed.

2017-08-07 23:58 UTC, betterenvi commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    # decode using numpy version.
Fixed.

2017-08-07 23:58 UTC, betterenvi commented on tensorflow/contrib/crf/python/ops/crf.py
> +    "viterbi_decode", "crf_decode", "CrfDecodeForwardRnnCell",
I have updated the top comment.

2017-08-07 23:59 UTC, betterenvi commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    # np.random.seed(1)
Fixed.

2017-08-08 00:00 UTC, betterenvi commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +        potentials: [B, T, num_tags]
Added.

2017-08-08 01:44 UTC, drpngx commented
Let me know when it's ready for review again. Thanks!

2017-08-08 02:16 UTC, betterenvi commented
@drpngx I had made some new changes according to your review comment. You may start review again whenever you're free. Thanks!

2017-08-09 13:51 UTC, betterenvi commented on tensorflow/contrib/crf/python/kernel_tests/crf_test.py
> +    def calc_accuracy(pred_tags, gold_tags, seq_lens):
Have added a deterministic example.

2017-08-09 13:56 UTC, betterenvi commented
@drpngx 

I have removed the non-deterministic example and added a deterministic one. In my test, `crf_decode` has passed this test.

By the way, `crf_decode` also has passed the previous non-deterministic example.

2017-08-11 00:33 UTC, drpngx approved these changes
Nice, thanks for adding that feature!

2017-08-11 00:33 UTC, drpngx commented
Jenkins, test this please.

2017-08-11 00:43 UTC, rmlarsen commented
Cool! Thanks for getting this reviewed so quickly @drpngx !

2017-08-11 03:31 UTC, merged