Update head.py
tensorflow/tensorflow pull request #12100
Opened 2017-08-08 07:01 UTC by alanyee

Replace scalar_summary for tf.summary.scalar

2017-08-08 18:21 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-08 18:21 UTC, rmlarsen approved these changes

2017-08-08 18:29 UTC, alanyee commented
#11159

2017-08-08 19:59 UTC, rmlarsen requested changes

2017-08-08 19:59 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/estimators/head.py
> -from tensorflow.python.ops import control_flow_ops
Oops! It looks like this import is still needed.

2017-08-08 20:40 UTC, alanyee commented on tensorflow/contrib/learn/python/learn/estimators/head.py
> -from tensorflow.python.ops import control_flow_ops
That's interesting. Why is it still needed?

2017-08-08 21:04 UTC, alanyee commented on tensorflow/contrib/learn/python/learn/estimators/head.py
> -from tensorflow.python.ops import control_flow_ops
Oh wait, never mind. I see that control_flow_ops is actually been getting called elsewhere in the code. I must have been looking at the different code file when I ran my search.

2017-08-08 21:09 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-09 00:55 UTC, rmlarsen commented
@alanyee lease address the remaining test failures in:

https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/6219/consoleFull

2017-08-09 23:15 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-10 15:38 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-08-10 15:38 UTC, rmlarsen submitted a review, later dismissed

2017-08-10 16:31 UTC, rmlarsen commented
@alanyee @ispirmustafa It looks like there are some non-trivial changes in the tags causing a failure in the unit tests:

======================================================================
FAIL: testBinaryClassificationEval (__main__.BinaryClassificationHeadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head_test.py", line 814, in testBinaryClassificationEval
    _assert_summary_tags(self, ["loss"])
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head_test.py", line 90, in _assert_summary_tags
    test_case.assertItemsEqual(expected_tags or [], actual_tags)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'loss'
First has 0, Second has 1:  u'binary_logistic_head/loss'

2017-08-10 16:46 UTC, alanyee commented
Ah, I have been trying to get around that problem which has occurred for another PR: 
```----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head_test.py", line 1444, in testMultiClassWithLabelKeysEvalAccuracy1
    _assert_summary_tags(self, ["loss"])
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace/bazel-out/local-opt/bin/tensorflow/contrib/learn/head_test.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/estimators/head_test.py", line 90, in _assert_summary_tags
    test_case.assertItemsEqual(expected_tags or [], actual_tags)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  'loss'
First has 0, Second has 1:  u'multi_class_head/loss'
```

The problem is essentially that the training and eval losses show up in different graphs which is why the deprecated API was used in the first place.

2017-08-10 17:02 UTC, ispirmustafa commented
Yes we intentionally keep deprecated summary API in head.py under contrib.
The heads we moved to core (python/estimator/canned/head.py) we use the new summary API.
Closing this since we'll not change deprecated api usages in contrib version of head.

2017-08-10 17:02 UTC, closed without merging

2017-08-10 17:16 UTC, alanyee commented
@ispirmustafa okay but i wanted to test out one more change to see if it would work