Add focal_loss
tensorflow/tensorflow pull request #12257
Opened 2017-08-14 04:48 UTC by Kongsea

Add a new loss function, focal_loss, which was descried in [this paper](https://arxiv.org/pdf/1708.02002.pdf).

2017-08-21 20:40 UTC, fchollet commented
This PR adds a new loss in core TF, `focal_loss`, which was described in an unreviewed paper that was released on Arxiv on August 7, two weeks ago.

I believe we should not add to core TF (in near-real time) every new idea that gets pushed to Arxiv. All code in core TF needs to be maintained in the long-term: adding new code has a cost, which gets integrated over time. Until it is demonstrated that a given feature is useful, we should not add it to core TF.

2017-08-21 22:43 UTC, martinwicke commented
Can you add this to contrib (contrib/losses) instead?

2017-08-22 01:11 UTC, Kongsea commented
OK, I will move it to contrib.

2017-08-22 14:27 UTC, mrlzla commented
Is this function working correct?
I have constant loss all the train time.

2017-09-17 02:26 UTC, drpngx commented
@Kongsea any luck with the move to contrib?

2017-09-18 01:54 UTC, Kongsea commented
@drpngx I have moved it to contrib. Please check it. Thank you.

2017-09-18 18:11 UTC, drpngx commented
There has been a change, I think you need to pull rebase and push again. Thanks.

2017-09-19 02:07 UTC, Kongsea commented
Now it seems OK. Please check it again.

2017-09-20 00:08 UTC, drpngx commented
Jenkins, test this please.

2017-09-25 06:35 UTC, CasiaFan commented
Based on the definition of Pt in paper, should the `labels` be added to this [equation](https://github.com/tensorflow/tensorflow/pull/12257/files#diff-01ec5a7b62cbe21e7fda63c7a92947e6R716)? @Kongsea

2017-09-25 09:25 UTC, CasiaFan commented
Based on the definition of cross-entropy, should the `labels` be added to this [equation](https://github.com/tensorflow/tensorflow/pull/12257/files#diff-01ec5a7b62cbe21e7fda63c7a92947e6R716)? otherwise, when alpha=0, gamma=1, the FL value is different from what tf.nn.softmax_cross_entropy returns.

2017-09-25 21:02 UTC, sb2nov commented
@vrv please review

2017-09-25 21:02 UTC, sb2nov commented
Jenkins, test this please.

2017-09-25 21:34 UTC, vrv commented
Adding gpapan@ who knows about this area, or feel free to re-assign it to someone who knows it well (I don't know it well enough).

2017-11-07 19:56 UTC, martinwicke commented
@gpapan are you able to review this? Let me know if not.

2017-12-12 18:32 UTC, martinwicke commented
CLA confused by me.

2017-12-27 02:31 UTC, drpngx commented
@martinwicke care to suggest an alternative reviewer perhaps? It looks like @gpapan is not available.

2018-01-17 13:02 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-01-17 22:39 UTC, alextp requested changes

2018-01-17 22:39 UTC, alextp commented on tensorflow/contrib/losses/python/losses/loss_ops.py
> +def focal_loss(predictions, labels, gamma=2, alpha=1, weights=1.0,
The arguments to losses should be labels,predictions instead of predictions,labels

2018-01-17 22:39 UTC, alextp commented on tensorflow/contrib/losses/python/losses/loss_ops.py
> +    labels: The ground truth output tensor, same dimensions as 'predictions'.
Should labels be [0, 1], [-1, 1]? Floating points? Integers?

2018-02-06 07:40 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-13 21:51 UTC, bhack commented
Any news?

2018-03-28 12:36 UTC, bhack commented
@tensorflowbutler Can you label nagging issue as nagging?

2018-03-29 02:21 UTC, closed without merging