Implement BiasAddGradHelper.
tensorflow/tensorflow pull request #12448
Opened 2017-08-21 11:57 UTC by bpiel

Registers the BiasAddGrad op as the gradient for BiasAdd by implementing BiasAddGradHelper.

Unlike the other tested ops in nn_grad_tests.cc, BiasAdd takes two arguments. The test I added does test both arguments, but not simultaneously. Not sure if that's acceptable. Guidance appreciated.

This is only my second PR to TensorFlow. When giving feedback, please assume that I barely know what I'm doing.

2017-08-23 02:30 UTC, asimshankar commented
Thanks for the PR
@suharshs : Mind taking a look?

2017-08-23 19:31 UTC, suharshs requested changes
Thanks for the PR! Just a couple of changes.

2017-08-23 19:31 UTC, suharshs commented on tensorflow/cc/gradients/nn_grad_test.cc
> +  RunTest(x1, shape, y1, shape);
You can create another overload for RunTest that takes multiple "x_shapes" like here in array_grad_test: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/gradients/array_grad_test.cc#L44

This should allow you to just specify shapes for the inputs and run one RunTest. Here is an example of a test that does that: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/gradients/array_grad_test.cc#L56

2017-08-23 19:31 UTC, suharshs commented on tensorflow/cc/gradients/nn_grad.cc
> +  auto dx_1 = BiasAddGrad(scope, grad_inputs[0], input_attrs);
I think the BiasAddGrad should happen after line 105

2017-08-23 20:43 UTC, bpiel commented
@suharshs back to you

2017-08-23 20:46 UTC, suharshs requested changes
Looks good after this minor change.

2017-08-23 20:46 UTC, suharshs commented on tensorflow/cc/gradients/nn_grad_test.cc
> +    EXPECT_LT(max_error, 1e-3);
Super minor: Lets make this 1e-4 to match the rest of the file. The array grads were 1e-3 because of some issue IIRC.

2017-08-23 20:50 UTC, suharshs approved these changes

2017-08-24 01:55 UTC, jhseu commented
Jenkins, test this please

2017-08-24 04:24 UTC, merged