Implements safe casting of to_<dtypes>() (#12235)
tensorflow/tensorflow pull request #12550
Opened 2017-08-24 07:55 UTC by Edwin222

* saturate_cast() supports SparseTensor

* to_float(), to_double(), to_int32(), to_int36(), to_bfloat16()
supports safe casting

2017-09-17 18:18 UTC, drpngx commented
@ebrevdo is working on sparse support. Any opinion here?

2017-09-27 18:15 UTC, sb2nov commented
@ebrevdo ping

2017-11-07 20:13 UTC, martinwicke commented
@ebrevdo can you take a look?

2017-11-07 22:40 UTC, ebrevdo requested changes
all the changes need unit tests for safe mode.

also the new sparsetensor branch needs to be tested.

2017-11-07 22:40 UTC, ebrevdo commented on tensorflow/python/ops/math_ops.py
> +    value: A `Tensor` or 'SparseTensor'.
nit: `SparseTensor` (backticks)

2017-11-07 22:40 UTC, ebrevdo commented on tensorflow/python/ops/math_ops.py
> +    mode: "safe"/"unsafe" mode setting
all these functions need more details about what safe and unsafe mean.

2017-11-07 22:40 UTC, ebrevdo commented on tensorflow/python/ops/math_ops.py
> +    return saturate_cast(x,dtypes.float64, name=name)
nit: space after x; more generally please review your python code throughout for spacing and other small nits.

2017-12-12 18:46 UTC, martinwicke commented
@Edwin222 any news? I'll mark this as stalled.

2018-01-17 18:30 UTC, drpngx commented
Closing for now. Feel free to reopen when you're ready.

2018-01-17 18:30 UTC, closed without merging