Safely read content from InputStream
tensorflow/tensorflow pull request #12643
Opened 2017-08-28 06:06 UTC by resec

Changed to use `ByteArrayOutputStream` on converting `InputStream` into `byte[]`, instead of relying on [`InputStream.available()`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#available--).

The old way may cause problem in cases like reading from buffered input stream or a network stream.

2017-09-06 00:27 UTC, asimshankar requested changes
Thanks for the PR. Have some questions about peak memory usage.

2017-09-06 00:46 UTC, resec commented on tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java
> +    byte[] graphDef = baos.toByteArray();
Thanks, it make sense. Let me rearrange the method calling.
Change the `loadGraph` to take `byte[]` and then in each constructor, build up the byte array in their own way.

2017-09-06 01:51 UTC, resec commented
@asimshankar Hi, I updated as said in comment, also add a check to decide the byte array output stream init size. Please help reviewing the change again, thanks.

2017-09-07 21:27 UTC, yifeif commented
@resec could you resolve the conflicts? Thank you!

2017-09-07 21:44 UTC, asimshankar approved these changes
Thanks! The change looks good, though I guess conflicts need to be resolved.

2017-09-08 00:53 UTC, resec commented
@asimshankar conflict resolved, thanks.

2017-09-08 03:24 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-09-08 04:03 UTC, resec commented
fix io exception not caught, not sure if i can trigger jenkins, let me try.

@tensorflow-jenkins test this please

2017-09-08 04:12 UTC, resec commented
:( can not trigger full testing, please help to trigger the build again, thanks

2017-09-08 16:46 UTC, yifeif commented
Thanks @resec! @tensorflow-jenkins test this please.

2017-09-08 18:04 UTC, merged

2017-09-15 22:50 UTC, asimshankar commented on tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java
> +
I think we forgot to actually read the bytes into the `graphDef` array  here.
i.e., an:

`is.read(graphDef)`

is required?

2017-09-15 23:12 UTC, asimshankar commented on tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java
> +
Sent a fix in #13073

2017-09-18 00:59 UTC, resec commented
@asimshankar thanks for the fix :)