Update __init__.py
tensorflow/tensorflow pull request #12675
Opened 2017-08-29 07:02 UTC by alanyee

-Add Python formatting for TF website
-Refactor comment
-Import statements are shorter than 80 chars, so pylint should not need to be suppressed here
-Add python formatting to correct website formatting away newlines

2017-09-02 06:45 UTC, martinwicke requested changes

2017-09-02 06:45 UTC, martinwicke commented on tensorflow/contrib/deprecated/__init__.py
> +clarity of the TensorFlow API. We however, also took the opportunity to make an
You either need another comma before 'however', or you revert this line. I'd go with the old order.

2017-09-02 06:45 UTC, martinwicke commented on tensorflow/contrib/deprecated/__init__.py
> +This behavior greatly complicates the reusability of the code that would add
reusability cannot be made more complicated. Reusing things can be. I think the old phrasing is better.

2017-09-02 06:45 UTC, martinwicke commented on tensorflow/contrib/deprecated/__init__.py
> +need to pass in a namescope, manually, to that function to create deduplicated
if you want to make the nature of "name scope" clearer, use `name_scope`.

2017-09-02 06:45 UTC, martinwicke commented on tensorflow/contrib/deprecated/__init__.py
> +need to pass in a namescope, manually, to that function to create deduplicated
Or even better: `tf.name_scope`.

2017-09-15 02:37 UTC, alanyee commented
@martinwicke does the commit look good now?

2017-09-17 18:44 UTC, drpngx commented
Jenkins, test this please.

@martinwicke any thoughts on the new version?

2017-09-25 23:13 UTC, alanyee commented
@drpngx @martinwicke any thoughts on the changes?

2017-09-26 04:04 UTC, martinwicke approved these changes

2017-09-26 04:04 UTC, martinwicke commented
Jenkins, test this please.

2017-09-26 16:58 UTC, drpngx commented
Hitting the permission denied. @gunan FYI it looks like we are seeing more of [this](https://ci.tensorflow.org/job/tensorflow-pull-requests-makefile/10811/) recently.

Jenkins, test this please.

2017-09-26 22:57 UTC, merged