Add uint16 support for tf.decode_raw
tensorflow/tensorflow pull request #12719
Opened 2017-08-31 03:59 UTC by yongtang

This fix tries to address the request raised in #10124 where uint16 support for tf.decode_raw is needed. tf.decode_raw already support half, float32, float64, int8, int16, int32, int64, uint8.

And uint16 was not supported yet.

This fix adds uint16 support for tf.decode_raw.

This fix fixes #10124.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-09-02 06:14 UTC, martinwicke commented
Jenkins, test this please.

2017-09-02 21:19 UTC, yongtang commented
The previously Jenkins test failure `tfexample_decoder_test` was caused by the fact that `decode_raw` support `uint16` now.

The PR has been updated. Now Jenkins tests should pass.

2017-09-07 23:00 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-09-07 23:57 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-09-11 18:23 UTC, rmlarsen requested changes

2017-09-11 18:23 UTC, rmlarsen commented on tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py
> +    # decode_raw support uint16 now so ValueError will be thrown instead.
Can you also add a unit test that tests that decode_raw can now successfully decode uint16?

2017-09-11 18:23 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-09-11 21:30 UTC, yongtang commented
@rmlarsen Thanks for the review. The PR has been updated with unit tests added. Please take a look.

2017-09-11 23:19 UTC, rmlarsen approved these changes

2017-09-11 23:20 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-09-12 16:55 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-09-13 17:03 UTC, merged