Add implementation of `conv1d_transpose`
tensorflow/tensorflow pull request #13105
Opened 2017-09-17 22:29 UTC by yongtang

This fix tries to address the issue raised in #8729 by providing the implementation of `conv1d_transpose`.

This fix fixes #8729.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-09-26 00:21 UTC, sb2nov commented
Jenkins, test this please.

2017-09-28 23:42 UTC, sb2nov commented
@yongtang can you look at the test failure

2017-09-29 14:12 UTC, yongtang commented
Thanks @sb2nov. The failure was caused by `xrange` in python 3. The failure has been fixed and the PR has been updated now. Please take a look and let me know if there are any other issues.

2017-09-29 20:39 UTC, sb2nov commented
Jenkins, test this please.

2017-09-30 03:31 UTC, yongtang commented
From the Jenkins output the Python 3 build has been fixed. The “Linux CPU Test Makefile” might be caused by the network issue. I think a rerun will fix it.

2017-10-02 14:23 UTC, alextp commented
Jenkins, test this please.

2017-10-02 14:25 UTC, alextp requested changes

2017-10-02 14:25 UTC, alextp commented on tensorflow/python/ops/nn_ops.py
> +      `[batch, in_channels, in_width]` for `NCHW` data format.
I'm confused; if it's conv1d, why is there h and w?

2017-11-06 21:13 UTC, yongtang commented
Thanks @alextp for the review and sorry for the late reply as I missed the GitHub previously notification. Indeed `NHWC` and `NCHW` is not appropriate for 1d situations. I have rebased and updated the PR so that `NWC` and `NCW` are used instead.

Please take a look and let me know if there are any issues.

2017-11-06 21:32 UTC, alextp requested changes
First, why the diff in fast_tensor_util.cpp? Is that a merger artifact?

Second, let's add an import of this symbol to tf.contrib.nn ; see how it's done in nth_element: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/nn/__init__.py#L35

This way users can access this function through the contrib module for at least one release before we graduate it to tf.nn.

2017-11-06 22:02 UTC, yongtang commented
Thanks @alextp for the help.

Not sure why `fast_tensor_util.cpp` was included in the PR as the filename is actually in `.gitignore`. I have removed the file from PR manually.

The conv1d_transpose has also been imported in `tf.contrib.nn` and exposed. Please take a look.

2017-11-06 22:05 UTC, alextp approved these changes

2017-11-06 22:06 UTC, alextp commented
Jenkins, test this please.

2017-11-09 06:47 UTC, martinwicke commented
Jenkins, test this please.

2017-11-09 16:58 UTC, martinwicke commented
Failures are unrelated.

2017-11-09 16:58 UTC, merged