Non-scalar Multinomial draws
tensorflow/tensorflow pull request #13189
Opened 2017-09-20 15:34 UTC by jinze1994

This PR tries to fix the issue in [#12804](https://github.com/tensorflow/tensorflow/pull/13178) where supports total_count to be a non-scalar tensor.

I have already test this feature in local, but I haven't found any file to add test code, please let me know if I need to add any test code.

2017-09-22 16:49 UTC, jinze1994 commented
@jvdillon Could you please review my code? Thank you very much~

2017-09-22 17:35 UTC, jvdillon commented
Looking now...

2017-09-22 17:41 UTC, jvdillon commented
Overall, looks good--just a few nitpicks.   I had actually hoped we could change the underlying C++ sampler, but I suppose this is a reasonable stop-gap measure.  I'll approve once the minor style issues have been addressed.

2017-09-22 17:41 UTC, jvdillon requested changes

2017-09-22 17:41 UTC, jvdillon commented on tensorflow/python/ops/distributions/multinomial.py
> +        n_draws[..., None], dtype=self.logits.dtype) * self.logits
Please use array_ops.newaxis rather than `None`

2017-09-22 17:41 UTC, jvdillon commented on tensorflow/python/ops/distributions/multinomial.py
> +    flat_logits = array_ops.reshape(logits, [-1, k]) # [B1*B2*...*Bm, k]
Please use kwarg for literals, ie, 
flat_logits = array_ops.reshape(logits, shape=[-1, k]) # [B1*B2*...*Bm, k]

2017-09-23 03:01 UTC, jinze1994 commented
@jvdillon 

Thank you for getting this reviewed, I have modified the code according to your suggestion. By the way, I am glad to try to help changing the underlying sampler in the future.

2017-09-26 00:21 UTC, sb2nov commented
@jvdillon is this good to go?

2017-09-27 18:37 UTC, jvdillon approved these changes

2017-09-27 18:39 UTC, jvdillon commented
Sorry for my slowness to review.  Thank you for your contribution.  Please feel free to reach out to me regarding issues that come up in your improvement in the underlying multinomial sampler.  It can also be made much more efficient than it currently is.

2017-09-28 20:03 UTC, sb2nov commented
Jenkins, test this please.

2017-09-28 20:30 UTC, sb2nov commented
@jinze1994 there seems to be test failure with the change https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/6702/consoleFull

2017-10-05 01:34 UTC, jinze1994 commented
@jvdillon @sb2nov 

Sorry for my delay to handle the test failure. I think this test failure occurred because there were not enough sample time when check the covariance from sampling, which led to some deviation. And I fix it by augmenting the sample time.

As for improving in the underlying multinomial sampler, thanks for jvdillon's support first, but I am not sure if I have enough time to achieve that. If I have enough time in the future, I will create a new PR for modify the underlying sampler.

2017-10-05 17:06 UTC, jvdillon commented
Thanks again!  (Right, fixing the C++ sampler should definitely be a separate PR, when/if you get to it.)

2017-10-09 14:37 UTC, jinze1994 commented
@sb2nov @jvdillon 
My pleasure. So could you please test this PR again?

2017-10-12 16:27 UTC, jinze1994 commented
@jvdillon Hi bro~ Could you please test this PR again? Or is there anything I could do for this PR?

2017-10-12 16:59 UTC, sb2nov commented
Jenkins, test this please.

2017-10-12 17:55 UTC, jinze1994 commented
I noticed that there ware still some test failure, and I think that occurred because there were not enough sample times, because I passed the test locally most of time.

I have already augmented the sample times at the failure place. Please test it again? Sorry for having troubled you so much. Thank you very much. @sb2nov @jvdillon

2017-10-13 11:03 UTC, jinze1994 commented
@jvdillon @sb2nov 
I've already handled the test failure, could you please test it again? Thank you very much.

2017-10-17 23:04 UTC, jvdillon commented
Jenkins, test this please.

2017-10-25 22:25 UTC, jvdillon commented
How are things coming along? Anything I can help with?

2017-10-25 22:27 UTC, jvdillon reviewed
Assuming tests pass, this LGTM.

2017-10-25 22:31 UTC, vrv commented
@tensorflow-jenkins test this please

2017-10-26 12:46 UTC, jinze1994 commented
@jvdillon @vrv 
I haven't figured out the failure reason of those check above, but it seems not to be related with this PR.
So is there anything I can do to avoid it and modify?

2017-10-26 23:18 UTC, jvdillon commented
Breakages seem unrelated.

2017-10-30 06:22 UTC, jinze1994 commented
@jvdillon @vrv Is this good to merge?

2017-10-30 16:01 UTC, jvdillon commented
@vrv seems like the breakages are unrelated. Maybe kick off another run and see if they all pass this time?

2017-10-30 16:56 UTC, vrv commented
@tensorflow-jenkins test this please

2017-10-31 18:00 UTC, jinze1994 commented
@jvdillon 
Sorry for that there are still some test failure, but I don't know how to handle that.
Should I merge with the current master branch to repair those BUILD failure?

2017-11-01 06:42 UTC, gunan commented
Jenkins, test this please.

2017-11-01 06:53 UTC, gunan commented
Jenkins, test this please.

2017-11-01 15:53 UTC, jinze1994 commented
@jvdillon @vrv 
I have rebased this PR with current tensorflow master, and it should solve the BUILD failures. So please test it again. Thank you.

2017-11-01 18:05 UTC, gunan commented
Jenkins, test this please.

2017-11-02 01:23 UTC, jinze1994 commented
Those failures seem unrelated with this PR.

2017-11-02 06:15 UTC, merged