Add `tfexample_decoder.Image` support for `shape_keys`
tensorflow/tensorflow pull request #13400
Opened 2017-09-30 02:50 UTC by flacjacket

Allow for the shape of an image decoded with the
`tfexample_decoder.Image` decoder to be determined by fields in the
serialized example being decoded. The functionality mirrors the use of
the `shape_keys` kwarg of the `Tensor` decoder.

2017-09-30 02:51 UTC, flacjacket commented
I signed it!

2017-09-30 03:14 UTC, sb2nov commented
Jenkins, test this please

2017-10-02 17:41 UTC, rmlarsen requested changes

2017-10-02 17:41 UTC, rmlarsen commented on tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py
> +        'image/channels': self._EncodedInt64Feature(shape_array[2:3]),
For a 2D image, should channels be left out, i.e. implied to be 1?

2017-10-02 17:41 UTC, rmlarsen commented on tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py
> +      self.assertEqual(tf_decoded_image.get_shape().ndims, 3)
Test that you can decode a 2d image to a 2d tensor.

2017-10-13 16:58 UTC, rmlarsen commented
@flacjacket any update on this?

2017-11-08 00:54 UTC, martinwicke commented
@flacjacket any updates?

2017-11-08 12:42 UTC, flacjacket commented
@rmlarsen Sorry for taking so long to get back to this. I have updated the tests to include 2d image tensors. However, it looks like the TF Test Suite check has been stalled overnight.

2017-11-14 00:10 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-11-15 22:16 UTC, rmlarsen commented
@flacjacket Could you take a look at the failing tests:

FAIL: //tensorflow/contrib/slim/python/slim/data:tfexample_decoder_test (see /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/testlogs/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test/test.log).
INFO: From Testing //tensorflow/contrib/slim/python/slim/data:tfexample_decoder_test:
==================== Test output for //tensorflow/contrib/slim/python/slim/data:tfexample_decoder_test:
2017-11-14 00:39:20.997015: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
............E.....EE..........
======================================================================
ERROR: testDecodeExampleWithNoShapeInfo (__main__.TFExampleDecoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py", line 169, in testDecodeExampleWithNoShapeInfo
    image_format='jpeg', image_shape=image_shape)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py", line 93, in GenerateImage
    num_pixels = image_shape[0] * image_shape[1] * image_shape[2]
IndexError: tuple index out of range

======================================================================
ERROR: testDecodeExampleWithShapeKeys (__main__.TFExampleDecoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py", line 191, in testDecodeExampleWithShapeKeys
    image_format='jpeg', image_shape=image_shape)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py", line 93, in GenerateImage
    num_pixels = image_shape[0] * image_shape[1] * image_shape[2]
IndexError: tuple index out of range

======================================================================
ERROR: testDecodeExampleWithShapeKeysList (__main__.TFExampleDecoderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py", line 208, in testDecodeExampleWithShapeKeysList
    image_format='jpeg', image_shape=image_shape)
  File "/var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/data/tfexample_decoder_test.py", line 93, in GenerateImage
    num_pixels = image_shape[0] * image_shape[1] * image_shape[2]
IndexError: tuple index out of range

----------------------------------------------------------------------
Ran 30 tests in 3.924s

FAILED (errors=3)
================================================================================

2017-12-13 00:51 UTC, martinwicke commented
Ping @flacjacket

2017-12-27 02:02 UTC, drpngx commented
@flacjacket any luck with this?

2018-01-17 13:02 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-01-17 18:05 UTC, drpngx commented
Closing for now. Please re-open once you have an update.

2018-01-17 18:05 UTC, closed without merging