Updating the install sources file with a supported configs page.
tensorflow/tensorflow pull request #13450
Opened 2017-10-02 19:35 UTC by av8ramit

This is an attempt to fix b/28192343. It will also help with issues like https://github.com/tensorflow/tensorflow/issues/13377. I'm completely open to all criticism with moving it somewhere else and formatting.

2017-10-02 21:40 UTC, frankchn commented
Jenkins, test this please.

2017-10-02 23:06 UTC, gunan requested changes
@jugglerix This change is similar to a pending change you have internally.

2017-10-02 23:06 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>GCC:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
This should be "Compiler"

2017-10-02 23:06 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>GCC:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
"Compiler" instead of "GCC"

2017-10-02 23:06 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>GCC:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
Compiler instead of GCC

2017-10-02 23:06 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +## Supported source configurations
Let's say "Tested"
we may be supporting more than what is listed here.

2017-10-03 00:08 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +## Supported source configurations
Done.

2017-10-03 00:08 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>GCC:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
Done.

2017-10-03 00:08 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>GCC:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
Done.

2017-10-03 00:08 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>GCC:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
Done.

2017-10-03 06:17 UTC, gunan requested changes

2017-10-03 06:17 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>Compiler:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
Also, it is vague now in this table which one of bazel or cmake is used in the builds. In the table headers, let's replace "Bazel/Cmake" with "Build tools" and in the table itself, let's have the name of the tool included  with the version.
For example, instead of 0.4.5, we will have Bazel 0.4.5

2017-10-03 06:17 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.3.0</td><td>CPU</td><td>3.5-3.6</td><td>MSVC 2015 update 3</td><td>Cmake</td><td>N/A</td><td>N/A</td></tr>
Cmake v3.6.3 throughout the table

2017-10-03 06:17 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>Compiler:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
replace Bazel/cmake with "Build tools"

2017-10-04 21:27 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>Compiler:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
Done.

2017-10-04 21:27 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><th>Version:</th><th>CPU/GPU:</th><th>Python Version:</th><th>Compiler:</th><th>Bazel/Cmake:</th><th>cuDNN:</th><th>CUDA:</th></tr>
Done.

2017-10-04 21:28 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.3.0</td><td>CPU</td><td>3.5-3.6</td><td>MSVC 2015 update 3</td><td>Cmake</td><td>N/A</td><td>N/A</td></tr>
Done.

2017-10-04 22:17 UTC, gunan approved these changes

2017-10-04 22:17 UTC, merged

2025-01-12 04:29 UTC, Scutua approved these changes