Add RDMA verbs configuration
tensorflow/tensorflow pull request #13564
Opened 2017-10-08 10:12 UTC by dariavel

RDAM configuration is now possible with the following environment variables:  RDMA_DEVICE, RDMA_DEVICE_PORT, RDMA_GID_INDEX,  RDMA_PKEY, RDMA_QUEUE_DEPTH, RDMA_TIMEOUT, RDMA_RETRY_CNT, RDMA_SL, RDMA_MTU and RDMA_TRAFFIC_CLASS.

2017-10-08 10:19 UTC, dariavel commented
I signed it!

Regards,
Daria Velikovsky
SW Engineer, SW
Mellanox Technologies
Office: +972-747238531, Mobile: +972-543271181
www.mellanox.com<http://www.mellanox.com/>
Follow us on Facebook<http://www.facebook.com/pages/Mellanox-Technologies/223164879116> and Twitter<http://twitter.com/mellanoxtech>



________________________________
From: googlebot <notifications@github.com>
Sent: Sunday, October 8, 2017 1:14:37 PM
To: tensorflow/tensorflow
Cc: Daria Velikovsky; Author
Subject: Re: [tensorflow/tensorflow] Add RDMA verbs configuration (#13564)


Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://cla.developers.google.com/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcla.developers.google.com%2F&data=02%7C01%7Cdaria%40mellanox.com%7Cdde0ef895b0b433d96db08d50e35631e%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C636430544819705169&sdata=bUEPhOQ0pFRZdDpqGsTyOedWyHRp2XwXd4xxO2qn7L4%3D&reserved=0> to sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

________________________________

  *   If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcla.developers.google.com%2Fclas&data=02%7C01%7Cdaria%40mellanox.com%7Cdde0ef895b0b433d96db08d50e35631e%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C636430544819705169&sdata=W5gEvaHw5IVa0%2B%2BlLDS6TnpAcSS%2B1h2IlmTpObi2Gg4%3D&reserved=0> and verify that your email is set on your git commits<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.github.com%2Farticles%2Fsetting-your-email-in-git%2F&data=02%7C01%7Cdaria%40mellanox.com%7Cdde0ef895b0b433d96db08d50e35631e%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C636430544819705169&sdata=0AI%2BD%2Flq2rq8i%2Bfq1BleXV1N1J77AkQeoChhTUCsucI%3D&reserved=0>.
  *   If your company signed a CLA, they designated a Point of Contact who decides which employees are authorized to participate. You may need to contact the Point of Contact for your company and ask to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the project maintainer to go/cla#troubleshoot.
  *   In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftensorflow%2Fpull%2F13564%23issuecomment-334996331&data=02%7C01%7Cdaria%40mellanox.com%7Cdde0ef895b0b433d96db08d50e35631e%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C636430544819705169&sdata=GhiLBFuURnprtcnDejVcQtB6CziJndVc9W98wsnD5tE%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAejJTdl2wKPls45idVNS7ZGsjLbzAonVks5sqKCNgaJpZM4Pxp_k&data=02%7C01%7Cdaria%40mellanox.com%7Cdde0ef895b0b433d96db08d50e35631e%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C636430544819705169&sdata=7i60CszubAt8mGvsonwvMaUnsUKxhHEEI7wJRFnRRLs%3D&reserved=0>.

2017-10-09 15:32 UTC, noaezra commented
I signed it!

2017-10-09 16:03 UTC, junshi15 commented
It looks good to me.

2017-10-10 06:27 UTC, dariavel commented
All the authors have signed the CLA.

2017-10-10 07:12 UTC, noaezra commented
I'm ok okay with my commits being contributed to this project.

2017-10-10 07:18 UTC, byronyi commented on tensorflow/contrib/verbs/rdma.cc
> +            [this, proto, buffer_size, key, in, step_id, key_with_step_id, is_dead, send_args, recv_args](const Status& s) mutable {
This line is way too long. Please wrap it to 80 columns.

2017-10-16 08:07 UTC, shamoya commented
Hi @poxvoculi @jhseu, 
Have you add the chance to take a look ?

2017-10-16 23:24 UTC, poxvoculi approved these changes

2017-10-16 23:24 UTC, poxvoculi commented on tensorflow/contrib/verbs/rdma.cc
> +  else {
Google style prefers:
} else {
  // set default device

2017-10-16 23:24 UTC, poxvoculi commented on tensorflow/contrib/verbs/rdma.cc
> +    CHECK(port_index != device_att.phys_port_cnt) << "No active ports";
This control flow is a little odd, with the return inside the for loop and below at line 215.  How about:
port_num = 0;  // line 181.
for (port_index = 1;...
   if (port_attr.state == IBV_PORT_ACTIVE) {
       CHECK_EQ(0, port_num) << "Multiple active ports";
        port_num = port_index;
    }
}
CHECK_GT(port_num, 0) << "No active ports";

2017-10-23 07:48 UTC, shamoya commented
Thanks @poxvoculi, can we merge this ?

2017-10-24 17:58 UTC, shamoya commented
@poxvoculi, we want to rearrange the commits of the PR (all of the commits are duplicated, probably something with the merges got mixed up). We will fix it tomorrow plz do not merge if you see this.

2017-10-24 20:26 UTC, drpngx requested changes
Block until refactor, as per comment.

2017-10-25 10:48 UTC, shamoya commented
@drpngx @poxvoculi @jhseu - We fixed the duplicated commits and now all looks good.
No change in code since @poxvoculi review.
Thanks @noaezra @dariavel for the great work.

2017-10-29 15:17 UTC, shamoya commented
@drpngx ?

2017-10-31 21:14 UTC, drpngx approved these changes

2017-10-31 21:14 UTC, drpngx commented
Sounds good, let's see if the test suite passes.

2017-10-31 22:20 UTC, drpngx commented
Could you pull rebase and push again? The different commits appear to be foiling the CLA bot.

2017-11-01 06:42 UTC, gunan commented
Jenkins, test this please.

2017-11-01 08:26 UTC, shamoya commented
Thanks @gunan @drpngx 
I guess the cla/google is fooled by - commits were authored by someone other than the pull request submitter ? 
If so, rebasing on top master on this PR will help ? 
Should we post a new PR with the changes ?

2017-11-01 17:39 UTC, drpngx commented
Yes rebase usually works

On Wed, Nov 1, 2017 at 1:28 AM, Ido Shamay <notifications@github.com> wrote:

> Thanks @gunan <https://github.com/gunan> @drpngx
> <https://github.com/drpngx>
> I guess the cla/google is fooled by - commits were authored by someone
> other than the pull request submitter ?
> If so, rebasing on top master on this PR will help ?
> Should we post a new PR with the changes ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/13564#issuecomment-341032108>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT_SbVAisThR5OH-VtlhVmFGqJEoS_E7ks5syCuzgaJpZM4Pxp_k>
> .
>

2017-11-02 05:43 UTC, gunan commented
Jenkins, test this please.

2017-11-02 05:43 UTC, gunan commented
Looks like all the authors did sign the CLA, but CLA bot is confused because of multiple commits from different authors. Once the tests pass, I can merge this PR.

2017-11-02 16:54 UTC, shamoya commented
@gunan , looks like there problem with the CI, not related to this patch.
Can we re-run the jenkins ?

2017-11-02 18:11 UTC, gunan commented
You are right. I think last night we ran out of daily quota on the backend, it should be fixed now.

2017-11-05 06:35 UTC, merged