Adding --verify_images to example image retrainer.
tensorflow/tensorflow pull request #13572
Opened 2017-10-08 18:08 UTC by ianmaddox

Adding --verify_images to allow soft checking of image files before bottleneck creation.
When enabled, invalid images are ignored with a warning instead of throwing an exception.

2017-10-09 14:00 UTC, caisq commented
@tensorflow-jenkins test this please

2017-11-07 23:45 UTC, petewarden requested changes
Sorry for the slow reply on this one. In general this is a great idea, and would make the script more usable. The dependency on PIL is a problem though. We don't require this library otherwise, and it's pretty heavyweight to install, especially on non-standard systems like the Pi: https://stackoverflow.com/questions/20176883/how-to-install-pil-with-jpeg-support-on-a-raspberry-pi

I'd be happy if you were able to replace this check using standard DecodeJpeg TF ops instead, since that wouldn't introduce a new dependency.

2017-12-12 18:48 UTC, martinwicke commented
@ianmaddox any updates? Marking as stalled for now.

2017-12-27 02:05 UTC, drpngx commented
@ianmaddox Feel free to reopen when you get a chance to take a look.

2017-12-27 02:05 UTC, closed without merging