Support reversing bool sequence.
tensorflow/tensorflow pull request #13719
Opened 2017-10-14 16:48 UTC by betterenvi

This PR tries to fix issue [#13717](https://github.com/tensorflow/tensorflow/issues/13717).

2017-10-14 18:57 UTC, caisq commented
@tensorflow-jenkins test this please

2017-10-14 21:19 UTC, ebrevdo requested changes

2017-10-14 21:19 UTC, ebrevdo commented on tensorflow/core/kernels/reverse_sequence_op.cc
> +TF_CALL_POD_TYPES(REGISTER_REVERSE_SEQUENCE_LEN);
just add
```
TF_CALL_bool(REGISTER_REVERSE_SEQUENCE_LEN)
```

here
etc.

there are other GPU pod types that you're not including in your declaration in register_types; i recommend reverting that change.

2017-10-14 21:19 UTC, ebrevdo commented on tensorflow/python/ops/array_grad.py
> +  if op.inputs[0].dtype.base_dtype == ops.dtypes.bool:
if op.get_attr("T") == dtypes.bool:
  ...

2017-10-14 21:19 UTC, ebrevdo commented on tensorflow/python/ops/array_grad.py
> +  if op.inputs[0].dtype.base_dtype == ops.dtypes.bool:
(though you don't really need to add this special case for the grad at al)

2017-10-15 03:09 UTC, betterenvi commented
@ebrevdo 
I had made some changes according to your comments.

2017-10-15 03:50 UTC, ebrevdo approved these changes
Thanks!

2017-10-15 16:30 UTC, caisq commented
@tensorflow-jenkins test this please

2017-10-15 17:25 UTC, merged