Update layers.py
tensorflow/tensorflow pull request #13829
Opened 2017-10-19 11:18 UTC by shreyneil

I have added a check on beta with reference to the following issue raised.
https://github.com/tensorflow/tensorflow/issues/11673

Please verify and get back.
Thank you.

I will add update the unit test cases to verify this patch.

2017-10-20 02:21 UTC, vrv approved these changes

2017-10-20 02:21 UTC, vrv commented
@tensorflow-jenkins test this please

2017-10-20 02:22 UTC, vrv commented
Please add the test as requested in the previous version of the CL, otherwise this looks great, thanks!

2017-10-20 19:38 UTC, shreyneil commented
https://github.com/tensorflow/tensorflow/pull/13864 contains the updated unit test case.

2017-10-21 17:15 UTC, vrv requested changes

2017-10-21 17:15 UTC, vrv commented on tensorflow/contrib/layers/python/layers/layers_test.py
> +class zero_debias_moving_mean(test.TestCase):
In this case, you can just add the test to the existing BatchNormTest suite, no need to add a new ones.

In general though, you can check the style of other class names in this file; one should use CamelCase test names here if you were adding a new class.

2017-10-21 17:15 UTC, vrv commented on tensorflow/contrib/layers/python/layers/layers_test.py
> +  def Error_in_tf.contrib.layers.batch_norm_when(self):
test names should start with 'test':

def testBatchNormCenterFalse

2017-10-21 17:15 UTC, vrv commented on tensorflow/contrib/layers/python/layers/layers_test.py
> +    import tensorflow as tf
In internal tests, you have to import the modules individually, you cannot import tensorflow here.  So you should use something like:

a = array_ops.placeholder(dtypes.float32, ...)

Take a look at the existing batch norm tests and use that as a guide for how to write the test where center=False

2017-10-25 21:25 UTC, vrv commented
It looks like you may be having trouble updating this PR to include all the changes  -- perhaps it makes sense to resend a new fresh PR with all of the requested changes (layers.py and layers_test.py change in the same PR).  Thanks!

2017-10-25 21:25 UTC, closed without merging