Initial SRU Implementation
tensorflow/tensorflow pull request #13978
Opened 2017-10-25 18:35 UTC by tjingrant

Hi, as per https://github.com/tensorflow/tensorflow/issues/13094, I'm submitting an initial PR for SRU implementation.

I intend to implement SRUBlock as well; but I have been distracted away by other high priority things until recently. So I will incrementally add the SRUBlock here as well.

In addition, it occurs to me that SRU only allows num_units equal to input_size. Can someone verify my interpretation? Otherwise we cannot perform equaiton 7 in the [paper](https://arxiv.org/pdf/1709.02755.pdf) because of dimension mismatch.

2017-10-28 05:29 UTC, ebrevdo requested changes
Could you look at the format of the simple lstm cell in core at master?  We recently converted it to use a build function, and it subclasses a special subclass of RNNCell.  It's constructor also takes a name= argument.  Could you modify the sru class to do the same?

2017-11-01 20:18 UTC, tjingrant commented
Just a reminder, quote from my original PR comment:

> In addition, it occurs to me that SRU only allows num_units equal to input_size. Can someone verify my interpretation? Otherwise we cannot perform equaiton 7 in the paper because of last-dimension size mismatch.

2017-11-07 21:47 UTC, tjingrant commented
@ebrevdo any update?

2017-11-07 22:07 UTC, ebrevdo commented on tensorflow/contrib/rnn/python/kernel_tests/core_rnn_cell_test.py
> +        g, _ = rnn_cell_impl.SRUCell(2, \
nit: don't use backslash here.

2017-11-07 22:10 UTC, ebrevdo requested changes

2017-11-07 22:10 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +    """Simple recurrent unit (SRU) with nunits cells."""
s/nunits/num_units/.

2017-11-07 22:10 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +    x_bar, f_intermediate, r_intermediate = \
nit:

```python
x_bar, f_intermediate, r_intermediate = (
  array_ops.split(...))
```

2017-11-07 22:10 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +    f_r = math_ops.sigmoid(nn_ops.bias_add(array_ops.concat([f_intermediate, \
ditto regarding backslashes

2017-11-07 22:10 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +    bias_initializer = self._bias_initializer or \
```python
... = (
  self._bais_initializer or ...)
```

2017-11-07 22:10 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +    self._num_units = num_units
set the input_spec to ensure inputs are matrices only.

2017-11-07 22:10 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +               bias_initializer=None):
add a name=None argument, see the LSTMCell in core for an example.

2017-11-08 21:09 UTC, tjingrant commented
@ebrevdo I've updated my code according to your comments.

2017-11-16 19:36 UTC, tjingrant commented
@ebrevdo any updates?

2017-12-06 22:30 UTC, tjingrant commented
@ebrevdo any update?

2017-12-06 23:04 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +    assert input_depth == self._num_units, "SRU requires unit_num == input_size"
raise a ValueError instead of asserting.

2017-12-07 00:33 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +    bias_initializer: (optional) The initializer to use for the bias.
name: ...

2017-12-07 00:33 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +     the given variables, an error is raised.
reorder args to match __init__'s signature.

2017-12-07 00:33 UTC, ebrevdo approved these changes
approval conditioned on fixes to nits.

2017-12-14 03:50 UTC, ebrevdo commented
@tjingrant quick ping on this.

2017-12-15 06:03 UTC, tjingrant commented
@ebrevdo should be good now.

2017-12-16 23:50 UTC, benoitsteiner commented
Jenkins, test this please

2017-12-17 01:00 UTC, merged

2017-12-17 16:44 UTC, ebrevdo commented
Thanks!

On Sat, Dec 16, 2017, 5:01 PM Benoit Steiner <notifications@github.com>
wrote:

> Merged #13978 <https://github.com/tensorflow/tensorflow/pull/13978>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/13978#event-1390926551>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABtimzytgw56Fzet3IEiWAUvQMnBDwAPks5tBGfRgaJpZM4QGdlg>
> .
>

2017-12-18 05:26 UTC, gunan commented
This PR introduces an API change. We will need to revert this and resubmit after an API review.

2017-12-18 21:11 UTC, asimshankar commented
@tjingrant : Could you add some more detail to the docstring, the current one liner seems a bit ... succinct :)

2017-12-18 21:32 UTC, tjingrant commented
@asimshankar yes, of course. But let's talk about it over here (https://github.com/tensorflow/tensorflow/pull/15436).

2017-12-18 21:36 UTC, ebrevdo commented on tensorflow/python/ops/rnn_cell_impl.py
> +class SRUCell(_LayerRNNCell):
ick!  this *is* an API change.  this should have gone into contrib!  i thought it had been moved since the test had been moved to contrib as well!

2017-12-18 21:36 UTC, ebrevdo commented
let's revert this and resubmit with the SRUCell going into tf.contrib.rnn (not just the test!)

2019-01-17 02:14 UTC, XiaoyuGuo123 commented
about this function 'tf.contrib.rnn.SRUCell(units)'   
How many states does the return value of this function call directly? I found it in debugging and it seems that there is only one state.
What should I do if I want to stack several layers of SRU?Because I don't understand that this function has only one return value. How does the internal state of c work when stacked on the SRU layers?