Feature Request: C++ gradient for LRN
tensorflow/tensorflow pull request #13987
Opened 2017-10-26 03:12 UTC by gdeer81

this resolves #13789 

Registers the `LRNGrad` op as the gradient for `LRN` by implementing `LRNGradHelper`

Single test case proves that everything was wired up correctly since I assume the `LRNGrad` code was thoroughly tested.

This is my first PR to TensorFlow. When giving feedback, please assume that I barely know what I'm doing.

2017-11-03 03:36 UTC, suharshs requested changes
Sorry for the delay. Looks good pending a couple minor comments.

2017-11-03 03:36 UTC, suharshs commented on tensorflow/cc/gradients/nn_grad_test.cc
> +  TensorShape x_shape({10, 10, 54, 10});
Nit: Since the shapes are the same you can just have one shape variables and pass it twice to the Run call.

2017-11-03 03:36 UTC, suharshs commented on tensorflow/cc/gradients/nn_grad.cc
> +  }
Could you run clang-format? Looks like there are some minor formatting issues.

2017-11-07 01:47 UTC, gdeer81 commented
TF Test Suite and Ubuntu CC state have been in "Waiting for status to be reported" for a while now

2017-11-07 02:12 UTC, suharshs approved these changes

2017-11-13 11:58 UTC, bpiel commented
@benoitsteiner @suharshs @skye @andydavis1 @asimshankar

Sorry for the broadcast ping, but not sure who would be best at this point.

This has been sitting for a while. Can it be merged? 
If not, why? It's not clear.

thanks

2017-11-13 15:41 UTC, skye commented
Jenkins test this please.

Sorry for the delay, I think we're a little behind on PRs this week.

2017-11-13 21:51 UTC, skye commented
@gdeer81 it looks like the test you added is failing: https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/7468/consoleFull (search for NNGradTest.LRN)

2017-11-14 04:10 UTC, gdeer81 commented
@skye looks like the failure was due to test timeout that I didn't experience in my local environment.
When I changed the test data I got the test time from 171s to 12s on my laptop so now it shouldn't timeout during the jenkins test run

2017-11-14 08:41 UTC, gdeer81 commented
Jenkins test this please.

2017-11-14 15:43 UTC, skye commented
@gdeer81 can you check how long just your test takes to run on your machine? (You can do this via: `bazel test //tensorflow/cc:gradients_nn_grad_test --test_filter=*LRN`) On my machine, all the current tests run in < 3 seconds. Assuming your test actually adds 9 seconds to the total test time, I think it'd be good to shrink it even more.

2017-11-15 00:37 UTC, gdeer81 commented
@skye here is the output when I do `bazel test //tensorflow/cc:gradients_nn_grad_test --test_filter=*LRN`
![nn_grad_test](https://user-images.githubusercontent.com/1340575/32812358-34bd3b1a-c96a-11e7-87b8-7e15ab9da4be.png)

I might have been looking at the wrong value when I said it takes 12 seconds so I'll just let the screenshot speak for itself and hopefully clear up any confusion

2017-11-15 00:59 UTC, skye commented
Ah ok. I'm honestly not sure what all this means either but looks good to me :) FYI I would do something like: `time ./bazel-bin/tensorflow/cc/gradients_nn_grad_test`

Jenkins test this please.

2017-11-15 08:49 UTC, gdeer81 commented
excellent, all checks have passed

2017-11-15 22:18 UTC, skye commented
@jhseu can you merge? I don't have permission apparently.

2017-11-29 19:54 UTC, gdeer81 commented
@skye or @jhseu is there anything else that I need to do? Those Internal CI build failures don't look like they have anything to do with the changes I made

2017-11-30 00:04 UTC, merged