Adding a feed for boolean tensors to TensorFlowInferenceInterface
tensorflow/tensorflow pull request #14059
Opened 2017-10-28 18:57 UTC by quaeler

For #13601, adding the requested implementation to `TensorFlowInferenceInterface`.

2017-10-28 20:36 UTC, quaeler commented
I could find no existing location for unit tests under the Android contrib project, and so added no unit test for this change.  If such a thing exists, please point me to it and i'll add one there.

2017-10-30 06:04 UTC, asimshankar requested changes

2017-10-30 06:04 UTC, asimshankar commented on tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java
> +    for (int i = 0; i < src.length; i++) {
Isn't there a definition of `b` missing here?

2017-10-30 15:31 UTC, asimshankar approved these changes

2017-10-30 15:31 UTC, asimshankar commented
Jenkins, test this please.

2017-11-01 06:40 UTC, merged