Documentation fix - clarifying sum in softmax function.
tensorflow/tensorflow pull request #14166
Opened 2017-11-02 00:57 UTC by nsuh

This notational fix makes it more clear that you're summing over the classes in the denominator of the softmax function.

2017-11-02 01:00 UTC, nsuh commented
I signed it!

2017-11-09 05:57 UTC, martinwicke approved these changes

2017-11-09 06:00 UTC, martinwicke requested changes
Actually, on second thought, I am not sure this is strictly an improvement. you say 1..10, the code would say 0..9. The real confusion probably stems from j being used earlier to index "over the pixels of our input image". Adding 1..10 gives some more hint in this contradictory situation, but not reusing this index may be better still (and probably good enough to skip the explicit 1..10).

2017-12-12 19:03 UTC, martinwicke commented
@nsuh any update? Marking as stalled.

2017-12-27 02:14 UTC, drpngx commented
@nsuh closing for now, feel free to reopen if you get a chance to address @martinwicke comments.

2017-12-27 02:14 UTC, closed without merging