Fix indenting on cache check in Network layer class
tensorflow/tensorflow pull request #14377
Opened 2017-11-08 18:47 UTC by footh

Resolves [#14054](https://github.com/tensorflow/tensorflow/issues/14054)

The `else` and ensuing code on the cache check was indented one spot too far. This resulted in the cache hit code not being executed when there was a cache hit (and the cache miss code never being called because there was a cache hit).

2017-11-16 01:31 UTC, fchollet approved these changes
LGTM

2017-12-15 00:49 UTC, martinwicke commented
I apologize that this has languished for so long.

This code has moved to network.py. Could you rebase?

@fchollet, should we make this fix internally?

2017-12-15 05:00 UTC, footh commented
Looking at the conflict (lines 2125-2135), it looks like this issue has already been resolved. So this PR is probably moot at this point.

2017-12-15 16:14 UTC, footh commented
Oops, no, I take that back. I just reread your comment and see the bug is in the network.py class. I will rebase.

2017-12-15 18:39 UTC, martinwicke requested changes

2017-12-15 18:39 UTC, martinwicke commented on tensorflow/python/layers/base.py
> -
I think we want this blank line.

2017-12-15 18:39 UTC, martinwicke approved these changes

2017-12-15 18:40 UTC, martinwicke commented on tensorflow/python/layers/base.py
> -
Never mind.

2017-12-15 18:41 UTC, martinwicke commented
Thanks! Testing now.

2017-12-20 22:23 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-12-20 23:54 UTC, merged