fix assert_shallow_structure for dicts
tensorflow/tensorflow pull request #14499
Opened 2017-11-12 14:37 UTC by boeddeker

The function `tensorflow.python.data.util.nest.flatten_up_to` used in `tf.data.Dataset.from_generator` does not compare the dict keys (only the length of the dict)
```python
tf_tree = dict(A=tf.placeholder(tf.float32), B=tf.placeholder(tf.float64))
np_tree = dict(A=np.zeros([1], np.float32), C=np.zeros([2], np.float64))
nest.flatten_up_to(tf_tree, np_tree)  # Fails now
```
and ignores nested dict's (Bug, iterate over keys in `tensorflow.python.data.util.assert_shallow_structure`)
```python
tf_tree = dict(A=tf.placeholder(tf.float32), B=dict(C=tf.placeholder(tf.float64)))
np_tree = dict(A=np.zeros([1], np.float32), B=dict(D=np.zeros([2], np.float64)))
nest.flatten_up_to(tf_tree, np_tree)  # Fails now
```

This PR fix `tensorflow.python.data.util.assert_shallow_structure` that is used in `tensorflow.python.data.util.nest.flatten_up_to`, but there may also other function that have such a bug.

2017-11-16 21:48 UTC, mrry requested changes
Thanks for the fix! That `tf.data` code has a fork of some of the `nest.py` code that includes this bug. Could you add the same fix [here](https://github.com/tensorflow/tensorflow/blob/9089ab59826ce656b6f8026b08471ca6696cacf9/tensorflow/python/util/nest.py#L454)?

2017-11-17 09:37 UTC, boeddeker commented
Sure, I made the modification also in the other `nest.py`.
I fixed also a wrong key the `nest_test.py`.

2017-11-17 17:05 UTC, mrry approved these changes
Looks great... thanks for the contribution!

2017-11-17 17:05 UTC, mrry commented
@tensorflow-jenkins test this please.

2017-11-17 20:56 UTC, merged