Improve SkipNBytes to RandomInputStream
tensorflow/tensorflow pull request #14557
Opened 2017-11-14 18:48 UTC by yongtang

This fix tries to address the issue raised in #14512 where SkipNBytes will takes a long time. In existing implementation, it needs to read through the file even though it is possible to random access the file itself.

This fix convert SkipNBytes in InputStreamInterface to pure virtual so that it is possible to have different implementations based on the underlying file type (seekable vs. no seekable)

This fix then have a specialized implementation in `RandomInputStream` so that
1. The `SkipNBytes` will first try to read 1 bytes from `expected_pos - 1`, if completed, then return.
2. If an out of range error returned from last step, then we don't know how far away we are from the EOF. We are forced to read through the file from the current pos all the way to `expected_pos`. This is similar to existing implementation.

Note: Because `RandomAccessFile` only exposes `Read` (with start offset), not `SizeOfFile`, it is not possible to just move the position marker as we won't know where is the EOF.

One potential improvement could be to expose a `SizeOfFile` in `RandomAccessFile`. That means adding additional changes. It could be added if it is agreed.

This fix fixes #14512.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-12-14 01:05 UTC, martinwicke commented
@rohan100jain can you take a look?

2017-12-27 01:38 UTC, drpngx commented
@rohan100jain any luck with this?

2018-01-17 13:03 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-01-23 18:39 UTC, rmlarsen commented
@rohan100jain Please take a look.

2018-01-23 22:37 UTC, rohan100jain requested changes

2018-01-23 22:37 UTC, rohan100jain commented on tensorflow/core/lib/io/inputstream_interface.h
> +  virtual Status SkipNBytes(int64 bytes_to_skip) = 0;
I don't understand the need to make this pure virtual... just keep it virtual and have RandomInputStream override with a more efficient implementation. Then you don't have to copy the implementations in the other subclasses.

2018-01-24 18:45 UTC, yongtang commented
Thanks @rohan100jain for the review. The PR has been updated. Please take a look.

2018-01-25 17:42 UTC, rohan100jain approved these changes

2018-01-25 17:42 UTC, merged