Make sparse_to_dense differentiable by wrapping scatter_nd.
tensorflow/tensorflow pull request #14552
Opened 2017-11-14 15:57 UTC by ahoereth

Make `sparse_to_dense` a wrapper of `scatter_nd`, as the two have very similar functionality and the latter is differentiable while the former is not. Ran into this because there apparently is no warning when trying to differentiate not differentiable ops.

Related: https://github.com/tensorflow/tensorflow/issues/6391#issuecomment-268392143

If this has potential to be merged and further changes are required, I am happy to work on those.

2017-11-14 17:19 UTC, ahoereth commented
Signed it!

2017-12-14 17:09 UTC, martinwicke commented
@rmlarsen, could you take a look?

2017-12-14 21:39 UTC, rmlarsen commented
@ahoereth can you add a unit test, please?

2017-12-15 21:22 UTC, rmlarsen requested changes
Looks good, but needs a unit test.

2017-12-27 01:30 UTC, drpngx commented
@ahoereth any chance to add the unit test?

2018-01-04 19:26 UTC, ahoereth commented
Sorry for the silence. Sure, I can add unit tests, I am just really not sure what kind of unit test you are expecting? The function itself and the one it wraps are both already unit tested. Should I duplicate the `scatter_nd_add` gradient unit tests (if there are any) and apply them to `sparse_to_dense`?

2018-01-23 21:55 UTC, rmlarsen commented
@ahoereth sorry I dropped this. Yes, a basic unit test for the gradient of sparse_to_dense is needed. You can copy or modify an existing one.

2018-01-23 21:56 UTC, rmlarsen commented
Also, please rebase to resolve the conflict.

2018-02-07 13:44 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-07 23:13 UTC, rmlarsen commented
@ahoereth any progress on adding a basic unit test?

2018-02-22 13:05 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-09 13:34 UTC, tensorflowbutler commented
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-16 21:08 UTC, rmlarsen commented
@ahoereth any chance you'll be able to finish this PR?

2018-04-08 18:35 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-04-09 15:54 UTC, rmlarsen approved these changes

2018-04-09 15:54 UTC, rmlarsen commented
@ahoereth Thanks for adding the test.

2018-04-09 17:41 UTC, rmlarsen commented
Please take a look at the test failures; https://source.cloud.google.com/results/invocations/7e00010b-9216-4bbd-8371-0be4e7023416/log

2018-04-12 08:33 UTC, ahoereth commented
Hey there, sorry for the long delay on this. Apparently my thoughts on how to easily do this would need some deeper changes (e.g. to allow [bool as ref's dtype for scatter_nd_add](https://source.cloud.google.com/results/invocations/356de39b-1dba-4e22-9cc7-780fe0fcc906/targets/%2F%2Ftensorflow%2Fpython%2Fkernel_tests:sparse_ops_test/log)). Closing this for now.

2018-04-12 08:33 UTC, closed without merging

2018-12-09 19:01 UTC, chengchengpei commented
is this merged to 1.12.0?