`mean_relative_error` supports complex label
tensorflow/tensorflow pull request #14667
Opened 2017-11-17 20:41 UTC by facaiy

Fix #14658 

### How to test

+ [x] add test case
+ [ ] pass all tests

2017-12-27 01:48 UTC, drpngx requested changes

2017-12-27 01:48 UTC, drpngx commented on tensorflow/python/ops/metrics_impl.py
> +  """Divides two Tensors, returning 0 if the denominator is <= 0.
please specify that this is component-wise division (aka Schur or Hadamard).

2017-12-27 01:49 UTC, drpngx commented
I'd rather we didn't do this. Performing division by zero raises the FP exception flag and makes for a very slow operation. Either we have a new safe operator in C++ or we should ask user-level awareness.

2017-12-27 06:04 UTC, facaiy commented
Yes, I found `_safe_div` exists in many modules, for example, `losses`, `metrics` and so on. Creating a C++ op perhaps is a better solution, at least for me.

2017-12-27 09:00 UTC, facaiy commented
It seems that `safe_div` has been implemented in C++ side, however it only supports integer now.  

https://github.com/tensorflow/tensorflow/blob/ac7387b48674fdeb11e7a4fa595c88b5e2afe16e/tensorflow/core/kernels/cwise_ops.h#L702-L705

https://github.com/tensorflow/tensorflow/blob/ac7387b48674fdeb11e7a4fa595c88b5e2afe16e/tensorflow/core/kernels/cwise_ops.h#L119-L137

2017-12-27 22:45 UTC, drpngx commented
OK, then should we implement the float version in `C++` then?

2017-12-28 02:12 UTC, facaiy commented
Yes, I think so. I'll open a issue later, and let's discuss the details there. Thank you for your help, @drpngx .

2017-12-28 18:53 UTC, drpngx commented
Thanks!

2017-12-28 18:53 UTC, closed without merging