Automate download and unzip of the model file
tensorflow/tensorflow pull request #14853
Opened 2017-11-24 04:43 UTC by daj

Also added the Exception to the log message when the ImageClassifier fails to initialize. :-)  When the model file is missing the Logcat error is now much more helpful:
```
E/TfLiteCameraDemo: Failed to initialize an image classifier.
    java.io.FileNotFoundException: mobilenet_quant_v1_224.tflite
        at android.content.res.AssetManager.openAssetFd(Native Method)
        at android.content.res.AssetManager.openFd(AssetManager.java:329)
        at com.example.android.tflitecamerademo.ImageClassifier.loadModelFile(ImageClassifier.java:137)
```

TESTING

Used Android Studio 3.0.1 and started with a `./gradlew clean`.  I was able to launch on a device and successfully use the app.

Doing a `./gradlew clean` then a command line build shows the download is happening before the build:
```
$ ./gradlew assemble
<snip>
:app:downloadModel
Downloading https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_224_android_quant_2017_11_08.zip
:app:unzipModel
Unzipping build/intermediates/mobilenet_v1_224_android_quant_2017_11_08.zip
:app:preBuild
:app:preDebugBuild
<snip>
:app:assembleRelease UP-TO-DATE
:app:assemble UP-TO-DATE

BUILD SUCCESSFUL
```

Running it a second time does not download the model again:
```
:app:downloadModel UP-TO-DATE
:app:unzipModel UP-TO-DATE
```

2017-11-29 21:58 UTC, sb2nov commented
@daj can you resolve the merge conflict

2017-11-30 03:39 UTC, daj commented
I've updated the pull request and rebased onto the latest master.

2017-12-04 03:08 UTC, drpngx commented
Jenkins, test this please.

2017-12-26 19:41 UTC, drpngx commented
@aselle WDYT?

2018-04-19 00:30 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 41 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-04-19 01:10 UTC, daj commented
@aselle please can you review?  I can update the PR to resolve the conflict, but I only want to do that if this will get reviewed.  Thanks!

2018-05-03 18:46 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-05-27 02:58 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 37 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-04 18:05 UTC, drpngx commented
@daj could you pull rebase and push again?

@aselle WDYT?

2018-06-06 01:56 UTC, daj commented
I opened this pull request 6 months ago, and I already rebased it once during that time.  I'd like to hear from a reviewer that they intend to review and merge it before I spend any time doing more rebasing.  Thanks!

2018-06-12 15:31 UTC, shashishekhar requested changes
@daj CL looks good, approval post resolving conflicts.

2018-06-13 18:02 UTC, shashishekhar submitted a review, later dismissed

2018-06-17 02:55 UTC, daj commented
@shashishekhar I rebased again and resolved another conflict.  Hopefully we can get it merged before things change again. :-)

2018-06-17 19:17 UTC, shashishekhar approved these changes

2018-06-17 22:10 UTC, merged

2018-06-17 22:11 UTC, drpngx commented
All tests pass. Woohoo!