Add complex dtypes support for `tf.squared_difference`
tensorflow/tensorflow pull request #14939
Opened 2017-11-28 13:37 UTC by yongtang

This fix tries to address the issue raised in #14932 where complex dtypes are not supported for `tf.squared_difference`, which is different from the doc string in `math_ops.cc` (see `BINARY_FEWER`).

This fix adds the `complex64` and `complex128` support in kernel, and adds additional test cases.

This fix fixes #14932.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2017-12-26 19:48 UTC, drpngx commented
@benoitsteiner WDYT?

2018-02-21 22:05 UTC, carlthome commented
Does this actually work as it should? The tests all have zeroes for the imaginary part so it's hard to tell.

2018-02-24 22:24 UTC, yongtang commented
@carlthome The PR has been updated with additional test cases to cover imag != 0 case.

2018-04-19 00:30 UTC, tensorflowbutler commented
Nagging Reviewer @benoitsteiner: It has been 41 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-05-27 02:57 UTC, tensorflowbutler commented
Nagging Reviewer @benoitsteiner: It has been 79 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-10 18:46 UTC, tensorflowbutler commented
Nagging Reviewer @benoitsteiner: It has been 94 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-18 14:53 UTC, qlzh727 commented
Nagging @benoitsteiner again.

2018-07-03 12:47 UTC, tensorflowbutler commented
Nagging Reviewer @benoitsteiner: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-07-18 19:02 UTC, tensorflowbutler commented
Nagging Reviewer%(reviewers): You have been added as a reviewer to this pull request. Please add your review or reassign. It has been  29ays with no activity and the `awaiting review` label has been applied.

2018-08-03 18:50 UTC, tensorflowbutler commented
Nagging Reviewer @benoitsteiner: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-08-18 18:41 UTC, tensorflowbutler commented
Nagging Reviewer @benoitsteiner: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2018-09-02 18:34 UTC, tensorflowbutler commented
Nagging Reviewer @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-09-17 18:56 UTC, tensorflowbutler commented
Nagging Reviewer @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2018-10-02 21:20 UTC, wt-huang commented
@rmlarsen Could you take a look?

2018-10-04 23:54 UTC, rmlarsen requested changes

2018-10-04 23:54 UTC, rmlarsen commented on tensorflow/python/ops/math_ops_test.py
> +      z = (x - y) * (x - y)
normally when we talk about "squared difference" we are referring to the L2 metric in a vector space. Therefore, this function should compute conj(x-y)*(x-y). In other words, you need to modify the implementation as well by adding a conjugation to the first input for complex types.

2018-10-13 21:50 UTC, yongtang commented
Thanks @rmlarsen for the review. I updated the PR to capture the complex support for squared difference. Please take a look at the change and see if it fits.

2018-10-28 18:36 UTC, tensorflowbutler commented
Nagging Assignees @rmlarsen, @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-11-20 17:42 UTC, yongtang commented
@rmlarsen The PR has been updated with `conj(x-y)*(x-y)` used now. Please take a look and see if there are any issues.

2018-12-04 22:10 UTC, harshini-gadige commented
@rmlarsen  Could you please review and approve this PR.

2018-12-05 01:07 UTC, rmlarsen approved these changes

2018-12-05 22:56 UTC, merged