Support "causal" padding in tf.layers.convolutional.Conv1D
tensorflow/tensorflow pull request #15037
Opened 2017-12-01 11:26 UTC by facaiy

Because #15000 is closed by mistake, hence the PR is reopened to resolve #14933 issue.

Because we don't see causal padding in other use cases expect of NTC, we choose to modify code at Conv1D, instead of tf.nn.convolution.

### How to test

+ [x] add test for layers.Conv1D
+ [x] add test for keras.layers.Conv1D
+ [ ] pass all tests.

2017-12-01 11:32 UTC, facaiy commented
cc @martinwicke @lukaszkaiser @fchollet who I think might be interested.

2017-12-01 16:03 UTC, facaiy commented on tensorflow/python/layers/convolutional.py
> +    if padding == "causal":
@szpssky note the code block is before invoking `super(Conv1D, self).__init__(`.  In your case, `causal` leaks into its parent class. I think there might be two reasons:
1. You might paste the code into wrong place by mistake, or
2. The multiple inheritance order of python varies on different environment, or I misunderstand the rule.

2017-12-01 18:10 UTC, fchollet requested changes
- Use `'` as string delimiter for consistency, everywhere
- `layer.padding` should return "causal". Currently you're encoding causal padding via `layer.padding == valid + layer._causal_padding == True`, which is quite confusing.
- Instead of having a method `_helper_for_preprocess` that returns two functions, have a method `_left_causal_padding`, and incorporate the code for output shape computation in `_compute_output_shape`.

2017-12-01 23:41 UTC, facaiy commented
Thanks for review, @fchollet . I agree that `self.padding` should be `causal`, and there are two ways I can think:
1. Modify code of `_Conv` and `Conv1D`: only support causal for NTC format. Easy, but a little tricky.
2. As suggested @lukaszkaiser in #15000,  Support LEFT padding in `tf.nn.convolution`: More general.
> In general, it'd be very very good to have causal="LEFT" padding in TF. This is the one reason why both T2T and Sonet re-implement conv layers...

I think the second way sounds unified. What do you think about the idea?

2017-12-01 23:47 UTC, fchollet commented
We can add `padding='causal'` in `tf.nn.convolution` indeed. Having support only in the layers in a bit restricted (although it is still pretty good, since most people just use the layers).

2017-12-02 13:43 UTC, facaiy commented
@fchollet I'd like to implement the specific case at first, 

Reply:
+ Clean double quote: done.
+ `layer.padding` should return "causal": done.
     create a private method `_get_padding`, which can be removed if `nn_ops.convolution` support causal padding in the future.
+ incorporate the code for output shape computation: not yet.
    Because both `build` and `_compute_out_shape` need correct `input_shape`, I cannot find an appropriate way to incorporate. So I leave the `inputs_fn` and `shape_fn`. The solution might look awkward, however it doesn't modify `_Conv` codes and underline the preprocessing. I think it's clear for understand and a little change for `_Conv`.

Others:
+ Leave comments: remind us to remove those codes if `nn_ops.convolution` support causal padding in the future.
+ Handle unknown dimension case, thanks @szpssky .

If everyone has a good idea, don't hesitate to tell me. Thanks very much.

2017-12-29 01:22 UTC, drpngx commented
@fchollet WDYT?

2018-03-18 17:51 UTC, martinwicke commented
@fchollet WDYT?

2018-04-25 12:00 UTC, facaiy commented
Close it since it has been a long time without any feedback.

2018-04-25 12:00 UTC, closed without merging