Update deprecated get_global_step in example
tensorflow/tensorflow pull request #15081
Opened 2017-12-03 18:28 UTC by tkondrashov

`WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensor_forest/client/random_forest.py:193: get_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_global_step`
thrown when running random_forest_mnist.py

updated to `training_util.get_global_step()` used elsewhere in the same file

2017-12-04 02:29 UTC, drpngx approved these changes

2017-12-04 02:32 UTC, drpngx requested changes
Can you try to remove the extra dependency?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/tensor_forest/BUILD#L533

2017-12-18 01:40 UTC, tkondrashov commented
Done, sorry for the delay!

2017-12-29 01:23 UTC, drpngx approved these changes

2017-12-29 01:23 UTC, drpngx commented
Jenkins, test this please.

2017-12-31 05:45 UTC, drpngx commented
Jenkins, test this please.

2017-12-31 06:40 UTC, merged