[CMake] Re-Enable include
tensorflow/tensorflow pull request #15099
Opened 2017-12-04 15:14 UTC by Androbin

Issue #3996 (and referenced tickets) are already fixed.

2017-12-04 17:48 UTC, mrry requested changes

2017-12-04 17:48 UTC, mrry commented on tensorflow/contrib/cmake/CMakeLists.txt
>  if (tensorflow_ENABLE_GPU)
Can you remove this conditional block?

2017-12-04 18:21 UTC, Androbin commented on tensorflow/contrib/cmake/CMakeLists.txt
>  if (tensorflow_ENABLE_GPU)
Oh, missed that one!

2017-12-04 21:02 UTC, mrry approved these changes
Thanks for the clean-up!

2017-12-04 21:57 UTC, caisq commented
@tensorflow-jenkins test this please

2017-12-05 13:43 UTC, Androbin commented
@sb2nov Is this the #14877 PIP package issue again?
`ImportError: No module named 'tensorflow.contrib.rnn.python.kernel_tests'`
`ImportError: No module named 'tensorflow.contrib.data.python.kernel_tests'`

2017-12-06 19:16 UTC, Androbin commented
@sb2nov Shouldn't at least one of them be fixed as of 06a5cc4acd377815a0a6bbaac6ea0ab972f1c8fb?

2017-12-06 19:45 UTC, Androbin commented
@caisq Test failures are well-known and should be unrelated to this PR.

2017-12-07 19:57 UTC, merged