minor docs addition to fixed_size_partitioner
tensorflow/tensorflow pull request #15164
Opened 2017-12-06 19:13 UTC by cbockman

Clarifying whether fixed_size_partitioner is equivalent to partition_strategy='div' or ='mod', as described in https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup (to hopefully help use downstream with embedding_lookup).

2017-12-08 03:01 UTC, cbockman commented
ps, I manually verified that this is the apparent behavior by iterating through the PartitionedVariable via the Iterator (as I was trying to figure out whether this was 'mod' or 'div', as you might imagine).

2017-12-08 07:01 UTC, ebrevdo requested changes
All partitioners act this way. It's embedding_lookup that decides how item assignment works with rows.  Partitioning just describes how many separate variables to create.  Talking about div vs mod here is confusing.

2017-12-09 02:24 UTC, cbockman commented
OK so, are these equivalent?  Perhaps I am misunderstanding partition_strategy.  

If they are not equivalent, could (per your comment on things being confusing as I suggested) docs should be added to embedding_lookup to clarify how to set partition_strategy, given a PartitionedVariable?

```
my_embedding_var = tf.get_variable(..., partitioner=fixed_size_partitioner, ...)

x = tf.embedding_lookup(my_embedding_var, ..., partition_strategy='mod', ...)
```

```
my_embedding_var = tf.get_variable(..., partitioner=fixed_size_partitioner, ...)

x = tf.embedding_lookup(my_embedding_var, ..., partition_strategy='div', ...)
```

2017-12-26 02:23 UTC, drpngx commented
@ebrevdo WDYT?

2018-01-17 13:00 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-06 07:30 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-20 19:34 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-07 13:11 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-25 00:59 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-08 18:28 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-10 01:12 UTC, tensorflowbutler commented
Nagging Reviewer @ebrevdo: It has been 16 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-05-27 02:57 UTC, tensorflowbutler commented
Nagging Reviewer @ebrevdo: It has been 151 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-10 18:47 UTC, tensorflowbutler commented
Nagging Reviewer @ebrevdo: It has been 166 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-25 19:11 UTC, tensorflowbutler commented
Nagging Reviewer @ebrevdo: It has been 181 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-07-10 19:03 UTC, tensorflowbutler commented
Nagging Reviewer @ebrevdo: It has been 196 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-07-10 20:09 UTC, cbockman commented
Closing this because doesn't look like this is going to be addressed either way.

2018-07-10 20:09 UTC, closed without merging