Add some sparse operators
tensorflow/tensorflow pull request #15184
Opened 2017-12-07 14:22 UTC by chaihua483

2017-12-09 04:05 UTC, chaihua483 commented
test

2017-12-26 02:27 UTC, drpngx commented
@benoitsteiner WDYT?

2018-01-05 03:03 UTC, chaihua483 commented
With this `op`, it might be easy to implement the gradient of `SparseReduceSumSparse`.

```
import tensorflow.contrib.sparse_ops.python.ops.sparse_ops as spops
@ops.RegisterGradient("SparseReduceSumSparse")
def _SparseReduceSumSparseGrad(op, *grads):
    output_tensor = sparse_tensor.SparseTensor(op.outputs[0], grads[1], op.outputs[2])
    input_tensor = sparse_tensor.SparseTensor(op.inputs[0], op.inputs[1], op.inputs[2])

    grad = spops.sparse_tile_like(output_tensor, input_tensor, op.inputs[3]).values

    return (None, grad,
            None, None)
```

I was wondering if it is proper adding this gradient directly into the `contrib` package?

2018-01-24 13:17 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-08 19:25 UTC, ebrevdo requested changes
Thanks for the contribution!

Can you add all this code to tensorflow.contrib.layers instead of its own new package?

also:
* update tf contrib cmake build to ensure it gets built on windows
* remove all commented out code
* run clang format to clean up the code.

2018-02-11 12:24 UTC, chaihua483 commented
@ebrevdo Thanks for your reply! I'd love to make changes recently.

2018-03-03 08:03 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-18 16:03 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-20 10:41 UTC, chaihua483 commented
@ebrevdo I did just as your suggestions. Please remind me if there is anything else to work on. Thank you.

2018-04-13 18:42 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-28 18:31 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-28 18:41 UTC, ebrevdo commented
Please resolve conflicts then we can negotiate like merge. Thanks!

2018-04-28 18:42 UTC, ebrevdo submitted a review, later dismissed

2018-04-28 18:53 UTC, drpngx commented on tensorflow/contrib/layers/python/ops/sparse_tile_like_op.py
> +  This `Op` is used for tile a `1D matrix` to `2D matrix` or `2D matrix`
You'll need to fix the docstring to pass the linter. You need something like
```
  """One-liner

  More verbose description.

  Args:
    sp_a: what it is, e.g. tensor of what type and shape if applicable
    sp_b: ditto
    axes: ditto

  Returns:
     What is returned.
"""
```

2018-04-28 18:54 UTC, drpngx commented on tensorflow/contrib/layers/ops/sparse_tile_like_op.cc
> +As you might see, the `op` will forget all the
please finish the writing

2018-04-28 18:54 UTC, drpngx commented on tensorflow/contrib/layers/ops/sparse_tile_like_op.cc
> +    .Doc(R"doc(
You now need to put a file in the `api_def` directory to document and generate the python.

2018-04-28 18:55 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +    // set values for out_values
Here and everywhere: capitalize and punctuate comments.

2018-04-28 18:56 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +};  // class
remove comment

2018-04-28 18:59 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +std::vector<int64> getRowOfTensor(const Tensor t, const int64 i) {
Use `GetRowOfTensor`

2018-05-13 18:28 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-04 16:22 UTC, drpngx commented
@chaihua483 could you pull rebase and push again?

2018-06-12 09:02 UTC, chaihua483 commented
Sorry for the delay.

2018-06-27 18:47 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-12 19:05 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-27 18:51 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-10 20:52 UTC, drpngx requested changes
Some cosmetic comments. I stopped at some point, not sure if it's building?

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +struct ReduceDetails {
Enclose in `namespace {}`

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +ReduceDetails SparseTensorReduceHelper(const SparseTensor& sp,
Do not return a struct, use `axes_slice, ReduceDetails* reduction`.

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +  auto sp_shape = sp.shape();
unused

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +  auto t_values = t.matrix<int64>();
const auto

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +std::vector<int64> GetRowOfTensor(const Tensor t, const int64 i) {
please don't return `std::vector`s.

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +    auto axes = axes_t->flat<int32>();
const

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +      int64 g_indice_len = g.values<T>().dimension(0);
const

2018-08-10 20:52 UTC, drpngx commented on tensorflow/contrib/layers/kernels/sparse_tile_like_kernel.cc
> +      while (row < group) {
huh? Does that build?

2018-08-31 07:53 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-15 18:32 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-30 12:44 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 50 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-15 12:45 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 65 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-31 12:42 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-11-12 11:42 UTC, chaihua483 commented
#14964 It seems to have been resolved.

2018-11-12 11:42 UTC, closed without merging