add c++ gradient for op: Pow
tensorflow/tensorflow pull request #15245
Opened 2017-12-10 06:48 UTC by facaiy

Fix  #15239.

### How to test

+ [x] add test case.
+ [ ] pass all tests.

2017-12-10 18:34 UTC, caisq commented
@tensorflow-jenkins test this please

2017-12-11 06:09 UTC, facaiy commented
Thanks, @caisq . Git failed to fetch github branch. I think it's an unrelated failure.

2017-12-16 00:37 UTC, suharshs requested changes
just some minor comments. thanks for the PR!

2017-12-16 00:37 UTC, suharshs commented on tensorflow/cc/gradients/math_grad.cc
> +#define RETURN(comp)  \
I find this easier to read without the macro. I think its ok just to duplicate the code in each clause. thanks

2017-12-16 00:37 UTC, suharshs commented on tensorflow/cc/gradients/math_grad_test.cc
> +  TensorShape x_shape({3});
x_shape and y_shape can both just be made 'shape'

2017-12-16 02:32 UTC, facaiy commented
Thank you, @suharshs . I have revised the codes as requested.

2017-12-18 22:50 UTC, suharshs approved these changes

2017-12-26 02:30 UTC, drpngx commented
Jenkins, test this please.

2017-12-26 03:54 UTC, facaiy commented
Time out failure:  //tensorflow/python/keras:data_utils_test

2017-12-26 04:48 UTC, caisq commented
The test failure is unrelated. Merging PR.

2017-12-26 04:48 UTC, merged

2017-12-28 01:50 UTC, drpngx commented
Looks like this test is flaky.

2017-12-31 23:16 UTC, gunan commented
This is causing a lot of issues on the dashboard.
I propose a rollback, and then we can figure out if the test is flaky or the new op is.