Model Average Optimizer
tensorflow/tensorflow pull request #15299
Opened 2017-12-12 07:26 UTC by jinxin0924

I have implemented model average optimizer and open a new pr since the [original one](https://github.com/tensorflow/tensorflow/pull/11581) is closed.

2017-12-12 07:30 UTC, jinxin0924 commented
@alextp, Could you please review this pr? It is quite similar to EASGD. Thanks a lot for your help in EASGD!

2017-12-19 22:55 UTC, yifeif commented
Thanks @jinxin0924. Could you resolve the conflicts?

2017-12-20 02:39 UTC, jinxin0924 commented
@yifeif Conflicts have been resolved. Thanks!

2017-12-20 17:57 UTC, alextp requested changes

2017-12-20 17:57 UTC, alextp commented on tensorflow/contrib/opt/python/training/model_average_optimizer.py
> +      A conditional 'Operation' that update both local and global varibales or
s/varibales/variables

2017-12-21 08:16 UTC, jinxin0924 commented on tensorflow/contrib/opt/python/training/model_average_optimizer.py
> +    self._map = {}
Rename it to self._local_2_global

2017-12-22 01:46 UTC, jinxin0924 commented
Hi @alextp , any more advice?

2018-01-06 00:31 UTC, alextp approved these changes

2018-01-06 00:31 UTC, alextp commented
Jenkins, test this please.

2018-01-06 07:29 UTC, jinxin0924 commented
Hi @alextp , could you help me figure out why the Linux CPU Test failed? I have looked at the console output, and found:
"Build step 'Execute shell' marked build as failure
Unable to get pull request builder trigger!!"
What does it mean?
Thank you!

2018-01-08 04:05 UTC, jinxin0924 commented
@caisq, could you please help me figure out why the Linux CPU Test failed? It seems the failure is not caused by this pr.

2018-01-15 03:45 UTC, jinxin0924 commented
@tensorflow-jenkins test this please

2018-01-15 06:20 UTC, jinxin0924 commented
@caisq,  could you please help me figure out why the Linux CPU Test failed?

2018-01-20 23:39 UTC, merged

2018-09-07 19:05 UTC, ceballosiker commented
Hi @jinxin0924 ,

I've been working with distributed tensorflow for a while and I found this contribution interesting. I've tried to make it work with a simple example on cifar-10, following this tutorial: https://www.tensorflow.org/tutorials/images/deep_cnn

The code I wrote works perfectly with tf.train.SyncReplicasOptimizer, however I can't make it work with your custom optimizer. I always get a TypeError: _true_getter() got multiple values for argument 'shape'. [Model Average Test](https://github.com/Acuratio/distributed-tensorflow-tests/blob/master/model_average_classifier.py)

This error was being triggered by tf.train.get_or_create_global_step() and tf.train.ExponentialMovingAverage(), so I removed them. However I still get the same error at the definition of the ModelAverageOptimizer which I can't remove, so I can't make it work.

Do you have any ideas as of why is this happening or how could I solve this? Any help would be much appreciated. Thanks!

2018-09-08 00:31 UTC, jinxin0924 commented
Hi @ceballosiker 
I am sorry it should be a bug. You can take a look at https://github.com/tensorflow/tensorflow/pull/19661#event-1826361323. It should be able to fix the problem.

2018-09-08 01:35 UTC, ceballosiker commented
@jinxin0924 

Thanks for the quick reply. I followed the instructions on that thread and solved the issue by modifying the model_average_optimizer.py with your suggestions, maybe you should update the optimizer to include those changes?

However, now the chief worker is blocking just after starting the session. I'll try to figure out why this is happening and keep you updated.

Thanks again for your help!

2018-09-08 01:47 UTC, jinxin0924 commented
@ceballosiker Yes, I have pulled those changes and it has been merged!