Release notes and version string update.
tensorflow/tensorflow pull request #15470
Opened 2017-12-19 05:01 UTC by gunan

2017-12-19 05:40 UTC, asimshankar approved these changes

2017-12-19 05:40 UTC, asimshankar commented on RELEASE.md
> +* Eager execution preview version is available under `tensorflow/contrib/eager/`.
Should we make this a link?
[Eager execution](https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html)

And the same for TensorFlow lite, linking to https://www.tensorflow.org/mobile/tflite/?

2017-12-19 05:41 UTC, asimshankar commented on tensorflow/core/public/version.h
> +#define TF_PATCH_VERSION 0rc0
Isn't `TF_PATCH_VERSION` supposed to be 0 and `-rc0` should go in the `TF_VERSION_SUFFIX`?

2017-12-19 05:43 UTC, asimshankar requested changes
Sorry, I was too eager with the approval earlier :)

I think the filenames and versions need to be fixed so that the version suffix is `-rc0`

2017-12-19 05:43 UTC, asimshankar commented on tensorflow/docs_src/install/install_c.md
> +           "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-${OS}-x86_64-1.5.0rc0.tar.gz" |
The filename should be `-rc0.tar.gz`

2017-12-19 06:30 UTC, gunan commented
Should be all addressed now. I messed up the version string update, but it should be good now.

2017-12-19 20:20 UTC, av8ramit approved these changes

2017-12-19 20:25 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.5.0rc0</td><td>CPU</td><td>2.7, 3.3-3.6</td><td>GCC 4.8</td><td>Bazel 0.5.4</td><td>N/A</td><td>N/A</td></tr>
This is an unfortunate issue with the script that changes the reference to 1.4.0. A fix is on my todo but can you revert it here to 1.4.0 if you get a chance? I've also added a note to the release process.

2017-12-19 20:34 UTC, asimshankar submitted a review, later dismissed

2017-12-19 20:40 UTC, av8ramit requested changes

2017-12-19 20:40 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.5.0rc0</td><td>CPU</td><td>2.7, 3.3-3.6</td><td>GCC 4.8</td><td>Bazel 0.5.4</td><td>N/A</td><td>N/A</td></tr>
This is an unfortunate issue with the script that changes the reference to 1.4.0. A fix is on my todo but can you revert it here to 1.4.0 if you get a chance? I've also added a note to the release process.

2017-12-20 19:18 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.5.0rc0</td><td>CPU</td><td>2.7, 3.3-3.6</td><td>GCC 4.8</td><td>Bazel 0.5.4</td><td>N/A</td><td>N/A</td></tr>
Done.

2017-12-20 19:38 UTC, av8ramit commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.5.0rc0</td><td>CPU</td><td>3.5-3.6</td><td>MSVC 2015 update 3</td><td>Cmake v3.6.3</td><td>N/A</td><td>N/A</td></tr>
Here as well.

2017-12-20 21:37 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.5.0rc0</td><td>CPU</td><td>3.5-3.6</td><td>MSVC 2015 update 3</td><td>Cmake v3.6.3</td><td>N/A</td><td>N/A</td></tr>
Done

2017-12-20 21:37 UTC, gunan commented on tensorflow/docs_src/install/install_sources.md
> +<tr><td>tensorflow-1.5.0rc0</td><td>CPU</td><td>2.7, 3.3-3.6</td><td>Clang from xcode</td><td>Bazel 0.5.4</td><td>N/A</td><td>N/A</td></tr>
Done

2017-12-20 21:45 UTC, av8ramit approved these changes

2017-12-20 22:15 UTC, merged