[XLA] Use tensorflow::port::Aligned{Malloc,Free}
tensorflow/tensorflow pull request #15510
Opened 2017-12-20 08:36 UTC by rongjiecomputer

Split from #15310.

#15213

2017-12-20 23:15 UTC, tatatodd reviewed
This seems fine to me, but let's see what Sanjoy thinks.

2017-12-21 01:25 UTC, sanjoy requested changes

2017-12-21 01:25 UTC, sanjoy commented on tensorflow/compiler/xla/service/cpu/external_constant_pool.h
>    // We need to `free()` pointers allocated into `entries_` since we allocate
Please update this comment.

2017-12-21 01:35 UTC, rongjiecomputer commented on tensorflow/compiler/xla/service/cpu/external_constant_pool.h
>    // We need to `free()` pointers allocated into `entries_` since we allocate
Done.

2017-12-21 01:42 UTC, sanjoy approved these changes
LGTM

2017-12-21 02:03 UTC, tatatodd commented
Jenkins, test this please.

2017-12-21 18:13 UTC, merged