Fix sample_distorted_bounding_box where min_object_covered could be None
tensorflow/tensorflow pull request #15531
Opened 2017-12-20 22:10 UTC by yongtang

This fix tried to address the issue raised in #15529 where not providing min_object_covered a value will result in a ValueError. In the docstring, however, min_object_covered has been described as default to 0.1.

The reason for the issue is that when sample_distorted_bounding_box switched to V2, min_object_covered has been changed form an attr to an input. As input could not have a default value, min_object_covered=None will result in an error.

This fix adds the check so that a default value 0.1 will be provided if min_object_covered=None.

This fix fixes #15529.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-01-23 20:10 UTC, rmlarsen requested changes

2018-01-23 20:10 UTC, rmlarsen commented on tensorflow/python/ops/image_ops_impl.py
> +    if min_object_covered is None:
You should update the default value instead, although that will require an API review, I believe.

2018-01-23 20:20 UTC, rmlarsen commented on tensorflow/python/ops/image_ops_impl.py
> +    if min_object_covered is None:
The documentation already stated that the default is 0.1, so I think it would be fine to change it.

2018-01-23 21:21 UTC, yongtang commented
Thanks @rmlarsen for the review. The PR has been updated.

2018-01-23 21:37 UTC, rmlarsen approved these changes

2018-01-24 21:31 UTC, asimshankar commented
(Good for API change, thanks!)

2018-01-24 23:16 UTC, rmlarsen commented
@yongtang please resolve conflict.

2018-01-25 00:06 UTC, rmlarsen approved these changes

2018-01-25 01:22 UTC, merged