Issue #15572, support for unspecified spatial dimensions in layers.Conv3d_transposed
tensorflow/tensorflow pull request #15595
Opened 2017-12-22 21:21 UTC by robb-brown

Patch to 3d transposed convolution to use the same code for adding biases that regular 3d conv uses.  This allows transposed convolution to add biases if the spatial dimensions are not specified and the dimension ordering is channel last.  The case with channel first ordering still requires spatial dimensions be specified for both conv3d and conv3d_transposed because add_bias doesn't support 5d dimension ordering specifications.

2017-12-25 02:18 UTC, drpngx requested changes
Can we have a test for that?

2017-12-26 18:29 UTC, robb-brown commented
Added tests for 2D and 3D transposed conv with unspecified spatial dimensions.

2017-12-26 18:43 UTC, drpngx commented
Could you fix the sanity checks?

```
FAIL: Found 8 non-whitelited pylint errors:
tensorflow/python/layers/convolutional_test.py:612: [E0001(syntax-error), ] inconsistent use of tabs and spaces in indentation
tensorflow/python/layers/convolutional.py:1625: [W0311(bad-indentation), ] Bad indentation. Found 8 spaces, expected 6
tensorflow/python/layers/convolutional.py:1626: [W0311(bad-indentation), ] Bad indentation. Found 12 spaces, expected 8
tensorflow/python/layers/convolutional.py:1627: [W0311(bad-indentation), ] Bad indentation. Found 12 spaces, expected 8
tensorflow/python/layers/convolutional.py:1631: [W0311(bad-indentation), ] Bad indentation. Found 12 spaces, expected 8
tensorflow/python/layers/convolutional.py:1632: [W0311(bad-indentation), ] Bad indentation. Found 12 spaces, expected 8
tensorflow/python/layers/convolutional.py:1633: [W0311(bad-indentation), ] Bad indentation. Found 8 spaces, expected 6
tensorflow/python/layers/convolutional.py:1634: [W0311(bad-indentation), ] Bad indentation. Found 12 spaces, expected 8
```

2017-12-26 19:17 UTC, robb-brown commented
I think that's got it.  I don't think I've ever seen different numbers of spaces used for indentation before.  That appears to be contrary to Google's style guide... maybe a good idea to update the TF CONTRIBUTING.md?

2018-01-17 13:01 UTC, tensorflowbutler commented
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

2018-01-23 00:29 UTC, rmlarsen commented
@robb-brown any progress on fixing the formatting errors?

2018-01-23 13:56 UTC, robb-brown commented
@rmlarsen : https://github.com/tensorflow/tensorflow/pull/15595/commits/ce0b0eeb7c352534361bdeccce2c46cde4788673

As far as I can tell my push a month ago fixed everything.  Your sanity checks appear to show green.

2018-01-23 17:40 UTC, martinwicke commented
Please fix the tests. In TF code, you cannot import `from tensorflow`. 

```
Running test tensorflow/python/layers_convolutional_test on GPU 7
Traceback (most recent call last):
  File "/tmpfs/tmp/bazel/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/python/layers_convolutional_test.runfiles/org_tensorflow/tensorflow/python/layers/convolutional_test.py", line 33, in <module>
    from tensorflow import placeholder, float32
ImportError: cannot import name 'placeholder'
```

2018-01-25 19:26 UTC, drpngx commented
Also please pull rebase and push again.

2018-02-09 19:13 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-10 13:08 UTC, tensorflowbutler commented
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-08 18:28 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-05-09 18:58 UTC, closed without merging