Make `frame` positions configurable
tensorflow/tensorflow pull request #15605
Opened 2017-12-23 15:55 UTC by Androbin

This also fixes a bug in `get_root_dir_with_all_resources`.

@jart Please don't close right away.

The value of `sys._getframe(1)` is caller-sensitive.
This leads to unexpected bugs where it gives the path of the wrong file.

For example, `get_root_dir_with_all_resources` is supposed to find the `runfiles` directoy.
But because of the extra call to `get_data_files_path`, everything shifts by one and now it resolves all paths on the location of the `resource_loader.py` file loaded (repository or PIP, but not a `runfiles` path). In the places it's used currently, it doesn't break anything, tho.

This PR fixes the behavior of `get_root_dir_with_all_resources` and makes the `frame` positions configurable on all methods (with a default for compatibility).

@martinwicke Friendly ping.

2017-12-27 20:50 UTC, jart requested changes
This API change seems doable. I'd like to understand better why it's necessary.

Can I see the code you wrote which needs this change? 

If that code is being run via `bazel test` then there's a slight chance that having `get_root_dir_with_all_resources` return `os.env.get('TEST_SRCDIR', '')` if nonempty might be what you want.

Based on what you describe, assuming your program is being run from within Bazel, it almost sounds like you've got TensorFlow pip installed in a system directory and Bazel is preferring to load sources from there rather than the runfiles symlink tree it constructed.

Because while what you describe is kind of a bug, it shouldn't matter, because in theory everything is supposed to trace back to the massive symlink directory Bazel generates.

2017-12-27 21:17 UTC, Androbin commented
Yes, the motivation behind this is about different files being de-referenced to different places.
No, it's not (purely) about references to PIP, I have already accounted for this.

The problem is rather that while the python file initially called via `bazel` is "correctly" reported to be in `runfiles`, any other files called have their symlinks resolved.

Depending on a few circumstances, things might as well work out, but in my case, I needed a `runfiles` path to remove a `__init__.py` file to make python call the PIP package instead of `runfiles` which doesn't contain generated ops which leads to immediate failure.

My use case might not need this anymore due to recent changes, but I think nonetheless that something so easily breakable should at least be given a parameter for control.

2017-12-27 21:19 UTC, Androbin commented
My use case might not need this anymore due to recent changes, but I think nonetheless that something so easily breakable should at least be given a parameter for control.

And `get_root_dir_with_all_resources` is dedicated to deal with `runfiles` paths.

2018-01-03 21:29 UTC, asimshankar commented
If there isn't a strong need for it right now, let's abandon and revisit when there is one.

2018-01-03 21:29 UTC, closed without merging