Scope subprocess and tempfile imports in tensorflow lite to fix #15410
tensorflow/tensorflow pull request #15890
Opened 2018-01-05 20:18 UTC by javierluraschi

Fix for https://github.com/tensorflow/tensorflow/issues/15410

As @aselle mentions in issue #15410: "this has to do with the interface sealing in tensorflow (where we try to prevent exposing symbols unrelated to the interfaces)", one potential fix is to scope the imports to the required `toco_convert_protos` function.

Validated this issue can be reproduced and fixed by this change.

2018-02-06 14:57 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-16 19:02 UTC, aselle requested changes
thanks for the fix, I ran it through our style checker, and it wasn't happy with the inline includes, so I made a separate pr here:
https://github.com/tensorflow/tensorflow/pull/17073

Please incorporate those changes in here, and then I will approve this pr.

2018-02-21 00:05 UTC, javierluraschi commented
Updated PR as requested.

Looks like we have two PR that we could merge, I have no preference as to which one should be merged.

2018-03-25 00:48 UTC, tensorflowbutler commented
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-08 18:27 UTC, tensorflowbutler commented
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-25 15:05 UTC, andrehentz commented
Is there anything left to be done here? Should this be closed? re-reviewed?

2018-05-10 12:48 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-05-22 20:48 UTC, javierluraschi commented
https://github.com/tensorflow/tensorflow/pull/17073 closes this one.

2018-05-22 20:48 UTC, closed without merging