Make platform a proper module
tensorflow/tensorflow pull request #16057
Opened 2018-01-11 22:58 UTC by droidicus

This fixes an issue where the nice error about importing tensorflow from the TF source directory is not displayed in Python 2.7

Fixes #16019

2018-01-12 02:23 UTC, droidicus commented
I signed it!

2018-01-22 23:38 UTC, rmlarsen approved these changes

2018-01-22 23:38 UTC, rmlarsen commented on tensorflow/python/eager/test.py
> +def main(argv=None): # pylint: disable=function-redefined
Two spaces before '#'

2018-01-22 23:41 UTC, rmlarsen requested changes

2018-01-22 23:41 UTC, rmlarsen commented on tensorflow/python/platform/__init__.py
> +
please revert

2018-01-22 23:41 UTC, rmlarsen commented
@droidicus Is this still needed?

2018-01-23 20:00 UTC, droidicus commented
It looks like this has already been fixed on master in another way, closing MR and associated issue.

2018-01-23 20:00 UTC, closed without merging