Propagate the error string of GIF processing for decode_gif
tensorflow/tensorflow pull request #16113
Opened 2018-01-14 18:39 UTC by yongtang

This fix tries to improve the error thrown by `decode_gif` to include the error string generated by GIF processing.

Previously, the error was not very indicative as the error string
returned by GIF processing was hidden:
```
..........
InvalidArgumentError (see above for traceback): Invalid GIF data, size 2091369
	 [[Node: DecodeGif = DecodeGif[_device="/job:localhost/replica:0/task:0/device:CPU:0"](ReadFile)]]
```

This fix propagate the error string (`can't process optimized gif`) to be part of the `InvalidArgumentError`:
```
InvalidArgumentError (see above for traceback): Invalid GIF data (size 2091369), can't process optimized gif
         [[Node: DecodeGif = DecodeGif[_device="/job:localhost/replica:0/task:0/device:CPU:0"](ReadFile)]]
```

This fix fixes #15838.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-01-22 22:59 UTC, rmlarsen requested changes

2018-01-22 22:59 UTC, rmlarsen commented on tensorflow/core/lib/gif/gif_io.h
> +              std::function<uint8*(int, int, int, int)> allocate_output,
Please add a unit test for the new functionality.

2018-01-23 00:20 UTC, yongtang commented
Thanks @rmlarsen for the review. A unit test `testOptimizedGifErrorString` has been added to image_ops_test.py. Please take a look and let me know if there are any issues.

2018-01-23 18:01 UTC, rmlarsen approved these changes

2018-01-23 18:01 UTC, merged