allow 'None' as batch size for TimeFreqLSTMCell
tensorflow/tensorflow pull request #16129
Opened 2018-01-15 10:31 UTC by progwolff

Currently it is not allowed to have a variable batch size in TimeFreqLSTMCell, as the size is casted to an int internally.
This patch fixes this by omitting the int cast.

Tested it in an audio event detection framework without problems.

2018-02-06 14:56 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-06 16:34 UTC, ebrevdo submitted a review, later dismissed
inputs.shape[0].value or tf.shape(...)

2018-02-07 19:05 UTC, rmlarsen commented
@progwolff please rebase to resolve the conflicts.

2018-02-07 21:44 UTC, progwolff commented
@rmlarsen done.

@ebrevdo Isn't `array_ops.shape` right here?

2018-02-07 22:53 UTC, rmlarsen approved these changes

2018-02-07 22:54 UTC, rmlarsen commented
@ebrevdo using array_ops.shape seems fine to me. What did you have in mind?

2018-02-07 22:55 UTC, ebrevdo commented
"x.shape[0].value or array_ops.shape(..)"

preserves more static shape info than just "array_ops.shape(...)"

On Wed, Feb 7, 2018 at 2:54 PM, Rasmus Munk Larsen <notifications@github.com
> wrote:

> @ebrevdo <https://github.com/ebrevdo> using array_ops.shape seems fine to
> me. What did you have in mind?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/16129#issuecomment-363939171>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABtimzbAgndvVaiKkK0ZwqaQcS0rzh02ks5tSimngaJpZM4ReNU->
> .
>

2018-02-07 23:09 UTC, rmlarsen commented
@ebrevdo Yes, we do want to capture that. I initially tought that ```x.shape[0].value or array_ops.shape(..)``` was pseudocode, but I guess the (ugly) way Python handles None with binary logical operators makes this work. Sigh.

2018-02-07 23:58 UTC, ebrevdo commented
yes; it'll use dynamic shape if the batch size is statically 0; but that's
an exceedingly rare case so we do this for the succinctness :)

On Wed, Feb 7, 2018 at 3:10 PM, Rasmus Munk Larsen <notifications@github.com
> wrote:

> @ebrevdo <https://github.com/ebrevdo> Yes, we do want to capture that. I
> initially tought that x.shape[0].value or array_ops.shape(..) was
> pseudocode, but I guess the (ugly) way Python handles None with binary
> logical operators makes this work. Sigh.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/16129#issuecomment-363942789>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABtimynV9NtP6cw7LuZf_BG-eBvryOfBks5tSi1IgaJpZM4ReNU->
> .
>

2018-02-08 00:09 UTC, rmlarsen requested changes
Please implement ebrevdo@'s suggested improvement.

2018-02-08 09:29 UTC, progwolff commented
The requested change is implemented. Good catch!

Many thanks to both of you!

2018-02-08 16:55 UTC, rmlarsen approved these changes

2018-02-08 19:49 UTC, rmlarsen commented
Fixed linter error.

2018-02-15 01:16 UTC, merged