Added training parameter to batch_normalization
tensorflow/tensorflow pull request #16134
Opened 2018-01-15 16:36 UTC by PiotrCzapla

According to the docs the batch_normalization layer does not work properly if the parameter is not set correctly.

2018-01-22 19:51 UTC, rmlarsen requested changes

2018-01-22 19:51 UTC, rmlarsen commented on tensorflow/examples/learn/resnet.py
> +    net = tf.layers.batch_normalization(net, training=mode == tf.estimator.ModeKeys.TRAIN)
Just calculate a boolean 

```training = mode == tf.estimator.ModeKeys.TRAIN```

and pass that to batch_normalization. Same everywhere.

2018-02-06 14:56 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-07 19:04 UTC, rmlarsen commented
@PiotrCzapla could you address my comments so we can merge this?

2018-02-19 11:07 UTC, PiotrCzapla commented
@rmlarsen thanks for making me fix this style issues. It make sense to keep the examples clean.

2018-03-06 19:17 UTC, tensorflowbutler commented
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-16 20:50 UTC, rmlarsen approved these changes

2018-03-17 18:16 UTC, merged