Update contrib/HVX readme
tensorflow/tensorflow pull request #16131
Opened 2018-01-15 15:59 UTC by bryant1410

I updated the README because of some imprecisions and to add clarifications of what I think will guide the users more appropriately.

First, the very simple "quick start guide" doesn't work, there's no "-X" option (at least publicly) and so you always need to have the SDK installed manually.

Apart from that, some clarifications and rewording were done to help the users understand what's happening.

/cc @satok16

2018-01-22 20:25 UTC, rmlarsen requested changes

2018-01-22 20:25 UTC, rmlarsen commented on tensorflow/contrib/hvx/README.md
> +This README explain how to build and use the TensorFlow runtime with HVX Acceleration. HVX is an extension of Hexagon, a DSP provided by Qualcomm which can compute vector calculations faster using lo
comma after Qualcom.
s/lower/less/

2018-01-23 18:04 UTC, rmlarsen approved these changes

2018-01-23 18:04 UTC, rmlarsen commented
@petewarden Cold you please take a look?

2018-01-25 21:20 UTC, petewarden approved these changes

2018-01-26 16:39 UTC, merged