Fix unicode string conversion issue in Python 2
tensorflow/tensorflow pull request #16168
Opened 2018-01-16 19:32 UTC by yongtang

This fix tries to address the issue raised in #16149 where the unicode string conversion with Python 2 does not match the behavior with Python 3.

The issue was that in Python 3, TensorFlow tries to do a unicode conversion in UTF8 while in Python 2
the default conversion was used.

This fix addresses the issue so that behaviors of TensorFlow with Python 2 and Python 3 match.

This fix fixes #16149.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-01-22 19:07 UTC, rmlarsen requested changes

2018-01-22 20:15 UTC, yongtang commented on tensorflow/python/lib/core/py_func.cc
> +          el = NULL;
Thanks @rmlarsen. The PR has been updated.

2018-01-23 00:19 UTC, alextp approved these changes

2018-01-23 18:02 UTC, rmlarsen approved these changes

2018-01-23 18:02 UTC, merged