Merge changes from r1.5 into master
tensorflow/tensorflow pull request #16172
Opened 2018-01-17 00:46 UTC by angersson

This change picks up the commits exclusive to the r1.5 branch and puts them back into master.

There were a bunch of merge conflicts here. I favored master in most cases except those to do with obvious versioning differences.

I'm not sure if I did the merge correctly, considering there are a great many CLs presented here.

2018-01-17 00:50 UTC, av8ramit requested changes

2018-01-17 00:50 UTC, av8ramit commented on tensorflow/core/ops/compat/ops_history.v1.pbtxt
> +  input_arg {
Can you check if this should be merged in?

2018-01-17 00:50 UTC, av8ramit commented on tensorflow/tools/ci_build/Dockerfile.pi
> -FROM ubuntu:14.04
Check if this was reverted in master?

2018-01-17 00:50 UTC, av8ramit commented on tensorflow/tools/ci_build/Dockerfile.pi-python3
> +FROM ubuntu:16.04
Same as above.

2018-01-17 00:50 UTC, av8ramit commented on tensorflow/workspace.bzl
> +          "https://mirror.bazel.build/bitbucket.org/eigen/eigen/get/034b6c3e1017.tar.gz",
Check which version is later, master or r1.5 and keep the appropriate one.

2018-01-18 01:00 UTC, angersson commented
I addressed @av8ramit's changes after doing some hearty investigation as to why they happened.

2018-01-18 01:07 UTC, av8ramit approved these changes

2018-01-18 01:07 UTC, av8ramit commented on tensorflow/python/eager/tensor_test.py
> -  def testTensorStrReprObeyNumpyPrintOptions(self):
Is keeping this change the right move?

2018-01-18 02:20 UTC, angersson commented
Re-un-disabled some tests that were removed by a merge.

2018-01-19 09:07 UTC, merged