Add test for float16 support with conv1d and update docstring
tensorflow/tensorflow pull request #16273
Opened 2018-01-21 22:33 UTC by yongtang

The float16 support for conv1d has already been in place. However there was no test for float16 with conv1d. This fix adds test case to cover float16 support with conv1d.

In addition, float64 support with conv1d is not possible because conv1d calls conv2d, which in turn does not support float64 yet (See #12941, #13097, and #12943)
The previous docstring incorrectly claimed float64 support with conv1d.

This fix also updates related docstring to remove float64 part.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-01-22 17:57 UTC, rmlarsen requested changes

2018-01-22 21:00 UTC, rmlarsen approved these changes

2018-01-22 21:01 UTC, rmlarsen requested changes

2018-01-22 21:01 UTC, rmlarsen commented on tensorflow/python/kernel_tests/conv1d_test.py
> +    # TODO (yongtang): dtypes.float64 can only be enabled once conv2d support
Nit: No space before openening paren.

2018-01-22 21:06 UTC, yongtang commented on tensorflow/python/kernel_tests/conv1d_test.py
> +    # TODO (yongtang): dtypes.float64 can only be enabled once conv2d support
@rmlarsen Done. Thanks.

2018-01-23 01:49 UTC, rmlarsen approved these changes

2018-01-23 01:49 UTC, merged