contrib/learn: Typo in variable name x_exrta --> x_extra
tensorflow/tensorflow pull request #16500
Opened 2018-01-27 17:58 UTC by cclauss

flake8 testing of https://github.com/tensorflow/tensorflow

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tensorflow/contrib/learn/python/learn/datasets/synthetic.py:156:32: F821 undefined name 'x_extra'
    spir_x = np.append(spir_x, x_extra)
                               ^
```

2018-01-27 23:04 UTC, caisq commented
@cclauss Thanks for the fix. Is it possible to add unit-test coverage for this?

2018-01-28 04:25 UTC, cclauss commented
@caisq Thanks for your positive comment.  Above, I have already provided the test case for this issue.

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__

The issues behind all [9 of my PRs](https://github.com/tensorflow/tensorflow/pulls/cclauss) to date were found using this same [flake8](http://flake8.pycqa.org) test.  I would be happy to work with you to get this test (esp. F821) implemented across the TensorFlow codebase as there are currently 24 undefined names in Python 2 and 33 undefined names in Python 3.

Pylint does not currently find undefined names.

2018-01-28 16:53 UTC, caisq commented
@cclauss The `flake8` command you included was helpful. However, I was asking about whether you could add a Python unit test in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/synthetic_test.py that exercises the previously problematic line, to prevent possible regressions in the future.

2018-01-29 19:16 UTC, cclauss commented
@caisq I usually use pytest instead of unittest.  Did the syntax get this right?

2018-01-29 20:43 UTC, caisq requested changes

2018-01-29 20:43 UTC, caisq commented on tensorflow/contrib/learn/python/learn/datasets/synthetic_test.py
>      synthetic.spirals(3)
Thanks for the unit test, @cclauss ! That's very helpful. However, i would probably rewrite the test method in a simpler way:

```python
def test_spirals(self):
  synthetic.spirals(3)
```

The point of the test is that you are covering a (previously uncovered) case of `spirals`, which is valuable in itself. It seems a little strange to write a test for a typo :)

2018-01-29 21:02 UTC, caisq approved these changes

2018-01-29 21:50 UTC, merged