[XLA] Fix error with subcomputation unification not adjusting conditionals
tensorflow/tensorflow pull request #16655
Opened 2018-02-01 11:23 UTC by DavidNorman

When the subcomputation unification finishes, it calls into the module to adjust any instructions which have had their computation parameters invalidated.

the conditional instruction was missing from this function.

2018-02-05 22:58 UTC, jhseu commented
Note that the good reviewers for this change are out for the next couple days, so expect a slow response.

2018-02-06 09:15 UTC, DavidNorman commented
no problem.  i'm not in a hurry.

2018-02-21 13:19 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-21 13:22 UTC, hawkinsp requested changes
Sorry about the slow review.

It looks like someone else made the same change to hlo_module.cc so you can revert that part of the PR, but the change to the test looks good.

2018-02-22 17:32 UTC, DavidNorman commented
ah yes - i noticed that it had been added from elsewhere.  I will abandon the change all-together.  simpler.

2018-02-22 17:32 UTC, closed without merging