CMake (Windows): Added support for ninja build and some fixes/changes
tensorflow/tensorflow pull request #16763
Opened 2018-02-05 03:18 UTC by ChaseOxide

Most changes have comments stuck with them, but here's the summary of it.  

Changes made:
- Added EXACT flag on find_package CUDA to clarify it is building for exactly that version, the output "minimum required" can be misleading
- Tests if the compiler is compatible with CUDA before it starts building
- BYPRODUCTS/BUILD_BYPRODUCTS are added for Ninja to search for dependency, otherwise it will output the error shown below  
`ninja: error: 'zlib/install/lib/zlibstatic.lib', needed by 'proto_text.exe', missing and no known rule to make it`
- Visual Studio is the only generator with that will output under $(Configuration) directory, thus removed if it is not Visual Studio
- Fixed CONFIGURE_COMMAND causing some CMake versions to break (it resets to default generator, the [CMake](https://cmake.org/files/v3.6/cmake-3.6.3-win64-x64.zip) I tried uses NMake Makefiles as default, which causes the output below  
  ```
  ...
  Submodule path 'third_party/benchmark': checked out '360e66c1c4777c99402cf8cd535aa510fee16573'
  Performing update step for 'protobuf'
  No patch step for 'protobuf'
  Performing configure step for 'protobuf'
  CMake Error at CMakeLists.txt:12 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  -- Building for: NMake Makefiles
  -- Configuring incomplete, errors occurred!
  ...
  ```

Additional Info: The current version of CMake has a problem with its ninja generator, as it may produce an error below  
`ninja: fatal: CreateProcess: The filename or extension is too long.`  
The CMake with its ninja generator improved can be found [here](https://gitlab.kitware.com/cmake/cmake/merge_requests/1604)

2018-02-05 03:23 UTC, ChaseOxide commented
I signed it!

2018-02-05 23:00 UTC, mrry requested changes
Thanks for the contribution! Looks fine to me modulo one typo.

2018-02-05 23:00 UTC, mrry commented on tensorflow/contrib/cmake/CMakeLists.txt
> +  # Test compatibality of compiler on CUDA
Nit (typo): "compatibility"

2018-02-05 23:00 UTC, mrry commented
@jhseu Before merging this, we should probably run a manual Windows CMake GPU build in addition to the regular presubmits.

2018-02-06 04:55 UTC, mrry approved these changes

2018-02-08 00:25 UTC, merged