GLSTMCell fix
tensorflow/tensorflow pull request #16849
Opened 2018-02-08 00:45 UTC by okuchaiev

* Make sure it works correctly for input_size != num_units

2018-02-22 13:06 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-09 13:36 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-25 03:43 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-08 18:31 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-27 03:04 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 107 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-10 18:52 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 122 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-25 19:15 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 137 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-10 19:06 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 152 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-25 19:00 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 167 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-09 13:03 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 182 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-24 21:45 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 197 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-08 18:39 UTC, tensorflowbutler commented
Nagging Assignee @ebrevdo: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-09 16:30 UTC, ebrevdo requested changes
can you add a unit test?

2018-09-09 16:30 UTC, ebrevdo commented on tensorflow/contrib/rnn/python/ops/rnn_cell.py
> +                                            int(input_size / self._number_of_groups)),
this won't work if input_size is a tensor.

2018-09-09 16:30 UTC, ebrevdo commented on tensorflow/contrib/rnn/python/ops/rnn_cell.py
> +                                            int(self._output_size / self._number_of_groups))
ditto

2018-09-09 16:30 UTC, ebrevdo commented
@qlzh727 is taking lead on deciding which cells in tf.contrib.rnn to keep.  Scott - PTAL?

2018-09-10 17:13 UTC, qlzh727 commented
Seems that there is a merge conflict with the existing file, can u rebase to the latest?

Agree with ebrevdo@ that a unit test is need to demonstrate that the change fixed the specific problem, which will prevent the problem happening from any future change.

2018-09-12 04:55 UTC, okuchaiev commented
@ebrevdo and @qlzh727 thanks for looking into this!
I've reviewed merge conflicts and apparently someone else has fixed this bug. 
The master looks good. Closing, because nothing needs to change in the code.

2018-09-12 04:55 UTC, closed without merging