Fix broken link in tfmobile documentation
tensorflow/tensorflow pull request #16993
Opened 2018-02-13 23:40 UTC by yongtang

This fix fixes the broken link in tfmobile documentation as
`android/` had been moved to `android/tfmobile/` in the repo
`googlecodelabs/tensorflow-for-poets-2`

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-02-14 03:05 UTC, chluke20an7 requested changes
I need my intier phone setup from home screne open apps an everything apps an so forth?

2018-03-01 02:12 UTC, protoget commented
Re @chluke20an7 friendly pinging about review.

2018-04-19 00:30 UTC, tensorflowbutler commented
Nagging Reviewer : It has been 48 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-05-03 03:04 UTC, protoget approved these changes

2018-05-17 18:48 UTC, tensorflowbutler commented
Nagging Reviewer : It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-02 07:19 UTC, tensorflowbutler commented
Nagging Reviewer : It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-04 05:05 UTC, merged