Fix batch input in TFLite multithreaded 1x1 conv
tensorflow/tensorflow pull request #17326
Opened 2018-02-28 14:41 UTC by deeply

Fix the issue that batch size is hard-coded as 1 in TFLite
multithreaded_ops::Conv() when filter size is 1x1 or filter and
input have the same size.

2018-03-28 12:28 UTC, tensorflowbutler commented
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-09 10:01 UTC, deeply commented
Hi @aselle , this might be a blocking issue if one need to run batch inference for model with 1x1 conv (e.g. mobilenet). Hope to get some feedback about this PR sooner :smile:

2018-05-10 01:01 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 15 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-05-27 02:59 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 47 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-10 18:54 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 62 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-25 19:16 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 77 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-07-10 19:07 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: It has been 92 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-07-25 19:01 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 107 days with no activity and the `awaiting review` label has been applied.

2018-08-09 13:04 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 121 days with no activity and the `awaiting review` label has been applied.

2018-08-24 21:46 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 137 days with no activity and the `awaiting review` label has been applied.

2018-09-08 18:40 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 152 days with no activity and the `awaiting review` label has been applied.

2018-09-17 21:06 UTC, aselle requested changes
I think the change is made to fix this in head, could you modify this pr to just be the test case, because that seems still useful.

2018-09-22 14:17 UTC, deeply commented
Looks like the issues have been fixed and related test cases have been added. After all, almost 7 months has passed since this PR was created.  Related commits are as follows:
- 645291feb9455c20c8d7296455403e895b5e0d1c : Fix TfLite Convolution handle input_bacthe incorrectly for 1*1 kernel, and improve test coverage for conv ops.
- 4902db818664b62f60c0f9572cc939f596d1c8bc : Fixes to hybrid conv. Add additional tests for pointwise conv.
- 6995d2b9be0e398f11a17348eb5b4745aee0af0d : Fix convolution bug when input and filter dimensions match.

I will close this outdated PR. @aselle

2018-09-22 14:17 UTC, closed without merging