Add tensor support for num_spectrogram_bins in linear_to_mel_weight_matrix
tensorflow/tensorflow pull request #17404
Opened 2018-03-03 22:32 UTC by yongtang

This fix tries to address the issue raised in #16553 where it was not possible to provide num_spectrogram_bins as a tensor or placeholder for linear_to_mel_weight_matrix.

The reason comes from the implementation of `_validate_arguments` which requires num_spectrogram_bins to be a python int.

However, the validation here is not necessary as `num_spectrogram_bins` will be passed to `math_ops.linspace`, which performs the validation anyway.

The validation in `math_ops.linspace` is done in shape function and in kernel's `Compute()`.

For that it makes sense to remove the validation of `num_spectrogram_bins` in `_validate_arguments` so that the issue raised in 16553 could be addressed.

This fix adds a test case to cover the changes. Also, the error case of `num_spectrogram_bins < 0` has already been covered in the existing test case:
https://github.com/tensorflow/tensorflow/blob/013a6c7b3112573ba4d932c8a22bfaf45f648c77/tensorflow/contrib/signal/python/kernel_tests/mel_ops_test.py#L149-L165

This fix fixes #16553.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-03-28 12:29 UTC, tensorflowbutler commented
Nagging Assignee @rryan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-01 18:24 UTC, rryan requested changes
Sorry for the delay. Just a few tiny nits. Thanks!

2018-04-01 21:06 UTC, yongtang commented on tensorflow/contrib/signal/python/ops/mel_ops.py
> +    # Note: As num_spectrogram_bins is passed to `math_ops.linspace`
Thanks @rryan. The doctoring has been updated.

2018-04-01 21:07 UTC, yongtang commented on tensorflow/contrib/signal/python/kernel_tests/mel_ops_test.py
> +          20, constant_op.constant(129), 8000.0, 125.0, 3800.0)
@rryan Thanks. The test case has been updated.

2018-04-01 21:07 UTC, yongtang commented on tensorflow/contrib/signal/python/kernel_tests/mel_ops_test.py
> +  def test_num_spectrogram_bins(self):
Thanks. Done.

2018-04-01 21:07 UTC, yongtang commented
Thanks @rryan for the review. The PR has been updated. Please take a look.

2018-04-01 21:10 UTC, rryan approved these changes
Great, thanks!

2018-04-12 20:01 UTC, merged