Docker Jupyter: Update deprecated softmax_cross_entropy_with_logits
tensorflow/tensorflow pull request #17412
Opened 2018-03-04 13:14 UTC by tiangolo

The current Jupyter Notebook included in the Docker image `3_mnist_from_scratch.ipynb` uses the deprecated [`tf.nn.softmax_cross_entropy_with_logits`](https://www.tensorflow.org/api_docs/python/tf/nn/softmax_cross_entropy_with_logits).

This PR updates that Jupyter Notebook to use the new [`tf.nn.softmax_cross_entropy_with_logits_v2`](https://www.tensorflow.org/api_docs/python/tf/nn/softmax_cross_entropy_with_logits_v2).

---

I ran it to make sure everything works, but I didn't commit the changes in the cells because the image style looks a bit different, and that would create changes in the diff of the images in the Notebook. This way it should be easier for you to see the exact change.

If you want me to, I can run the cells and commit the new output (with changes in image style and size, but same content).

2018-03-15 01:29 UTC, frankchn requested changes
Can we not delete all the `collapsed: false` lines? Ideally the changes should be as minimal as possible.

2018-03-15 14:16 UTC, tiangolo commented
Sure @frankchn ! Done :heavy_check_mark:

2018-03-15 17:56 UTC, frankchn approved these changes

2018-04-05 09:52 UTC, tiangolo commented
@frankchn I see the error is related to other sections that were not modified by this PR:

```
Writing docs for tf.contrib.quantize (<module 'tensorflow.contrib.quantize' from '/Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/tools/docs/build_docs_test.runfiles/org_tensorflow/tensorflow/contrib/quantize/__init__.py'>).
Writing docs for tf.contrib.tpu.infeed_dequeue_tuple (<function infeed_dequeue_tuple at 0x1195756e0>).
WritingERROR:
    output file name: /Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/tools/docs/build_docs_test.runfiles/org_tensorflow/tensorflow/docs_src/tutorials/kernel_methods.md
    Cannot make link to "tf.contrib.learn.estimator": Not in index.
F
======================================================================
FAIL: testBuildDocs (__main__.BuildDocsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/tools/docs/build_docs_test.runfiles/org_tensorflow/tensorflow/tools/docs/build_docs_test.py", line 70, in testBuildDocs
    self.fail('Found %s Errors!' % status)
AssertionError: Found 1 Errors!
----------------------------------------------------------------------
Ran 1 test in 25.613s
FAILED (failures=1)
 docs for tf.contrib.lite.convert_op_hints_to_stubs (<function convert_op_hints_to_stubs at 0x11a4d22a8>).
```

What should we do about it? Is it a race condition or something? Should we re-trigger the CI?

2018-04-05 16:11 UTC, frankchn commented
That's fine. Unrelated test failure -- merging.

2018-04-05 16:11 UTC, merged