Don't use NCHW or NHCW for conv1d
tensorflow/tensorflow pull request #17455
Opened 2018-03-06 00:13 UTC by alanhdu

Fixes deprecation warning when using tf.layers.conv1d.

2018-03-06 00:15 UTC, alanhdu commented
This was initially closed because @protoget thought that:

> Internally we still need NCHW or NWHC, the data_format is later passed to gen_nn_ops.conv2d.

But I've confirmed that this is actually not true: `tf.nn.conv1d` explicitly converts `NCW` and `NWC` back to `NCHW` and `NWHC`:

https://github.com/tensorflow/tensorflow/blob/6fdb9ad1baf7686a75f9e660178f7ac595e7fc2e/tensorflow/python/ops/nn_ops.py#L2428-L2435

and has explicitly deprecated `NCHW` and NWHC` as arguments:

https://github.com/tensorflow/tensorflow/blob/b07680459a88224fce83daa7b3b70bcc62b9c896/tensorflow/python/ops/nn_ops.py#L2366-L2375

2018-03-13 17:56 UTC, reedwm requested changes

2018-03-13 17:56 UTC, reedwm commented on tensorflow/python/ops/nn_ops.py
> +      elif data_format not in {"NCW", "NWC"}:
Before it only gave a deprecation warning if the user passed "NCHW" or "NHWC" but now it raises an error. Change {"NCW", "NWC"} to {"NCW", "NWC", "NCHW", "CHWC"}

2018-03-14 15:33 UTC, alanhdu commented
@reedwm Done!

2018-03-15 17:32 UTC, reedwm approved these changes

2018-03-19 21:11 UTC, alanhdu commented
@reedwm @protoget Is there anything else I need to do here? I'm hoping that this can get merged in for the 1.7 release (if only for the aesthetic value of not having deprecation warnings in my code :stuck_out_tongue_winking_eye:).

2018-03-19 22:42 UTC, merged

2018-03-19 22:42 UTC, reedwm commented
Sorry for the delay.

@gunan, will this be included in 1.7?

2018-03-20 06:56 UTC, gunan commented
No, 1.7 is almost final.
And since this is only warnings, we will probably not delay the final release for this cherrypick.