Fix minor typos for programer guide documents
tensorflow/tensorflow pull request #17486
Opened 2018-03-06 16:06 UTC by imsheridan

Described as PR title.

2018-03-06 16:13 UTC, mrry requested changes
Please revert the changes in `datasets.md`.

2018-03-06 16:13 UTC, mrry commented on tensorflow/docs_src/programmers_guide/datasets.md
> +  iterates through it once. For more sophisticated users, the
This changes the sense of the sentence—please revert.

2018-03-06 16:13 UTC, mrry commented on tensorflow/docs_src/programmers_guide/datasets.md
> +A dataset comprises elements that each has the same structure. An element
I prefer the previous version here—please revert.

2018-03-13 05:46 UTC, frankchn requested changes

2018-03-13 05:46 UTC, frankchn commented on tensorflow/docs_src/programmers_guide/low_level_intro.md
> +layer to an input, call the layer as if it was a function. For example:
Same thing with the past subjunctive, `were` is correct usage.

2018-03-13 05:46 UTC, frankchn commented on tensorflow/docs_src/programmers_guide/low_level_intro.md
> +tensor as we could for any other tensor. For example, the following code:
`for` is not necessary, and either `would` or `could` is OK here.

2018-03-13 06:27 UTC, frankchn submitted a review, later dismissed

2018-03-13 06:27 UTC, frankchn commented on tensorflow/docs_src/programmers_guide/low_level_intro.md
> +TensorFlow provides an utility called TensorBoard. One of TensorBoard's many
`A` utility rather than `an`

2018-03-28 12:29 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-03-28 14:19 UTC, imsheridan commented
Is there any admin help review this patch?

2018-03-28 17:19 UTC, mrry approved these changes

2018-04-05 23:54 UTC, merged