Variadic arguments for tf.control_dependencies
tensorflow/tensorflow pull request #17818
Opened 2018-03-19 07:57 UTC by carlthome

# Disclaimer: this is a UX proposal for the Python API but it should be discussed first!

## Proposal
I see a lot of people get tripped up on `tf.control_dependencies` as they often try to pass a single tensor/op to it and forget to explicitly wrap it in a Python list. Perhaps it would be better to support both usages, as that is more in line with how `tf.keras` does things.

**TL;DR: This commit changes `tf.control_dependencies` so that it takes a list as before, but also works with variadic arguments as well.**

```py
with tf.control_dependencies(tf.assert_positive(x)):
  x = tf.identity(x)
```

## TODO
- [ ] Discuss if this is a worthwhile change.
- [ ] Consider changing type check from `list` to `collections.Iterable` despite docstring.
- [ ] Add test of single (and a couple) tensor(s).
- [ ] (possibly) adjust docstring

2018-03-26 22:50 UTC, josh11b commented
API owner comment: Should use python.util.nest.flatten() to accept arbitrary nesting of lists, tuples, etc. Don't worry about collections.Iterable, flatten() will handle the common sequence types. Otherwise this looks good.

2018-03-28 18:08 UTC, carlthome commented
Cool. `nest.flatten` looks very clean. 🎉

2018-03-28 20:40 UTC, asimshankar commented on tensorflow/python/framework/ops.py
> +  def control_dependencies(self, *control_inputs):
The docstring for control_inputs could use an update :)

Also, doesn't this break the behavior of `tf.control_dependencies(None)`?

2018-04-13 18:41 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-04-16 19:06 UTC, martinwicke commented
@carlthome can you update the PR to address @asimshankar's comments?

2018-04-19 16:45 UTC, martinwicke commented
@asimshankar another round of review?

2018-04-20 07:23 UTC, asimshankar requested changes

2018-04-24 11:34 UTC, carlthome commented on tensorflow/python/framework/ops.py
> +      raise ValueError("To clear existing dependencies, every element passed "
Is there a better term for "regular object" than "non-None" that's Pythonic?

2018-06-13 18:57 UTC, closed without merging

2018-06-13 18:58 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.