Fix the incorect format of math equation in factorization_ops
tensorflow/tensorflow pull request #18054
Opened 2018-03-28 16:02 UTC by imsheridan

This PR is to fix the incorrect rendering of math equation in [tf.contrib.factorization.WALSModel](https://www.tensorflow.org/versions/r1.7/api_docs/python/tf/contrib/factorization/WALSModel).

This PR fixed the incorrect math equation rendering in above api guides according to the
[Math in markdown](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/documentation.md#math-in-markdown) guideline. That is using $$, \( and \) to surround the math equation.

Take the [math equation](https://www.tensorflow.org/versions/r1.7/api_docs/python/tf/contrib/factorization/WALSModel#class_walsmodel) as an example to show the fixing result:
Before:
![image](https://user-images.githubusercontent.com/1680977/38040047-3bd9af06-32e1-11e8-9fa3-a93a9820c5b4.png)

After:
![image](https://user-images.githubusercontent.com/1680977/38040098-5f2a0262-32e1-11e8-8239-aa02c87c2823.png)

2018-03-28 16:03 UTC, rmlarsen approved these changes

2018-03-28 16:03 UTC, rmlarsen commented
Thanks!

2018-03-28 16:04 UTC, rmlarsen commented
@imsheridan  The "F" should be a subscript on the norm (Frobenius norm). Can you fix that?

2018-03-28 16:05 UTC, rmlarsen requested changes

2018-03-28 16:05 UTC, rmlarsen commented on tensorflow/contrib/factorization/python/ops/factorization_ops.py
>     \|\sqrt W \odot (A - U V^T) \|_F^2 + \lambda (\|U\|_F^2 + \|V\|_F^2)
"F" should be subscript on the norm.

2018-03-28 16:07 UTC, imsheridan commented
@rmlarsen Could you please help point out which "F"?

2018-03-28 16:08 UTC, imsheridan commented on tensorflow/contrib/factorization/python/ops/factorization_ops.py
>     \|\sqrt W \odot (A - U V^T) \|_F^2 + \lambda (\|U\|_F^2 + \|V\|_F^2)
Got it, I'll fix it soon

2018-03-28 16:14 UTC, imsheridan commented
@rmlarsen Fixed the "F" should be a subscript on the norm (Frobenius norm) as below:
![image](https://user-images.githubusercontent.com/1680977/38041900-8a6171a0-32e5-11e8-92f9-3e80e7b72a39.png)

2018-03-28 20:00 UTC, rmlarsen commented
@imsheridan Thanks!

2018-03-28 20:01 UTC, rmlarsen commented
@imsheridan would you mind checking the same issue matrix_solve_ls again?

2018-03-28 21:29 UTC, rmlarsen commented
@imsheridan please fix linter errors (probably >80 char lines)

2018-03-29 00:14 UTC, imsheridan commented
@rmlarsen I fixed the reported lint errors. Yeah sure I'm checking whether the same issue occurs in matrix_solve_ls.

2018-03-29 01:20 UTC, imsheridan commented
@rmlarsen Just FYI, I checked [matrix_solve_ls PR](https://github.com/tensorflow/tensorflow/pull/18022) didn't have the same above subscript "F" issue, so don't needs to change :)

2018-03-29 02:05 UTC, rmlarsen approved these changes

2018-03-29 02:05 UTC, merged