Disable the toco binary in pip feature until it can used shared libs
tensorflow/tensorflow pull request #18061
Opened 2018-03-28 20:09 UTC by aselle

The binary size was doubled by the saved model change. Since to process
saved models most of the TensorFlow runtime is needed. A workaround to
this is in the works and should be submitted in the next couple weeks.

2018-03-28 20:11 UTC, gargn approved these changes

2018-03-28 21:57 UTC, rmlarsen commented
@aselle please fix linter errors.

2018-03-28 21:57 UTC, rmlarsen requested changes

2018-03-28 21:57 UTC, rmlarsen commented on tensorflow/contrib/lite/toco/python/toco_wrapper.py
> +Please use the python TOCO API or use
please fix linter errors.

2018-03-29 06:27 UTC, aselle commented on tensorflow/contrib/lite/toco/python/toco_wrapper.py
> +Please use the python TOCO API or use
done

2018-03-29 14:59 UTC, rmlarsen approved these changes

2018-03-29 14:59 UTC, merged