Fix adam optimizer related math equation rendering format
tensorflow/tensorflow pull request #18168
Opened 2018-04-02 05:11 UTC by imsheridan

This PR is to fix mess-up math equation format in below Adam optimizer related docstrings.

This PR is to fix this math equation issue according to the [Math in markdown guideline](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/documentation.md#math-in-markdown).

Take [LazyAdamOptimizer](https://www.tensorflow.org/api_docs/python/tf/contrib/opt/LazyAdamOptimizer#methods) as an example below:
Before:
![image](https://user-images.githubusercontent.com/1680977/38183933-b681b03a-3676-11e8-8099-b53e2f55d0cc.png)

After:
![image](https://user-images.githubusercontent.com/1680977/38184016-476ff1e2-3677-11e8-8d48-b68d2f257f41.png)

2018-04-09 19:32 UTC, MarkDaoust requested changes
Thanks for the PR.
 
I'm pretty sure that being inside of fenced code-blocks (delimited by ```) will block latex from rendering. 

Can you delete those ``` ?

Thanks.

2018-04-10 12:09 UTC, imsheridan commented
Thanks @MarkDaoust , you're right and I've fixed this.

2018-04-16 19:04 UTC, martinwicke commented
@MarkDaoust can you take another look?

2018-04-17 17:42 UTC, MarkDaoust requested changes
Thanks for the changes. I tried this on tensorflow.org and there are still a couple of little issues. Can you take a look?

2018-04-19 17:25 UTC, imsheridan commented on tensorflow/contrib/optimizer_v2/adam.py
> +    \\(m_0 <- 0\\) (Initialize initial 1st moment vector)
@MarkDaoust Thanks for your suggestion, fixed :)

2018-04-19 17:25 UTC, imsheridan commented on tensorflow/core/api_def/base_api/api_def_ResourceApplyAdam.pbtxt
> +$$lr_t <- \text{learning_rate} * \sqrt{(1 - beta_2^t) / (1 - beta_1^t)}$$
Sure @MarkDaoust , I've fixed all the arrow like with "\Leftarrow"

2018-04-19 17:29 UTC, imsheridan commented
Thanks a lot for your comments, @MarkDaoust . Could u pls take another look?

2018-04-19 20:11 UTC, MarkDaoust approved these changes

2018-04-19 20:13 UTC, MarkDaoust commented
Thanks. 

I replaced the "\leftarrows" with ":=" as renders less badly than "<-" but is still readable in the source file.

2018-04-19 23:49 UTC, martinwicke commented
This fails because the APIDef isn't valid protobuf any more. Most likely a string escape gone wrong.

2018-04-20 03:10 UTC, imsheridan commented
@martinwicke Fixed the invalid protobuf typo. Could u pls kindly help run the gate tests?

2018-04-20 17:58 UTC, imsheridan commented
The failure case is the timeout of `//tensorflow/core:common_runtime_ring_reducer_test`, which seems to be unrelated.

2018-04-22 05:08 UTC, merged