INTEL MKL:  Fixing a unit test failure, for direct session memory allocation
tensorflow/tensorflow pull request #18240
Opened 2018-04-04 18:04 UTC by ashraf-bhuiyan

A unit test "direct_session_with_tracking_alloc_test" failed both in Google CI and Intel internal test. The root cause is: The check failed for checking allocation ID to 3 and 4 (hard coded). Here the test assumes, that the allocation id does not change in any place. But the problem is, the BFCallocator changed the allocation id when mkl is used. But, when mkl is not used, BFCAllocator is not used, thus allocation id is not overridden.
If MKL is used, it goes through various additional graph rewrite pass. In TF, everytime a graph pass happens, "constant" nodes are allocated and deallocated. Each allocation calls the (FindChunkPtr of BFCAllocator) which increments the value of AllocationId. Thus AllocationId becomes more than 3 and 4 if MKL is used, they can be 10 and 11 or other numbers. If MKL is used following the AllocationId check will not hold. Thus, skipping the check if MKL is used.

2018-04-17 17:12 UTC, ashraf-bhuiyan commented
@andrewharp, if possible, can you please take a look into this PR.

2018-05-02 18:42 UTC, tensorflowbutler commented
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-04 05:12 UTC, tatianashp commented
It would be better to specify the correct values of allocation ids when run with MKL instead of skipping the test. It is OK if these values are different from those when run without MKL, as long, as they are consistent across MKL runs. Could you please make this change.

2018-05-04 19:04 UTC, ashraf-bhuiyan commented
I addressed your comment, added proper allocation ID when MKL is used.

2018-05-05 00:54 UTC, tatianashp requested changes

2018-05-05 00:54 UTC, tatianashp commented on tensorflow/core/common_runtime/direct_session_with_tracking_alloc_test.cc
> +#ifdef INTEL_MKL
It would be better to duplicate only constant values rather than the whole if statement

2018-05-09 22:31 UTC, ashraf-bhuiyan commented
Tatiana, I just have addressed your comment in the code. Now ifdef MKLDNN block only surround the parameter, not the whole block. Please take a look.

2018-05-10 01:58 UTC, tatianashp submitted a review, later dismissed

2018-05-10 02:38 UTC, tatianashp commented
The changes look good to me. Thanks! I'll approve once you resolve the conflicts. The constants for non-MKL path have changed to 9 and 10. The constants for MKL path now should be 15 and 16.

2018-05-10 19:04 UTC, ashraf-bhuiyan commented
I resolved the conflict and tested, test passed both MKL and non MKL version. Thanks.

2018-05-10 19:18 UTC, tatianashp submitted a review, later dismissed
Looks good. Thanks for addressing all the comments!

2018-05-17 00:36 UTC, tatianashp approved these changes
Looks good!

2018-05-18 14:50 UTC, merged