Fix math equation rendering format in api definitions
tensorflow/tensorflow pull request #18274
Opened 2018-04-05 19:32 UTC by imsheridan

This PR is to fix mess-up math equation format in api definition related pbtxts according to the [Math in markdown guideline](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/documentation.md#math-in-markdown).

Take [tf.gather_nd](https://www.tensorflow.org/api_docs/python/tf/gather_nd) as an example below:
Before:
![image](https://user-images.githubusercontent.com/1680977/38387596-e9a3c364-394a-11e8-8594-116c1cb9fb7b.png)
After:
![image](https://user-images.githubusercontent.com/1680977/38387667-25d5b52c-394b-11e8-8da0-e06873811fd3.png)

2018-04-12 01:57 UTC, jhseu commented
Adding Martin because if we decide to change the formatting here, it might be better to change everything at once.

2018-04-12 15:10 UTC, martinwicke commented
@MarkDaoust will this render correctly? Some of these are MathJax inside code blocks. I'm happy with this change if it works.

2018-04-27 23:32 UTC, MarkDaoust commented on tensorflow/core/api_def/base_api/api_def_Exp.pbtxt
> +  summary: "Computes exponential of x element-wise.  \\(y = e^x\\)."
These ones, in .pbtxt files, need to stay double-escaped.

2018-04-27 23:35 UTC, MarkDaoust requested changes
hmmm.... 

https://www.tensorflow.org/api_docs/python/tf/zeta

It looks like a lot of the spots where you reduced the escaping one level on the `\\(` are already rendering correctly. So I think the reduced escaping will break them. you need to use `\\\\(` in the `.pbtxt` files.

They're not rendering on the cc pages:

https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/zeta

It looks like the cc pages just don't have mathjax installed, but that's a separate problem.

2018-05-12 18:33 UTC, tensorflowbutler commented
Nagging Assignee @andrewharp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-27 12:35 UTC, tensorflowbutler commented
Nagging Assignee @andrewharp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-14 18:50 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-06-19 00:37 UTC, MarkDaoust commented
>It looks like a lot of the spots where you reduced the escaping one level on the \\( are already rendering correctly. So I think the reduced escaping will break them. you need to use \\\\( in the .pbtxt files.

Nope. I was wrong about this.

It's the summary line that looses one level of escaping. The summary lines (like the change to Exp) need the double escaping \\\\( \\\\). The description fields need the single escaping (that's why [polygamma](https://www.tensorflow.org/api_docs/python/tf/polygamma) already works).

2018-06-19 00:43 UTC, MarkDaoust approved these changes

2018-06-29 20:52 UTC, merged