Expose Scaffold.default_local_init_op as a public static method.
tensorflow/tensorflow pull request #18398
Opened 2018-04-10 21:47 UTC by dthkao

As discussed offline with @martinwicke, removes the underscore in all repo usages. Fixes #18242

2018-04-10 23:15 UTC, martinwicke commented
Can you run the api_compatibility_test and do what it says when it fails (it will fail)?

2018-04-12 17:34 UTC, martinwicke approved these changes

2018-04-12 17:35 UTC, martinwicke requested changes

2018-04-12 17:35 UTC, martinwicke commented on tensorflow/python/training/monitored_session.py
>      return control_flow_ops.group(
Please add a docstring.

2018-04-12 17:35 UTC, martinwicke commented on tensorflow/python/training/monitored_session.py
>      return control_flow_ops.group(
Ideally, say which initialization steps this method includes, in which order, so it's possible to use it without looking at the code.

2018-04-12 20:35 UTC, dthkao commented
Done.

2018-04-12 22:46 UTC, martinwicke requested changes
I believe you need a "Returns: " section in order to not later break the linter.

2018-04-12 22:57 UTC, dthkao commented
Sorry about that. Ran lint this time too to make sure.

2018-04-12 23:11 UTC, martinwicke approved these changes

2018-04-12 23:13 UTC, martinwicke commented
Thanks!

2018-04-16 02:11 UTC, merged