Add testing for TF-TRT
tensorflow/tensorflow pull request #18509
Opened 2018-04-13 22:21 UTC by samikama

This pr adds a py_test with a trivial class to contrib/tensorrt. Tagging @aaroey

2018-04-16 19:21 UTC, aaroey requested changes

2018-04-17 00:44 UTC, samikama commented
@aaroey It should be done now. Thanks for the review.

2018-04-17 17:35 UTC, aaroey approved these changes

2018-04-17 22:15 UTC, aaroey requested changes

2018-04-17 22:15 UTC, aaroey commented on tensorflow/contrib/tensorrt/BUILD
> +    srcs_version = "PY2AND3",
Please add
```
tags = [                                                                     
    "manual",                                                                
    "notap",                                                                 
],
```
below this line.

2018-04-17 23:05 UTC, samikama commented on tensorflow/contrib/tensorrt/BUILD
> +py_test(
@aaroey  It is done but somehow github can't see it

2018-04-17 23:05 UTC, samikama commented on tensorflow/contrib/tensorrt/BUILD
> +    srcs_version = "PY2AND3",
@aaroey  Same here

2018-04-18 02:00 UTC, aaroey approved these changes

2018-04-18 02:03 UTC, merged