Using xrange from six
tensorflow/tensorflow pull request #18610
Opened 2018-04-17 18:56 UTC by yongtang

In python 2 vs 3 xrange is different. This fix is an enhancement to use xrange from six, instead of additional logic of handling xrange in python 2 vs python 3.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-04-17 20:23 UTC, martinwicke requested changes

2018-04-17 20:26 UTC, martinwicke approved these changes

2018-04-17 20:26 UTC, martinwicke commented
nvm just fixed it.

2018-04-17 21:40 UTC, yongtang commented
Thanks @martinwicke for the help.

I looked into the build failure. One failure:
```
//tensorflow/core:common_runtime_ring_reducer_test
```
seems to be unrelated as well.

2018-04-19 16:26 UTC, merged

2018-04-19 16:26 UTC, martinwicke commented
Yeah, known failure.