Update depreciation.py
tensorflow/tensorflow pull request #18670
Opened 2018-04-18 18:18 UTC by gautam1858

writing if statement in one line

2018-04-19 15:59 UTC, martinwicke requested changes
it

2018-04-19 15:59 UTC, martinwicke commented on tensorflow/python/util/deprecation.py
> +
This is a change in behavior: 

- super needs to be outside the if
- logging.warning is outside the if warn_once

You can pull the check for _PRINTED_WARNING out, but not the warn_once.

2018-04-19 17:38 UTC, gautam1858 commented
@martinwicke made the changes

2018-04-19 19:58 UTC, martinwicke requested changes

2018-04-19 19:58 UTC, martinwicke commented on tensorflow/python/util/deprecation.py
> +
This is still not right. Please make sure that the behavior matches the original. Right now, you would always log a warning, not only the first time.

If you're unsure, run the tests. I think they at least cover the "warn once" case, not sure the coverage for _PRINT_DEPRECATION_WARNINGS is good enough, but passing the tests will be a decent indicator.

2018-05-26 18:58 UTC, tensorflowbutler commented
Nagging Assignee @martinwicke: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-13 18:59 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-07-12 19:04 UTC, closed without merging

2018-07-12 19:07 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.