Support string tensors for `tf.count_nonzero`
tensorflow/tensorflow pull request #18715
Opened 2018-04-20 03:00 UTC by yongtang

This fix tries to address the issue raised in #18712 where `tf.count_nonzero` does not support string tensors.

The reason the string tensor does not work was because `tf.count_nonzero` uses `input_tensor.dtype.as_numpy_dtype()` to created a numpy type `zero` which is passed to `tf.not_equal`. However, `as_numpy_dtype()` will convert `tf.string` to `np.object` so an exception is thrown.

But passing a numpy type `zero` to `tf.not_equal` is unnecessary as we could use `tf.zeros` instead, which works for `tf.string`

This fix fixes the issue. This fix fixes #18712.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-04-22 05:54 UTC, martinwicke requested changes

2018-04-22 05:54 UTC, martinwicke commented on tensorflow/python/ops/math_ops.py
> +      or `bool`.
Can you add a note and example about the behavior of this function with dtype string to the docstring?

2018-04-22 16:12 UTC, yongtang commented
Thanks @martinwicke for the review. The PR has been updated and example/note for tf.count_nonzero with strings has been added. Please take a look and let me know if there are any issues.

2018-04-23 06:51 UTC, martinwicke approved these changes

2018-04-23 06:51 UTC, merged