Raise error on separable convolution and depthwise convolution with strides > 1 and rate > 1
tensorflow/tensorflow pull request #18814
Opened 2018-04-24 00:29 UTC by Corea

In documents, `separable_con2d` and `depthwise_conv2d` should not accept `strides > 1` and `rate > 1` at the same time. But they don't have any code to check these parameters, so it worked in a wrong way.

2018-04-26 22:59 UTC, drpngx requested changes
I think strides can be a tensor as well, so if you want this, you need to check if it's a Tensor first. In the Tenor case, then you need to use tf asserts.

2018-04-26 22:59 UTC, drpngx commented
Also, a test would be nice!

2018-05-11 18:45 UTC, tensorflowbutler commented
Nagging Assignee @ekelsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-26 19:01 UTC, tensorflowbutler commented
Nagging Assignee @ekelsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-10 21:51 UTC, tensorflowbutler commented
Nagging Assignee @ekelsen: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-26 02:38 UTC, tensorflowbutler commented
Nagging Assignee @ekelsen: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-10 19:14 UTC, tensorflowbutler commented
Nagging Assignee @ekelsen: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-25 19:07 UTC, tensorflowbutler commented
Nagging Assignee @ekelsen: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-09 13:10 UTC, tensorflowbutler commented
Nagging Assignee @ekelsen: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-10 21:33 UTC, annarev commented
Closing due to lack of activity. @Corea feel free to resend this as a different PR when you have time to address @drpngx comments.

2018-08-10 21:33 UTC, closed without merging