Add DeviceSet to Cluster
tensorflow/tensorflow pull request #18838
Opened 2018-04-24 21:08 UTC by aaroey

Add DeviceSet to Cluster so we can access memory allocators when running grappler optimizations.
This is required by the TensorRT integration with TF.

2018-04-24 21:08 UTC, aaroey commented
@samikama

2018-04-26 18:20 UTC, benoitsteiner requested changes

2018-04-26 21:12 UTC, aaroey reviewed
Done, thanks for the review.

2018-04-26 21:12 UTC, aaroey commented on tensorflow/core/grappler/clusters/BUILD
> +        "//tensorflow/core:core_cpu_lib",
Done.

2018-04-26 21:12 UTC, aaroey commented on tensorflow/core/grappler/clusters/cluster.h
> +  const DeviceSet* GetDeviceSet() const {
Done.

2018-04-27 17:58 UTC, benoitsteiner approved these changes

2018-04-27 17:58 UTC, merged