Adding Wrapper for Ridge Solver
tensorflow/tensorflow pull request #18900
Opened 2018-04-26 11:26 UTC by coreywho

Created a wrapper to run a sklearn.linear_model.Ridge solver in a Tensorflow Session to allow for faster convergence when optimizing a linear least squares + l2 regularization problem

2018-05-26 18:55 UTC, tensorflowbutler commented
Nagging Assignees @ekelsen, @rmlarsen: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-06 08:37 UTC, coreywho commented
Hi, could someone check this PR? Thanks!

2018-06-21 18:56 UTC, tensorflowbutler commented
Nagging Assignees @ekelsen, @rmlarsen: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-06 18:49 UTC, tensorflowbutler commented
Nagging Assignees @ekelsen, @rmlarsen: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-16 21:34 UTC, rmlarsen requested changes

2018-07-16 21:34 UTC, rmlarsen commented on tensorflow/contrib/opt/python/training/external_optimizer.py
> +    var_vals = self._minimize(
this fits on a single line

2018-07-16 21:34 UTC, rmlarsen commented on tensorflow/contrib/opt/python/training/external_optimizer.py
> +  Where l is a hyperparameter.
Can you please add a unit test for this Interface?

2018-07-31 19:02 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-08-10 21:28 UTC, case540 commented
Seems like our bot mistakenly removed "waiting for response" label. Please address comments about tests on this PR. Thanks!

2018-09-08 18:33 UTC, closed without merging

2018-09-08 18:44 UTC, tensorflowbutler commented
It has been 28 days that this pull-request has stalled. Please create a new pull-request with the requested changes.