Allow tfdbg mouse down scroll in curses UI
tensorflow/tensorflow pull request #18942
Opened 2018-04-28 03:37 UTC by pvaneck

This commit allows users to continuously scroll the screen when the mouse is held down on the scroll bar when using the curses UI for tfdbg.

2018-05-01 03:25 UTC, caisq requested changes
This looks great. Just a minor comment.

2018-05-01 03:25 UTC, caisq commented on tensorflow/python/debug/cli/curses_ui.py
> +            if scroll_command is not None:
Can you change this to
```python
if scroll_command in (_SCROLL_UP_A_LINE, SCROLL_DOWN_A_LINE):
```

The behavior for hold-scrolling outside the UP and DN blocks is a little weird due to the way the multi-line scrolling actions happen.

2018-05-02 06:54 UTC, pvaneck commented
Yea, the click hold scrolling is pretty wonky outside the arrow buttons. I've added the requested change.

2018-05-02 13:15 UTC, caisq approved these changes

2018-05-02 14:08 UTC, merged