[INTEL MKL] This fixes a failure in //tensorflow/python/profiler:model_analyzer_test.
tensorflow/tensorflow pull request #19152
Opened 2018-05-08 16:38 UTC by agramesh1

Modified  testComplexCodeView to look for lower total_float_ops. The value of total_float_ops is lower when Tensorflow is compiled with Intel MKL.

2018-05-08 17:33 UTC, rmlarsen requested changes

2018-05-08 17:33 UTC, rmlarsen commented on tensorflow/python/profiler/model_analyzer_test.py
> +        self.assertLess(101600, tfprof_node.total_float_ops)
Should this be conditional on IsMklEnabled() ?

2018-05-08 21:16 UTC, agramesh1 commented
@rmlarsen thanks. I have updated the PR based on your feedback.

2018-05-08 23:32 UTC, rmlarsen submitted a review, later dismissed

2018-05-09 15:46 UTC, rmlarsen approved these changes

2018-05-09 16:51 UTC, merged