Fix tf.matching_files issue with access denied subdirectory.
tensorflow/tensorflow pull request #19307
Opened 2018-05-15 22:45 UTC by yongtang

This fix tries to address the issue raised in #19274 where
tf.matching_files will return an error if no permission for
subdirectories (Even if the subdirectories does not match).

This fix addresses the issue by ignore the case for `permisson denied`
during the directory traversal.

This fix fixes #19274.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-06-04 12:40 UTC, tensorflowbutler commented
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-19 18:43 UTC, tensorflowbutler commented
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-20 01:17 UTC, tensorflowbutler commented
Nagging Assignee @rohan100jain: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-03 18:51 UTC, tensorflowbutler commented
Nagging Assignee @rohan100jain: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-09 20:43 UTC, rohan100jain requested changes
Also, can you add a test to file_io_test.py. Create a directory structure and use chmod to change file permissions so that you don't have access to a sub directory. Make sure that you can traverse the other files.

2018-08-09 20:43 UTC, rohan100jain commented on tensorflow/core/platform/file_system_helper.cc
> +    if (s.code() != tensorflow::error::PERMISSION_DENIED) {
Hmmm so the semantics of GetChildren are not clear when PERMISSION_DENIED is returned. Should we try to process the children in the vector? Might be better to bail if we hit PERMISSION_DENIED?

2018-08-10 21:35 UTC, yifeif commented
@yongtang are you still working on this PR?

2018-08-12 17:45 UTC, yongtang commented
@rohan100jain @yifeif Thanks for the help. The PR has been updated with test cases added. Also, when GetChildren encountered PERMISSION_DENIED will pass. Please take a look and let me know if there are any issues.

2018-08-20 18:54 UTC, rohan100jain commented
Thanks @yongtang!

2018-08-20 18:54 UTC, rohan100jain commented on tensorflow/python/lib/io/file_io_test.py
> +    # Test case for GitHub issue 19274.
Remove this comment line

2018-08-20 18:54 UTC, rohan100jain commented on tensorflow/python/lib/io/file_io_test.py
> +          gen_io_ops.matching_files(dir_path).eval(), expected_match)
why use gen_io_ops.matching_files.. why not file_io.get_matching_files instead? In fact try looking for .../test_dir/*/file*.txt and expect to only find file1.txt, file2.txt and file3.txt

2018-08-23 20:54 UTC, yongtang commented
Thanks @rohan100jain  for the review. The PR has been updated. Please take a look.

2018-09-07 18:52 UTC, tensorflowbutler commented
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-22 12:36 UTC, tensorflowbutler commented
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-07 12:35 UTC, tensorflowbutler commented
Nagging Assignee @rohan100jain: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-08 17:16 UTC, rohan100jain approved these changes

2018-10-15 21:20 UTC, yongtang commented
@yifeif The `feedback/copybara` is failing but I could not see the details. Is there anyway to see what might be the error in `feedback/copybara`?

2018-10-16 00:08 UTC, merged