INTEL MKL: Enhance MkL Relu Op with primitive reuse
tensorflow/tensorflow pull request #19400
Opened 2018-05-18 20:26 UTC by gzmkl

Enable MKL primitive reuse for Relu Op via caching, to improve
  (1) model training and
  (2) inference of small batch size
by minimizing primitive creation time.

Notes:
   Changes of mkl_conv_ops.cc of this PR 
          https://github.com/tensorflow/tensorflow/pull/19399
   is also included because of refactoring work for primitive reuse of conv2d Fwd and based classes. 
   (otherwise, branch will not build)
   So we suggest that PR 19399 is reviewed and merged first.  Thanks!

2018-05-21 16:21 UTC, gzmkl commented
Close temporarily - pending conv_bwd PR

2018-05-21 20:36 UTC, gzmkl commented
mkl_conv_ops.cc has been reverted to avoid any review confusion. 
The new version of mkl_conv_ops.cc is contained in PR #19399. 

Thanks

2018-06-04 15:59 UTC, drpngx commented
@rmlarsen there are a few of these CLs, I am assigning them to you. You could try to enlist @tatianashp if she's up for it.

2018-06-04 16:55 UTC, gzmkl commented
Pending on https://github.com/tensorflow/tensorflow/pull/19754

2018-07-04 22:14 UTC, gzmkl commented
Reopen since PR #19399 has been merged

2018-07-15 12:19 UTC, yiqianglee commented
Yes, i have already singed CLA, and should be ok to contribute.

2018-07-18 17:18 UTC, gzmkl commented
Hi,
I am the PR submitter and confirm that I am OK with all the changes made by yiqianglee.
Thanks,
GZ

2018-07-19 16:53 UTC, rmlarsen commented
@gzmkl I think many of my comments for PR 19403 would apply to this as well, please modify accordingly.

2018-07-19 17:58 UTC, gzmkl commented
Plan to apply  PR 19403 comments on this PR too.

2018-07-31 18:11 UTC, rmlarsen commented
@gzmkl resolved conflict.

2018-07-31 19:55 UTC, drpngx commented
I think the Mac error is unrelated to this CL.

```
ERROR: /Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/external/com_google_googletest/BUILD.bazel:45:1: Couldn't build file external/com_google_googletest/_objs/gtest/external/com_google_googletest/googletest/src/gtest-death-test.o: C++ compilation of rule '@com_google_googletest//:gtest' failed: Unexpected IO error.: Running '/Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow/_bin/xcode-locator 8.3.3' failed with code 1.
This most likely indicates that xcode version 8.3.3 is not available on the host machine.
Process exited with status 1
stdout: error: Unable to extract CFBundleShortVersionString from URL: file:///Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/external/grpc/tools/dockerfile/distribtest/node_ubuntu1604_x64/
```

2018-08-01 00:17 UTC, rmlarsen commented
@gzmkl can you ping this PR when you are done applying the changes suggested in PR 19403, please?

2018-08-01 15:19 UTC, gzmkl commented
Hi Rasmus, I am done with code change with this PR. Thanks!

From: Rasmus Munk Larsen [mailto:notifications@github.com]
Sent: Tuesday, July 31, 2018 5:21 PM
To: tensorflow/tensorflow <tensorflow@noreply.github.com>
Cc: Zhuang, Guozhong <guozhong.zhuang@intel.com>; Mention <mention@noreply.github.com>
Subject: Re: [tensorflow/tensorflow] INTEL MKL: Enhance Mkl Relu Op with primitive reuse (#19400)


@gzmkl<https://github.com/gzmkl> can you ping this PR when you are done applying the changes suggested in PR 19403, please?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/tensorflow/tensorflow/pull/19400#issuecomment-409408371>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Ab3J2y4p2rtzWj9xpELB3flY7T-p-c88ks5uMPRXgaJpZM4UFTyj>.

2018-08-01 16:55 UTC, gzmkl commented
I have done code change per code review suggestions from other PR (19403). 

Please ignore changes in mkl_util.h after PR 19403/19402 have been approved.  

Thanks!

2018-08-07 21:24 UTC, rmlarsen requested changes

2018-08-07 21:34 UTC, gzmkl commented on tensorflow/core/util/mkl_util.h
> +    CHECK(stream_iter == map.end());
It seems that mkl_util.h is screwed up, after quite a lot of code changes
per BatchNorm/Pooling primitive reuse PR. 

Let me check the source code.

2018-08-07 21:59 UTC, gzmkl commented on tensorflow/core/util/mkl_util.h
> +    CHECK(stream_iter == map.end());
I re-based mkl_util.h file with the public "master" branch. 
So the file in the PR branch is now same as the one in the master branch. 

Build/test shows no issue. 

Thanks

2018-08-13 16:16 UTC, gzmkl commented
Hi,

I have done code change with PR (taking review comments of previous related PRs such as #19403; rebase mkl_util.h to avoid merge conflicts etc). Please let me know if I need to take future actions.

Thanks!

2018-08-13 16:49 UTC, drpngx commented
Could you pull rebase and push again to resolve the conflicts? Thanks.

2018-08-13 16:51 UTC, drpngx commented
@yiqianglee do you approve the commit for the CLA?

2018-08-13 17:39 UTC, gzmkl commented
Hi, 
Ramesh of our team will take care of merge conflicts, as he has seen many of such on multiple PRs but did not have time to fix this PR.

Thanks,
GZ

2018-08-14 01:03 UTC, agramesh1 commented
I am ok with my commits being contributed to this project.

2018-08-14 22:08 UTC, gzmkl commented
I am OK with the change (to address merge conflicts) by Ramesh.

2018-08-14 22:10 UTC, gzmkl commented
Hi, 
Ramesh has helped to address the merge conflict. 
Somehow the "cla" tag still says "no". Please help to address the cla problem.

We would like to merge this PR asap, because we need to submit Relu3D before the end of the Friday, to give a two-week window for getting into Tensorflow 1.11.

Thank you!

2018-08-14 22:17 UTC, drpngx commented
@rmlarsen if you have time, then the authors would like to have this reviewed in the next couple of days or so to make the `1.11` release cutoff.

2018-08-14 23:09 UTC, yiqianglee commented
I am OK with the change by Ramesh and GZ.

2018-08-16 20:31 UTC, rmlarsen approved these changes

2018-08-16 20:31 UTC, rmlarsen commented
@gzmkl Thanks. Sorry about the review delay.

2018-08-16 21:51 UTC, gzmkl commented
Rasmus,
Thank you very much for the diligent work of review all primitive reuse PRs. 
There were too much code change (almost rewriting MKL-DNN integration code). 
We truly appreciate your hard work with valuable code refinement suggestions. Great collaboration!
-GZ

2018-08-24 22:31 UTC, gzmkl commented
Hi, 
I saw this PR approved but was not merged. There was a time-time during "Internal CI Build".
Please let me know what I can help. Thanks!  -GZ

2018-08-28 20:36 UTC, merged