Add Hadoop SequenceFile support for tensorflow Dataset
tensorflow/tensorflow pull request #19534
Opened 2018-05-24 14:36 UTC by yongtang

This fix adds Hadoop SequenceFile for tensorflow Dataset, so that it is possible to process files stored in Hadoop system directly.

This fix is a very preliminary and early implementation. It supports `org.apache.hadoop.io.Text` only, and there is no compression support yet.

Will work on expanding the support of other serialization types, and compresion support in the follow up PR.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-06-09 18:33 UTC, tensorflowbutler commented
Nagging Reviewer @mrry: It has been 14 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-24 18:34 UTC, tensorflowbutler commented
Nagging Reviewer @mrry: It has been 29 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-06-25 04:08 UTC, mrry requested changes
Just some minor changes needed... sorry for the delay.

2018-06-25 04:08 UTC, mrry commented on tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc
> +    std::string version;
Style nit: use `string` instead of `std::string` in the `tensorflow` namespace.

2018-06-25 04:08 UTC, mrry commented on tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc
> +}
The `OpKernel` implementation should also be in the anonymous namespace.

2018-06-25 04:08 UTC, mrry commented on tensorflow/contrib/hadoop/kernels/hadoop_dataset_ops.cc
> +      // Resets all Parquet streams.
Nit: Copy-paste error?

2018-06-25 04:08 UTC, mrry commented on tensorflow/contrib/hadoop/python/kernel_tests/hadoop_test.py
> +    filenames = array_ops.placeholder_with_default(
Can you simply make a `constant_op.constant()` here? (It doesn't look like the placeholder is ever fed.)

2018-06-25 04:08 UTC, mrry commented on tensorflow/contrib/hadoop/python/ops/hadoop_dataset_ops.py
> +  def __init__(self, filenames, output_types=(dtypes.string, dtypes.string)):
Remove the `output_types` argument since it can't currently be set to anything other than the default.

2018-06-25 04:08 UTC, mrry commented on tensorflow/contrib/hadoop/python/ops/hadoop_dataset_ops.py
> +    return self._output_types
Simplify these: 

```python

  @property
  def output_classes(self):
    return ops.Tensor, ops.Tensor

  ...

  @property
  def output_types(self):
    return dtypes.string, dtypes.string

2018-06-25 16:04 UTC, yongtang commented
Thanks @mrry for the detailed review! The PR has been updated with comments addressed. Please take a look and let me know if there are any other issues.

2018-07-02 17:20 UTC, yongtang commented
@mrry The PR has been updated with the compiler errors (changes in `framework/dataset.h`) fixed. All tests passed except Sanity test, which is actually covered in https://github.com/tensorflow/tensorflow/pull/20474#issuecomment-401872675

Please take a look and let me know if there are any other issues.

2018-07-02 18:24 UTC, mrry requested changes

2018-07-02 18:24 UTC, mrry commented on 1.log
> +//tensorflow/contrib/hadoop:hadoop_test                               NO STATUS
Please revert this file and `2.log`.

2018-07-02 18:41 UTC, yongtang commented
@mrry Really sorry for the extra log files (1.log and 2.log) in the last update :cold_sweat: . I was too quick to use `git add -A` without check in detail.

The PR has been updated. Please take a look.

2018-07-02 18:52 UTC, mrry submitted a review, later dismissed

2018-07-02 18:53 UTC, mrry commented
Thanks for that! The change looks good to me now.

2018-07-24 12:58 UTC, tensorflowbutler commented
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-24 18:36 UTC, yongtang commented
@case540 As this PR has been approved and all tests passed, maybe it is ready to add `ready to pull` label?

2018-08-08 18:57 UTC, tensorflowbutler commented
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-09 17:28 UTC, drpngx commented
Oh it fails under windows with:
```
FAIL: //py_test_dir/tensorflow/contrib/hadoop:hadoop_test (see T:/tmp/nsz6drem/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/py_test_dir/tensorflow/contrib/hadoop/hadoop_test/test.log)
INFO: From Testing //py_test_dir/tensorflow/contrib/hadoop:hadoop_test:
==================== Test output for //py_test_dir/tensorflow/contrib/hadoop:hadoop_test:
2018-08-08 21:40:30.356453: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
E.
======================================================================
ERROR: test_sequence_file_dataset (__main__.SequenceFileDatasetTest)
Test case for SequenceFileDataset.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1293, in _do_call
    return fn(*args)
  File "C:\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1368, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NewRandomAccessFile failed to Create/Open: \\?\T:\tmp\Bazel.runfiles__x3fyn6j\runfiles\org_tensorflow\py_test_dir\tensorflow\contrib\hadoop\python\kernel_tests\testdata/string.seq : The filename, directory name, or volume label syntax is incorrect.

; Unknown error
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[], []], output_types=[DT_STRING, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

```

2018-08-10 20:12 UTC, case540 commented
Could you fix the merge conflicts? Then I'll attempt to merge it

2018-08-10 20:25 UTC, yifeif commented
Looks like part of this PR has been merged. But let's run another import with the new commits once the conflicts have been resolved.

2018-08-10 20:31 UTC, yongtang commented
Thanks @case540 @yifeif for the help. It looks like the changes are already in though the PR is not closed automatically. When I do the `git rebase upstream/master` it have:
```
ubuntu@ip-172-31-47-125:~/tensorflow$ git rebase --continue
Applying: Fix Windows Build failures caused by os.path.join
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

ubuntu@ip-172-31-47-125:~/tensorflow$ 
```

I also checked the master and the changes are there. I think it is safe to close this PR.

2018-08-10 20:32 UTC, yongtang commented
Thanks all for the help 👍 !

2018-08-10 20:32 UTC, closed without merging

2018-08-10 20:44 UTC, yifeif commented
Perfect. Thank you @yongtang!