More documentation for keras adagrad and adadelta
tensorflow/tensorflow pull request #20011
Opened 2018-06-14 10:18 UTC by maxpumperla

Replicating PR https://github.com/keras-team/keras/pull/10410 from `keras`, as suggested by @fchollet

2018-06-18 07:36 UTC, maxpumperla commented on tensorflow/python/keras/optimizers.py
> +    which are adapted relative to how frequently a parameter gets
@caisq are you sure? this is a rather common formulation and I do mean an adaption _relative to x_ (not _adapt_ relatively, but _is_ relative), as e.g. used here:

https://books.google.es/books?id=omIpBgAAQBAJ&pg=PA58&lpg=PA58&dq=%22is+adapted+relative%22&source=bl&ots=q8_AXXgfnX&sig=vxktLNEYCCotiMMREPza-evZn-s&hl=en&sa=X&ved=0ahUKEwidlL_C19zbAhUJSsAKHZZwDsMQ6AEINDAC#v=onepage&q=%22is%20adapted%20relative%22&f=false

2018-07-03 12:49 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: It has been 18 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-07-03 14:13 UTC, caisq commented on tensorflow/python/keras/optimizers.py
> +    which are adapted relative to how frequently a parameter gets
@maxpumperla On second look, you are right. The usage of `relative to` here looks correct to me.

2018-07-31 19:03 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-10 17:09 UTC, caisq submitted a review, later dismissed

2018-08-10 18:13 UTC, maxpumperla commented
cool. can we merge this then?

2018-08-14 00:16 UTC, fchollet requested changes
Looks good, but please use an indentation of 2 (you're using 4).

2018-08-31 08:05 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-15 18:43 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-18 08:18 UTC, maxpumperla commented
@fchollet ok, fixed. good to go.

2018-10-03 18:54 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-16 02:54 UTC, merged