New function recursive_fill in image_ops
tensorflow/tensorflow pull request #20076
Opened 2018-06-16 13:33 UTC by jmlipman

Implementation of a very common post-processing operation in image processing in a efficient manner embedded in a tensorflow graph. This function will iteratively fill the "holes" of a binary 2D or 3D image until it cannot fill more. It is also possible to set the sensitivity of the method by establishing a threhsold and a maximum number of iterations. For instance, let the threshold be 8 (or actually any number below or equal to 8)

Then from this:
0 0 0 0 0
0 1 1 1 0
0 1 0 1 0
0 1 1 1 0
0 0 0 0 0

We will obtain this:
0 0 0 0 0
0 1 1 1 0
0 1 1 1 0
0 1 1 1 0
0 0 0 0 0

2018-06-16 13:36 UTC, jmlipman commented
I signed it!

2018-06-26 18:32 UTC, ringw requested changes
Thanks!

2018-06-26 18:32 UTC, ringw commented on tensorflow/contrib/image/python/ops/image_ops.py
> +    total_dims: Number of dimensions of the mask. Only 2 or 3 allowed.
We would normally get the static shape of the mask and require that the number of dimensions is set, and not pass the dimensionality as a separate argument. For example, see around line 250 of this file. Then if the number of dimensions is statically unknown, the caller can manually set it with e.g. `mask.set_shape([None, None])` for 2D.

2018-06-26 18:32 UTC, ringw commented on tensorflow/contrib/image/python/ops/image_ops.py
> +    mask: A 2D or 3D `Tensor` of 0s and 1s representing the mask to be filled.
We should always allow 4-dimensional tensors, where the 0th axis contains a batch of images to be processed independently. The docstring should also explicitly state that a 3D or 4D input is always treated as containing voxels along the last 3 dimensions, which are always filled in 3-dimensional space.

2018-07-11 12:51 UTC, tensorflowbutler commented
Nagging Reviewer @ringw: It has been 24 days with no activity and the `awaiting review` label was assigned. Can you please take a look?

2018-07-28 18:51 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-10 17:06 UTC, caisq commented
Ping @jmlipman . Can you address the comments from @ringw?

2018-08-31 08:05 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-31 19:13 UTC, ringw commented
@jmlipman Hmm, I actually think conv2d and conv3d will already treat the 0th axis as a batch of independent images, so you shouldn't really need to modify the loop. You can treat a 4-D input as a batch of 3-D voxel masks if you just skip `array_ops.expand_dims(mask, 0)` in that case. Please also just copy `test_random_3d_fills` and create a 4-D test case!

2018-08-31 19:15 UTC, ringw requested changes

2018-08-31 19:15 UTC, ringw commented on tensorflow/contrib/image/python/ops/image_ops.py
> +    # two elements, it requires two inputs as well.
What happens if you remove the second argument, and `loop_body` and `loop_cond` just reference `new_voxels` from the outer scope?

2018-08-31 19:15 UTC, ringw commented on tensorflow/contrib/image/python/ops/image_ops.py
> +    def loop_body(x, y): # pylint: disable=unused-argument
Maybe rename "x" to "current_mask"

2018-09-15 18:44 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-30 12:53 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-15 12:53 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-30 12:47 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-30 13:48 UTC, caisq commented
pinging PR author @jmlipman

2018-11-14 19:05 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-12-13 18:56 UTC, closed without merging

2018-12-13 18:57 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.