Untrunctaed normal distribution in VarianceScalingInitializer
tensorflow/tensorflow pull request #20197
Opened 2018-06-21 18:30 UTC by ppwwyyxx

#19996 
@martinwicke

2018-06-21 18:47 UTC, martinwicke approved these changes

2018-06-21 18:47 UTC, martinwicke commented on tensorflow/python/ops/init_ops.py
> +  `distribution="normal"` is a deprecated alias for "truncated_normal".
If you want, you can use @deprecated_arg_values to formally encode this (with a warning). But I think what you did here is fine.

2018-06-21 18:49 UTC, martinwicke requested changes
Actually, we should have a test. I'd mock out random_normal and truncated_normal and check that the right one is called (I think a statistical tests would be expensive or prone to be flaky, but if you can make one that isn't, go for it).

2018-06-21 23:25 UTC, martinwicke requested changes
If you find that these random ops are already seeded properly, there's nothing to do (may be done in test_session).

2018-06-22 15:48 UTC, martinwicke submitted a review, later dismissed

2018-06-22 18:02 UTC, ppwwyyxx commented
It turns out that `assert_called()` is only available in Py3.6+

2018-06-26 01:28 UTC, ppwwyyxx commented
Now the failures are: 
`//tensorflow/tools/api/tests:api_compatibility_test`. I'm not sure how that works or if I should do anything to make it pass.
`//tensorflow/core:common_runtime_ring_reducer_test`: that's probably unrelated to this PR.

2018-06-27 17:57 UTC, martinwicke commented
The api_compatibility test log has instructions on how to update the api goldens that it compares against. Please run that, you'll have to do that on MacOS or Linux, and I believe in Py2. 

@gunan is this still true? Do we have instructions for this somewhere (maybe we should).

2018-06-27 22:51 UTC, martinwicke approved these changes

2018-06-28 01:04 UTC, merged

2018-06-28 01:04 UTC, martinwicke commented
Thank for the quick PR!

2018-06-28 05:33 UTC, gunan commented
Sorry, I have not gotten around to making the test work on python 3, so it still  only works on python 2, on linux and macos. The test prints its instructions, and all instructions should already exist in the folder.

2018-06-28 17:43 UTC, ppwwyyxx commented
Apart from rebuilding with py2, another painful point is that the linter script will always lint all thousands of python sources, despite the "--incremental" option (which is explicitly not used by the linter).