make benchmark_model for tflite build
tensorflow/tensorflow pull request #20330
Opened 2018-06-27 05:30 UTC by freedomtan

benchmark_model doesn't build for desktop as reported at https://github.com/tensorflow/tensorflow/issues/20313

2018-07-05 16:43 UTC, andrewginns commented
This fix worked for me
Ubuntu 16.04
Bazel 0.10.0

2018-07-09 14:46 UTC, shashishekhar requested changes

2018-07-09 14:46 UTC, shashishekhar commented on tensorflow/contrib/lite/tools/benchmark/benchmark_params.h
> +  template <typename T>
Can you move this to protected section.

2018-07-09 14:47 UTC, shashishekhar commented on tensorflow/contrib/lite/tools/benchmark/benchmark_params.h
> +  template <typename T>
Thank you for the patch!

2018-07-09 15:43 UTC, freedomtan commented on tensorflow/contrib/lite/tools/benchmark/benchmark_params.h
> +  template <typename T>
Done. Thanks for the review.

2018-07-09 16:26 UTC, shashishekhar approved these changes

2018-07-09 16:40 UTC, shashishekhar commented
Unfortunately merging this will have to wait, see 
https://groups.google.com/a/tensorflow.org/forum/#!topic/announce/6ojJ7ykrmZ0

2018-07-16 19:53 UTC, merged