Update nasm from 2.12.02 to 2.13.03
tensorflow/tensorflow pull request #20400
Opened 2018-06-29 04:01 UTC by yongtang

This fix updates nasm from 2.12.02 (2016-07-06)
to the latest version of 2.13.03 (2018-02-07)

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-07-03 13:15 UTC, yongtang commented
/cc @gunan @yifeif to take a look

2018-07-03 17:16 UTC, yifeif requested changes
Thanks @yongtang!
small nit, do you mind run buildozer to re-order the srcs/includes alphabetically?

2018-07-03 18:48 UTC, yongtang commented
Thanks @yifeif. The PR has been updated with included files list ordered. The `XLA` test is failing but that might be unrelated I think?

2018-07-10 21:31 UTC, yifeif approved these changes

2018-07-11 16:49 UTC, merged