Adding matrix square root op
tensorflow/tensorflow pull request #20611
Opened 2018-07-07 07:20 UTC by jonathanwyatt16

This PR adds the matrix square root op support requested in #9202. 

The implementation calls the Eigen sqrt() method in a manner nearly identical to the matrix exp() and log() calls. The gradient computation is included, with an explanation given in the inline comments of linalg_grad.py. 

Any feedback would be much appreciated!

2018-07-20 00:33 UTC, rmlarsen requested changes

2018-07-20 00:33 UTC, rmlarsen commented on tensorflow/python/ops/linalg_grad.py
> +  order = shape_batch.as_list()[-1] # m
Can you change / add to this such that the gradient works for dynamic shapes?

2018-07-20 00:33 UTC, rmlarsen commented on tensorflow/python/ops/linalg_grad.py
> +    inv_ksum = _linalg.inv(math_ops.add(k1, k2))
Instead of forming the inverse and multiplying by it, can you write this in terms of linalg.matrix_solve?

2018-07-20 00:33 UTC, rmlarsen commented on tensorflow/python/ops/linalg_grad.py
> +  for flat_sqrt_matrix, flat_grad_matrix in zip(split_sqrt, split_grad):
Can you write it in batch form without looping? The batch dimension may not be known at graph construction time.

2018-07-20 00:33 UTC, rmlarsen commented on tensorflow/python/ops/linalg_grad.py
> +  # Take the differential: dA = d(RR) = RdR + dRR
nice

2018-07-30 06:06 UTC, jonathanwyatt16 commented
@rmlarsen Thank you very much for the feedback! I’ve just pushed a commit that I believe includes the requested changes.

2018-08-10 00:12 UTC, martinwicke commented
@rmlarsen do the changes look good to you?

@jonathanwyatt16 could you resolve conflicts?

2018-08-24 21:52 UTC, tensorflowbutler commented
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-28 06:29 UTC, jonathanwyatt16 commented
I've just rebased this PR again to resolve another merge conflict.

2018-09-11 18:53 UTC, tensorflowbutler commented
Nagging Assignee @martinwicke: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-21 19:27 UTC, MarziEd commented
Any update please ?

2018-09-21 20:14 UTC, martinwicke commented
I just triggered the tests. @rmlarsen can you check that your comments have been addressed?

2018-09-29 16:56 UTC, jonathanwyatt16 commented
I've just rebased this PR again to resolve another merge conflict.

2018-10-14 18:38 UTC, tensorflowbutler commented
Nagging Reviewer @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-10-15 15:55 UTC, jonathanwyatt16 commented
I've just rebased this PR again to resolve another merge conflict.

2018-10-15 18:34 UTC, martinwicke submitted a review, later dismissed

2018-10-15 18:35 UTC, martinwicke commented
I think you addressed @rmlarsen's comments. @rmlarsen, please speak up if I'm wrong.

2018-10-18 08:09 UTC, jonathanwyatt16 commented
@martinwicke I’ve just pushed a commit that I believe addresses six of the test failures--still troubleshooting the clang-format check failure. Would it be possible to trigger the tests again?

2018-10-21 20:34 UTC, MarziEd commented
Hi, 
I need this matrix square root badly. I was wondering, can I have it by building Tensorflow from source? 
Any help would be really appreciated since I am a newbie.

2018-10-22 05:51 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed a commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 05:51 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed a commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 05:56 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed another commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 06:04 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed another commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 06:28 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed another commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 06:37 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed another commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 06:44 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed another commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 07:00 UTC, jonathanwyatt16 commented
@martinwicke Thanks for triggering the tests. I've just pushed a commit that I believe addresses the clang-format test failure. Would it be possible to trigger the tests again?

@MarziEd I'm hopeful that we will be ready to merge this PR soon. Until then, feel free to clone the matrix_square_root branch from my fork and build it by following [this documentation](https://www.tensorflow.org/install/source).

2018-10-22 18:10 UTC, merged