Merge crop_and_resize with resize_bilinear_op internals
tensorflow/tensorflow pull request #20746
Opened 2018-07-12 16:56 UTC by nluehr

Improves performance of crop_and_resize.

2018-07-13 18:02 UTC, alextp requested changes
Thanks for the contribution! Overall looks good, but I have some small coding style comments.

2018-07-13 18:02 UTC, alextp commented on tensorflow/core/kernels/crop_resize_bilinear_core.h
> +    const bool clip, const int i, int& lower, int& upper, float& lerp) {
It's our style guide that out-parameters get passed as pointers and not references (const references are fine since you cannot mutate those)

2018-07-13 18:02 UTC, alextp commented on tensorflow/core/kernels/crop_resize_bilinear_core.h
> +namespace {
No anonymous namespaces in header files (this defeats the single-linkage purpose of having things in header files). Use something like ::tensorflow::internal instead

2018-07-13 18:02 UTC, alextp commented on tensorflow/core/kernels/crop_resize_bilinear_core.h
> +U cast_to(float v, float min_val, float max_val, U u_min_val, U u_max_val);
This looks like it's doing more than casting, so document intended usage?

2018-07-13 18:02 UTC, alextp commented on tensorflow/core/kernels/crop_resize_bilinear_core.h
> +#endif
Add a comment with what #if is ending here

2018-07-16 23:12 UTC, nluehr commented
@alextp Thanks for the review. Your suggestions have been incorporated. Anything else needed?

2018-07-16 23:28 UTC, alextp approved these changes

2018-07-17 18:55 UTC, merged

2018-07-23 15:52 UTC, alextp commented
It looks like this was a performance regression which we will have to roll back.

Maybe we should add a benchmark for these ops so we can try this change again without a slowdown?

2018-07-23 16:46 UTC, alextp commented
Here is the rollback: https://github.com/tensorflow/tensorflow/commit/6795a8c3a3678fb805b6a8ba806af77ddfe61628

2018-07-23 18:02 UTC, thorjohnsen commented
Hi Alex,

Can you please provide the details for the performance regression that you are seeing? We saw a noticeable performance improvement for our test cases. 

Cheers,
Thor