Fix support for renorm with float16
tensorflow/tensorflow pull request #20809
Opened 2018-07-15 02:51 UTC by Mostafa-Alaa

This PR fixes a bug when using BatchNormalization with `renorm` set and the input tensor `x` data type is float16 or bfloat16.

2018-07-24 07:06 UTC, georgepaw commented
Could we have a look at this please?

2018-07-24 14:39 UTC, qlzh727 commented
Nudge @fchollet for review.

2018-08-08 18:58 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-08-09 14:41 UTC, qlzh727 commented
Thanks for the change and sorry for the long delay. The code looks good, can you add a unit test for that? Thanks.

2018-08-10 16:29 UTC, Mostafa-Alaa commented
No problem, I'll be adding the test unit asap.

2018-08-14 00:34 UTC, fchollet requested changes
Thank you for the PR.

1) Before casting any tensor, you should do a type check to see if it needs to be cast, e.g.

```python
if x.dtype != target_dtype:
   x = cast(x, target_dtype)
```
This avoids unnecessary cast ops in the graph.

2) Every change should be unit-tested. Please add a unit test that 1) demonstrates the existence of the problem you are fixing (the test should fail without your fix), and 2) verifies the correctness of the new behavior.

Thank you!

2018-08-14 19:08 UTC, Mostafa-Alaa commented
@fchollet Thank you for the review.

For the first part I think it might not be the best to add the type check before a cast for a couple of reasons
  1) It would add a lot of redundant code before each cast.
  2) Type checking using ```x.dtype != target_dtype``` would work if ```x``` is a tensor but will fail for python lists, tuples, scalars.

A better design would be to add the type check in the cast function itself which already takes place as per [here](https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/python/ops/math_ops.py#L654) if ```x``` is a tensor, so the unnecessary cast ops wouldn't be a problem, the case where an unnecessary cast op might emerge if ```x``` is not a tensor and a ```convert_to_tensor``` call might be sufficient is already a ```TODO```.

Kindly correct me if I missed something, as for the second part I'll add it right away.

2018-08-14 22:58 UTC, Mostafa-Alaa commented
@fchollet @qlzh727 I've added the unit test kindly check and review.

2018-08-30 14:33 UTC, qlzh727 commented
Ping @fchollet for review.

2018-09-02 22:51 UTC, Mostafa-Alaa commented
@qlzh727 I've fixed the indentation problem, please rerun the checks.

2018-09-19 12:46 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-10-04 19:05 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2018-10-27 12:35 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-11-07 17:17 UTC, qlzh727 commented
@Mostafa-Alaa , can u please resolve the merge conflict? Thanks.

2018-11-22 18:47 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-12-07 18:45 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2018-12-22 18:32 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

2019-01-17 18:52 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-02-01 18:56 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-02-16 18:37 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

2019-03-03 18:39 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

2019-03-18 13:02 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

2019-04-02 21:35 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

2019-04-26 01:52 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-04-26 01:52 UTC, closed without merging