Improvement of shape function in HistogramFixedWidth
tensorflow/tensorflow pull request #20853
Opened 2018-07-16 20:13 UTC by yongtang

In the HistogramFixedWidth op, there are restrictions over the shape of range_value and nbins. The range_value should be a vector of 2 elements and nbins should be a scalar.

This fix adds the restriction to shape function of HistogramFixedWidth.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-07-16 20:50 UTC, rmlarsen requested changes

2018-07-16 20:50 UTC, rmlarsen commented on tensorflow/core/ops/math_ops.cc
> +      // value_range should be a vector.
Can you add a unit test for the shape function here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/math_ops_test.cc

2018-07-16 22:51 UTC, yongtang commented
@rmlarsen Thanks for the review. The PR has been updated. Please take a look.

2018-07-17 20:05 UTC, rmlarsen approved these changes

2018-07-18 01:42 UTC, merged