[Intel MKL] Adding support for MKL builds with AVX2.
tensorflow/tensorflow pull request #20861
Opened 2018-07-17 00:18 UTC by claynerobison

MKL-DNN ignores the compiler switches and takes code paths based on the platform detected at runtime. This commit will add support for avx2 instructions to the rest of TensorFlow.

2018-07-17 18:19 UTC, rmlarsen requested changes

2018-07-17 18:19 UTC, rmlarsen commented on tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh
> +TF_BAZEL_BUILD_OPTIONS="--config=mkl --copt=-mavx2 --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0"
Does AVX2 imply FMA and AVX? The two latter are typically more important for performance. Should we explicitly list all three?

2018-07-17 18:19 UTC, rmlarsen commented on tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh
> +#"TF_BAZEL_BUILD_OPTIONS": "'{}'" (default build option= avx)
Cruft?

2018-07-18 04:45 UTC, claynerobison commented
@rmlarsen Clarified comments and added more complete support for the haswell and sandybridge instruction sets. The mtune parameters won't add instructions, but will tune cache sizes etc for the specified architecture.

2018-07-18 19:12 UTC, rmlarsen submitted a review, later dismissed

2018-07-18 19:13 UTC, rmlarsen commented
@claynerobison Thanks!

2018-07-18 19:15 UTC, rmlarsen commented
@gunan @jhseu does this look good to you?

2018-07-18 19:18 UTC, gunan submitted a review, later dismissed

2018-07-18 19:31 UTC, jhseu submitted a review, later dismissed

2018-07-18 21:47 UTC, claynerobison commented
Sorry, @jhseu @rmlarsen @gunan further internal testing revealed that we didn't have the full haswell arch build flag being passed in to the first two containers. Fixed it with the last commit.

2018-07-18 23:02 UTC, rmlarsen approved these changes

2018-07-19 18:18 UTC, gunan approved these changes

2018-07-20 00:20 UTC, merged