[Intel MKL]: Upgrading to MKL-DNN v0.15
tensorflow/tensorflow pull request #21011
Opened 2018-07-21 01:55 UTC by mahmoud-abuzaina

This PR upgrades Intel MKL-DNN library to v0.15. It also includes a small change that makes convolution compatible with that library version.

2018-07-23 14:19 UTC, andydavis1 submitted a review, later dismissed

2018-07-24 18:36 UTC, mahmoud-abuzaina commented
@caisq these unsuccessful tests don't seem to be related to this PR. They are failing for others PR too.

2018-07-27 20:29 UTC, tatianashp commented
+@gunan Bazel file changes MKL-DNN file from .tar.gz to .zip. Will this work on Linux?

2018-07-27 20:30 UTC, tatianashp requested changes

2018-07-27 20:30 UTC, tatianashp commented on tensorflow/core/util/mkl_util.h
> +  // does not matter since MKL should never operate on this buffer.
Please fix the comment to be a complete meaningful sentence.

2018-07-27 20:31 UTC, tatianashp commented
/cc @yifeif, @gunan

2018-07-27 22:34 UTC, gunan commented
In theory, zip files also should work, but I would still keep the tar.gz files to be sure.

2018-07-27 23:07 UTC, tatianashp commented
@mahmoud-abuzaina Could you use tar.gz for MKL-DNN? Also, please fix the comment.

2018-07-27 23:19 UTC, mahmoud-abuzaina commented
@tatianashp Both are fixed.

2018-07-27 23:30 UTC, mahmoud-abuzaina commented
it seems there is a conflict introduced few minutes ago because of some change on the master branch. Rebasing now...

2018-07-27 23:46 UTC, mahmoud-abuzaina commented
Rebase is done.

2018-07-28 00:39 UTC, tatianashp approved these changes

2018-07-30 17:45 UTC, mahmoud-abuzaina commented
@gunan is this ready to be merged?

2018-07-30 17:50 UTC, gunan commented
It is in the process of merging internally.

2018-08-02 19:08 UTC, merged