[WIP] cmake: add systemlib_GRPC option.
tensorflow/tensorflow pull request #21031
Opened 2018-07-22 11:37 UTC by cdluminate

This is still a work in progress, don't merge.

I'm trying to add a cmake option to build against `libgrpc++-dev` package provided system. However I'm not sure whether it is working since it fails to build.

The build failure looks like this:
```
In file included from /dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:6:
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:105:19: error: 'RpcMethod' in namespace 'grpc' does not name a type
     const ::grpc::RpcMethod rpcmethod_SendEvents_;
                   ^~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:106:19: error: 'RpcMethod' in namespace 'grpc' does not name a type
     const ::grpc::RpcMethod rpcmethod_SendTracebacks_;
                   ^~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:107:19: error: 'RpcMethod' in namespace 'grpc' does not name a type
     const ::grpc::RpcMethod rpcmethod_SendSourceFiles_;
                   ^~~~~~~~~
[ 15%] Building CXX object CMakeFiles/tf_protos_cc.dir/tensorflow/core/protobuf/saver.pb.cc.o
[ 15%] Building CXX object CMakeFiles/tf_protos_cc.dir/tensorflow/core/protobuf/tensor_bundle.pb.cc.o
In file included from /dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:6:
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h: In constructor 'tensorflow::EventListener::WithStreamedUnaryMethod_SendTracebacks<BaseClass>::WithStreamedUnaryMethod_SendTracebacks()':
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:247:21: error: 'StreamedUnaryHandler' in namespace 'grpc' does not name a template type
         new ::grpc::StreamedUnaryHandler< ::tensorflow::CallTraceback, ::tensorflow::EventReply>(std::bind(&WithStreamedUnaryMethod_SendTracebacks<BaseClass>::StreamedSendTracebacks, this, std::placeholders::_1, std::placeholders::_2)));
                     ^~~~~~~~~~~~~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:247:70: error: expected primary-expression before ',' token
         new ::grpc::StreamedUnaryHandler< ::tensorflow::CallTraceback, ::tensorflow::EventReply>(std::bind(&WithStreamedUnaryMethod_SendTracebacks<BaseClass>::StreamedSendTracebacks, this, std::placeholders::_1, std::placeholders::_2)));
                                                                      ^
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:247:96: error: expected primary-expression before '>' token
         new ::grpc::StreamedUnaryHandler< ::tensorflow::CallTraceback, ::tensorflow::EventReply>(std::bind(&WithStreamedUnaryMethod_SendTracebacks<BaseClass>::StreamedSendTracebacks, this, std::placeholders::_1, std::placeholders::_2)));
                                                                                                ^
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h: In constructor 'tensorflow::EventListener::WithStreamedUnaryMethod_SendSourceFiles<BaseClass>::WithStreamedUnaryMethod_SendSourceFiles()':
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:267:21: error: 'StreamedUnaryHandler' in namespace 'grpc' does not name a template type
         new ::grpc::StreamedUnaryHandler< ::tensorflow::DebuggedSourceFiles, ::tensorflow::EventReply>(std::bind(&WithStreamedUnaryMethod_SendSourceFiles<BaseClass>::StreamedSendSourceFiles, this, std::placeholders::_1, std::placeholders::_2)));
                     ^~~~~~~~~~~~~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:267:76: error: expected primary-expression before ',' token
         new ::grpc::StreamedUnaryHandler< ::tensorflow::DebuggedSourceFiles, ::tensorflow::EventReply>(std::bind(&WithStreamedUnaryMethod_SendSourceFiles<BaseClass>::StreamedSendSourceFiles, this, std::placeholders::_1, std::placeholders::_2)));
                                                                            ^
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.h:267:102: error: expected primary-expression before '>' token
         new ::grpc::StreamedUnaryHandler< ::tensorflow::DebuggedSourceFiles, ::tensorflow::EventReply>(std::bind(&WithStreamedUnaryMethod_SendSourceFiles<BaseClass>::StreamedSendSourceFiles, this, std::placeholders::_1, std::placeholders::_2)));
                                                                                                      ^
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc: In constructor 'tensorflow::EventListener::Stub::Stub(const std::shared_ptr<grpc::ChannelInterface>&)':
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:30:24: error: class 'tensorflow::EventListener::Stub' does not have any field named 'rpcmethod_SendEvents_'
   : channel_(channel), rpcmethod_SendEvents_(EventListener_method_names[0], ::grpc::RpcMethod::BIDI_STREAMING, channel)
                        ^~~~~~~~~~~~~~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:30:85: error: 'grpc::RpcMethod' has not been declared
   : channel_(channel), rpcmethod_SendEvents_(EventListener_method_names[0], ::grpc::RpcMethod::BIDI_STREAMING, channel)
                                                                                     ^~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:31:5: error: class 'tensorflow::EventListener::Stub' does not have any field named 'rpcmethod_SendTracebacks_'
   , rpcmethod_SendTracebacks_(EventListener_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:31:70: error: 'grpc::RpcMethod' has not been declared
   , rpcmethod_SendTracebacks_(EventListener_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
                                                                      ^~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:32:5: error: class 'tensorflow::EventListener::Stub' does not have any field named 'rpcmethod_SendSourceFiles_'
   , rpcmethod_SendSourceFiles_(EventListener_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:32:71: error: 'grpc::RpcMethod' has not been declared
   , rpcmethod_SendSourceFiles_(EventListener_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
                                                                       ^~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc: In member function 'virtual grpc::ClientReaderWriter<tensorflow::Event, tensorflow::EventReply>* tensorflow::EventListener::Stub::SendEventsRaw(grpc::ClientContext*)':
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_service.grpc.pb.cc:36:105: error: 'rpcmethod_SendEvents_' was not declared in this scope
   return new ::grpc::ClientReaderWriter< ::tensorflow::Event, ::tensorflow::EventReply>(channel_.get(), rpcmethod_SendEvents_, context);
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~
/dev/shm/tensorflow.orig/tensorflow/contrib/cmake/build/tensorflow/core/debug/debug_serv [...]

2018-07-22 14:07 UTC, cdluminate commented
After installing a temporary `libgrpc++-dev 1.13.1` package, this patch is working.

2018-07-23 14:04 UTC, mrry approved these changes

2018-07-23 14:29 UTC, cdluminate commented
I'm about to add more similar patches that add `systemlib_XXX` options. Should I submit as different PRs, or continue pushing my commits to this PR?

When all the external dependencies can be switched to use the system provided one, I'm able to make the Debian package.

2018-07-23 15:17 UTC, mrry commented
@cdluminate Multiple small PRs will be much easier to review and merge, thanks!

2018-07-23 15:39 UTC, cdluminate commented
@mrry I see. Then please merge this if acceptable.

2018-07-24 03:07 UTC, cdluminate commented
@mrry I looked into it but I don't understand how it fails to build.

This PR adds an option that is not enabled by default, and the option is tested by me on Debian unstable. Indeed this option may not work on windows, but when we look at the cmake options from build log:

```
T:\src\github\tensorflow\cmake_build>"C:\Program Files\cmake\bin\cmake.exe" T:\src\github\tensorflow\tensorflow\contrib\cmake -A x64 -DSWIG_EXECUTABLE=C:\swig\swig.exe -DPYTHON_EXECUTABLE="C:\Python35\python.exe" -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARIES="C:\Python35\libs\python35.lib" -Dtensorflow_BUILD_PYTHON_TESTS=ON -Dtensorflow_BUILD_CC_TESTS=OFF -Dtensorflow_TF_NIGHTLY=OFF -Dtensorflow_DISABLE_EIGEN_FORCEINLINE="ON" -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX 
```

We can find out that neither `-Dsystemlib_GRPC` nor `-Dsystemlib_ALL` is defined. In the rest of the build log, GRPC is cloned and built from scratch, that means the cmake part guarded by `systemlib_GRPC == ON` is not the cause of build failure.

2018-07-24 16:23 UTC, mrry commented on tensorflow/contrib/cmake/CMakeLists.txt
> +    list(APPEND tensorflow_EXTERNAL_LIBRARIES ${grpc_LIBRARIES})
I think this line is causing the Windows build failure. AFAICT `${gprc_LIBRARIES}` isn't set when `WIN32` is true.

2018-07-24 22:01 UTC, mrry requested changes

2018-07-24 22:01 UTC, mrry commented on tensorflow/contrib/cmake/CMakeLists.txt
> +  option(systemlin_GRPC "Use the system installed library as shared objects instead of downloading GRPC and statically linking to it: GRPC" OFF)
Looks like a typo here ("systemlin_GRPC"). Can you please fix?

2018-08-08 18:59 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-09 01:37 UTC, drpngx commented
running again. I'm assuming that if it passes, then we can ignore @mrry comment, otherwise we will need the author to make that change.

2018-08-09 10:38 UTC, cdluminate commented
@drpngx @mrry I'm working on another cmake patchset for building TF on debian unstable. The suggested changes will be made in the mentioned patchset. I'll submit the patchset as another PR soon. At that time this PR will be replaced.

2018-08-09 21:31 UTC, drpngx commented
Sounds good, thanks!

2018-08-18 07:44 UTC, cdluminate commented
A new PR https://github.com/tensorflow/tensorflow/pull/21699 has been proposed to replace this one.

2018-09-02 18:35 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-17 18:57 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-17 19:41 UTC, mrry commented
Closing this because it has been superseded by #21699.

2018-09-17 19:41 UTC, closed without merging