Fix:  Validate variable dtype before restoring checkpoint
tensorflow/tensorflow pull request #21078
Opened 2018-07-24 03:21 UTC by facaiy

Fix #20487

2018-07-24 03:51 UTC, drpngx commented on tensorflow/core/kernels/save_restore_tensor.cc
> +    // Precheck dtype.
remove comment

2018-07-24 03:52 UTC, drpngx commented on tensorflow/core/kernels/save_restore_tensor.cc
> +      return errors::InvalidArgument(
It might be more user-friendly to collect all variables that have a mismatch and then report them all.

2018-07-24 03:52 UTC, drpngx requested changes
Nice, thanks!

2018-07-24 06:35 UTC, facaiy commented
Thank you for your review. Could you take a look again?

2018-07-24 15:42 UTC, drpngx requested changes
Some more minor nits

2018-07-24 15:42 UTC, drpngx commented on tensorflow/core/kernels/save_restore_tensor.cc
> +      string error_msg = string("tensor_name = ") + tensor_name +
Thanks for the change! Could you use `StrCat`? I think it'll make it easier to read.

2018-07-24 15:42 UTC, drpngx commented on tensorflow/core/kernels/save_restore_tensor.cc
> +  DataType original_dtype;
Put that inside the loop.

2018-07-24 15:42 UTC, drpngx commented on tensorflow/core/kernels/save_restore_tensor.cc
> +    string error_msg = std::accumulate(mismatched_errors.begin(),
You can use `str_util::Join`. Use `const string error_msg`.

2018-07-24 15:42 UTC, drpngx commented on tensorflow/core/kernels/save_restore_tensor.cc
> +  for (auto i : sorted_name_idx) {
Use `size_t` for clarity.

2018-07-25 05:36 UTC, facaiy commented
Thanks. I think all comments have been resolved.

2018-07-25 16:25 UTC, drpngx submitted a review, later dismissed
Thank you!

2018-07-26 06:35 UTC, facaiy commented
The failures seems unrelated, right?

2018-07-29 17:34 UTC, drpngx approved these changes

2018-07-29 20:52 UTC, drpngx commented
Unrelated failure, presumably (OOM in `scatter_nd_test`. Running again to check.

2018-08-07 23:51 UTC, facaiy commented
Build failure

```
ERROR: /Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/external/gif_archive/BUILD.bazel:8:1: Couldn't build file external/gif_archive/_objs/gif/external/gif_archive/lib/dgif_lib.o: C++ compilation of rule '@gif_archive//:gif' failed: Unexpected IO error.: Running '/Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow/_bin/xcode-locator 8.3.3' failed with code 1.
40
This most likely indicates that xcode version 8.3.3 is not available on the host machine.
41
Process exited with status 1
42
stdout: error: Unable to extract CFBundleShortVersionString from URL: file:///Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/external/aws/aws-cpp-sdk-sagemaker/include/aws/sagemaker
```

2018-08-09 01:24 UTC, merged