[INTEL MKL] Using MKL DNN sgemm
tensorflow/tensorflow pull request #21102
Opened 2018-07-24 20:53 UTC by agramesh1

Added code to call MKL DNN sgemm when building from MKL DNN opensources only.  This PR depends on https://github.com/tensorflow/tensorflow/pull/21011, so it should be merged only after 21011 is merged

2018-07-24 21:21 UTC, rmlarsen commented on tensorflow/core/kernels/matmul_op.cc
> +TF_CALL_float(REGISTER_CPU_EIGEN);
Why do we register with the "eigen" label to call MKL instead of Eigen?  Confusing...

2018-07-24 22:34 UTC, agramesh1 commented
@rmlarsen It looks like there are some unit tests that specifically require Eigen. I think a change was made by someone at Google to add the Eigen registrations. https://github.com/tensorflow/tensorflow/commit/d8697935d334bb0f2e1c9bccfe9a2a7bee9785cc . For MKL accelerated matmuls we define Eigen version as well default cpu which uses MKL.

2018-07-24 23:05 UTC, rmlarsen commented
@agramesh1 Sounds good. I'll try to remember why that is on my own time ;-)

2018-08-03 18:20 UTC, tatianashp requested changes

2018-08-03 18:20 UTC, tatianashp commented on tensorflow/core/kernels/matmul_op.cc
> +TF_CALL_int32(REGISTER_CPU);
Please factor out common registrations under #if defined(INTEL_MKL) and use defined(DO_NOT_USE_ML) only for the portion that differs, that is, TF_CALL_double(...).

2018-08-03 18:20 UTC, tatianashp commented on tensorflow/core/kernels/mkl_matmul_op.cc
> +    //Using the fortran api of mkldnn
Is this Fortran API or C++ API expecting column major layout? Please make clear.

2018-08-06 22:14 UTC, tatianashp approved these changes
Looks good. Thank you!

2018-08-08 17:28 UTC, merged