Added a normalization term to ctc_beam_search_decoder
tensorflow/tensorflow pull request #21187
Opened 2018-07-27 14:38 UTC by vsl9

Added a normalization term to ctc_beam_search_decoder in order to get correct log probabilities.
It solves https://github.com/tensorflow/tensorflow/issues/6034

The decoder is supposed to get logits as inputs instead of log probabilities, so it should compute log(softmax(logits)) inside.
The original code was relied on an equation: log(exp(x)) = x. But it didn't include a softmax normalization term: sum(exp(x_j)).

2018-08-14 21:02 UTC, ebrevdo commented
This PR looks right; and may have fixed a bug in how we handle uncentered logits.  We're discussing it and will have more to say in a little bit.

2018-08-14 21:02 UTC, ebrevdo requested changes

2018-08-14 21:02 UTC, ebrevdo commented on tensorflow/core/util/ctc/ctc_beam_search.h
> +    logsumexp += expf(raw_input(j) - max_coeff);
can you use std::exp and std::log?  or probably better, Eigen::numext::{log,exp}?

2018-08-15 15:54 UTC, vsl9 commented
@ebrevdo Sure, I switched to Eigen and updated ground truth values in Keras CTC beam search test.

2018-08-17 15:00 UTC, ebrevdo approved these changes

2018-08-17 15:01 UTC, ebrevdo commented
This is perfect, thanks!

2018-08-24 04:54 UTC, merged