make sparsemax nan and infinity safe
tensorflow/tensorflow pull request #21183
Opened 2018-07-27 09:08 UTC by AndreasMadsen

logits that are -inf will be given 0 probability and logits that are
inf will result in a nan output. Likewise if all logits are -inf the
output will also be nan.

This is done by using where operators, mostly because `0 * inf = nan`
and `x/0 = sign(x) inf` following the IEEE 754 standard. However these
results are not mathematically correct in the context of the sparsemax
algorithm.

Fixes: https://github.com/tensorflow/tensorflow/issues/15564

2018-07-31 18:03 UTC, rmlarsen requested changes
A few nits. Otherwise looks good to me.

2018-07-31 18:03 UTC, rmlarsen commented on tensorflow/contrib/sparsemax/python/ops/sparsemax_loss.py
> +    # In the paper, they call the logits z
Missing period at the end.

2018-07-31 18:03 UTC, rmlarsen commented on tensorflow/contrib/sparsemax/python/ops/sparsemax.py
> +    # In the paper, they call the logits z
Missing period at the end of sentence.

2018-08-01 09:13 UTC, AndreasMadsen commented
@rmlarsen Thanks. Please take another look :)

2018-08-16 20:06 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-31 19:33 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-15 18:50 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-17 16:01 UTC, martinwicke submitted a review, later dismissed

2018-09-17 16:01 UTC, martinwicke commented
Adding API review label to discuss moving sparsemax into core.

2018-09-26 14:32 UTC, AndreasMadsen commented
@martinwicke I will go on vacation for a week. I will fix this when I get back.

2018-10-05 18:39 UTC, AndreasMadsen commented
@martinwicke I think I fixed the issues. Can you run the CI again?

2018-10-05 21:50 UTC, rmlarsen commented
@AndreasMadsen Sorry about the delay. merging now.

2018-10-05 21:50 UTC, rmlarsen approved these changes

2018-10-05 23:17 UTC, merged