Added dim parameter to tf.losses.softmax_cross_entropy
tensorflow/tensorflow pull request #21203
Opened 2018-07-28 10:06 UTC by Siddhant085

Added dim parameter to losses.softmax_cross_entropy

2018-08-10 21:56 UTC, martinwicke requested changes

2018-08-10 21:56 UTC, martinwicke commented on tensorflow/python/ops/losses/losses_impl.py
> +    onehot_labels, logits, weights=1.0, label_smoothing=0, scope=None, dim=-1,
Should this be `axis`?

2018-08-13 22:46 UTC, martinwicke commented
(for API owners) Yes, should be axis. Fine otherwise.

2018-09-05 18:50 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 22 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-22 12:38 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-07 12:36 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-22 19:04 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-11-06 18:54 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-11-06 19:14 UTC, caisq commented
@Siddhant085 Sorry for the delay, but please take a look at the test failures, e.g.,
https://source.cloud.google.com/results/invocations/f9de5bb5-3450-4f3c-b30a-e978b5e2203b/targets/%2F%2Ftensorflow%2Fpython%2Fkernel_tests:losses_test/log

2018-11-21 18:55 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2018-12-20 18:44 UTC, closed without merging

2018-12-20 18:44 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.