Make full model before calling set_model on callback
tensorflow/tensorflow pull request #21244
Opened 2018-07-30 14:47 UTC by smatzek

Commit 1b67ccbe8006eacffd268553abd01310e8b187d6 removed the _make_train_function calls from Keras training fit_generator for eager execution.

This breaks some callbacks that depend on the entire model to be populated on the set_model or on_train_begin methods.

This commit adds the method calls back in but guarded by an eager check.  It is not doing a revert / fix because the fix that removed the calls also put a test case in for eager fit_generator testing which we want to retain.

2018-07-30 21:27 UTC, wdirons commented
@martinwicke , would you be able to review this change? We would like to get this cherry-picked into 1.10 if possible.

2018-07-31 18:22 UTC, tanzhenyu requested changes

2018-08-01 14:06 UTC, smatzek commented on tensorflow/python/keras/engine/training_generator.py
> +  if not context.executing_eagerly():
Yes I can write a test for this.

2018-08-02 18:42 UTC, smatzek commented on tensorflow/python/keras/engine/training_generator.py
> +  if not context.executing_eagerly():
Done

2018-08-10 17:45 UTC, case540 commented
Pinging for review

2018-08-30 14:15 UTC, smatzek commented
@ tanzhenyu I have completed the changes you requested.

2018-09-14 12:39 UTC, tensorflowbutler commented
Nagging Reviewer @tanzhenyu: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-09-17 17:15 UTC, smatzek commented on tensorflow/python/keras/engine/training_test.py
> +  def test_fit_generator_with_callback(self):
Done

2018-09-17 18:04 UTC, alextp submitted a review, later dismissed

2018-09-17 18:31 UTC, alextp approved these changes

2018-09-20 18:55 UTC, fchollet approved these changes
LGTM, thanks for the PR.

2018-09-28 01:27 UTC, merged