Enable int64 support for MatMul
tensorflow/tensorflow pull request #21253
Opened 2018-07-30 20:58 UTC by yongtang

This fix tries to address the issue raised in #21241 where there were no int64 support for MatMul. This fix adds int64 support for MatMul.

This fix fixes #21241.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-07-31 16:37 UTC, rmlarsen approved these changes

2018-07-31 16:38 UTC, rmlarsen requested changes

2018-07-31 16:38 UTC, rmlarsen commented on tensorflow/python/kernel_tests/matmul_op_test.py
> +      if not use_static_shape and dtype == np.int32 and dtype == np.int64:
I think you meant
```
if not use_static_shape and (dtype == np.int32 or dtype == np.int64):
```

2018-07-31 20:17 UTC, yongtang commented
Thanks @rmlarsen for the review and sorry for the bug in the test. The PR has been updated. Please take a look.

2018-08-31 15:01 UTC, tensorflowbutler commented
Nagging Reviewer @rmlarsen: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 20 days with no activity and the `awaiting review` label has been applied.

2018-09-07 14:01 UTC, justin1121 commented
Any update on getting this merged? Very interested in seeing it land!

2018-09-13 16:59 UTC, rmlarsen approved these changes

2018-10-01 18:57 UTC, tensorflowbutler commented
Nagging Assignee @case540: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-15 19:36 UTC, merged