Improve estimator.py doc-strings
tensorflow/tensorflow pull request #21286
Opened 2018-07-31 19:11 UTC by olicht

* Fixed typos
* Warped python terms with ` ...`
* A lot of tf terms are now links to their docs

2018-07-31 19:13 UTC, olicht commented
I signed it!

2018-07-31 22:57 UTC, case540 approved these changes

2018-07-31 22:58 UTC, case540 commented
Thanks for the cleanup! Much appreciated.

2018-08-10 17:37 UTC, case540 requested changes

2018-08-10 17:37 UTC, case540 commented on tensorflow/python/estimator/estimator.py
> +    config = run_config.RunConfig.replace(config, model_dir=model_dir)
Can you undo this change? I was under the impression this CL was doc updates only.

2018-08-13 16:40 UTC, merged