Add scope for node placement and numerical_hint function
tensorflow/tensorflow pull request #21321
Opened 2018-08-01 22:39 UTC by samikama

This PR adds an nvidia_scope for users to be able to fine-tune trt conversion process and a numerical_hint function for future user defined quantization ranges in TRT.

2018-08-01 22:41 UTC, samikama commented
@aaroey can you add @pooyadavoodi to reviewers please. I can't seem to be able to add him

2018-08-02 14:08 UTC, aaroey commented
@samikama I was not able to do so either. His id doesn't show up in the reviewers list.

2018-08-06 14:57 UTC, aaroey requested changes

2018-08-06 14:57 UTC, aaroey commented on tensorflow/contrib/tensorrt/BUILD
> +        "python/nvidia_scope.py",
nit: please rename to `nv_scope.py`.

2018-08-06 14:57 UTC, aaroey commented on tensorflow/contrib/tensorrt/test/base_test.py
> +class SimpleScopedGraphDefTest(trt_test.TfTrtIntegrationTestBase):
Please move this to a separate `_test.py` file.

2018-08-06 21:30 UTC, pooyadavoodi commented on tensorflow/contrib/tensorrt/python/nvidia_scope.py
> +    include      : Whether to include the node or not.
Looks like you have renamed `include` to `select` in the code but forgot to rename it in the comments?

2018-08-06 21:34 UTC, pooyadavoodi commented on tensorflow/contrib/tensorrt/python/quantization_hints.py
> +  """Add a const numerical hint node"""
Could you describe in the comment what exactly this function and the arguments `max_value` and `min_value` do?

2018-08-06 21:36 UTC, pooyadavoodi commented on tensorflow/contrib/tensorrt/test/base_test.py
> +        with nv_scope(select=False):
This is only testing `select=False`.
How about `select=True`?
How about testing other arguments of `nv_scope`?

2018-09-29 18:39 UTC, closed without merging

2018-09-29 18:41 UTC, tensorflowbutler commented
It has been 49 days that this pull-request has stalled. Please create a new pull-request with the requested changes.