[INTEL MKL] Enable Pooling3D ops
tensorflow/tensorflow pull request #21586
Opened 2018-08-13 23:57 UTC by gzmkl

The enhancement within this PR enables MKL Pooling3D operations (both average pooling and max pooling).

2018-08-17 16:22 UTC, ezhulenev requested changes
PR looks ok, except isPool2D variable name in bunch of places, that is not style compliant.

2018-08-17 17:29 UTC, gzmkl commented on tensorflow/core/kernels/mkl_pooling_ops_common.cc
> +  if (isPool2D) {
Do you have any suggestion? I am thinking to rename it to "is_pool2d". Please let me know if the new name is fine to you.

2018-08-17 19:35 UTC, gzmkl commented on tensorflow/core/kernels/mkl_pooling_ops_common.cc
> +  if (isPool2D) {
Done with code change

2018-08-18 21:29 UTC, ezhulenev approved these changes

2018-08-28 02:02 UTC, merged