Simplyfing the evaluation step
tensorflow/tensorflow pull request #21689
Opened 2018-08-17 21:08 UTC by yashk2810

Simplyfing the evaluation step by taking argmax of the softmax of the predictions instead of tf.multinomial. This makes it easier to understand.

2018-08-17 21:09 UTC, yashk2810 commented
@alextp @yifeif

2018-08-17 21:24 UTC, alextp requested changes

2018-08-18 00:44 UTC, yashk2810 commented on tensorflow/contrib/eager/python/examples/generative_examples/image_captioning_with_attention.ipynb
> +        "        predicted_id = tf.argmax(tf.nn.softmax(predictions[0])).numpy()\n",
Done

2018-08-21 19:06 UTC, yashk2810 commented
Done

2018-08-21 19:43 UTC, alextp submitted a review, later dismissed

2018-08-22 14:46 UTC, alextp approved these changes

2018-08-27 15:30 UTC, yashk2810 commented
If all the required tests have passed, shouldn't the copybara bot merge this PR?

2018-08-27 15:41 UTC, alextp commented
A lot of tests failed, apparently.

2018-09-05 11:56 UTC, yashk2810 commented
Is there any way I can run these tests?

2018-09-06 22:28 UTC, yashk2810 commented
@protoget Can you merge this?

2018-09-08 00:10 UTC, yashk2810 commented
This is the fifth time that these tests have failed lol 😂😂.

None of them are being caused to fail because of this PR.

2018-09-11 15:28 UTC, merged