assert_element_shape support partial shapes
tensorflow/tensorflow pull request #21702
Opened 2018-08-18 10:21 UTC by facaiy

Fix #16052.

2018-08-18 10:32 UTC, facaiy commented
@mrry could you take a look? Thanks.

2018-08-20 15:22 UTC, mrry requested changes

2018-08-21 04:01 UTC, facaiy commented on tensorflow/contrib/framework/python/framework/tensor_util.py
> +def _shape_tensor_equal(expected_shape, actual_shape):
Sure :-)

2018-08-21 17:46 UTC, mrry approved these changes
Thanks for the change!

2018-08-21 21:29 UTC, facaiy commented
thanks, mrry. I think the test failure(including sanity error) is unrelated.

2018-08-28 22:29 UTC, facaiy commented
Hi, do you have any update here?

2018-08-28 23:25 UTC, merged