Fix batch normalization in canned DNN Estimators
tensorflow/tensorflow pull request #21916
Opened 2018-08-28 00:08 UTC by lukmanr

This PR fixes the implementation of batch normalization in canned DNN estimators.  Batch normalization should be applied after the inputs but before the activation function.

2018-08-28 10:28 UTC, lukmanr commented
This is a fix for issue #21915.

2018-08-28 17:16 UTC, ispirmustafa requested changes
Thank you Lukman.

2018-08-28 17:16 UTC, ispirmustafa commented on tensorflow/python/estimator/canned/dnn.py
> +    def batch_norm_train_op(loss):
no need to have a different train_op

2018-08-28 17:16 UTC, ispirmustafa commented on tensorflow/python/estimator/canned/dnn.py
> +              name=hidden_layer_scope)
let's do following which will be more readable:
net = dense(activation=none)
if batch-norm:
  net = batch-norm(net)
if activation-fn:
  net = activation-fn(net)
if dropout:
  net = dropout

2018-08-30 20:40 UTC, ispirmustafa requested changes
let's have an experimental configuration argument, without touching the default behavior. something like following:

_BatchNormOptions = namedtuple(...)
def experimental_batch_norm_options(
    apply_before_activation=False,
    momentum=0.999)
    return _BatchNormOptions(apply_before_activation=...)

DNNClassifier(..., batch_norm=experimental_batch_norm_options(...))

Adding wicke for comments

2018-09-16 02:32 UTC, tensorflowbutler commented
Nagging Assignee @aaroey: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-09-24 22:54 UTC, lukmanr commented
Hi @ispirmustafa, the PR is updated per your suggestions.  I have tests for both options, apply_before_activation=False and apply_before_activation=True.

2018-09-24 23:43 UTC, ispirmustafa commented on tensorflow/python/estimator/canned/dnn.py
> +      batch_norm=None,
This should also support boolean for backward compatibility. 
You can do something like following in init-fn:
if batch_norm and batchPnorm is bool:
  batchnorm = experimental_batch...

2018-09-25 16:42 UTC, ispirmustafa commented on tensorflow/python/estimator/canned/dnn.py
> +      batch_norm=None,
Hi @lukmanr 
I couldn't see the backward compatibility. Could you please add a test to check backward compatibility: one with batch_norm=False, one with batch_norm=True.

2018-09-25 18:43 UTC, lukmanr commented
Hi @ispirmustafa, backwards compatibility is enforced in the _dnn_logit_fn_builder method.  All the cases of batch_norm=False, batch_norm=True and batch_norm=_BatchNormOptions are now covered in the dnn tests, especially since I reverted to make batch_norm=False be the default in each of the canned estimator __init__ functions.

2018-09-25 23:52 UTC, ispirmustafa requested changes
Thank you!
one final minor comment. otherwise LGTM

2018-09-25 23:52 UTC, ispirmustafa commented on tensorflow/python/estimator/canned/dnn.py
> +      after each hidden layer with default options, or a `_BatchNormOptions`
here instead of referring a private symbol '_BatchNormOptions', mention experimental_batch_norm_options

2018-09-27 16:57 UTC, lukmanr commented
Thanks - comment adjustments done.

2018-09-28 00:34 UTC, ispirmustafa approved these changes
Thank you @lukmanr!

2018-10-03 20:41 UTC, josh11b requested changes

2018-10-03 20:41 UTC, josh11b commented on tensorflow/python/estimator/canned/dnn.py
> +_BatchNormOptions = collections.namedtuple(
Make this ExperimentalBatchNormOptions, export it, and get rid of the method below. You can set the defaults for a namedtuple using e.g. https://stackoverflow.com/questions/11351032/namedtuple-and-default-values-for-optional-keyword-arguments or inheritance which would also allow you to set the docstring.

2018-10-03 20:41 UTC, josh11b commented on tensorflow/python/estimator/canned/dnn.py
> +_BatchNormOptions = collections.namedtuple(
(This was from TF API review.)

2018-10-18 18:57 UTC, tensorflowbutler commented
Nagging Assignee @aaroey: It has been 20 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-11-02 12:39 UTC, tensorflowbutler commented
Nagging Assignee @aaroey: It has been 35 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-11-20 07:48 UTC, tensorflowbutler commented
Nagging Assignee @aaroey: It has been 52 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-12-04 18:54 UTC, tensorflowbutler commented
Nagging Assignee @aaroey: It has been 67 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2019-02-01 22:41 UTC, rthadur commented
@lukmanr gentle ping to rebase your branch

2019-04-05 21:00 UTC, rthadur commented
I'm going to go ahead and close this PR due to lack of activity, If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-04-05 21:00 UTC, closed without merging