fix the comparison error when building a CPP API application
tensorflow/tensorflow pull request #21966
Opened 2018-08-30 08:33 UTC by again4you

### Summary

When building a CPP API application with "-Wall -Werror" option, `error: comparison between signed and unsigned integer expressions' occurs since return type of num_elements() is 'int64' instead of 'size_t' in ops.h to express -1. This patch fixes this bug by explicit type casting.

### related issue
* https://github.com/tensorflow/tensorflow/issues/20428

Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>

2018-08-30 08:42 UTC, again4you commented
I signed it!

2018-08-31 05:19 UTC, aaroey submitted a review, later dismissed

2018-08-31 22:14 UTC, reedwm requested changes

2018-08-31 22:14 UTC, reedwm commented on tensorflow/cc/framework/ops.h
> +      if (t.NumElements() != static_cast<int>(v.size())) {
Change the static cast to int64 instead

2018-09-04 10:28 UTC, again4you commented
@reedwm @aaroey, 
Ping!  Any comments?

2018-09-04 17:57 UTC, reedwm approved these changes

2018-09-07 13:06 UTC, again4you commented
@aaroey,
If you are satisfied with this PR, could you merge it?
Or let me know something to do.

2018-09-10 02:10 UTC, merged