Append error msg to exception for test.assert_* method
tensorflow/tensorflow pull request #22006
Opened 2018-09-01 13:41 UTC by facaiy

Fix #21988.

2018-09-07 01:29 UTC, facaiy commented
@yifeif Hi, yifei. Could you take a look? Thanks.

2018-09-13 10:04 UTC, facaiy commented
ping @yifeif :-)

2018-09-19 23:42 UTC, facaiy commented
Gentle ping @yifeif

2018-09-20 01:11 UTC, yifeif requested changes
Thanks @facaiy. Small nit.

2018-09-20 01:11 UTC, yifeif commented on tensorflow/python/framework/test_util.py
>        #
nit, here and below --> Adds more details to

2018-09-20 05:30 UTC, facaiy commented
Thank you, yifei. I fixed it :-)

2018-09-23 15:32 UTC, yifeif approved these changes

2018-09-24 21:59 UTC, merged