Add MklSlice op.
tensorflow/tensorflow pull request #22076
Opened 2018-09-05 01:04 UTC by pandaoxin

Add MklSlice op, please review.

2018-09-14 20:41 UTC, penpornk requested changes
Thank you for your PR! 

There is already an MKLSliceOp which replaces TF's Slice by default. How is MKLDnnSliceOp going to be used? Is it meant to replace MKLSliceOp eventually, or are you just going to use it in some special cases? 

Please also add some tests for the op.

2018-09-14 20:41 UTC, penpornk commented on tensorflow/core/kernels/mkl_slice_op.cc
> +      stream(stream::kind::eager).submit(net).wait();
Please add a comment that this line executes the primitive.

2018-09-17 05:44 UTC, pandaoxin commented on tensorflow/core/kernels/mkl_slice_op.cc
> +      OP_REQUIRES(context, 0 <= b && b <= input_tf_shape.dim_size(i),
Ok.

2018-09-17 05:47 UTC, pandaoxin commented
@penpornk Thanks for your detailed comments! Have modified the code. This patch uses Mkl-dnn's primitive to implement slice, while the Mklslice already exists works for Intel Mkl.

2018-09-18 17:51 UTC, penpornk requested changes
Thank you for the changes and the clarification! I think we should refactor the lambda shape function out to common_shape_fns.cc since it's almost the same as the original one in TF Slice op. Please also add tests for this op.

2018-09-18 17:51 UTC, penpornk commented on tensorflow/core/ops/array_ops.cc
>        const Tensor* sizes_value = c->input_tensor(3);
If this is the only difference from the lambda shape function in "Slice", please refactor the function and put it in [common_shape_fns.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/common_shape_fns.cc) instead. Please see [_MklConcat](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc#L3059) for example.

2018-09-19 05:12 UTC, pandaoxin commented
Thank you @penpornk ! I have modified the location of Slice shape function. And I also remember that there is a test added in mkl_layout_pass test(tensorflow/core/graph/mkl_layout_pass_test.cc). Besides, there already exists some UT tests for Slice op.

2018-09-20 22:17 UTC, penpornk requested changes
Thank you @pandaoxin! I have some last minor changes. Please also run clang-format. It seems there are some extra blank lines. 

Tests: My bad. Sorry about that! For some reason I forgot about the test in `mkl_layout_pass_test.cc`.

2018-09-21 01:27 UTC, pandaoxin commented
Hi @penpornk , thanks for your advice! Modifications done.

2018-09-21 17:01 UTC, penpornk submitted a review, later dismissed
Thank you again for the PR!

2018-09-21 20:06 UTC, martinwicke commented
@pandaoxin can you look into the lint errors?

2018-09-23 02:35 UTC, pandaoxin commented
@martinwicke The failed test said that:
'Missing dependency: //tensorflow/contrib/eager/python:parameter_server',
which seems not related to my committed code, while the lint error as well(cannot find my file).
Could you help me check the error? Thanks very much!

2018-09-24 16:03 UTC, martinwicke commented
Yeah, that does look unrelated. I'll try again, maybe it was broken at head.

2018-09-24 17:17 UTC, martinwicke commented
@pandaoxin Can you change the CHECKs for either DCHECKs or even better proper errors? We're trying to remove CHECKs since they have the ability to kill production serving system, while errors (non-OK Status) can be handled gracefully.

2018-09-25 02:18 UTC, pandaoxin commented
@martinwicke Ok, thank you! Code modified.

2018-09-25 02:44 UTC, penpornk commented
Thank you! Please also change `CHECK_NOTNULL` to `DCHECK_NOTNULL` and `LOG(FATAL)` to `LOG(DFATAL)` (in `mkl_slice_op.cc`).

2018-09-25 03:17 UTC, pandaoxin commented
Hi @penpornk , since there is neither DCHECK_NOTNULL nor DFATAL, I turn both of them into DCHECK. Please review.

2018-09-25 06:27 UTC, penpornk commented
There might be a better substitute. Let's wait for @martinwicke.

2018-09-25 16:34 UTC, martinwicke commented
DCHECK for both these is fine.

2018-09-25 16:44 UTC, penpornk approved these changes

2018-09-26 01:16 UTC, pandaoxin commented
Thank you! @penpornk @martinwicke

2018-09-27 01:29 UTC, pandaoxin commented
@penpornk @martinwicke Merge button still unavailable, seems two approving reviews required?

2018-09-27 04:49 UTC, martinwicke commented
It's making its way through the infra. The merge button is meaningless -- we use our scripts to merge anyway.

2018-09-27 04:58 UTC, pandaoxin commented
@martinwicke ok, thanks.

2018-09-27 06:16 UTC, merged