Fix dynamic rnn comment
tensorflow/tensorflow pull request #22188
Opened 2018-09-10 10:53 UTC by pengwa

2018-09-10 19:37 UTC, yifeif requested changes

2018-09-10 19:37 UTC, yifeif commented on tensorflow/python/ops/rnn.py
> +      input.
super nit, input -> inputs.

2018-09-11 01:04 UTC, pengwa commented on tensorflow/python/ops/rnn.py
> +      input.
pl

2018-09-11 01:06 UTC, pengwa commented
@yifeif have fixed as you suggested. please help check.

2018-09-11 05:41 UTC, yifeif approved these changes
Thanks @pengwa!

2018-09-11 17:00 UTC, merged