[xla] Improve validation of Broadcast shape
tensorflow/tensorflow pull request #22303
Opened 2018-09-16 22:49 UTC by Keno

If one misreads the semantics of this instruction, it's easy to cause
an out of bounds access into the dimensions here. Add an extra check
to return a proper error to the user rather than crashing in that
case.

Ref #22130

2018-09-18 21:15 UTC, michaelisard commented
This should be reviewed by someone on the XLA team. @eliben would you assign someone?

2018-09-19 15:21 UTC, eliben requested changes
Just one small comment.

2018-09-19 15:41 UTC, Keno commented on tensorflow/compiler/xla/service/hlo_verifier.cc
> +  const Shape& broadcast_shape = broadcast->shape();
I meant to use it for the other instance of this value also, but I can also just get rid of it. Up to you.

2018-09-19 16:42 UTC, meheffernan submitted a review, later dismissed
Looks good to me. Thanks!

2018-09-20 12:06 UTC, eliben commented on tensorflow/compiler/xla/service/hlo_verifier.cc
> +  const Shape& broadcast_shape = broadcast->shape();
I'd get rid of it because the char savings here are minimal and not worth the potential for confusion/inconsistency

2018-09-24 14:41 UTC, qlzh727 commented
@Keno, can u address the last comment, and I will merge the change afterwards. Thanks.

2018-09-24 15:50 UTC, Keno commented
Yes, I will. Been a bit busy, but I'll push an update shortly.

2018-10-04 00:46 UTC, Keno commented
I had pushed an update to this PR to address the review. Doesn't look like @tensorflowbutler noticed though.

2018-10-04 12:04 UTC, eliben approved these changes

2018-10-08 19:28 UTC, merged