[INTEL MKL] Fix typo error of an environment variable
tensorflow/tensorflow pull request #22324
Opened 2018-09-17 19:26 UTC by gzmkl

Change the name of an environment variable
from
     TF_MKL_OPTIMIZE_PRIMITVE_MEMUSE
to
    TF_MKL_OPTIMIZE_PRIMITIVE_MEMUSE

2018-09-18 14:44 UTC, qlzh727 commented
Can u fix the cl format lint error?

https://source.cloud.google.com/results/invocations/c3df27fd-ff97-4e5f-b9a6-8f309dcf940b/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_clang_format_out/log

diff --git a/tensorflow/core/util/mkl_util.h b/tensorflow/core/util/mkl_util.h
index 5ea8f2ee47..06c3598f85 100644
--- a/tensorflow/core/util/mkl_util.h
+++ b/tensorflow/core/util/mkl_util.h
@@ -2041,7 +2041,7 @@ class MklPrimitiveFactory {
   static inline bool IsPrimitiveMemOptEnabled() {
     bool is_primitive_mem_opt_enabled = true;
     TF_CHECK_OK(ReadBoolFromEnvVar("TF_MKL_OPTIMIZE_PRIMITIVE_MEMUSE", true,
-          &is_primitive_mem_opt_enabled));
+                                   &is_primitive_mem_opt_enabled));
     return is_primitive_mem_opt_enabled;
   }

2018-09-18 16:58 UTC, gzmkl commented
I fixed a couple of coding style issues by running cpplint.py utility. 
But I am not sure if it addressed the issue that Qianli pointed out (not so obvious to me :)).
Thanks!

2018-09-20 00:24 UTC, tatianashp requested changes

2018-09-21 16:09 UTC, gzmkl commented on tensorflow/core/util/mkl_util.h
> +#ifndef TENSORFLOW_TENSORFLOW_CORE_UTIL_MKL_UTIL_H_
Well, I ran cpplint.py and somehow the utility complains about it.

If it is fine, let me change it back, to make it consistent across all header files.

2018-09-21 16:31 UTC, tatianashp commented
Yes, please change it back to be consistent with the coding style in other
files in this directory.

On Fri, Sep 21, 2018 at 9:16 AM, Guozhong Zhuang <notifications@github.com>
wrote:

> *@gzmkl* commented on this pull request.
> ------------------------------
>
> In tensorflow/core/util/mkl_util.h
> <https://github.com/tensorflow/tensorflow/pull/22324#discussion_r219550058>
> :
>
> > @@ -13,8 +13,8 @@ See the License for the specific language governing permissions and
>  limitations under the License.
>  ==============================================================================*/
>
> -#ifndef TENSORFLOW_CORE_UTIL_MKL_UTIL_H_
> -#define TENSORFLOW_CORE_UTIL_MKL_UTIL_H_
> +#ifndef TENSORFLOW_TENSORFLOW_CORE_UTIL_MKL_UTIL_H_
>
> Well, I ran cpplint.py and somehow the utility complains about it.
>
> If it is fine, let me change it back, to make it consistent across all
> header files.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/22324#discussion_r219550058>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA8ObAIMIpSb0aaey7HehSpbKJjVCJECks5udRDZgaJpZM4WsjrE>
> .
>

2018-09-21 16:48 UTC, gzmkl commented on tensorflow/core/util/mkl_util.h
> +#ifndef TENSORFLOW_TENSORFLOW_CORE_UTIL_MKL_UTIL_H_
Done by changing back the macro def.

2018-09-21 17:01 UTC, gzmkl commented on tensorflow/core/util/mkl_util.h
> +                      : memory::format::ncdhw;  // not support avx2 for 3d yet.
Done

2018-09-21 18:48 UTC, tatianashp approved these changes

2018-09-25 17:19 UTC, gzmkl commented
Hi Tatiana, 
I noticed that this PR is "merge" blocked due to some CI build issue. 
Please let me know what I need follow up.
Regards,
Guozhong

2018-09-28 20:13 UTC, merged