[Features] Enable partitioned variable assignments
tensorflow/tensorflow pull request #22473
Opened 2018-09-23 12:46 UTC by wangsiyu

`PartitionedVariable` cannot use `assign`, `assign_add` and `assign_sub` functions in graph mode. In this pull request, I have enabled these functions in graph mode. This is the first step to enable variables partitioner usage in distribution strategy.

2018-09-23 12:53 UTC, wangsiyu commented
@ebrevdo @theweiho Any coding style and design review comments are welcome. @yuefengz This maybe the first step to enable variable partitioned usage in distribution strategy

2018-09-23 13:02 UTC, yangjunpro commented
Thank @wangsiyu for the work. 
@yuefengz  @ebrevdo @theweiho any feedback from your sides are highly appreciated.

Talk is cheap, show the code.

Siyu directly made this PR to ensure the communication could be more efficient.

2018-09-25 05:47 UTC, wangsiyu commented
Unrelated failures? @ebrevdo @theweiho I noticed master branch also failed with these unitest especially in  XLA.

2018-09-26 02:59 UTC, facaiy commented
@alextp Hi, Alexandre. The PR seems to be duplicated with tf 2.0 tensorflow/community#11 , right?

> symbols like tf.assign* will be removed in favor of methods in tf.Variable

Could you make a comment or reassign? Should we accept the PR or reject?

2018-09-26 14:31 UTC, alextp requested changes
Can you move these changes to assign_* methods on PartitionedVariable, to be more 2.0-friendly?

2018-09-26 15:18 UTC, wangsiyu commented
Sorry，I am confused. These assign* methods have already implemented in PartitionedVariable class and I think it convents to 2.0？

2018-09-26 15:28 UTC, yangjunpro commented
@alextp 

Hi Alex,

I am also a little bit puzzled as to your comments.

It is appreciated if you could directly comment on our code commit so it would be  easier to ensure we are on the same page.

Thanks.

2018-09-26 16:30 UTC, alextp commented
I meant this NotImplementedError: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variables.py#L2400

If we can replace this error with an implementation of assign, assign_add, etc for PartitionedVariable this will be more 2.0-friendly.

2018-09-26 23:24 UTC, alextp submitted a review, later dismissed

2018-09-26 23:27 UTC, facaiy commented on tensorflow/python/ops/variables.py
> +          "Multi-axis partition assign_fn is not supported "
missing %s ?

2018-09-28 11:02 UTC, wangsiyu commented
@alextp I have refined the coding style according to @facaiy . Please review again. Thanks.

2018-09-29 09:51 UTC, wangsiyu commented
Any update for me？

2018-10-01 12:17 UTC, alextp approved these changes

2018-10-01 14:41 UTC, merged