Reduce the size of //tensorflow/tools/pip_package:simple_console_windows
tensorflow/tensorflow pull request #22483
Opened 2018-09-24 13:42 UTC by meteorcloudy

To fix https://github.com/tensorflow/tensorflow/issues/22390

/cc @gunan

2018-09-24 17:58 UTC, gunan submitted a review, later dismissed

2018-09-24 21:08 UTC, angersson commented on configure.py
> +  # include it's dependencies. This is for:
Nit: "its"

2018-09-24 21:08 UTC, angersson commented on configure.py
> +  #   1. Run python tests against system installed TF pip package.
Nit: "Running python tests against the"

2018-09-24 21:09 UTC, angerson requested changes
I pointed out some small typos. Thanks for this!

2018-09-24 21:09 UTC, angersson commented on configure.py
> +  #   2. Avoid redundant files in //tensorflow/tools/pip_package:simple_console_windows,
Nit: "Avoiding"

2018-09-25 07:37 UTC, meteorcloudy commented on configure.py
> +  # include it's dependencies. This is for:
Done

2018-09-25 07:38 UTC, meteorcloudy commented on configure.py
> +  #   1. Run python tests against system installed TF pip package.
Done.

2018-09-25 07:38 UTC, meteorcloudy commented on configure.py
> +  #   2. Avoid redundant files in //tensorflow/tools/pip_package:simple_console_windows,
Done

2018-09-25 07:39 UTC, meteorcloudy commented
Thanks for the review!

2018-09-25 22:19 UTC, gunan commented
@meteorcloudy could you send this internally instead?

2018-09-25 22:19 UTC, closed without merging

2018-09-26 07:54 UTC, meteorcloudy commented
Will do it!