Fix validating callback type for distributed Keras
tensorflow/tensorflow pull request #22587
Opened 2018-09-28 06:57 UTC by EFanZh

2018-10-02 00:33 UTC, fchollet reviewed
Thank you for your PR. Could you please add a quick unit test?

2018-10-09 04:17 UTC, EFanZh commented
@fchollet I have added some unit tests.

2018-10-23 12:53 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-10-23 13:35 UTC, caisq commented
@fchollet Can you review this again? Thanks.

2018-11-07 19:14 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-11-22 18:49 UTC, tensorflowbutler commented
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2019-04-04 22:30 UTC, rthadur commented
@EFanZh please resolve conflicts

2019-04-05 17:32 UTC, rchao requested changes
Thanks for the PR! To move forward, we'd like to request the following changes:

1) distributed_training_utils.py has been moved to tensorflow/python/keras/distribute, so let's sync and apply the change there
2) Add a test target in BUILD file

2019-04-08 22:24 UTC, rchao requested changes

2019-04-08 22:24 UTC, rchao commented on tensorflow/python/keras/distribute/distributed_training_utils_test.py
> +from __future__ import absolute_import, division, print_function
Please avoid multiple import and have them on separate lines. Thank you!

2019-04-09 00:48 UTC, rchao approved these changes

2019-04-12 17:25 UTC, rchao commented
Hello, the content of this PR has been added in https://github.com/tensorflow/tensorflow/commit/c89c25b1f82394ebcefb7bf14dd8e96791aab328#diff-f107d83c80db7670b1808be2ebbf9999 and thus I'll close this PR. Thank you for the contribution.

2019-04-12 17:25 UTC, closed without merging