print error information, when the os is not supported
tensorflow/tensorflow pull request #22600
Opened 2018-09-28 16:43 UTC by knightXun

2018-09-28 19:06 UTC, asimshankar requested changes
Thanks!

2018-09-28 19:06 UTC, asimshankar commented on tensorflow/go/test.sh
> +  echo "Only support Linux/Darwin.System $OS is not supported"
Nit: Add a space between. Or make this:

```sh
echo "The test script works only on Linux or Darwin, not $OS."
```

2018-09-29 17:41 UTC, knightXun commented
＠asimshankar I think that's ok

2018-09-30 09:19 UTC, asimshankar approved these changes
Thanks!

2018-10-02 22:52 UTC, merged