Ios lite simple app improvment
tensorflow/tensorflow pull request #22764
Opened 2018-10-05 11:04 UTC by gorBaghdasaryan

2018-10-05 16:00 UTC, rmlarsen commented
@gorBaghdasaryan your PR contains a bunch of XCode files. Did you submit those by mistake?

2018-10-06 07:57 UTC, gorBaghdasaryan commented
@rmlarsen no, not by chance. all these changes are needed

2018-10-23 12:53 UTC, tensorflowbutler commented
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-11-07 19:14 UTC, tensorflowbutler commented
Nagging Reviewer @petewarden: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2018-12-04 18:56 UTC, tensorflowbutler commented
Nagging Reviewer @petewarden, @miaout17: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-12-10 19:00 UTC, miaout17 requested changes

2018-12-10 19:00 UTC, miaout17 commented on tensorflow/contrib/lite/examples/ios/simple/AppDelegate.m
> +// Copyright 2015 Google Inc. All rights reserved.
Could you change this to...

> // Copyright 2018 The TensorFlow Authors. All Rights Reserved.


Thanks

2018-12-10 19:00 UTC, miaout17 commented on tensorflow/contrib/lite/examples/ios/simple/ios_image_load.h
> -#endif  // TENSORFLOW_CONTRIB_LITE_EXAMPLES_IOS_SIMPLE_IOS_IMAGE_LOAD_H_
Missing `#ifdef` here. This doesn't compile

2018-12-10 19:00 UTC, miaout17 commented on tensorflow/contrib/lite/examples/ios/simple/RunModelViewController.mm
> +// Copyright 2017 The TensorFlow Authors. All Rights Reserved.
// Copyright 2018 The TensorFlow Authors. All Rights Reserved.

Thanks!

2019-02-22 23:00 UTC, petewarden commented
Sorry for the slow response on this. It looks like a good improvement to the sample app, but one of our goals is to keep the code for the example as simple as possible, so it might be best as a separate github project. If you do create one, we'd be happy to link to it from documentation.

2019-02-22 23:00 UTC, closed without merging