allows cond_v2 to return output tensors in nested structures
tensorflow/tensorflow pull request #22951
Opened 2018-10-12 20:46 UTC by pythonanonuser

2018-10-12 20:49 UTC, pythonanonuser commented
CLA has been signed. My github has 2 emails linked to it, but I signed the CLA using the primary email address for my github account. Not sure if this is causing an issue.

2018-10-12 22:09 UTC, skye commented
Can you try signing the CLA using the other email too?

2018-10-12 22:19 UTC, skye requested changes
Looks good!

2018-10-12 22:19 UTC, skye commented on tensorflow/python/kernel_tests/control_flow_ops_py_test.py
> +  # Test for list
nit: you can remove these comments above the tests, since the test name gives you the same info now

2018-10-12 22:19 UTC, skye commented on tensorflow/python/kernel_tests/control_flow_ops_py_test.py
> +  def testEmbeddedListOutput(self):
nit: we usually use the term "nested" instead of "embedded" (e.g. change this to testNestedListOutput)

2018-10-12 22:19 UTC, skye commented on tensorflow/python/ops/cond_v2.py
> +    # Make sure both structured outputs for both graphs have the same structure
nit: move this check into _check_same_outputs

2018-10-12 23:41 UTC, pythonanonuser commented
Formatting changes made. CLA signed with both emails tied to this github account. Let me know if you need anything else on this. Thanks!

2018-10-13 00:37 UTC, skye submitted a review, later dismissed
Thanks! It looks like the googlebot is still unhappy with the CLA, I'll try to find someone who can help us out.

2018-10-13 01:40 UTC, pythonanonuser commented
@skye Please re-approve. Accidentally forgot to remove some redundant code in the last commit.

2018-10-13 01:42 UTC, pythonanonuser commented
Also CLA issue may be stemming from the fact that my git email was configured improperly, and I was committing as Ubuntu instead of @pythonanonuser. Problem fixed in this latest commit.

2018-10-15 15:42 UTC, willnorris commented
The first commit (1c10a57) is authored by "Ubuntu <ubuntu@ip-172-31-7-102.us-west-2.compute.internal>".  That need to be updated to properly be attributed to you.  That should resolve the CLA checking issue.

2018-10-15 17:14 UTC, skye commented
@pythonanonuser, I think you need to rebase in and force push in order to rewrite the previous commits that are still authored by "Ubuntu" (I would rebase -i + squash to make sure, ping me offline if you need help with this).

2018-10-15 17:14 UTC, skye commented
@willnorris thanks for your help!

2018-10-17 21:07 UTC, pythonanonuser commented
@skye @willnorris just rebased and squashed this as 1 commit. Hopefully this fixes all issues?

2018-10-17 23:37 UTC, harshini-gadige commented
@pythonanonuser Request you to sign the CLA. Thanks !

2018-10-17 23:51 UTC, pythonanonuser commented
@harshini-gadige CLA has been signed

2018-10-18 14:27 UTC, skye commented
Hey @pythonanonuser, the commit is still authored by Ubuntu. Can you do:
git commit --amend --author=<the proper email address>
And repush the branch?

2018-10-19 19:38 UTC, skye submitted a review, later dismissed

2018-10-19 19:39 UTC, skye commented
Yay CLA works!

I think you may need to pull the latest changes and repush your branch, but otherwise LGTM.

2018-10-24 01:35 UTC, closed without merging