[XLA] Add simple HLO if conversion pass
tensorflow/tensorflow pull request #22974
Opened 2018-10-14 23:52 UTC by Keno

kConditional operations are currently generally disallowed in parallel contexts
(e.g. in mapped computations). The julia XLA frontend was running into this limitation
quite a bit, because existing julia code tends to use the terniary operator for select,
e.g. to describe the derivative of a `max` call (and thus a `relu`) - see the
definitions of the derivatives of `max` at
https://github.com/JuliaDiff/DiffRules.jl/blob/master/src/rules.jl#L94

To support these sorts of patterns, add a simple if conversion pass that converts
conditionals in parallel context by equivalent select operations (which are well supported),
i.e. a computation like:

```
if {
 %pif = () parameter(0)
 ROOT %cif = f32[] constant(0)
}

else {
 %pelse = () parameter(0)
 ROOT %celse = f32[] constant(1)
}

mapped {
 %a = f32[] parameter(0)
 %b = f32[] parameter(1)
 %lt = pred[] less-than(%a, %b)
 %t = () tuple()
 ROOT %conditional = f32[] conditional(%lt, %t, %t), true_computation=if, false_computation=else
}

ENTRY comp {
 %p1 = f32[1000]{0} parameter(0)
 %p2 = f32[1000]{0} parameter(1)
 ROOT %mapped = f32[1000]{0} map(%p1, %p2), dimensions={0}, to_apply=mapped
}
```

gets rewritten to

```
mapped {
 %a = f32[] parameter(0)
 %b = f32[] parameter(1)
 %cif = f32[] constant(0)
 %celse = f32[] constant(1)
 %lt = pred[] less-than(%a, %b)
 ROOT %select = f32[] select(%lt, %cif, %celse)
}

ENTRY comp {
 %p1 = f32[1000]{0} parameter(0)
 %p2 = f32[1000]{0} parameter(1)
 ROOT %mapped = f32[1000]{0} map(%p1, %p2) dimensions={0} to_apply=mapped
}
```

To keep things simple, this is accomplished by first rewriting the conditional
to two calls and a select and then inlining the individual calls. Naturally,
the transformation is only applied if the called computation do not
have side effects (which they generally don't if they're in parallel
context). In the future, it would be good to let MapInliner further
simplify this to an implicitly mapped select.

2018-10-16 19:53 UTC, sanjoy requested changes

2018-10-16 19:53 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.cc
> +StatusOr<bool> DoConditionalToSelect(HloInstruction* conditional) {
Please either make this `static` or put in an anonymous namespace.

2018-10-16 19:53 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.cc
> +  for (HloComputation* computation : conditional->called_computations()) {
Up to you, but I think `conditional->true_computation()->HasSideEffects() || conditional->false_computation()->HasSideEffects()` looks a bit cleaner.

2018-10-16 19:53 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.cc
> +          conditional->shape(), HloOpcode::kSelect,
I suspect this may need to be a `kTupleSelect` if `conditional->shape()` is a tuple.

2018-10-16 19:53 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.cc
> +        if (node.context() != CallContext::kParallel) return Status::OK();
We prefer using braces even for single statement `if` and `for`.

2018-10-16 19:53 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.cc
> +          conditional->shape(), HloOpcode::kSelect,
Also, I think we need to broadcast the condition when creating the select if `conditional->shape()` is not a scalar.

2018-10-16 23:14 UTC, sanjoy submitted a review, later dismissed

2018-10-16 23:14 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.h
> +// are not allowed to appear (e.g. mapped computation)
Just to be clear, this is a backend constraint right (that we can't codegen this) not a general constraint (i.e. the un-transformed IR still passes the verifier)?  If yes, would be nice to note explicitly.

2018-10-24 23:40 UTC, sanjoy commented
Hi Keno,

It'd be great if you could fix it on the PR itself; I believe the error message has a diff?  If you run into any unforeseen issues let me know and I'll send you a buildified BUILD file.

2018-11-05 03:50 UTC, Keno commented
bump

2018-11-05 04:12 UTC, sanjoy requested changes
lgtm with comments addressed but not actually lgtm'ing since I'm not sure if the code will be auto merged automatically without giving you time to address the comments.

2018-11-05 04:12 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.h
> +// are not allowed to appear (e.g. mapped computation)
Ok, can you instead s/not allowed/legal but not supported/ or something like that?  I don't want folks to get misled by this comment about what HLO is allowed.

2018-11-05 04:12 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.cc
> +    condition = computation->AddInstruction(HloInstruction::CreateBroadcast(
This can be a new utility in tensorflow/compiler/xla/service/hlo_creation_utils.h

2018-11-05 04:48 UTC, sanjoy commented on tensorflow/compiler/xla/service/conditional_to_select.cc
> +    condition = computation->AddInstruction(HloInstruction::CreateBroadcast(
Making the existing switch between select and triple-select sgtm.

2018-11-05 19:39 UTC, Keno commented
I've addressed those two comments. @davidel had some thoughts on the split of work here between HLO and the backend, but I think the conclusion ended up being that while we should fix this in the backend also, the HLO-level pass in nevertheless useful.

2018-11-20 18:26 UTC, sanjoy submitted a review, later dismissed

2018-12-05 19:01 UTC, tensorflowbutler commented
Nagging Assignee @ymodak: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-12-13 18:42 UTC, ymodak commented
@Keno Can you please resolve the conflicts? Thanks!

2018-12-15 22:19 UTC, Keno commented
done

2019-02-13 22:00 UTC, ymodak commented
@Keno gentle ping. Can you please resolve the conflicts? Thanks!

2019-02-13 22:05 UTC, Keno commented
Well, I keep doing that but nothing happens after. Happy to do another rebase, but this PR tends to accumulate conflicts quickly.

2019-02-13 22:20 UTC, sanjoy submitted a review, later dismissed

2019-02-13 22:21 UTC, sanjoy commented
@ymodak I'm happy to manually pull in the CL to Google and check it in (and resolve the merge conflicts internally).  However it is missing the `[ready to pull]` label -- can I just add that label directly?

2019-02-27 00:12 UTC, yifeif commented
@Keno do you mind resolving the conflicts? Thank you!

2019-02-27 18:05 UTC, Keno commented
I was under the impression @sanjoy would do that on import

2019-02-27 18:42 UTC, sanjoy commented
> I was under the impression @sanjoy would do that on import

I tried to do that but it seems like we don't have a way to pull in a change with conflicts into piper (so that I can later resolve the conflicts).  @yifeif - is that accurate?

2019-03-13 21:06 UTC, rthadur commented
@Keno @sanjoy @yifeif any updates on resolving conflicts ?

2019-03-13 21:11 UTC, Keno commented
Let me just do it. Sounds like that's easiest.

2019-03-13 21:28 UTC, rthadur commented
> Let me just do it. Sounds like that's easiest.

thank you

2019-03-16 17:53 UTC, sanjoy approved these changes

2019-03-18 21:36 UTC, merged

2019-03-20 01:56 UTC, Keno commented
Thanks, @sanjoy.