[XLA] Sink constants into the conditional computation in while loops
tensorflow/tensorflow pull request #22984
Opened 2018-10-15 10:46 UTC by georgepaw

Modify the WhileLoopConstantSinking  pass so that it sinks the constants into the while loop conditional as well. From my (limited) experiments, this helps the `WhileLoopAnalysis::ComputeWhileLoopTripCount` function in being able to evaluate and get the trip count (at least for simple while loops created by `dynamic_rnn`s where the original conditional is `and`ed with the max_iterations) .

2018-10-16 19:41 UTC, sanjoy requested changes

2018-10-16 19:41 UTC, sanjoy commented on tensorflow/compiler/xla/service/while_loop_constant_sinking.cc
> +  auto invariant_conditional_gte_index_to_inst =
Let's use an explicit type for these.

2018-10-16 19:41 UTC, sanjoy commented on tensorflow/compiler/xla/service/while_loop_constant_sinking.cc
> +    if (invariant_value.opcode() != HloOpcode::kConstant) continue;
We always use braces for `if` and `for`.

2018-10-16 19:41 UTC, sanjoy commented on tensorflow/compiler/xla/service/while_loop_constant_sinking.cc
> +    // Check if there is a corresponding GTE in while_conditional
Please end comments with period (here and elsewhere).

2018-10-16 19:41 UTC, sanjoy commented on tensorflow/compiler/xla/service/while_loop_constant_sinking.cc
> +    auto* invariant_cond_gte = it->second;
Would be nice to use an explicit type here and below.

2018-10-16 19:41 UTC, sanjoy commented on tensorflow/compiler/xla/service/while_util.h
> +  static std::map<int64, HloInstruction*> GetGTEsMapForWhileConditional(
Do we care about stable ordering here?  If not, let's use ` absl::flat_hash_map`.

2018-10-16 19:41 UTC, sanjoy commented on tensorflow/compiler/xla/service/while_util.cc
> +        inst->operand(0) == while_conditional.parameter_instruction(0)) {
Can we instead walk the use list of `while_conditional.parameter_instruction(0)`?

2018-10-16 19:41 UTC, sanjoy commented on tensorflow/compiler/xla/service/while_util.cc
> +      result[inst->tuple_index()] = inst;
What if there are multiple GTEs with the same index?

2018-10-22 09:20 UTC, georgepaw commented
Thank you for the review comments! I think I have addressed all of them now.

2018-10-22 16:01 UTC, sanjoy requested changes
Just one minor nit.

2018-10-22 19:44 UTC, georgepaw commented on tensorflow/compiler/xla/service/while_loop_constant_sinking.cc
> +      invariant_conditional_gte_index_to_inst =
Done!

2018-10-22 19:47 UTC, georgepaw commented
Done, thank you 👍

2018-10-22 19:47 UTC, sanjoy approved these changes
Looks great!

2018-11-07 21:10 UTC, merged