Update feature_column_v2_test.py
tensorflow/tensorflow pull request #23124
Opened 2018-10-20 09:11 UTC by larrytin

2018-11-06 18:56 UTC, tensorflowbutler commented
Nagging Reviewer @rohan100jain: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-11-21 18:57 UTC, tensorflowbutler commented
Nagging Reviewer @rohan100jain: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2018-12-04 21:20 UTC, ymodak approved these changes

2018-12-04 23:53 UTC, ymodak commented
Thanks @larrytin  Can you please resolve the conflicts?

2018-12-05 19:52 UTC, rmlarsen commented
@larrytin could you please resolve the conflict?

2019-01-23 22:12 UTC, rthadur commented
@larrytin  gentle ping

2019-02-20 16:57 UTC, rohan100jain requested changes

2019-02-20 16:57 UTC, rohan100jain commented on tensorflow/python/feature_column/feature_column_v2_test.py
> +      # Each row is formed by concatenating `one_hot_body_style`,
I think the original comment was fine. We sort the feature column names and this seems okay to me.

2019-04-21 16:31 UTC, rthadur commented
closing this PR based on latest comments from reviewer.

2019-04-21 16:31 UTC, closed without merging