MKL DNN: cleaning mkl softamx kernel
tensorflow/tensorflow pull request #23168
Opened 2018-10-22 18:20 UTC by ashraf-bhuiyan

Cleaned up Intel MKL ML related code. The intention is to stop supporting MKL ML (closed source library) code and have the MKL DNN code (Open sourced library) to be the default code path.

2018-11-01 17:18 UTC, ashraf-bhuiyan commented
Hi, if possible, can you please take a look at this PR. It is a very small change to one file to clean up the MKL ML code.

2018-11-16 17:44 UTC, ashraf-bhuiyan commented
Hi, if possible, can you please take a look at this PR. It is a very small change to one file to clean up the MKL ML code.

2018-11-16 18:56 UTC, xiejw commented
sorry, did not notice it was assigned to me. I am not familiar with this code. Can you find another reviewer? thanks

2018-11-16 21:31 UTC, tatianashp requested changes
The code looks good. A few nits on the comments.

2018-11-16 21:31 UTC, tatianashp commented on tensorflow/core/kernels/mkl_softmax_op.cc
>        // n = batch, c = channels, t = sequence lenght, h = height,
typo

2018-11-16 21:31 UTC, tatianashp commented on tensorflow/core/kernels/mkl_softmax_op.cc
>        // n = batch, c = channels, t = sequence lenght, h = height,
'sequence lenght'

2018-11-16 21:31 UTC, tatianashp commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +              "Input dims must be <= 5 and >=1"));
Please place on the same line if it fits into 80 characters.

2018-11-27 00:37 UTC, ashraf-bhuiyan commented
I will wait a few days to commit this PR, since another PR also changing the file.

2018-12-13 18:46 UTC, ymodak commented
@ashraf-bhuiyan Can you please resolve the conflicts? Thanks!

2018-12-28 18:39 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-01-07 18:22 UTC, ashraf-bhuiyan commented
It will be worked on. Need to fix a conflicted file.

2019-01-10 16:40 UTC, ashraf-bhuiyan commented
I merged the softmax file with the master, and removed the conflict, and thus, it seems lots of changes. But, it has actually fewer changes comparing to master, about 6 to 7 lines.

2019-01-15 20:04 UTC, ashraf-bhuiyan commented
@tatianashp if possible please have a look in this PR. Only few line changes in this PR.

2019-01-17 19:09 UTC, tatianashp approved these changes

2019-01-17 19:09 UTC, tatianashp commented
Looks good. Thanks for fixing the typos.

2019-03-06 00:05 UTC, rthadur commented
code has been merged to master.

2019-03-06 00:05 UTC, closed without merging