verbs: make sure the memory region to send from is registered
tensorflow/tensorflow pull request #23221
Opened 2018-10-24 19:17 UTC by guoshimin

Fixes #23220

2018-10-25 17:35 UTC, xiejw commented
I am not the expert for this. Re: Admin, please find a new reviewer.

2018-10-26 06:49 UTC, yanivbl6 commented
Thanks for the PR. Did you test it on 1.9?
I am asking because verbs is currently fails on build. 

When testing it on my own branch, it did seem to fix #23220, but I am worried about the registered memory not being properly de-registered.

2018-10-26 07:35 UTC, guoshimin commented
Yes I tested it on 1.9. Does the mr get deregistered in `RdmaTensorResponse::Destroy()`?

2018-10-26 08:11 UTC, yanivbl6 commented
It is normally dereged from MRDestroy, called on iterator erasure 
`void RdmaMemoryMgr::EvictMemoryRegion(void* addr, size_t length);`

You can use InsertMemoryRegion to register memory so it can also be used in the future (using FindMemoryRegion) and automatically evicted in the end.

2018-10-26 10:46 UTC, byronyi commented
The cost of registration on every single transmission is higher than cost of actual transmission for small sized tensor (could be up to 32KB). 

I believe @yanivbl6 is working on a better fix.

2018-10-26 13:29 UTC, yanivbl6 commented
If you use InsertMemoryRegion, next attempts to access the same memory should work as with FindMemoryRegion without extra registration, so performance will be fine in the long run as long it's not just random data access (unlikely in the case of graph-computation).

I don't want people to wait for my fix as I am having an hard time finding the time to work on this.
that being said, I would like to have this tested on master due to the major changes pushed to the memory allocation mechanism since 1.9 (In the same commit that also broke the build).

2018-10-31 16:37 UTC, poxvoculi commented
I defer to @yanivbl6 on any changes to contrib/verbs.  When he's ready to accept, I will approve.  (I can't test any of this code.)

2018-10-31 21:01 UTC, guoshimin commented
@yanivbl6 Thanks for your explanation. Changed to use InsertMemoryRegion. Not sure what allocator_name should be set to. Seems it's only for display purposes.

2018-11-08 05:39 UTC, yanivbl6 requested changes

2018-11-08 05:40 UTC, yanivbl6 commented
Sorry, I added the comments but forgot to submit the review.

2018-11-08 06:01 UTC, guoshimin commented on tensorflow/contrib/verbs/rdma.cc
> +              src_addr_, tensor_bytes, "what should go here?");
Done

2018-11-08 06:08 UTC, yanivbl6 commented
OK with me.
noting again that verbs is still broken in master branch, so one would need to cherry-pick this patch from older version you get this fix.

2018-11-09 18:56 UTC, guoshimin commented
@yanivbl6 Do you know what's the last release version where verbs still built?

@poxvoculi Can you approve? Thanks!

2018-11-09 20:22 UTC, poxvoculi submitted a review, later dismissed

2018-11-10 07:44 UTC, yanivbl6 commented
The patch that broke the code was [33170cc)](https://github.com/tensorflow/tensorflow/commit/33170cc661f3838aa7d0d7fc19bb0c6ba4812a3c)

The last version I tried myself which worked was 1.9, but 1.10 might also work.

2018-11-24 18:32 UTC, tensorflowbutler commented
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-12-27 07:52 UTC, 2sin18 commented
I patched this PR in r1.12 branch with other commits cherry-picked from master branch, but "local protection error" still exists for slim based inception model.

2018-12-27 07:57 UTC, byronyi commented
I believe the issue has been fixed in #24250 without this PR. @2sin18 @guoshimin could you confirm?

2018-12-27 08:11 UTC, 2sin18 commented
I have cherry-pick your commit from master, but it still not works in r1.12. I will try this patch in r1.13 branch. Thanks.

2018-12-27 11:51 UTC, 2sin18 commented
I add `force_gpu_compatible=True` to `GPUOptions`, and #24250 works without this PR.

2018-12-27 12:45 UTC, byronyi commented
You could patch 7dea8383bbb97a1e78cdece876e083b22191974e as well.

2019-01-07 19:38 UTC, guoshimin commented
I can't test the new fix since we are still using 1.9.  I'll close my PR for now.

2019-01-07 19:38 UTC, closed without merging