Added org.tensorflow.Tensor.create() methods that are an order of mag…
tensorflow/tensorflow pull request #23288
Opened 2018-10-26 08:16 UTC by w-adamski

…nitude faster on android.

2018-10-31 02:53 UTC, asimshankar commented
@w-adamski : Thanks for the contribution! Did you see the note about the CLA? We can only look at the change after the CLA has been signed. Thanks!

2018-11-05 09:13 UTC, w-adamski commented
Yes, I've seen the note about CLA, but apparently signing it by a corporation takes more time than signing by an individual.

2018-12-05 19:01 UTC, tensorflowbutler commented
Nagging Assignees @asimshankar, @protoget: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-12-05 19:23 UTC, asimshankar commented
@w-adamski : Wasn't sure if your last comment meant that you do intend to figure out the CLA with your employer or if you're abandoning this PR. Could you clarify? Thanks!

2018-12-06 08:54 UTC, w-adamski commented
As far as I know the CLA will be signed. Possibly (but it's not certain) this month.

2019-03-15 14:31 UTC, w-adamski commented
I signed it!

2019-05-29 20:00 UTC, asimshankar commented
@sjamesr : Mind taking a look? Seems reasonable to me

2019-07-05 17:34 UTC, sjamesr approved these changes

2019-08-20 13:18 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-09-05 19:56 UTC, rthadur requested changes
please address internal test failures , thank you

2019-09-05 19:56 UTC, rthadur commented on tensorflow/java/src/main/java/org/tensorflow/Tensor.java
> +    setArray(t.nativeHandle, data);
error: cannot find symbol
    setArray(t.nativeHandle, data);
              ^
  symbol:   variable nativeHandle
  location: variable t of type Tensor<Integer>

2019-09-05 19:56 UTC, rthadur commented on tensorflow/java/src/main/java/org/tensorflow/Tensor.java
> +    setArray(t.nativeHandle, data);
error: cannot find symbol
    setArray(t.nativeHandle, data);
              ^
  symbol:   variable nativeHandle
  location: variable t of type Tensor<Integer>

2019-09-05 19:56 UTC, rthadur commented on tensorflow/java/src/main/java/org/tensorflow/Tensor.java
> +    setArray(t.nativeHandle, data);
same as above

2019-09-05 19:56 UTC, rthadur commented on tensorflow/java/src/main/java/org/tensorflow/Tensor.java
> +    setArray(t.nativeHandle, data);
same as above

2019-09-16 09:36 UTC, herbakamil commented
This PR has currently very low priority for us so if anyone needs that feel free to update it / use it in your own PR.

Anyway I will add it into the bottom of our backlog so maybe some day we'll go back to it if it makes sense.

2019-09-16 18:00 UTC, rthadur commented
@herbakamil thank you for letting us know , please let us know once you are ready with new changes i can reopen it .

2019-09-16 18:00 UTC, closed without merging