Added note on weight decay for tf.contrib.opt optimizers.
tensorflow/tensorflow pull request #23363
Opened 2018-10-30 05:51 UTC by Ouwen

Addresses: #22763

2018-10-30 20:27 UTC, alextp requested changes

2018-11-14 19:12 UTC, tensorflowbutler commented
Nagging Assignee @akshaym: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-11-15 20:20 UTC, alextp approved these changes

2018-11-30 18:58 UTC, tensorflowbutler commented
Nagging Assignee @akshaym: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-12-05 01:29 UTC, merged