Fixed technical issues with README.md
tensorflow/tensorflow pull request #23757
Opened 2018-11-14 23:33 UTC by claytonjian

Improved the README.md file to adhere to more technical writing standards. Concision was improved, errors were fixed, and formality is increased

Fixes #23756

2018-11-15 00:31 UTC, claytonjian commented
I signed it!

2018-11-29 19:17 UTC, tensorflowbutler commented
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-11-29 22:02 UTC, drpngx requested changes

2018-11-29 22:02 UTC, drpngx commented on README.md
> +between them.  This flexible architecture enables computation to CPUs or GPUs in a desktop, server, or mobile device without rewriting
It's a bit subjective, but I think it's better to be less formal in an intro document. I'd undo this.

2019-02-08 01:47 UTC, ymodak commented
@claytonjian Can you solve the merge conflicts to move ahead with the PR? Thanks

2019-02-26 12:56 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-03-27 13:00 UTC, closed without merging

2019-03-27 13:00 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.