Add Sigmoid, Tanh ops and unit tests.
tensorflow/tensorflow pull request #23908
Opened 2018-11-21 21:32 UTC by trevor-m

Add conversion for all three activation types supported by TensorRT's IActivationlayer: Relu, Tanh, Sigmoid. Also adds unit tests for all three ops.

2018-11-22 06:06 UTC, aaroey requested changes
Thanks for the PR!

2018-11-22 06:06 UTC, aaroey commented on tensorflow/contrib/tensorrt/convert/convert_nodes_test.cc
> +    return input;
nit: return 0.

2018-11-22 06:06 UTC, aaroey commented on tensorflow/contrib/tensorrt/convert/convert_nodes_test.cc
> +  {
nit: remove this outer curly braces.

2018-11-22 06:06 UTC, aaroey commented on tensorflow/contrib/tensorrt/convert/convert_nodes_test.cc
> +          << op_name << "(" << input_data[i] << ") should be equal to "
We don't need these logs, if the check fails it should print similar logs.

2018-11-22 06:06 UTC, aaroey commented on tensorflow/contrib/tensorrt/convert/convert_nodes_test.cc
> +      EXPECT_TRUE(TrtDimsEqualsArray({1, 2, 3}, output.tensor()->getDimensions()))
nit: use ExpectTrtDimsEqualsArray

2018-11-26 22:37 UTC, aaroey commented
@trevor-m thanks for the fix. Would you please fix the clang-format problem as well?

2018-11-27 18:08 UTC, trevor-m commented
Hey Lambda, thanks for the review.
Unfortunately we can't use ASSERT_TRUE(false) because the function has a non-void return value. See https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/7clymoTb3A0
Let me know if you know a work around or better alternative than EXPECT_TRUE().

Also, is there a way I can run the clang-format check locally?

Thanks again!

2018-11-27 19:32 UTC, aaroey commented
@trevor-m Thanks for the fixes. For formatting we can just run the clang-format tool, but that will change the untouched lines as well, and I don't think we have good solution to that.

2018-11-28 18:33 UTC, harshini-gadige commented
> @trevor-m Thanks for the fixes. For formatting we can just run the clang-format tool, but that will change the untouched lines as well, and I don't think we have good solution to that.

@trevor-m  Any update please ?

2018-11-28 18:39 UTC, trevor-m commented
> > @trevor-m Thanks for the fixes. For formatting we can just run the clang-format tool, but that will change the untouched lines as well, and I don't think we have good solution to that.
> 
> @trevor-m Any update please ?

Update on what?

2018-11-28 18:46 UTC, harshini-gadige commented
> > > @trevor-m Thanks for the fixes. For formatting we can just run the clang-format tool, but that will change the untouched lines as well, and I don't think we have good solution to that.
> > 
> > 
> > @trevor-m Any update please ?
> 
> Update on what?

I see this PR has not been approved by @aaroey yet. So wanted to check if there are any changes pending from your side.

2018-11-28 18:50 UTC, trevor-m commented
> > > > @trevor-m Thanks for the fixes. For formatting we can just run the clang-format tool, but that will change the untouched lines as well, and I don't think we have good solution to that.
> > > 
> > > 
> > > @trevor-m Any update please ?
> > 
> > 
> > Update on what?
> 
> I see this PR has not been approved by @aaroey yet. So wanted to check if there are any changes pending from your side.

Ah I see, I believe I have addressed all of @aaroey's requested changes.

2018-11-28 20:50 UTC, trevor-m commented
> Hi @trevor-m, it looks like `binary_tensor_weight_broadcast_test` and `multi_connection_neighbor_engine_test` are failing, would you help to run them to make sure they are not broken?
> 
> Thanks.

Hey Lambda, it looks like those tests were using sigmoid to purposely break the graph into separate engines. I've updated them to use `sin` instead which we use in other tests for the same purpose.

2018-11-28 20:56 UTC, aaroey commented on tensorflow/contrib/tensorrt/test/binary_tensor_weight_broadcast_test.py
> +        # sin is used to break the graph into separate segments since it is an
Please remove these comments and use `self.trt_incompatible_op()` instead.

2018-11-28 21:58 UTC, aaroey submitted a review, later dismissed

2018-11-28 21:58 UTC, aaroey commented
Thanks @trevor-m for the fix, I'll retry.

2018-11-28 22:58 UTC, aaroey commented
Hi @trevor-m, sorry but we got one more errors:

```
tensorflow/contrib/tensorrt/test/binary_tensor_weight_broadcast_test.py:29: [W0611(unused-import), ] Unused math_ops imported from tensorflow.python.ops

tensorflow/contrib/tensorrt/test/multi_connection_neighbor_engine_test.py:28: [W0611(unused-import), ] Unused gen_math_ops imported from tensorflow.python.ops

tensorflow/contrib/tensorrt/test/multi_connection_neighbor_engine_test.py:29: [W0611(unused-import), ] Unused math_ops imported from tensorflow.python.ops
```

Would you help to fix them as well?
Thanks.

2018-11-28 23:24 UTC, aaroey approved these changes

2018-11-29 16:31 UTC, merged