[tflite] python script for object detection w/ SSD
tensorflow/tensorflow pull request #23994
Opened 2018-11-27 08:39 UTC by freedomtan

Add a TFLite Python script that uses SSD to detect objets.

2018-12-12 18:46 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2018-12-27 18:40 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-01-11 18:56 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-01-26 18:36 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-02-10 18:37 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

2019-02-25 19:11 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

2019-03-12 12:57 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

2019-03-27 13:00 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

2019-04-11 13:02 UTC, tensorflowbutler commented
Nagging Reviewer @jch1: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 104 days with no activity and the `awaiting review` label has been applied.

2019-04-29 11:56 UTC, gbaned commented
@jch1, @achowdhery Hi, Could you PTAL and approve

2019-05-14 13:08 UTC, tensorflowbutler commented
Nagging Reviewer @jch1, @achowdhery: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-05-15 04:30 UTC, Dayananda-V requested changes

2019-05-15 04:30 UTC, Dayananda-V commented on tensorflow/lite/examples/python/ssd_object_detection.py
> +  parser.add_argument("--image", help="image to be classified")
suggest to define default value under argument declaration and parse argument with short key as well.
same comment can be applicable for all argument.

2019-05-15 04:30 UTC, Dayananda-V commented on tensorflow/lite/examples/python/ssd_object_detection.py
> +  if input_details[0]['dtype'] == type(np.float32(1.0)):
hope this is can be replace with better one as 
`input_details[0]['dtype'] == np.float32`

2019-05-15 04:30 UTC, Dayananda-V commented on tensorflow/lite/examples/python/ssd_object_detection.py
> +  if show_image:
keep 'matplotlib.pyplot' package under show_image flag.

2019-05-15 04:30 UTC, Dayananda-V commented on tensorflow/lite/examples/python/ssd_object_detection.py
> +    plt.show()
Suggest to provide save test result when show_image is disable as default option. Same will update on document as well.

2019-07-12 18:20 UTC, jdduke commented
Hi @freedomtan, thanks for the PR. We're no longer adding additional examples in lite/examples; most of our examples have moved to the new [TF examples repo](https://github.com/tensorflow/examples/tree/master/lite). We're still trying to determine how we want to present Python-based examples. Once we have that figured out, I'll reopen the PR and we can proceed. Thanks again for your contribution, hopefully we can make this work.

2019-07-12 18:20 UTC, closed without merging

2019-07-13 00:04 UTC, freedomtan commented
@jdduke Thanks. As you know, Python examples won't work on Android devices, but they work on many other environments and could helpful when testing if models work well with TFLite. I saw people asking for example scripts for object detection and segmentation several times before.

2019-07-15 17:03 UTC, jdduke commented
Absolutely, Python examples are important and we'd like to expand the set of such examples. Once we have a path forward for how/where we'd like to host them we can get back to you about this particular contribution. Thanks again for your patience.