Fix discrepancy between tf.placeholder and tf.sparse.placeholder
tensorflow/tensorflow pull request #24048
Opened 2018-11-29 19:37 UTC by yongtang

When working on sparse placeholder I noticed that if shape is presented with `None` in any dims, the shape information is remvoed from sparse.placeholder. So `(None, 4)` will be `(None, None)`.

This is different from tf.placeholder:
```
root@ubuntu:/v# python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> v1 = tf.placeholder(tf.float32, (None, 4))
>>> v1.get_shape()
TensorShape([Dimension(None), Dimension(4)])
>>> v2 = tf.sparse.placeholder(tf.float32, (None, 4))
>>> v2.get_shape()
TensorShape([Dimension(None), Dimension(None)])
>>>
```

This fix adds the fix so that tf.placeholder and tf.sparse.placeholder
behaves the same.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2018-11-29 21:47 UTC, alextp requested changes

2018-11-29 21:47 UTC, alextp commented on tensorflow/python/ops/array_ops.py
> +    shape = [dim if dim is not None else -1 for dim in shape]
I don't think putting -1s here is the right fix. Specifically, I worry that downstream users of that shape tensor will not be able to process the -1s in the elements.

My understanding of the shape tensor in sparse tensors is that, when evaluated, it should be the full shape of the sparse tensor, which this change breaks.

Can you add a longer test for the kind of code you want to support?

2019-02-13 21:50 UTC, ymodak commented
@yongtang gentle ping! Can you please address the changes requested? Thanks!

2019-03-01 07:18 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-03-29 13:04 UTC, closed without merging

2019-03-29 13:04 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.