TFTRT: Prevent segments with no inputs
tensorflow/tensorflow pull request #24130
Opened 2018-12-03 19:33 UTC by trevor-m

If a segment is created with no inputs, the TFTRT currently crashes during runtime. This PR simply prevents the TRT engine for that segment from building so that the native TF fallback will be executed instead of crashing.

This issue came up for me recently trying to convert ConvS2S which uses weight normalization. I've created an issue for the potential bug in constant folding: https://github.com/tensorflow/tensorflow/issues/24083.

This may become redundant when the node validation is working for all nodes - that would disqualify these nodes from even being considered for a segment because their inputs are weights not tensors. Nevertheless it is a good check to have.

2018-12-05 18:05 UTC, pooyadavoodi commented
Looks good to me.

@azaks2 @smit-hinsu 
Could you please review.

2018-12-05 18:57 UTC, smit-hinsu commented
Looks good to me and will approve once https://github.com/tensorflow/tensorflow/pull/24183 is merged to update the CODEOWNERS file.

2018-12-05 19:16 UTC, smit-hinsu commented on tensorflow/contrib/tensorrt/convert/convert_graph.cc
> +  if (inputs.size() == 0) {
```suggestion
  if (inputs.empty()) {
```

2018-12-05 19:17 UTC, smit-hinsu requested changes
Minor suggestion.

2018-12-05 20:28 UTC, smit-hinsu submitted a review, later dismissed

2018-12-06 17:47 UTC, smit-hinsu commented
Trevor, the commit to use `empty` method has your personal email address as author and that email has not signed the CLA.

2018-12-06 18:01 UTC, trevor-m commented
> Trevor, the commit to use `empty` method has your personal email address as author and that email has not signed the CLA.

Oh I see, thanks for pointing that out.

2018-12-06 18:21 UTC, smit-hinsu approved these changes

2018-12-07 00:37 UTC, merged