Update op_level_cost_estimator.cc
tensorflow/tensorflow pull request #24160
Opened 2018-12-05 07:07 UTC by MikalaiDrabovich

wccftech.com/nvidia-gtx-1080-gp104-die-shot
techpowerup.com/gpu-specs/geforce-rtx-2080-ti.c3305

2018-12-05 19:42 UTC, jlebar commented on tensorflow/core/grappler/costs/op_level_cost_estimator.cc
> +      // Turing
It's different for SM 6.0 vs SM 6.1 and 6.2:

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#architecture-6-x

7.x (Turing or Volta) is apparently also 64 cores per SM: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#architecture-7-x

"Cores per SM" is sort of a meaningless figure, but I think it *should* be fair to use it to compute gflops, if that's all you're doing.

2018-12-05 19:42 UTC, jlebar requested changes
I don't think this is correct.

2018-12-06 00:05 UTC, MikalaiDrabovich commented
yes, as per @jlebar link, SM 6.1 and 6.2 should have 128, not 64 'cores', otherwise grappler will probably optimize for 2x lower gflops then available.

2018-12-06 02:07 UTC, rmlarsen commented
@MikalaiDrabovich will you update the PR to reflect the documentation from NVIDIA?

2019-04-04 22:12 UTC, rthadur commented
> @MikalaiDrabovich will you update the PR to reflect the documentation from NVIDIA?

@MikalaiDrabovich gentle ping to update PR

2019-04-26 01:59 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-04-26 01:59 UTC, closed without merging