[tensor_forest] Add total variance in the final element of tree leaf vector
tensorflow/tensorflow pull request #24269
Opened 2018-12-10 19:30 UTC by yupbank

To support total variance on forest level, we need to add total variance to tree level

2018-12-11 17:23 UTC, nataliaponomareva requested changes
Do you want to really add it to contrib or may be to canned directly?
It might be easier too (eg we can extend the proto instead of relying on any)

2018-12-11 17:32 UTC, yupbank commented on tensorflow/contrib/decision_trees/proto/generic_tree_model.proto
> +  repeated Member members = 100;  // A higher id for more readable printing.
ah... sorry, my auto lint does that... let me revert this

2018-12-21 16:44 UTC, yupbank commented on tensorflow/contrib/decision_trees/proto/generic_tree_model.proto
> +    // 6) for regression problem, len(vector) = n_component + 1
hey, so right now the option is being controlled by the `tree_path`, but we do export them into the tree.

2019-04-05 18:23 UTC, nataliaponomareva requested changes

2019-04-05 18:23 UTC, nataliaponomareva commented on tensorflow/contrib/tensor_forest/kernels/v4/leaf_model_operators.cc
> +  const float total_variance = TotalVariance(stat);
Can you add a test to make sure it returns what u think it does

2019-07-11 12:37 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-07-11 19:26 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-07-11 19:26 UTC, closed without merging