Make tf.image.convert_image_dtype() float to int conversions symmetric
tensorflow/tensorflow pull request #24283
Opened 2018-12-11 06:28 UTC by drkoller

When `tf.image.convert_image_dtype()` converts floating-point image data to integer types, it is currently scaling by `dtype.max + 0.5` and then truncating. This biases the converted values, and is not symmetric with respect to  the integer to floating-point transformation, which simply scales the integer values by `1. / dtype.max`. As a result, integer data values that are read from an image file, converted to floats in the [0, 1.0] range, perturbed only very slightly, and then converted back to an integer image type, may result in different pixel values than the original image (which is undesirable).

This PR changes the floating-point to integer conversion such that values are scaled by simply multiplying by `dtype.max` and rounding, which results in better numerical stability and symmetry with the conversion in the opposite direction.

The type conversion method in this PR is also more consistent with other image processing libraries. For example, the `scikit-image` (`skimage`) behavior is documented as:

> By default...floating point values are scaled and rounded to the nearest integers, which minimizes back and forth conversion errors.

2019-01-18 07:05 UTC, drkoller commented
Nagging Reviewer @drpngx: It's been over a month since I submitted this PR. The suggested code change is minor but improves the numerical robustness of image type conversions. Is there any further information that I can provide to help with a timely review?

2019-02-01 18:58 UTC, tensorflowbutler commented
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-02-16 18:39 UTC, tensorflowbutler commented
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-03-03 18:40 UTC, tensorflowbutler commented
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 44 days with no activity and the `awaiting review` label has been applied.

2019-03-18 13:03 UTC, tensorflowbutler commented
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 59 days with no activity and the `awaiting review` label has been applied.

2019-04-02 21:36 UTC, tensorflowbutler commented
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 74 days with no activity and the `awaiting review` label has been applied.

2019-04-17 13:02 UTC, tensorflowbutler commented
Nagging Reviewer @drpngx: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 89 days with no activity and the `awaiting review` label has been applied.

2019-04-29 11:48 UTC, gbaned commented
@drpngx Hi, Could you PTAL and approve

2019-05-16 06:44 UTC, gbaned commented
@annarev @yhliang2018  Can any of you please review this ?

2019-05-30 13:01 UTC, tensorflowbutler commented
Nagging Reviewer @annarev, @yhliang2018: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-06-03 17:11 UTC, alextp requested changes
Can you add a unit test?

I also think this a potentially API-breaking change, so we should make a tf.image.convert_image_dtype_v2() with the new behavior.

2019-06-11 10:22 UTC, gbaned commented
@drkoller Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

2019-06-26 12:39 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-06-27 07:56 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-06-27 07:56 UTC, closed without merging