Constant Folding: Only apply size limit if size of tensor is increasing
tensorflow/tensorflow pull request #24478
Opened 2018-12-20 18:43 UTC by trevor-m

Many kernels have sizes larger than the constfolding limit of 10mb. Many networks use identity ops or pointwise scaling ops on these kernels. The size limit prevents constant folding in these cases even though the output of the folding would not have increased the size of the protobuf, and in many cases would actually decrease it by removing the ops.

In TFTRT, TRT requires weights to be known statically so we rely heavily on constant folding. If a weight is not constant folded, we are unable to convert that layer into TRT.

This fixes https://github.com/tensorflow/tensorflow/issues/24083

2018-12-20 19:47 UTC, skye submitted a review, later dismissed
Nice, thanks!

2018-12-20 19:47 UTC, skye commented
FYI @rmlarsen @ezhulenev

2018-12-20 19:49 UTC, trevor-m commented
Sorry, I think I wasn't using the correct input size originally.

There is still a problem where sometimes it thinks the input size is 0 (occuring with Square op in https://github.com/tensorflow/tensorflow/issues/24083)

2018-12-20 19:55 UTC, skye requested changes

2018-12-20 19:55 UTC, skye commented on tensorflow/core/grappler/optimizers/constant_folding.cc
> +  size_t input_size = 0;
nit: maybe total_inputs_size or similar?

2018-12-20 19:55 UTC, skye commented on tensorflow/core/grappler/optimizers/constant_folding.h
> +                              NodeDef* node, size_t input_size = 0);
Document what input_size is

2018-12-20 19:57 UTC, skye commented
Ah I keep reviewing as you're commenting/making changes :) Are you planning to address the Square op issue in this PR? If so, please let me know when it's ready to review.

2018-12-20 20:53 UTC, trevor-m commented
> Ah I keep reviewing as you're commenting/making changes :) Are you planning to address the Square op issue in this PR? If so, please let me know when it's ready to review.

Sorry about that, I discovered the problems shortly after creating the pr. I will let you know after I have investigating the square issue. Thanks for reviewing!

2018-12-20 22:52 UTC, trevor-m commented
@skye I have fixed the problem now.

2018-12-20 23:10 UTC, skye submitted a review, later dismissed

2018-12-20 23:10 UTC, skye commented on tensorflow/core/grappler/optimizers/constant_folding.h
> +  // than input_size (optional).
nit: rename input_size to original_size or something, so it's more clear what this means outside of the context of how you call it.

2018-12-21 05:17 UTC, pooyadavoodi commented on tensorflow/core/grappler/optimizers/constant_folding.cc
> +        strings::StrCat("Can't fold ", name, ", its size would be too large"));
I suggest to print both the limit and the size here in case of failure.

2018-12-21 21:16 UTC, ezhulenev submitted a review, later dismissed

2018-12-21 21:17 UTC, ezhulenev commented
Thanks for the fix.

2018-12-28 02:39 UTC, ezhulenev approved these changes

2018-12-30 06:48 UTC, merged