Fix python 3.7 build error due to astor
tensorflow/tensorflow pull request #24493
Opened 2018-12-21 04:21 UTC by ilango100

This upgrade is needed for tensorflow to be properly built with Python 3.7, since astor 0.6.2 is python 3.7 incompatible due to usage of 'async'.

2018-12-21 17:00 UTC, gunan approved these changes

2018-12-21 17:01 UTC, gunan requested changes
The URLs do not match. Could you change the 2nd url to download from pypi?

2018-12-21 17:11 UTC, ilango100 commented
Yup Fixed!

2018-12-21 17:37 UTC, gunan approved these changes

2018-12-21 17:37 UTC, gunan commented
Thanks for the contribution!

2019-01-04 13:45 UTC, stonebig commented
is there still hope for Tensorflow on Python-3.7 ?

2019-01-04 14:55 UTC, ilango100 commented
Sure! tf-nightly builds of 1.13 version are already python 3.7 compatible: [tf-nightly](https://pypi.org/project/tf-nightly/). But unfortunately, not for Windows. But building for windows from source with Python 3.7 (with GPU support) is possible now with this PR.

2019-01-04 17:04 UTC, hgadig commented
@gunan Can these 2 failures related to Mac be ignored to proceed to "Ready to Pull" ?

2019-01-08 19:16 UTC, gunan commented
I just noticed. THis is a PR to the release branch.
We cannot accept this. Please recreate this to the master branch.

2019-01-08 19:16 UTC, closed without merging