[Intel MKL] Enable pad+fusedconv fusion
tensorflow/tensorflow pull request #24538
Opened 2018-12-24 01:49 UTC by guizili0

2019-01-08 01:03 UTC, penpornk requested changes
Thank you very much for your PR and so sorry for my delay!

2019-01-08 02:45 UTC, guizili0 commented on tensorflow/core/graph/mkl_layout_pass.cc
> +      if (padding != "VALID") {
@penpornk we only merge the case that pad only have one output node _FusedConv2D.
below code did this check.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/graph/mkl_layout_pass.cc#L2644

2019-01-08 07:48 UTC, penpornk commented on tensorflow/core/graph/mkl_layout_pass.cc
> +      if (padding != "VALID") {
@guizili0 Got it. Sorry I always forgot about this!

2019-01-08 08:32 UTC, guizili0 commented on tensorflow/core/graph/mkl_layout_pass.cc
> +      if (padding != "VALID") {
@penpornk that's fine.

2019-01-08 08:33 UTC, guizili0 commented on tensorflow/core/kernels/mkl_fused_ops_test.cc
> +    conv_comp.PerformConversion(dtype, output_tensor, output_meta_tensor,
@penpornk seems the function PerformConversion cannot be static.
I got error when I did this.
./tensorflow/core/lib/core/status_test_util.h:24:3: error: cannot call member function 'tensorflow::Status tensorflow::OpsTestBase::InitOp()' without object
   EXPECT_EQ(::tensorflow::Status::OK(), (statement))
   ^
tensorflow/core/kernels/mkl_fused_ops_test.cc:57:5: note: in expansion of macro 'TF_EXPECT_OK'
     TF_EXPECT_OK(InitOp());

2019-01-09 06:35 UTC, guizili0 commented
@penpornk I have modified code based on your comments, after internal test passed, I will push the code for review, sorry about the delay.

2019-01-16 05:45 UTC, guizili0 commented
@penpornk your comments had been addressed, please help to review, sorry about this delay.

2019-01-18 00:40 UTC, penpornk requested changes
No worries! Sorry for my delay as well. Thank you so much for the changes. I think we should be good to go after a few very minor changes.

2019-01-18 00:40 UTC, penpornk commented on tensorflow/core/graph/mkl_layout_pass_test.cc
> +// E = input(as bias), F = _FusedConv2D(C, A, E), G=Output(C, F)
`G=Output` -> `G = Output`. Sorry for nitpicking!

2019-01-18 00:40 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_ops_test.cc
> +    for (int i = 0; i < args.size() + 3; i++)
Nit: we prefer `++i` to `i++`.

2019-01-18 00:40 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_ops_test.cc
> +                     .Attr("num_args", num_args)
Sorry for being ambiguous. I meant let's keep `Input` and `Attr` in a similar order to when they are defined in `REGISTER_OP`:
https://github.com/tensorflow/tensorflow/blob/34d2f298f78d009b5ad2732e436cdae640509a33/tensorflow/core/ops/mkl_nn_ops.cc#L88-L111

So in this case I was talking about moving `num_args` to between `T` and `strides`.
```c++
    TF_EXPECT_OK(NodeDefBuilder("pad_fused_conv_op", "_MklPadWithFusedConv2D")
                     .Input(FakeInput(dtype))
                     .Input(FakeInput(dtype))
                     .Input(FakeInput(DT_UINT8))
                     .Input(FakeInput(num_args, DT_UINT8))
                     .Input(FakeInput(DT_UINT8))
                     .Attr("T", dtype)
                     .Attr("num_args", num_args)
                     .Attr("strides", {1, stride, stride, 1})
                     .Attr("padding", "VALID")
                     .Attr("fused_ops", fused_ops)
```

2019-01-18 07:11 UTC, guizili0 commented
@penpornk thanks for you update, the changes you requested had been addressed, please help to review.

2019-01-19 00:57 UTC, penpornk submitted a review, later dismissed
Thank you very much again for the PR! :)

2019-01-22 00:38 UTC, guizili0 commented
@penpornk Can you help to check these failure, it seems did not related to my code, and others PR also had failure in these UT.

2019-01-22 18:30 UTC, agramesh1 commented
pinging @caisq also

2019-01-22 18:36 UTC, caisq commented
@agramesh1 Roger. Starting the testing and merging process.

2019-01-22 18:38 UTC, penpornk commented
@guizili0 @agramesh1 Sorry for my delay! Thank you, @caisq !

2019-01-22 19:51 UTC, caisq commented
Experiencing some glitches in the sync'ing mechanisms. Stay tuned. cc @yifeif

2019-01-22 23:05 UTC, yifeif commented
sync should be resolved, thanks for the patience!

2019-01-23 00:40 UTC, yifeif commented
@guizili0 do you mind resolving the merge conflicts before we proceed? Thank you!

2019-01-23 02:39 UTC, guizili0 commented
@yifeif conflict has been resolved, thanks.

2019-01-23 21:52 UTC, penpornk commented
For some reason, I'm getting a message that there is a conflict again. @guizili0, could you please help take a look? Sorry for the inconvenience!

2019-01-24 00:56 UTC, guizili0 commented
@penpornk I cannot find the conflict, and the merge status is "Merging can be performed automatically with 1 approving review." Can you help to check it?

2019-01-24 02:02 UTC, penpornk commented
@guizili0 It's getting merged now. Sorry for the trouble!

2019-01-24 02:22 UTC, merged