[INTEL MKL] Enabled filter caching for convolution.
tensorflow/tensorflow pull request #24588
Opened 2018-12-27 01:15 UTC by bhavani-subramanian

When filter is a constant in convolution operations, we can avoid converting filter from TensorFlow format to MKL format by caching it after the first conversion. This cached filter can then be reused in subsequent iterations without having to perform the conversion again.

This PR also contains unit tests for the following cases:

1. To check if the attribute `is_filter_const` is set to true (in the graph pass) when filter is a constant and false otherwise.
2. To ensure that cached filter data is used when `Conv2D` kernel is run more than once.

For quantized Conv2D kernels, we expect `is_filter_const` to be true in the compute kernel.

2019-01-14 18:55 UTC, bhavani-subramanian commented
Hi @tatianashp, @penpornk can you please take a look at this PR? Thanks.

2019-01-14 19:05 UTC, penpornk commented
@bhavani-subramanian Sorry for the delay! I'll look at it today.

2019-01-15 08:11 UTC, penpornk requested changes
Apologies again for the lateness! Thank you for the PR and for improving the code's readability!

2019-01-18 22:33 UTC, bhavani-subramanian commented on tensorflow/core/kernels/mkl_fused_ops_test.cc
> +    const Tensor& second = *GetOutput(2);
Done.

2019-01-18 22:33 UTC, bhavani-subramanian commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +    SHARED_LOCKS_REQUIRED(mu_) {
Done.

2019-01-18 22:33 UTC, bhavani-subramanian commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +    EXCLUSIVE_LOCKS_REQUIRED(mu_) {
Done.

2019-01-18 22:34 UTC, bhavani-subramanian commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +                   MklDnnData<Tfilter>& filter, const memory::desc& filter_md) {
@penpornk I don't quite follow. Are you saying that I should include both `LOCKS_EXCLUDED` and `SHARED_LOCKS_REQUIRED'? Aren't they mutually exclusive?

2019-01-18 22:34 UTC, bhavani-subramanian commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +    SHARED_LOCKS_REQUIRED(mu_) {
Done.

2019-01-22 20:27 UTC, penpornk requested changes
Thank you for the changes! Sorry for being ambiguous. I have clarified my requests about the thread safety attributes in the comments. The comments involving the outdated code don't need changes (I just felt like replying there too).

2019-01-24 21:22 UTC, bhavani-subramanian commented
Thanks for the clarification, @penpornk. I have addressed your review comments.

2019-01-25 18:35 UTC, penpornk approved these changes
Thank you for the PR! :)

2019-01-25 19:19 UTC, bhavani-subramanian commented
Hi @caisq the 2 failing checks are not related to this PR.

These checks fail for another recently submitted PR as well: https://github.com/tensorflow/tensorflow/pull/25186

2019-01-29 19:20 UTC, penpornk commented
@bhavani-subramanian There seems to be a merge conflict. Could you please help take a look if you can resolve it from your side? Thank you!

2019-01-29 20:38 UTC, penpornk commented
@bhavani-subramanian Never mind. It finally got pulled in now. Sorry!

2019-01-29 21:13 UTC, bhavani-subramanian commented
Thanks @penpornk!

2019-01-29 23:23 UTC, merged