[XLA] Unimplemented inst in call fusion
tensorflow/tensorflow pull request #24631
Opened 2018-12-30 12:28 UTC by DavidNorman

If an unimplemented instruction is embedded inside a call or fusion operation then currently the system aborts having done a ConsumeValueOrDie.  This change allows the various clients of the evaluator to process a graph containing calls/fusions safely.

Applies to all XLA systems.

2018-12-31 06:40 UTC, jlebar requested changes
Thank you for the patch!

As it happens, these testcases are about to break because we're about to land a patch to make kRNG work in the evaluator.

Is there another instruction you could use?

2018-12-31 06:40 UTC, jlebar commented on tensorflow/compiler/xla/service/hlo_evaluator_test.cc
> +// containing an unimplemented instruction
Nit

> Check that we correctly return *an* error status when evaluating *a* call instruction containing an unimplemented instruction.

Nit: Period at end of sentence

2018-12-31 06:40 UTC, jlebar commented on tensorflow/compiler/xla/service/hlo_evaluator_test.cc
> +// Check that we correctly return error status when evaluating call instruction
s/call/fusion/

2018-12-31 15:33 UTC, DavidNorman commented
used a custom-call

2019-01-01 03:09 UTC, jlebar commented
> is there a danger that the constant subexpression evaluator will eval the kRng instructions and eliminate them from the graph?

CSE doesn't evaluate instructions, it just commons them (i.e. replaces two instances of the same thing with one instance).  So the evaluator isn't used in CSE, and however it worked before it should continue working.

CSE skips side-effecting ops, and kRNG is marked as side-effecting.  As it happens @bixia1 is working on changing this and making the side-effects more explicit in the HLO graph, e.g. passing the state (i.e. the seed) explicitly between kRNG ops.

2019-01-01 03:09 UTC, jlebar approved these changes

2019-01-04 11:42 UTC, DavidNorman commented
@jlebar sorry - i meant the constant subexpression removal step (which uses the evaluator) rather than the common subexpression removal.

2019-01-04 21:30 UTC, jlebar commented
> sorry - i meant the constant subexpression removal step (which uses the evaluator) rather than the common subexpression removal.

Ah, what we call "constant folding".  `hlo_constant_folding.cc` explicitly skips kRNG ops.  Which I suppose is a bit of a hack, but there you go.

2019-01-09 21:15 UTC, ymodak commented
@DavidNorman Can you please resolve the merge conflicts? Thanks!

2019-01-24 19:54 UTC, ymodak commented
@DavidNorman gentle ping

2019-02-03 09:26 UTC, closed without merging