Add tensor forest classification train in core
tensorflow/tensorflow pull request #24656
Opened 2019-01-01 23:44 UTC by yupbank

According to https://github.com/tensorflow/community/blob/master/rfcs/20180626-tensor-forest.md

This is a first step. And the whole process is tracked by #21830

We are adding an canned TensorForestClassifier and TensorForestRegressor into core.

The Pr is only a third step implementing TensorForestClassifier with train only functionality.

2019-01-16 21:44 UTC, nataliaponomareva reviewed
I wonder whether it is still WIP. For one, i dont see the graph so it is hard to comment overall

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resource_ops.cc
> +class TensorForestCreateFertileStatsVariableOp : public OpKernel {
please add a comment to as what this represents. Eg a resource around statistics of the leaves for all the leaves in a tree that can still be splitted

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resource_ops.cc
> +// Op for serializing a model.
probably a copy past comment. for serializing fertile leaf stats

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +  // add left leaf
where is best coming from??

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +  new_children->push_back(decision_tree_->nodes_size());
nodes_size - 1?

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +  new_children->push_back(decision_tree_->nodes_size());
ditto

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +const bool TensorForestFertileStatsResource::IsSlotFinished(
can u add comments to these methods to help understand what they are for

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +    const bool is_regression, const int32 node_id, const int32 example_id,
lets stick to node_id everywhere? in a previous file u call them node but it is still an int

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +    // for (auto candidate : slot.candidates()) {
const auto&?

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +    // for (auto candidate : slot.candidates()) {
is the comment on line 195 important

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +        1 - candidate.right_split_stats().sum_of_square().value(0) /
can u make getGini a method that takes in split stats? This way it is much shorter and much less error prone

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +  float min_score = FLT_MAX;
comment: we are looking to minimize the gini

2019-01-16 21:44 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/resources.cc
> +  float incoming_weight = 1.0;
it looks like it is just a cont, move it to the top of the file, make it a real const

2019-02-13 18:53 UTC, tensorflowbutler commented
Nagging Reviewer @nataliaponomareva: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-03-06 18:55 UTC, tensorflowbutler commented
Nagging Reviewer @nataliaponomareva: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 15 days with no activity and the `awaiting review` label has been applied.

2019-03-27 13:00 UTC, tensorflowbutler commented
Nagging Reviewer @nataliaponomareva: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-04-01 18:23 UTC, nataliaponomareva requested changes
Thanks Peng, it looks mostly good!
My two main questions
1) SplitStats for classification - didn't understand why you need sum/sum of squares there
2) Tests for the ops/training?

2019-04-01 18:23 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/tensor_forest.proto
> +  // example weights.  Gini(X) = 1 - \sum_i{(X_i/n)^2}
sorry i don't follow completely. X_i is the mean here? What is i index then?

2019-04-01 18:23 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/tensor_forest.proto
> +  // LeafStat right_stats = 5;
commented out?

2019-04-01 18:23 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/train_ops.cc
> +        out(example_id) =
didn't we have this op already for the inference?

2019-04-01 18:23 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/train_ops.cc
> +    mutex_lock l(*fertile_stats_resource->get_mutex());
can it be shared lock here

2019-04-01 18:23 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/train_ops.cc
> +        // TODO(gilberth): Consider using a memory pool for these.
please remove todo for gilberth

2019-04-01 18:23 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/train_ops.cc
> +    // TODO(gilberth): This is a rough approximation based on measurements
ditto here. i assume it means this code is a direct copy from contrib? :)

2019-04-01 18:23 UTC, nataliaponomareva commented on tensorflow/core/kernels/tensor_forest/train_ops.cc
> +                  std::queue<std::tuple<int32, int32>>* waiting,
what is this waiting?

2019-05-28 21:55 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-05-28 21:55 UTC, closed without merging