cloud oauth_client: update for OpenSSL 1.1.0 compatibility
tensorflow/tensorflow pull request #24666
Opened 2019-01-02 12:37 UTC by perfinion

EVP_MD_CTX_cleanup was removed in OpenSSL 1.1.0. There is a call to
EVP_MD_CTX_destroy right after and _destroy will call _cleanup if
required. EVP_MD_CTX_destroy exists in OpenSSL 1.0, 1.1 and BoringSSL so
removing the call to _cleanup works everywhere.

Signed-off-by: Jason Zaman <jason@perfinion.com>

2019-01-03 03:50 UTC, perfinion commented
Related Gentoo bug: https://bugs.gentoo.org/673968

2019-01-03 21:28 UTC, penpornk requested changes
Thank you for the fix!
Could you please add comments near the `EVP_MD_CTX_destroy` calls that `EVP_MD_CTX_destroy` is renamed to `EVP_MD_CTX_free` in OpenSSL 1.1.0 but the old name is still retained as macro; and maybe add a link to the [change notes](https://www.openssl.org/news/cl110.txt)? Just for reference.

2019-01-05 04:05 UTC, perfinion commented
@penpornk Good idea, I pushed an update with the comment and a note to not change it till support is dropped for 1.0.x. 
Distros will take a while to fully move over to OpenSSL 1.1 so that part is in no hurry.

2019-01-05 20:20 UTC, penpornk approved these changes
Awesome! Thank you very much again for the PR! :)

2019-01-07 21:21 UTC, merged