Fix incorrectly returned error type during RaggedTensor iteration
tensorflow/tensorflow pull request #24723
Opened 2019-01-06 07:07 UTC by yongtang

This fix tries to address the issue raised in #24679 where RaggedTensor iteration does not stop correctly (eager mode):
```
import tensorflow as tf
r = tf.ragged.constant([[1., 2.], [3., 4., 5.], [6.]])
for elem in r:
    print(elem)
```

The reason was that `__getitem__()` should have thrown IndexError (translated to StopIteration in next/__next__()) in order for python to correctly process iteration.

This fix fixes the issue.

This fix fixes #24679.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2019-01-09 19:34 UTC, penpornk requested changes
Thank you for your PR!

2019-01-09 19:34 UTC, penpornk commented on tensorflow/python/ops/ragged/ragged_getitem.py
> +          raise IndexError('row key {} out of bounds'.format(row_key))
```suggestion
          raise IndexError('Row key {} out of bounds'.format(row_key))
```

2019-01-09 19:34 UTC, penpornk commented on tensorflow/python/ops/ragged/ragged_tensor_test.py
> +      self.assertAllEqual(elem, value)
Can we just use `value[i]` and skip using `value`?

2019-01-09 22:59 UTC, penpornk approved these changes
Thank you again for the fix!

2019-01-17 23:40 UTC, penpornk requested changes
The PR is failing this test
https://github.com/tensorflow/tensorflow/blob/b797012b39f89c45f13336b36c6b73e9ad93d815/tensorflow/python/ops/ragged/ragged_tensor_test.py#L856

Below is the error message
```
ERROR: testRaggedTensorGetItemErrorsWithRaggedRank1('foo', <type 'exceptions.TypeError'>, 'Only\\ integers\\,\\ slices\\ \\(\\`\\:\\`\\)\\,\\ ellipsis\\ \\(\\`\\.\\.\\.\\`\\)\\,\\ tf\\.newaxis\\ \\(\\`None\\`\\)\\ and\\ scalar\\ tf\\.int32\\/tf\\.int64\\ tensors\\ are\\ valid\\ indices') (__main__.RaggedTensorTest)
testRaggedTensorGetItemErrorsWithRaggedRank1('foo', <type 'exceptions.TypeError'>, 'Only\\ integers\\,\\ slices\\ \\(\\`\\:\\`\\)\\,\\ ellipsis\\ \\(\\`\\.\\.\\.\\`\\)\\,\\ tf\\.newaxis\\ \\(\\`None\\`\\)\\ and\\ scalar\\ tf\\.int32\\/tf\\.int64\\ tensors\\ are\\ valid\\ indices') (__main__.RaggedTensorTest)
```
Please modify the code to account for this. Thank you!

2019-01-18 18:09 UTC, yongtang commented
Thanks @penpornk for the help. The PR has been updated with test fixed. Please take a look.

There are still failing tests remaining but it looks like they are unrelated.

2019-01-19 01:50 UTC, penpornk approved these changes
Thank you for the fix! :) I agree the failing tests are unrelated.

2019-01-24 18:03 UTC, merged