TF Keras generic_utils_test missing test cases add
tensorflow/tensorflow pull request #24929
Opened 2019-01-15 11:03 UTC by Dayananda-V

test case added for
1-func_dump
2-func_load

2019-01-24 06:16 UTC, Dayananda-V commented
@fchollet 

Please help to review the test case

2019-01-29 00:56 UTC, fchollet requested changes
Thanks for the PR!

2019-01-29 00:56 UTC, fchollet commented on tensorflow/python/keras/utils/generic_utils_test.py
> +  @parameterized.parameters(['simple_function', 'closured_function'])
Add line break above

2019-01-29 00:56 UTC, fchollet commented on tensorflow/python/keras/utils/generic_utils_test.py
> +        bar = generic_utils.Progbar(
For a progbar test, you should catch the stdout and check that the display matches what you expect in the different verbosity modes.

2019-01-29 00:56 UTC, fchollet commented on tensorflow/python/keras/utils/generic_utils_test.py
> +    self.assertEqual(bathces[0][1]-bathces[0][0], 32)
- Fix typo
- For PEP8 style compliance, please insert spaces around operator `-`

2019-01-29 00:56 UTC, fchollet commented on tensorflow/python/keras/utils/generic_utils_test.py
> +    with self.assertRaises(ValueError):
When testing exceptions, match the error against a regex.

2019-02-08 22:20 UTC, hgadig commented
@fchollet  Please review and approve this PR or suggest changes(if required)

2019-03-09 18:43 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-03-24 12:44 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-04-13 12:44 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet, @fchollet: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-05-06 13:02 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet, @fchollet, @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-05-21 13:06 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet, @fchollet, @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-05-21 17:39 UTC, pavithrasv approved these changes

2019-06-26 20:46 UTC, rthadur commented
@Dayananda-V can you please resolve conflicts ?

2019-07-11 12:37 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-08-09 12:37 UTC, closed without merging

2019-08-09 12:37 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.