Use safe variance epsilon for float16 layer_norm
tensorflow/tensorflow pull request #24979
Opened 2019-01-17 01:25 UTC by benbarsdell

- The original epsilon value (1e-12) is too small for float16 and can
  cause NaNs in the output when the variance is small.
- This commit also adds float16 and float32 cases to LayerNormTest and
  improves the numerical robustness of the test logic.

I believe this is one of (but not all of) the reasons that NaNs are observed during fp16 training of the BERT model as noted here: https://github.com/google-research/bert/pull/255#issuecomment-450591507

2019-01-29 00:27 UTC, fchollet requested changes
Thanks for the PR!

2019-01-30 02:06 UTC, benbarsdell commented on tensorflow/contrib/layers/python/layers/layers.py
> +    variance_epsilon = 1e-12 if dtype != dtypes.float16 else 1e-3
Choosing the best value here is a bit tricky. Some considerations:

- 1e-3 is the default for all of the TF Python batchnorm APIs (and the FusedBatchNorm op uses 1e-4).
- 1e-7 is in the subnormal range of values for fp16 (not sure if this is a concern or not).
- If the input array is not normally-distributed, the maximum value can far exceed the stddev, which results in overflow during the division if epsilon is too small.
- The BERT model fails to train (gets NaNs) if this variance_epsilon is set to less than ~3e-5.

I'm happy to make the value smaller, but I think 3e-5 is as small as we can practically go (1e-4 seems like a safe choice). Let me know what you think.

2019-02-06 17:36 UTC, tfboyd commented on tensorflow/contrib/layers/python/layers/layers.py
> +    variance_epsilon = 1e-12 if dtype != dtypes.float16 else 1e-3
@fchollet @benbarsdell ping

2019-02-08 19:12 UTC, fchollet approved these changes
Sounds good, thanks!

2019-02-22 01:40 UTC, jlebar commented
> **import/copybara ** — An error happened while migrating the change
Required

@rthadur any idea what this means / how to retrigger?

2019-02-22 18:46 UTC, merged