TF Keras slice_arrays object is not subscriptable problem fix
tensorflow/tensorflow pull request #25099
Opened 2019-01-22 09:36 UTC by Dayananda-V

slice_arrays method fails to slice when receive arrays contains object not subscriptable.

Issue Reproduction:
tensorflow.python.keras.utils.generic_utils.slice_arrays(list([1, 2, 3], start=0, stop=1)

2019-01-29 00:45 UTC, fchollet requested changes
Thank you for the PR. Please add a unit test for this change.

2019-01-30 11:05 UTC, Dayananda-V commented
@fchollet 

unit test case added. Thanks

2019-05-09 08:24 UTC, gbaned commented
@fchollet, @pavithrasv Could you PTAL and approve.

2019-06-06 21:21 UTC, pavithrasv approved these changes

2019-06-07 19:21 UTC, merged