Lite: Floor-Div different datatypes supported
tensorflow/tensorflow pull request #25130
Opened 2019-01-23 10:47 UTC by ANSHUMAN87

TFLite FloorDiv currently supports only Int32.
This PR add support for other datatypes as well.
Test cases also updated.

2019-02-20 19:03 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-03-07 23:51 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-03-22 12:55 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-04-05 17:05 UTC, jdduke requested changes

2019-04-05 17:05 UTC, jdduke commented on tensorflow/lite/kernels/floor_div.cc
> +    case kTfLiteInt64: {
In general we only add new types when they're explicitly needed. Unless you have an int64 model, let's leave that type out.

2019-04-05 17:05 UTC, jdduke commented on tensorflow/lite/kernels/floor_div.cc
> +    case kTfLiteUInt8: {
For uint8, it also requires changing behavior in the toco toolchain to allow the type to be quantized.

2019-04-22 20:35 UTC, jdduke requested changes
We'll need to update the op versioning as done in https://github.com/tensorflow/tensorflow/commit/e476315d4484ed2b344983e1c5258b976927257c#diff-c6d779ac1662f9870bf80c4a641ca49b. Do you have a particular model which requires this change?

2019-04-24 18:42 UTC, jdduke commented on tensorflow/lite/kernels/floor_div.cc
> +    case kTfLiteUInt8:
Can we leave out uint8 and just add float?

2019-04-25 06:36 UTC, ANSHUMAN87 commented
@jdduke : Your comments are addressed now, Thanks!

2019-04-26 17:20 UTC, jdduke approved these changes

2019-05-06 04:02 UTC, ANSHUMAN87 commented
@rthadur : Gentle Reminder!

2019-05-14 20:12 UTC, merged