[TF C++] Added WhileContext to all while loop nodes
tensorflow/tensorflow pull request #25287
Opened 2019-01-29 17:57 UTC by samdow

Per discussions in #24842 and [here](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!topic/developers/IjuGQNcD6Kw), this adds the while context to all the nodes created by the while loop using the method Skye suggested. It also updates the one test that checks the while context.

cc @skye

2019-01-29 19:28 UTC, skye requested changes
Please update the comment at http://go/gh/tensorflow/tensorflow/blob/master/tensorflow/core/graph/graph.h#L290 as well.

2019-01-29 21:56 UTC, samdow commented on tensorflow/cc/ops/while_loop.cc
> +        scope.graph()->FindNodeId(id)->set_while_ctx(while_ctx);
Totally right. It's my bad! I was hitting the wrong tests. But all C++ tests pass now

2019-01-30 00:16 UTC, skye submitted a review, later dismissed
Thanks!

2019-01-30 16:17 UTC, shahzadlone commented on tensorflow/cc/ops/while_loop_test.cc
> +  int start_idx = scope_.graph()->num_node_ids();
```start_idx``` should be ```const```, if not muted/modified anywhere?

2019-01-30 16:17 UTC, shahzadlone commented on tensorflow/cc/ops/while_loop_test.cc
> +  int final_idx = scope_.graph()->num_node_ids();
```final_idx``` should be ```const```, if not muted/modified anywhere?

2019-02-01 17:39 UTC, samdow commented
Sorry! I think I made the const changes like minutes after it was marked ready to pull. I only added const though and the C++ tests are still passing

2019-02-01 18:37 UTC, skye approved these changes

2019-02-01 18:38 UTC, skye commented
No worries! To be honest I don't really understand how our PR magic works... I just re-approved the changes, so hopefully it'll run the tests and merge now.

2019-02-07 19:05 UTC, skye commented
Sorry for the delay. I'm seeing internally that tensorflow/core:graph_control_flow_test (not sure why this didn't show up in the PR tests here, maybe I'm missing something). @samdow can you take a look?

2019-02-07 22:48 UTC, samdow commented
Thanks for checking! I tried to run it locally but it seemed to pass for me:
![screen shot 2019-02-07 at 2 47 01 pm](https://user-images.githubusercontent.com/17888388/52448014-5e55bd00-2ae7-11e9-88d1-b03fb45969b0.png)
Would you be able to tell me what error it was getting? I'll also try rebasing in case the test changed

2019-02-13 00:12 UTC, skye commented
Just FYI, I'm holding off on moving this forward until we resolve the discussion about the original email.

2019-02-20 19:59 UTC, rthadur commented
Thank you all , closing this PR because the changes are already checked in internal system.

2019-02-21 15:37 UTC, skye commented
@samdow do we still need this change?

2019-02-22 17:56 UTC, samdow commented
Sorry for the delay! I just wanted to check it, but we do not need this change because @melissagrueter's PR will fix the AddGradients problem we were having

2019-02-22 17:56 UTC, closed without merging

2019-02-22 18:07 UTC, skye commented
No worries, I was just checking as well. Thanks!