Add example code to tf.data.Dataset.filter() documentation
tensorflow/tensorflow pull request #25437
Opened 2019-02-01 22:15 UTC by kweinmeister

2019-02-02 00:24 UTC, MarkDaoust requested changes
Hi, 

Thanks for the change.

I know a lot of them are already like this, but anything you can do to make the example more copy-paste runnable helps.

2019-02-02 01:59 UTC, kweinmeister commented on tensorflow/python/data/ops/dataset_ops.py
> +    a.filter(lambda x: x < 3) == { 1, 2 }
I changed the expected result to be commented out. Please let me know if any other changes need to be made after the latest commit.

2019-02-02 01:59 UTC, kweinmeister commented on tensorflow/python/data/ops/dataset_ops.py
> +    b = { 4, 5, 6, 7 }
Done!

2019-02-04 17:41 UTC, MarkDaoust approved these changes
LGTM. Thanks.

2019-02-06 23:43 UTC, merged