[tools]add transform graph(fold_moments,fold_batch_norms_algebraic)
tensorflow/tensorflow pull request #25477
Opened 2019-02-04 01:20 UTC by czy2014hust

2019-02-22 22:37 UTC, petewarden submitted a review, later dismissed

2019-05-16 18:24 UTC, petewarden submitted a review, later dismissed

2019-06-26 20:44 UTC, rthadur commented
@czy2014hust can you please resolve conflicts ?

2019-08-01 20:33 UTC, petewarden approved these changes

2019-08-20 13:18 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-08-20 22:42 UTC, rthadur requested changes

2019-08-20 22:42 UTC, rthadur commented on tensorflow/tools/graph_transforms/fold_moments.cc
> +        CHECK_EQ(sub_node.input(0), mean_node.input(0))
please use DCHECK instead here

2019-08-20 22:42 UTC, rthadur commented on tensorflow/tools/graph_transforms/fold_batch_norms_algebraic.cc
> +        CHECK_EQ(mul_node.name(), mul_node_alias.name())
please use DCHECK instead here

2019-08-21 02:47 UTC, closed without merging