Fix infinite loop when ignore_errors is used with TFRecordDataset
tensorflow/tensorflow pull request #25705
Opened 2019-02-12 22:13 UTC by yongtang

This fix tries to address the issue raised in #25700 where
ignore_errors combined with TFRecordDataset will have a infinite loop.
The issue was that when ignore errors happen, the index of the file names
are not moved forward with error returned. So the same file is repeated.

This fix is a short solution to fix it.

This fix fixes #25700.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2019-02-12 22:17 UTC, yongtang commented
Not very familiar with this part of the code, maybe there are some better ways of fixing it? /cc @mrry

2019-02-20 00:10 UTC, mrry commented
Thanks for the contribution! I'm reassigning this to @jsimsa to make a call on what the right semantics should be here.

2019-02-20 18:10 UTC, jsimsa requested changes
Hi @yongtang thank you for the fix. Could you please add a test that would fail before this fix and passes with your fix? Thank you.

2019-02-21 19:26 UTC, jsimsa approved these changes

2019-02-26 01:20 UTC, merged