TFTRT: Fix bugs with Concat and clean up
tensorflow/tensorflow pull request #25730
Opened 2019-02-13 23:05 UTC by trevor-m

Previously, the Concat layer had a bug where we only checked if the first input was a tensor, and then assumed all N inputs were tensors as well. This could lead to segfaults. Now, we properly convert all inputs to tensors. I also added more checks in general.

Since ConcatV2 does not have a C++ API, how do think we should proceed regarding unit tests? We could either manually construct the node def or just expand the existing python tests.
Defintion of ConcatV2 is here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt

2019-02-19 20:32 UTC, aaroey requested changes
Thanks @trevor-m for the fix. I think `ops::Concat()` will result in a ConcatV2 op, so please help to add unit test using that.

2019-02-19 21:24 UTC, trevor-m commented
> Thanks @trevor-m for the fix. I think `ops::Concat()` will result in a ConcatV2 op, so please help to add unit test using that.

Thanks Lambda. I will add some unit tests.

2019-02-20 23:31 UTC, trevor-m commented
@aaroey I have added the unit tests.

2019-02-26 23:05 UTC, aaroey requested changes

2019-02-26 23:05 UTC, aaroey commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
> +    input_tensors.push_back(params->converter->GetAsTensor(inputs.at(i)));
Another problem is, as chatted, IConstantLayer will add implicit batch dims, how to handle that? Also please add corresponding tests. Thanks.

2019-03-04 22:06 UTC, trevor-m commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
> +// TODO(tmorris): Add a caching mechanism so many constant layers are not
@aaroey How should we handle the possibility that a constant is created for a certain weight but with different dims? Do we need to add the dims as a second key to the cache?

2019-03-14 19:58 UTC, trevor-m commented
@aaroey Could you review this when you have a chance? Thanks

2019-03-26 00:39 UTC, aaroey submitted a review, later dismissed

2019-03-26 01:07 UTC, aaroey approved these changes

2019-03-26 05:09 UTC, merged