Update gpu_fusible.h
tensorflow/tensorflow pull request #25741
Opened 2019-02-14 04:49 UTC by siju-samuel

conumser -> consumer

2019-02-14 19:06 UTC, Harshini-Gadige submitted a review, later dismissed

2019-02-16 10:42 UTC, d0k requested changes

2019-02-16 10:42 UTC, d0k commented on tensorflow/compiler/xla/service/gpu/gpu_fusible.h
> +// This function works for both, sibling and producer-consumser multi-output
`consumser` is still a typo ;)

2019-02-16 11:07 UTC, siju-samuel commented on tensorflow/compiler/xla/service/gpu/gpu_fusible.h
> +// This function works for both, sibling and producer-consumser multi-output
@d0k thanks.

2019-02-16 11:09 UTC, d0k approved these changes

2019-02-18 09:26 UTC, merged