Add support for mkl_quantize_op. fp32->{uint8, int8}
tensorflow/tensorflow pull request #25902
Opened 2019-02-19 23:45 UTC by Srini511

This PR adds support for MKL quantize operator to convert activations in  fp32 to 8 bits precision

2019-03-02 00:58 UTC, Srini511 commented
Hi @penpornk . Gentle reminder for review.

2019-03-14 17:28 UTC, Srini511 commented
@penpornk gentle reminder.

2019-03-15 08:05 UTC, penpornk requested changes
Thank you very much for the PR, and I'm so sorry for my delay!

2019-03-15 08:05 UTC, penpornk commented on tensorflow/core/ops/mkl_array_ops.cc
>  #endif
```suggestion
#endif  // INTEL_MKL
```

2019-03-18 22:28 UTC, Srini511 commented on tensorflow/core/graph/mkl_layout_pass.cc
> +              << "could possibly be a filter"
Agree

2019-03-18 22:29 UTC, Srini511 commented on tensorflow/core/kernels/BUILD
> +   srcs = [
Agree

2019-03-18 22:45 UTC, Srini511 commented on tensorflow/core/kernels/BUILD
> +       "//third_party/mkl:intel_binary_blob",
agree

2019-03-18 22:55 UTC, Srini511 commented on tensorflow/core/kernels/mkl_quantize_op.cc
> +    max_range = std::max(0.0f, max_range);
we cannot say that if both min_range and max_range are both negative.

2019-03-18 22:59 UTC, Srini511 commented on tensorflow/core/kernels/mkl_quantize_op.cc
> +      output_tf_shape.AddDim((dst_pd.get_size() / sizeof(T)) + 1);
Not needed actually. copy paste

2019-03-18 23:01 UTC, Srini511 commented on tensorflow/core/kernels/mkl_quantize_op.cc
> +      // 255].  If the input range is [0, x], then the scale is x/255 instead
Agree

2019-03-18 23:05 UTC, Srini511 commented on tensorflow/core/kernels/mkl_quantize_op.cc
> +  int mode_;
It is not needed for now, but is meant to be placeholders for future implementation of other types.

2019-03-18 23:07 UTC, Srini511 commented on tensorflow/core/kernels/mkl_quantize_op_test.cc
> +  test::FillValues<quint8>(&expected, {0, 1, 1, 2, 127, 255, 255, 2});
Yes it is a saturating scaling operation.

2019-03-19 17:40 UTC, Srini511 commented
Hi @penpornk . Thank you for the review. I have addressed your comments. Please let me know if the changes are okay.

2019-03-20 08:02 UTC, penpornk requested changes
Thank you for the changes and the clarifications! A few more minor changes, please.

2019-03-20 08:02 UTC, penpornk commented on tensorflow/core/kernels/mkl_quantize_op.cc
> +  int mode_;
Got it. Thank you!

2019-03-20 17:03 UTC, Srini511 commented
Hi @penpornk , I have done the changes above too. Thank you!

2019-03-20 17:57 UTC, penpornk approved these changes
Thank you again for the PR!

2019-03-20 21:23 UTC, merged