Enhancement to Dimension and TensorShape API documentation
tensorflow/tensorflow pull request #25993
Opened 2019-02-22 00:40 UTC by SSaishruthi

This PR is intended to help beginners understand the functionality of both Dimension and TensorShape API better by providing additional notes about each function and making it self-explanatory.

2019-02-22 00:52 UTC, SSaishruthi commented
I signed it!

2019-02-22 18:48 UTC, rthadur commented
> I signed it!

@SSaishruthi we did not see CLA , can you please make sure you use same username and email while signing CLA

2019-03-02 07:39 UTC, SSaishruthi commented
CLA issue has been resolved.

2019-04-18 17:22 UTC, SSaishruthi commented
Hi @rthadur,
Is this PR in review? 
TIA

2019-04-18 17:32 UTC, rthadur commented
> Hi @rthadur,
> Is this PR in review?
> TIA

yes, can you please resolve conflicts.

2019-04-18 17:42 UTC, SSaishruthi commented
@rthadur 
Resolved

2019-05-10 16:07 UTC, qlzh727 requested changes
Changes for the change. Honestly, I don't think the currently PR increase the readability a lot since most of the method and code are self-explanatory. The comment and doc is usually needed when the code has extra complexity. If the code itself can already serve as doc, then adding more doc will actually reduce the readability since it provide more noisy.

I will also let Mark from doc team to do further review.

2019-05-10 16:07 UTC, qlzh727 commented on tensorflow/python/framework/tensor_shape.py
> +    """Subtraction of `other` from `self`.
This actually gives user the wrong impression that the value of self is being updated, which is not in this case. The method only return the subtracted value without updating self and other.

2019-05-10 16:07 UTC, qlzh727 commented on tensorflow/python/framework/tensor_shape.py
> +    """Subtraction of `other` from `self`.
same of all the methods above and below.

2019-05-10 16:07 UTC, qlzh727 commented on tensorflow/python/framework/tensor_shape.py
> +    Returns:
should have a blank line between docstring and return section.

2019-05-10 16:07 UTC, qlzh727 commented on tensorflow/python/framework/tensor_shape.py
> +    """
Not sure why the docstring is empty.

2019-05-20 02:40 UTC, SSaishruthi commented
Working on the changes.

2019-07-11 12:37 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-08-09 12:37 UTC, closed without merging

2019-08-09 12:37 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.