Lite: Concatenation Op Refactored
tensorflow/tensorflow pull request #26134
Opened 2019-02-26 12:33 UTC by ANSHUMAN87

1:> Code refactored for reference_ops usage as both optimized and reference are same.
2:> Error message corrected.
3:> Wrong restriction removed.
4:> Test case added for Quantizied Input.

2019-03-04 23:25 UTC, jdduke commented
Even though both are the same now, when we add an optimized version in optimized_ops.h, we'll have a way of selecting between ref/opt using a custom resolver, so I would leave that code as it is.

2019-03-05 04:31 UTC, ANSHUMAN87 commented
> Even though both are the same now, when we add an optimized version in optimized_ops.h, we'll have a way of selecting between ref/opt using a custom resolver, so I would leave that code as it is.

@jdduke : Completely agree with you. But i think, the code is confusing, even i had to spend some time to find out, that both are same. Also it is not very big changes to accommodate optimization kernel if added in future. May be what we can do, we can keep the Enum(KernelType), and mark a TODO by optimization type, to be added in future. What do you think?

2019-03-05 15:47 UTC, srjoglekar246 commented
This is a convention we follow in most op-code, so it won't make sense to modify one implementation. IMO we can keep the current logic as-is.

2019-03-05 16:46 UTC, ANSHUMAN87 commented
@srjoglekar246: I found many op-code which follow convention as I mentioned in my previous comment. I think if we keep the current code it loses the readability also. It's better we follow the convention which is more readable.

2019-03-08 22:27 UTC, jdduke requested changes

2019-03-08 22:27 UTC, jdduke commented on tensorflow/lite/kernels/concatenation.cc
> -  TF_LITE_ENSURE(context, t0->dims->size <= 4);
Please avoid coupling refactorings with behavioral changes. This should be its own CL, with its own test, separate from any kind of refactoring.

2019-03-22 11:40 UTC, ANSHUMAN87 commented
@jdduke: Would you please help conclude this PR, TIA!

2019-03-24 17:08 UTC, ANSHUMAN87 commented
@jdduke : gentle reminder for conclusion, TIA!

2019-03-25 16:03 UTC, jdduke commented
The new tests are fine, but I don't think it's worth removing the kOptimized codepath yet. Instead it'd be good to figure out how to refactor the code to make it easier to have a parallel optimized/reference codepath without the if/else conditions.

2019-03-29 06:27 UTC, ANSHUMAN87 commented
> The new tests are fine, but I don't think it's worth removing the kOptimized codepath yet. Instead it'd be good to figure out how to refactor the code to make it easier to have a parallel optimized/reference codepath without the if/else conditions.

@jdduke : Thanks for the suggestion! I have handled your comment, please check and approve, Thanks!

2019-04-24 18:24 UTC, jdduke commented on tensorflow/lite/kernels/concatenation.cc
> -#undef TF_LITE_MACRO_DISPATCH
It's good practice to under the macros.

2019-04-24 18:25 UTC, jdduke commented on tensorflow/lite/kernels/concatenation.cc
> +      TF_LITE_CONCATENATION_QUANTIZED;
Let's make this define a function style invoke with no args

TF_LITE_CONCATENATION_QUANTIZED()

2019-04-25 10:16 UTC, ANSHUMAN87 commented
@jdduke : Your comments are handled now, please check, Thanks!

2019-05-03 18:30 UTC, jdduke approved these changes

2019-05-03 22:00 UTC, merged