C++ API
tensorflow/tensorflow pull request #26152
Opened 2019-02-27 03:42 UTC by jackyko1991

This is a fork of https://github.com/tensorflow/tensorflow/pull/24963

1.  To build a DLL for TensorFlow C++ API, you can now build
  `//tensorflow:tensorflow_cc.dll`
2. You can also get a compressed package for both (tensorflow.dll, tensorflow.lib) and C API headers by building
  `//tensorflow/tools/lib_package:libtensorflow_cc`

2019-02-28 08:48 UTC, meteorcloudy commented
@jackyko1991 #24963 is now merged. Can you rebase your branch?

There're something wrong during code transformation when pushing to github at https://github.com/tensorflow/tensorflow/blob/3e21fe5faedab3a8258d344c8ad1cec2612a8aa8/tensorflow/BUILD#L521, I'm sending a fix to add the missing line endings.

2019-02-28 09:27 UTC, jackyko1991 commented
@meteorcloudy I have rebased my fork to match your fixes.

When I come across with the C++ api, I discovered that it depends a lot on the core libraries which some of the headers maybe moved or renamed. 

For example, `tensorflow::Status` is one of the mostly used class in TF core, its [header](https://github.com/tensorflow/tensorflow/blob/3f23f4ddeabbdc0704444d84c158bd6c348a9f10/tensorflow/core/lib/core/status.h) includes a non-existing `#include "tensorflow/core/lib/core/error_codes.pb.h"`, which I believe is renamed as [tensorflow/core/lib/core/errors.h](https://github.com/tensorflow/tensorflow/blob/3f23f4ddeabbdc0704444d84c158bd6c348a9f10/tensorflow/core/lib/core/errors.h)

strangely enough this kind of file renaming still pass CI tests.

Another issue is that ops now appears to be named as "kernels"

In the [official document of c++ api](https://www.tensorflow.org/guide/extend/cc), it has the line `using namespace tensorflow::ops;`, it was defined by this [header](https://github.com/tensorflow/tensorflow/blob/3f23f4ddeabbdc0704444d84c158bd6c348a9f10/tensorflow/cc/ops/standard_ops.h). But now it is relocated at [core kernels](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/kernels). This will ruin most of the old c++ codes without a clear clarification on header changes.

I am working at exporting core headers together with `
 //tensorflow/tools/lib_package:libtensorflow_cc`, but library linking and third party dependency may still be problematic, especially for eigen and other lower level headers like absl.

Can you come with a better idea to solve it?

2019-02-28 09:38 UTC, meteorcloudy commented
@jackyko1991 Sorry, I'm not sure the correct solution here because I'm not quite familiar with actual implementation.

@mrry Can you help answer the questions?

2019-02-28 18:22 UTC, mrry commented
@gunan owns the ongoing process of modularizing the TF codebase and providing stable APIs to other libraries. I believe he has plans in motion, so I'll defer to him on how a large change to the build files would fit with those plans.

2019-03-04 09:59 UTC, meteorcloudy requested changes
Although I'm not familiar with the actual headers, the structure of this PR makes sense to me. 
But it would be even better if we can add a few tests for this.

2019-03-04 09:59 UTC, meteorcloudy commented on tensorflow/core/BUILD
> +# filegroup(
Remove this?

2019-03-05 13:11 UTC, jackyko1991 commented on tensorflow/core/BUILD
> +# filegroup(
This has been fixed

2019-03-05 21:37 UTC, chsigg commented
The devil is probably in the details, but shouldn't transitive_hdrs be able to collect those header files?

2019-03-06 02:13 UTC, jackyko1991 commented
I have tried transitive_hdrs at the beginning but I would like the headers
to locate at original folders structures. Directly use transitive_hdrs
seems only flatten all headers in one folder layer?

Christian Sigg <notifications@github.com> 於 2019年3月6日週三 上午5:43寫道：

> The devil is probably in the details, but shouldn't transitive_hdrs be
> able to collect those header files?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/26152#issuecomment-469867529>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALgaB-_gqiqeIi32TCsznbVLFaJ2jgfZks5vTuTwgaJpZM4bTovb>
> .
>

2019-03-06 07:44 UTC, chsigg commented
No, it should not flatten the directory tree. You can use a bazel genrule to write the headers with the correct tree structure.

2019-03-06 08:20 UTC, jackyko1991 commented
@chsigg do you mean use some genrule like the following:
```bazel
genrule(
    name = "tensorflow_cc_headers",
    srcs = [
        "//tensorflow/core:headers"
    ],
    outs = tf_genrule_cmd_cc_headers,
    cmd = "cp $(locations //tensorflow/core:headers) > $@",
)
```

I am new to bazel and using some hard skills to copy the header. It will be nice if you can provide relavent example on copying file in folder structure.

2019-03-06 11:50 UTC, jackyko1991 commented
https://github.com/tensorflow/tensorflow/issues/22047#issuecomment-421452033 suggested an approach to export necessary symbols via `tf_exported_symbols_msvc.lds`.

Can anyone give a help on this? My temporary solution is to link all the generated libs against the executable but still get some of them missing.

2019-03-06 12:17 UTC, guikarist commented
> [#22047 (comment)](https://github.com/tensorflow/tensorflow/issues/22047#issuecomment-421452033) suggested an approach to export necessary symbols via `tf_exported_symbols_msvc.lds`.
> 
> Can anyone give a help on this? My temporary solution is to link all the generated libs against the executable but still get some of them missing.

It is just a last resort. See [guide in my script](https://github.com/guikarist/tensorflow-windows-build-script#prerequisites)(after *"If you need to build C++ API,"*). Then my script apply [a patch](https://github.com/guikarist/tensorflow-windows-build-script/blob/master/patches/cpp_symbol.1.12.0.patch) to Tensorflow source before building.

2019-03-06 14:35 UTC, chsigg commented
> @chsigg do you mean use some genrule like the following:
> ...

Would something like the install_headers target work?

https://github.com/tensorflow/tensorflow/blob/08d767919de9c5698d18c3de1c17c3e6a0dfa961/tensorflow/BUILD#L664

2019-03-16 15:21 UTC, bygreencn commented
> [#22047 (comment)](https://github.com/tensorflow/tensorflow/issues/22047#issuecomment-421452033) suggested an approach to export necessary symbols via `tf_exported_symbols_msvc.lds`.
> 
> Can anyone give a help on this? My temporary solution is to link all the generated libs against the executable but still get some of them missing.

cmake compile mode give create_def_file.py to give a method, but bazel compile mode had not do it and current tensorflow_cc has not exported the correct cc symbols. Could you please continue to check it make tensorflow__cc export the correct symbols?

2019-03-18 10:33 UTC, bygreencn commented
> > [#22047 (comment)](https://github.com/tensorflow/tensorflow/issues/22047#issuecomment-421452033) suggested an approach to export necessary symbols via `tf_exported_symbols_msvc.lds`.
> > Can anyone give a help on this? My temporary solution is to link all the generated libs against the executable but still get some of them missing.
> 
> cmake compile mode give create_def_file.py to give a method, but bazel compile mode had not do it and current tensorflow_cc has not exported the correct cc symbols based on your patch with v1.13.1. Could you please continue to check it make tensorflow__cc export the correct symbols?

![image](https://user-images.githubusercontent.com/22853/54524104-09417c80-49ac-11e9-8f01-f5c7d541be64.png)
I means that it still has more c++ api with TF_*  prefix and CPP project will feedback lnk2001 error.

2019-04-19 08:11 UTC, guikarist commented
Any news?

2019-04-21 22:15 UTC, rthadur commented
@jackyko1991 can you please resolve conflicts

2019-05-28 21:47 UTC, rthadur commented
@jackyko1991 can you please resolve conflicts ?

2019-06-26 19:24 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-06-26 19:24 UTC, closed without merging