[INTEL MKL] Add 2D Concat Feature with MKLDNN
tensorflow/tensorflow pull request #26169
Opened 2019-02-27 09:29 UTC by mdfaijul

This PR adds features for concatenating 2D tensors with MKLDNN. Such concatenation is used in Wide and Deep models.

2019-02-28 17:11 UTC, mdfaijul commented
Temporarily closing. Will reopen after some more changes.

2019-03-14 22:34 UTC, mdfaijul commented
@penpornk did you have chance to look into this PR?

2019-03-15 12:44 UTC, penpornk requested changes
Thank you for the PR and I'm so sorry for my delay!

2019-03-15 16:44 UTC, mdfaijul commented on tensorflow/core/kernels/mkl_concat_op.cc
> +          // When memory::format::nc, dst_dims are already in MKLDNN order
@penpornk Addressed all your comments. Please check.

2019-03-19 10:10 UTC, penpornk approved these changes
Thank you again for contributing!

2019-03-20 04:10 UTC, merged