[Intel MKL]: Dequantize Op
tensorflow/tensorflow pull request #26228
Opened 2019-02-28 21:25 UTC by mahmoud-abuzaina

This PR adds support for Dequantize Op in MKL-DNN.

2019-03-15 17:20 UTC, mahmoud-abuzaina commented
Hi @penpornk , could you please review this PR? also if you can review #26585, it will be great. Thanks!

2019-03-19 10:08 UTC, penpornk requested changes
Thank you for your PR and I'm so sorry for my delay!
There are a few typos / C++ style mismatches that I saw in many Intel MKL PRs. I'm assuming it's because you start from the same template. It would be great if you could apply any applicable typos/style changes from here back to the template as well. Thank you very much!

2019-03-19 10:08 UTC, penpornk commented on tensorflow/core/kernels/mkl_dequantize_op_test.cc
> +  const Tensor& output_mkl_shape = *GetOutput(1);
Maybe we should remove this line if you are not checking it?

2019-03-19 10:08 UTC, penpornk commented on tensorflow/core/kernels/mkl_dequantize_op_test.cc
> +}
Please add a new line after this line.

2019-03-19 10:08 UTC, penpornk commented on tensorflow/core/kernels/mkl_dequantize_op_test.cc
> +}  // End namespace tensorflow
Per [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Namespaces),
```suggestion
}  // namespace tensorflow
```
Please also add a newline at the end of file.

2019-03-19 10:08 UTC, penpornk commented on tensorflow/core/ops/mkl_array_ops.cc
>  #endif
```suggestion
#endif  // INTEL_MKL
```

2019-03-21 06:55 UTC, penpornk requested changes
Thank you very much for your quick fixes! I have a few more minor changes I overlooked the first time. Sorry about that!

2019-03-21 06:55 UTC, penpornk commented on tensorflow/core/graph/mkl_layout_pass.cc
> +      VLOG(1) << "DequantizeRewrite: Mode is not SCALED."
```suggestion
      VLOG(1) << "DequantizeRewrite: Mode is not SCALED. "
```

2019-03-21 06:55 UTC, penpornk commented on tensorflow/core/graph/mkl_layout_pass.cc
> +                 "Eigen op for Dequantize op ";
```suggestion
                 "Eigen op for Dequantize op.";
```

2019-03-21 06:55 UTC, penpornk commented on tensorflow/core/kernels/BUILD
> +    deps = if_mkl([
With `mkl_deps`, we actually don't need `if_mkl` anymore. Please remove `if_mkl`. Thank you!

2019-03-22 02:04 UTC, mahmoud-abuzaina commented
@penpornk Thank you so much for reviewing this. I have addressed all the comments.

2019-03-22 06:19 UTC, penpornk approved these changes
Thank you again for contributing!

2019-03-22 06:29 UTC, penpornk requested changes
I just realized there is still one comment unanswered so I'm temporarily holding back the approval until it is addressed.

2019-03-22 06:29 UTC, penpornk commented on tensorflow/core/kernels/mkl_dequantize_op.cc
> +        output_tf_shape.AddDim((dst_pd.get_size() / sizeof(float)) + 1);
Just realized you haven't replied to this one yet.

2019-03-22 16:55 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl_dequantize_op.cc
> +        output_tf_shape.AddDim((dst_pd.get_size() / sizeof(float)) + 1);
Sorry I forgot to fix this. Will fix it now. +1 is not needed now. We used to use it in the past because of MKL-DNN issue that is now resolved.

2019-03-22 18:17 UTC, mahmoud-abuzaina commented
@penpornk I have addressed the missed comment. Thanks!

2019-03-22 18:25 UTC, penpornk approved these changes
Great! Thank you very much again!

2019-03-22 21:08 UTC, merged