Upgrading MKL DNN to 0.18 RC
tensorflow/tensorflow pull request #26261
Opened 2019-03-01 17:19 UTC by agramesh1

2019-03-01 22:14 UTC, penpornk requested changes
Thank you very much, Ramesh! Could you please replace `MKL DNN` with `MKL-DNN`? I just want it to be consistent with the MKL-DNN repo.

2019-03-01 22:14 UTC, penpornk commented on tensorflow/workspace.bzl
> +    # in third_party/mkl_dnn/mkldnn.BUILD.
Could you please also add a note that the MKL ML files above also need to be updated if MKL-DNN is jumping a version?

2019-03-02 01:11 UTC, agramesh1 commented
@penpornk Thanks for the quick review. I modified the PR based on your comments.

2019-03-02 01:40 UTC, penpornk reviewed
Thank you for your quick changes, Ramesh! I noticed that MKL-DNN released v0.18 two hours ago. Would  you like to proceed with the current commit on the branch or change to the v0.18 commit? (I'm fine either way.)

2019-03-02 04:11 UTC, penpornk approved these changes
We talked offline and decided to go with this commit.

2019-03-04 22:18 UTC, penpornk commented
@agramesh1 Merging is blocked because your workspace.bzl is now out of date. Could you please sync? Thank you!

2019-03-05 04:53 UTC, agramesh1 commented
@penpornk  I re-based the code.

2019-03-05 05:10 UTC, penpornk approved these changes
Thank you!

2019-03-05 05:35 UTC, merged