Add skip_empty argument to tf.strings.split Issue #26368
tensorflow/tensorflow pull request #26475
Opened 2019-03-08 07:36 UTC by lhendre

There were two split functions defined in TensorFlow 1.13:

tf.string_split
string_split_v2
We have consolidated these two ops into tf.strings.split in TF 2.0:

tf.strings.split(
    source,
    sep=None,
    maxsplit=-1
)
and wish to deprecate tf.string_split. However, tf.strings.split is missing the skip_empty functionality included in string_split:

tf.string_split(
    source,
    delimiter=' ',
    skip_empty=True
)
This feature request would be to include skip_empty functionality for tf.strings.split.

The code and unit tests are running.  I am currently running End to end tests and ensuring it adheres to clean standards.

2019-03-08 13:21 UTC, lhendre commented
#26475

2019-03-08 13:28 UTC, lhendre commented
#26368

2019-03-08 14:54 UTC, lhendre commented
Code has been put through python and C++ coding standards. 
There is pylint fix I have been dealing with but I am not sure if it is part of tensorflow's standards or a part of pylint not related to tensorflow as I am having trouble removing it E:292,27: Unexpected keyword argument 'skip_empty' in the function call (unexpected-keyword-arg).  This seems to be correct by all things I can see and it should be noted that the code runs and passes unit tests so the function, so I am not sure why it is throwing that?  
Otherwise, as i mentioned testing is passing on my end.  I am continuing to look for improvements but let me know if there are any thoughts

2019-03-08 16:07 UTC, lhendre commented
Changed tests and uses to have the skip empty default to true as was the case in the previous version.  Fixed linting issue

2019-03-08 16:08 UTC, lhendre commented
We had a question on if the skip empty argument should default to true or falses, previous unit tests had it default to false, but the previous version defaulted to true.  We went with defaulting to true for the time being.

2019-03-08 20:58 UTC, hawkinsp commented
(I'm not a good reviewer for this change, unassigning.)

2019-03-08 21:15 UTC, rthadur commented
@lhendre could you please re base your branch, @alextp do you want to review this change ?

2019-03-08 21:33 UTC, alextp requested changes
I think this is done better as a post-processing step.

2019-03-08 21:40 UTC, lhendre commented
Ill re base it, as I am about to enter transit, to clarify @alextp you mean reviewing the change would be better done after re base?

2019-03-08 21:45 UTC, alextp commented
No, this is not what I meant. What I meant is that I think filtering away the empty strings is better done as a post-processing step, say with boolean_mask, instead of another flag to split.

2019-03-08 22:31 UTC, lhendre commented
@alextp So to clarify I should make this a Post-processing step, my understanding then is to use a filter(maybe a boolean mask) in file python/ops/string_ops.py after the call to gen_string_ops.string_split_v2?  I am fine with this and can start looking into this.  

Would you like me to bring this back up at the issue itself?  This setup was based on how the previous skip_empty so this would be a departure from previous work.  Ill start looking into it

2019-03-09 21:57 UTC, lhendre commented
I have the mask working, I am working on updating the indices and shapes since those are set during processing @alextp

2019-03-09 23:24 UTC, lhendre commented
Im having some trouble getting the indices and shape values to be correct if you have any suggestions

2019-03-09 23:34 UTC, lhendre commented
@alextp I am not sure how to go about setting the indices and shapes.  The values are correct and I have removed the unit tests for indices and shapes.  They were previously set in the earlier portion of the code so I am not sure if we want to leave them at their previously values or change them(I have issues both figuring out how to change them and what to change them to).  Im leaving this as is for feedback

2019-03-11 16:27 UTC, alextp commented
I'm sorry I wasn't clear; I meant instead that we should let users filter out empty strings as post processing if they do want to.

Re indices and shapes, the right answer is to have proper ragged and sparse tensor support to tf.boolean_mask. Can you file an issue?

2019-03-13 03:21 UTC, lhendre commented
Ill Open up an issue and post about this in the current open issue at #26368, would you like to close that one?

2019-04-13 01:28 UTC, closed without merging