Tried - Error Logging for GradientTape #26143
tensorflow/tensorflow pull request #26489
Opened 2019-03-08 16:00 UTC by shashvatshahi1998

i have added isinstance() method to check variable type and raise according exception message

2019-03-08 18:15 UTC, rthadur commented
@shashvatshahi1998 please sign CLA

2019-03-08 18:31 UTC, shashvatshahi1998 commented
i am trying again and again why this is not working.

2019-03-08 18:32 UTC, shashvatshahi1998 commented
ok its done

2019-03-08 20:52 UTC, alextp commented on tensorflow/python/eager/backprop.py
> +    if not isinstance(variables,float):
variables is a list of tensorflow variables. You should check their dtypes

2019-03-09 10:14 UTC, shashvatshahi1998 commented
i have commited once again can you please review it

2019-03-11 16:17 UTC, alextp requested changes

2019-03-11 16:17 UTC, alextp commented on tensorflow/python/keras/activations.py
> +      max_value: float. Saturation threshold.Returns:
This looks wrong

2019-03-11 16:17 UTC, alextp commented on tensorflow/python/eager/backprop.py
> +      if is_floating(v) == False:
"if not is_floating(v)" reads better

2019-03-11 16:17 UTC, alextp commented on tensorflow/python/eager/backprop.py
> +        raise ValueError("Gradient calculation supports only float types.")
Maybe print v so the user can debug?

2019-03-11 16:17 UTC, alextp commented on tensorflow/python/ops/string_ops.py
> +def string_split(source, delimiter=" ", skip_empty=True, maxsplit=-1):  # pylint: disable=invalid-name
The changes in this file seem unrelated. Adding arguments to public API functions in TF requires an extra review step.

2019-03-26 14:23 UTC, closed without merging

2019-03-26 16:12 UTC, alextp commented
Did you mean to close this PR?