doc improvement for tf.math.asin and tf.math.atan
tensorflow/tensorflow pull request #26494
Opened 2019-03-08 19:17 UTC by Sudeepam97

PR for issue #26492

2019-03-11 08:15 UTC, martinwicke requested changes
Do we not have acos? 

Assuming we do, the same change needs to be made there as well I assume.

2019-03-11 08:15 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Asin.pbtxt
> +if `y = tf.math.sin(x)` then, `x = tf.math.asin(y)`.
sin isn't invertible, so this is true for the invertible range [-pi/2, pi/2]. That would be worth mentioning.

2019-03-11 08:15 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Atan.pbtxt
> +if `y = tf.math.tan(x)` then, `x = tf.math.atan(y)`.
same here

2019-03-11 13:49 UTC, Sudeepam97 commented
> Do we not have acos?
> 
> Assuming we do, the same change needs to be made there as well I assume.

Actually, I have fixed acos in #26017. Would you be able to look at that PR as well? It has been pending for a long time.

As for the changes, will writing something like...
**"Note: The output of `tf.math.asin` will lie within the invertible range of sine i.e. [-pi/2, pi/2] "**
...be enough or should I add another usage example that demonstrates this?

2019-03-12 21:47 UTC, martinwicke commented
I think the wording changes you propose are good. 

This comment also applies to #26017, can you make the same change to cos (except of course the range is different)?

2019-03-13 12:35 UTC, Sudeepam97 commented
Alright, I've specified the range for all the three operations.

2019-03-20 15:58 UTC, martinwicke approved these changes

2019-03-20 23:27 UTC, merged

2019-03-21 03:55 UTC, Sudeepam97 commented
@martinwicke will you be able to approve #26017 as well if that PR is fine?