Added description for softmax and sigmoid
tensorflow/tensorflow pull request #26514
Opened 2019-03-09 15:16 UTC by aweers

It's my first contribution so I'm not sure whether everything is right the way i did it. Also I am not a native english speaker so maybe there are some spelling errors.

2019-03-10 00:40 UTC, kyscg requested changes
Try these @aweers

2019-03-10 00:40 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  range (0, 1) and sum to 1. It is is often used as activation of the last layer of a
Maybe change it to:
`It is often used as the activation for the last layer`

2019-03-10 00:40 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  classification network because the result could be interpreted as probability
And this:
`because the result could be interpreted as a probability`

2019-03-10 00:40 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  distribution. To calculate the softmax all inputs `x` become exp(x) divided by the sum
Here:
`To calculate the softmax, all inputs...`

2019-03-10 00:40 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  version of the Heaviside function. For small values (<-5) the sigmoid returns
Maybe put "Unit Step Function" in parenthesis for the Heaviside, the whole point after all is simplicity.

2019-03-10 00:40 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  a value close to zero and for larger values (>5) the result of the funtion gets
function*

2019-03-10 11:30 UTC, aweers commented
Thanks for the feedback @kyscg! I updated the descriptions with your suggestions.

2019-03-10 11:32 UTC, kyscg submitted a review, later dismissed
LGTM @aweers 
Cheers!!

2019-03-11 22:04 UTC, alextp requested changes

2019-03-11 22:04 UTC, alextp commented on tensorflow/python/keras/activations.py
> +  distribution. To calculate the softmax, all inputs `x` become exp(x) divided by the sum
I think an equation reads better than the textual description of it here (the sentence starting with "to calculate" should just show exp(x)/ tf.reduce_sum(exp(x))

2019-03-12 15:33 UTC, alextp submitted a review, later dismissed

2019-03-12 23:55 UTC, rthadur commented
@aweers please resolve conflicts

2019-03-13 16:06 UTC, aweers commented
Hope, everything is ok now! ;)

2019-03-13 22:27 UTC, rthadur commented
> Hope, everything is ok now! ;)

@alextp can you please review

2019-03-13 22:37 UTC, alextp commented on tensorflow/python/keras/activations.py
> +=======
Remove =====

2019-03-14 15:57 UTC, alextp submitted a review, later dismissed

2019-03-22 18:22 UTC, aweers commented
How to fix this error? Can't even see any details when clicking on 'Details'

2019-03-25 10:10 UTC, alextp commented on tensorflow/python/keras/activations.py
>    """Sigmoid activation function.
This extra quote is a syntax error

2019-03-25 16:14 UTC, aweers commented
Thanks @alextp, I hope now everything is right... ;)

2019-03-25 16:31 UTC, alextp approved these changes

2019-03-25 18:24 UTC, merged