Modified activation functions according to tf.keras.activations.tanh #25827
tensorflow/tensorflow pull request #26556
Opened 2019-03-11 02:28 UTC by shashvatshahi1998

I modified tanh(),sigmoid() and exp() functions

2019-03-11 22:29 UTC, alextp requested changes
This PR looks like it has a few unrelated changes. Can you have it have one change only?

2019-03-12 08:55 UTC, shashvatshahi1998 commented
i have updated it

2019-03-12 08:58 UTC, shashvatshahi1998 commented
in this commit i have just added details to exp() function, if you will ask me i will also update tanh ,linear and sigmoid functions.

2019-03-12 10:36 UTC, arp95 commented on tensorflow/python/keras/activations.py
> +>>>>>>> c5ffa1c... modified some activation functions
This seems to be a merge conflict. Please resolve this.

2019-03-12 14:13 UTC, kyscg commented
There's a better fix in #26603 

Think we can close this @alextp @rthadur

2019-03-12 15:47 UTC, closed without merging