Update initializers.py
tensorflow/tensorflow pull request #26560
Opened 2019-03-11 04:55 UTC by PariksheetPinjari909

Added missing documentation string

2019-03-28 13:06 UTC, tensorflowbutler commented
Nagging Reviewer @fchollet, @pavithrasv: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-04-01 11:11 UTC, penpornk requested changes
Thank you for your PR and sorry for our delay!

2019-04-01 11:11 UTC, penpornk commented on tensorflow/python/keras/initializers.py
> +      TruncatedNormal instance.
The indentation is a bit off.
```suggestion
    A TruncatedNormal instance.
```

2019-04-01 11:11 UTC, penpornk commented on tensorflow/python/keras/initializers.py
> +      RandomUniform instance.
```suggestion
    A RandomUniform instance.
```

2019-04-02 04:48 UTC, PariksheetPinjari909 commented
@penpornk I have accepted your suggestion, can you do cla check. Thanks

2019-04-02 05:10 UTC, penpornk approved these changes
Thank you again for your contribution!

CLA: The other contributor is me through github UI so it doesn't detect my CLA. I have verified that the CLA is okay. To make it technically correct, I'll also say I'm okay with contributing to this PR.

2019-04-02 15:20 UTC, penpornk commented
@PariksheetPinjari909 Could you please resolve the conflict?

2019-04-04 04:51 UTC, PariksheetPinjari909 commented
I am closing the PR as the changes are already taken.

2019-04-04 04:51 UTC, closed without merging