Check for memory overflow during tensor allocation
tensorflow/tensorflow pull request #26859
Opened 2019-03-19 04:17 UTC by joyalbin

2019-04-02 18:14 UTC, joyalbin commented
@aselle Could you please review this PR

2019-04-17 13:03 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 14 days with no activity and the `awaiting review` label has been applied.

2019-05-02 13:03 UTC, tensorflowbutler commented
Nagging Reviewer @aselle: You have been added as a reviewer to this pull request. Please add your review or reassign. It has been 29 days with no activity and the `awaiting review` label has been applied.

2019-05-02 17:37 UTC, jdduke requested changes

2019-05-02 17:37 UTC, jdduke commented on tensorflow/lite/core/subgraph.cc
> +    TF_LITE_ENSURE(context_, x >= 0 && y >= 0);
I'm not sure we should return the error as an int64_t here? As that will be ignored?

Either this method should return an error, and the int64_t result is a pointer arg, or we should return -1 here.

2019-05-28 21:37 UTC, rthadur commented
@joyalbin can you please check review comments ?

2019-06-26 20:58 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-06-26 20:58 UTC, closed without merging

2019-12-19 19:05 UTC, aselle commented
Thanks for the submission. I've reworked this internally based on some refactors and also optimized the code from overflow.h to not have to do some checks since we already know it is unsigned this should land soon.