Relu activation optimizations
tensorflow/tensorflow pull request #26939
Opened 2019-03-20 12:56 UTC by siju-samuel

2019-03-25 20:33 UTC, jdduke requested changes

2019-03-25 20:33 UTC, jdduke commented on tensorflow/lite/kernels/internal/optimized/optimized_ops.h
> +  output = input.cwiseMax(-1.0f).cwiseMin(1.0f);
Is this faster than a clamp? Or does it do the same thing? Same for the other activation.

2019-04-22 02:42 UTC, rthadur commented
@siju-samuel gentle ping to address comments

2019-05-28 21:36 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-05-28 21:36 UTC, closed without merging