Added Support for different data types.
tensorflow/tensorflow pull request #26934
Opened 2019-03-20 11:22 UTC by amitsrivastava78

Added different data types along with test cases.

2019-04-16 10:39 UTC, amitsrivastava78 commented
@miaout17 , can you please review the PR.

Regards
Amit

2019-08-20 13:16 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-09-13 23:52 UTC, gunan commented
@rthadur, could you follow up on the review.

2019-09-16 19:12 UTC, rthadur commented
@gunan sure , thanks for the reminder.

2019-09-17 17:34 UTC, miaout17 requested changes
Thanks for the contribution. Mostly looks good. 

Side note: Usually we should bump the op version when adding supported types, but since this the conversion process is experimental and nobody seems to be using it, I think it's fine to stick with version 1.

2019-09-17 17:34 UTC, miaout17 commented on tensorflow/lite/kernels/if.cc
> +  switch (cond->type) {
Is should be possible to significantly shorten the code, like...
```
bool condition;
switch (cond->type) {
    case kTfLiteInt32:
      condition = cond->data.i32[0];
      break;
    case kTfLiteFloat32:
      condition = cond->data.f[0];
      break;
    // omitted...
  }
  active_branch_subgraph_index = condition
                                         ? op_data->then_subgraph_index
                                         : op_data->else_subgraph_index;
  

```

2019-10-02 12:29 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-10-31 12:34 UTC, closed without merging

2019-10-31 12:34 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.