Lite: Slice Op refactored
tensorflow/tensorflow pull request #26936
Opened 2019-03-20 12:36 UTC by ANSHUMAN87

2019-03-29 18:03 UTC, ANSHUMAN87 commented
@jianlijianli : Gentle Reminder!

2019-04-15 17:34 UTC, ANSHUMAN87 commented
@jianlijianli : Gentle Reminder!

2019-05-16 07:10 UTC, ANSHUMAN87 commented
@jianlijianli : Gentle Reminder!

2019-05-29 06:24 UTC, ANSHUMAN87 commented
@jianlijianli : Gentle Reminder!

2019-08-20 13:16 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-11-20 23:04 UTC, jianlijianli commented
Could you please add a high level description what this CL does? Thanks.

2019-11-26 10:02 UTC, gbaned commented
@ANSHUMAN87 Could you please address the reviewer comments and resolve conflicts? Thanks!

2019-12-11 12:29 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-12-12 06:43 UTC, ANSHUMAN87 commented
> Could you please add a high level description what this CL does? Thanks.

Updated!

2020-02-14 11:12 UTC, ANSHUMAN87 commented
@jianlijianli: Gentle reminder!

2020-04-27 15:57 UTC, jdduke submitted a review, later dismissed

2020-05-05 07:35 UTC, ANSHUMAN87 commented
@gbaned: Gentle reminder! Please help merge the PR!

2020-05-05 16:14 UTC, rthadur requested changes
@ANSHUMAN87 can you please check internal error ?

2020-05-05 16:14 UTC, rthadur commented on tensorflow/lite/kernels/slice_test.cc
> +  SliceOpModel<int64_t, int32_t> m({3, 2, 3, 1}, {4}, {4}, TensorType_INT32,
`tensorflow/lite/kernels/slice_test.cc:242:34: error: no matching constructor for initialization of 'SliceOpModel<int64_t, int32_t>' (aka 'SliceOpModel<long, int>')
  SliceOpModel<int64_t, int32_t>`

2020-05-05 16:14 UTC, rthadur commented on tensorflow/lite/kernels/slice_test.cc
> +  SliceOpModel<bool, int32_t> m({2, 3}, {2}, {2}, TensorType_INT32,
`tensorflow/lite/kernels/slice_test.cc:253:31: error: no matching constructor for initialization of 'SliceOpModel<bool, int32_t>' (aka 'SliceOpModel<bool, int>')
  SliceOpModel<bool, int32_t> m({2, 3}, {2}, {2}, TensorType_INT32,`

2020-05-08 15:22 UTC, gbaned commented
@ANSHUMAN87 Can you please check @rthadur's comments and keep us posted. Thanks!

2020-05-09 17:29 UTC, ANSHUMAN87 commented
@gbaned , @rthadur : It is strange i am unable to reproduce the errors as you mentioned.

2020-05-09 21:15 UTC, ANSHUMAN87 commented
@gbaned , @rthadur : The failure is resolved now, Thanks!

2020-06-09 14:57 UTC, ANSHUMAN87 commented
@gbaned , @rthadur : I do not think there is anything left for this PR as @jdduke : already approved this PR earlier. Can you please expedite and merge this PR. Thanks!

2020-06-09 15:52 UTC, rthadur commented
@ANSHUMAN87 sorry for the delay , will try to pull this again , thank you

2020-06-09 15:52 UTC, rthadur approved these changes

2020-06-10 00:37 UTC, rthadur submitted a review, later dismissed

2020-06-15 15:22 UTC, ANSHUMAN87 commented
> @ANSHUMAN87 getting below error , can you please check
> `/tensorflow/lite/kernels/test_util.cc:317 Expected equality of these values: CountPartitionsDelegatedTo(interpreter_.get(), TestNnApiDelegate()) Which is: 0 1 Expecting operation to be accelerated but cannot find a partition associated to the NNAPI delegate`

@rthadur : Sorry for late response! The error you posted does not seem to be relevant to my change! Please let me know, if anything needs to be done from my end. Thanks!

2020-06-17 00:42 UTC, rthadur commented
@jianlijianli @jdduke  can you please help with internal failures ?

2020-06-17 17:15 UTC, jdduke requested changes

2020-06-17 17:15 UTC, jdduke commented on tensorflow/lite/kernels/slice_test.cc
> +TEST_P(SliceOpTest, SliceInt64) {
You'll need to blacklist these 2 new tests @ https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/nnapi/acceleration_test_list.cc#L330

2020-07-03 14:56 UTC, gbaned commented
@ANSHUMAN87 Can you please check @jdduke's comments and keep us posted. Thanks!

2020-07-03 15:45 UTC, ANSHUMAN87 commented
@gbaned : Thanks for tracking it! I have updated based on @jdduke comment for the internal failure reported by @rthadur .
Can you please approve it, and check for merge, as the new change is only to disable the test cases ? TIA!

2020-07-06 21:00 UTC, rthadur approved these changes

2020-07-09 22:21 UTC, merged

2020-07-10 06:43 UTC, ANSHUMAN87 commented
Thanks @jdduke, @rthadur, @gbaned!