optimized RNNBatchStep source code
tensorflow/tensorflow pull request #26982
Opened 2019-03-21 10:54 UTC by joyalbin

TODO(mirkov,raziel): replace this for-loop with a MACRO (or function)

2019-05-09 09:29 UTC, gbaned commented
@aselle Could you PTAL and approve.

2019-08-02 15:01 UTC, talumbau requested changes

2019-08-02 15:01 UTC, talumbau commented on tensorflow/lite/kernels/internal/kernel_utils.cc
> +#define TFLITE_QUANTIZE_GET_MIN_MAX(units, batch, quantized_batch, scale) \
Do you have data that suggests this macro is faster than an inlined function? Overall I think this is good to get rid of code duplication, but would only go this route if we had evidence that an inline function here was slower.

2019-08-07 12:23 UTC, gbaned commented
@joyalbin Could you please address the reviewer comments. Thanks!

2019-08-20 13:16 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-08-26 05:28 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-08-26 05:28 UTC, closed without merging