Comment added in keras.layers.core.py
tensorflow/tensorflow pull request #27057
Opened 2019-03-23 09:03 UTC by gshashank84

Comment added for clarification on the question "why do we use **tensordot** to compute dot product here?".
#25780

2019-03-24 03:34 UTC, shahzadlone approved these changes

2019-04-25 20:50 UTC, gshashank84 commented
I have added comment for better understanding of the other person, what is your point of view? @pavithrasv

2019-04-26 23:47 UTC, fchollet commented on tensorflow/python/keras/layers/core.py
> +      # tensordot(inputs, weights, axes)
I don't understand what the comment mean, please rephrase.

2019-04-26 23:48 UTC, fchollet requested changes
I don't understand what the comment mean, please rephrase.

2019-05-20 21:37 UTC, pavithrasv commented on tensorflow/python/keras/layers/core.py
> +      # tensordot(inputs, weights, axes)
This still feels unclear to me and I think that the `tensordot` API documentation is sufficient here and we probably do not need this comment.

2019-05-20 21:44 UTC, closed without merging