tf.compat.path_to_str  #25826
tensorflow/tensorflow pull request #27335
Opened 2019-03-31 06:35 UTC by shashvatshahi1998

Added some usage examples #25826

2019-03-31 06:45 UTC, shashvatshahi1998 commented
@rthadur  please assign reviewers please

2019-03-31 09:55 UTC, shashvatshahi1998 commented
please somebody review

2019-04-01 04:57 UTC, shashvatshahi1998 commented
Please @xiejw  review this pr

2019-04-04 03:56 UTC, shashvatshahi1998 commented
Please somebody review this PR @rthadur , @tomhennigan , @mihaimaruseac

2019-04-04 17:04 UTC, mihaimaruseac reviewed
Looks good, minor nits and a request to actually run the examples

2019-04-04 17:04 UTC, mihaimaruseac commented on tensorflow/python/util/compat.py
> +  Examples:
Add an empty line above `Examples:` please

2019-04-04 17:04 UTC, mihaimaruseac commented on tensorflow/python/util/compat.py
> +  'C:\\XYZ\tensorflow\\./.././tensorflow' # Windows OS
Shouldn't it be `XYZ\\tensorflow` (double backslash)?

Can you actually run it and see what the output should be when backslashes and slashes are mixed?

2019-04-04 17:04 UTC, mihaimaruseac commented on tensorflow/python/util/compat.py
> +  'C:\\XYZ\tensorflow\\..\\tensorflow' # Windows OS
Same as above

2019-04-05 07:21 UTC, shashvatshahi1998 commented
@mihaimaruseac  I have done the changes requested by you, now can you please review it

2019-04-05 08:11 UTC, shashvatshahi1998 commented
@rthadur , @mihaimaruseac please somebody review it.

2019-04-05 13:45 UTC, shashvatshahi1998 commented
Please @mihaimaruseac  review it now.

2019-04-05 15:37 UTC, mihaimaruseac reviewed
Thank you for the updates, there is a trailing whitespace which you should remove and then all is good.

2019-04-05 15:37 UTC, mihaimaruseac commented on tensorflow/python/util/compat.py
> +
Trailing whitespace

2019-04-05 18:22 UTC, shashvatshahi1998 commented
@mihaimaruseac I am not able to remove that white trailing space, I tried for 10 times atleast how to remove that there is nothing to be removed , please help.

2019-04-05 18:49 UTC, mihaimaruseac commented
In your editor, you go to that line and press delete/backspace a few times.

Most editors can be configured to remove trailing whitespace on save. What editor are you using?

2019-04-05 19:02 UTC, shashvatshahi1998 commented
I am using vim editor

2019-04-05 19:11 UTC, shashvatshahi1998 commented
Done with changes @mihaimaruseac , now please approve it and merge it.

2019-04-05 19:22 UTC, mihaimaruseac submitted a review, later dismissed

2019-04-06 01:22 UTC, shashvatshahi1998 commented
@mihaimaruseac,@rthadur why there is ubuntu sanity check , please somebody guide me.

2019-04-06 02:14 UTC, shashvatshahi1998 commented
Please, @mihaimaruseac, @rthadur help me with this ubuntu sanity check, I'm not getting the reason for the error.

2019-04-06 04:39 UTC, mihaimaruseac commented
Click on details then on log

```
1. do_pylint PYTHON2: Python 2 pylint
  FAIL
2. do_pylint PYTHON3: Python 3 pylint
  FAIL
```

Basically you're not following PEP8 style guide so code cannot be merged. Please fix.

2019-04-06 05:24 UTC, shashvatshahi1998 commented
What's wrong in my style I am not able to understand.

2019-04-06 05:33 UTC, shashvatshahi1998 commented
I have tried to change a little bit can you please tell me what can I do further.

2019-04-06 12:00 UTC, shashvatshahi1998 commented
@mihaimaruseac  please review it once and tell me further changes.

2019-04-06 14:10 UTC, mihaimaruseac commented
You didn't fix the error, instead changed irrelevant lines.

If you look at the [error log](https://source.cloud.google.com/results/invocations/7a6a3039-f030-40c3-a3d0-20605ad514e2/log) it says right there

```
FAIL: Found 1 non-whitelited pylint errors:
tensorflow/python/util/compat.py:123: [C0301(line-too-long), ] Line too long (89/80)
```

You can run the linter locally too, see https://pypi.org/project/pep8/

2019-04-06 14:42 UTC, shashvatshahi1998 commented
@mihaimaruseac  I have reduced the lengths of all the lines(<80) according to pylint norms, so now can you please review it.

2019-04-06 15:08 UTC, mihaimaruseac requested changes

2019-04-06 15:08 UTC, mihaimaruseac commented on tensorflow/python/util/compat.py
> +  else as it is.
Don't change this line. I know it is already too long but first phrase in docstring should always be on a single line and followed by empty space (please run linter locally and check the warnings issued on the lines you're changing).

2019-04-06 16:25 UTC, shashvatshahi1998 commented
@mihaimaruseac I have done the changes requested by you now you can review it.

2019-04-06 17:07 UTC, mihaimaruseac approved these changes
Thank you. I think it will get merged on Monday though

2019-04-06 17:11 UTC, shashvatshahi1998 commented
@rthadur please apply kokoro force run

2019-04-07 02:18 UTC, shashvatshahi1998 commented
Please @rthadur apply all checks

2019-04-07 03:40 UTC, mihaimaruseac commented
It's weekend, people are not going to work on this until Monday. Please wait.

2019-04-07 03:42 UTC, mihaimaruseac commented
The Windows Bazel GPU check: don't worry about it, it's not your PR's fault. But until MondayTuesday there likely won't be a fix to it.

2019-04-08 02:24 UTC, shashvatshahi1998 commented
Please somebody check the internal CI build please.

2019-04-08 15:52 UTC, shashvatshahi1998 commented
@mihaimaruseac please now its more than 2 days please assign someone to check import/copybara

2019-04-08 16:00 UTC, mihaimaruseac commented
It's Monday morning, people have not yet come to the office. When @rthadur comes in he will apply the copybara checks.

There is one issue though, which you should fix before: since you include commits changing other files, copybara sees a change in `api_def_Bitcast.pbtxt` which shouldn't be (but it is included because of d3c1f4a).

You could try rebasing/squashing these commits to only have one single commit doing the exact change this PR does. Not fixing this will make merging the PR slower

2019-04-08 18:11 UTC, shashvatshahi1998 commented
@mihaimaruseac why merging is still blocked when all required checks are done?

2019-04-08 18:19 UTC, mihaimaruseac commented
Because `￼Windows Bazel GPU — Internal CI build failed`

2019-04-08 18:25 UTC, shashvatshahi1998 commented
@mihaimaruseac  what can I do for Windows Bazel GPU test.

2019-04-08 18:29 UTC, mihaimaruseac commented
Just wait.

2019-04-09 16:05 UTC, mihaimaruseac commented
That test fails in several PRs, just wait for it to be fixed and then the PR will be merged automatically. Unless mentioned again, you don't have anything else to do for this PR (except maybe clean it up, squash/remove old commits)

2019-04-10 15:07 UTC, shashvatshahi1998 commented
@mihaimaruseac what happened to it now 4 tests are failing why?

2019-04-10 15:17 UTC, mihaimaruseac commented
Other tests failed. They were run because your PR touched other files so they were marked as required to run before merging. Please try to have clean PRs in the future.

You don't have to do anything here though, this will get merged in a few minutes

2019-04-10 15:18 UTC, mihaimaruseac commented
See 66d7a531f as the commit merging this.

2019-04-10 15:18 UTC, closed without merging

2019-04-10 15:28 UTC, shashvatshahi1998 commented
@mihaimaruseac sure, I will try to submit PRs with no unwanted commits.