Updated docs formatting
tensorflow/tensorflow pull request #27588
Opened 2019-04-06 19:51 UTC by neighlyd

tf.feature_column.categorical_column_with_vocabulary_file defined in python/feature_column/feature_column_v2.py.

2019-04-07 05:04 UTC, rthadur commented
@neighlyd thanks for your contribution, please sign CLA

2019-04-08 16:59 UTC, dynamicwebpaige submitted a review, later dismissed
LGTM! Thanks for these fixes.

2019-04-08 17:37 UTC, mihaimaruseac approved these changes

2019-04-08 17:48 UTC, rthadur commented
@neighlyd gentle ping to sign CLA

2019-04-08 17:59 UTC, neighlyd commented
I signed it this morning!

On Sat, Apr 6, 2019 at 12:54 PM googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project (if not, look below for help).
> Before we can look at your pull request, you'll need to sign a Contributor
> License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed (or fixed any issues), please reply here (e.g. I
> signed it!) and we'll verify it.
> ------------------------------
> What to do if you already signed the CLA Individual signers
>
>    - It's possible we don't have your GitHub username or you're using a
>    different email address on your commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>
> Corporate signers
>
>    - Your company has a Point of Contact who decides which employees are
>    authorized to participate. Ask your POC to be added to the group of
>    authorized contributors. If you don't know who your Point of Contact is,
>    direct the Google project maintainer to go/cla#troubleshoot (Public
>    version <https://opensource.google.com/docs/cla/#troubleshoot>).
>    - The email used to register you as an authorized contributor must be
>    the email used for the Git commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - The email used to register you as an authorized contributor must
>    also be attached to your GitHub account
>    <https://github.com/settings/emails>.
>
> ℹ️ *Googlers: Go here
> <https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftensorflow%2Fpull%2F27588>
> for more info*.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/27588#issuecomment-480532682>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIrDh-UKDvj2VqQ7N35Yyu9mOyN0Z2Izks5vePtXgaJpZM4cgYpl>
> .
>

2019-04-08 17:59 UTC, neighlyd commented
I apologize, it looks like I hadn't replied to the googlebot's CLA message! I went ahead and did that.

2019-04-10 18:42 UTC, mihaimaruseac requested changes

2019-04-10 18:42 UTC, mihaimaruseac commented on tensorflow/python/feature_column/feature_column_v2.py
> +  other 50 each have a 2-character U.S. state abbreviation. Both a literal `'XX'`
Linter reports error here

```
FAIL: Found 1 non-whitelited pylint errors:
tensorflow/python/feature_column/feature_column_v2.py:1608: [C0301(line-too-long), ] Line too long (81/80)
```

2019-04-11 00:02 UTC, mihaimaruseac approved these changes
Thank you

2019-04-11 20:15 UTC, merged