Updated Doc: Change Formatting of Source Paper Link
tensorflow/tensorflow pull request #27591
Opened 2019-04-06 21:17 UTC by BradHuang1999

Changed direct arxiv link to format with paper title and authors that looks like:

See Source [Batch Normalization: Accelerating Deep Network Training by Reducing 
Internal Covariate Shift, S. Ioffe, C. Szegedy](http://arxiv.org/abs/1502.03167).

2019-04-06 23:28 UTC, kyscg requested changes

2019-04-06 23:28 UTC, kyscg commented on tensorflow/python/ops/nn_impl.py
> +  See Source [Batch Normalization: Accelerating Deep Network Training by Reducing
```suggestion
  See Source: [Batch Normalization: Accelerating Deep Network Training by Reducing 
```

2019-04-06 23:28 UTC, kyscg commented on tensorflow/python/ops/nn_impl.py
> +  Internal Covariate Shift, S. Ioffe, C. Szegedy](http://arxiv.org/abs/1502.03167).
```suggestion
  Internal Covariate Shift; S. Ioffe, C. Szegedy](http://arxiv.org/abs/1502.03167).
```

2019-04-06 23:28 UTC, kyscg commented on tensorflow/python/ops/nn_impl.py
> +  See Source [Batch Normalization: Accelerating Deep Network Training by Reducing
```suggestion
  See Source: [Batch Normalization: Accelerating Deep Network Training by Reducing 
```

2019-04-06 23:28 UTC, kyscg commented on tensorflow/python/ops/nn_impl.py
> +  Internal Covariate Shift, S. Ioffe, C. Szegedy](http://arxiv.org/abs/1502.03167).
```suggestion
  Internal Covariate Shift; S. Ioffe, C. Szegedy](http://arxiv.org/abs/1502.03167).
```

2019-04-07 05:08 UTC, rthadur commented
@BradHuang1999 please sign CLA

2019-04-07 06:03 UTC, BradHuang1999 commented
@rthadur Already have. It seems that since I have integrated @kyscg’s change, we will need his consent as well

2019-04-07 06:58 UTC, kyscg commented
I've signed it

2019-04-08 04:43 UTC, kyscg approved these changes

2019-04-08 19:00 UTC, ymodak approved these changes

2019-04-12 16:48 UTC, kyscg commented
@rthadur @gbaned Gentle ping to pull

2019-04-12 17:42 UTC, rthadur commented
@BradHuang1999 can you please resolve conflicts.

2019-04-12 17:51 UTC, BradHuang1999 commented
Done.

2019-04-12 17:57 UTC, kyscg commented
@rthadur It's done, gentle ping to set CLA's to yes and pull. Thankss

2019-04-22 01:26 UTC, kyscg commented
@rthadur It's been a while, could you pull this in, all changes have been approved

2019-05-01 19:50 UTC, merged