[doc/keras] incorrect comment in the example for `tf.keras.layers.Add` #27632
tensorflow/tensorflow pull request #27637
Opened 2019-04-08 12:44 UTC by shashvatshahi1998

Issue #27632

2019-04-08 12:45 UTC, shashvatshahi1998 commented
Removed typo

2019-04-08 14:19 UTC, csukuangfj reviewed
line 239 should be removed

2019-04-08 15:26 UTC, mihaimaruseac commented
Please make sure the commits on the PR are only those needed for the PR. It makes integrating the code much harder to have commits touching other files.

You can create branches for each topic of work you chose to do, push the branches, make PRs with those branches only. Plus, on each branch you can `git squash`, `git rebase`, etc, to make everything look clean and neat and get approval and merging much faster.

2019-04-08 16:47 UTC, mihaimaruseac requested changes
Please include only files that are needed for the PR. Use multiple branches, rebase them.

2019-04-08 16:47 UTC, mihaimaruseac commented on tensorflow/python/keras/layers/pooling.py
> +    pool_size: Integer, size of the max  pooling windows.
This shouldn't be in this PR.

2019-04-08 16:55 UTC, shashvatshahi1998 commented
@mihaimaruseac I have removed that unwanted line but when I am trying to rebase my previous commits , I am facing some issues.

2019-04-08 16:59 UTC, mihaimaruseac commented
Can you elaborate on the issues?

For future references, here's how I would do multiple PRs to the same repo:

1. fork the repo on github (delete old fork before)
2. `git clone` your fork
3. `git checkout -b $NAME` where `$NAME` would be the name of the branch
4. work only on one thing there, commit often
5. `git rebase -i ...` reorder commits, squash, cleanup
6. `git push`, make PR, go to step 3 with a different branch

Whenever you have to work on a PR you `git checkout` the corresponding branch, work on it and push and the PR updates automatically

2019-04-10 14:30 UTC, mihaimaruseac commented
@shashvatshahi1998 ping on this?

2019-04-11 16:44 UTC, mihaimaruseac commented
@shashvatshahi1998 should we also close this and reopen as a clean PR?

2019-04-22 02:54 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-04-22 02:54 UTC, closed without merging