[doc/keras] incorrect comment in `__init__` of `tf.keras.layers.AveragePooling1D` #27633
tensorflow/tensorflow pull request #27641
Opened 2019-04-08 13:52 UTC by shashvatshahi1998

#27633

2019-04-08 15:29 UTC, mihaimaruseac commented
Linking [to this comment](https://github.com/tensorflow/tensorflow/pull/27637#issuecomment-480879996) to make PRs look clean and easier to review and merge. Please follow

2019-04-08 16:51 UTC, mihaimaruseac approved these changes
Approved, but since the PR is not clean it might cause issues downstream. Please make clean PRs in the future

2019-04-08 16:52 UTC, mihaimaruseac requested changes
This changes `MaxPooling`, not `AveragePooling`

2019-04-08 17:59 UTC, shashvatshahi1998 commented
@mihaimaruseac  now I have corrected it.

2019-04-08 18:18 UTC, mihaimaruseac commented
#27633 also mentions `input_shape` and `output_shape` lists being badly formatted. Can you please make a PR for those too (separate from this one and not including all of these unrelated changes)?

2019-04-08 18:18 UTC, mihaimaruseac submitted a review, later dismissed

2019-04-08 18:54 UTC, shashvatshahi1998 commented
Input shape:
    - If `data_format='channels_last'`:
      3D tensor with shape `(batch_size, steps, features)`.
    - If `data_format='channels_first'`:
      3D tensor with shape `(batch_size, features, steps)`.

  Output shape:
    - If `data_format='channels_last'`:
      3D tensor with shape `(batch_size, downsampled_steps, features)`.
    - If `data_format='channels_first'`:
      3D tensor with shape `(batch_size, features, downsampled_steps)`.
@mihaimaruseac  so you want me to edit this input and output shape description in average_pooling function.

2019-04-08 19:03 UTC, mihaimaruseac commented
In a __different PR__, if you do it. If you don't do it, that's also ok, just don't close #27633` then.

2019-04-11 14:46 UTC, mihaimaruseac commented
You will have to resolve conflicts before this can be merged.

2019-04-11 15:49 UTC, shashvatshahi1998 commented
@mihaimaruseac  removed the merge conflicts.

2019-04-11 15:52 UTC, mihaimaruseac requested changes
You're undoing previous PR now.

2019-04-11 15:52 UTC, mihaimaruseac commented on tensorflow/python/util/compat.py
> +
This change is unrelated and just undoes your previously merged PR.

I suggest we close this one and start a new PR from a fresh fork, making it a clean PR.

2019-04-11 16:09 UTC, shashvatshahi1998 commented
ok let's close this PR

2019-04-11 16:43 UTC, closed without merging

2019-04-11 16:43 UTC, mihaimaruseac commented
Please reopen from a new fork, as a clean PR.