[Intel MKL] update mkl addn op for multi-input
tensorflow/tensorflow pull request #27772
Opened 2019-04-12 05:47 UTC by guizili0

2019-04-12 22:11 UTC, penpornk requested changes
Thank you for your PR! I have minor formatting changes.

2019-04-12 22:11 UTC, penpornk commented on tensorflow/core/kernels/mkl_aggregate_ops.cc
> +            auto tf_data_format =
This and the line above can be done after `GetMklShape(ctx, mkl_input_index, &mkl_shape);` in line 167.

2019-04-12 22:11 UTC, penpornk commented on tensorflow/core/kernels/mkl_aggregate_ops.cc
> +        // all inputs are in Eigen input, get the shape from first one.
```suggestion
        // All inputs have TF shapes, get the shape from first one.
```

2019-04-16 08:22 UTC, guizili0 commented on tensorflow/core/graph/mkl_layout_pass.cc
> -  }
For multi input of float add, change input order will have very little influence on the precision, so we remove this sort.

2019-04-16 08:23 UTC, guizili0 commented
@penpornk I have update my code based on your comments, please help to review it again, thanks.

2019-04-16 17:07 UTC, penpornk approved these changes
Thank you for the fixes and the clarifications!

2019-04-18 01:25 UTC, merged