Porting of Relu variant to TFLite Micro.
tensorflow/tensorflow pull request #27810
Opened 2019-04-13 08:29 UTC by amitsrivastava78

This is for HiKey Borads.

2019-04-13 08:30 UTC, amitsrivastava78 commented
I am planning to put padding, round, prelu  along with lstm support for tflite Macro, let me know if this work is conflicting with anyone.

Regrds
Amit

2019-04-25 13:04 UTC, amitsrivastava78 commented
@aselle , I have resolved the merge conflicts, can you please take a look.

Regards
Amit

2019-05-15 05:47 UTC, amitsrivastava78 commented
@petewarden , great fan of your blogs , i have re-based the code again ,kindly have a look, also let me know if you want me to split the activation kernels into different files ?

Regards
Amit

2019-05-24 10:30 UTC, amitsrivastava78 commented
@petewarden  can you please respond to the above query.

Regards
Amit

2019-06-04 11:00 UTC, gbaned commented
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

2019-06-04 11:26 UTC, amitsrivastava78 commented
> @amitsrivastava78 Could you please resolve the conflicts? Thanks!

@gbaned , conflict resolved.

Regards
Amit

2019-08-01 20:37 UTC, petewarden requested changes

2019-08-01 20:37 UTC, petewarden commented on tensorflow/lite/experimental/micro/kernels/relu_variants.cc
> +  return new PreluOpData;
We can't use new/delete in Micro unfortunately. You can check out some of the other kernel implementations for the pattern we use instead.

2019-08-02 03:01 UTC, amitsrivastava78 commented
@petewarden , thanks for your comments, i have updated the code as per your suggestion, 
Resolved the merge conflicts and tested the code again. kindly have a look.

Regards
Amit

2019-08-09 10:26 UTC, gbaned commented
@amitsrivastava78 Could you please resolve the conflicts? Thanks!

2019-08-20 13:14 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-08-29 09:31 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-08-29 09:31 UTC, closed without merging