[TF 2.0 docs] Add example for EarlyStopping
tensorflow/tensorflow pull request #27838
Opened 2019-04-14 17:44 UTC by aweers

I think a short example like this is very useful for user who don't have much experience and want to use a callback for their first time.

2019-04-14 17:45 UTC, aweers commented
If the responses are positive I will create examples for the other callbacks, too. ;)

2019-04-14 17:58 UTC, kyscg requested changes
Great work @aweers 

I tried to make the comments interactive. Change these and keep going

Cheers!!!

2019-04-14 17:58 UTC, kyscg commented on tensorflow/python/keras/callbacks.py
> +  # first create the callback
```suggestion
  # Firstly, let's create the callback
```

2019-04-14 17:58 UTC, kyscg commented on tensorflow/python/keras/callbacks.py
> +  # this callback will stop training when there is no improvement in
```suggestion
  # This callback will stop training when there is no improvement in
```

2019-04-14 17:58 UTC, kyscg commented on tensorflow/python/keras/callbacks.py
> +  # validation loss for three epochs
```suggestion
  # the validation loss for three consecutive epochs.
```

2019-04-14 17:58 UTC, kyscg commented on tensorflow/python/keras/callbacks.py
> +  # then simply train the model with the callback
```suggestion
  # We now simply train the model with the callback.
```

2019-04-14 20:06 UTC, aweers commented
Thank you again @kyscg! I like the interactive style and will try to make the next examples in a similiar way!

2019-04-15 05:44 UTC, kyscg submitted a review, later dismissed

2019-04-15 17:00 UTC, rthadur commented
@aweers can you please sign CLA

2019-04-15 17:28 UTC, aweers commented
@rthadur I signed the CLA ;)

2019-04-22 01:24 UTC, kyscg commented
@rthadur @rchao Gentle ping to review

2019-04-22 17:48 UTC, rchao commented on tensorflow/python/keras/callbacks.py
> +  # This callback will stop training when there is no improvement in
s/stop training/stop the training

2019-04-22 17:49 UTC, rchao commented on tensorflow/python/keras/callbacks.py
> +  # Firstly, let's create the callback
This line of comment is probably self-explanatory by the code.

2019-04-22 17:49 UTC, rchao commented on tensorflow/python/keras/callbacks.py
> +  # We now simply train the model with the callback.
This line as well, self-explanatory by model.fit()

2019-04-22 17:50 UTC, rchao reviewed
Thanks for the PR! Please see the comments.

2019-04-22 18:33 UTC, aweers commented
@rchao I updated the file with your suggestions

2019-04-22 18:36 UTC, aweers commented
But somehow I don't see a new commit? Only if I try to edit the file again, I see the changes I made...

2019-04-22 18:44 UTC, rchao commented
> But somehow I don't see a new commit? Only if I try to edit the file again, I see the changes I made...

Thanks! I don't see it either. Please let me know once the commit is made.

2019-04-23 15:05 UTC, aweers commented
@rchao @rthadur now the commit is made, don't know why it took some time... But CLA check failed again, so it need to be set by you ;)

2019-04-23 20:22 UTC, rchao approved these changes
Looks good! Thank you.

2019-05-01 19:01 UTC, merged