[TF 2.0 docs] Add description for activation functions
tensorflow/tensorflow pull request #27835
Opened 2019-04-14 13:36 UTC by aweers

Add descriptions to softplus, softsign and tanh. I am not a native English speaker, so maybe there are some spelling errors.

2019-04-14 14:42 UTC, kyscg requested changes
Nice contribution, could you please make the following changes?

I've made them out for you, just accept the suggested changes.

Cheers!!

2019-04-14 14:42 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  value close to zero, for positve values the result of
```suggestion
  value close to zero, for positive values the result of 
```

2019-04-14 14:42 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  the function is similiar to the result a linear function
```suggestion
  the function is similar to what a linear function 
```

2019-04-14 14:42 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  """The Softsign activation function is similiar to the
```suggestion
  """The Softsign activation function is similar to the 
```

2019-04-14 14:42 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  has a smaller slope than tanh.
```suggestion
  has a smaller slope. 
```

2019-04-14 14:42 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  """The Hyperbolic Tangent activation function is a similiar to the
```suggestion
  """The Hyperbolic Tangent activation function is a similar to the 
```

2019-04-14 14:42 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  sigmoid activation function. It has also a smooth curve from its
```suggestion
  sigmoid activation function. It also is a smooth curve ranging within 
```

2019-04-14 14:42 UTC, kyscg commented on tensorflow/python/keras/activations.py
> +  minimum to its maximum value. The difference to the sigmoid function
```suggestion
  its minimum and maximum value. The difference from the sigmoid function 
```

2019-04-14 14:55 UTC, kyscg commented
We've signed the CLA's. @rthadur, could you set CLA's to yes and review please

Thanks..

2019-04-14 14:55 UTC, aweers commented
Thanks, @kyscg for the improvements! ;)

2019-04-14 14:56 UTC, kyscg submitted a review, later dismissed

2019-04-15 14:55 UTC, kyscg commented
@rthadur, gentle ping to review and set CLA's to yes

2019-04-15 17:09 UTC, rthadur commented
@aweers thank you for your contribution , please make sure all the contributors have signed CLA

2019-04-15 17:26 UTC, aweers commented
@rthadur @kyscg and I signed the cla and we are the only contributors ;)

2019-04-22 01:24 UTC, kyscg commented
@rthadur @akshaym Gentle ping to review

2019-04-26 23:24 UTC, fchollet requested changes
Thank you for the PR. You should format docstrings according to the TensorFlow style conventions; in particular, the docstring should start with a single line ending in a period, followed by 2 line breaks.

2019-04-28 16:25 UTC, aweers commented
Hi @fchollet, thanks for your suggestions! I hope now everything matches the style conventions. ;)

2019-08-20 13:14 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-11-19 20:14 UTC, rthadur commented
@aweers can you please resolve conflicts ?

2019-12-11 12:29 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-01-09 12:34 UTC, closed without merging

2020-01-09 12:35 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.