Enable AsGraphDefInternal to work with two versions of BatchDatasetOp and add tests for BatchDatasetOp
tensorflow/tensorflow pull request #27876
Opened 2019-04-15 23:33 UTC by feihugis

This PR enables AsGraphDefInternal to work with two versions of BatchDatasetOp and adds tests for `BatchDatasetOp`.

cc: @jsimsa

2019-04-16 01:54 UTC, jsimsa requested changes

2019-04-16 01:54 UTC, jsimsa commented on tensorflow/core/kernels/data/batch_dataset_op_test.cc
> +          /*op_version*/ 1,
you do not have to write for op_version 1 as it is not used anywhere

2019-04-16 01:54 UTC, jsimsa commented on tensorflow/core/kernels/data/batch_dataset_op.cc
> +      if (type_string() == "BatchDataset") {
as per my comment in the test file, please undo this change

2019-04-16 03:32 UTC, feihugis commented
Got it. I rewrite this PR:

- https://github.com/tensorflow/tensorflow/pull/27876/commits/dac2bf1ba9361da4c416776fece91564f7bc174f: Minor updates of the comments in dataset.h file

- https://github.com/tensorflow/tensorflow/pull/27876/commits/bed70239456192e2aa7da32cc34c966c40914af4: add the tests for BatchDatasetOp (remove the parts for op_version 1)

2019-04-16 03:46 UTC, jsimsa submitted a review, later dismissed

2019-04-17 15:30 UTC, feihugis commented
The failure log for the test `Ubuntu CC` can't be accessed. Could you please help check the log?

2019-04-19 23:23 UTC, feihugis commented
The `Ubuntu CC` test runs successfully on my laptop. @gbaned Could you please help re-trigger the test?

2019-04-23 18:59 UTC, feihugis commented
Thanks @gbaned for re-triggering the tests. 

Recently, some changes (https://github.com/tensorflow/tensorflow/commit/0c23c60a1a013901c85e340c60afdfd9ec6e9dce#diff-79a93a3e76fded5f3522ad99b27976fd) were added to `BatchDatasetV2`, which causes the test failures. Will revise this PR accordingly.

2019-04-25 09:45 UTC, gbaned commented
@feihugis Any update please?  Thanks!

2019-04-25 15:13 UTC, feihugis commented
@gbaned Sorry for the delay as I'm in a conference these two days. Will fix the issue today.

2019-04-25 17:39 UTC, feihugis commented
> Recently, some changes ([0c23c60#diff-79a93a3e76fded5f3522ad99b27976fd](https://github.com/tensorflow/tensorflow/commit/0c23c60a1a013901c85e340c60afdfd9ec6e9dce#diff-79a93a3e76fded5f3522ad99b27976fd)) were added to `BatchDatasetV2`, which causes the test failures. Will revise this PR accordingly.

@jsimsa @gbaned The new attr `parallel_copy` is added to `BatchDatasetOpTest` via https://github.com/tensorflow/tensorflow/pull/27876/commits/6e7399a4ca8df3b7d55f981605d32a00aaf51890. Could you please have a look at the change when you get a chance?

2019-05-01 17:52 UTC, feihugis commented
> Recently, some changes ([0c23c60#diff-79a93a3e76fded5f3522ad99b27976fd](https://github.com/tensorflow/tensorflow/commit/0c23c60a1a013901c85e340c60afdfd9ec6e9dce#diff-79a93a3e76fded5f3522ad99b27976fd)) were added to `BatchDatasetV2`, which causes the test failures. Will revise this PR accordingly.
> 
@jsimsa `BatchDatasetV2` got a new attribute (`parallel_copy`), so I revise this PR accordingly by adding `parallel_copy` to `BatchDatasetOpTest` via [6e7399a](https://github.com/tensorflow/tensorflow/commit/6e7399a4ca8df3b7d55f981605d32a00aaf51890). Could you please review the change when you have time?

2019-05-01 18:01 UTC, jsimsa approved these changes

2019-05-03 17:17 UTC, merged