Lite: Unpack quantization support added
tensorflow/tensorflow pull request #27881
Opened 2019-04-16 05:29 UTC by ANSHUMAN87

Quantization support added for Unpack Op

2019-04-16 06:20 UTC, ANSHUMAN87 commented
Add ref: #27760

2019-04-16 17:37 UTC, jdduke commented
We should also bump the operator version when using quantized types. See also [this commit](https://github.com/tensorflow/tensorflow/commit/e476315d4484ed2b344983e1c5258b976927257c) for an example of how to bump version(s) when adding new features/types to an existing operator.

2019-04-17 04:15 UTC, ANSHUMAN87 commented
> We should also bump the operator version when using quantized types. See also [this commit](https://github.com/tensorflow/tensorflow/commit/e476315d4484ed2b344983e1c5258b976927257c) for an example of how to bump version(s) when adding new features/types to an existing operator.

@jdduke : Your comment is addressed now, please check, Thanks!

2019-04-18 15:36 UTC, jdduke commented
Adding @suharshs and @jianlijianli for review.

2019-04-18 15:39 UTC, jdduke requested changes

2019-04-18 15:39 UTC, jdduke commented on tensorflow/lite/kernels/unpack.cc
> +    // unpacking quantized tensors.
This comment is slightly confusing, checking quantization match makes sense, but "we do not support unacking quantized tensors" doesn't sound right, as that's exactly what we're doing? Did you mean rescaling quantized tensors?

2019-04-18 15:39 UTC, jdduke commented
Looks good, thanks!

2019-04-24 07:58 UTC, ANSHUMAN87 commented
@rthadur : Would you please help proceed with this PR, Thanks!

2019-04-24 08:23 UTC, gbaned commented
@suharshs, @jianlijianli Could you PTAL and approve.

2019-04-24 23:37 UTC, jianlijianli submitted a review, later dismissed
Thanks for adding this. Logic looks great. Please address the comment jdduke has. Thanks!

2019-04-25 06:51 UTC, ANSHUMAN87 commented
@jdduke : Your comment is addressed now, Thanks!
@jianlijianli : Thanks for approving the PR!

2019-04-26 00:05 UTC, jianlijianli submitted a review, later dismissed
Thanks for the update.

2019-04-30 08:49 UTC, ANSHUMAN87 commented
@gbaned : I have resolved the merge conflict, please help proceed with this PR, thanks!

2019-05-06 03:57 UTC, ANSHUMAN87 commented
@gbaned : Would you please help proceed with this PR, thanks!

2019-05-08 17:16 UTC, jdduke approved these changes

2019-05-10 21:10 UTC, merged