Added error handling code and minor code updates to tensor_shape.py
tensorflow/tensorflow pull request #27962
Opened 2019-04-18 20:09 UTC by SSaishruthi

This PR adds error handling code as well as minor updates to the tensor_shape.py

2019-04-23 22:54 UTC, SSaishruthi commented
@gunan This PR has minor code changes to tensor_shape.py.

2019-04-25 17:38 UTC, gunan commented
I am not the code owner for this file, please redirect.

2019-04-25 17:49 UTC, SSaishruthi commented
@rthadur Can you please assign a reviewer?

2019-04-30 17:27 UTC, qlzh727 requested changes
I don't think swallow the TypeError and ValueError is appropriate in this case. The downside here is that the original error contains actionable details about why the error is happening, while the NotImplemented is too generic and doesn't tell user the error detail.

2019-05-01 16:50 UTC, SSaishruthi commented
@qlzh727 Thanks for the review. I will add code to print Type and Value error

2019-05-01 16:58 UTC, qlzh727 commented
What i feel confused is why not just let it throw the original error? What's the benefit to have NotImplemented here comparing to existing error?

2019-05-03 17:02 UTC, qlzh727 commented
I think I fine with NotImplemented being used at built in binary special methods, eg __eq__, __lt__, etc, so that it will handle those case gracefully, but it shouldn't be used for other case, which explicit error is better. 

Check https://docs.python.org/3/library/constants.html.

2019-05-03 17:54 UTC, SSaishruthi commented
@qlzh727 Makes sense. I have updated `is_compatible_with` and `merge_with` methods. Please let me know if this looks good. Thanks in advance.

2019-05-09 16:57 UTC, SSaishruthi commented
Hi @qlzh727,
Are updates looking good or need further changes?
TIA

2019-05-10 16:15 UTC, qlzh727 commented
What I am still bit confused is why this PR is needed in the first place. Can u give a test case that the existing code will fail in an unpleasant way but the current code won't?

2019-05-10 16:57 UTC, SSaishruthi commented
Thanks, @qlzh727 for the review. I will work on this and update

2019-05-20 04:41 UTC, SSaishruthi commented
Hi @qlzh727 
I am not sure whether to call it an unpleasant way. The current change will directly print the error instead of the traceback. Other methods have similar error handling and that is one of the reasons for the change. 

Current traceback
```
>>> tf.Dimension('-1') == tf.Dimension('1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saishruthi.tn@ibm.com/anaconda3/envs/cp/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 190, in __init__
    raise ValueError("Dimension %d must be >= 0" % self._value)
ValueError: Dimension -1 must be >= 0
```

Proposed will only have the error message
```
ValueError: Dimension -1 must be >= 0
```

Please let me know how we can go about this.

2019-05-20 15:09 UTC, qlzh727 requested changes

2019-05-20 15:09 UTC, qlzh727 commented on tensorflow/python/framework/tensor_shape.py
> +      return (type(e), '::', e)
I think this is even more confusing and also break the contract of returning a Boolean value. Now its returning a tuple with errors. 

And also, catching the error and rethrow it is kind of anti-pattern in the code. Why do u want to specially handle these errors? Is it just for hiding the stacktrace?

2019-06-10 04:16 UTC, closed without merging