fix issue #27985
tensorflow/tensorflow pull request #27986
Opened 2019-04-19 14:52 UTC by pminervini

The `dresult` variable may be an `IndexedSlices` object, which does not have a `_copy` method.

2019-04-19 14:54 UTC, pminervini commented
I signed it!

2019-04-19 16:52 UTC, alextp requested changes
Thanks for the contribution!

I'd like a test which fails before this change and passes after, so we don't accidentally break this again.

2019-04-19 18:06 UTC, pminervini commented
@alextp yeah let me briefly look into that

2019-04-19 19:28 UTC, pminervini commented
I managed to reproduce the problem with a small self-contained script:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import tensorflow as tf
import tensorflow.contrib.eager as tfe

config = tf.ConfigProto()
config.gpu_options.allow_growth = True

tf.enable_eager_execution(config=config)

shape = (5, 5)
initializer = tf.random_uniform_initializer(-1.0, 1.0)
var = tfe.Variable(initializer(shape), name='tensor')

with tf.GradientTape() as tape:
        a = tf.gather(tf.gather(var, [0, 1]), [0, 1])
        b = tf.gather(tf.gather(var, [2, 3]), [0, 1])

        x = tf.reshape(tf.concat((a[0], a[1]), axis=0), [1, -1])
        y = tf.reshape(tf.concat((b[0], b[1]), axis=0), [1, -1])

        r = tf.einsum('ij,ij->i', x, y)

g = tape.gradient(r, [var])
```

Here's the output - I'll commit a unit test shortly.

```bash
$ ./fun.py 
2019-04-19 20:27:55.511171: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-19 20:27:55.580302: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-19 20:27:55.580656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:02:00.0
totalMemory: 11.91GiB freeMemory: 5.75GiB
2019-04-19 20:27:55.580679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-04-19 20:27:55.921738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-19 20:27:55.921768: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-04-19 20:27:55.921779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-04-19 20:27:55.921949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5526 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "./fun.py", line 25, in <module>
    g = tape.gradient(r, [var])
  File "/home/anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/backprop.py", line 901, in gradient
    output_gradients=output_gradients)
  File "/home/anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/imperative_grad.py", line 64, in imperative_grad
    output_gradients)
  File "/home/anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 858, in grad_fun
    return [dresult._copy(device_name=self_device)]
AttributeError: 'IndexedSlices' object has no attribute '_copy'
```

2019-04-19 19:44 UTC, pminervini commented
@alextp this should do the trick - what do you think?

2019-04-19 22:05 UTC, alextp submitted a review, later dismissed

2019-04-19 22:37 UTC, alextp submitted a review, later dismissed

2019-04-20 09:47 UTC, pminervini commented
@alextp link to the test: https://github.com/pminervini/tensorflow/blob/master/tensorflow/python/framework/ops_test.py#L161

Is there a way to enforce this to run on GPU?

2019-04-22 15:35 UTC, alextp commented
Use the  `@test_util.run_gpu_only` decorator

2019-04-22 15:48 UTC, alextp commented on tensorflow/python/framework/ops.py
> +        return [dresult._copy(device_name=self_device)] if hasattr(dresult, '_copy') else [dresult]
The linter will fail on this line of code.

Also, you should probably put the whole thing inside the [], like `return [dresult._copy() if hasattr(dresult, '_copy') else dresult]` which will make it easier to split into lines to fit in 80 columns.

2019-04-22 16:21 UTC, pminervini commented
@alextp done!

2019-04-22 16:27 UTC, alextp submitted a review, later dismissed

2019-04-22 17:10 UTC, pminervini commented
@alextp there was one line exceeding 80 chars in `ops_test.py`, it should be fine now

2019-04-22 17:13 UTC, alextp approved these changes

2019-04-22 17:31 UTC, pminervini commented
@alextp mmm where is the problem?

2019-04-22 17:55 UTC, alextp commented
Nothing wrong, the build is just currently broken.

2019-04-22 20:31 UTC, merged