Initial implementation of general eigenvalue decomposition
tensorflow/tensorflow pull request #28340
Opened 2019-05-02 16:57 UTC by Randl

2019-05-02 16:59 UTC, mrry commented
I'm going to punt this one to @rmlarsen, since linear algebra is more his domain!

2019-05-02 17:00 UTC, mrry commented on tensorflow/compiler/tests/BUILD
> +    srcs = ["eig_op_test.py"],
Does this file exist? I can't see it in the PR or in the repository....

2019-06-18 21:45 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-06-18 21:58 UTC, Randl commented
I've not got any response from you or anyone else, neither any review expect note about non-existing file, which was fixed. Are there any actions expected from me at this point?

2019-06-18 22:09 UTC, Randl commented
@rthadur Also I have no rights to reopen the PR

2019-06-19 17:51 UTC, rthadur commented
reopened , can you please resolve conflicts

2019-06-21 06:57 UTC, Randl commented
@rthadur done, rebased on master

2019-07-17 13:07 UTC, Randl commented
ping

2019-07-17 14:58 UTC, mrry commented
I’m sorry you’ve experienced a delay on this pull request. Unfortunately, this code is outside my domain of expertise. As I mentioned on May 2nd, @rmlarsen or someone else more familiar with Eigen would be a more appropriate reviewer.

2019-08-20 13:13 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-10-05 11:51 UTC, Randl commented
ping @rmlarsen 
Can you please review or propose someone else who can review?

2019-10-07 17:49 UTC, rthadur commented
This PR will be reviewed soon , thanks for your patience.

2019-10-08 17:09 UTC, rmlarsen commented
@Randl my apologies for the long delay. I will review this.

2019-10-09 18:06 UTC, rmlarsen requested changes
Overall very nice. Thank you for the contribution, and please accept my apologies for missing this PR.

2019-10-09 18:06 UTC, rmlarsen commented on tensorflow/python/ops/linalg_ops.py
> +
We need to mention that the eigenvalues and eigenvectors for a non-Hermitian matrix in general are complex, and the eigenvectors are not guaranteed to be linearly independent (The matrix may be "defective", i.e. have lower geometric than algebraic multiplicity). Furthermore, mention that what we compute here are the _right_ eigenvectors. Maybe add a reference to R. A. Horn & C. R. Johnson, "Matrix Analysis", Chapter 1.

2019-10-10 11:40 UTC, Randl commented on tensorflow/core/ops/linalg_ops.cc
> +    .Input("input: T")
@rmlarsen I've decomposed the op to input and output types, however it seems that underlying `LinearAlgebraOp` doesn't support different input and output types (at least, straightforward attempt to do so didn't work). The solution I thought about is to decompose `LinearAlgebraOp` similarly to what I did in `ComplexEigOp`, with default of same type for input and output. What do you think?

2019-10-10 16:52 UTC, rmlarsen requested changes

2019-10-10 16:52 UTC, rmlarsen commented on tensorflow/python/kernel_tests/self_adjoint_eig_op_test.py
> +"""Tests for tensorflow.ops.linalg_ops.self_adjoint_eig."""
Thanks for the cleanup!

2019-10-10 16:52 UTC, rmlarsen commented on tensorflow/core/kernels/eig_op_complex64.cc
> +REGISTER_LINALG_OP("Eig", (ComplexEigOp<complex64, complex64>),
Now that this supports real type as well, should we simply call the kernel "EigOp" for consistency? EigenDecompositionOp would perhaps be less idiomatic, but more informative. I'm fine with either.

2019-10-10 18:35 UTC, rmlarsen submitted a review, later dismissed
Thank you for the nice contribution!

2019-10-10 21:48 UTC, rthadur commented
@Randl can you please check the build failures ?

2019-10-10 23:02 UTC, Randl commented
@rthadur fixed lint stuff, should work now

2019-10-10 23:43 UTC, Randl commented
Sorry, I messed up a bit with version control. The current version worked locally for Ubuntu 18.04.

2019-10-11 18:19 UTC, Randl commented
@rmlarsen can you rerun CI again please

2019-10-11 19:05 UTC, Randl commented
@rmlarsen Can you do it once again please? Sorry for bothering you, I'm new to the whole API thing. Hopefully, it should be the last one.

2019-10-11 20:06 UTC, rmlarsen commented
@Randl no problem. It is rather tedious to add a new op, sorry.

2019-10-12 17:36 UTC, Randl commented
@rthadur @rmlarsen Is it ok now? Seems like windows fails are due to upstream. Is anything else required from my side?

2019-10-14 22:26 UTC, rmlarsen approved these changes

2019-10-14 22:27 UTC, rmlarsen commented
@Randl thank you. We'll take it from here.

2019-10-15 03:48 UTC, merged