[LITE]Elementwise ops refactor
tensorflow/tensorflow pull request #28476
Opened 2019-05-07 13:55 UTC by siju-samuel

2019-05-09 02:44 UTC, siju-samuel commented
@jdduke @achowdhery could you please help to review this. TIA

2019-05-09 15:32 UTC, jdduke requested changes

2019-05-09 15:32 UTC, jdduke commented on tensorflow/lite/kernels/elementwise.cc
> +  return kTfLiteOk;
No need for return kTfLiteOk

2019-05-09 15:32 UTC, jdduke commented on tensorflow/lite/kernels/elementwise.cc
> +  return kTfLiteOk;
No need for `reutnr kTfLiteOk`.

2019-05-09 15:32 UTC, jdduke commented on tensorflow/lite/kernels/elementwise.cc
> +  return kTfLiteOk;
Alternatively, use a switch, with no default case, which will ensure you always handle the path. Same below.

2019-05-14 11:26 UTC, siju-samuel commented
@jdduke Thanks a lot for the review, i have updated the code based on your comments. Could you please have a look again. TIA

2019-05-17 20:19 UTC, jdduke commented on tensorflow/lite/kernels/elementwise.cc
> +  return EvalNumeric(context, node, [](float f) { return RoundToNearest(f); });
Why the lambda? Just pass RoundtoNearest directly to EvalNumeric.

2019-05-17 20:21 UTC, jdduke submitted a review, later dismissed

2019-05-17 21:09 UTC, rthadur commented
@siju-samuel can you please resolve conflicts.

2019-07-02 19:48 UTC, girving commented
I won't be able to do this review.

2019-07-08 16:49 UTC, siju-samuel commented
@jdduke Gentle ping to review and approve once again. I rebased it due to the recent changes. Thanks in advance.

2019-07-12 18:04 UTC, jdduke approved these changes

2019-07-15 16:41 UTC, jdduke requested changes

2019-07-15 16:41 UTC, jdduke commented on tensorflow/lite/kernels/internal/reference/reference_ops.h
> -inline void Floor(const RuntimeShape& input_shape, const float* input_data,
For internal reasons, we need to keep the Floor/Ceil/Round implementations in this file. Can you please update accordingly? Thanks.

2019-07-19 16:50 UTC, jdduke submitted a review, later dismissed

2019-07-22 02:46 UTC, rthadur commented
@siju-samuel thank you , can you please check this build failures : 
https://source.cloud.google.com/results/invocations/da218a31-ea37-4298-b520-309de102e5f0/log
https://source.cloud.google.com/results/invocations/9a225bff-fc03-4596-b2a4-3f0ee7a68881/log

2019-07-23 05:39 UTC, siju-samuel commented
@rthadur Sorry for the delay,  I could find that target `//tensorflow/python/keras/distribute:keras_dnn_correctness_test`
 is failing with and without my changes. My modifications are in lite folder only. 

Another build error showing is, which may not b the actual reason, which is also not in scope of my change
`
ERROR: /tmpfs/src/github/tensorflow/tensorflow/tools/api/golden/BUILD:3:1: invalid label '//tensorflow:tensorflow_py:__subpackages__' in element 0 of 'package' argument: invalid target name 'tensorflow_py:__subpackages__': target names may not contain ':'
ERROR: package contains errors: tensorflow/tools/api/golden
Loading: 412 packages loaded
    currently loading: tensorflow/cc/saved_model/python ... (54 packages)
Loading: 462 packages loaded
    currently loading: tensorflow/core/kernels ... (4 packages)
ERROR: error loading package 'tensorflow/tools/api/golden': Package 'tensorflow/tools/api/golden' contains errors
`

Could you please help me find the reason. Thanks in advance.

2019-07-23 17:21 UTC, rthadur commented
I will pull this in and try to merge

2019-08-13 09:28 UTC, siju-samuel commented
Rebased due to conflict.

2019-08-20 13:12 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-11-26 10:37 UTC, gbaned commented
@siju-samuel  Could you please resolve the conflicts? Thanks!

2019-12-11 12:29 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-01-09 12:34 UTC, closed without merging

2020-01-09 12:35 UTC, tensorflowbutler commented
It has been 43 days that this pull-request has stalled. Please create a new pull-request with the requested changes.