Creating Cuda forwarding alias macros
tensorflow/tensorflow pull request #28564
Opened 2019-05-09 19:38 UTC by jerryyin

This PR is a follow-up to the original PR #28343. The reviewer requested to break down the original large PR to a series of smaller ones. According to the plan [here](https://github.com/tensorflow/tensorflow/pull/28343#issuecomment-491025711), this PR is the first one in the whole series.

@chsigg @whchung

2019-05-09 21:17 UTC, whchung requested changes
need to use macro to guard the header to prevent multiple inclusion

2019-05-09 22:17 UTC, jerryyin commented
> need to use macro to guard the header to prevent multiple inclusion

Thanks for reminding. Code updated to add include guard, changes not yet applied to website ui.

2019-05-09 23:39 UTC, whchung approved these changes

2019-05-10 09:25 UTC, merged

2019-05-10 18:26 UTC, chsigg reviewed
Approved.