Update array_ops
tensorflow/tensorflow pull request #28615
Opened 2019-05-10 22:43 UTC by jvishnuvardhan

Updated tf.identity with an example.

2019-05-10 22:45 UTC, alextp requested changes

2019-05-10 22:45 UTC, alextp commented on tensorflow/python/ops/array_ops.py
> +  with tf.device('cpu:0'):
You don't need the device block

2019-05-13 19:18 UTC, jvishnuvardhan commented on tensorflow/python/ops/array_ops.py
> +  with tf.device('cpu:0'):
Updated. Thanks Alex.

2019-05-13 19:47 UTC, alextp approved these changes

2019-05-15 18:25 UTC, jvishnuvardhan commented
@yifeif Can you please merge this to r2.0. Thanks!

2019-06-05 19:01 UTC, rthadur commented
Closing this PR as this not against `master`, please open a new PR against `master` 
CC @mihaimaruseac

2019-06-05 19:01 UTC, closed without merging