Fix trt6 version parsing
tensorflow/tensorflow pull request #28633
Opened 2019-05-12 03:45 UTC by jhalakpatel

1. find_cuda_config.py - Fix version parsing for TRT 6.  If required version >= 6, parse version information from NvInferVersion.h, else parse version information from NvInfer.h.

2019-05-14 22:56 UTC, jhalakpatel commented
@annarev Do you have any comments or suggestions on the review?

2019-05-15 21:16 UTC, aaroey requested changes

2019-05-15 21:16 UTC, aaroey commented on third_party/tensorrt/tensorrt_configure.bzl
> +    implementation=_tensorrt_configure_impl,
Please revert these changes as well.

2019-05-15 21:16 UTC, aaroey commented on third_party/tensorrt/tensorrt_configure.bzl
> +  actual = [int(v) for v in actual_version.split(".")]
Please revert all indention changes in this file. .bzl files requires 4-space indention.

2019-05-15 23:36 UTC, jhalakpatel commented
@aaroey Addressed review comments.

2019-05-15 23:46 UTC, aaroey approved these changes

2019-05-17 13:16 UTC, merged