[LITE] Reduce all op support
tensorflow/tensorflow pull request #28699
Opened 2019-05-14 11:13 UTC by siju-samuel

2019-05-16 16:55 UTC, siju-samuel commented
@talumbau Could you please have a look at this PR. TIA

2019-05-29 11:55 UTC, gbaned commented
@talumbau Can you please review this PR? Thanks!

2019-06-05 08:05 UTC, gbaned commented
@siju-samuel Can you please resolve conflicts? Thanks!

2019-06-25 11:43 UTC, gbaned commented
@siju-samuel gentle ping to resolve conflicts? Thanks!

2019-06-27 21:27 UTC, talumbau requested changes
Overall looks good. Just needs some additional tests

2019-06-27 21:27 UTC, talumbau commented on tensorflow/lite/kernels/reduce_test.cc
> +TEST(ConstAllOpTestFalse, NotKeepDims) {
This test is fairly duplicative of the next test. Can you rename to ConstAllOpsTestMixed and use this data:

```
std::vector<bool> data = {true, true, false, false, true, true,
                            true, true,  false, false, true, true};
```

with an axis of `[0,2]`. The result will be `true, false, true`. (the extraneous `-3, -3` axis dimensions are specified in the next test so we are still testing that functionality.

2019-06-27 21:27 UTC, talumbau commented on tensorflow/lite/kernels/reduce_test.cc
> +TEST(ConstAllOpTestFalse, NotKeepDims) {
Also please add another version of the test described in the above comment with `keep_dims=true`. Thanks! Nice PR!

2019-07-02 03:06 UTC, siju-samuel commented
@talumbau I have updated the testcase based on your review comment. please help to review again.

2019-07-08 16:02 UTC, talumbau requested changes
Thanks for adding the tests! This looks good except for the one typo I noted. I can approve as soon as that is resolved. Thanks!

2019-07-08 16:02 UTC, talumbau commented on tensorflow/lite/schema/schema_generated.h
> +    BuiltinOperator_REDUCE_ANY
Should be `BuiltinOperator_REDUCE_ALL` here.

2019-07-08 16:46 UTC, siju-samuel commented
@talumbau Thanks a lot for review and pointing out the bug. I have updated the code.

2019-07-08 19:45 UTC, talumbau approved these changes

2019-07-11 03:04 UTC, siju-samuel commented
@gbaned Could u please help to merge this PR before new conflicts comes. TIA

2019-07-12 17:36 UTC, jdduke commented
Hi @siju-samuel, can you link to the models which require this operator? Thanks. The bar for adding new builtin ops has been raised, as we want to make the builtin op set a clear reference for the most important operators required for mobile execution.

2019-07-17 10:47 UTC, gbaned commented
@siju-samuel Did you get a chance to look on jdduke's  comments? Please let us know on the update. Thanks!

2019-07-17 11:36 UTC, siju-samuel commented
For inference purpose, currently I'm not using any model which have reduce-all op.

2019-07-25 09:14 UTC, gbaned commented
@siju-samuel Could you please resolve the conflicts? Thanks!

2019-08-09 12:37 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-08-13 23:26 UTC, rthadur commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-08-13 23:26 UTC, closed without merging