[XLA] rename xla compile mark from _XlaCompile to XlaCompile
tensorflow/tensorflow pull request #28719
Opened 2019-05-15 00:10 UTC by LogX2

code in mark_for_compilation_pass.cc shows that we can force an op to be compiled by xla by adding a mark "kXlaCompileAttr" to the op in its op.cc. However,  tf framework does not support a node attr name with the beginning of "_" such as "_XlaCompile", which makes the design in mark_for_compilation.cc  not work. 
i have tested this solution in nccl_ops.cc and it worked.

2019-05-15 03:22 UTC, sanjoy requested changes
We have underscores on these attributes by design -- we don't want to expose these as part of our public APIs (at least not without thinking carefully about it :) ).

Can you give us a somewhat higher level picture of what you're trying to do?  When you said this worked for nccl_ops.cc what exactly did you do?

2019-05-15 04:07 UTC, LogX2 commented
i'm trying to add a nccl_ops(NcclAllReduce, NcclBroadCast ... ) support for xla. One method is taking advantage of the code below (mark_for_compilation_pass.cc +1115):
`    if (GetNodeAttr(n->attrs(), kXlaCompileAttr, &compile_attr).ok()) {
      marked_for_compilation = compile_attr;
    } else if (options.flib_def->GetAttr(*n, kXlaCompileAttr, &compile_attr)
                   .ok()) {
      marked_for_compilation = compile_attr;
    }`

it seems that an op can be added to xla engine by adding an attribute named kXlaCompileAttr. but when i tried to do this , this problem occurred and then i fixed according to my understanding.

2019-05-15 19:54 UTC, sanjoy commented
To add support for `NcclAllReduce`, `NcclBroadCast` etc. you need to add `XlaOpKernel`s for these in `tf2xla/kernels`.  Once you you have registered kernels for these ops, mark for compilation should pick these up automatically.

2019-05-16 02:33 UTC, LogX2 commented
but actually, MarkForCompilePass does not add a registered xla kernel unconditionally. there are several code blocks deciding  whether to pick up a specific registered xla kernel and put it into the final graph. in my case, MarkForCompilationPass  can find  the new added nccl xla kernel, but will not mark this op as this op does not satisfy the following condition:
```
    if (effective_cluster_sizes[cluster] >= min_cluster_size ||
        (effective_cluster_sizes[cluster] > 0 && marked_for_compilation)) {
      string& name = cluster_names[cluster];
```
so i want to make the variable "marked_for_compilation" be true to satisfy this condition.  one way do this is add a kXlaCompleAttr in this op:
```
    if (GetNodeAttr(n->attrs(), kXlaCompileAttr, &compile_attr).ok()) {
      marked_for_compilation = compile_attr;
    } else if (options.flib_def->GetAttr(*n, kXlaCompileAttr, &compile_attr)
                   .ok()) {
      marked_for_compilation = compile_attr;
    }
```
but when i tried to add this attr,  i found it impossible to add it manually without changed the existed xla framework. so i push this PR. 

if we cannot add a  kXlaCompileAttr like this,  what is the correct way to satisfy this condition ?  Is there a previous optimizer adding this attr automatically?

2019-05-16 19:26 UTC, sanjoy commented
This logic:

```
    if (effective_cluster_sizes[cluster] >= min_cluster_size ||
        (effective_cluster_sizes[cluster] > 0 && marked_for_compilation)) {
      string& name = cluster_names[cluster];
```

is a profitability heuristic.  There are two ways to override this for testing purposes:

 - Preferred:  use `xla.compile` to force the cluster you're trying to compile to get compiled.
 - Less preferred: assign the nodes you want to be compiled to `XLA_GPU` or `XLA_CPU` devices, which will force them to get compiled.

If you're in a situation where you think the heuristic is wrong for profitability reasons (e.g. you have a case where a cluster containing `NcclAllReduce` should be compiled even if `effective_cluster_sizes[cluster] < min_cluster_size` since that results in better performance) then we should adjust the heuristic directly instead of hacking around it via the `_XlaCompile` attribute.

2019-05-16 19:26 UTC, closed without merging