[ROCm] Adding ROCm support for tile ops
tensorflow/tensorflow pull request #28873
Opened 2019-05-20 18:27 UTC by deven-amd

This PR adds ROCm support for tile ops

The changes in this PR are trivial, please review and merge...thanks.

--------------------------

@tatianashp , @whchung

2019-05-20 18:33 UTC, whchung approved these changes

2019-05-21 05:48 UTC, chsigg requested changes
Minor nit. I will fix it during import.

2019-05-21 05:48 UTC, chsigg commented on tensorflow/core/kernels/tile_ops_gpu_impl.h
> +#error "This header must be included inside with Cuda or ROCm defined"
CUDA

2019-05-21 14:01 UTC, rthadur commented
@chsigg can you please approve .thank you

2019-05-23 10:56 UTC, merged