test streaming accuracy python implementation
tensorflow/tensorflow pull request #28985
Opened 2019-05-24 06:54 UTC by zhizunbao-y

2019-05-24 06:59 UTC, zhizunbao-y commented
I signed it!

2019-05-24 18:13 UTC, tafsiri commented
@gbaned did you mean to request a review from someone else? I don't generally work on the python tf implementation.

2019-05-27 11:02 UTC, chsigg commented
@gbaned, I would like to skip reviewing this CL. I'm not familiar with this code.

2019-05-30 21:07 UTC, jdduke commented
Neither am I a good reviewer for this CL.

2019-08-01 11:26 UTC, gbaned commented
@yifeif Can you please review this PR ?

2019-08-20 13:11 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-08-20 18:07 UTC, frankchn commented
@zhizunbao-y 

Thanks for the PR! In addition to my comments in the doc, can you also do the following:

1. Add your script to the BUILD file so that folks can run this as part of the bazel build environment
2. Add instructions to your main file (test_stream_accuracy.py) detailing how to run this

2019-08-20 18:07 UTC, frankchn requested changes

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/recognize_commands.py
> +        # If there are to few results, assume the result will be unreliable and bail.
typo: `too few`

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/recognize_commands.py
> +class RecognizeResult:
Here, and other places: Inherit classes from `object`, i.e. `class RecognizeResult(object):`

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/test_streaming_accuracy.py
> +
Remove extra line

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/test_streaming_accuracy.py
> +
Remove extra line

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/test_streaming_accuracy.py
> +
Remove extra line

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/test_streaming_accuracy.py
> +    wav_file = "/home/yuan/datasets/speech_dataset/generated_wav_and_label/streaming_test.wav"
Can you take this in as a parameter (using absl flags perhaps). Same with everything else

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/test_streaming_accuracy.py
> +    #  ops = tf.get_default_graph().get_operations()
Remove debugging

2019-08-20 18:07 UTC, frankchn commented on tensorflow/examples/speech_commands/test_streaming_accuracy.py
> +    average_window_duration_ms = 500
You might also want this as parameters.

2019-08-26 10:06 UTC, gbaned commented
@zhizunbao-y Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

2019-08-26 10:47 UTC, zhizunbao-y commented
> @zhizunbao-y Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!
Okay, thank you for informing me. I will revise and update it as soon as possible.

2019-09-01 05:50 UTC, zhizunbao-y commented
I have done the refinement followed by @frankchn .

2019-09-03 07:59 UTC, frankchn submitted a review, later dismissed
LGTM, except 2 minor nits. Thanks for doing this :)

2019-09-03 07:59 UTC, frankchn commented on tensorflow/examples/speech_commands/accuracy_utils.py
> +                                                   false_positive_percentage))
Add trailing new line to the file.

2019-09-03 07:59 UTC, frankchn commented on tensorflow/examples/speech_commands/test_streaming_accuracy.py
> +
Extra line still there

2019-09-05 09:22 UTC, gbaned commented
@zhizunbao-y Could you please check reviewer comments? Thanks!

2019-09-05 17:01 UTC, frankchn approved these changes

2019-09-06 04:20 UTC, gbaned commented
@zhizunbao-y Could you please address Ubuntu Sanity errors? Thanks!

2019-09-09 18:23 UTC, frankchn submitted a review, later dismissed

2019-09-10 05:21 UTC, gbaned commented
@zhizunbao-y Still, Ubuntu Sanity checks failing. Could you please check again?  Thanks!

2019-09-15 09:54 UTC, zhizunbao-y commented
@gbaned I don't know which part of the code made the Ubuntu sanity check failing. Please give me some guidance.

2019-09-16 03:38 UTC, zhizunbao-y commented
I am sorry. It might be an input type error that caused this check error. I have fixed it. Please run check again. Thanks!

2019-09-16 05:40 UTC, frankchn commented
Here are the errors from Ubuntu Sanity:

From pylint:
```
tensorflow/examples/speech_commands/recognize_commands.py:107: [C0330(bad-continuation), ] Wrong continued indentation (remove 1 space).
tensorflow/examples/speech_commands/recognize_commands.py:128: [C0330(bad-continuation), ] Wrong hanging indentation (remove 35 spaces).
tensorflow/examples/speech_commands/recognize_commands.py:129: [C0330(bad-continuation), ] Wrong hanging indentation (remove 28 spaces).
tensorflow/examples/speech_commands/recognize_commands.py:135: [C0330(bad-continuation), ] Wrong continued indentation (add 10 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:136: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:138: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:140: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:148: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:149: [C0330(bad-continuation), ] Wrong continued indentation (add 9 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:154: [C0330(bad-continuation), ] Wrong continued indentation (remove 1 space).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:169: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:172: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:173: [C0330(bad-continuation), ] Wrong continued indentation (remove 5 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:174: [C0330(bad-continuation), ] Wrong continued indentation (remove 5 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:175: [C0330(bad-continuation), ] Wrong continued indentation (remove 5 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:184: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:185: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:186: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:187: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:189: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:190: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:191: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:192: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:194: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:195: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:196: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:197: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:199: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:200: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:201: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:202: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:204: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:205: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:206: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:207: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:207: [C0326(bad-whitespace), ] Exactly one space required after comma
tensorflow/examples/speech_commands/test_streaming_accuracy.py:208: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:210: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:211: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:212: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:213: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:215: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:216: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:217: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:218: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:220: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:221: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:222: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:223: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:225: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:226: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:227: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:228: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:230: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:231: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:232: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:233: [C0330(bad-continuation), ] Wrong hanging indentation (add 2 spaces).
tensorflow/examples/speech_commands/test_streaming_accuracy.py:23 [...]

2019-09-18 01:07 UTC, zhizunbao-y commented
I used the pylintrc in tensorflow/tensorflow/tools/ci_build/ to check my code.
This time might be ok.

2019-09-24 17:19 UTC, frankchn approved these changes

2019-11-11 06:59 UTC, merged