Adding doc for 2.0 acosh
tensorflow/tensorflow pull request #29016
Opened 2019-05-24 23:33 UTC by SSaishruthi

Added:
- Description 
- Input range
- Example

In order to reflect in doc, should I change in any file?

Thanks.

2019-05-25 00:17 UTC, SSaishruthi commented
@dynamicwebpaige This address the issue #25802.
Working on other components

2019-05-31 23:37 UTC, martinwicke requested changes

2019-05-31 23:37 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Acosh.pbtxt
> +tensor `x` is [-2, -0.5, 1, 1.2, 200, 10000]
Please write examples as code, in this case: 

x = [-2, -0.5, 1, 1.2, 200, 10000]

2019-05-31 23:37 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Acosh.pbtxt
> +END
you need to end the code block (```)

2019-05-31 23:37 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Acosh.pbtxt
> +Input range is [1, infinity). It returns `nan` if the input lies outside the range.
I'd say inf instead of infinity

Please put backticks around `[1, inf)` so it renders as code.

2019-05-31 23:37 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Acosh.pbtxt
> +tensor `x` is [-2, -0.5, 1, 1.2, 200, 10000]
might be good to add inf to x, so readers know what happens.

2019-06-01 00:00 UTC, SSaishruthi commented
Thanks, @martinwicke for the review
I have added `inf` as one of the inputs. Is it ok to give as `float("inf")` or I need to use `math.inf`?

2019-06-01 00:07 UTC, martinwicke requested changes

2019-06-01 00:07 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Acosh.pbtxt
> +Input range is `[1, inf)`. It returns `nan` if the input lies outside the range.
If the output below is correct, then the input range is `[1, inf]`, since inf -> inf, not inf -> nan.

2019-06-01 00:07 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Acosh.pbtxt
>  ```python
I believe you need an empty line before the code block for it to render correctly.

2019-06-01 00:08 UTC, martinwicke commented
`float(inf)` is fine, I left some more comments. Please also apply the equivalent to your other PRs if they appear relevant.

2019-06-01 03:33 UTC, SSaishruthi commented
@martinwicke Completed changes. Please let me know if this looks good.

2019-06-01 03:51 UTC, martinwicke approved these changes

2019-06-06 17:57 UTC, merged