[T.F 2.0 Doc Changes] Adding details to math functions
tensorflow/tensorflow pull request #29018
Opened 2019-05-25 06:53 UTC by SSaishruthi

This PR is related with issue #25802

Added details to the following functions:

1. add_n
2. asinh
3. atanh

Thanks in advance.

2019-05-31 23:40 UTC, martinwicke requested changes

2019-05-31 23:40 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_AddN.pbtxt
> +  `x` is an input tensor with value [9, 7, 10]
Please write examples inside code blocks as code, in this case 

x = [9, 7, 10]

2019-05-31 23:40 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Asinh.pbtxt
> +  tf.math.asinh(x, name ='asinh') ==> [-1.4436355 -0.4812118  0.8813736  1.0159732  5.991471   9.903487 ]
I'd remove the name arg, it's just a distraction. There's a spurious space before `]`.

2019-05-31 23:40 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Asinh.pbtxt
> +  (-infinity, infinity).
I'd say inf instead of infinity.

please, backticks around `(-inf, inf)`

2019-05-31 23:40 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Atanh.pbtxt
> +  for every element in the tensor. Input range is (-1,1) and output range is
backticks around range

2019-05-31 23:40 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Atanh.pbtxt
> +  (-infinity, infinity). If input is -1, output will be -infinity and if the
infinity -> inf, backticks around range, -1, -inf

2019-05-31 23:40 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Atanh.pbtxt
> +  tf.math.atanh(x, name ='atanh') ==> [-inf -0.54930615 inf  0. 0.54930615 nan]
remove name arg

2019-06-01 03:10 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Atanh.pbtxt
> +  tf.math.atanh(x) ==> [nan -inf -0.54930615 inf  0. 0.54930615 nan cnan]
cnan --> nan

2019-06-01 03:32 UTC, SSaishruthi commented
@martinwicke Completed changes. Please let me know if this looks good.

2019-06-01 04:03 UTC, SSaishruthi commented on tensorflow/core/api_def/base_api/api_def_Atanh.pbtxt
> +  tf.math.atanh(x) ==> [nan -inf -0.54930615 inf  0. 0.54930615 nan cnan]
Sorry about it. Updated

2019-06-01 04:53 UTC, martinwicke approved these changes

2019-06-05 13:16 UTC, gbaned commented
@SSaishruthi Can you please check build failures? Thanks!

2019-06-05 21:57 UTC, SSaishruthi commented
Hi @gbaned @martinwicke

I noticed the error in log files.
```
Execution platform: @org_tensorflow//third_party/toolchains:rbe_cuda10.0-cudnn7-ubuntu14.04
2019-06-01 05:00:14.254608: F tensorflow/python/framework/python_op_gen_main.cc:123] Non-OK-status: api_def_map.LoadFileList(env, api_files) status: Invalid argument: Error parsing ApiDef file tensorflow/core/api_def/base_api/api_def_AddN.pbtxt: 9(3): Expected identifier, got: 
```

Can you please help me with this? I have similar issues with my other PRs

2019-06-06 00:38 UTC, martinwicke requested changes

2019-06-06 00:38 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_AddN.pbtxt
> +  ```
This has to go before the line saying `END`.

2019-06-06 00:39 UTC, martinwicke commented
Left a comment. May not be the only issue.

2019-06-17 20:58 UTC, SSaishruthi commented
@martinwicke 
Updated code as per the comment in other PR. Can you please trigger the test to see if that works?

2019-06-18 19:33 UTC, martinwicke submitted a review, later dismissed

2019-06-25 21:32 UTC, SSaishruthi commented
@martinwicke 
Made some updates. Can you please trigger the test?

2019-06-25 22:10 UTC, martinwicke approved these changes

2019-06-27 01:41 UTC, merged