[Intel MKL] Update TF to fuse Conv2d+Relu6/Elu
tensorflow/tensorflow pull request #29045
Opened 2019-05-27 05:08 UTC by guizili0

We first disable Conv2d+Relu6/Elu in MKL build as lack of the backend support, now add the support in backend and remove the limitation in Conv2d fusion.

2019-05-28 22:46 UTC, penpornk requested changes
Thank you for your PR! I have minor formatting comments.

2019-05-28 22:46 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_ops_test.cc
> +  const int filter_size = 1;
Per our [Style Guide](https://google.github.io/styleguide/cppguide.html#Constant_Names) on naming constants,
```suggestion
  const int kFilterSize = 1;
```
Please change other places as well.

2019-05-31 06:22 UTC, guizili0 commented
@penpornk thanks for the comments, I have update my code based on your comments. Please help to check, thanks.

2019-06-01 05:23 UTC, penpornk approved these changes
Thank you for the prompt fixes!

2019-06-01 05:23 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_ops_test.cc
> +      next_op = ops::Relu6(root.WithOpName(last_op), next_op);
Nice catch!

2019-06-06 06:27 UTC, merged