[T.F 2.0 API Docs] Examples for exp, expm1 and equal math functions
tensorflow/tensorflow pull request #29068
Opened 2019-05-28 06:33 UTC by SSaishruthi

Reference Issue: #25802

This PR adds examples to the following math functions.

1. equal
2. exp
2. expm1

Thanks in advance.

2019-05-28 15:44 UTC, martinwicke requested changes

2019-05-28 15:44 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Equal.pbtxt
> +y = tf.constant([2,4])
Please add space after comma

2019-05-28 15:44 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Equal.pbtxt
> +```python
I think you need a blank line here to make the renderer happy.

2019-05-28 15:44 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Exp.pbtxt
> +  This function computes exponential of every element in the input tensor.
*the* exponential

2019-05-28 15:44 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Exp.pbtxt
> +
Please put all equations in backticks to make them render as code. This is very hard to read without that sort of font-based highlighting.

The math in this example is wrong. The example text is confusing and misleading, it needs to be rewritten.

This is the correct trigonometric replacement:  e^(x+iy) = e^x * e^iy = e^x * (cos y + i sin y).

2019-05-28 15:44 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Expm1.pbtxt
> +  #Refer `exp` for explanation
"Please refer to `exp` for an explanation."

Do you intend to add this kind of note to all functions which operate on complex numbers? Almost all functions do. I'm not sure we have to teach all our users about complex numbers. If they use them, they likely know how they work. If they don't, there's not much these examples will do to help them.

If we do want to add a uniform not and explanation about complex numbers, the docstring for exp is probably not the best place for it. I'd prefer to link out to wikipedia and keep the explanations here to a minimum.

2019-05-28 17:41 UTC, SSaishruthi commented
Hi @martinwicke 
I have made changes to the branch. I thought of pointing users about handling complex numbers in exponential function under `expm1`. That is the reason for adding the below line.

```
Refer `exp` for an explanation.
```

I have removed it for now. If you feel it is ok to add, I can make changes to it and push again.

2019-06-01 04:04 UTC, SSaishruthi commented
@martinwicke Completed changes. Please let me know if this looks good.

2019-06-01 04:51 UTC, martinwicke commented on tensorflow/core/api_def/base_api/api_def_Expm1.pbtxt
>    summary: "Computes exponential of x - 1 element-wise."
Actually, can you change this summary? I think it is ambiguous at best. 

Maybe better: "Computes `exp(x)` - 1 element-wise."

2019-06-01 04:52 UTC, martinwicke commented
Looks good after one more.comment.

2019-06-01 05:11 UTC, SSaishruthi commented
> Looks good after one more.comment.

@martinwicke Updated. Thanks a lot

2019-06-01 06:07 UTC, martinwicke approved these changes

2019-06-04 00:58 UTC, merged