Updated linear activation function with arguments, returns and note.
tensorflow/tensorflow pull request #29080
Opened 2019-05-28 15:36 UTC by lufol

This is my first commit.
Please, feel free to comment on this small change.

2019-05-28 15:51 UTC, dynamicwebpaige requested changes

2019-05-28 15:51 UTC, dynamicwebpaige commented on tensorflow/python/keras/activations.py
> +  # Note
Please follow the same style convention for `Returns:`.

```
Note:
      Often used as the last layer of regression networks.
```

2019-05-28 16:16 UTC, lukasfolle reviewed
Should be ok now.

2019-05-28 16:17 UTC, lukasfolle reviewed
Should be correct now

2019-05-28 18:31 UTC, ymodak approved these changes

2019-06-19 19:57 UTC, lukasfolle reviewed
@dynamicwebpaige Fixed in 613a70f!

2019-06-19 20:32 UTC, ymodak approved these changes

2019-06-19 22:01 UTC, merged