Added missing documentation sections to tf.image.convert_image_dtype
tensorflow/tensorflow pull request #29451
Opened 2019-06-05 19:45 UTC by KabirKwatra

Added returns and raises section to make_saveable_from_iterator function #29406

@rthadur 
Pull request is now against master.
Recommitted for easysier merging into master.

2019-06-05 21:57 UTC, alextp submitted a review, later dismissed

2019-06-05 22:48 UTC, jsimsa requested changes
Remove trailing white space from this CL and update the name of this PR to reflect the change.

2019-06-05 22:49 UTC, jsimsa commented on tensorflow/python/data/experimental/ops/iterator_ops.py
> +    A SaveableObject for saving/restore iterator state using Saver.
s/restore/restoring

2019-06-05 22:49 UTC, jsimsa commented on tensorflow/python/data/experimental/ops/iterator_ops.py
> +    ValueError: If iterators does not support checkpointing.
s/iterators/iterator

2019-06-06 00:56 UTC, KabirKwatra commented
requested changes were made.

2019-06-06 04:15 UTC, jsimsa requested changes
@KabirKwatra thank you for the update. However, the PR description still incorrectly references `tf.image.convert_image_dtype`. Please update it to reference the method for which documentation is updated.

2019-06-09 22:54 UTC, KabirKwatra commented
@jsimsa Sorry about the title, It has been corrected.

2019-06-10 15:50 UTC, jsimsa approved these changes

2019-06-13 17:25 UTC, merged