LICENSE: Restore original Apache license
tensorflow/tensorflow pull request #29523
Opened 2019-06-07 07:44 UTC by I-Hong

* Remove copyright notice from first line. Apache's instruction: 

> Each original source document (code and documentation, but **excluding the LICENSE** and NOTICE files) SHOULD include a short license header at the top. 

Ref: http://www.apache.org/dev/apply-license.html#new

* The Apache 2.0 license includes an Appendix about how to apply the license terms to files. We should not modify the license file. 
Reference: https://github.com/kubernetes/kubernetes/commit/d30db1f9a915aa95402e1190461469a1889d92be

2019-06-12 19:08 UTC, ewilderj commented
Thanks, I'm going to check this PR with our open source counsel.

2019-06-12 19:11 UTC, ewilderj commented
This is the same situation as encountered in https://github.com/tensorflow/tensorflow/pull/26554 -- this change doesn't make any difference, so in the name of caution about changing the long-standing license doc, I'm closing this PR.

2019-06-13 03:55 UTC, martinwicke reviewed
You are correct about the appendix. 

But can you revert line 1? We checked with our lawyers, and that is actually correct.

2019-06-13 03:56 UTC, martinwicke requested changes
Please revert line 1

2019-06-13 06:35 UTC, I-Hong commented on LICENSE
> -Copyright 2019 The TensorFlow Authors.  All rights reserved.
Thanks, @martinwicke. Updated!

2019-06-13 06:35 UTC, I-Hong commented
Thanks, @martinwicke. Updated!

2019-06-13 14:21 UTC, martinwicke approved these changes
Thank you!

2019-06-19 19:31 UTC, merged