Explicitly disable XLA for AMP test
tensorflow/tensorflow pull request #29619
Opened 2019-06-11 00:12 UTC by bas-aarts

This test checks for certain graph nodes to verify AMP correctness,
but XLA changes the graph in ways that make these checks fail.

2019-06-11 05:07 UTC, gbaned commented
@bas-aarts Please sign CLA in order to proceed with next steps. Thank you!

2019-06-11 18:27 UTC, bas-aarts commented
I signed the NVidia CLA!

2019-06-12 17:32 UTC, reedwm requested changes

2019-06-12 17:32 UTC, reedwm commented on tensorflow/python/grappler/auto_mixed_precision_test.py
> +    self._original_tf_xla_flags = os.getenv(self.TF_XLA_FLAGS)
I think you can use the `test_util.disable_xla` annotation to disable it. [See here for an example.](https://github.com/tensorflow/tensorflow/blob/754ac36f54db34d303a60eb08d34199a7945e576/tensorflow/python/kernel_tests/array_ops_test.py#L1128).

For the description, you could put something like "This test does not pass with XLA".

2019-06-19 19:04 UTC, reedwm approved these changes

2019-06-20 07:57 UTC, merged