Fix: EagerFunc tensor conversion error
tensorflow/tensorflow pull request #29728
Opened 2019-06-13 04:51 UTC by kami93

This is the fix to the issue [https://github.com/tensorflow/tensorflow/issues/29727](https://github.com/tensorflow/tensorflow/issues/29727). When the desired dtype is integer, let input argument be 0 (strict integer) instead of 0.0.

2019-06-13 17:01 UTC, alextp approved these changes

2019-06-13 17:01 UTC, alextp requested changes
Can I get a test which fails before and passes after this change?

2019-06-19 10:37 UTC, gbaned commented
@kami93 Could you please check reviewer comments and keep us posted. Thanks!

2019-06-20 00:38 UTC, kami93 commented
@alextp 
The issue is regarding calculating gradients of operations that involves pipeline through the "tfe.py_func" as described in [https://github.com/tensorflow/tensorflow/issues/29727](https://github.com/tensorflow/tensorflow/issues/29727). When calculating such gradients, the member function "_convert" of the EagerFunc class defined in "tensorflow/python/ops/script_ops.py" tries to make zero constants with the same dtypes as the tensors given as input arguments to the tfe.py_func pipeline.

```
class EagerFunc(object):
  """A wrapper for a function owned by an EagerPyFunc."""

  def __init__(self, func, Tout, is_grad_func):
    """Constructs an EagerFunc.
    Args:
      func: The function to wrap.
      Tout: A list of datatypes for the output; an empty list if the output is
        None.
      is_grad_func: Whether this EagerFunc is the gradient of another
        EagerPyFunc.
    """
    self._func = func
    self._out_dtypes = Tout
    self._is_grad_func = is_grad_func

    context.ensure_initialized()

  def _convert(self, value, dtype):
    """Converts `value` to a tensor of type `dtype`, with error checking.
    Args:
      value: The tensor to convert.
      dtype: The desired dtype.
    Returns:
      A tensor of type `dtype`, or a zeros tensor if value is None and
      this function is in fact a grdient function.
    Raises:
      RuntimeError: if `value` is a variable.
    """

    if isinstance(value, resource_variable_ops.ResourceVariable):
      raise RuntimeError(
          "Attempting to return a variable from an eagerly executed py_func. "
          "Only numeric data structures like Tensors or NumPy arrays should "
          "be returned; to return the value of a variable, make sure to obtain "
          "the Tensor backing it by calling `.read_value()` on the variable in "
          "question: %s" % value)
    if value is None and self._is_grad_func:
      # Gradient functions may legitimately return a list that contains
      # both Tensors and Python Nones. Unfortuantely this breaks the
      # OpKernel, so for now we replace None objects with zeros, which is
      # mathematically correct but will prevent short-circuiting gradient
      # computations.
      #
      # TODO(akshayka): Make it possible to return a list of both Tensors and
      # Nones from an EagerPyFunc.
      return constant_op.constant(0.0, dtype=dtype)
    return ops.convert_to_tensor(value, dtype=dtype)
```
Currently, the "_convert" function returns "constant_op.constant(0.0, dtype=dtype)" as shown in the above code block. With this code, there is no problem when the input tensors' dtypes happen to be all "float" types, however, if some of the dtypes are "int" types, TypeError is raised because 0.0 is float.

My commit is just a simple fix to this which replaces 0 by 0.0 if the dtype is integer.

2019-06-20 14:31 UTC, alextp commented
@kami93 this makes sense. I just want a unit test because my experience has been that in TF any bugfix without a test protecting it will regress into a bug as we make many changes to the codebase. A simple test will do.

2019-06-27 08:15 UTC, gbaned commented
@kami93 Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

2019-07-12 12:33 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-07-16 12:08 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-07-16 12:08 UTC, closed without merging