Follow up the while signature change.
tensorflow/tensorflow pull request #29803
Opened 2019-06-14 17:50 UTC by trentlo

- Assert that the input and output resources are in the same order to make the
   expected signature of the xla computation more straightforward.

2019-06-14 17:53 UTC, trentlo commented
@sanjoy, this is the (minor) cleanup I promised you a while ago. Please help to take a look.

@jlebar @hawkinsp

2019-06-14 18:06 UTC, sanjoy approved these changes
lgtm

2019-06-26 03:40 UTC, sanjoy requested changes
Hi Trent,

Internally this fails tensorflow/compiler/tests:eager_test_cpu (not sure how it passed presubmit in github, doing an OSS build now).

The problem is that TF eager will sometimes compile regular function calls with XLA, and in such cases the resource outputs may not all be grouped together in the end.  However `XlaComputationLaunchContext::PopulateOutputs` will do the right thing for them.

Do you mind moving this `TF_RET_CHECK` to happen only for while loops since that is the only case where it is guaranteed that this invariant will hold?

2019-06-26 05:02 UTC, trentlo commented
Understood. Let me see if I can place it in a better place.

2019-06-27 19:23 UTC, trentlo commented
Done. Please help to take a look.

Although I think it should not affect the change, I don't fully understand the purpose of the token inputs/outputs. How are they generated, stack access ops?

2019-06-27 20:27 UTC, sanjoy requested changes
Minor nits, otherwise looks great!

2019-06-27 20:27 UTC, sanjoy commented on tensorflow/compiler/tf2xla/kernels/while_op.cc
> +              "Expect input resources are grouped in the end of while body ",
Let's also use `i` in the error message.  If you think that's not useful then please change the loop to a range for loop.

2019-06-27 20:27 UTC, sanjoy commented on tensorflow/compiler/tf2xla/kernels/while_op.cc
> +Status VerifyBodyFunctionSignature(XlaOpKernelContext* ctx,
Why not `VerifyResourcesArgsGroupedAtEnd`

2019-06-27 20:29 UTC, sanjoy commented
> Done. Please help to take a look.
> 
> Although I think it should not affect the change, I don't fully understand the purpose of the token inputs/outputs. How are they generated, stack access ops?

There are some internal users for this, but I'm not sure if there are any external uses.

Roughly: `TOKEN` values let us sequence side effecting operations like `outfeed` and `infeed` in XLA, and we might need to thread these values through function calls, functional while loops etc.

2019-06-27 21:05 UTC, trentlo commented
Revised accordingly.

Thanks for the explanations on `token`.

2019-06-27 21:12 UTC, sanjoy approved these changes
lgtm

2019-07-01 18:27 UTC, rthadur commented
This is merged by the commit: `5205ef9` , so closing this PR

2019-07-01 18:27 UTC, closed without merging