Update TensorBoard callback in callbacks.py
tensorflow/tensorflow pull request #30027
Opened 2019-06-21 11:18 UTC by 8bitmp3

See #29958 : Suggested improvements:

* _Added a TensorBoard example:_

Material used and modified from [TensorBoard in Notebooks](https://www.tensorflow.org/tensorboard/r2/tensorboard_in_notebooks) and [Getting started with TensorBoard](https://www.tensorflow.org/tensorboard/r2/get_started).

Note the`%`-sign in front of the command line invocations (for Jupyter).

* _Replaced bullet points `*` with `-` to attempt to fix the way certain bullet points are displayed:_

Previously, they were displayed in one "sentence" as this Markdown `*` syntax wasn't "picked up": `This callback logs events for TensorBoard, including: * Metrics summary plots * Training graph visualization * Activation histograms * Sampled profiling` (For reference, see r1.14 doc [link](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard) and r2.0 doc [link](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/callbacks/TensorBoard)).

2019-07-08 18:26 UTC, 8bitmp3 commented
just checking in to see if anything else needs to be done @rchao @gbaned thanks!

2019-08-18 21:40 UTC, omalleyt12 requested changes
Thanks for the PR!

2019-08-18 21:40 UTC, omalleyt12 commented on tensorflow/python/keras/callbacks.py
> +  import datetime
Can you remove the datetime logic? Let's just show the minimum example for this callback

2019-08-20 10:16 UTC, gbaned commented
@8bitmp3 Could you please address the reviewer comments. Thanks!

2019-08-20 13:10 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-09-04 12:32 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-09-26 11:32 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-09-26 11:32 UTC, closed without merging