Correct Tensor order for dilation2D
tensorflow/tensorflow pull request #30277
Opened 2019-07-01 13:58 UTC by gabriel-vanzandycke

`gen_nn_ops.dilation2d` seems to be in `NHWC` while the parent function was asking for `NCHW`.
I corrected the doc and the check.

2019-07-01 14:02 UTC, gabriel-vanzandycke commented
I signed it...

2019-07-03 05:30 UTC, sjamesr commented
Thank you for the change, I think it's correct but let me follow up with more knowledgeable folks in the TF team before I approve it.

2019-07-03 09:28 UTC, martinwicke approved these changes
This change is correct. Bummer.

2019-07-03 09:33 UTC, martinwicke commented
@gabriel-vanzandycke can you also correct the converter tool to add the data_format arg? It should be parallel to the entry for erosion2d: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2.py#L1525

@tomerk The converter didn't do the right thing here, can you review the change to make sure it will once @gabriel-vanzandycke is done?

@tensorflow/api-owners This is a bug affecting the API: the accepted string has changed. The old state is a bug, we need to fix it. I added relnotes.

2019-07-03 09:33 UTC, martinwicke requested changes
Please add the converter code, see other comment.

2019-08-01 18:26 UTC, martinwicke approved these changes
Let's get this in, I'll submit the converter change separately.

2019-08-01 22:41 UTC, merged