[ROCm] Adding ROCm support for the reduction ops
tensorflow/tensorflow pull request #30291
Opened 2019-07-01 21:49 UTC by deven-amd

This PR adds ROCm support for the reduction ops

The changes in this PR are mostly trivial, please review and merge.

Notes:
* ROCm does not have support for complex datatype for some BLAS operations. As a consequence you will see #ifdef GOOGLE_CUDA around code related to complex datatype
* This PR merge (https://github.com/tensorflow/tensorflow/commit/41c36223dcd265603ca6916fec0a88016eb9abaa#diff-dfb288ce4a5f0ff51ccd12df2c86edac) seems to have accidentally undone ROCm support for the where op. The second commit in this PR, re-enables the ROCm support for the where op. It is included as a part of this PR, because ROCm support for where op is required for the `--config=rocm` build to complete, when ROCm support for reduction ops is also enabled.

-------------------------------------------

@tatianashp @whchung @chsigg

2019-07-01 21:52 UTC, whchung commented on tensorflow/core/kernels/reduction_ops_gpu_complex64.cu.cc
> +#endif  // GOOGLE_CUDA || TENSORFLOW_USE_ROCM
@deven-amd this is not needed?

2019-07-01 21:54 UTC, whchung requested changes
nit picking: `reduction_ops_gpu_complex64.cu.cc` has one line which shouldn't be changed

2019-07-01 22:46 UTC, deven-amd commented on tensorflow/core/kernels/reduction_ops_gpu_complex64.cu.cc
> +#endif  // GOOGLE_CUDA || TENSORFLOW_USE_ROCM
good catch...let me fix this

2019-07-01 23:16 UTC, deven-amd commented on tensorflow/core/kernels/reduction_ops_gpu_complex64.cu.cc
> +#endif  // GOOGLE_CUDA || TENSORFLOW_USE_ROCM
done

2019-07-01 23:30 UTC, whchung submitted a review, later dismissed

2019-07-03 06:41 UTC, chsigg submitted a review, later dismissed

2019-07-03 12:50 UTC, deven-amd commented
@rthadur , I will push out a rebase shortly to resolve the merge conflict.

2019-07-03 13:46 UTC, deven-amd commented
rebase done.

@chsigg , please re-approve...thanks

2019-07-03 14:06 UTC, chsigg approved these changes

2019-07-10 19:58 UTC, deven-amd commented
@rthadur 

this is the 3rd of 4 PRs that seem to be stuck in the merge pipeline. 
Please let me know if there is anything that needs to be done on my end.
thanks

deven

2019-07-10 20:21 UTC, rthadur commented
> @rthadur
> 
> this is the 3rd of 4 PRs that seem to be stuck in the merge pipeline.
> Please let me know if there is anything that needs to be done on my end.
> thanks
> 
> deven

trying to pull this in again , thank you

2019-07-12 20:44 UTC, rthadur commented
@deven-amd there are some internal test failures happening for this change , @chsigg can you please help to resolve those ?

2019-07-22 14:00 UTC, deven-amd commented
@rthadur @chsigg gentle ping. thanks.

2019-07-29 21:46 UTC, dagamayank commented
@chsigg while we have your attention, can you please also propose next steps for this PR?

2019-08-02 20:32 UTC, chsigg approved these changes

2019-08-07 14:35 UTC, dagamayank commented
@chsigg gentle ping.

2019-08-08 12:47 UTC, merged