Update gpu.Dockerfile
tensorflow/tensorflow pull request #30365
Opened 2019-07-03 17:45 UTC by casperdcl

added missing /usr/local/cuda/lib64 in LD_LIBRARY_PATH

fixes library not found errors in images based off tensorflow

2019-07-03 17:50 UTC, casperdcl commented
I signed it

2019-07-03 22:58 UTC, angerson requested changes
Thanks for your PR! Please have a look at the README in the dockerfiles directory for instructions on editing the partials and the rest of the dockerfiles.

2019-07-10 15:55 UTC, casperdcl commented
@angersson updated partials

2019-07-11 18:23 UTC, angerson approved these changes
Looks good, thanks!

2019-07-11 21:53 UTC, merged