Sriniva2/scatter sub
tensorflow/tensorflow pull request #30375
Opened 2019-07-03 21:33 UTC by Srini511

This PR parallelizes scatter update op using.
Single Threaded
Benchmark                 Time(ns) Iterations
---------------------------------------------
BM_ScatterAddInt32/1      11742060        100    85.2M items/s
BM_ScatterAddInt32/10     23648080        100    422.9M items/s
BM_ScatterAddInt32/64     62754140        100    1019.9M items/s
BM_ScatterAddInt32/256   187718030        100    1363.7M items/s
BM_ScatterAddInt32/1024  662454890        100    1545.8M items/s

TF_NUM_INTRAOP_THREADS=13
Benchmark                 Time(ns) Iterations
---------------------------------------------
BM_ScatterAddInt32/1       2277507        282    439.1M items/s
BM_ScatterAddInt32/10      3805265        181    2627.9M items/s
BM_ScatterAddInt32/64     11039150        100    5797.5M items/s
BM_ScatterAddInt32/256    42545230        100    6017.1M items/s
BM_ScatterAddInt32/1024  139565500        100    7337.1M items/s

2019-07-08 23:47 UTC, penpornk requested changes
Thank you for the PR! The speedups are nice. :)

2019-07-08 23:47 UTC, penpornk commented on tensorflow/core/kernels/scatter_functor.h
> +    Index bad_index GUARDED_BY(mu_);
Please initialize this to -1.

2019-07-08 23:47 UTC, penpornk commented on tensorflow/core/kernels/scatter_functor.h
> +    if (found_bad_index) return bad_index;
Since we have initialized `bad_index` to -1, you can just return `bad_index` without checking. Please remove `found_bad_index`.

2019-07-08 23:47 UTC, penpornk commented on tensorflow/core/kernels/scatter_op_test.cc
> +class ScatterSubOpTest : public OpsTestBase {
Please add a blank line above this line.

2019-07-08 23:47 UTC, penpornk commented on tensorflow/core/kernels/scatter_op_test.cc
> +  int kNumUpdates = big_num_updates ? 1000000 : 1000;
Please make this a constant.

2019-07-09 04:38 UTC, Srini511 commented
Thanks @penpornk . Addressed the changes requested.

2019-07-09 16:42 UTC, penpornk approved these changes
Thank you for your quick fixes!

2019-07-09 17:34 UTC, rthadur commented
@Srini511 can you please check build failures ?

2019-07-09 17:55 UTC, Srini511 commented
@rthadur , I did a full build and also all the 4 root cause targets at my end. They seem to be passing. Any suggestions on how to reproduce this?

2019-07-09 18:19 UTC, penpornk requested changes

2019-07-09 18:19 UTC, penpornk commented on tensorflow/core/kernels/scatter_functor.h
> +    Index bad_index = -1 GUARDED_BY(mu_);
The assignment should be after `GUARDED_BY`.
```suggestion
    Index bad_index GUARDED_BY(mu_) = -1;
```

2019-07-09 18:27 UTC, Srini511 commented
@penpornk , I accepted your suggestion and somehow, the cla check is broken :-)

2019-07-09 19:19 UTC, penpornk approved these changes
@Srini511 No worries. :) It just got confused because the auto-generated author email from my suggestion is 38085909+penpornk@users.noreply.github.com, which the bot does not recognize.

@rthadur Thank you!

2019-07-09 20:39 UTC, penpornk commented
12 tests passed and only `Ubuntu Python2` and `Ubuntu Python3` are failing. Both of them don't have links to test logs so I'm going to rerun the tests again.

2019-07-10 16:37 UTC, Srini511 commented
@penpornk I think all the required tests have passed!

2019-07-10 16:50 UTC, penpornk commented
@Srini511 Yay!
@rthadur I think this PR is ready to pull. :) Only `Windows Bazel GPU` is failing this time, and it used to pass last time we ran the tests (without code changes).

2019-07-10 17:55 UTC, rthadur commented
@penpornk done.

2019-07-10 18:04 UTC, penpornk commented
@rthadur Thank you! :)

2019-07-10 18:12 UTC, Srini511 commented
Thanks @penpornk and @rthadur

2019-07-10 18:58 UTC, merged

2019-07-10 23:43 UTC, Srini511 commented
Hi @penpornk is there a problem with the PR?

2019-07-11 00:10 UTC, penpornk commented
@Srini511 Sorry about that. It was causing third_party/tensorflow/contrib/metrics:metric_ops_large_test to fail so I had to revert. Could you please help take a look? Thank you!

Here is the error log (line numbers might not match):
```
Traceback (most recent call last):   File "absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
     yield   
File "absl/third_party/unittest3_backport/case.py", line 162, in run
     testMethod()   
File "tensorflow/contrib/metrics/python/ops/metric_ops_large_test.py", line 64, in testLargeCase
     self.assertNear(got_value, expected_value, 1.0)   
File "tensorflow/python/framework/test_util.py", line 1095, in decorated
     return f(*args, **kwds)   
File "tensorflow/python/framework/test_util.py", line 2195, in assertNear
     (f1, f2, err, " (%s)" % msg if msg is not None else ""))   
File "<embedded stdlib>/unittest/case.py", line 422, in assertTrue
     raise self.failureException(msg) AssertionError: False is not true : 291006464.000000 != 297795584.000000 +/- 1.000000
```

2019-07-11 00:15 UTC, Srini511 commented
Hi @penpornk, I cannot find that test since it is in contrib directory. Is it an internal test?

2019-07-11 00:29 UTC, Srini511 commented
Found the test. Will look into it and let you know. Thanks!