[Intel MKL] Replace redundant attribute function with a generic function.
tensorflow/tensorflow pull request #30392
Opened 2019-07-04 05:11 UTC by Zantares

In MKL layout pass, use an iterator to get all attributes from original node, and copy them to the node builder instead of specific function. It helps to remove redundant code.
TF will throw an error if the two nodes have different attributes, so it can be easily found when copied wrong attributes.

modified:
- tensorflow/core/graph/mkl_layout_pass.cc

Signed-off-by: Lu Teng teng.lu@intel.com

2019-07-10 17:09 UTC, penpornk requested changes
This is awesome! Thank you! :)

2019-07-10 17:09 UTC, penpornk commented on tensorflow/core/graph/mkl_layout_pass.cc
> +    iter++;
Nit:
```suggestion
    ++iter;
```

2019-07-11 02:20 UTC, Zantares commented on tensorflow/core/graph/mkl_layout_pass.cc
> +    iter++;
Modified, thanks for your suggestion!

2019-07-16 12:01 UTC, gbaned commented
@Zantares Could you please resolve the conflicts? Thanks!

2019-07-16 16:49 UTC, penpornk submitted a review, later dismissed
Ouch. For some reason, I only saw that you have updated this just now. So sorry for the delay! (I'll re-approve if the merging has conflicts.)

2019-07-19 19:44 UTC, penpornk commented
@Zantares Could you please help resolve the conflicts? Thank you!

2019-07-25 02:06 UTC, Zantares commented
> @Zantares Could you please help resolve the conflicts? Thank you!

Sorry for the delay, I was on a vacation few days ago. I have merged the master to this branch and fixed the conflict, please take a review again, thanks!

2019-07-26 09:44 UTC, Zantares commented
This PR helps me to find redundant attributes in UT,  I removed them and made a new commit.

2019-07-26 19:58 UTC, penpornk approved these changes
No worries! Thanks again for your PR!

2019-07-29 17:54 UTC, merged