[Intel MKL] Enabling MKL Conv2D BWD in eager mode
tensorflow/tensorflow pull request #30402
Opened 2019-07-04 06:52 UTC by mahmoud-abuzaina

This PR depends on #30401. So please review and merge #30401 first.

2019-07-10 18:18 UTC, penpornk requested changes
Thank you for your PR! 
I have an overall question: Why do we need an additional op for the eager version? Can't we just add `eager` as a parameter to `_MklConv2DBackpropFilter` and `_MklConv2DBackpropInput`?

2019-07-24 09:39 UTC, gbaned commented
@mahmoud-abuzaina Did you get a chance to look on reviewer comments? Please let us know on the update. Thanks!

2019-07-26 23:19 UTC, gzmkl commented on tensorflow/core/kernels/mkl_conv_grad_input_ops.cc
> +      if (eager_mode) {
Sure, I will do

2019-07-26 23:23 UTC, gzmkl commented
@gbaned: I am sorry for the late response. After handling the related PR "eagle mode Conv fwd",
I can deal with the "bwd" one. I may not answer all questions/comments since I am covering
the original developer. But I will try my best.

2019-07-29 17:57 UTC, gzmkl commented on tensorflow/core/kernels/mkl_conv_grad_input_ops.cc
> +      if (eager_mode) {
Done with code change

2019-07-29 18:26 UTC, penpornk approved these changes
Thank you for the fix!

2019-07-29 18:29 UTC, penpornk requested changes
Oops. Just realized my question about adding `eager` as an op attribute instead of template parameter hasn't been answered yet. Taking the approval back for now. (Probably have to wait for the FWD PR https://github.com/tensorflow/tensorflow/pull/30401)

2019-08-02 23:52 UTC, penpornk approved these changes

2019-08-05 17:12 UTC, alextp approved these changes
@penpornk I think in the future we shouldn't need special eager-owners approval for these changes; now that the mechanism is agreed upon these should be safe.

2019-08-05 17:26 UTC, penpornk commented
@alextp Got it. Then I can handle MKL-related, incremental eager PRs alone and will request reviews from eager owners when there are major changes.

2019-08-05 21:58 UTC, gzmkl commented
@penpornk  Hi Penporn, please help to get this one merged into 2.0. Thanks!   -GZ

2019-08-05 22:27 UTC, penpornk commented
@gzmkl I'm working on getting it merged in the master branch. :) After that, I'll see if we can cherrypick this into 2.0. Same for https://github.com/tensorflow/tensorflow/pull/31311.

2019-08-05 23:10 UTC, merged