[ROCm] Skipping subtests that check support for float64 type in the NN ops
tensorflow/tensorflow pull request #30500
Opened 2019-07-08 17:40 UTC by deven-amd

ROCm platform currently does not support the float64/double type in the NN ops

This commit skips subtests (within python unit-tests) that test this functionality. The "skip" is guarded by the call to "is_built_with_rocm()", and hence these unit-tests will not be affected in any way when running with TF which was not built with ROCm support (i.e. `--config=rocm`)

---------------------------------

@tatianashp @whchung @chsigg

2019-07-08 17:43 UTC, whchung commented on tensorflow/python/ops/nn_test.py
> +
nit: please help remove these empty lines.

2019-07-08 17:44 UTC, whchung requested changes
@deven-amd minor cosmetic changes are required.

2019-07-08 18:22 UTC, deven-amd commented on tensorflow/python/ops/nn_test.py
> +
done

2019-07-08 18:27 UTC, whchung submitted a review, later dismissed

2019-07-09 12:41 UTC, chsigg submitted a review, later dismissed

2019-07-10 14:27 UTC, deven-amd commented
I looked at the CI failure logs, and they do not seem related to the changes in this PR.

The one failure in `Linux GPU` is in a test that was modified by this PR. However the changes in this PR should be a no-op for the CUDA / `Linux GPU` run, and hence it does not seem likely that the change in this PR is the cause for the failure.

2019-07-10 17:41 UTC, rthadur commented
@deven-amd here is the internal error : 
`InternalError: 2 root error(s) found.
  (0) Internal: cuDNN Backward Data function launch failure : input shape([1,5,8,7,2]) filter shape([1,2,3,2,3])
	 [[node gradients_5/conv_5_grad/Conv3DBackpropInputV2 (defined at /third_party/py/absl/third_party/unittest3_backport/case.py:162) ]]
  (1) Internal: cuDNN Backward Data function launch failure : input shape([1,5,8,7,2]) filter shape([1,2,3,2,3])
	 [[node gradients_5/conv_5_grad/Conv3DBackpropInputV2 (defined at /third_party/py/absl/third_party/unittest3_backport/case.py:162) ]]
	 [[gradients_5/conv_5_grad/Conv3DBackpropInputV2/_19]]`

2019-07-10 18:02 UTC, deven-amd commented
@rthadur 

I saw the error in the invocation log, but cannot see how the change in this PR can cause it. 

For the CUDA run, the only thing that will change with this PR is the ordering the dtypes in the list, it will go from `[dtypes.float64, dtypes.float32, dtypes.float16]` to `[dtypes.float32, dtypes.float16, dtypes.float64]`. The two are functionally equivalent and should not cause any failure (I would think)

Let me push out a change that keeps the above mentioned ordering intact, and see it that fixes the error!

deven

2019-07-11 14:03 UTC, deven-amd commented
@whchung , please re-approve this to kick-off the CI runs. 
I need to figure out whether or not my last change fixes the failure in the `LInux GPU` CI run.

Thanks
deven

2019-07-11 16:32 UTC, deven-amd commented
@rthadur , the CI errors are gone :)

2019-07-11 21:30 UTC, rthadur commented
@deven-amd thank you , @chsigg can you please review this again.

2019-07-11 21:30 UTC, whchung approved these changes

2019-07-16 08:38 UTC, chsigg approved these changes

2019-07-18 19:34 UTC, merged