[XLA] Add option to tfcompile HLO proto
tensorflow/tensorflow pull request #30520
Opened 2019-07-09 08:30 UTC by rjeli

2019-07-09 19:33 UTC, sanjoy requested changes

2019-07-09 19:33 UTC, sanjoy commented on tensorflow/compiler/aot/tfcompile_main.cc
> +    return errors::InvalidArgument("Must specify either --graph or --hlo_module");
Also check that the user didn't specify both.

2019-07-09 19:33 UTC, sanjoy commented on tensorflow/compiler/aot/flags.cc
> +      {"hlo_module", &flags->hlo_module,
State that the user may supply one of `--graph` or `--hlo_module`.

2019-07-09 19:33 UTC, sanjoy commented on tensorflow/compiler/aot/flags.cc
> +      {"hlo_module", &flags->hlo_module,
Please also add a warning that the HLO proto is *not* a backwards / forwards compatible format and it is not okay to e.g. expect an HLO module generated today will continue to work in perpetuity with tfcompile.

2019-07-09 22:04 UTC, rjeli commented
Ok, thanks for review. My first TF PR so want to make sure I have the style/conventions right 🙂

2019-07-09 23:40 UTC, rjeli commented on tensorflow/compiler/aot/tfcompile_main.cc
> +   || (!flags.graph.empty() && !flags.hlo_module.empty())) {
This is just an XNOR (`flags.graph.empty() == flags.hlo_module.empty()`), but I assume clarity is more important

2019-07-10 00:04 UTC, sanjoy approved these changes
lgtm

2019-07-10 20:24 UTC, sanjoy commented
This breaks some internal tests.  You can reproduce the error `bazel test //tensorflow/compiler/aot/tests:all_tests -c opt`, we don't test these by default since that would end up building LLVM twice, once for the host build and once for the target build.

Right now `//tensorflow/compiler/aot/tests:all_tests` is broken for some unrelated reasons, but I have a fix in flight that should land soon.

2019-08-01 06:34 UTC, gbaned commented
@sanjoy  Any update on this PR, please.

2019-08-02 02:27 UTC, sanjoy commented
> Right now `//tensorflow/compiler/aot/tests:all_tests` is broken for some unrelated reasons, but I have a fix in flight that should land soon.

This is fixed now so @rjeli should be able to run the AOT tests with this patch and fix them.

2019-08-02 02:47 UTC, sanjoy requested changes
The AOT unit tests need to be fixed, as stated in the conversation.

2019-08-20 10:34 UTC, gbaned commented
@rjeli Could you please address the reviewer comments. Thanks!

2019-08-20 13:08 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-09-04 12:32 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-09-10 09:53 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-09-10 09:53 UTC, closed without merging