Add NMSv3 GPU op
tensorflow/tensorflow pull request #30893
Opened 2019-07-20 03:11 UTC by samikama

This PR adds GPU version of NMSv3 Op and extends NMS kernel to support legacy networks as well as modern networks, addressing the issue mentioned in original NMS GPU op commit.

2019-07-22 16:47 UTC, samikama commented
@aaroey, can you take a look. This is pretty much the same of NMSv2 except that the NMS op is limited to boxes with scores greater than the threshold.

2019-08-13 13:58 UTC, fferroni commented
@samikama  hi, do you have an expectation of the speed-up from CUDA? I've been trying on some synthetic data of 100,000 boxes, and get a CPU time that is much better than your implementation...?

2019-08-14 19:27 UTC, aaroey commented
@samikama could you address the comment by @fferroni above and provide a simple repro of the performance benefits?

2019-08-20 13:07 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-08-28 22:23 UTC, samikama commented
@fferroni Could you post your test case? In my tests it was on par with CPU implementation. Nevertheless, I did improve the performance with a new commit. Here are some numbers from my tests
```
python TestNMSv3.py --num_iter=1000 -num_boxes=4096 --max_output=2000
GPUv3     times=  1.196 +-   0.040 msec 
GPUv2     times=  1.170 +-   0.468 msec 
CPU         times= 77.669 +-  17.420 msec
HCPU      times= 75.239 +-  17.725 msec 
```
Test randomly generates 4096 boxes and scores that are fed into NMSv2 and NMSv3 ops on GPU and NMSV3 op on CPU, max_output_size is set to 2000 in all ops, data is placed in variables so no host to device copy needed. CPU is fed with data on GPU, HCPU is fed with data on CPU. All arguments of the ops are identical whenever possible. 1000 tests are run and average and stddev is reported. There can be further improvements that will show up when op is executed on graph by changing op to an async op but considering the improvement, I don't think it is necessary.

2019-08-29 16:45 UTC, samikama commented
@aaroey do you have any more concerns?

2019-09-04 04:44 UTC, aaroey requested changes

2019-09-04 04:44 UTC, aaroey commented on tensorflow/core/kernels/non_max_suppression_op.cu.cc
> +__device__ float legacy_offset(float);
As commented on the other PR, please remove these legacy offset funcs?

2019-09-04 04:44 UTC, aaroey commented on tensorflow/core/kernels/non_max_suppression_op.cu.cc
> +  constexpr int SHIFTLEN = NumBits(8 * sizeof(T)) - 1;
nit: kShiftLen, kRemainderMask

2019-09-04 04:44 UTC, aaroey commented on tensorflow/core/kernels/non_max_suppression_op.cu.cc
> +  void Compute(OpKernelContext* context) override {
This method is almost the same as NonMaxSuppressionV2GPUOp::Compute() except the additional score input handling logic. Please do something like: add a NonMaxSuppressionGPUOpBase class and encapsulate the common code as helper member functions and reuse them in both ops.

2019-09-09 17:29 UTC, samikama commented on tensorflow/core/kernels/non_max_suppression_op.cu.cc
> +#include "third_party/cub/device/device_radix_sort.cuh"
Hi @aaroey These were changed by clang-format, If I revert them clang-format check will complain.

2019-09-09 17:47 UTC, aaroey commented on tensorflow/core/kernels/non_max_suppression_op.cu.cc
> +#include "third_party/cub/device/device_radix_sort.cuh"
I see, sorry I didn't know that. Feel free to skip.

2019-09-09 21:49 UTC, aaroey submitted a review, later dismissed
Thanks for the fix!

2019-09-09 22:07 UTC, aaroey approved these changes

2019-09-10 01:13 UTC, merged

2019-09-11 21:28 UTC, aaroey commented
This PR breaks an internal test and was partially rolled back in https://github.com/tensorflow/tensorflow/commit/009dcac2213e737f22db69e84615b66f77bd6ddb, and the problem is tracked in #32446.