Make ReplaceInstruction preserve the sharding info.
tensorflow/tensorflow pull request #30986
Opened 2019-07-24 11:30 UTC by davors72

Right now ReplaceInstruction preserves the metadata if the user hasn't specified any on the new instruction. If we don't do this for the sharding information as well optimizations will drop the
sharding information.

2019-07-24 14:28 UTC, sanjoy requested changes
I'm not sure if this is correct.  IIUC sharding is semantically meaningful information that cannot be "transparently" copied in this way.

@hyouklee for second opinion.

2019-07-24 17:18 UTC, davors72 commented
> I'm not sure if this is correct. IIUC sharding is semantically meaningful information that cannot be "transparently" copied in this way.
> 
> @hyouklee for second opinion.

Thanks for getting back @sanjoy 

I'd agree that sharding is semantically meaningful. The issue we have currently is fairly critical because the sharding information as specified by user python code is being dropped by HLO optimization passes (specifically in this case algebraic simplifier). In other words the semantic meaning is lost altogether. The only other option I can see is for HLO passes (at least in algebraic simplifier) to be rewritten to preserve sharding information.

I understand that we may not want this to add semantic meaning, however if an optimization writer wishes to add their own sharding information they can and this diff won't overwrite it. This will only add it in the case it has been left empty (either removing the information from the old instruction or adding the default sharding information to the new one would avoid this). 

I don't mind if this diff specifically isn't accepted but we will need some way of addressing this issue.

2019-07-24 17:48 UTC, hyouklee commented
We currently don't have a well defined policy whether the sharding is a guaranteed property of the operation or just a user hint. If what you want is the latter, it would probably be okay to propagate the sharding as long as shapes match between the old and new instruction. But this PR still wouldn't be enough to guarantee preserving the sharding annotation since optimization passes don't always use ReplaceInstruction() API.

We use kDomain instructions (with HloDomainIsolator and HloDomainRemover) to preserve sharding annotations on some backends, although it doesn't always work well (and could potentially prevent quite some compiler optimizations). You can see "tensorflow/compiler/xla/service/hlo_domain_test.cc" how it can be used.

2019-07-24 21:48 UTC, davors72 commented
@hyouklee  Ok if it is not XLA policy to preserve sharding we may need to revisit a proper solution later. In the meantime could this PR still be approved? ReplaceInstruction guarantees the shapes are the same and even if it isn't enough to catch all cases it at least fixes the regressions we have reproducible cases for right now.

2019-07-24 23:59 UTC, hyouklee commented
For the TPU backend we do guarantee sharding using the domain mechanism I commented earlier. I was just saying that we don't have a global policy in XLA about sharding that all backends agreed on. Is it a not an option to use domains? If not, I would be fine to approve the PR.

@sanjoy Do you have other concerns?

2019-07-25 04:29 UTC, sanjoy commented
No other concern, but please add a comment on `ReplaceInstruction` that makes this new behavior obvious.

2019-07-25 14:17 UTC, davors72 commented
Thanks guys! @sanjoy, added a comment now. @hyouklee it's not that it is not an option to use domains but that would be a larger fix. We could revisit that later if more sharding issues crop up but for now this feels like a less intrusive fix for just the issues we have now.

2019-07-25 15:29 UTC, sanjoy approved these changes
lgtm

2019-07-26 00:17 UTC, merged