[INTEL MKL] Enable MatMul in eager mode
tensorflow/tensorflow pull request #31168
Opened 2019-07-30 15:38 UTC by gzmkl

Enable MKL MatMul in eager mode.

Pending on the following PRs (that is, this PR should be merged after them):
https://github.com/tensorflow/tensorflow/pull/30401   (MKL conv fwd in eager mode)
https://github.com/tensorflow/tensorflow/pull/30402   (MKL conv bwd in eager mode)

2019-07-30 15:42 UTC, agramesh1 commented
Pinging @penpornk for review.

2019-07-30 18:37 UTC, penpornk reviewed
This PR overlaps a lot with https://github.com/tensorflow/tensorflow/pull/30401. Can you make this PR depend on https://github.com/tensorflow/tensorflow/pull/30401? Otherwise, we should just wait until https://github.com/tensorflow/tensorflow/pull/30401 is merged.

2019-07-30 18:40 UTC, penpornk commented
(I meant, this PR seems to have just a few lines of changes when based on https://github.com/tensorflow/tensorflow/pull/30401.)

2019-07-31 17:21 UTC, gzmkl commented
@penpornk.  Yes, it depends on PR #30401. It is better waiting #30401 is merged. Thanks!

2019-08-02 18:52 UTC, gzmkl commented
Headsup: after PR https://github.com/tensorflow/tensorflow/pull/30402 being merged, 
there will be some conflicts which I will resolve.

2019-08-03 00:02 UTC, gzmkl commented
FYI - the expected merge conflicts have been resolved

2019-08-03 00:11 UTC, penpornk requested changes
Thank you! A few minor changes please.

2019-08-03 00:11 UTC, penpornk commented on tensorflow/core/common_runtime/eager/BUILD
> +load(
This has already been loaded in the lines above. Please remove.

2019-08-03 00:11 UTC, penpornk commented on tensorflow/core/common_runtime/eager/BUILD
> +
Please remove the extra blank line.

2019-08-03 21:13 UTC, agramesh1 commented
Please ignore, Git merge messed things up. Created a new PR here https://github.com/tensorflow/tensorflow/pull/31311  I will try to close this PR.

2019-08-03 21:53 UTC, penpornk commented
I'll close the PR for you.

2019-08-03 21:53 UTC, closed without merging