BaseDenseAttention now supports attention dropout
tensorflow/tensorflow pull request #31191
Opened 2019-07-31 09:46 UTC by claverru

Added optional dropout applied to attention weights (scores)

2019-07-31 09:47 UTC, claverru commented
> @googlebot I signed it!

2019-08-19 23:38 UTC, tanzhenyu commented
I'm not sure I'm the best person to review this.
Can you find the author of dense attention?
https://github.com/tensorflow/community/blob/master/rfcs/20190115-dense-attention.md

2019-08-20 13:06 UTC, mellanox-github commented
Can one of the admins verify this patch?

2019-08-27 06:48 UTC, claverru commented
@roumposg 

https://github.com/tensorflow/models/blob/master/official/transformer/v2/attention_layer.py

I know its not a paper, but the official TensorFlow implementation. I was just morroring it.

And the results are slightly different from the "more conventional" dropout, given that it's applied to the attention weights. Think of it as the recurrent dropout the RNNs have.

On the other hand, I was about to contribute the implementation of the Relative Encoding (https://arxiv.org/abs/1803.02155, and with a better explanation https://arxiv.org/abs/1809.04281). Would it be a good idea?

2019-08-27 15:30 UTC, roumposg requested changes
Let's add a test. Because `dropout` is probabilistic, we can only test the shape of the output tensor. See the `test_shape` tests in https://github.com/tensorflow/tensorflow/blob/51c581749570584d504d9a748f1b6202d6adcced/tensorflow/python/keras/layers/dense_attention_test.py

2019-08-27 16:16 UTC, claverru commented
@roumposg Thank you, I appreciate it. I will fix them as soon as I can. Also thanks to @tanzhenyu .

2019-08-28 07:52 UTC, claverru commented on tensorflow/python/keras/layers/dense_attention.py
> +    dropout: Float between 0 and 1. Fraction of the units to drop for the attention scores.
Done

2019-08-28 07:52 UTC, claverru commented on tensorflow/python/keras/layers/dense_attention.py
> +      * training: Whether the layer is training or not. Used to apply dropout.
Done

2019-08-28 07:52 UTC, claverru commented on tensorflow/python/keras/layers/dense_attention.py
> +  def _apply_scores(self, scores, value, training, scores_mask=None):
Done

2019-08-28 07:53 UTC, claverru commented on tensorflow/python/keras/layers/dense_attention.py
> +	    weights = tf.nn.dropout(weights, rate=self.dropout)
Done

2019-08-28 07:54 UTC, claverru commented on tensorflow/python/keras/layers/dense_attention.py
> +  def call(self, inputs, training, mask=None):
Not sure since dropout is suposed to work differently in training mode and inference mode.

2019-08-28 07:55 UTC, claverru commented on tensorflow/python/keras/layers/dense_attention.py
> +    result = self._apply_scores(scores=scores, value=v, training, scores_mask=scores_mask)
Done

2019-08-28 17:00 UTC, roumposg requested changes
Thanks for working on this. Please, also add a test. Because `dropout` is probabilistic, we can only test the shape of the output tensor. See the `test_shape` tests in https://github.com/tensorflow/tensorflow/blob/51c581749570584d504d9a748f1b6202d6adcced/tensorflow/python/keras/layers/dense_attention_test.py and add a similar one, thanks.

Also, please add validation as I replied in one of the comments, thanks.

2019-08-29 10:06 UTC, claverru commented
@roumposg I think it should be finished now, let me know please.

2019-08-29 14:43 UTC, roumposg submitted a review, later dismissed

2019-08-29 14:50 UTC, tanzhenyu submitted a review, later dismissed

2019-09-06 19:44 UTC, tanzhenyu approved these changes

2019-09-18 15:04 UTC, claverru commented
@gbaned Is everything alright?

2019-09-23 10:46 UTC, gbaned commented
@claverru Sorry for the late reply. It is pending with internal merging. Thanks!

2019-11-29 21:01 UTC, arthurflor23 commented
Any news?

2019-11-30 10:58 UTC, claverru commented
> Any news?

@gbaned ?

2019-12-02 05:06 UTC, gbaned commented
@arthurflor23, @claverru  This is failing some internal tests, please stay tuned. Thanks!

2020-02-14 10:44 UTC, tanzhenyu commented
It broke internal tests so @roumposg submitted a separate commit [here](https://github.com/tensorflow/tensorflow/commit/2c0ab25cad67841e28218f3612801f9a2d673a0a)

2020-02-14 10:53 UTC, claverru commented
Thank you @tanzhenyu , @roumposg !

2020-02-14 17:26 UTC, rthadur commented
Seems auto-merge is not happening but the changes are now committed so we can close this. Thank you for the PR.

2020-02-14 17:26 UTC, closed without merging