Support the NHWC avg pooling after cuDNN 7.3.0
tensorflow/tensorflow pull request #31207
Opened 2019-07-31 17:29 UTC by houtoms

The efficient NHWC cuDNN average pooling is there after 7.3.0. Therefore, we can directly call cuDNN kernels when NHWC inputs are given.

fyi @nluehr

2019-07-31 17:40 UTC, whchung requested changes

2019-07-31 17:40 UTC, whchung commented on tensorflow/core/kernels/avgpooling_op.cc
> +#include "third_party/gpus/cudnn/cudnn.h"
please guard with `#if GOOGLE_CUDA`.

2019-07-31 17:47 UTC, houtoms commented on tensorflow/core/kernels/avgpooling_op.cc
> +#include "third_party/gpus/cudnn/cudnn.h"
Thanks for the comments. Done.

2019-07-31 19:05 UTC, whchung approved these changes

2019-08-05 13:01 UTC, chsigg approved these changes

2019-08-05 18:37 UTC, houtoms commented
Hi, @chsigg Thx for approving the PR. There is one broken test (Ubuntu Python3 PIP), but it seems it is related to MLIR. Could you please help me check?

2019-08-05 20:15 UTC, merged