[INTEL MKL] Work around tf.data related performance regression on Int…
tensorflow/tensorflow pull request #31221
Opened 2019-08-01 05:35 UTC by wei-v-wang

…el MKL backend.

RN50 real data performance regression was about 40%. This PR brings the
performance back by adding the MKL specific #ifdef macro.

2019-08-01 14:32 UTC, jsimsa requested changes
This PR fixes a symptom and not the real issue.

I would prefer to understand why is the use of multi-device function backend causing a regression (as compared to regular function backend.

2019-08-01 14:37 UTC, jsimsa commented
Furthermore, while your fix might address the resnet performance regression, it would break any programs that require the use of multi-device function backend.

2019-08-01 16:43 UTC, wei-v-wang commented
Thanks @jsimsa for the review. We now roughly know why is_multi_device_function==true would cause performance slowdown, and we are internally working on a real solution, rather than a workaround. It will take time to finish validation to ensure the general solution does not incur other regressions. 

For "programs that require the use of multi-device function backend",  good point. This PR will generate an inconsistency from the python level. Could you please point me to some design principals (documents) of this is_multi_device_function? E.g. I'd like to understand is_multi_device_function transparent to the user and how can I tell that a particular program is using/benefiting from multi-device function backend, especially on why multi_device_function would benefit the Eigen on CPU and MKL on CPU, where the sharing of inter-op thread pool is already causing some headache sometimes. Thanks!

2019-08-01 17:14 UTC, jsimsa commented
Here is an example of a program that requires multi-device function backend: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/kernel_tests/map_test.py#L1227

Or any program that runs with a GPU and access a variable from input pipeline. In the presence of GPU, variables will be placed on GPU by default and without multi-device function such programs would not work. Here is a trivial example::

```
    v = tf.Variable([1.])  # implicitly on GPU
    def _map_fn(features, labels):
      return tf.add(features, v), labels

    features = tf.constant([[0., 1.], [2., 3.]])
    labels = tf.constant([1, 0])
    dataset = tf.data.Dataset.from_tensor_slices((features, labels))
    dataset = dataset.map(_map_fn)
```

2019-08-01 17:15 UTC, jsimsa commented
multi-device function backend is considered an implementation detail and there are no design principals / documents (as far as I know). You can study its code [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/process_function_library_runtime.h) and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/process_function_library_runtime.cc).

2019-08-01 17:53 UTC, wei-v-wang commented
Thanks @jsimsa for your time and this example! I understand is_multi_device_function more now. 
"Or any program that runs with a GPU and access a variable from input pipeline. In the presence of GPU, variables will be placed on GPU by default and without multi-device function such programs would not work. " It seems to me that this design is benefitting heterogeneous (CPU w/ GPU, CPU w/TPU) where the accelerators might need CPU's help for input pipelining. But different from  GPU, Intel MKL also runs on CPU, so Intel MKL does not need multi_device capability to read variables from the input pipelining, right? 
Also, my PR has added "#ifdef", so when we find it is GPU, multi_device will still be true.  

I think programs that require multi_device support are mostly written for non-CPUs (as you said,  to transfer data from input to compute), this PR maybe does not affect such programs I think. Please correct me if I am wrong. I think for pure CPUs, Intel MKL does not need to read variable from the input pipeline, therefore does not need multi_device_function?  

Or, for Intel MKL, are you thinking of the support that "one socket of a two socket system does input processing, and the compute would be on the other socket feature"?  Without multi_device_function feature, this will not be possible in TensorFlow, correct?  If that is the case, I think it makes sense.

2019-08-01 18:10 UTC, jsimsa commented
As you pointed out, cross-devices computation does not have to be just between CPU and GPU/TPU. There can be multiple CPU devices (e.g. one for each NUMA zone or if explicitly created by the user program).

Independently of the above, I think you change is making the tf.data code brittle (and harder to test) and I would prefer to first understand the problem (and convince myself that there is no better solution) before accepting such a change.

2019-08-01 18:21 UTC, wei-v-wang commented
Ok, thanks @jsimsa It now makes sense for me. Actually a better solution (not affecting tf.data at all) is coming up soon by our team. I am going to close my PR in light of our discussion above. Thank you!

2019-08-01 18:31 UTC, jsimsa commented
Sounds good.

2019-08-01 18:32 UTC, closed without merging

2019-08-02 17:43 UTC, wei-v-wang commented
@jsimsa  FYI, this is the real fix: https://github.com/tensorflow/tensorflow/pull/31254 
Restricting graph rewrite rule so that we don't have a standalone mkl version of slice op while others are non MKL.