Add documentation about Dataset shard's deterministic nature
tensorflow/tensorflow pull request #31897
Opened 2019-08-22 15:35 UTC by anubh-v

Hi everyone,
This pull request addresses the issue raised in issue #31698. 
Specifically, I have edited the documentation so that it clearly mentions that the `shard` operation in the Dataset API is deterministic.

[Here](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/core/kernels/data/shard_dataset_op.cc) is the file containing the implementation of `shard` in r2.0.
If I understand correctly, [this line](https://github.com/tensorflow/tensorflow/blob/b8b60ae09afb3b05dde9f183bac587c7dd437c78/tensorflow/core/kernels/data/shard_dataset_op.cc#L132) dictates exactly how the target Dataset is split into its "shards".

Please let me know your feedback.
Thanks for your time.

2019-08-22 17:43 UTC, alextp approved these changes

2019-08-22 19:12 UTC, aaudiber requested changes
Thanks @anubh-v, the example is great. I left a couple minor suggestions

2019-08-22 19:12 UTC, aaudiber commented on tensorflow/python/data/ops/dataset_ops.py
> +
Delete the trailing whitespace on lines 977, 989, and 992

2019-08-22 19:12 UTC, aaudiber commented on tensorflow/python/data/ops/dataset_ops.py
> +    `shard` is a deterministic operator; the returned Dataset depends only
We can make this more precise: "The dataset produced by `A.shard(n, i)` will contain all elements of `A` where their index mod `n` equals `i`."

Can we move this sentence to replace "For example:" above?

2019-08-22 19:37 UTC, merged

2019-08-22 20:25 UTC, rthadur commented
@aaudiber sorry this was merged automatically , @anubh-v do you want to address @aaudiber in a new PR if not i can take up this internally , thank you for your contribution.

2019-08-23 01:46 UTC, anubh-v commented
Thanks @aaudiber, I will raise a new PR to make the suggested changes.