[XLA] Make sure HloComputation::Equals takes dangling side-effects into account.
tensorflow/tensorflow pull request #31981
Opened 2019-08-26 14:14 UTC by georgepaw

Current implementation does not take dangling side-effect instructions such as outfeeds or rngs into account.
For example:
```
c1 (arg0.1: f32[], arg1.2: f32[2], arg2.3: f32[1,1,2,2]) -> () {
  %arg0.1 = f32[] parameter(0)
  %arg2.3 = f32[1,1,2,2]{3,2,1,0} parameter(2)
  %arg1.2 = f32[2]{0} parameter(1)
  // Do some computation
  %result = fp32[] ....
  %aa = token[] after-all()
  %feed = token[] outfeed(result.35, aa)
  ROOT %tuple.53 = () tuple()
}

c2 (arg0.1: f32[], arg1.2: f32[2], arg2.3: f32[1,1,2,2]) -> () {
  %arg0.1 = f32[] parameter(0)
  %arg2.3 = f32[1,1,2,2]{3,2,1,0} parameter(2)
  %arg1.2 = f32[2]{0} parameter(1)
  ROOT %tuple.53 = () tuple()
}
```
then `*c1 == *c2` evaluates to true.

2019-08-26 14:16 UTC, georgepaw commented
Note that we could simplify this by saying "two computations can never be equal if they have side effects". And it seems like most instructions with side-effect override identical to `false` but there are exceptions like the all-reduce in this test.

2019-08-28 15:54 UTC, sanjoy requested changes

2019-08-28 16:16 UTC, georgepaw commented on tensorflow/compiler/xla/service/hlo_computation_test.cc
> +  EXPECT_FALSE(*comp2 == *comp3);
Sure, I was just following other tests in the file

2019-08-28 16:20 UTC, georgepaw commented on tensorflow/compiler/xla/service/hlo_computation.cc
> +        // Make sure an instruction is only matched once.
Don't really follow this one, did you mean
> `instr_this` matches **two** instructions in `side_effect_instrs_other`
?
For every instruction with side-effect in "this" we find an instruction in "other" which matches. If there are two instructions in "other" which match an instruction from "this" we would expect two instructions in "this" as well for the computations to be identical.
We could check the other set is empty at the end, but we make sure we have the same number of side effect instructions before, and for every instruction in "this" we either remove an instruction from "other" if we match or we return early if we don't so the set should implicitly be empty.

2019-09-01 18:01 UTC, georgepaw commented on tensorflow/compiler/xla/service/hlo_computation.cc
> +  auto identical_from_instr = [&matched_between_comps, is_layout_sensitive](
Sure, should it be in an anonymous namespace? It also uses an internal state `matched_between_comps` to speed up the lookup for dangling instructions - do we want to keep that?

2019-12-18 09:39 UTC, gbaned commented
@georgepaw Can you please resolve conflicts? Thanks!

2020-01-02 12:30 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-02-05 10:58 UTC, gbaned commented
@georgepaw gentle ping to resolve conflicts? Thanks!

2020-02-12 10:00 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-02-12 10:00 UTC, closed without merging