include comment for kInferencesPerCycle for a Teensy4.0
tensorflow/tensorflow pull request #32030
Opened 2019-08-28 01:49 UTC by matpalm

2019-08-28 01:52 UTC, matpalm commented
@googlebot I signed it!

2019-08-28 01:53 UTC, matpalm commented
cc @dansitu

2019-10-24 20:14 UTC, aselle requested changes

2019-10-24 20:14 UTC, aselle commented on tensorflow/lite/experimental/micro/examples/hello_world/arduino/constants.cc
> +// For a cycle in ~4 seconds on a Teensy4.0 use kInferencesPerCycle = 400000
How about making a variable for each platform? i.e.
```
constexpr int kInferencesPerCycle_ArduinoMkrZero = 1000;
constexpr int kInferencesPerCycle_Teensy40 = 400000;
constexpr int kInferencesPerCycle = kInferencesPerCycle_ArduinoMkrZero;
```

2019-10-30 09:42 UTC, gbaned commented
@matpalm Could you please check reviewer comments and keep us posted. Thanks!

2019-11-14 12:28 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-11-18 10:02 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2019-11-18 10:02 UTC, closed without merging