[INTEL MKL] Add primitive cache for mkl softmax
tensorflow/tensorflow pull request #32151
Opened 2019-09-02 06:54 UTC by ShengYang1

Enable primitive reuse in MklSoftmax, please review.

2019-09-18 00:34 UTC, ShengYang1 commented
@xiejw  Could you take a look at this PR and give some suggestions? Thank you!

2019-09-19 21:42 UTC, penpornk requested changes
Thank you for your PR and sorry for our delay!

2019-09-19 21:42 UTC, penpornk commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +    MklSoftmaxPrimitive<T>* softmax_forward = nullptr;
Let's initialize this to the value in line 143 instead of `nullptr`.

2019-09-19 21:42 UTC, penpornk commented on tensorflow/core/kernels/mkl_softmax_op.cc
>        // construct input Tf layout. For TF layout, although input shape
Please update the comment.

2019-09-21 06:46 UTC, ShengYang1 commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +    std::shared_ptr<memory::desc> src_md;
We use shared_ptr just for easily resource management.

2019-09-21 06:48 UTC, ShengYang1 commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +    if (context_.softmax_fwd == nullptr) {
MklPrimitive was implemented in another way and this if expression was necessary before. Now it can be safely deleted. Thanks for your correction.

2019-09-21 07:03 UTC, ShengYang1 commented
@penpornk Changes applied.

2019-09-23 21:11 UTC, penpornk approved these changes
Thank you for the fixes!

2019-09-23 21:37 UTC, penpornk requested changes
I'm temporarily taking back my approval. I feel a bit weird about having unnecessary `shared_ptr`.

2019-09-23 21:37 UTC, penpornk commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +    std::shared_ptr<memory::desc> src_md;
If that's the case, would `unique_ptr` also work for you? It should be more efficient than `shared_ptr`.

2019-09-23 22:10 UTC, penpornk approved these changes

2019-09-23 22:10 UTC, penpornk commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +    std::shared_ptr<memory::desc> src_md;
Never mind. I see this in other PRs as well. I think this is more of a design question. I'll bring this up in a sync meeting later.

2019-09-25 17:15 UTC, merged