[Intel MKL] Upgrading giflib to fix CVE-2019-15133
tensorflow/tensorflow pull request #32169
Opened 2019-09-03 09:45 UTC by claynerobison

# [CVE-2019-15133](https://nvd.nist.gov/vuln/detail/CVE-2019-15133)

**NVD**: 2019/08/17 - CVSS v2.0 Base Score: 4.3 - CVSS v3.0 Base Score: 6.5
In GIFLIB before 2019-02-16, a malformed GIF file triggers a divide-by-zero exception in the decoder function DGifSlurp in dgif_lib.c if the height field of the ImageSize data structure is equal to zero.

## **References to Advisories, Solutions, and Tools**

Source | Link | Type
---- | ---- | ----
MISC | [bugs.chromium.org](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13008) | Mailing List, Third Party Advisory
UBUNTU | [usn.ubuntu.com](https://usn.ubuntu.com/4107-1/) | Third Party Advisory

2019-09-03 22:13 UTC, claynerobison commented
@rthadur This CVE doesn't just apply to MKL builds.

2019-09-03 22:30 UTC, penpornk requested changes
Thank you very much for the PR!

2019-09-03 22:30 UTC, penpornk commented on tensorflow/workspace.bzl
> +            "https://storage.googleapis.com/mirror.tensorflow.org/ufpr.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz",
```suggestion
            "https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz",
```

2019-09-04 00:20 UTC, penpornk approved these changes
Thank you for the quick fix!

2019-09-04 22:10 UTC, merged

2019-09-04 22:19 UTC, claynerobison commented
@penpornk @gunan May I suggest that this be cherry-picked?

2019-09-04 23:54 UTC, gunan commented
@goldiegadde this should be cherrypicked into 1.15 and 2.0

2019-09-05 00:02 UTC, penpornk commented
@gunan @claynerobison @goldiegadde I see a Windows Bazel failure (in some other PR's test results) that seems to originated from this PR.

```
gif.lib(gif_font.obj) : error LNK2019: unresolved external symbol strtok_r referenced in function GifDrawBoxedText8x8
```
[Full log](https://source.cloud.google.com/results/invocations/bd42ab39-0f56-4edc-b789-d16d76348800/log).

(The error doesn't show up in this PR's test results because the Windows tests were failing from CSRSparseMatrix changes at the time.)

Please don't cherrypick this PR yet. I'll fix this and cherrypick the changes afterwards.

2019-09-05 01:04 UTC, penpornk commented
Since this is affecting all other Windows test, we are reverting the PR for now.

2019-09-05 17:05 UTC, mihaimaruseac commented
Please assign to me (or notify me) when fixing