Use `patch` utility for patching sources on all platforms
tensorflow/tensorflow pull request #32177
Opened 2019-09-03 13:06 UTC by grwlf

Let me propose a fix for https://github.com/tensorflow/tensorflow/issues/31196 issue

2019-09-03 16:58 UTC, mihaimaruseac requested changes
This PR does more than its description says it does. Please remove unrelated changes.

2019-09-04 10:06 UTC, grwlf commented
> This PR does more than its description says it does. Please remove unrelated changes.

Rebased to master. @mihaimaruseac @rthadur please check

2019-09-04 15:52 UTC, mihaimaruseac approved these changes

2019-09-04 15:53 UTC, mihaimaruseac requested changes

2019-09-04 15:53 UTC, mihaimaruseac commented on third_party/repo.bzl
>  # Runs 'git apply' on Unix, 'patch -p1' on Windows.
Please also edit this comment.

2019-09-06 07:08 UTC, grwlf commented on third_party/repo.bzl
>  # Runs 'git apply' on Unix, 'patch -p1' on Windows.
Done

2019-09-06 15:47 UTC, mihaimaruseac approved these changes

2019-09-06 18:41 UTC, merged