Some XLA utility function in hlo_creation_utils
tensorflow/tensorflow pull request #32264
Opened 2019-09-05 21:49 UTC by nouiz

A split from: https://github.com/tensorflow/tensorflow/pull/32251

2019-09-05 22:15 UTC, cheshire commented on tensorflow/compiler/xla/service/hlo_creation_utils.h
> +// Creates an Iota HLO instruction
Dot after sentence

2019-09-05 22:15 UTC, cheshire commented on tensorflow/compiler/xla/service/hlo_creation_utils.h
> +// Create a BitcastConvert HLO instruction.
Creates

2019-09-05 22:15 UTC, cheshire requested changes
Two minor changes, LGTM otherwise.

2019-09-06 12:09 UTC, nouiz commented
Fixed.

2019-09-06 14:18 UTC, cheshire approved these changes

2019-09-09 13:04 UTC, nouiz commented
Any idea what is going on with the 'Ubuntu CC' CI? It didn't run in 3 days.

2019-09-09 18:14 UTC, cheshire commented
This change got imported, I need to make sure it runs locally before it will get committed. I think external bots are fine with this PR.

2019-09-09 23:30 UTC, merged