[ROCm] enumerate ROCm GPU devices in grappler.
tensorflow/tensorflow pull request #32389
Opened 2019-09-10 19:38 UTC by whchung

Co-authored with @jeffdaily .

Enable enumerating ROCm GPU devices constructing grappler clusters.

2019-11-19 23:17 UTC, rthadur commented
@jaingaurav gentle ping for review

2019-11-19 23:36 UTC, jaingaurav requested changes

2019-11-19 23:36 UTC, jaingaurav commented on tensorflow/core/grappler/devices.cc
> +#if GOOGLE_CUDA || TENSORFLOW_USE_ROCM
Using ifdef's in the code doesn't seem right here. Can we just have 3 separate files? device_default.cc, device_cuda.cc & device_rocm.cc and fix the build rules to include the correct one?

2019-11-19 23:36 UTC, jaingaurav commented on tensorflow/core/grappler/devices.h
> +    const GpuVersion& min_gpu_version = std::pair<int, int>(0, 0)
Same comment goes here. I don't think we should have preprocessor macros that change the function signature. This should be broken out into different files.

2019-12-05 10:33 UTC, gbaned commented
@whchung  Could you please check reviewer comments and keep us posted. Thanks!

2019-12-18 20:07 UTC, whchung commented
Closing this PR as from empirical testing it doesn't bring merits.

2019-12-18 20:07 UTC, closed without merging