Handle the case where axis is a tuple.
tensorflow/tensorflow pull request #32463
Opened 2019-09-12 12:35 UTC by HarikrishnanBalagopal

Previously the code only handled ints and lists as axis. Gave an error `TypeError: 'tuple' object does not support item assignment` when giving tuple as axis argument. See this issue https://github.com/tensorflow/tensorflow/issues/32311

2019-09-13 10:58 UTC, robieta approved these changes
LGTM

2019-09-13 12:59 UTC, robieta requested changes
input_shape includes the batch dim. Can you change it to `(2, 8, 8, 3)`?

2019-09-16 12:16 UTC, HarikrishnanBalagopal commented
@robieta Sorry for the late response. I made the change to (2, 8, 8, 3).

2019-09-16 16:02 UTC, robieta approved these changes

2019-09-16 21:15 UTC, merged