[Intel MKL] Supporting MatMul, Transpose and Softmax with BFloat16 type
tensorflow/tensorflow pull request #32508
Opened 2019-09-13 19:24 UTC by nhasabni

This PR enables _MklMatMul, _MklTranspose and _MklSoftmax with BFloat16 type.
Some of the changes are suggested by Clang format checker.

2019-09-18 18:12 UTC, penpornk requested changes
Thank you for your PR! I have minor comments.

2019-09-18 18:12 UTC, penpornk commented on tensorflow/core/kernels/mkl_matmul_op.cc
> +// MKLDNN only supports SGEMM
```suggestion
// MKL-DNN only supports SGEMM and bfloat16-GEMM.
```

2019-09-18 18:12 UTC, penpornk commented on tensorflow/core/kernels/mkl_matmul_op.cc
> +    int index_transa = transa ? 1 : 0;
Let's make `index_transa` and `index_transb` `const int`.

2019-09-18 18:12 UTC, penpornk commented on tensorflow/core/kernels/mkl_matmul_op.cc
> +    // MKL DNN only supports the Fortran api and requires column major while
```suggestion
    // MKL-DNN only supports the Fortran API and requires column major while
```

2019-09-18 18:12 UTC, penpornk commented on tensorflow/core/kernels/mkl_matmul_op.cc
> +    // Tensorflow uses row major so we reverse the order A and B
```suggestion
    // Tensorflow uses row major so we reverse the order of A and B.
```

2019-09-18 19:08 UTC, nhasabni commented
hi @penpornk, thanks for review. I have addressed your points. Pls take a look.

2019-09-19 18:25 UTC, penpornk approved these changes
Thank you for the quick fixes!

2019-09-19 18:34 UTC, nhasabni commented
Thank you a quick review @penpornk!

2019-09-19 23:22 UTC, merged