Add CPU BatchNormalization for NCHW format
tensorflow/tensorflow pull request #32567
Opened 2019-09-16 22:49 UTC by houtoms

Previously, CPU doesn't support NCHW. This makes other operations based on NCHW batch norm hard to use. For example, the layer norm can be transformed to use NCHW batch norm on GPU. However, since we don't have CPU NCHW batch norm, we have to either avoid using NCHW batch norm or add more parameters to control the execution path.

This PR enables NCHW batch norm on CPU.

fyi. @nluehr

2019-09-16 22:50 UTC, houtoms commented
This PR is originally served for https://github.com/tensorflow/tensorflow/pull/31557.

@reedwm

2019-09-16 23:55 UTC, reedwm requested changes

2019-09-16 23:55 UTC, reedwm commented on tensorflow/core/kernels/fused_batch_norm_op.cc
> +			OP_REQUIRES_OK(context, context->allocate_temp(
Please use spaces over tabs. And same for other parts of the file.

2019-09-16 23:55 UTC, reedwm commented on tensorflow/python/ops/nn_fused_batchnorm_test.py
> +      self._test_inference(
For consistency with the GPU case, you should put the NCHW case first. And same for some of the test cases below

2019-09-16 23:55 UTC, reedwm commented on tensorflow/python/ops/nn_fused_batchnorm_test.py
>    def testTrainingShape2(self):
Can you add a CPU test to the testTrainingShape3 and testBatchNormGradShape3 functions?

2019-09-17 00:27 UTC, houtoms commented
Done. Please check.

2019-09-17 01:09 UTC, reedwm approved these changes

2019-09-18 17:51 UTC, merged