[XLA] Add DiagSlice HLO instruction
tensorflow/tensorflow pull request #32590
Opened 2019-09-17 13:42 UTC by xinan-jiang

There is the purpose of the new HLO instruction:
Generate more efficient kernel for DiagPart and MatrixDiagPart. For example:
`
  %iota.3 = s32[1024,1024]{1,0} iota(), iota_dimension=0
  %iota.2 = s32[1024,1024]{1,0} iota(), iota_dimension=1,
  %compare.0 = pred[1024,1024]{1,0} compare(s32[1024,1024]{1,0} %iota.3, s32[1024,1024]{1,0} %iota.2), direction=EQ
  %param_0.3 = f32[1024,1024]{1,0} parameter(0)
  %constant_0 = f32[] constant(0)
  %broadcast.0 = f32[1024,1024]{1,0} broadcast(f32[] %constant_0), dimensions={}
  %select.0 = f32[1024,1024]{1,0} select(pred[1024,1024]{1,0} %compare.0, f32[1024,1024]{1,0} %param_0.3, f32[1024,1024]{1,0} %broadcast.0)
  ROOT %reduce.0 = f32[1024]{0} reduce(f32[1024,1024]{1,0} %select.0, f32[] %constant_0), dimensions={0}, to_apply=%add_F32.17
`
Here is the hlo code for tf.diag_part(X), where X is tensor with shape 1024x1024. the generated kernel's launch dimension is 1024x1024, and it has 'compare' and 'select' operation to get the right index to output. and the more expensive operation 'reduce' to get the right value to output. The kernel is less efficient for diag-part op. Actually it just need 1024 threads to get the right value from the diag part of the source matrix  which just determined by offset.

2019-09-17 15:42 UTC, blakehechtman commented
Do you have an example where the 1024x1024 kernel launch was not already the result of another operations where the select and reduce could not be fused into the previous operation?

Either way this should be split into two parts.
1. Add the Hlo and make an evaluator implementation and move the expander into an Hlo pass.
2. Add the implementation for the CPU/GPU backends.

2019-09-17 17:28 UTC, sanjoy commented
Can we make this a generic optimization that works as a lowering strategy for fused reductions?  For instance can we recognize this kind of access pattern and use a smarter elemental lowering for the fused kernel?

/CC @bixia1

2019-09-18 01:13 UTC, xinan-jiang commented
@blakehechtman The current implementation could be fused into the previous operations. However, it is hard to be fused into the following operations because of reduction. In this PR, the diag-part is lowing to a slice. The slice operation is more easy to be fused into previous operations and following operations.
@sanjoy It's a good question, but I have no idea now. I think 'slice' is a more straight expression of diag-part than 'reduce'.

2019-09-18 12:26 UTC, xinan-jiang commented
> Can we make this a generic optimization that works as a lowering strategy for fused reductions? For instance can we recognize this kind of access pattern and use a smarter elemental lowering for the fused kernel?

I think the diag-part is basically an index transformation as transpose, slice and reshape. Should we design a 'shuffle' instruction with a nested computation which describes the index transformation for general index transformation situation?

2019-09-19 14:46 UTC, sanjoy commented
> I think the diag-part is basically an index transformation as 'transpose', 'slice' and 'reshape'. Should we design a 'shuffle' instruction with a nested computation which describes the index transformation for general index transformation situation?

Sorry I responded without fully understanding the IR snippet.

The IR snippet looks like it should be easily representable as a gather_nd with an iota index?  At least on CPU/GPU the iota index should fuse into the gather and the gather should further fuse into its users.

I agree using a reduction this was seems odd.

2019-09-26 23:41 UTC, bixia1 reviewed
I will need more time to understand the implementation. At the same time, are you able to add some comment to the code to help? 
In terms of the testing, beside matrix_test.cc, what else you have tested? I think matrix_test.cc only test input with shape(2, 3, 4).

2019-09-26 23:41 UTC, bixia1 commented on tensorflow/compiler/xla/client/lib/matrix.cc
> +    XlaOp k_offset = ConcatInDim(builder, { row_offset, col_offset }, 1);
What does "k" in "k_offset" mean?

2019-09-30 15:45 UTC, bixia1 reviewed
Looks good to me, thank you for working on this!

2019-09-30 15:45 UTC, bixia1 commented on tensorflow/compiler/xla/client/lib/matrix.cc
> +    // The dimensions [0, axis) are batch dimensions.
Can you add description like this to here and move the example below to right after this description?
The start_indices has a shape of {diag_len, 2}, and each pair of value in its dimension 1 represents the (row, col) of the diagonal. We set index_vector_dim to 1 and make start_index_map and collapsed_slice_dims contain the same two dimension indices. This makes sure that the (row, col) pairs in start_indices are propagated to the indices for the two collapsed dimensions in the operand indices through start_index_map.

2019-09-30 15:45 UTC, bixia1 commented on tensorflow/compiler/xla/client/lib/matrix.cc
> +    return Gather(x, start_indices, dim_numbers, slice_sizes, true);
Explain true, such as:  /* indices_are_sorted= */ true

2019-09-30 15:45 UTC, bixia1 commented on tensorflow/compiler/xla/client/lib/matrix_test.cc
> +template <typename T>
Thank you for adding the tests!

2019-09-30 15:45 UTC, bixia1 commented on tensorflow/compiler/xla/tests/client_library_test_base.h
> +  // Creates a parameter instruction that wraps the given constant array
I understand the you copied the comment from the routine above, but I would suggest to change it to:
  Creates a parameter instruction that wraps the given constant array
  "array_4d" and then stores it to  the global handle for that parameter "data_handle".

2019-09-30 16:43 UTC, bixia1 submitted a review, later dismissed

2019-09-30 18:31 UTC, bixia1 submitted a review, later dismissed

2019-10-02 07:37 UTC, xinan-jiang commented
squash the commits that resolve conflicts.

2019-10-02 15:03 UTC, bixia1 approved these changes

2019-10-03 16:13 UTC, bixia1 requested changes
Hi, I got some feedback for this change from google internal. We want to keep the original implementation for some platforms, such as non-cpu and non-gpu platforms. Similar to the idea of having ArgMin and ArgMinTwoPass in file tensorflow/compiler/xla/client/lib/arithmetic.h, can we have GetMatrixDiagonal and GetMatrixDiagonalViaGather? You may want to mimic how ArgMinTwoPass is used in third_party/tensorflow/compiler/tf2xla for this.

2019-10-04 18:04 UTC, bixia1 approved these changes

2019-10-07 03:54 UTC, bixia1 requested changes
The following two tests fail, the failing tests are related to zero size tensor.
//third_party/tensorflow/python/kernel_tests:diag_op_test_xla_gpu	FAILED
 //third_party/tensorflow/contrib/distributions:matrix_inverse_tril_test_xla_gpu	FAILED

2019-10-14 15:44 UTC, bixia1 approved these changes

2019-10-14 22:54 UTC, merged