[XLA:GPU][ROCm] Enabling amdgpu backend in XLA unit tests
tensorflow/tensorflow pull request #32673
Opened 2019-09-19 21:10 UTC by jerryyin

This PR enables amdgpu XLA backend for unit tests, in preparation for setting up ROCm XLA community support builds.

2019-09-20 15:45 UTC, cheshire commented on tensorflow/compiler/xla/tests/build_defs.bzl
>      if cuda_is_configured():
`cuda_is_configured() or rocm_is_configured()`?

2019-09-20 15:45 UTC, cheshire commented on tensorflow/compiler/xla/tests/build_defs.bzl
> +    """Removes "gpu" from a backend list if Cuda or Rocm is not enabled.
CUDA

2019-09-20 15:45 UTC, cheshire requested changes
LGTM apart from minor nits

2019-09-20 16:21 UTC, cheshire approved these changes

2019-09-23 10:30 UTC, gbaned commented
@jerryyin Could you please check failed build errors? Thanks!

2019-09-23 14:21 UTC, jerryyin commented
@gbaned Judging from the build failures: `external/local_config_mlir/include/mlir/Dialect/QuantOps/UniformSupport.h:148:14: error: 'clamp' is not a member of 'std'`

I don't think the failures have anything to do with this PR. `std::clamp` is a C++ 17 addition and shouldn't be used in that header file.

2019-10-03 19:15 UTC, merged