Support the 3D convolution ops for auto_mixed_precision
tensorflow/tensorflow pull request #32850
Opened 2019-09-26 22:37 UTC by houtoms

Previous TF auto_mixed_precision doesn't support 3D convolutions.

Since the cuDNN enhanced the performance of 3D convolutions since v7.6.2 (https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_762.html#rel_762), this PR added the support and related tests.

fyi @nluehr @benbarsdell

2019-10-03 01:48 UTC, reedwm requested changes

2019-10-03 01:48 UTC, reedwm commented on tensorflow/python/grappler/auto_mixed_precision_test.py
> +    with compat.forward_compatibility_horizon(2019, 6, 7):
This compat line isn't necessary, as it's already past 2019-06-07

2019-10-03 01:48 UTC, reedwm commented on tensorflow/python/grappler/auto_mixed_precision_test.py
> +  def test_conv3d_bn(self):
This test will fail in the GitHub tests, as they don't yet run with cuDNN 7.6.2.

You can delete them or disable them with [`@unittest.skip`](https://docs.python.org/2/library/unittest.html#skipping-tests-and-expected-failures). Or you can wait until we start running with cuDNN >= 7.6.2.

2019-10-11 10:47 UTC, gbaned commented
@houtoms Could you please check reviewer comments and keep us posted. Thanks!

2019-10-14 16:26 UTC, houtoms commented
Sure, working on it.

2019-10-14 16:52 UTC, houtoms commented
Thx, I've made the changes.

2019-10-14 18:27 UTC, reedwm submitted a review, later dismissed

2019-10-14 23:43 UTC, reedwm commented
Please fix the failing tests. Looks like you need to import `unittest`.

2019-10-14 23:56 UTC, reedwm approved these changes

2019-10-15 03:59 UTC, merged