Update commands to look for keyword controller in lspci log
tensorflow/tensorflow pull request #32882
Opened 2019-09-27 17:57 UTC by sunway513

Some GPU SKUs changed the lspci reading in ROCm2.8. 
By looking for the keyword "controller" we would be able to cover all, hence this change in ROCm unit test script would ensure better coverage on AMD GPU coverage. 
cc @whchung @parallelo

2019-09-27 18:08 UTC, whchung approved these changes

2019-10-01 16:01 UTC, Ishaan28malik requested changes
LGTM

2019-10-07 03:39 UTC, sunway513 commented
> Not agreed

Hi @Ishaan28malik , can you help elaborate your concern? 
This change is specific to ROCm unit test script.

2019-10-07 11:04 UTC, Ishaan28malik commented
@sunway513 looks good to me, I have seen it thoroughly now.

2019-10-07 15:29 UTC, sunway513 commented
Thank you @Ishaan28malik.
The Ci failure in Android Demo App seems not related to the PR. @whchung @christisg what's the next step for this PR?

2019-10-07 17:52 UTC, chsigg approved these changes

2019-10-10 18:02 UTC, chsigg commented
I will try to get it merged manually.

2019-10-11 13:55 UTC, merged