reverting bias cache optimization
tensorflow/tensorflow pull request #32922
Opened 2019-09-30 17:19 UTC by Srini511

Reverting bias cache optimization because of some internal failures

2019-10-01 23:04 UTC, penpornk requested changes
Thank you for the PR!

2019-10-01 23:04 UTC, penpornk commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +      // TODO Disabling bias caching for now. The graph obtained after
Nit: Please add one blank line to separate this from the normal comment above.
Nit: TODO should be an action item. Maybe rephrase it?
```c++
// TODO(intel-tf): Re-enable bias caching. Currently, the graph obtained 
// after quantize_graph.py does not run with correct accuracy with this 
// feature enabled.
```

2019-10-02 17:39 UTC, penpornk commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +
Nit: Please remove this blank line. I don't think we need this extra space between comment and code. (I only needed the blank line in line 1588 but not 1592.) Sorry about the nit!

2019-10-02 18:33 UTC, Srini511 commented
@penpornk please take a look

2019-10-02 21:05 UTC, penpornk requested changes
Thanks so much for your patience!

2019-10-02 21:07 UTC, Srini511 commented
Hi @penpornk , i think i have made the changes requested. :-)

2019-10-02 22:55 UTC, penpornk approved these changes
Oops, sorry! I meant to click approve. :)

2019-10-03 04:59 UTC, merged