Fix tf.assert_equal issue when one tenor is empty and another is non-empty
tensorflow/tensorflow pull request #33066
Opened 2019-10-05 07:36 UTC by yongtang

This fix tries to address the issue raised in #32082 where tf.assert_equal([], [1.0]) doesn't raise error.
The reason was that in assert_equal `[1.0]` was broadcasted as `[]` and equal was in place in that situation.

This PR updates the _binary_asesert so that it will check if x, y are both empty or both non-empty. If one is empty and another is non-empty, then assertion throws exception. This change is to not impact other ops that depends on the broadcast behavior.

This fix fixes #32082.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2019-10-07 16:23 UTC, alextp submitted a review, later dismissed

2019-10-08 15:47 UTC, alextp approved these changes

2019-10-16 04:17 UTC, gbaned requested changes

2019-10-16 04:17 UTC, gbaned commented on tensorflow/python/ops/check_ops.py
> +              static_func(x_static, y_static))
`InvalidArgumentError: assertion failed: [`Tensor(\"Placeholder:0\", dtype=int32)` elements must be either positive integers or `-1`.] [Condition x >= y did not hold element-wise:] [x (Placeholder:0) = ] [] [y (reshape/assert_greater_equal/y:0) = ] [-1]
	 [[node reshape/assert_greater_equal/Assert/Assert (defined at /tensorflow/contrib/distributions/python/kernel_tests/bijectors/reshape_test.py:111) ]]

Errors may have originated from an input operation.
Input Source operations connected to node reshape/assert_greater_equal/Assert/Assert:
```suggestion
              static_func(x_static, y_static))` 
We can see the above internal error, can please fix it.

2019-11-08 12:35 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-11-08 14:45 UTC, yongtang commented
@alextp @gbaned 

I take a look at the internal testing error:
```
InvalidArgumentError: assertion failed: [Tensor("Placeholder:0", dtype=int32)elements must be either positive integers or-1`.] [Condition x >= y did not hold element-wise:] [x (Placeholder:0) = ] [] [y (reshape/assert_greater_equal/y:0) = ] [-1]
[[node reshape/assert_greater_equal/Assert/Assert (defined at /tensorflow/contrib/distributions/python/kernel_tests/bijectors/reshape_test.py:111) ]]

Errors may have originated from an input operation.
Input Source operations connected to node reshape/assert_greater_equal/Assert/Assert:
```

However, It is pointing to `tensorflow/contrib/distributions/python/kernel_tests/bijectors/reshape_test.py:111`

which does not exist anymore in master branch, because  tf.contrib has been deleted.

I am wondering if any additional information is available about how this internal test is being performed?

If you can point me to the location of the source file that I could see I think I could quickly fix it.

2019-11-15 21:53 UTC, merged