add PLATFORM_WINDOWS to stream_executor\platform\platform.h
tensorflow/tensorflow pull request #33114
Opened 2019-10-07 16:37 UTC by fo40225

add PLATFORM_WINDOWS to stream_executor\platform\platform.h

2019-10-07 17:51 UTC, sanjoy requested changes
I don't understand this change.  The description says "add PLATFORM_WINDOWS to stream_executor\platform\platform.h" but the actual change only changes hlo_evaluator.h in an unrelated manner?

2019-10-16 03:22 UTC, fo40225 commented
PLATFORM_WINDOWS already added to stream_executor\platform\platform.h on Aug 28, 2019 but not in v2.0.0.

2019-10-16 19:13 UTC, sanjoy commented
> PLATFORM_WINDOWS already added to stream_executor\platform\platform.h on Aug 28, 2019 but not in v2.0.0.
> 
> This PR will fix the problem of the file `tensorflow/compiler/xla/service/hlo_evaluator.cc` didn't define `M_PI`.

Can you please change the PR description to say this?

2019-10-18 17:01 UTC, sanjoy commented
> Can you please change the PR description to say this?

The PR description should also include _why_ you're defining _USE_MATH_DEFINES in hlo_evaluator.cc.

2019-10-25 23:10 UTC, sanjoy approved these changes

2019-10-28 23:40 UTC, merged