Fix the issue for importing googletest.h
tensorflow/tensorflow pull request #33123
Opened 2019-10-07 21:57 UTC by feihugis

This PR removes `#include "testing/base/public/googletest.h"` in the `input_generator_test` and `util_test` so that these test can also run on the local environment. Otherwise, there will be an error below:

```
ERROR: /home/abc/tensorflow/tensorflow/lite/testing/kernel_test/BUILD:33:1: C++ compilation of rule '//tensorflow/lite/testing/kernel_test:util_test' failed (Exit 1)
tensorflow/lite/testing/kernel_test/util_test.cc:21:10: fatal error: testing/base/public/googletest.h: No such file or directory
 #include "testing/base/public/googletest.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/lite/testing/kernel_test:util_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
``` 

Fixes #26671

2019-10-07 22:22 UTC, mihaimaruseac requested changes
Please don't reformat files which are not related to the change

2019-10-07 23:14 UTC, feihugis commented
> Please don't reformat files which are not related to the change

The format changes are removed now.

2019-10-08 16:03 UTC, jdduke approved these changes

2019-10-08 16:41 UTC, mihaimaruseac approved these changes

2019-10-17 03:34 UTC, feihugis commented
As this issue has been fixed by @nairb774 via (https://github.com/tensorflow/tensorflow/commit/1c88fff548acb048f2fe64fd2564e885759def12, https://github.com/tensorflow/tensorflow/commit/c9c0e70d0b1d6d4fd618c5ebdebd859dbe59848f,  https://github.com/tensorflow/tensorflow/commit/db5816707ab0fc4ae6d3959a313d67dd871a8d9d), I will close this PR. Thanks for your fix, @nairb774 !

2019-10-17 03:34 UTC, closed without merging

2019-10-17 21:19 UTC, nairb774 commented
Hey @feihugis, sorry about the conflict. I didn't know this was out there - I'm new to the project. I stumbled onto the build problem because I am trying to improve the state of the build/test health. There seem to be a number of things that are excluded from testing coverage which don't seem to need to be. I'm hoping that I can work through the broken code/issues and get more of this under CI so we have less of this broken code floating around.

Sorry :(

2019-10-18 05:36 UTC, feihugis commented
No worries, @nairb774! Your fixes are great.