Fix SIGABRT on `tf.image.encode_png` with empty tensor
tensorflow/tensorflow pull request #33220
Opened 2019-10-10 19:31 UTC by yongtang

This fix address the issue raised in #31429 where SIGABRT was thrown on `tf.image.encode_png` with empty tensor.

Instead of thrown out SIGABRT, this fix adds the error checking so that InvalidArgument was returned gracefully.

This fix fixes #31429

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2019-10-10 20:06 UTC, mihaimaruseac submitted a review, later dismissed
Thank you for these fixes. I was waiting for the external contributor to fix but it seems they gave up and then I forgot to check again.

2019-10-25 18:05 UTC, rthadur requested changes

2019-10-25 18:05 UTC, rthadur commented on tensorflow/python/ops/image_ops_test.py
> +
`File "/third_party/py/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "third_party/py/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "third_party/tensorflow/python/ops/image_ops_test.py", line 4082, in testEmptyTensor
    png = image_ops.encode_png(image)
  File "<embedded stdlib>/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "third_party/tensorflow/python/framework/test_util.py", line 2808, in assertRaisesWithPredicateMatch
    (str(type(e)), str(e)))
AssertionError: Exception of type <type 'exceptions.AssertionError'>: OpError not raised`

2019-10-25 18:05 UTC, rthadur commented on tensorflow/python/ops/image_ops_test.py
> +
@yongtang can you please fix above error ?

2019-12-20 12:32 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2019-12-20 19:43 UTC, yongtang commented
@rthadur sorry for the late reply. The email notification before slip through. I have rebased and update the PR. Can you give it a try and see if the issue still exist?

2019-12-20 21:09 UTC, mihaimaruseac approved these changes

2020-01-02 18:58 UTC, rthadur requested changes

2020-01-02 18:58 UTC, rthadur commented on tensorflow/python/ops/image_ops_test.py
> +        png = image_ops.encode_png(image)
Hi @yongtang 
Failing with similar error internally , can you please check once,
`Traceback (most recent call last):
  /unittest/case.py", line 59, in testPartExecutor
    yield
  /unittest/case.py", line 605, in run
    testMethod()
  File "/google3/runfiles/google3/third_party/tensorflow/python/ops/image_ops_test.py", line 4079, in testEmptyTensor
    png = image_ops.encode_png(image)
  File "contextlib.py", line 88, in __exit__
    next(self.gen)
  File "google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 2819, in assertRaisesWithPredicateMatch
    (str(type(e)), str(e)))
AssertionError: Exception of type <class 'AssertionError'>: OpError not raised`

2020-01-13 14:55 UTC, yongtang commented
@rthadur Sorry for the late reply as I was mostly out of office year end (was back last week). I will take a look at the errors shortly.

2020-01-22 19:05 UTC, yongtang commented
@mihaimaruseac I had been trying to find where the test failure is from, but couldn't figure out from the traceback error message. I tried to search the source tree but could not find `testPartExecutor` that showed up in error message.

I guess this test might from some previous version setup? Could it be that test was from an old version of TF setup (like 1.14 or earlier) against master 2.1?

Wondering if you have any clue about the background information with the test error?

```
Traceback (most recent call last): 

/unittest/case.py", line 59, 

in testPartExecutor yield /unittest/case.py", line 605, 

in run testMethod() File "/google3/runfiles/google3/third_party/tensorflow/python/ops/image_ops_test.py", line 4079,

in testEmptyTensor png = image_ops.encode_png(image) File "contextlib.py", line 88, 

in __exit__ next(self.gen) File "google3/runfiles/google3/third_party/tensorflow/python/framework/test_util.py", line 2819,

in assertRaisesWithPredicateMatch (str(type(e)), str(e))) AssertionError: Exception of type <class 'AssertionError'>: OpError not raised
```

2020-01-22 23:33 UTC, mihaimaruseac commented
I will have to look into this. I'll update the PR over the weekend. Sorry for the delay

2020-01-23 21:09 UTC, yongtang commented
Thanks @mihaimaruseac 👍 , let me know if there is anything I can help.

2020-01-23 23:57 UTC, mihaimaruseac commented on tensorflow/python/ops/image_ops_test.py
> +        png = image_ops.encode_png(image)
So, I tested internally and the error doesn't seem to be raised always, that's why the test fails (in 1 / 4 attempts).

2020-02-05 11:00 UTC, gbaned commented
@yongtang Can you please check mihaimaruseac's comments and keep us posted? Thanks!

2020-02-21 18:50 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-03-17 12:01 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-03-17 12:01 UTC, closed without merging