[INTEL MKL] Reimplement CompareMklDnnLayouts
tensorflow/tensorflow pull request #33404
Opened 2019-10-16 04:14 UTC by ShengYang1

The implementation of `CompareMklDnnLayouts` in mkl_util.h was not correct. The code compared `mkldnn_memory_desc_t` by bytes and didn't exclude the garbage values, which causing the comparison always failing thus unnecessary reorders were executed. We reimplement the function by comparing class members one by one.

2019-10-18 05:46 UTC, penpornk requested changes
Thank you for the PR! Just curious, why does the struct has garbage in the first place?

2019-10-18 05:46 UTC, penpornk commented on tensorflow/core/util/mkl_util.h
> +    bool base_equal = true && mdd1.ndims == mdd2.ndims &&
Nit: We don't need `true`.
```suggestion
    bool base_equal = mdd1.ndims == mdd2.ndims &&
```

2019-10-18 09:12 UTC, ShengYang1 commented
> Thank you for the PR! Just curious, why does the struct has garbage in the first place?

For example, `dims` field in `mkldnn_memory_desc_t` is a C array with size 12. Most of the time, only the first four values are used and the rest are uninitialized. So we couldn't compare it by bytes.

2019-10-18 09:16 UTC, ShengYang1 commented on tensorflow/core/util/mkl_util.h
> +    bool base_equal = true && mdd1.ndims == mdd2.ndims &&
Done

2019-11-11 00:39 UTC, ShengYang1 commented
Any updates?

2019-11-11 18:14 UTC, penpornk approved these changes
I'm so sorry for the delay! Thank you again for the PR!

2019-11-11 18:15 UTC, penpornk commented
> > Thank you for the PR! Just curious, why does the struct has garbage in the first place?
> 
> For example, `dims` field in `mkldnn_memory_desc_t` is a C array with size 12. Most of the time, only the first four values are used and the rest are uninitialized. So we couldn't compare it by bytes.

Thanks for the explanation as well! :)

2019-11-12 20:08 UTC, merged