fixing documentation for tf.batch_to_space
tensorflow/tensorflow pull request #33481
Opened 2019-10-17 18:51 UTC by vishalsubbiah

issue #33354
each step is not separated correctly : https://www.tensorflow.org/api_docs/python/tf/batch_to_space

replacing #33351

2019-10-17 18:52 UTC, vishalsubbiah commented
cc @mihaimaruseac

2019-10-17 21:00 UTC, mihaimaruseac submitted a review, later dismissed
Might need to run lint on the code to check formatting, but looks good

2019-10-18 15:44 UTC, mihaimaruseac submitted a review, later dismissed

2019-10-29 18:04 UTC, vishalsubbiah commented
@rthadur can i redo a certain check? the error for Ubuntu Sanity is 
```
ERROR: /tmpfs/src/github/tensorflow/tensorflow/tools/ci_build/BUILD:3:1:  failed: No usable spawn strategy found for spawn with mnemonic TestRunner.  Your --spawn_strategy, --genrule_strategy or --strategy flags are probably too strict. Visit https://github.com/bazelbuild/bazel/issues/7480 for migration advice
```
This shouldn't be because of my change

2019-10-29 21:02 UTC, rthadur requested changes

2019-10-29 21:02 UTC, rthadur commented on tensorflow/python/ops/array_ops.py
> +      4. Crop the start and end of dimensions `[1, ..., M]` of `reshaped_permuted`
`FAIL: Found 1 non-whitelisted pylint errors:
tensorflow/python/ops/array_ops.py:3445: [C0301(line-too-long), ] Line too long (82/80)`
can you please fix this sanity error

2019-10-29 22:08 UTC, rthadur approved these changes

2019-10-30 06:25 UTC, merged