Update README.md
tensorflow/tensorflow pull request #33579
Opened 2019-10-21 17:50 UTC by Samsomyajit

This update is requested in reference to the issue #33552 
[Under the heading "Obtain and Import the Library", the link incorrectly refers to the micro_speech.zip package instead of a person_detection example.]
So I updated the "Obtain and Import the Library" section on  the micro_speech.zip [now: person_detection_example.zip].

2019-10-21 21:23 UTC, rthadur commented
please combine #33582 with this PR

2019-10-22 04:05 UTC, Samsomyajit commented
in reference to issue #33552 .... Just like the person detection .zip name in the magic-wand documentation the same problem is present.

2019-10-22 04:23 UTC, Samsomyajit commented
@rthadur would you please check this out: when I click on the person_detection.zip link after update this pops out:

`
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error nighteye="disabled">
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: tensorflow-nightly/github/tensorflow/tensorflow/lite/experimental/micro/tools/make/gen/arduino_x86_64/prj/person_detection/person_detection.zip
</Details>
</Error>
`

2019-10-22 04:25 UTC, Samsomyajit commented
@rthadur Why close #33582 ? The magic_wand has the same problem as person_detection in README.md

2019-10-22 17:33 UTC, Samsomyajit commented
@rthadur Please check the update made to the README.md and tell me if its fine now

2019-10-22 20:57 UTC, mihaimaruseac commented
This should include the changes from #33582?

2019-10-23 05:21 UTC, adisakshya reviewed
Yes, the link for ```person_detection``` is fixed. Also the```magic-wand``` documentation needs this same fix as #33582 suggests. You can include the changes from #33582 here in #33579.

2019-10-23 05:42 UTC, Samsomyajit commented
> Yes, the link for `person_detection` is fixed. Also the`magic-wand` documentation needs this same fix as #33582 suggests. You can include the changes from #33582 here in #33579.

I have added the magic_wand.zip issue just like the person_detection as requested....

2019-10-23 15:56 UTC, mihaimaruseac requested changes

2019-10-23 15:56 UTC, mihaimaruseac commented on tensorflow/lite/experimental/micro/examples/magic_wand/README.md
> +> Yes, the link for `person_detection` is fixed. Also the`magic-wand` documentation needs this same fix as #33582 suggests. You can include the changes from #33582 here in #33579.
Please remove this line

2019-10-23 16:56 UTC, Samsomyajit commented
@mihaimaruseac PLease check the updated README.md the rquested line is removed.

2019-10-23 18:17 UTC, mihaimaruseac submitted a review, later dismissed

2019-10-28 14:16 UTC, mihaimaruseac requested changes

2019-10-28 14:16 UTC, mihaimaruseac commented on tensorflow/lite/experimental/micro/examples/magic_wand/README.md
> +
Remove this additional empty line

2019-10-28 14:16 UTC, mihaimaruseac commented on tensorflow/lite/experimental/micro/examples/magic_wand/README.md
> +
Remove this additional empty line

2019-10-28 14:16 UTC, mihaimaruseac commented on tensorflow/lite/experimental/micro/examples/person_detection/README.md
> +
Remove this additional empty line

2019-10-28 14:16 UTC, mihaimaruseac commented on tensorflow/lite/experimental/micro/examples/person_detection/README.md
> +
Remove this additional empty line

2019-11-07 19:31 UTC, Samsomyajit commented on tensorflow/lite/experimental/micro/examples/magic_wand/README.md
> +
Plz check! I made the necessary changes

2019-11-08 16:36 UTC, mihaimaruseac requested changes

2019-11-08 16:36 UTC, mihaimaruseac commented on tensorflow/lite/experimental/micro/examples/magic_wand/README.md
> +Include Library -> Add .ZIP Library...`.
`Sketch -> ..` should all be on a single line.

2019-11-08 20:36 UTC, mihaimaruseac approved these changes

2019-11-11 21:14 UTC, merged

2019-11-21 03:57 UTC, Shusuke-O commented
Hello. I'm trying to check a magic wand example. But I cannot download magic_wand.zip on the README.md.