Fix behavior difference between tf.io.GFile and python file for utf8
tensorflow/tensorflow pull request #33590
Opened 2019-10-22 04:21 UTC by yongtang

This PR tries to address the issue raised in #33563 where
tf.io.GFile behavior is different from python file for utf8.

The issue was that tf.io.GFile's read does not take utf8 into
consideration for non binary mode.

This PR fixes the discrepancy.

This PR fixes #33563

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2019-10-22 16:17 UTC, mihaimaruseac requested changes

2019-10-22 16:17 UTC, mihaimaruseac commented on tensorflow/python/lib/io/file_io.i
> +  tensorflow::tstring result;
Should this be `std::string` or `tensorflow::tstring`? Afaik, `tensorflow:tstring` should be used only if the string is in a tensor. Adding @gharibian to confirm

2019-10-22 16:17 UTC, mihaimaruseac commented on tensorflow/python/lib/io/file_io.i
> +      if ((result_read[i] & 0xe0) == 0xc0) {
Let's extract the `0xe0`, `0xc0`, `0xf0` and `0xf8` magic constants to same named constants to increase readability

2019-10-22 16:17 UTC, mihaimaruseac commented on tensorflow/python/lib/io/file_io.i
> +      else if ((result_read[i] & 0xf0) == 0xe0) {
Let's write these as

```
if (...) {
  ...
} else if (...) {
  ...
} else {
  ...
}
```

2019-10-22 16:17 UTC, mihaimaruseac commented on tensorflow/python/lib/io/file_io.i
> +    // 1) read at least bytes - total
Let's move these to a comment in the header of the function, not in the `while` loop.

2021-01-13 16:00 UTC, gbaned commented
@yongtang  Can you please resolve conflicts? Thanks!

2021-01-13 18:28 UTC, yongtang commented
Thanks @mihaimaruseac @gbaned for the review and sorry for the late response as the notice slipped through. The PR has been rebased and updated and the review comment has also been addressed. Please take a look.

2021-01-14 18:54 UTC, mihaimaruseac approved these changes

2021-06-09 15:44 UTC, mihaimaruseac requested changes
This still seems to fail:

```
======================================================================
ERROR: testReadWriteNonBinaryModeUTF8 (__main__.FileIoTest)
testReadWriteNonBinaryModeUTF8 (__main__.FileIoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/lib/io/file_io_test.runfiles/org_tensorflow/tensorflow/python/lib/io/file_io_test.py", line 686, in testReadWriteNonBinaryModeUTF8
    self.assertEqual(g.read(), f.read())
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

2021-07-08 04:12 UTC, gbaned commented
@yongtang Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

2022-12-14 10:31 UTC, gbaned commented
Hi @yongtang I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! thank you for your contribution.

2022-12-14 10:31 UTC, closed without merging