Williscool
tensorflow/tensorflow pull request #33632
Opened 2019-10-23 08:56 UTC by Williscool13

Addressing issue #26211. Feedback would be greatly appreciated, and will make any revisions necessary.

2019-10-23 18:17 UTC, mihaimaruseac submitted a review, later dismissed

2019-10-24 16:14 UTC, mihaimaruseac submitted a review, later dismissed

2019-10-24 19:39 UTC, mihaimaruseac commented
```
FAIL: Found 1 non-whitelisted pylint errors:
tensorflow/python/keras/activations.py:220: [C0301(line-too-long), ] Line too long (82/80)
```

Please fix.

2019-10-25 15:33 UTC, mihaimaruseac approved these changes

2019-10-25 16:33 UTC, rthadur submitted a review, later dismissed

2019-10-25 18:50 UTC, rthadur commented
@Williscool13 can you please check this failures here https://source.cloud.google.com/results/invocations/d5139b8a-2820-46ed-8563-f604013d9fda/log

2019-10-25 19:58 UTC, mihaimaruseac commented
```
File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/keras/activations.py", line 204, in tensorflow.python.keras.activations.relu
Failed example:
    tf.keras.activaions.relu(foo, max_value=5).numpy()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest tensorflow.python.keras.activations.relu[3]>", line 1, in <module>
        tf.keras.activaions.relu(foo, max_value=5).numpy()
    AttributeError: module 'tensorflow.python.keras.api._v2.keras' has no attribute 'activaions'
```

please fix

2019-10-25 19:59 UTC, mihaimaruseac requested changes

2019-10-25 19:59 UTC, mihaimaruseac commented on tensorflow/python/keras/activations.py
> +  >>> tf.keras.activaions.relu(foo, max_value=5).numpy()
Typo, should be `activations`

2019-10-28 14:09 UTC, mihaimaruseac approved these changes

2019-10-29 01:37 UTC, merged