[INTEL MKL] Fixed MKL QuantizeV2 operator.
tensorflow/tensorflow pull request #33659
Opened 2019-10-24 01:51 UTC by mdfaijul

There has been a new attribute added to QuantizeV2 (commit id: 4a8064512ca53c). Since MKL version was not updated accordingly, all quantization models with MKLDNN have been failing. This PR updates the MKL version to adapt those changes.

This PR also contains a small fix to `tensorflow/core/graph/mkl_layout_pass.cc` that was causing an abort in debug mode.

2019-10-24 23:02 UTC, penpornk requested changes
Thank you for the PR! I have one question.

2019-10-25 00:15 UTC, mdfaijul commented on tensorflow/core/kernels/mkl_quantize_op.cc
> +        !std::is_signed<T>::value
@penpornk Thanks for your comments. I have followed Eigen library based implementation https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/quantize_op.cc#L62-L67
We are actually not using this. Better, I would remove this variable and the related statement.

2019-10-25 00:23 UTC, mdfaijul commented on tensorflow/core/kernels/mkl_quantize_op.cc
> +        !std::is_signed<T>::value
@penpornk Removed `half_range_` member variable.

2019-10-25 00:42 UTC, penpornk approved these changes
Sounds good. Thank you for the change!

2019-10-25 05:57 UTC, merged