Add unit tests for keras network get_layer.
tensorflow/tensorflow pull request #33812
Opened 2019-10-29 07:58 UTC by vcarpani

This PR adds unit tests for the method `get_layer` of a Keras `Network`.

2019-12-24 08:47 UTC, gbaned commented
@vcarpani Can you please resolve conflicts? Thanks!

2020-03-14 00:07 UTC, tanzhenyu submitted a review, later dismissed

2020-03-14 16:31 UTC, mihaimaruseac submitted a review, later dismissed

2020-03-14 16:32 UTC, mihaimaruseac commented
Can you please resolve conflicts?

2020-03-18 17:09 UTC, mihaimaruseac submitted a review, later dismissed

2020-03-20 17:11 UTC, mihaimaruseac approved these changes

2020-03-20 18:58 UTC, mihaimaruseac requested changes

2020-03-20 18:58 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network_test.py
> +    with self.assertRaises(ValueError):
From @fchollet this should check the text of the error with `assertRaisesRegexp`

2020-03-20 18:58 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network_test.py
> +    self.assertEqual(network.get_layer(index=1, name='dense_b'), dense_a)
From @fchollet:

> This makes me think we should raise an error if both arguments are passed

2020-03-24 11:25 UTC, gbaned commented
@vcarpani Can you please check @mihaimaruseac's comments and keep us posted. Thanks!

2020-03-24 11:32 UTC, vcarpani commented
Yes, thanks for the feedback; will check them, but it make take a little be longer than usual cause COVID

2020-03-27 16:20 UTC, mihaimaruseac submitted a review, later dismissed

2020-03-27 16:20 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> +    elif index is not None:
Since raising exception ends function body, there is no need for `elif`:

```suggestion

    if index is not None:
```

2020-03-27 16:20 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> +    elif name is not None:
Same here 

```suggestion

    if name is not None:
```

2020-03-30 16:12 UTC, mihaimaruseac submitted a review, later dismissed

2020-03-30 16:12 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> +      raise ValueError('Provide only a layer name or a layer index.')
Add an empty line after this please, to clearly separate the two blocks

2020-03-30 16:12 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> +    if name is not None:
Add an empty line above this please, to clearly separate the two blocks

2020-03-31 16:26 UTC, mihaimaruseac submitted a review, later dismissed

2020-03-31 18:18 UTC, mihaimaruseac commented
Sanity build failed due to pylint issue. Please make sure you download log and look for the pylint errors and fix them

2020-04-02 02:20 UTC, mihaimaruseac submitted a review, later dismissed

2020-04-02 11:54 UTC, gbaned commented
@vcarpani Can you please address Ubuntu Sanity errors? Thanks!

2020-04-02 17:49 UTC, mihaimaruseac approved these changes

2020-04-03 19:15 UTC, merged