Fixed cpu frequency retrieval and clock cycle for IBM Power systems
tensorflow/tensorflow pull request #33965
Opened 2019-11-04 10:08 UTC by npanpaliya

2019-11-12 21:00 UTC, penpornk requested changes
Thank you very much for the PR and I'm so sorry for my delay!

2019-11-20 09:52 UTC, npanpaliya commented
Thank you @penpornk for the comments and sorry for the delay as I was occupied in other tasks. I've addressed all your suggestions.

2019-11-21 21:42 UTC, penpornk requested changes
@npanpaliya No worries at all and thank you for the fixes! Would you mind making one more minor change?

2019-11-21 21:42 UTC, penpornk commented on tensorflow/core/platform/profile_utils/cpu_utils.h
> +    uint64 result=0;
Nit: `result` is not used. We can remove it. Same for line 115.

2019-11-25 17:54 UTC, penpornk approved these changes
Thank you very much again for contributing! :)

2019-11-26 01:51 UTC, merged

2019-11-27 07:45 UTC, npanpaliya commented
@penpornk Thank you for reviewing and merging this.