Update activations.py
tensorflow/tensorflow pull request #34079
Opened 2019-11-07 19:50 UTC by darsh8200

All spelling corrected in the documentation of the code.

2019-11-07 19:53 UTC, darsh8200 commented
@googlebot I signed it!

2019-11-08 16:40 UTC, mihaimaruseac requested changes

2019-11-08 16:40 UTC, mihaimaruseac commented on tensorflow/python/keras/activations.py
> +  https://cdn-images-1.medium.com/max/1600/1*m0e8lZU_Zrkh4ESfQkY2Pw.png
Don't remove the markdown markers here. They are useful to make the image show up as an image on the documentation page

2019-11-08 16:40 UTC, mihaimaruseac commented on tensorflow/python/keras/activations.py
> +      Tensorflow Activation function denoted by input string.
Capital `F` please

2019-11-13 06:32 UTC, darsh8200 commented on tensorflow/python/keras/activations.py
> +      Tensorflow Activation function denoted by input string.
Done and commited the changes.

2019-11-13 15:37 UTC, rthadur approved these changes

2019-11-13 16:36 UTC, mihaimaruseac approved these changes

2019-11-15 18:37 UTC, merged