Move TensorRT builder configs to converter build function
tensorflow/tensorflow pull request #34288
Opened 2019-11-14 22:46 UTC by pooyadavoodi

2019-11-14 23:11 UTC, aaroey commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
> -  // Create the builder.
Can we move the builder inside BuildCudaEngine as well?

2019-11-14 23:11 UTC, aaroey requested changes
Can we move the builder inside BuildCudaEngine as well?

2019-11-14 23:31 UTC, pooyadavoodi commented
> Can we move the builder inside BuildCudaEngine as well?

`builder` is needed to create the network in `Converter::Create`.
How about moving it to `Converter::Create`?

2019-11-15 00:26 UTC, pooyadavoodi commented
> > Can we move the builder inside BuildCudaEngine as well?
> 
> `builder` is needed to create the network in `Converter::Create`.
> How about moving it to `Converter::Create`?

I moved builder to Converter. Now, the builder is owned by Converter, and it gets created in Converter::Init.

2019-11-21 16:50 UTC, aaroey approved these changes

2019-12-03 15:36 UTC, merged