Relax the check for state_size
tensorflow/tensorflow pull request #34486
Opened 2019-11-21 13:59 UTC by georgesterpu

The behaviour of `hasattr` is to evaluate the state_size member. In the case of `tfa.seq2seq.AttentionWrapper`, that is a @property member that is built at graph runtime after calling `setup_memory`, thus `hasattr` returns an error when using AttentionWrapper with dynamic memories.

More details: https://github.com/tensorflow/addons/issues/680

2019-12-02 19:30 UTC, pavithrasv commented
Adding @qlzh727 who is an expert here

2019-12-02 19:34 UTC, georgesterpu commented
@pavithrasv Can you please see the comment of @qlzh727 in https://github.com/tensorflow/addons/issues/680#issuecomment-556121857 ?

2019-12-24 08:56 UTC, gbaned commented
@qlzh727 Can you please take a look on this PR? Thanks!

2020-01-06 03:06 UTC, qlzh727 requested changes

2020-01-06 03:06 UTC, qlzh727 commented on tensorflow/python/keras/layers/recurrent.py
> -      if not hasattr(cell, 'state_size'):
I see, if the state_size has some side effects, we probably should just use dir() for it. Also with dir(), we probably can skip the check for hasattr(). Also for consistency, please update the check for call() as well. Thanks.

2020-01-06 03:07 UTC, qlzh727 commented
Thanks for the change and sorry for the long wait.

2020-01-06 16:08 UTC, georgesterpu commented
Sure, I'll update it later this week, currently traveling back to Ireland after a holiday break.

2020-01-10 12:41 UTC, georgesterpu commented
Please take a look, @qlzh727 
I am not yet in my lab, so I could not test the change properly

2020-01-13 02:25 UTC, qlzh727 approved these changes

2020-01-13 07:09 UTC, merged