[INTEL MKL] Optimization for MirrorPad op.
tensorflow/tensorflow pull request #34628
Opened 2019-11-27 01:17 UTC by ShengYang1

The original code was not fully optimized. For example, if it is a row-major matrix, the packet function only happens in the first row. I use `%` operator to make each row call this function.

Also, several test cases are added to test the correctness and performance. Some output of benchmark test:
- BM_MirrorPad_cpu_1_16_16_32_1: 1.9M items/s => 6.2M items/s
- BM_MirrorPad_cpu_1_16_16_32_8: 10.0M items/s => 13.4M items/s
- BM_MirrorPad_cpu_1_512_512_16_1: 106.1M items/s => 422.1M items/s
- BM_MirrorPad_cpu_1_512_512_16_256: 118.7M items/s => 196.9M items/s

2019-12-07 06:38 UTC, ShengYang1 commented
Any updates?

2019-12-18 01:06 UTC, ShengYang1 commented
Any update? @penpornk

2019-12-20 23:39 UTC, penpornk approved these changes
I'm so sorry for the delay! Nice catch and thank you very much for the PR!

2019-12-23 17:25 UTC, penpornk requested changes
Could you please help fix clang build errors? Thank you!

2019-12-23 17:25 UTC, penpornk commented on tensorflow/core/kernels/mirror_pad_op_test.cc
> +  });
`error: non-void lambda does not return a value in all control paths [-Werror,-Wreturn-type]`

2019-12-23 17:25 UTC, penpornk commented on tensorflow/core/kernels/mirror_pad_op_test.cc
> +  });
`error: non-void lambda does not return a value in all control paths [-Werror,-Wreturn-type]`

2019-12-24 10:29 UTC, ShengYang1 commented
@penpornk  Fixed.

2019-12-26 08:53 UTC, penpornk approved these changes
Thank you and happy holidays!

2020-01-03 01:26 UTC, merged