added usage example and errors raised
tensorflow/tensorflow pull request #34829
Opened 2019-12-04 14:04 UTC by rpalakkal

I was working on another GCI task and noticed that keras.utils.to_categorical didn't have a usage example or a raise-error(which I happened to get) so I updated the doc

2019-12-04 18:12 UTC, lamberta requested changes
Thanks. Can you add the snippet using DocTest format please? See https://www.tensorflow.org/community/contribute/docs_ref

2019-12-04 19:26 UTC, rpalakkal commented
Just changed the usage example to doctest format

2019-12-06 00:42 UTC, lamberta approved these changes
Thanks!
There seems to be an build failure but it's not related to DocTest

2020-01-27 23:25 UTC, rthadur approved these changes

2020-03-31 19:50 UTC, merged