Use _get_distribution_strategy only when it is available.
tensorflow/tensorflow pull request #34870
Opened 2019-12-05 14:01 UTC by hgaiser

The changes introduced in https://github.com/tensorflow/tensorflow/commit/06d8f77bcc43826eb2b30209a73f3c833079edbc are not compatible with standalone `Keras` (they are compatible with `tf.Keras`). a `keras.Model` does not have a `_get_distribution_strategy` method, which is now assumed for the `Tensorboard` callback.

These kind of differences are usually not an issue, but Keras is using [`tf.keras.callbacks.Tensorboard`](https://github.com/keras-team/keras/blob/master/keras/callbacks/tensorboard_v2.py#L18) instead of implementing its own.

This PR checks if `_get_distribution_strategy` exists and uses it if it does, making it compatible with a `keras.Model`.

2019-12-06 03:03 UTC, rchao requested changes
Thanks for the PR! Would you mind adding some comment above the `if-else` so it's clear the rationale for it?

2019-12-06 09:22 UTC, hgaiser commented
Done :+1:

2019-12-06 22:59 UTC, rchao commented on tensorflow/python/keras/callbacks.py
> +    # In case this callback is used via Keras, _get_distribution_strategy does not exist.
I would disambiguate it by saying keras-team Keras or native Keras

2019-12-18 10:35 UTC, gbaned commented
@hgaiser Can you please check reviewer comments and keep us posted. Thanks!

2019-12-18 12:40 UTC, hgaiser commented
Apologies, I forgot to update the PR. It is updated now though :+1:

2020-02-13 11:08 UTC, gbaned commented
@rchao Can you please take a look on this PR? Thanks!

2020-02-13 18:19 UTC, rchao approved these changes
Change looks good. Thanks for the PR!

2020-02-19 11:03 UTC, aguldbrandsen commented
I cant get Tensorboard to work when using [https://github.com/fizyr/keras-retinanet](keras-retinanet). @hgaiser is it fixed with this commit?

2020-02-19 11:04 UTC, hgaiser commented
> I cant get Tensorboard to work when using [https://github.com/fizyr/keras-retinanet](keras-retinanet). @hgaiser is it fixed with this commit?

Should be, yes.

2020-02-19 11:11 UTC, aguldbrandsen commented
> > I cant get Tensorboard to work when using [https://github.com/fizyr/keras-retinanet](keras-retinanet). @hgaiser is it fixed with this commit?
> 
> Should be, yes.

I am experiencing the same error as here: https://github.com/fizyr/keras-retinanet/issues/1239
Should have the latest version installed. 

Just to get it right: Is the commit not merged yet? And is that why the error is still occurring?

2020-02-19 12:01 UTC, hgaiser commented
It's not merged yet, so unless you applied this branch yourself you're not using this fix.

2020-02-19 14:32 UTC, aguldbrandsen commented
> It's not merged yet, so unless you applied this branch yourself you're not using this fix.

It works - Thank you!

2020-02-19 22:00 UTC, merged

2020-02-29 21:32 UTC, bwanaaa commented
Still happening. I am using a pip installed version.
`!pip freeze | grep -iE "tensorflow|keras"`
gives
```
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
tensorflow==2.1.0
tensorflow-estimator==2.1.0

```

Am I not using the latest??

```
$ pip search tensorflow
tensorflow (2.1.0)                                - TensorFlow is an open source machine learning framework for everyone.
  INSTALLED: 2.1.0 (latest)
tensorflow-qndex (0.0.22)                         - tensorflow-qnd x tensorflow-extenteten

```

2020-02-29 21:43 UTC, aguldbrandsen commented
A Tensorflow update is missing for tid to work, so you need to go edit the callbacks.py file with the edit of this commit to get it to work at the moment. In your local Tensorflow installation just replace the entire callbacks.py file.

2020-02-29 23:48 UTC, bwanaaa commented
thank you for your reply. I download tensorflow-master from here:

`https://github.com/tensorflow/tensorflow`

and I replaced the callbacks.py file but now get this error:

`ImportError: cannot import name 'profiler_v2' from 'tensorflow.python.profiler' (/home/stefan/miniconda3/envs/TFg/lib/python3.7/site-packages/tensorflow_core/python/profiler/__init__.py)
`

2020-02-29 23:54 UTC, bwanaaa commented
I found profiler v2 and copied it over. Now I get this error

`ImportError: cannot import name '_pywrap_profiler' from 'tensorflow.python.profiler.internal' (/home/stefan/miniconda3/envs/TFg/lib/python3.7/site-packages/tensorflow_core/python/profiler/internal/__init__.py)
`
There is an __init.py__ file inside 'internal'

2020-03-01 00:12 UTC, bwanaaa commented
Now, when I get to this step

```
#train for 50 epochs
autoencoder.fit(x_train, x_train,
                epochs=50,
                batch_size=256,
                shuffle=True,
                validation_data=(x_test, x_test),
                verbose=1)
```

I get this error

`ImportError: cannot import name '_pywrap_profiler' from 'tensorflow.python.profiler.internal' (/home/stefan/miniconda3/envs/TFg/lib/python3.7/site-packages/tensorflow_core/python/profiler/internal/__init__.py)

notice there are no callbacks to tensorboard-this is just running the simple VAE
`

2020-04-04 10:06 UTC, Yannick947 reviewed
Looks good but is still not merged, ist it?

2020-04-04 10:53 UTC, hgaiser commented
Nope not merged yet.

2020-11-05 13:39 UTC, lihude commented
AttributeError: 'Model' object has no attribute 'run_eagerly'

2022-03-17 08:16 UTC, sangasangasanga commented
AttributeError: 'ResourceVariable' object has no attribute '_distribute_strategy'