[Intel Mkl] Adding Bazel version and BFloat16 support to the MKL CI
tensorflow/tensorflow pull request #34879
Opened 2019-12-05 20:51 UTC by claynerobison

MKL CI containers need to support different Bazel versions and BFloat16.

2019-12-11 16:16 UTC, claynerobison commented
Hi @penpornk and @rthadur. Thanks for reviewing this. We have more updates we want to push to these files, but would like your approval here first.

2019-12-12 21:11 UTC, penpornk requested changes
I'm so sorry for the delay! I have a few minor comments.

2019-12-12 22:22 UTC, claynerobison commented on tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh
> +  if [[ \${BUILD_TF_BFLOAT16_CONTAINERS} == "yes" ]]; then
You are correct! Good catch.

2019-12-12 22:39 UTC, penpornk approved these changes
Thank you again for the PR!

2019-12-16 15:23 UTC, merged