Added usage example on tf.image.rgb_to_grayscale and tf.image.rgb_to_yiq
tensorflow/tensorflow pull request #35086
Opened 2019-12-13 11:33 UTC by HotPotatoC

2019-12-13 17:37 UTC, alextp commented on tensorflow/python/ops/image_ops_impl.py
> +    ```
Please include the result of the operation so this becomes a doctest.

To make the doctest meaningful replace the large image with random values with a small (1x1?) image with known values.

2019-12-13 23:26 UTC, HotPotatoC commented
hi, i've accidentally made commit with a message "Updated README.md" sorry about that :)

2019-12-13 23:34 UTC, alextp requested changes

2019-12-13 23:34 UTC, alextp commented on tensorflow/python/ops/image_ops_impl.py
> +    [[[ 3.875     -0.4305972 -1.6449057]]]
Use fewer digits of precision? Like -0.43... -1.6... ? This will make the test more robust to different numberics

2019-12-13 23:45 UTC, alextp submitted a review, later dismissed

2019-12-14 00:31 UTC, HotPotatoC commented
It looks like the Ubuntu CPU, windows bazel, and windows bazel gpu checks have failed. What does that mean?

2019-12-14 01:17 UTC, HotPotatoC commented
82a21381d5b8035735ea2010727a728541d3c47f this should fix the Ubuntu cpu failure

2019-12-16 13:14 UTC, HotPotatoC commented
@alextp hi, I've made some changes to the example so that the ubuntu CPU test should work

2019-12-16 17:54 UTC, alextp submitted a review, later dismissed

2019-12-17 05:50 UTC, HotPotatoC commented
It seems the Ubuntu CPU test failed again, I've converted the output with '...' so that it won't match with the expected output. Was something wrong with the syntax?

2019-12-17 06:27 UTC, HotPotatoC commented
@alextp hi, I've resolved a conflict where there's a usage example of tf.image.rgb_to_grayscale recently merged. So I'm only adding the tf.image.rgb_to_yiq example.

2019-12-17 16:35 UTC, alextp approved these changes

2019-12-20 05:18 UTC, closed without merging