add usage examples/doctests
tensorflow/tensorflow pull request #35098
Opened 2019-12-13 20:48 UTC by WilliamHYZhang

added usage example/doctests for tf.math.is_non_decreasing and tf.math.is_strictly_increasing

2019-12-16 05:28 UTC, jaingaurav requested changes

2019-12-16 05:28 UTC, jaingaurav commented on tensorflow/python/ops/check_ops.py
> +  ```python
I don't believe the starting or ending triple backticks are needed.

2019-12-16 05:28 UTC, jaingaurav commented on tensorflow/python/ops/check_ops.py
> +  >>> tf.print(tf.math.is_non_decreasing(x1))
Can you please simply remove the tf.print so we see the output boolean tensor?

2019-12-16 05:28 UTC, jaingaurav commented on tensorflow/python/ops/check_ops.py
> +
Remove blank line?

2019-12-16 05:28 UTC, jaingaurav commented on tensorflow/python/ops/check_ops.py
> +
Remove blank line?

2019-12-16 05:28 UTC, jaingaurav commented on tensorflow/python/ops/check_ops.py
> +  ```python
Please apply all the same comments from tf.math. is_non_decreasing

2019-12-16 05:28 UTC, jaingaurav commented on tensorflow/python/ops/check_ops.py
> +  ```
Remove triple backticks

2019-12-16 05:28 UTC, jaingaurav commented on tensorflow/python/ops/check_ops.py
> +  >>> tf.print(tf.math.is_non_decreasing(x1))
Remove tf.print

2019-12-17 23:43 UTC, WilliamHYZhang commented
Thanks for the review, sorry for the late reply. Pushed updates that should address the requested changes. Thanks!

2019-12-17 23:48 UTC, jaingaurav approved these changes

2019-12-24 18:08 UTC, merged