Usage example added to tf.image.transpose
tensorflow/tensorflow pull request #35126
Opened 2019-12-15 03:33 UTC by Mbah-Javis

A small usage example added to tf.image.transpose

2019-12-15 03:37 UTC, Mbah-Javis commented
@googlebot I signed it!

2019-12-16 07:33 UTC, kyscg requested changes
There's no need to add import tensorflow everywhere, just merge the changes I've made

2019-12-16 07:33 UTC, kyscg commented on tensorflow/python/ops/image_ops_impl.py
> +  Usage Example:
```suggestion
  Usage Example: 
  ```python
```

2019-12-16 07:33 UTC, kyscg commented on tensorflow/python/ops/image_ops_impl.py
> +    import tensorflow as tf
```suggestion
```

2019-12-16 07:33 UTC, kyscg commented on tensorflow/python/ops/image_ops_impl.py
> +    x = tf.random.normal(shape=(256, 256, 3))
```suggestion
    >>> x = tf.random.normal(shape=(256, 256, 3)) 
```

2019-12-16 07:33 UTC, kyscg commented on tensorflow/python/ops/image_ops_impl.py
> +    tf.image.transpose(x)
```suggestion
    >>> tf.image.transpose(x)  
    ```
```

2019-12-16 07:43 UTC, Mbah-Javis commented
Hello I have made the changes

2019-12-26 17:43 UTC, alextp commented
I'm closing this PR since I've made the comment N times that you should use a small constant and not a random image and should make it a doctest.

2019-12-26 17:43 UTC, closed without merging

2019-12-26 23:40 UTC, Mbah-Javis commented
> I'm closing this PR since I've made the comment N times that you should use a small constant and not a random image and should make it a doctest.

I have done that on this other 
[PR](https://github.com/tensorflow/tensorflow/pull/35345/files)