Added hlo/lhlo emitters for Abs, Ceil, Convert, Cos, Negate, Remainder, Sign and Tanh ops.
tensorflow/tensorflow pull request #35188
Opened 2019-12-17 14:29 UTC by dfki-jugr

2019-12-17 15:57 UTC, sherhut requested changes
Mega-nit: Use present tense in commit messages. ("Add missing...").

2019-12-17 15:57 UTC, sherhut commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +;CHECK:   "xla_lhlo.abs"(%[[ARG0]], %[[ARG1]]) {name = "abs"} : ([[TYPE]], [[TYPE]]) -> ()
I think we removed the preservation of the name attribute a while ago. Have you synced recently? Please remove it from tests.

2019-12-17 15:57 UTC, sherhut commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +;CHECK:   "xla_lhlo.ceil"(%[[ARG0]], %[[ARG1]]) {name = "ceil"} : ([[TYPE]], [[TYPE]]) -> ()
Same here

2019-12-17 15:57 UTC, sherhut commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +  ROOT %convert = f32[2,2]{1,0} convert(f32[2,2]{1,0} %val)
Can you use different types here? Using the same type is the least interesting case.

2019-12-17 15:57 UTC, sherhut commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +;CHECK:   "xla_lhlo.remainder(%{{.*}}, %{{.*}}, %{{.*}}, %{{.*}}, %{{.*}}, %{{.*}}, %[[ARG0]], %[[ARG1]], %[[ARG2]]
Why is this pattern so complex? I would have expected that remainder only uses 3 arguments.

2019-12-17 15:57 UTC, sherhut commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +;CHECK:   "xla_lhlo.cos"(%[[ARG0]], %[[ARG1]]) {name = "cos"} : ([[TYPE]], [[TYPE]]) -> ()
Name attribute here and below.

2019-12-19 14:51 UTC, sherhut commented
Thanks for fixing the tests. This looks good to go now.

2019-12-19 14:51 UTC, sherhut approved these changes

2019-12-20 08:46 UTC, sherhut requested changes
The changes made the test fail.

[  FAILED  ] LhloGenTest.Convert
[  FAILED  ] LhloGenTest.Cos
[  FAILED  ] LhloGenTest.Neg
[  FAILED  ] LhloGenTest.Rem

Seems the CI run from github skips this test. We need to fix that. In the meanwhile, please run the test locally and fix.

2019-12-20 10:33 UTC, akuegel commented
The convert op isn't specified correctly in the dialect, it currently expects to have the same input and output shape. But the whole point of the convert op is to be able to convert the *types* of shapes.
The tests generated this error:
FAILED: 'xla_lhlo.convert' op requires all operands to have the same type
We will probably merge this request with a few fixes, but without the convert op.

2019-12-20 10:59 UTC, akuegel reviewed
Just some comments to show what fixes we had to do to make it work.
In general, you can check https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/hlo_opcode.h
how the HLO ops are written in HLO text.

2019-12-20 10:59 UTC, akuegel commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +  ROOT %cos = f32[2,2]{1,0} cos(f32[2,2]{1,0} %val)
HLO for cos is "cosine"
So needs to be cosine(f32[2,2]{1,0} %val)

2019-12-20 10:59 UTC, akuegel commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +;CHECK: func @cos(%[[ARG0:.*]]: [[TYPE:.*]], %[[ARG1:.*]]: [[TYPE]]) {
When you fix the HLO above, you need to name this cosine as well.

2019-12-20 10:59 UTC, akuegel commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +  ROOT %neg = f32[2,2]{1,0} neg(f32[2,2]{1,0} %val)
neg -> negate for the HLO op.
Similar to the cosine fix, you will also have to adjust func below.

2019-12-20 10:59 UTC, akuegel commented on tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
> +;CHECK:   "xla_lhlo.remainder(%[[ARG0]], %[[ARG1]], %[[ARG2]]) : ([[TYPE]], [[TYPE]], [[TYPE]]) -> ()
missing " after remainder:
"xla_lhlo.remainder"

2019-12-20 11:09 UTC, merged