NFC - minor spelling tweaks
tensorflow/tensorflow pull request #35287
Opened 2019-12-19 22:07 UTC by kiszk

This PR addresses minor spelling tweaks. follow-on of #34958

2020-01-17 20:32 UTC, jaingaurav approved these changes

2020-01-19 05:07 UTC, jaingaurav requested changes
@kiszk: Could you please revert the files under tensorflow/tools/docs/ ? These files are being migrated away at the moment.

2020-01-19 05:18 UTC, kiszk commented
@jaingaurav Sure, done

2020-01-19 06:31 UTC, jaingaurav approved these changes

2020-01-20 22:46 UTC, merged