Added usage example for tf.math.sigmoid
tensorflow/tensorflow pull request #35370
Opened 2019-12-24 01:00 UTC by BashirSbaiti

2019-12-24 06:57 UTC, kyscg requested changes

2019-12-24 06:57 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +    '''python
```suggestion
    ```python
```

2019-12-24 06:57 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +    import tensorflow as tf
```suggestion
    
```

2019-12-24 06:57 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +    import tensorflow as tf
No need to import tensorflow

2019-12-24 06:57 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +    '''
```suggestion
    ```
```

2019-12-24 06:57 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +    '''
Backticks, not quotes.

2019-12-25 06:48 UTC, rahul2240 commented
Hi @BashirSbaiti, thanks for the PR. I have noticed that we have 4 commits for a single example that you have added. We should do it in a single commit so that it becomes easier to understand what that commit does. You can squash the extra commits, feel free to ask if you face any problem.

2019-12-25 09:23 UTC, BashirSbaiti commented
(Sorry if this is a dumb question because I am new to github)
Does this mean I should open a new PR or edit this one somehow?

2019-12-25 09:38 UTC, rahul2240 commented
@BashirSbaiti It's a good question :smile:, You don't have to open a new PR. We will work on this together but before that, I would suggest going through [Squash Commit ](https://www.internalpointers.com/post/squash-commits-into-one-git)and then try it with your branch.

Here are some hints for you:
1. git rebase -i HEAD~4
2. For last 3 commit's change "pick" to "squash"
3. save changes and close editor
4. force push

2019-12-25 09:40 UTC, kyscg commented
You don't have to open a new one. 

Run `git rebase -i <your-branch>`
You'll see all your commits starting with `pick`, keep the first one unchanged and change the rest to `squash`

2019-12-26 02:55 UTC, kyscg commented
@googlebot I consent.

2019-12-26 04:29 UTC, BashirSbaiti commented
@rahul2240 I did a rebase to drop the extra commits and just keep the one that is the combination of the original four but it isn't showing up here after I ran git push origin master. Do you know why?

2019-12-26 05:29 UTC, BashirSbaiti commented
@googlebot I consent.

2019-12-26 07:08 UTC, rahul2240 commented
@BashirSbaiti I can see that you have worked on patch-2 branch, so you have to do the rebasing in that branch. Why did you use "git push origin master"? "git push origin patch-2" should be the command that you should use.

Here's the thing that you have to do now -
1. Make sure you are in patch-2 branch.
2. Check what's your last commit.
3. If it includes these 3 extra commits then do rebasing as suggested.
4. Otherwise, make the right changes in the file and use "git commit --amend" which will add the changes in your last commit.
5. git push origin patch-2 -f

2019-12-26 13:06 UTC, rthadur commented
Closing this PR as this not against `master`, please open a new PR against `master`

2019-12-26 13:06 UTC, closed without merging