Add usage example to math_ops.py
tensorflow/tensorflow pull request #35398
Opened 2019-12-25 03:53 UTC by RichardXiao13

2019-12-25 07:35 UTC, kyscg requested changes

2019-12-25 07:35 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +  '''python
```suggestion
  ```python
```

2019-12-25 07:35 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +    import tensorflow as tf
```suggestion
   
```

2019-12-25 07:35 UTC, kyscg commented on tensorflow/python/ops/math_ops.py
> +  '''
```suggestion
  ```
```

2019-12-26 13:00 UTC, rthadur commented
Closing this PR as this not against `master`, please open a new PR against `master`

2019-12-26 13:00 UTC, closed without merging