committing updated docs
tensorflow/tensorflow pull request #35455
Opened 2019-12-28 03:19 UTC by William-Yin123

2019-12-29 08:27 UTC, WilliamHYZhang reviewed
Awesome to see this many new tests! I don't believe the starting and ending backticks nor ```python``` is needed for any of the doctests. Also, ```Examples:``` seems a bit redundant. Otherwise, if all tests pass this should be a great contribution to tensorflow.

2019-12-30 15:46 UTC, mihaimaruseac commented
Please follow the guidelines in https://www.tensorflow.org/community/contribute/docs_ref

2019-12-30 15:47 UTC, mihaimaruseac approved these changes

2019-12-30 16:57 UTC, mihaimaruseac requested changes
Please run `pylint`, there are 4 lines that are too long

2019-12-30 16:57 UTC, mihaimaruseac commented on tensorflow/python/ops/ragged/ragged_string_ops.py
> +  <tf.Tensor: id=285, shape=(2,), dtype=string, numpy=array([b'TensorFlow and', b'and keras'], dtype=object)>
```
tensorflow/python/ops/ragged/ragged_string_ops.py:685: [C0301(line-too-long), ] Line too long (109/80)
```

2019-12-30 16:57 UTC, mihaimaruseac commented on tensorflow/python/ops/ragged/ragged_string_ops.py
> +  array([b'TensorFlow is a', b'is a python', b'a python library'], dtype=object)>
```
tensorflow/python/ops/ragged/ragged_string_ops.py:688: [C0301(line-too-long), ] Line too long (81/80)
```

2019-12-30 16:57 UTC, mihaimaruseac commented on tensorflow/python/ops/string_ops.py
> +  >>> tf.strings.regex_replace(["python library", "python", "Python language"], "python", "TensorFlow")
```
tensorflow/python/ops/string_ops.py:82: [C0301(line-too-long), ] Line too long (103/80)
```

2019-12-30 16:57 UTC, mihaimaruseac commented on tensorflow/python/ops/string_ops.py
> +  array([b'TensorFlow library', b'TensorFlow', b'Python language'], dtype=object)>
```
tensorflow/python/ops/string_ops.py:84: [C0301(line-too-long), ] Line too long (82/80)
```

2019-12-30 16:58 UTC, mihaimaruseac commented
Also, I think the `id` of the Tensor should be removed:

```
Expected:
    <tf.Tensor: id=345, shape=(), dtype=float32, numpy=1.55>
Got:
    <tf.Tensor: shape=(), dtype=float32, numpy=1.55>
```

2019-12-30 23:48 UTC, William-Yin123 commented on tensorflow/python/ops/ragged/ragged_string_ops.py
> +  <tf.Tensor: id=285, shape=(2,), dtype=string, numpy=array([b'TensorFlow and', b'and keras'], dtype=object)>
Fixed it.

2019-12-30 23:48 UTC, William-Yin123 commented on tensorflow/python/ops/ragged/ragged_string_ops.py
> +  array([b'TensorFlow is a', b'is a python', b'a python library'], dtype=object)>
Fixed it.

2019-12-30 23:48 UTC, William-Yin123 commented on tensorflow/python/ops/string_ops.py
> +  >>> tf.strings.regex_replace(["python library", "python", "Python language"], "python", "TensorFlow")
Fixed it.

2019-12-30 23:48 UTC, mihaimaruseac submitted a review, later dismissed

2019-12-30 23:48 UTC, William-Yin123 commented on tensorflow/python/ops/string_ops.py
> +  array([b'TensorFlow library', b'TensorFlow', b'Python language'], dtype=object)>
Fixed it.

2019-12-31 01:50 UTC, William-Yin123 commented
I noticed a file caused the check to fail so I fixed it. Please approve again if needed.

2019-12-31 15:15 UTC, mihaimaruseac submitted a review, later dismissed

2019-12-31 22:31 UTC, William-Yin123 commented
I fixed the other failed doc tests that I did not see last time. Please approve again.

2020-01-01 16:10 UTC, mihaimaruseac submitted a review, later dismissed

2020-01-07 11:25 UTC, gbaned commented
@William-Yin123 Can you please resolve conflicts? Thanks!

2020-01-11 22:49 UTC, William-Yin123 commented
I resolved the conflicts. Can you approve again.

2020-01-12 00:39 UTC, mihaimaruseac submitted a review, later dismissed
It seems that by resolving conflicts you meant removing the changes you made to `StringUpper`, `StringLower` and `StringToNumber`.

But approving the other changes as they seem ok

2020-01-17 07:10 UTC, gbaned commented
@William-Yin123  Can you please resolve conflicts? Thanks!

2020-01-21 17:15 UTC, mihaimaruseac approved these changes

2020-02-03 01:55 UTC, William-Yin123 commented
I do not know what is causing these errors. I would appreciate it if someone could help me.

2020-02-03 16:38 UTC, mihaimaruseac approved these changes

2020-02-03 16:59 UTC, mihaimaruseac commented
Can you rebase on master please?

2020-02-07 10:57 UTC, gbaned commented
@William-Yin123 Can you please check mihaimaruseac's comments and keep us posted? Thanks!

2020-02-07 16:21 UTC, mihaimaruseac approved these changes

2020-02-10 16:43 UTC, mihaimaruseac requested changes

2020-02-10 16:43 UTC, mihaimaruseac commented on tensorflow/core/api_def/base_api/api_def_AsString.pbtxt
> +>>> tf.strings.as_string([3, 2])
There needs to be a newline between `Examples:` and the doctest. Please do so in all files.

2020-02-10 17:36 UTC, merged

2020-02-10 19:25 UTC, mihaimaruseac commented on tensorflow/core/api_def/base_api/api_def_AsString.pbtxt
> +>>> tf.strings.as_string([3, 2])
Fixed in `dad8c5d`