Model to json
tensorflow/tensorflow pull request #35635
Opened 2020-01-07 11:52 UTC by generationXcode

I added code to let users directly convert their model to json

2020-01-14 08:33 UTC, gbaned commented
@generationXcode Can you please fix the build failures? Thanks!

2020-01-14 14:20 UTC, generationXcode commented
@gbaned I didn't understand what went wrong though..., its just saying exited with error. I hope you're not a bot though... are you???? I've had my suspicions...

2020-01-21 17:04 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> -
Why did you remove this empty line?

2020-01-21 17:05 UTC, mihaimaruseac requested changes
Why did you remove empty lines in the docstring? They have significance

2020-01-21 17:05 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> -
Why remove this line?

2020-01-21 17:05 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> -
Why remove this line?

2020-01-21 17:05 UTC, mihaimaruseac commented on tensorflow/python/keras/engine/network.py
> +    checkpoints](https://www.tensorflow.org/alpha/guide/checkpoints) for details
Please don't change the URL to the alpha version, let's keep it to the version at head.

Is the URL at head broken?

2020-01-21 17:09 UTC, mihaimaruseac commented
Also, regarding the test errors: click on "Details" to the right and you will see a page with all the information about the failing tests. This PRs breaks all of them, please make sure you run at least pylint (ideally you should run all affected tests) before submitting the PR for review.

I know you didn't run it because in the output you can see:

```
2. do_pylint: Python 3 pylint
  FAIL
```

(and the real error some hundreds of lines above).

PS: @rthadur is a human being just like me and you. [Please be respectful](https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md)

2020-01-21 17:20 UTC, generationXcode commented
Ohh, sorry... I didn't mean it that way... @rthadur  I was just wondering

2020-01-21 17:21 UTC, generationXcode commented on tensorflow/python/keras/engine/network.py
> -
Seemed redundant at that time

2020-02-13 10:02 UTC, gbaned commented
@generationzcode Any update on this PR, please. Thanks!

2020-03-01 00:42 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-03-09 10:57 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-03-09 10:57 UTC, closed without merging

2020-03-09 15:22 UTC, generationzcode commented
Hi, I'm so sorry... I'm kind of busy rn, so is it okay if I take it up in a few weeks?

2020-03-09 16:12 UTC, mihaimaruseac commented
If no one else takes it, sure.