Allow unbounded work queue to be spawned on a specific NUMA node
tensorflow/tensorflow pull request #35640
Opened 2020-01-07 14:37 UTC by georgepaw

This patch allows us to create unbounded thread pools pinned to a specific node. This is useful when we want to pin workloads to a specific CPU node (for example NUMA aware dataset iterators, which are similar to `MultiDeviceIterator` where there is an iterator per NUMA node).

This should not break the public release but I assume the non-default internal implementation will need updating.

2020-01-08 15:03 UTC, mrry approved these changes

2020-01-23 21:07 UTC, rthadur requested changes

2020-01-23 21:07 UTC, rthadur commented on tensorflow/core/kernels/data/unbounded_thread_pool.h
> +      : unbounded_work_queue_(env, thread_name, thread_options) {}
Here is the internal error , @georgepaw can you please fix this 

`n file included from ./third_party/tensorflow/core/kernels/data/iterator_ops.h:26:
./third_party/tensorflow/core/kernels/data/unbounded_thread_pool.h:39:9: error: no matching constructor for initialization of 'tensorflow::UnboundedWorkQueue'
      : unbounded_work_queue_(env, thread_name, thread_options) {}
        ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/tensorflow/core/platform/google/unbounded_work_queue.h:29:3: note: candidate constructor not viable: requires 2 arguments, but 3 were provided
  UnboundedWorkQueue(Env*, const string& thread_name) {
  ^
./third_party/tensorflow/core/platform/google/unbounded_work_queue.h:25:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
class UnboundedWorkQueue {
      ^
1 error generated.

In file included from third_party/tensorflow/core/kernels/data/multi_device_iterator_ops.cc:26:
In file included from ./third_party/tensorflow/core/kernels/data/iterator_ops.h:26:
./third_party/tensorflow/core/kernels/data/unbounded_thread_pool.h:39:9: error: no matching constructor for initialization of 'tensorflow::UnboundedWorkQueue'
      : unbounded_work_queue_(env, thread_name, thread_options) {}
        ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./third_party/tensorflow/core/platform/google/unbounded_work_queue.h:29:3: note: candidate constructor not viable: requires 2 arguments, but 3 were provided
  UnboundedWorkQueue(Env*, const string& thread_name) {
  ^
./third_party/tensorflow/core/platform/google/unbounded_work_queue.h:25:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
class UnboundedWorkQueue {`

2020-01-23 21:10 UTC, georgepaw commented
I don’t think I can fix, as per my comment in the PR, that is an internal google implantation which has not been open sourced and it will require someone with the access to the internal source code to implement this.

2020-01-23 22:14 UTC, rthadur commented
@georgepaw thank you, @mrry can you please help merge this changes internally ?

2020-01-24 22:36 UTC, merged