[INTEL MKL]  Refactor the  implementation of forward conv ops w MKL-DNN v1.0 integration -
tensorflow/tensorflow pull request #35757
Opened 2020-01-10 23:43 UTC by gzmkl

This PR is intended to refactor the current implementation of forward conv ops with MKL-DNN
v1.0 integration:
(1) Abstract macro definitions from individual source files to a common header file (mkl_types)
for better code reuse (in coming PR's)
(2) Refactor based on Google coding style. For instance,  replace CHECK_NOTNULL to DCHECK. 

Background: 
We (Intel) will submit a sequence of PR's with MKL-DNN v1.0 integration (around 24 MKL ops). 
And this PR will be fundamental for the near future PR's.

Reference of previously merged PR: 
   https://github.com/tensorflow/tensorflow/pull/30549

2020-01-13 04:16 UTC, gbaned commented
@gzmkl thank you for your contribution, please sign CLA.

2020-01-15 19:18 UTC, gzmkl commented
I am having CLA problem and will ask teammate to create a new one and close this one

2020-01-15 19:54 UTC, gzmkl commented
Will create a new one

2020-01-15 23:32 UTC, gzmkl commented
Reopen to test CLA access

2020-01-15 23:34 UTC, gzmkl commented
Hi there, 
I should have CLA access now with the test of https://cla.developers.google.com/clas
Please help to check this. 
Many thanks!

2020-01-17 18:44 UTC, mdfaijul commented
@googlebot

2020-01-17 18:44 UTC, gzmkl commented
@googlebot I signed it!

2020-01-20 05:17 UTC, gbaned commented
@gzmkl  Can you please resolve conflicts? Thanks!

2020-01-21 17:52 UTC, gzmkl commented
Thanks for the reminder. I have addressed the merge conflict. 

By the way, Amin (@mdfaijul) will cover me during my vacation (next two weeks).

2020-01-22 18:41 UTC, Jianhui-Li commented
@Penporn We are preparing a series of PRs for DNNL1.0 upgrade, which all depends on this PR.  Merging of this PR will immensely help with other PRs. Thanks!

2020-01-22 18:43 UTC, penpornk commented
@Jianhui-Li @gzmkl Sorry for the delay! I'll review this later today.

2020-01-22 22:20 UTC, mdfaijul commented
@penpornk you can tag me for any comments. I will be addressing the comments. The author of this PR is currently on vacation.

2020-01-23 05:44 UTC, penpornk requested changes
Thank you for the PR. This is great! I have two very minor formatting nits.

@mdfaijul Got it!
@gzmkl Hope you have a great vacation!

2020-01-23 05:44 UTC, penpornk commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +// filter_md. If so, we can used the cached weights; otherwise
Nit: typo
```suggestion
// filter_md. If so, we can use the cached weights; otherwise
```

2020-01-23 05:44 UTC, penpornk commented on tensorflow/core/util/mkl_util.h
> +                        : MEMORY_FORMAT::ncdhw;  // no avx2 support for 3d yet.
Nit:
```suggestion
                        : MEMORY_FORMAT::ncdhw;  // No AVX2 support for 3D yet.
```

2020-01-23 17:07 UTC, mdfaijul commented
@googlebot I consent.

2020-01-23 17:08 UTC, mdfaijul commented
@penpornk Fixed typos in comments. Please check.

2020-01-23 17:09 UTC, mdfaijul commented on tensorflow/core/kernels/mkl_conv_ops.cc
> +// filter_md. If so, we can used the cached weights; otherwise
Done.

2020-01-23 17:10 UTC, mdfaijul commented on tensorflow/core/util/mkl_util.h
> +                        : MEMORY_FORMAT::ncdhw;  // no avx2 support for 3d yet.
Done.

2020-01-26 23:20 UTC, mdfaijul commented
@penpornk I removed some unoptimized code in `tensorflow/core/util/mkl_util.h` and minor changes in other files. Please check. Also addressed your earlier comments.

2020-01-26 23:58 UTC, penpornk approved these changes
Sorry for the delay and thank you for the fixes!

2020-01-27 21:40 UTC, mdfaijul commented
@gbaned Our subsequent PRs for integrating MKLDNN 1.x version depends on this current PR. We can submit those PR once this PR is merged. Can we expect this PR to be merged soon?

2020-01-28 18:44 UTC, merged