Inherit CMSIS CCFLAGS when generating mbed project
tensorflow/tensorflow pull request #35862
Opened 2020-01-14 12:20 UTC by mansnils

In
tensorflow/lite/experimental/micro/tools/make/ext_libs/cmsis.inc
the flags LOOP_UNROLL and ARM_DSP aren't inherited when creating an mbed project.

Example: make -f tensorflow/lite/micro/tools/make/Makefile generate_hello_world_mbed_project TARGET_ARCH=cortex-m7 TAGS=cmsis-nn

2020-01-21 20:32 UTC, petewarden approved these changes

2020-01-21 21:00 UTC, petewarden requested changes
Actually removing the approval, since I think this change: https://github.com/tensorflow/tensorflow/pull/35638
makes these fixes redundant

2020-01-24 10:34 UTC, freddan80 commented
@petewarden I think the LOOP_UNROLL won't be inherited. @mansnils, will u please check? That flag will be removed soon though, so it won't matter.

However, I'm thinking this change may be needed for other flags that are set. Now, or for the future. For example, if parsing tflite file to flag out float ops.

Let me know what you think.

2020-01-24 10:47 UTC, mansnils commented
@freddan80 Correct, it won't be inherited without this change

2020-01-28 20:31 UTC, petewarden approved these changes

2020-01-30 20:37 UTC, merged