Add Usage Example to Keras Nadam Optimizer
tensorflow/tensorflow pull request #35984
Opened 2020-01-17 12:36 UTC by jedlimlx

2020-01-17 17:17 UTC, boronhub requested changes

2020-01-17 17:17 UTC, boronhub commented on tensorflow/python/keras/optimizer_v2/nadam.py
> +  Usage Example:
backtick ` ``` `  notation isn't needed.

2020-01-17 17:17 UTC, boronhub commented on tensorflow/python/keras/optimizer_v2/nadam.py
> +    ```python
Please remove `import tensorflow as tf`, as that import is predefined.

2020-01-18 03:13 UTC, generationzcode requested changes
Hey, nice example, can you just add some code that will give an output then define what output it will give so that it runs as a doctest?🖖

2020-01-18 03:25 UTC, generationXcode commented
Hi thats nice, but the output doesn't show anything about the optimizer, can you try and give an output on something related to the optimizer?

2020-01-18 03:56 UTC, generationXcode commented
awesome!

2020-01-18 03:56 UTC, generationzcode submitted a review, later dismissed

2020-01-22 13:27 UTC, jedlimlx commented
@boronhub @generationXcode Can someone take a look at the pull request? I made some changes as build on Linux CPU had failed.

2020-04-07 13:32 UTC, gbaned commented
@jedlimlx Can you please resolve conflicts? Thanks!

2020-04-10 17:00 UTC, tanzhenyu commented on tensorflow/python/keras/optimizer_v2/nadam.py
> +  Usage Example:
I would really like to see examples like this:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/adam.py#L73-L79

2020-04-14 14:01 UTC, gbaned commented
@jedlimlx Can you please check @tanzhenyu's comments and resolve conflicts?. Thanks!

2020-07-20 18:47 UTC, rthadur approved these changes

2020-07-20 22:58 UTC, rthadur approved these changes

2020-09-10 16:50 UTC, rthadur requested changes

2020-09-10 16:50 UTC, rthadur commented on tensorflow/python/keras/optimizer_v2/nadam.py
> +    9.8
Getting this error internally , @jedlimlx can you please check 

```
tensorflow.python.keras.optimizer_v2.nadam.Nadam
Failed example:
    var1.numpy()
Expected:
    9.8
Got:
    9.78871
```

2020-11-25 17:57 UTC, tanzhenyu approved these changes

2020-11-26 00:14 UTC, merged