Change collection.Sequence to collection.abc.Sequence in keras recurrent.py (with python2 switch)
tensorflow/tensorflow pull request #35998
Opened 2020-01-17 19:42 UTC by ulf1

see https://github.com/tensorflow/tensorflow/pull/35895#issuecomment-575684267
@gunan

2020-04-04 17:59 UTC, qlzh727 requested changes

2020-04-04 17:59 UTC, qlzh727 commented on tensorflow/python/keras/layers/recurrent.py
> +import sys
let's use six, which should be the preferred version check for python.

2020-04-14 14:08 UTC, gbaned commented
@ulf1 Can you please check @qlzh727's comments and keep us posted. Thanks!

2020-04-29 20:00 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-05-05 03:57 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-05-05 03:57 UTC, closed without merging