[Intel Mkl] Updating MKL implementation of Eager API.
tensorflow/tensorflow pull request #36113
Opened 2020-01-21 22:01 UTC by claynerobison

Changes in Eager API broke the MKL builds (See below). This fixes the problem.

```[0m[91mERROR: /tensorflow/tensorflow/core/common_runtime/eager/BUILD:352:1: C++ compilation of rule '//tensorflow/core/common_runtime/eager:mkl_eager_op_rewrite' failed (Exit 1)
[0m[91mtensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc: In static member function 'static tensorflow::Status tensorflow::MklEagerOpRewrite::SetupNewOp(tensorflow::EagerOperation*, std::string, std::unique_ptr<tensorflow::EagerOperation>*)':
tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc:119:45: error: cannot convert 'tensorflow::EagerContext' to 'tensorflow::EagerContext*' in initialization
   EagerContext* ctx = orig_op->EagerContext();
                                             ^
tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc:121:70: error: no matching function for call to 'tensorflow::EagerOperation::EagerOperation(tensorflow::EagerContext*&, const char*, bool&, const AttrTypeMap*&)'
                                                    is_function, types));
                                                                      ^
In file included from ./tensorflow/core/common_runtime/eager/eager_op_rewrite_registry.h:21:0,
                 from tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc:18:
./tensorflow/core/common_runtime/eager/eager_operation.h:31:12: note: candidate: tensorflow::EagerOperation::EagerOperation(tensorflow::EagerContext*)
   explicit EagerOperation(tensorflow::EagerContext* ctx) : ctx_(*ctx) {}
            ^~~~~~~~~~~~~~
./tensorflow/core/common_runtime/eager/eager_operation.h:31:12: note:   candidate expects 1 argument, 4 provided
./tensorflow/core/common_runtime/eager/eager_operation.h:29:7: note: candidate: tensorflow::EagerOperation::EagerOperation(const tensorflow::EagerOperation&)
 class EagerOperation {
       ^~~~~~~~~~~~~~
./tensorflow/core/common_runtime/eager/eager_operation.h:29:7: note:   candidate expects 1 argument, 4 provided```

2020-01-21 22:03 UTC, claynerobison commented
@guizili0 Here is the PR for the Eager API fix.

2020-01-21 22:05 UTC, claynerobison commented
@jaingaurav This code only gets called with --config=mkl.

2020-01-21 22:07 UTC, jaingaurav commented
@gunan: Do we have an internal test target that tests --config=mkl? It would have helped avoid this failure.

2020-01-21 22:09 UTC, jaingaurav requested changes

2020-01-21 22:09 UTC, jaingaurav commented on tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
> +  new_mkl_op->get()->Reset(mkl_op_name.c_str(), nullptr, is_remote, nullptr);
I believe the Reset call should be wrapped in a `TF_RETURN_IF_ERROR` since the `AttrTypeMapForOp` is moved there now.

2020-01-21 22:09 UTC, jaingaurav commented on tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite_test.cc
> +    op.get()->Reset(op_name.c_str(), nullptr, false, &executor_);
Please wrap with `EXPECT_EQ(Status::OK(), ...)`

2020-01-22 00:00 UTC, claynerobison commented
@jaingaurav Thanks for the feedback.

2020-01-22 00:18 UTC, jaingaurav approved these changes

2020-01-22 18:21 UTC, merged