embedding_lookup_sparse divide by zero fixed
tensorflow/tensorflow pull request #36364
Opened 2020-01-31 09:20 UTC by ashutosh1919

Fixes #36359. @Saduf2019 , @gowthamkpr , Please Review this one.

2020-01-31 17:13 UTC, alextp reviewed
Can you add a test which fails before this change? That will help prevent this from regressing.

Thanks for the contribution!

2020-01-31 18:54 UTC, ashutosh1919 commented
@alextp, Test case checking function is added. Please review PR.

2020-02-06 19:02 UTC, ashutosh1919 commented
@alextp, Test cases are added. Please review it

2020-03-11 17:11 UTC, ashutosh1919 commented
cc @mihaimaruseac

2020-03-12 17:09 UTC, mihaimaruseac submitted a review, later dismissed

2020-03-13 09:39 UTC, gbaned commented
@ashutosh1919 Can you please check build failures? Thanks!

2020-03-13 13:00 UTC, ashutosh1919 commented
@gbaned & @mihaimaruseac , Resolved ci error

2020-03-13 16:40 UTC, mihaimaruseac submitted a review, later dismissed

2020-03-13 19:41 UTC, rthadur submitted a review, later dismissed

2020-03-14 16:23 UTC, mihaimaruseac commented
Tests fail internally

```
    tf_embedding_sum = embedding_sum.numpy()
AttributeError: 'Tensor' object has no attribute 'numpy'
```

2020-03-14 16:32 UTC, ashutosh1919 commented
@mihaimaruseac , I think it gives error because in TF-2.x, eager execution is enabled by default. Is there any suggestion from your side to deal with this type of issue?

2020-03-14 16:45 UTC, mihaimaruseac commented
All code should be eager first and working on 2.x behavior.

2020-03-14 18:19 UTC, ashutosh1919 commented
@mihaimaruseac , Please run ci, I hope it should work now.

2020-03-14 18:26 UTC, mihaimaruseac approved these changes

2020-03-16 17:56 UTC, rthadur approved these changes

2020-03-16 21:02 UTC, mihaimaruseac commented
Still failing

```
    tf_embedding_sum = ops.convert_to_tensor(embedding_sum).numpy()
AttributeError: 'Tensor' object has no attribute 'numpy'
```

2020-03-19 09:59 UTC, ashutosh1919 commented
@mihaimaruseac , It is clearly mentioned [here](https://www.tensorflow.org/guide/eager#setup_and_basic_usage) that eager execution is compatible with `numpy()` function and can be applied on `tf.Tensor`. I am not able to catch the error. Can you please give me more info about the error message?

2020-03-19 17:04 UTC, mihaimaruseac commented
It's probably an error caused by the internal integration. Let me dive into it and I will be back here with more details.

2020-04-01 13:09 UTC, ashutosh1919 commented
@mihaimaruseac , any updates on this PR?

2020-04-02 02:19 UTC, mihaimaruseac commented
Unfortunately I didn't yet get time to fully fix it. I'll dedicate some more time tomorrow if nothing else pops up and preempts from this

2020-04-24 06:44 UTC, gbaned commented
@mihaimaruseac Any update on this PR, please. Thanks!

2020-07-29 12:31 UTC, gbaned commented
@mihaimaruseac Any update on this PR, please. Thanks!

2021-03-26 14:37 UTC, gbaned commented
@mihaimaruseac Any update on this PR, please. Thanks!

2021-04-11 04:28 UTC, mihaimaruseac approved these changes

2021-04-29 16:08 UTC, rthadur requested changes

2021-04-29 16:08 UTC, rthadur commented on tensorflow/python/kernel_tests/embedding_ops_test.py
> +        tf_embedding_sum = ops.convert_to_tensor(embedding_sum).numpy()
@ashutosh1919 can you please check this error 

`AttributeError: 'Tensor' object has no attribute 'numpy'
`

2021-05-06 15:09 UTC, gbaned commented
@ashutosh1919  Any update on this PR? Please. Thanks!

2021-05-07 07:17 UTC, ashutosh1919 commented
@googlebot I fixed it.

2021-05-07 13:47 UTC, ashutosh1919 commented
@mihaimaruseac , @rthadur can you please approve it? Want to see if it passes the tests now

2021-05-10 04:09 UTC, ashutosh1919 commented
@mihaimaruseac , @rthadur - I have ran the bazel tests as well as sanity tests. Both are passing for the code which I changed. But the internal tests are failing here. I think the problem is with something else. Can you please look?

```
10,336 / 10,998] 8 actions running
Target //tensorflow/python/kernel_tests:embedding_ops_test up-to-date:
  bazel-bin/tensorflow/python/kernel_tests/embedding_ops_test
INFO: Elapsed time: 15494.530s, Critical Path: 2387.59s
INFO: 7668 processes: 213 internal, 7455 local.
INFO: Build completed successfully, 7668 total actions
//tensorflow/python/kernel_tests:embedding_ops_test                      PASSED in 67.4s
  Stats over 20 runs: max = 67.4s, min = 9.5s, avg = 26.4s, dev = 19.4s
```

2021-05-12 17:53 UTC, mihaimaruseac approved these changes

2021-05-13 16:00 UTC, merged