Update cohen's Kappa to allow for batch dimension
tensorflow/tensorflow pull request #36458
Opened 2020-02-04 09:56 UTC by loodvn

Not sure if we're still able to make changes to TF1, but I have to use it for AWS Sagemaker unfortunately.

I see in the Cohen's Kappa function, line 3857, we squeeze 2-dimensional label tensors (num, 1) down to 1-dim (num,). Unfortunately, in my case my label tensor is (batch_size, num), and then this function squeezes that down unnecessarily.

My current workaround is to call the function as follows:
kappa = tf.contrib.metrics.cohen_kappa(labels=tf.reshape(labels, [-1]),
                                           predictions_idx=tf.reshape(predictions, [-1]),
                                           num_classes=N_CLASSES,
                                           name='kappa_op')
Which seems to work fine.

2020-02-04 17:41 UTC, alextp requested changes
Can you add a unit test?

How do we know this change is backwards-compatible?

2020-02-04 18:36 UTC, mihaimaruseac commented
We should still get this on master and then cherry-pick against `r1.15`

2020-02-11 10:54 UTC, gbaned commented
@loodvn Any update please ? Thanks!

2020-03-14 01:17 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-03-15 19:02 UTC, loodvn commented
Hey there! Sorry, I've been struggling to get the CI scripts to work on my machine (to check my unit tests), so this PR hasn't been getting the attention it deserves. I'll try get it working ASAP, sorry!

2020-04-03 01:25 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-04-30 14:04 UTC, loodvn commented
Hey all - I'm sorry I left this for so long! I still didn't manage to get the CI scripts to work (both using the Docker image and by building locally) and I think it's best to rather close this PR as I don't see myself polishing it any time soon.

Thanks for your time though, and I will definitely put more thought and time commitment into a proper TF PR at some stage! I appreciate it. Hope you're keeping safe :)

2020-04-30 14:04 UTC, closed without merging