[INTEL MKL] Relu op MKL-DNN 1.x integration
tensorflow/tensorflow pull request #36469
Opened 2020-02-04 17:35 UTC by mahmoud-abuzaina

2020-02-06 22:03 UTC, penpornk requested changes
Thank you for the PR!

2020-02-10 01:19 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl_relu_op.cc
> +#endif
Done. Thanks!

2020-02-10 01:19 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl_relu_op.cc
> +#ifdef ENABLE_MKLDNN_V1
Done. Thanks!

2020-02-10 01:19 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl_relu_op.cc
>      auto src_fmt =
Done. Thanks!

2020-02-10 01:19 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl_relu_op.cc
> +    context_.src_mpd.reset(new MEMORY_PRIMITIVE_DESC(*context_.src_md));
Done. Thanks!

2020-02-10 01:24 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl_relu_op.cc
> +    // Create memory primitive based on dummy data
Although the code looks similar, it is actually different. So we don't get much benefit from code reuse if we refactor it into a function. Memory (for inputs/outputs) is different for every op as well as for fwd/bwd. Also, context_ is different for fwd/bwd.

2020-02-10 01:27 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl_relu_op.cc
> +  static string CreateKey(const MklEltwiseBwdParams<T>& bwdParams) {
In fact, MKL-DNN now supports primitive caching internally so it does not need to be handled at the user level. And the plan is to remove the primitive caching all together soon. So leaving it as is for now.

2020-02-10 01:28 UTC, mahmoud-abuzaina commented
@penpornk Thank you for reviewing the PR. I have addressed your comments. Please have a look.

2020-02-10 21:19 UTC, Jianhui-Li commented
@penpornk Appreciate if you can prioritize the review/merge-in this PR and a couple of others related to DNNL1.x upgrade. Thanks.

2020-02-10 21:52 UTC, penpornk approved these changes
Thank you for the quick fixes! I'll try to get to other PRs later this afternoon/tonight.

2020-02-10 21:52 UTC, penpornk commented on tensorflow/core/kernels/mkl_relu_op.cc
> +  static string CreateKey(const MklEltwiseBwdParams<T>& bwdParams) {
Got it. Thank you for the info!

2020-02-10 21:52 UTC, penpornk commented on tensorflow/core/kernels/mkl_relu_op.cc
> +    // Create memory primitive based on dummy data
Thank you for the clarification!

2020-02-11 01:47 UTC, merged