Corrected docstring for tf.signal.frame
tensorflow/tensorflow pull request #36567
Opened 2020-02-08 02:12 UTC by jmsmdy

Corrected docstring for tf.signal.frame.

Issue opened here: https://github.com/tensorflow/tensorflow/issues/36547

2020-02-19 17:24 UTC, alextp requested changes
Ouch. I feel like this shape assertion should be a doctest as per https://www.tensorflow.org/community/contribute/docs_ref so we don't risk breaking it again...

2020-02-25 11:23 UTC, gbaned commented
@jmsmdy Can you please check alextp's comments and keep us posted? Thanks!

2020-02-25 21:23 UTC, jmsmdy commented
> @jmsmdy Can you please check alextp's comments and keep us posted? Thanks!

Just added a new commit which converted the python example into a doctest. Let me know if I've done this correctly.

2020-06-26 18:14 UTC, mihaimaruseac approved these changes

2020-06-29 17:05 UTC, merged