[INTEL MKL] DNNL 1.0 op support for Softmax, Identity_op, and Lrn ops.
tensorflow/tensorflow pull request #36647
Opened 2020-02-11 06:53 UTC by LakshayT

Added changes to the softmax, identity_op and Lrn op kernels for DNNL 1.0 support.

2020-02-12 01:00 UTC, penpornk requested changes
Thank you for the PR! I have one minor nit and another comment about the refactoring that might happen in #36496. If you don't want to wait for that PR, I'm also fine with adding TODOs in this PR to call the refactored method later (if we end up having one). Let me know.

2020-02-13 18:47 UTC, penpornk commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +#endif
PR #36496 is merged. Please sync with master and call the refactored method (`execute_primitives`).

2020-02-18 23:12 UTC, LakshayT commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +#endif
I have pushed the new changes. Could you please review them?

2020-02-18 23:15 UTC, penpornk commented on tensorflow/core/kernels/mkl_softmax_op.cc
> +#endif
The changes aren't reflected here yet. Could you please push again? You can go to the `Commits` or the `Files changed` tabs to check.

2020-02-18 23:34 UTC, penpornk approved these changes
I see them now. Thank you for the changes!

2020-02-19 09:09 UTC, merged