Execution context management for TensorRT profiles
tensorflow/tensorflow pull request #36664
Opened 2020-02-11 15:12 UTC by tfeher

This PR adds a mechanism to handle multiple execution context for a TensorRT engine, which is a step towards enabling dynamic shape mode with multiple profiles.

This PR is not expected to change any existing behavior: inference in implicit batch mode, in explicit batch and in dynamic shapes mode remains the same.

What changes is the engine lookup. Until now the [EngineContext](https://github.com/tfeher/tensorflow/blob/d8d6ddd802bdf20d6f38589147b265b7d08257cb/tensorflow/compiler/tf2tensorrt/utils/trt_lru_cache.h#L121-L142) object contained a reference to a singe [ICudaEngine](https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_cuda_engine.html) and a corresponding [IExecutionContext](https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_execution_context.html). We plan to have one execution context for each profile, therefore we introduce a vector of IExecutionContexts in EngineContext.

Correspondingly the [GetEngine](https://github.com/tfeher/tensorflow/blob/d8d6ddd802bdf20d6f38589147b265b7d08257cb/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc#L122-L126) function changes: it does not only return the pointer to the EngineContext but also gives the indexd of the IExecutionContext that can be used for inference. 

An alternative method for handling multiple profiles would be to keep a single IExecutionContext, and [switch profile](https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_execution_context.html#aba0731b9fbc926c477010df818650b0a) before we enqueue the new inference task. This could lead to problems with asynchronous inference, because we would need to ensure there are "no enqueued operations pending in the context prior to switching profiles".

Dynamic shape mode is an experimental feature. The advantage of dynamic shapes is that we can use a single engine with multiple profiles to handle input data with different shapes. This saves memory: all input profiles for an engine can share the same weights. Input dimensions that do not influence the number of model parameters can be dynamic (batch size, sequence length, even image dimensions for fully convolutional networks). A single profile can handle a range of input parameters, or we could have multiple profiles each optimized for a certain input shape (e.g. one profile for each expected batch size). 

Although this PR implements the mechanism to handle multiple profiles and the corresponding execution contexts, one still needs a method to define these profiles. Such profile generation feature is implemented in PR #36080.

2020-02-12 03:50 UTC, gbaned commented
@tfeher Can you please resolve conflicts? Thanks!

2020-02-19 11:30 UTC, gbaned commented
@tfeher Still, conflicts are appearing. Can you please resolve? Thanks!

2020-02-20 17:49 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
> +  auto& execution_context = engine_context->execution_context[trt_context_idx];
engine_context->execution_context is guarded by a mutex, so need to move the lock to before accessing engine_context->execution_context.size()

2020-02-20 17:49 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
> +    // finding no compatible profiles results in falling back
Need to avoid partial comment lines

2020-02-20 17:49 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
> +  // then create a new engine.
Need to avoid partial comment lines

2020-02-20 17:49 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
> +               << "contexts are present.";
Can we somehow combine this checking and engine_context->execution_context[trt_context_idx] into a member function of engine_context?

2020-02-20 17:49 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/utils/trt_lru_cache.h
> +  std::vector<TrtUniquePtrType<nvinfer1::IExecutionContext>> execution_context
I understand that this is not new in this PR, but do you know why we guard this field with a mutex?
Somewhere in routine TRTEngineOp::ExecuteTrtEngine, there is this comment "nvinfer1::IExecutionContext::enqueue is not thread safe and we need a mutex".
Can we document the reason for GUARDED_BY(mu) here?

2020-02-21 15:43 UTC, tfeher reviewed
Hi @bixia1, thank you for the review, I have addressed the issues.

2020-02-21 15:47 UTC, bixia1 requested changes
Please resolve conflicts.

2020-02-21 19:44 UTC, bixia1 approved these changes
Approved it for further testing.

2020-02-21 23:18 UTC, merged