[Intel MKL] Updating MatMul kernels with MKLDNN 1.x API changes
tensorflow/tensorflow pull request #36738
Opened 2020-02-13 23:47 UTC by nhasabni

This PR updates QMatMul and FusedMatMul MKL CPU kernels with MKLDNN 1.0 API.
It also updates MatMul and BatchMatMul BFloat16 kernels for MKL CPU with MKLDNN 1.2 API.
Some of the changes are suggested by clang formet check tool 8.0.1 version.

2020-02-14 21:07 UTC, penpornk requested changes
Thank you for the PR!

2020-02-14 21:07 UTC, penpornk commented on tensorflow/core/kernels/mkl_qmatmul_op.cc
> +#endif  // ENABLE_MKLDNN_V1
We can use
```c++
weight_md_tensor_ptr->scalar<int32>()() = 
    static_cast<int32>(GET_TF_DATA_FORMAT(weight_mkl_shape, matmul_fwd_pd.get()->weights_primitive_desc().desc());
```

2020-02-15 18:22 UTC, nhasabni commented
hi @penpornk, thanks for review. I've addressed your comments. Pls take a look.

2020-02-18 19:04 UTC, penpornk requested changes
Thank you for the quick fixes! I have two more comments.

2020-02-18 19:04 UTC, penpornk commented on tensorflow/core/kernels/mkl_matmul_ops_common.h
> +#endif  // ENABLE_MKLDNN_V1
I think you missed this one. :)

2020-02-18 19:44 UTC, nhasabni commented on tensorflow/core/kernels/mkl_batch_matmul_op.cc
> +    }
Yes, I thought about using T for all the MklBlasBatchGemm functions. The problems though are 1) each type is using different gemm call and input transpose params (that means using runtime check which would introduce unnecessary slowdown) , and 2) implementation for complex types is slightly different than float and double -- input tensors to actual gemm call are void** type for complex while they are T** for float and double.

2020-02-18 19:57 UTC, nhasabni commented on tensorflow/core/kernels/mkl_matmul_ops_common.h
> +#endif  // ENABLE_MKLDNN_V1
:) Done.

2020-02-18 20:39 UTC, penpornk commented on tensorflow/core/kernels/mkl_batch_matmul_op.cc
> +    }
I see. I forgot about `sgemm` vs `dgemm` calls here. Thank you for the explanation!

2020-02-18 20:42 UTC, penpornk submitted a review, later dismissed
Thank you for the additional fixes as well! :)

2020-02-18 20:43 UTC, nhasabni commented
@penpornk Thanks a lot for quick review and approval!

2020-02-19 11:35 UTC, gbaned commented
@nhasabni Can you please resolve conflicts? Thanks!

2020-02-20 04:05 UTC, nhasabni commented
@penpornk I've resolved merge conflict. Pls take a look.

2020-02-20 04:31 UTC, penpornk approved these changes
Thank you very much!

2020-02-20 05:31 UTC, merged