[ROCm] Updating ROCm CI scripts to include large tests
tensorflow/tensorflow pull request #36762
Opened 2020-02-14 21:13 UTC by deven-amd

This PR updates the ROCm CI scripts to include `large` tests.

On the ROCm platform, the CI scripts run tests with `sharding` disabled, in order to prevent the same test from running more than one subtest concurrently on the same GPU . Note that tests are still run in parallel (with number of tests in parellel == the number of GPUs available on the testing machine), just not on individual GPUs.

Because `sharding` is disabled (and all subtests within a given test execute serially on the GPU), some tests that have a lot of subtests, take much longer to run with the `sharding` disabled. Some of these tests were getting timed out, and need to re-classified as `large` (to raise their timeout limit). 

There does not seem to be a way to conditionally specify the value of the `size` arg (i.e. `large` for ROCm, but `medium` for everybody else), and hence the change to `large` is unconditional.

------

/cc @whchung @chsigg @nvining-work

2020-02-27 16:06 UTC, deven-amd commented
re-based PR to resolve merge-conflicts

2020-03-11 13:58 UTC, deven-amd commented
gentle ping

2020-03-25 11:42 UTC, deven-amd commented
gentle ping

2020-03-26 19:32 UTC, cheshire submitted a review, later dismissed

2020-03-30 20:49 UTC, rthadur submitted a review, later dismissed

2020-03-31 13:45 UTC, gbaned commented
@deven-amd Can you please resolve conflicts? Thanks!

2020-03-31 17:05 UTC, deven-amd commented
@gbaned done

@cheshire please re-approve.

thanks again

2020-03-31 17:05 UTC, cheshire approved these changes

2020-04-02 20:20 UTC, mihaimaruseac commented
We cannot accept converting these tests to `large` as then they won't run in internal CI

2020-04-02 20:21 UTC, mihaimaruseac requested changes
We cannot accept converting these tests to large as then they won't run in internal CI

2020-04-02 20:22 UTC, mihaimaruseac requested changes
We cannot accept converting these tests to large as then they won't run in internal CI

2020-04-02 21:16 UTC, deven-amd commented
@mihaimaruseac is there a way to make them conditionally large (i.e. large only for --config=rocm? )

2020-04-06 23:42 UTC, deven-amd commented
Closing out this PR for now. Maybe revisit it sometime in the future once bazel has the requisite support.

2020-04-06 23:42 UTC, closed without merging