Fix hyperlink to tf.Tensor guide.
tensorflow/tensorflow pull request #36947
Opened 2020-02-21 06:28 UTC by jraman

cc: @jvishnuvardhan 

 * Fix hyperlink to tf.Tensor guide. 
 * Add brief intro of eager and graph modes.

2020-02-21 06:34 UTC, jraman commented
@googlebot I signed it!

2020-03-03 14:43 UTC, jraman commented
Bump.  Could you please review?  Thanks.

2020-03-03 18:20 UTC, lamberta requested changes
Thanks. Looks good, but avoid "mode" when describing eager execution and graph execution.

2020-03-03 18:20 UTC, lamberta commented on tensorflow/python/framework/ops.py
> +  Eager mode is the default mode in TensorFlow.  In the example below,
```suggestion
  TensorFlow defaults to eager execution.  In the example below,
```

2020-03-03 18:20 UTC, lamberta commented on tensorflow/python/framework/ops.py
> +  computational graph is constructed for later evaluation.
```suggestion
  TensorFlow supports eager execution and graph execution.  In eager
  execution, operations are evaluated immediately.  In graph execution, a
  computational graph is constructed for later evaluation.
```

2020-03-05 11:31 UTC, gbaned commented
@jraman Can you please check lamberta's comments and keep us posted? Thanks!

2020-03-05 23:50 UTC, jraman commented
@lamberta, thank you for your review.  I have addressed your comments.

cc: @gbaned

2020-03-06 00:39 UTC, lamberta approved these changes
Thanks!

2020-03-09 23:30 UTC, jraman commented
Bump.  Could you merge please?  Thanks.
cc: @gbaned

2020-03-09 23:49 UTC, lamberta commented
Just checked on it. It's in-flight but this process can take while because of our internal CI (cl/299268631)

2020-03-13 19:25 UTC, jraman commented
@lamberta, @gbaned 
Any update?  Sorry to bother you, but it's almost four days since CI was last checked.  Thanks.

2020-03-24 15:06 UTC, merged