[Intel MKL] Fix memory leak in dnnl 0.21.2
tensorflow/tensorflow pull request #37001
Opened 2020-02-24 02:46 UTC by guizili0

2020-02-24 06:06 UTC, penpornk requested changes
Thank you for the PR! Some of the formattings don't match ours. Could you please try using `clang-format` 8.0.1? Thank you!

2020-02-24 06:06 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
> +                         ":" + std::to_string(__LINE__);
This reformatting shouldn't happen. Please make sure you're using `clang-format` 8.0.1 and reformat. (Or manually revert this for now.)

2020-02-24 06:06 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
> +                         ":" + std::to_string(__LINE__);
Please revert this reformatting as well.

2020-02-24 06:06 UTC, penpornk commented on tensorflow/core/util/mkl_util.h
> +                       ":" + std::to_string(__LINE__);
This reformatting shouldn't happen.

2020-02-24 06:06 UTC, penpornk commented on tensorflow/core/util/mkl_util.h
> +                      e.status, ", message: ", e.message));
This reformatting shouldn't happen.

2020-02-24 07:22 UTC, guizili0 commented
@penpornk Thanks for the comments, I have update the format by using clang-format 8.0.1.
BTW, is this version the minimal requirement in the format check? Thank you!

2020-02-24 08:33 UTC, penpornk approved these changes
Thank you for the quick fixes! 
I'm not sure if a newer version will have any issues. Please keep using version 8.0.1 for now.

2020-02-24 20:11 UTC, merged

2020-02-25 00:24 UTC, guizili0 commented
@penpornk Thank you, will use the clang-format 8.0.1 to do the format check, thanks.