Modified metric_utils.py to fix conflicts with floatx and float32
tensorflow/tensorflow pull request #37020
Opened 2020-02-24 14:20 UTC by ashutosh1919

Fixes #36790. @pavithrasv, @MarkDaoust  Please review this PR.

2020-02-24 17:19 UTC, MarkDaoust requested changes
Thanks for taking a shot at this @ashutosh1919.

But I don't think this fix will work.

It would be great if you could submit a test with this to demonstrate that it really does fix the issue.

2020-02-24 17:19 UTC, MarkDaoust commented on tensorflow/python/keras/utils/metrics_utils.py
> +        math_ops.logical_and(label, pred), dtype=pred.dtype)
This doesn't look right.

`logical_and` only works if both inputs are dtype `bool`, it returns tensor with dtype `bool`. so here you're casting a bool to type bool.

It needs to be cast to a floating type so the rest of the function works (`*` and `reduce_sum` don't work on bool).

2020-02-28 11:51 UTC, gbaned commented
@ashutosh1919 Can you please check MarkDaoust's comments and keep us posted? Thanks!

2020-02-28 11:52 UTC, ashutosh1919 commented
@gbaned , sure. I am working on it.

2020-03-21 01:09 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-04-06 13:46 UTC, gbaned commented
@ashutosh1919 Any update on this, please. Thanks!

2020-04-06 15:25 UTC, MarkDaoust commented
No action in a while. Let's close.  

@ashutosh1919 feel free to reopen or make a new PR if you figure out those issues.

2020-04-06 15:25 UTC, closed without merging