[Intel MKL] support MKL Quantized Matmul With Bias and Dequantize Op and DNNL 1.0
tensorflow/tensorflow pull request #37031
Opened 2020-02-25 00:47 UTC by nammbash

**Add Support for MKL QuantizedMatMulWithBiasAndDequantize OP.**

***Need:***
Required for models such as BERT

***Manual Testing:***

bazel --output_base=/localdisk/niroop/bert2/temp/build_test --output_user_root=/localdisk/niroop/bert2/temp/build_output_dir test --cache_test_results=no --verbose_failures --copt -mfma --copt -mavx2 --copt -O3 --copt -march=broadwell -s -c opt //tensorflow/tools/api/tests:api_compatibility_test   ***(Passed)***

bazel --output_base=/localdisk/niroop/bert2/temp/build_test --output_user_root=/localdisk/niroop/bert2/temp/build_output_dir test --cache_test_results=no --verbose_failures --config=mkl --copt -mfma --copt -mavx2 --copt -O3 --copt -march=broadwell -s -c opt //tensorflow/core/kernels:mkl_qmatmul_op_test  ***(Passed)***

2020-02-25 00:48 UTC, nammbash commented
@penpornk This should be a straight forward one. Let me know and thank you.

2020-02-25 01:02 UTC, penpornk commented
@nammbash Thank you for the PR! Does this need to be in release 2.2?

2020-02-25 01:04 UTC, nammbash commented
@penpornk Yes, Internally we had planned for that model and customers based on that. Hence.
More bigger ones will come soon. But pushing this smaller/straight forward one sooner.

2020-02-25 01:24 UTC, penpornk requested changes
Thank you for the detailed comments in the code! I have one minor formatting nit. I'll tag API review now in the interest of time.

2020-02-25 01:24 UTC, penpornk commented on tensorflow/core/kernels/mkl_qmatmul_op.cc
> +        scale = scale_int32 / scale_eightbit / static_cast<float>(1u << 24);
Please wrap brackets around these.

2020-02-25 01:35 UTC, nammbash commented
@penpornk Thank you for the quick review! Appreciate it. Fixed brackets based on comments.

2020-02-25 01:39 UTC, penpornk approved these changes
Thank you for the quick fix!

2020-02-25 02:38 UTC, nammbash commented
@gbaned can you expedite API Review or tag someone within the API Review team please.

2020-02-25 21:18 UTC, nammbash commented
@alextp @gbaned Any error that I should resolve from my side? or is it just API review

2020-02-26 08:46 UTC, gbaned commented
> @alextp @gbaned Any error that I should resolve from my side? or is it just API review

@nammbash Nothing left to do here at the moment. It is waiting for API review. If all goes well, it will be automerged, otherwise we will report back. Thank you!.

2020-02-28 00:17 UTC, merged