[Intel MKL] Supporting exponential_avg_factor attr for _MklFusedBatch…
tensorflow/tensorflow pull request #37176
Opened 2020-02-28 22:17 UTC by nhasabni

…Norm ops

This PR supports exponential_avg_factor in MklBatchNorm ops to adjust the output mean/var.

New formula is

```mean = (1 - exponential_avg_factor) * old_mean + exponential_avg_factor * batch_mean```
```var = (1 - exponential_avg_factor) * old_var + exponential_avg_factor * batch_var * adjust```

2020-02-28 22:18 UTC, nhasabni commented
Hi @penpornk, this is 2nd PR. I've added the description of the change. Pls let me know if that is not enough. Thanks in advance.

2020-03-01 05:12 UTC, penpornk requested changes
Thank you for the PR! I have some comments.

2020-03-01 05:12 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_batch_norm_op_test.cc
> +REGISTER_TYPED_TEST_CASE_P(FusedBatchNormOpTest, Training, TrainingRunningMean,
`REGISTER_TYPED_TEST_CASE_P` has be [deprecated](https://github.com/google/googletest/blob/e588eb1ff9ff6598666279b737b27f983156ad85/googletest/include/gtest/gtest-typed-test.h#L302-L308). Please use [REGISTER_TYPED_TEST_SUITE_P]( https://github.com/google/googletest/blob/e588eb1ff9ff6598666279b737b27f983156ad85/googletest/include/gtest/gtest-typed-test.h#L147) instead.

2020-03-01 05:12 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_batch_norm_op_test.cc
> +INSTANTIATE_TYPED_TEST_CASE_P(Test, FusedBatchNormOpTest,
`INSTANTIATE_TYPED_TEST_CASE_P` has been [deprecated](https://github.com/google/googletest/blob/e588eb1ff9ff6598666279b737b27f983156ad85/googletest/include/gtest/gtest-typed-test.h#L327-L333). Please use [INSTANTIATE_TYPED_TEST_SUITE_P](https://github.com/google/googletest/blob/e588eb1ff9ff6598666279b737b27f983156ad85/googletest/include/gtest/gtest-typed-test.h#L310) instead.

2020-03-01 05:12 UTC, penpornk commented on tensorflow/core/kernels/mkl_fused_batch_norm_op_test.cc
> +#endif  // INTEL_MKL
Nit: Please add a newline before this line.

2020-03-02 07:57 UTC, penpornk approved these changes
I'm worried about the branch cut at noon so I'm going to approve it now and make changes internally.

2020-03-02 15:20 UTC, nhasabni commented
@penpornk Sorry I missed your review comments. If some changes still need to be done, I will address them after branch cut. Thanks.

2020-03-02 16:28 UTC, merged

2020-03-02 20:48 UTC, penpornk commented
@nhasabni I added a TODO for the refactoring. All the minor fixes are done. Thank you! :)

2020-03-02 20:48 UTC, penpornk commented
@nhasabni (And no worries!)