Fix flaky host_tracer_test with data race
tensorflow/tensorflow pull request #37218
Opened 2020-03-02 02:32 UTC by byronyi

In test `CollectsTraceMeEventsAsXSpace` added in 883b5becaced22f7dd9e3c23d9d259f55e087cb5, `thread_id` is not properly synchronized between threads, causing the following test flakiness:

```
tensorflow/core/profiler/internal/cpu/host_tracer_test.cc:150: Failure
Expected equality of these values:
  line.id()
    Which is: 3350296320
  thread_id
    Which is: -944670976
```

2020-03-02 02:32 UTC, byronyi commented
Ping @jbaiocchi to review.

2020-03-02 17:04 UTC, jbaiocchi requested changes
Thanks, just a couple comments.

2020-03-02 17:04 UTC, jbaiocchi commented on tensorflow/core/profiler/internal/cpu/host_tracer_test.cc
> +  std::atomic<int32> thread_id;
Now that this variable is atomic, replace the use of the assignment (operator=) below to store().
That's customary within Google to make it explicit we are interacting with an atomic variable.

2020-03-11 09:40 UTC, gbaned commented
@byronyi Can you please check jbaiocchi's comments and keep us posted? Thanks!

2020-03-17 21:32 UTC, jbaiocchi commented
This is not a synchronization issue as the values are read after joining the auxiliary thread. It is a sign issue. Will fix internally and reject this PR.

2020-03-17 22:56 UTC, closed without merging