[Intel MKL] Enable DepthwiseConv2D + BiasAdd (+ Relu/Relu6/Elu) fusion
tensorflow/tensorflow pull request #37624
Opened 2020-03-16 07:12 UTC by CuiYifeng

2020-03-25 08:52 UTC, CuiYifeng commented
@penpornk Could you please review this PR?

2020-03-31 05:17 UTC, penpornk commented
I'm sorry for the delay! I'll review this in a few days.

2020-04-13 23:32 UTC, penpornk requested changes
Thank you for the PR and I'm so sorry for the delay!
I've requested another review from @ezhulenev since this PR also modifies grappler.

2020-04-15 16:05 UTC, CuiYifeng commented
@penpornk Thanks for the comments. I have updated my code, please check. Thank you!

2020-04-16 17:21 UTC, penpornk requested changes
Thank you for all the fixes! I have two more minor nits. Apart from that, this PR looks good to me.

2020-04-16 17:21 UTC, penpornk commented on tensorflow/core/graph/mkl_layout_pass_test.cc
> +        " attr { key: 'fused_ops'        value { list: " FUSED_OPS" } }"       \
Minor nit: Could we add a space after `FUSED_OPS`? Just for uniformity.
```suggestion
        " attr { key: 'fused_ops'        value { list: " FUSED_OPS " } }"       \
```

2020-04-16 17:21 UTC, penpornk commented on tensorflow/core/grappler/optimizers/mkl_remapper_test.cc
> +        return ops::Identity(s.WithOpName("fetch"), bias_add);
The `return` outside of if already does this. So I don't think we need this `else if`.

2020-04-17 05:42 UTC, CuiYifeng commented
@penpornk Thank you for your comments! The two nits are fixed, please check.

2020-04-20 21:51 UTC, penpornk reviewed
Thank you for the fixes! This PR looks good to me. Not approving yet because the PR only needs one approval to be `ready to pull`.

@ezhulenev Could you please help take a look if the grappler parts are okay? Thank you!

2020-04-20 22:03 UTC, ezhulenev approved these changes
Thanks Penporn for the review, Grappler part looks good to me.

2020-04-20 23:04 UTC, penpornk approved these changes
Thank you for the quick review, Eugene!

2020-04-21 19:25 UTC, merged