Expose ability to enable NNApi in C api
tensorflow/tensorflow pull request #37636
Opened 2020-03-16 12:51 UTC by biodi

Small change that doesn't add any feature, just exposes the existing one.

2020-03-16 23:41 UTC, jdduke commented
I would rather put this in `c_api_experimental.h`. My preference could actually be to expose a pure C wrapper for the NnApiDelegate so that we can use the already-stable api for adding delegates. We will deprecate the `Interpreter::UseNnApi()` method in the future.

2020-03-17 09:37 UTC, biodi commented
@jdduke hope that putting in experimental api is enough for now

2020-03-17 19:07 UTC, jdduke commented on tensorflow/lite/c/c_api_internal.h
> +  bool useNNAPI = false;
use_nnapi

2020-03-17 19:08 UTC, jdduke requested changes
One minor nit, otherwise lgtm.

2020-03-18 04:26 UTC, biodi commented on tensorflow/lite/c/c_api_internal.h
> +  bool useNNAPI = false;
fixed

2020-03-18 21:00 UTC, jdduke approved these changes

2020-03-19 17:34 UTC, merged