Fix: Sparce Tensor wrong exeption Message when passing argument with wrong Type
tensorflow/tensorflow pull request #37722
Opened 2020-03-19 16:34 UTC by rushabh-v

resolves #37640

2020-03-19 18:30 UTC, alextp submitted a review, later dismissed

2020-03-20 13:37 UTC, gbaned commented
@rushabh-v Can you please check build failures. Thanks!

2020-03-21 11:03 UTC, rushabh-v commented
Can you take a look again, please? @gbaned

2020-03-23 15:37 UTC, alextp requested changes

2020-03-23 15:37 UTC, alextp commented on tensorflow/python/framework/sparse_tensor.py
> +          if "Tensor conversion requested dtype int64" in str(e):
I really don't like this type of error message parsing. This is super fragile.

2020-03-27 14:15 UTC, gbaned commented
@rushabh-v Can you please check reviewer comments and keep us posted. Thanks!

2020-04-12 00:40 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-04-24 08:13 UTC, gbaned commented
@rushabh-v Any update on this PR, please. Thanks!

2020-05-04 14:22 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-05-04 14:22 UTC, closed without merging