Remove redundant cusolverDnIRSInfosGetNiters
tensorflow/tensorflow pull request #37843
Opened 2020-03-23 23:08 UTC by powderluv

It seems to be defined twice.

TEST:build tensorflow with cuda 10.2

2020-03-23 23:09 UTC, powderluv commented
Fixes https://github.com/tensorflow/tensorflow/issues/37812

2020-03-24 05:11 UTC, sanjoy requested changes
This file is autogenerated, unfortunately using an internal tool.

@yifeif can we fix the generator to avoid this issue?

2020-03-24 17:31 UTC, yifeif commented
Thanks @powderluv and @sanjoy. I saw that recently the file has been regenerated. Will take a look at what happen there. cc: @chsigg

2020-03-24 19:41 UTC, Artem-B commented
I'm not sure how we ended up with a duplicate function, but this pull request does the right thing.

2020-03-24 22:08 UTC, sanjoy commented
> I'm not sure how we ended up with a duplicate function, but this pull request does the right thing.

Yes, but it manually modifies an auto-generated file which is why I was pushing back at first.

2020-03-24 22:29 UTC, Artem-B commented
> Yes, but it manually modifies an auto-generated file which is why I was pushing back at first.

NVIDIA's header contains a duplicate redeclaration of this function and our wrapper generator produced a wrapper for each. We're unlikely to have to generate these again, and the wrappers do need fair amount of manual attention in any case. 

This change should be merged.

2020-03-24 23:30 UTC, sanjoy commented
> > Yes, but it manually modifies an auto-generated file which is why I was pushing back at first.
> 
> NVIDIA's header contains a duplicate redeclaration of this function and our wrapper generator produced a wrapper for each. We're unlikely to have to generate these again, and the wrappers do need fair amount of manual attention in any case.
> 
> This change should be merged.

Ok, thanks!

2020-03-24 23:30 UTC, sanjoy approved these changes

2020-03-25 02:01 UTC, merged