Tf
tensorflow/tensorflow pull request #37947
Opened 2020-03-26 16:38 UTC by ghosalsattam

This Pull request is to create a basic "gaussian kernel op". It is necessary image processing tool and is often used with other methods like CannyEdgeDetection etcc to reduce noise etc. So it is an important image processing tool.

2020-03-26 16:40 UTC, ghosalsattam commented
@rthadur @tensorflow-jenkins @tensorflower-gardener @tanzhenyu Please provide a review.

2020-03-26 18:34 UTC, mihaimaruseac requested changes
Does this really need to be an addition to TF? Can it be made to TensorFlow Addons instead?

Also, the PR should have tests (https://www.tensorflow.org/community/contribute/tests). Also, read documentation on how to contribute to the code (https://www.tensorflow.org/community/contribute/tests) and the coding style (https://www.tensorflow.org/community/contribute/code_style).

Finally, the additions should not be in the root of the package.

2020-03-26 18:34 UTC, mihaimaruseac commented on .github/workflows/pythonpackage.yml
> +name: Python package
This file should not exist

2020-03-26 18:34 UTC, mihaimaruseac commented on tensorflow/python/keras/layers/convolutional.py
> +<<<<<<< HEAD
Merge conflict markers. These should not be left in the PR

2020-03-27 03:00 UTC, tanzhenyu commented
+1 on making this part of Addons, not TF core.

2020-03-27 03:00 UTC, tanzhenyu commented
Or actually keras-image as a separate repo for image related things, for what it's worth

2020-03-27 04:44 UTC, ghosalsattam commented
I have added the file to keras addons

2020-03-27 16:29 UTC, mihaimaruseac commented
Please change PR title to something relevant. Please move implementation files to obey the layout of the rest of the code.

Please make sure you follow the links mentioned in the previous review and also consider whether this should be a part of TensorFlow Addons instead.

2020-03-31 13:32 UTC, gbaned commented
@ghosalsattam Can you please check @mihaimaruseac's comments and keep us posted. Thanks!

2020-03-31 13:50 UTC, closed without merging

2025-09-02 11:38 UTC, aiswaryasankar commented
**🔒 Entelligence AI Vulnerability Scanner**

✅ **No security vulnerabilities found!**

Your code passed our comprehensive security analysis.

📊 **Files Analyzed**: 3 files

---

2025-09-02 13:14 UTC, mihaimaruseac commented
This is spam, @aiswaryasankar . Please stop or you will be banned