Fix document error for ApplyFtrl, ApplyFtrlV2 and SparseApplyFtrlV2
tensorflow/tensorflow pull request #38020
Opened 2020-03-29 14:24 UTC by blueyi

The implementation of Ftrl optimizer has been updated, but the internal doc is incorrect.

2020-03-29 19:00 UTC, mihaimaruseac requested changes
Can you also point to the commit that changed code? Or the issue this fixes?

2020-03-29 19:00 UTC, mihaimaruseac commented on tensorflow/core/api_def/base_api/api_def_SparseApplyFtrlV2.pbtxt
> +accum_new = accum + grad * grad
Same here

2020-03-30 16:47 UTC, blueyi commented on tensorflow/core/api_def/base_api/api_def_ApplyFtrlV2.pbtxt
> +accum_new = accum + grad * grad
Please reference this commit #https://github.com/tensorflow/tensorflow/commit/20d5683b826be03776978af3b8108fc3b5dc9cb8

2020-03-30 16:55 UTC, blueyi commented on tensorflow/core/api_def/base_api/api_def_SparseApplyFtrlV2.pbtxt
> +accum_new = accum + grad * grad
Also reference here: #https://github.com/tensorflow/tensorflow/commit/20d5683b826be03776978af3b8108fc3b5dc9cb8

2020-05-04 14:34 UTC, gbaned commented
@blueyi, @mihaimaruseac Any update on this PR? Please. Thanks!

2020-05-04 15:40 UTC, mihaimaruseac approved these changes

2020-05-07 18:37 UTC, merged