Add support for attr classes in Dataset
tensorflow/tensorflow pull request #38266
Opened 2020-04-06 13:14 UTC by AdrienCorenflos

See issue: https://github.com/tensorflow/tensorflow/issues/38192
I have not run the tests (can't manage to build tf locally...) but I modified a venv locally and it seems to work on the example attached.

2020-04-06 13:17 UTC, AdrienCorenflos commented
@googlebot I signed it!

2020-04-07 00:16 UTC, aaudiber requested changes
Thanks for contributing this improvement @AdrienCorenflos. Can you add a test to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/kernel_tests/dataset_test.py which tests that `attr.s` classes can be used by `tf.data.Dataset` code?

2020-04-07 00:16 UTC, aaudiber commented on tensorflow/python/data/util/structure_test.py
> +    self.assertEqual(spec.x, tensor_spec.TensorSpec([], dtypes.float32))
Also check `spec.y`

2020-04-07 00:16 UTC, aaudiber commented on tensorflow/python/data/util/structure_test.py
> +
Please add a test for an `ObjectProxy` of `attr.s`, similar to the test for `ObjectProxy` of `namedtuple` below

2020-04-08 13:55 UTC, AdrienCorenflos commented
@aaudiber see https://github.com/tensorflow/tensorflow/pull/38266/commits/c4bf9b0c2ef80b48ac76c7128a3b34cda87f8d0a

2020-04-08 17:48 UTC, aaudiber commented on tensorflow/python/data/util/structure_test.py
> +
nit: extra newline

2020-04-08 17:48 UTC, aaudiber commented on tensorflow/python/data/kernel_tests/dataset_test.py
> +
nit: extra newline

2020-04-08 18:11 UTC, aaudiber approved these changes
LGTM, thanks!

2020-04-09 09:02 UTC, gbaned commented
@AdrienCorenflos Can you please fix build failures ? Thanks!

2020-04-09 09:37 UTC, AdrienCorenflos commented
Hi
How do I know which one of the 1000+ failures and errors is due to my change? There are no logs for errors, just error code 1...

2020-04-09 16:26 UTC, jsimsa commented
If you click on Target Log tab you should see this: 
<img width="1532" alt="Screen Shot 2020-04-09 at 9 26 07 AM" src="https://user-images.githubusercontent.com/1072079/78917770-32fc9400-7a44-11ea-8fbb-159c2adc8cea.png">

2020-04-09 16:29 UTC, aaudiber commented
@AdrienCorenflos you can find the detailed error message under the "Target Log" tab. It looks like the cause of the failures is "ModuleNotFoundError: No module named 'attr'". This is because the `attr` module may not always be available (TF is still in the process of dropping python2 within Google). You can fix this issue by guarding your attr imports with

```
try:
  import attr  # pylint:disable=g-import-not-at-top
except ImportError:
  attr = None
```

and then checking whether attr is None before using it. See function_test.py for an example of doing this: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/function_test.py

2020-04-13 08:22 UTC, gbaned commented
@AdrienCorenflos Can you please check @aaudiber's comments and resolve conflicts?. Thanks!

2020-04-29 01:22 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-05-04 14:40 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-05-04 14:40 UTC, closed without merging

2020-05-04 14:47 UTC, AdrienCorenflos commented
Hi, FYI I have not continued on this one because there is an underlying bug with datasets that needs correcting first (basically you have different behaviours when you do tf.data.Dataset.from_tensor_slices([namedtuples]) vs data.map(namedtuples) which was propagated to my stuff). I will raise a separate issue when I have some time.

2020-05-11 08:52 UTC, AdrienCorenflos commented
@gbaned see this
https://github.com/tensorflow/tensorflow/issues/39403