Fix issue 36146
tensorflow/tensorflow pull request #38283
Opened 2020-04-06 20:28 UTC by tonytonev

Improved error message to clarify why a custom mapping is not being accepted. Fix for issue #36146.

2020-04-06 20:31 UTC, tonytonev reviewed
Fixed according to @mdanatg 's suggestion here: https://github.com/tensorflow/tensorflow/issues/36146#issuecomment-608541085

2020-04-06 20:39 UTC, mdanatg requested changes
Thanks for adding this! Just one suggestion to include as much context information as we can.

2020-04-07 15:16 UTC, mdanatg submitted a review, later dismissed

2020-04-07 18:57 UTC, tonytonev reviewed
@mdanatg it looks like "Ubuntu Sanity" and "MacOS Python2 and CC" CI builds failed for this, but I can't if the reason. What should I do?

2020-04-07 20:16 UTC, mdanatg commented on tensorflow/python/util/nest.py
> +                      f"like {instance}. Note that it must accept a single "
I think the linter fomplains about the f-strings. Due to some internal restrictions, the code still need to be Python2-compatible for a few more months. So we need to use `.format()` instead, for now.

2020-04-07 21:57 UTC, tonytonev commented on tensorflow/python/util/nest.py
> +                      f"like {instance}. Note that it must accept a single "
OK, I updated it to use `.format()`

2020-04-08 00:34 UTC, mdanatg approved these changes

2020-04-10 12:30 UTC, merged