Several Python api-doc examples
tensorflow/tensorflow pull request #38373
Opened 2020-04-09 02:32 UTC by tomasvr

Added examples for several Python API functions.

2020-04-09 15:31 UTC, mihaimaruseac requested changes
We should not add python documentation to the base API definitions. These definitions are visibile on all languages for which we have bindings and it does not make sense to have Python doctests in a C++ documentation, for example

2020-04-10 21:26 UTC, tomasvr commented
I see, sorry I was not aware of that. Is there any way I can make the examples appear only in the Python API docs? Then I could perhaps try to amend it. Thank you for your feedback.

2020-04-14 17:10 UTC, mihaimaruseac commented
See 8582a58

2020-04-24 08:35 UTC, gbaned commented
@tomasvr Can you please check reviewer comments and keep us posted. Thanks!

2020-04-28 14:14 UTC, tomasvr commented
@gbaned I removed the examples from the general API for now. I'm currently preoccupied with new courses so I have to leave the other examples for now.

2020-04-28 17:54 UTC, mihaimaruseac reviewed
The triple backticks (` ``` `) are not needed. https://www.tensorflow.org/community/contribute/docs_ref

2020-04-28 17:54 UTC, mihaimaruseac commented on tensorflow/python/ops/linalg_ops.py
> +  ```
```suggestion

```

2020-04-28 17:54 UTC, mihaimaruseac commented on tensorflow/python/ops/linalg_ops.py
> +  ```
```suggestion
```

2020-04-28 17:55 UTC, mihaimaruseac submitted a review, later dismissed

2020-04-30 00:23 UTC, mihaimaruseac commented
Can you fix the Ubuntu CPU test, please?

2020-05-04 10:57 UTC, gbaned commented
@tomasvr Can you please check @mihaimaruseac comments and keep us posted. Thanks!

2020-05-07 22:08 UTC, tomasvr commented
I am not sure what is causing the Ubuntu CPU to fail. I simply copied the results for the example calculation straight from the actual output of my terminal itself.

2020-05-07 22:20 UTC, tomasvr commented
@gbaned I believe it's fixed now.

2020-05-08 14:14 UTC, gbaned commented
@tomasvr Can you please address Ubuntu Sanity errors? Thanks!

2020-05-28 01:20 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-05-28 10:19 UTC, closed without merging