Reduce code duplication tpu_embedding
tensorflow/tensorflow pull request #38371
Opened 2020-04-08 23:30 UTC by tomasvr

I was browsing over the code of the `tpu_embedding.py` file and noticed some code duplication in the `_validate_generate_enqueue_ops_enqueue_datas_list` method which I thought could be simplified. 
Also removed an unnecessary `else` statement.

Let me know what you think, cheers!

2020-04-09 05:27 UTC, revan requested changes

2020-04-09 05:27 UTC, revan commented on tensorflow/python/tpu/tpu_embedding.py
> +      # Helper function to check device agreement
```suggestion
      """Helper function to check device agreement."""
```

2020-04-09 05:29 UTC, revan approved these changes

2020-04-12 12:58 UTC, tomasvr commented
I see the import/copybara check has failed, but I cannot retrieve any more information regarding this check. Could you please tell me what I can do to resolve this? Thank you in advance.

2020-04-13 21:02 UTC, merged