[compiler] Correct dims_rhs constraint
tensorflow/tensorflow pull request #38398
Opened 2020-04-09 16:49 UTC by gaurav1086

Correct dims_rhs constraint

2020-04-10 03:40 UTC, joker-eph reviewed
Thanks for the fix!

Can you update the test coverage as well?

2020-04-10 14:55 UTC, gaurav1086 commented
@joker-eph thanks for the review. Could you kindly point me to the existing coverage/example for this (type of) functionality ?

2020-04-10 15:40 UTC, joker-eph commented
Here is the current test https://github.com/tensorflow/tensorflow/blob/316054e5c1d71285970951dc097db4d45f1e1567/tensorflow/compiler/mlir/tensorflow/tests/einsum.mlir

2020-04-11 12:35 UTC, gaurav1086 commented
@joker-eph not familiar with the mlir format. Added a test cases (5D), please advise. thank you.

2020-04-11 17:29 UTC, joker-eph approved these changes

2020-04-11 17:29 UTC, joker-eph commented on tensorflow/compiler/mlir/tensorflow/tests/einsum.mlir
> +// CHECK: return %[[v0]]
You can just limit yourself to `// CHECK: %[[v0:.*]] = "tf.Einsum"` ; the rest of the line does not matter in this test I believe: we just want to make sure that Einsum isn't replaced.

2020-04-11 17:29 UTC, joker-eph commented on tensorflow/compiler/mlir/tensorflow/tests/einsum.mlir
> +// CHECK-LABEL: einsum_no_match2
This needs to be einsum_no_match5D

2020-04-11 17:29 UTC, joker-eph requested changes
(test needs update)

2020-04-11 17:51 UTC, joker-eph approved these changes

2020-04-13 16:23 UTC, merged