Fix invalid shape issue in random.uniform
tensorflow/tensorflow pull request #38585
Opened 2020-04-16 02:56 UTC by yongtang

Note: This PR is a resubmission from #34399

This PR tries to address the issue raised in #34363 where
invalid shape passed to minval/maxval (expected to be 0-D)
does not raise an error.

The issue was that in most of the scenarios the shape was
checked inside the C++ kernel ops.

However, in one condition math_ops.add was used which will
implicitly do broadcast when necessarily.
This results in maxval/minval's shape getting carried.

This PR adds the shape check before math_ops.add, to make
sure the shape is guaranteed.

This PR fixes #34363.

Signed-off-by: Yong Tang yong.tang.github@outlook.com

2020-04-16 15:24 UTC, alextp commented on tensorflow/python/ops/random_ops.py
> +        maxval = array_ops.ensure_shape(maxval, ())
Doesn't this prevent us from making broadcast-correct randomuniform? As in, if I'm asking for a random uniform with shape [a, b] I should be able to have maxval/minval with any shape which broadcasts to [a, b] as we can broadcast the elementwise operations

2020-04-17 19:38 UTC, yongtang commented
Thanks @alextp for the review. After looking through the API,  the PR has been changed to explicitly calling `broadcast_to` before the
```
+        maxval = array_ops.broadcast_to(maxval, shape)
+        minval = array_ops.broadcast_to(minval, shape)
         result = math_ops.add(result * (maxval - minval), minval, name=name)
```

Since `broadcast_to` will return invalid argument error if maxval or minval is larger than the original shape, this will fix the issue #34363, and avoid the restriction of minval and maxval (could be any shape as long as broadcast makes sense and will not 'overflow' after broadcast).

The PR has been updated. Please take a look and see if this works.

2020-04-17 20:56 UTC, alextp submitted a review, later dismissed

2020-04-28 07:18 UTC, gbaned commented
Here are the internal errors, @yongtang can you please verify ?

Traceback (most recent call last):
  File "/third_party/py/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/third_party/py/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "/learning/brain/contrib/slim/model_analyzer_test.py", line 72, in testNoBias
    model_analyzer.analyze_ops(g))
  File "<embedded stdlib>/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "<embedded stdlib>/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 3202 != 4000L

2020-05-05 15:36 UTC, yongtang commented
@gbaned @alextp sorry for the late reply. 

The internal test failure is not very straightforward. I am wondering if is it possible to share the code of the internal test  `testNoBias` in file `/learning/brain/contrib/slim/model_analyzer_test.py`?

I assume this is a test related to `tf.contrib.slim`. Given `tf.contrib.slim` has been removed in 2.x, I searched the history of 1.x branch in tensorflow. However, I am not able to locate the `model_analyzer_test.py` file. There is only a `model_analyzer.py` file which might be related. I also could not find a `testNoBias`.

If there are some code available I think I might be quickly find out the reason for the failure.

My wild guess is that the failure is caused by the fact that the following actually adds two more nodes in the graph:
```
        maxval = array_ops.broadcast_to(maxval, shape)
        minval = array_ops.broadcast_to(minval, shape)
```

But without code it is really hard to say what will be the right fix.

2020-05-05 15:44 UTC, alextp commented
It should be safe to disable this test internally.

2020-05-11 20:00 UTC, yongtang commented
@gbaned Any update on this PR? From the comment https://github.com/tensorflow/tensorflow/pull/38585#issuecomment-624133713 I think the internal test failure could be just ignored?

/cc @alextp

2020-05-22 00:34 UTC, rthadur approved these changes

2020-05-26 22:09 UTC, rthadur requested changes
@yongtang can you please check the internal error ?

2020-05-26 22:09 UTC, rthadur commented on tensorflow/python/kernel_tests/random/random_ops_test.py
> +
`tensorflow/python/framework/ops.py", line 1820, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
google3.third_party.tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be at most rank 0 but is rank 1 for '{{node random_uniform/BroadcastTo_1}} = BroadcastTo[T=DT_FLOAT, Tidx=DT_INT32](zeros, random_uniform/shape)' with input shapes: [1], [0].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<embedded stdlib>/unittest/case.py", line 59, in testPartExecutor
    yield
  File "<embedded stdlib>/unittest/case.py", line 605, in run
    testMethod()
  File "tensorflow/python/framework/test_util.py", line 1785, in decorated
    return func(self, *args, **kwargs)
  File "/tensorflow/python/kernel_tests/random/random_ops_test.py", line 425, in testUniformWithInvalidMaxMindShape
    random_ops.random_uniform(shape=(), minval=array)
  File "//tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "tensorflow/python/ops/random_ops.py", line 312, in random_uniform
    minval = array_ops.broadcast_to(minval, shape)
  File "/tensorflow/python/ops/gen_array_ops.py", line 854, in broadcast_to
    "BroadcastTo", input=input, shape=shape, name=name)
  File "/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "//tensorflow/python/framework/ops.py", line 3493, in _create_op_internal
    op_def=op_def)
  File "/tensorflow/python/framework/ops.py", line 1983, in __init__
    control_input_ops, op_def)
  File "//tensorflow/python/framework/ops.py", line 1823, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be at most rank 0 but is rank 1 for '{{node random_uniform/BroadcastTo_1}} = BroadcastTo[T=DT_FLOAT, Tidx=DT_INT32](zeros, random_uniform/shape)' with input shapes: [1], [0].`

2020-05-26 23:40 UTC, yongtang commented
Thanks @rthadur. I think the issue is caused by different error checking in graph vs eager mode so the exception message is slightly different. I have updated the PR that should cover both (I think). Please give it a try and let me know if the issue still persists.

2020-05-27 00:51 UTC, rthadur submitted a review, later dismissed

2020-05-27 03:48 UTC, rthadur commented
@yongtang this test is still failing internally , please check 
`tensorflow/python/framework/test_util.py", line 1785, in decorated
    return func(self, *args, **kwargs)
  File "//tensorflow/python/kernel_tests/random/random_ops_test.py", line 423, in testUniformWithInvalidMaxMindShape
    random_ops.random_uniform(shape=(), minval=array)
  File "//tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)`

2020-05-27 15:11 UTC, yongtang commented
Thanks @rthadur Is it possible that you can post the full output of the error message? I think you might be only posting a part of it and it is hard to see where the error is.

2020-05-27 18:33 UTC, rthadur commented
Sure , here it is 
`/tensorflow/python/framework/test_util.py", line 1785, in decorated
    return func(self, *args, **kwargs)
  File "/tensorflow/python/kernel_tests/random/random_ops_test.py", line 423, in testUniformWithInvalidMaxMindShape
    random_ops.random_uniform(shape=(), minval=array)
  File "//tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "//tensorflow/python/ops/random_ops.py", line 312, in random_uniform
    minval = array_ops.broadcast_to(minval, shape)
  File "/tensorflow/python/ops/gen_array_ops.py", line 836, in broadcast_to
    _ops.raise_from_not_ok_status(e, name)
  File "/tensorflow/python/framework/ops.py", line 6831, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
google3.third_party.tensorflow.python.framework.errors_impl.UnknownError: error running delegate kernel tf.BroadcastTo: Rank of input (1) must be no greater than rank of output shape (0). [Op:BroadcastTo]`

2020-05-27 19:01 UTC, yongtang commented
Thanks @rthadur. I have updated the PR with additional test failure covered. Please give it a try and see if it works now.

2020-05-27 19:36 UTC, alextp approved these changes

2020-05-27 21:00 UTC, rthadur commented
Seems auto-merge is not happening but the changes are now committed so we can close this. Thank you for the PR.

2020-05-27 21:00 UTC, closed without merging

2020-05-27 21:17 UTC, yongtang commented
Thanks all for the help! 👍 🎉

2020-05-27 22:20 UTC, mihaimaruseac commented
Hmm, internal testing on private code was broken by this so it got reverted. I'll try to merge manually this week/next one.

2020-05-27 22:24 UTC, yongtang commented
@mihaimaruseac Thanks. 👍 Let me know if I can be of any help.