Grpc server uses provided host name/ip instead of localhost if possible
tensorflow/tensorflow pull request #38600
Opened 2020-04-16 10:46 UTC by fesun

Now grpc server ignores use provided host name/ip and always return "localhost" as server target. This makes cluster spec propagation propagates "localhost" to remote. See #38519

2020-04-28 08:51 UTC, byronyi commented
Ping @haoyuz; any updates?

2020-04-28 17:06 UTC, haoyuz requested changes
Thank you for the PR!

2020-04-29 02:23 UTC, fesun commented on tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc
> +  string host_name;
To align requested_port, I will host_name_ if you'd prefer.

2020-04-29 02:49 UTC, haoyuz approved these changes

2020-04-29 02:50 UTC, haoyuz commented
Adding @bramandia to take another look (assigned in the original issue #38519).

2020-05-04 10:53 UTC, gbaned commented
@bramandia Can you please review this PR ? Thanks!

2020-05-09 02:52 UTC, fesun commented
@bramandia Could you please take a look at this? Thanks!

2020-05-10 00:51 UTC, bramandia approved these changes

2020-05-10 00:52 UTC, bramandia commented
> @bramandia Could you please take a look at this? Thanks!
Done.

Sorry for the delay, this went to my personal email instead.

2020-05-18 18:33 UTC, merged