Change code examples in tf.strings.format to use TF 2.x
tensorflow/tensorflow pull request #38895
Opened 2020-04-25 18:21 UTC by yongtang

The code examples in tf.strings.format still uses 1.x (`tf.compat.v1`)
which is not appropriate now.

This PR changes code examples in tf.strings.format to use TF 2.x.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2020-04-28 00:25 UTC, mihaimaruseac requested changes
LGTM but let's convert to doctests using `>>> ` format: https://www.tensorflow.org/community/contribute/docs_ref

2020-04-28 17:52 UTC, mihaimaruseac commented on tensorflow/python/ops/string_ops.py
> +    >>> assert(formatted == expected)
We don't need the assertion written explicitly. The following should work (modulo some output change):

```suggestion
    >>> formatted = tf.strings.format("tensor: {}, suffix", tensor)
    "tensor: [0 1 2 ... 7 8 9], suffix"
```

We should do the same for the other doctests below

2020-04-28 18:38 UTC, mihaimaruseac submitted a review, later dismissed

2020-04-28 18:38 UTC, mihaimaruseac commented on tensorflow/python/ops/string_ops.py
> +    >>> print(formatted)
```suggestion
    >>> tf.strings.format("tensor: {}, suffix", tensor)
```

2020-04-28 18:38 UTC, mihaimaruseac commented on tensorflow/python/ops/string_ops.py
> +    >>> print(formatted)
```suggestion
    >>> tf.strings.format("first: {}, second: {}, suffix",
    ...                               (tensor_one, tensor_two))
```

2020-04-28 18:39 UTC, mihaimaruseac submitted a review, later dismissed
Thank you

2020-04-29 07:54 UTC, gbaned commented
@yongtang Can you please address Ubuntu Sanity errors? Thanks!

2020-04-30 00:00 UTC, yongtang commented
Thanks @mihaimaruseac @gbaned for the help. I have updated the PR. The previous failure was caused by the fact that doctest does not use "```" to locate the code block anymore (use ">>>" and "...") instead. I have removed the redundant "```" that was causing the test failure in the PR.

Please take a look and let me know if there are any other issues.

2020-04-30 00:41 UTC, mihaimaruseac commented on tensorflow/python/ops/string_ops.py
> +    >>> tensor_one = tf.reshape(tf.range(100), [10, 10])
Let's try a shorter range so that we don't need to have a line too long and disable pylint

2020-04-30 00:54 UTC, yongtang commented
Thanks @mihaimaruseac, the PR has been updated with a shorter example and the pylint disable has been removed as well.

2020-04-30 15:50 UTC, mihaimaruseac approved these changes

2020-05-01 20:28 UTC, rthadur approved these changes

2020-05-01 21:29 UTC, merged