[XLA] Remove cross device nodes from clusters
tensorflow/tensorflow pull request #38911
Opened 2020-04-26 10:33 UTC by zhuzilin

This is a PR from JIZHI, the AI platform in Tencent.

This pr removes the the cross device nodes (nodes that have input or output from
other device) from the compilation candidates in `MarkForCompilation`. The reason for this change is that if the cross device nodes are introduced into clusters, the following 2 situation may happen and largely harm the performance.
```
  device0:  op1 ---    op2        cluster(op1, op2) ---
                  |          ===>                     |
  device1:        ---> op3                            ---> op3

  or

  device0:  op1   ---> op2              ---> cluster(op1, op2)
                  |          ===>       |
  device1:  op3 ---               op3 ---
```
XLA will delay the execution of an op when one of its predecessors is merged in the middle of a cluster. This delay will be ok when the op and the cluster are on the same device, because their kernels are executed sequentially. But when using multiple devices, this delay will make one device wait. For example, this is the timeline of a transformer model:
Before removing cross device nodes:
![image](https://user-images.githubusercontent.com/10428324/80304808-105fce80-87eb-11ea-845d-473d9397c421.png)
After removing cross device nodes:
![image](https://user-images.githubusercontent.com/10428324/80304824-29687f80-87eb-11ea-8712-bca355333d52.png)
The alternative way to solve this problem is to add more condition in `TryToContract`. However,  that will result in larger modification because we need to save the device information of all nodes in a cluster. If you prefer this way, we are also glad to help.

Thank you for your time on reviewing this pr.

2020-05-19 23:37 UTC, cheshire reviewed
Is it possible to write a test for this?

2020-05-20 08:12 UTC, zhuzilin commented
> Is it possible to write a test for this?

I'd love to do that. What I need is a test like the `XlaCompilationTest` in `mark_for_compilation_pass_test.cc`, right?

2020-05-21 08:28 UTC, zhuzilin commented
@cheshire I found tests like `CreateCombinedCpuGpuClusters` and `ClusterResourceOpsWhenSafe` where cluster across device is allowed. Should XLA be able to cluster in this way? If that's the case, I need to change accordingly. The main purpose of this pr is to solve the TODO in `NOT_DontClusterSpreadingNodes`.

2020-05-21 17:34 UTC, cheshire commented
> For example, this is the timeline of a transformer model

BTW for BERT specifically we have found we were able to get better performance with `tf.function(experimental_compile=True)`: https://github.com/tensorflow/models/blob/master/official/nlp/modeling/layers/transformer.py#L228

> Should XLA be able to cluster in this way? 
I'm actually not sure;
 @sanjoy any comments?
But in general if you are changing behavior it needs to be tested

2020-05-21 19:42 UTC, sanjoy commented
Generally we only allow one kind of cross device cluster: if one device is a GPU and another device is the CPU.  We don't allow a single cluster to have ops that are placed on different GPUs.

Btw, your case should have been handled by [this logic](https://github.com/tensorflow/tensorflow/blob/37ab9c3bfcbb278ae003cf32f08b3d41a78401a7/tensorflow/compiler/jit/mark_for_compilation_pass.cc#L1375), do you know why it didn't?

2020-05-28 01:36 UTC, zhuzilin commented
@sanjoy The `ClusteringWillIntroduceInterDeviceDependency` only deal with the cross device edge between XLA clusters and for my case, the "op3" is not in one of the clusters.
I do think the code in this pr may remove too much ops and we need to come up with a better solution. Any thoughts on how to deal with the case when "op3" is not clustered? An alternative way I can think of is saving the output devices and input devices of all clusters to help with contraction.

2020-05-28 09:51 UTC, tpopp commented
One nit to Sanjoy's comment. We don't have clusters using multiple devices as far as I know. But in the case of GPU/CPU, we will move the CPU ops to the GPU if possible to make a larger cluster.

I also don't think the problem is that `ClusteringWillIntroduceInterDeviceDependency` only works with clusters at a basic level. It is generally assumed that any individual Op is much less expensive than a cluster of many ops. If OP2 and OP1 become CLUSTER2 and CLUSTER1, and OP2 depends on OP3 as in example 2, clustering of CLUSTER2 and CLUSTER1 shouldn't cause much problems because it is assumed that OP3 is relatively cheap (which is not assumed if OP3 is instead CLUSTER3). This isn't always reality because maybe OP3 has CLUSTER4 as an input, in which case there suddenly becomes a transitive dependency from CLUSTER4 -> (CLUSTER1, CLUSTER2) when previously it was only CLUSTER4 -> CLUSTER2. This new solution does catch that case and helps, but at the same time, if OP3 is always ReadVariable and doesn't depend on CLUSTER4, then this change is hurting performance.

Regarding this approach, `ClusteringWillIntroduceInterDeviceDependency` only handles the second example because the straighforward way of handling the first case caused large regressions in multi-gpu resnet through breaking clusters into many pieces. Since this approach is the same but potentially breaking clusters even more, I would expect the same result.

I'll try to think about this more and respond, but generally I expect this won't be acceptable as is because breaking apart clusters in this way will make some layouts improve and some layouts regress (and in this case I expect resnet to regress which is important). That is the general result with all of this autoclustering though because it is impossible to have a generally optimal clustering function without a cost function. And I'm not even sure if it's possible to have an optimal solution with reasonable compile time even if we assume all nodes cost the same amount of time.  This is all my long winded way of saying that I don't know of an ideal solution, and because I have constructed pros and cons for every clustering conditions I've thought of so far, I would generally require/settle for proof that the most common models are generally improving with the autoclustering changes.

Also, if you haven't tried `TF_XLA_FLAGS=--tf_xla_auto_jit=fusible` I would recommend trying it and seeing if this alternative clustering strategy helps in this case.

2020-06-02 15:08 UTC, gbaned commented
@sanjoy  Any update on this PR? Please. Thanks!

2020-06-03 17:39 UTC, tpopp commented
The benchmark where a similar change caused problems did not show problems with this change, so I will run a larger suite of benchmarks tomorrow to confirm nothing else has problems, but presumably they won't show any problems as they're for 1-gpu models, and we can review this and look into submitting it.

Just be warned that changes like these around autoclustering have a larger chance of triggering complaints after at which point we might have to rollback if other important models are found to have large regressions with this change.

2020-06-03 17:47 UTC, tpopp reviewed
I will approve this after confirming that other benchmarks do not have large regressions.

2020-06-04 02:12 UTC, zhuzilin commented
@tpopp 
Thank you for your benchmarking and review. I've changed the code to `absl::c_any_of`. Could you have another look?
> Just be warned that changes like these around autoclustering have a larger chance of triggering complaints after at which point we might have to rollback if other important models are found to have large regressions with this change.

I totally understand and agree with this.

2020-06-08 16:37 UTC, tpopp commented
The code looks good.

The one issue now is that 11 test cases fail because less clustering happens now in `tensorflow/compiler/jit:compilation_passes_test` I don't have a good solution for a quick fix to these tests.

NOT_DontClusterSpreadingNodes Also should become DontClusterSpreadingNodes and the last check would be inverted.

2020-06-09 04:31 UTC, zhuzilin commented
@tpopp 
I've checked the test failures. 
3 of them is due the nodes connected to `_SOURCE` or `_SINK` which may have different device assigned and can be fix by ignoring the edges with `_SOURCE` or `_SINK` involve. The remaining are:
```
[==========] 135 tests from 12 test suites ran. (16741 ms total)
[  PASSED  ] 127 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] XlaCompilationTest.CallXlaDeviceFuncWithResourceOp
[  FAILED  ] XlaCompilationTest.TensorArrayShapeOnXlaDevice
[  FAILED  ] XlaCompilationTest.DontClusterMergingNodes
[  FAILED  ] XlaCompilationTest.DontClusterMergingNodesOnCPU
[  FAILED  ] XlaCompilationTest.NOT_DontClusterSpreadingNodes
[  FAILED  ] XlaCompilationTest.CreateCombinedCpuGpuClusters
[  FAILED  ] XlaCompilationTest.ClusterResourceOpsWhenSafe
[  FAILED  ] XlaCompilationTest.ClusterShapeConsumerWithProducer
```
The reasons of error in them are:
- `CallXlaDeviceFuncWithResourceOp`: `/job:worker/replica:0/task:0/device:XLA_CPU:0` is not compatible with `/job:localhost/replica:0/task:0/cpu:0`.
- `TensorArrayShapeOnXlaDevice`: `placeholder` is on cpu while `test/reshape` is on gpu, this pr will remove `test/reshape` from the cluster.
- `DontClusterMergingNodes` and `NOT_DontClusterSpreadingNodes` are meant to be changed for this pr.
- `CreateCombinedCpuGpuClusters`: `test/x` has connection with cpu while it is on gpu. This also has the problem whether we will allow clusters that cross cpu and gpu.
- `ClusterResourceOpsWhenSafe`: `test/b` is a cross-cpu-and-gpu op.
- `ClusterShapeConsumerWithProducer`: `test/y` is a cross-cpu-and-gpu op.

I think we may need to change 7 of them and figure out a way to make "cpu:0" and "XLA_CPU"0" compatible. I wonder if those two device will appear at the same time in production?

As for the `_SOURCE` and `_SINK` related condition, I've tried with
```c++
    // skip nodes that have cross device edges.
    auto is_cross_device_edge = [](const Edge* e) {
      auto src = e->src();
      if (src->name() == "_SOURCE")
        return false;
      auto dst = e->dst();
      if (dst->name() == "_SINK")
        return false;
      return !src->assigned_device_name().empty() &&
             !dst->assigned_device_name().empty() &&
             src->assigned_device_name() != dst->assigned_device_name();
    };
```

2020-06-09 21:38 UTC, tpopp commented
>This also has the problem whether we will allow clusters that cross cpu and gpu.

I'm actually surprised that I didn't see benchmark regressions now that I think about this. I personally would vote for still making CPUs special and allowing them through because there was good reason at the time, but I won't block you doing otherwise if I don't see a benchmark regression (like was currently the case).

> and figure out a way to make "cpu:0" and "XLA_CPU"0" compatible. I wonder if those two device will appear at the same time in production?

Those two devices can occur together, but I don't think they can to be clustered. In `CallXlaDeviceFuncWithResourceOp` It looks like just an unfortunate case of not having enough ops to be clustered now that the ops along the edge of a device boundary aren't clustered. In theory, it would be nice to realize they're both on CPU, but that's more a shortcoming of TF->XLA's symbolic devices, and I don't think you need to feel responsible to handle that because I suspect it would involve either a lot of work or a hardcoded check between the names. (I might have misinterpreted the problem though)

There should be:
`src->IsSource()` and `src->IsSink()` and an `src->IsOp()` (which returns Not (IsSink() || IsSource()) ) by the way.

2020-06-10 03:06 UTC, zhuzilin commented
@tpopp 
I've changed the test according to this pr. Right now there should be no building failure related to the new cluster rule.
> I personally would vote for still making CPUs special and allowing them through because there was good reason at the time, but I won't block you doing otherwise if I don't see a benchmark regression (like was currently the case).

For simplicity, I remain removing all cpu ops because it may require the same "hardcoded check between the names".

2020-06-15 15:46 UTC, tpopp requested changes
Sorry for the delay. I had some holidays last week.

I don't know how this github approval works. A few of these test cases can be deleted now and then it looks good to go.

2020-06-15 15:46 UTC, tpopp commented on tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> +  EXPECT_EQ(clusters["A"], "");
You can delete this test since we will now not compile functions with resource variables as input.

2020-06-15 15:46 UTC, tpopp commented on tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
>  // TODO(b/117085735): This form of clustering should be prevented.
You can delete this TODO and remove the "NOT_"

2020-06-15 15:46 UTC, tpopp commented on tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> +  EXPECT_EQ(clusters["test/x"], "");
You can delete this test case, now that it's not supported (this is just checking that nothing was clustered).

2020-06-15 15:46 UTC, tpopp commented on tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> +  EXPECT_EQ(clusters["test/b"], "");
Can you add a `TODO(tpopp): See if this test case should be deleted or changed`

2020-06-15 15:46 UTC, tpopp commented on tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> +  EXPECT_EQ(clusters["test/y"], "");
This is also checking that nothing is clustered, so it can be deleted.

2020-06-15 15:58 UTC, marko-radojcic commented
Dedicated hardware? I love it.

On Mon, Jun 15, 2020, 5:55 PM Tres <notifications@github.com> wrote:

> *@tpopp* requested changes on this pull request.
>
> Sorry for the delay. I had some holidays last week.
>
> I don't know how this github approval works. A few of these test cases can
> be deleted now and then it looks good to go.
> ------------------------------
>
> In tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> <https://github.com/tensorflow/tensorflow/pull/38911#discussion_r440257135>
> :
>
> > @@ -322,7 +322,7 @@ TEST(XlaCompilationTest, CallXlaDeviceFuncWithResourceOp) {
>        MarkForCompilationPassTestHelper::MarkForCompilation(&graph, &flib_def));
>    auto clusters = GetClusters(*graph);
>
> -  EXPECT_NE(clusters["A"], "");
> +  EXPECT_EQ(clusters["A"], "");
>
> You can delete this test since we will now not compile functions with
> resource variables as input.
> ------------------------------
>
> In tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> <https://github.com/tensorflow/tensorflow/pull/38911#discussion_r440260473>
> :
>
> >    std::unordered_map<string, string> clusters = GetClusters(*graph);
> -  EXPECT_NE(clusters["MatMul0_dev0"], clusters["MatMul1_dev1"]);
> -  EXPECT_NE(clusters["MatMulCombined_cpu"], clusters["MatMul0_dev0"]);
> -  EXPECT_NE(clusters["MatMulCombined_cpu"], clusters["MatMul1_dev1"]);
> -  EXPECT_EQ(clusters["A_dev0"], clusters["MatMul0_dev0"]);
> -  EXPECT_EQ(clusters["B_dev1"], clusters["MatMul1_dev1"]);
> +  EXPECT_EQ(clusters["MatMulCombined_cpu"], "");
> +  EXPECT_EQ(clusters["MatMul0_dev0"], "");
> +  EXPECT_EQ(clusters["MatMul1_dev1"], "");
>  }
>
>  // TODO(b/117085735): This form of clustering should be prevented.
>
> You can delete this TODO and remove the "NOT_"
> ------------------------------
>
> In tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> <https://github.com/tensorflow/tensorflow/pull/38911#discussion_r440262279>
> :
>
> > @@ -1379,7 +1371,7 @@ TEST(XlaCompilationTest, CreateCombinedCpuGpuClusters) {
>
>    std::unordered_map<string, string> clusters = GetClusters(*graph);
>
> -  EXPECT_NE(clusters["test/x"], "");
> +  EXPECT_EQ(clusters["test/x"], "");
>
> You can delete this test case, now that it's not supported (this is just
> checking that nothing was clustered).
> ------------------------------
>
> In tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> <https://github.com/tensorflow/tensorflow/pull/38911#discussion_r440267896>
> :
>
> > @@ -1451,8 +1443,7 @@ TEST(XlaCompilationTest, ClusterResourceOpsWhenSafe) {
>
>    std::unordered_map<string, string> clusters = GetClusters(*graph);
>
> -  EXPECT_NE(clusters["test/b"], "");
> -  EXPECT_EQ(clusters["test/b"], clusters[resource_read_name]);
> +  EXPECT_EQ(clusters["test/b"], "");
>
> Can you add a TODO(tpopp): See if this test case should be deleted or
> changed
> ------------------------------
>
> In tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> <https://github.com/tensorflow/tensorflow/pull/38911#discussion_r440270333>
> :
>
> > @@ -1562,9 +1553,9 @@ TEST(XlaCompilationTest, ClusterShapeConsumerWithProducer) {
>
>    std::unordered_map<string, string> clusters = GetClusters(*graph);
>
> -  EXPECT_NE(clusters["test/y"], "");
> -  EXPECT_EQ(clusters["test/x"], clusters["test/y"]);
> -  EXPECT_NE(clusters["test/z"], clusters["test/y"]);
> +  EXPECT_EQ(clusters["test/y"], "");
>
> This is also checking that nothing is clustered, so it can be deleted.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/38911#pullrequestreview-430751763>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIT525RGG3YN75B6FBNOJV3RWY76FANCNFSM4MRFLIWQ>
> .
>

2020-06-16 01:18 UTC, zhuzilin commented
@tpopp 
I've removed those tests. Could you have another look :).

2020-06-16 10:46 UTC, tpopp approved these changes

2020-06-16 13:10 UTC, gbaned commented
@zhuzilin Can you please fix build failures ? Thanks!

2020-06-16 13:56 UTC, zhuzilin commented
@gbaned I'd love to.
@tpopp I've just checked the building errors. All of them seem to have nothing to do with the change made in this pr. Instead, they have triggered the following error:
```
2020-06-16 12:07:21.049677: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at xla_compile_on_demand_op.cc:209 : Invalid argument: Unsupported type in DataTypeToPrimitiveType: 'variant'
Fatal Python error: Segmentation fault
```
Do you have any idea the cause of this problem? Thank you :).

2020-06-16 13:58 UTC, marko-radojcic commented
Compile on Android tablet?

On Tue, 16 Jun 2020, 15:57 Zilin Zhu, <notifications@github.com> wrote:

> @gbaned <https://github.com/gbaned> I'd love to.
> @tpopp <https://github.com/tpopp> I've just checked the building errors.
> All of them seem to have nothing to do with the change made in this pr.
> Instead, they have triggered the following error:
>
> 2020-06-16 12:07:21.049677: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at xla_compile_on_demand_op.cc:209 : Invalid argument: Unsupported type in DataTypeToPrimitiveType: 'variant'
> Fatal Python error: Segmentation fault
>
> Do you have any idea the cause of this problem? Thank you :).
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/38911#issuecomment-644782869>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIT525T6TQ5U3TOKLWZMJQDRW523PANCNFSM4MRFLIWQ>
> .
>

2020-06-17 16:43 UTC, tpopp commented
I didn't get time today to look into this very deeply but did confirm it's from this PR.

 I think the current location of the check is preventing ops from being compiled that have AlwaysCompile semantics, and this check needs to be moved to inside the CrossDeviceDependency check or similar to still create 1 op clusters when needed. I could be wrong, but that's my guess.

2020-06-18 02:19 UTC, zhuzilin commented
@tpopp 
Sorry that I'm not familiar with the "AlwaysCompile" semantic... However, I found out that there are test errors for both gpu and cpu tests (like add_n_test_cpu) and for cpu ones, I think there shouldn't be any cross device edges.
BTW, could you tell me how to run the `add_n_test`? I tried to use bazel build and run the binary but it exited with:
```
  File "/root/ttensorflow/bazel-bin/tensorflow/compiler/tests/add_n_test_gpu.runfiles/org_tensorflow/tensorflow/compiler/tests/xla_test.py", line 89, in __init__
    for name in FLAGS.types.split(',')
AttributeError: 'NoneType' object has no attribute 'split'
```
The error is caused by the flag in `xla_test.py`, but I couldn't pass the flag to the binary...

2020-06-18 12:15 UTC, tpopp commented
If `bazel run` or `bazel test` work for you, I would recommend that. These tests need additional arguments that are encoded in the BUILD and bzl files and are automatically added. In this case, it looks like you would need something like `--test_device=XLA_GPU --types=DT_HALF,DT_FLOAT,DT_DOUBLE,DT_UINT8,DT_QUINT8,DT_INT8,DT_QINT8,DT_INT32,DT_QINT32,DT_INT64,DT_BOOL,DT_COMPLEX64,DT_COMPLEX128`

Regarding AlwaysCompile, devices in Tensorflow don't have to correspond to just concepts like "CPU" and "GPU".  If you look here (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/jit/mark_for_compilation_pass.cc#L1629), you'll see `registration->autoclustering_policy` and `XlaOpRegistry::AutoclusteringPolicy::kAlways` which is a concept that you might have a device "XLA_GPU" device which requires that all ops on it be compiled, or you might take a specific node in the tensorflow graph and set it to always be compiled as checked by `cluster.is_xla_compile_attr_true()`.

So I believe in this case, the operations are being forcefully put on "XLA_CPU" and "XLA_GPU", but then this new code prevents them from ever being put in a cluster, so they are never compiled like we want. What should be acceptable instead is putting all these ops in clusters, but then possibly never combining them with other clusters. Then the cluster is only the single op, so no dependencies are created like you desire with this PR, but they are still in a "cluster" which is compiled like the devices require.

2020-06-18 12:16 UTC, tpopp commented
One thing I forgot to clarify. In this example, the CPU test still fails because "CPU" and "XLA_CPU" are different "devices" even though they will end up running on the same hardware.

2020-06-22 13:10 UTC, gbaned commented
@zhuzilin Can you please check @tpopp's comments and keep us posted. Thanks!

2020-06-22 14:00 UTC, zhuzilin commented
@gbaned Sorry for the delay...
@tpopp Thank you for these detailed explanation. I also agree that allowing those ops with cross-device edges inside a cluster but stopping them from merging may be a better way to walk around these tests. In that case, we will need to add a new attribute to `Cluster` that shows the input devices and output devices of it. Any if we separate the input devices and output devices, we can allow cluster A and B be merged when only B has a cross device output and A is an input of B. Any suggestion on the design? or maybe we need a new pr thread for that?

2020-06-25 18:11 UTC, tpopp commented
Hi,

sorry for the delay in response on my side. I haven't had time to think this through, so I can't say how I would solve this if I were implementing this. After checking with cheshire though, I think the issue is that we can't have a VARIANT type as a value living out of a cluster, so the issue might not be specifically the lack of ops being clustered, but the test expecting certain ops to not be on the edge of a cluster.

I think your idea for the clusters work. I also think the performance will not be an issue if you walk through all the input/output nodes to a cluster each time and look at their devices, though I could be wrong.

Regarding a new PR, I don't know what Tensorflow's policy is on that. If no one complains, I'm not going to complain though.

2020-06-26 03:49 UTC, zhuzilin commented
Ok. I'll close this pr for now and will propose another design.

2020-06-26 03:49 UTC, closed without merging