Improve android sample
tensorflow/tensorflow pull request #39073
Opened 2020-05-01 08:26 UTC by hannesa2

It doesn't build out of the box

* enable build on command line
* Remove an unused and error causing class
* Update to forced necessary Gradle version

2020-06-02 15:13 UTC, gbaned commented
@caisq, Can you please take a look this PR ? Thanks!

2020-06-02 15:15 UTC, caisq commented
@gbaned I don't think I have the necessary background and expertise to review this PR. Can you check with experts such as @petewarden or @miaout17 ?

2020-06-02 15:17 UTC, hannesa2 commented
The breaking change was to delete this file 
`tensorflow/java/src/main/java/org/tensorflow/op/core/Zeros.java` 
It was preventing form successful build

2020-06-03 13:21 UTC, hannesa2 commented
` ./gradlew clean build`

show now

<img width="413" alt="image" src="https://user-images.githubusercontent.com/3314607/83641484-e77ee600-a5ad-11ea-9517-af0e13fa79b8.png">

2020-07-14 23:34 UTC, frankchn approved these changes

2020-07-22 17:27 UTC, frankchn commented
@hannesa2 What is the build error when `Zeros.java` is left alone? We do have users who are using code in `Zeros.java` so we can't delete it.

2020-07-22 17:28 UTC, frankchn requested changes

2020-07-22 17:28 UTC, frankchn commented on tensorflow/java/src/main/java/org/tensorflow/op/core/Zeros.java
> -/* Copyright 2018 The TensorFlow Authors. All Rights Reserved.
We checked and we have internal users using this code, so we can't delete it.

2020-07-22 17:39 UTC, hannesa2 commented
> @hannesa2 What is the build error when `Zeros.java` is left alone? We do have users who are using code in `Zeros.java` so we can't delete it.

@frankchn 
## A: This is the first error

<img width="937" alt="image" src="https://user-images.githubusercontent.com/3314607/88209154-922c9000-cc52-11ea-8ed6-63b5b8d885f0.png">

## B: After solving A

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/3314607/88209385-ed5e8280-cc52-11ea-900d-f19209781d3d.png">

Because I don't know your internal structure, I can't solve it to fulfill internal and external build

2020-07-22 18:22 UTC, frankchn commented
@hannesa2 Have you tried importing `org.tensorflow.op.core.Fill` to `Zeros.java` to resolve that error instead?

2020-07-22 18:24 UTC, frankchn commented
Note that `Fill` is a generated class, so you might have to run some generator in your environment in order for that symbol to resolve. I suspect you have to change/add gradle settings for that to work.

2020-07-22 18:32 UTC, hannesa2 commented
> org.tensorflow.op.core.Fill

Still the same
<img width="431" alt="image" src="https://user-images.githubusercontent.com/3314607/88214373-60b7c280-cc5a-11ea-8e72-ac45635db47e.png">

2020-07-22 18:32 UTC, frankchn commented
There is a test for `Zeros.java` at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/test/java/org/tensorflow/op/core/ZerosTest.java so you might want to make sure the test can pass too.

2020-07-22 18:37 UTC, hannesa2 commented
> There is a test for Zeros.java at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/test/java/org/tensorflow/op/core/ZerosTest.java so you might want to make sure the test can pass too.

Sorry, it's out of the Android project 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/3314607/88214825-1125c680-cc5b-11ea-94d3-38b14612db0a.png">

2020-07-22 18:40 UTC, frankchn commented
I think you have to somehow get gradle/your environment to run the code at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/gen/cc/op_generator.cc during builds. That code generates all the relevant op files that are used. The standard TensorFlow Java Bazel build environment is set up to do this, but I am not sure how to do it on gradle and android.

> Sorry, it's out of the Android project

Yeah it is, but it shows that the `Zeros.java` code can be built and runs properly and this seems to be more of ab build environment setup issue on the Android example.

2020-07-22 18:44 UTC, hannesa2 commented
> I think you have to somehow get gradle/your environment to run the code at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/gen/cc/op_generator.cc during builds.

I've the feeling that it's a way in the wrong direction.
I should run a generator, to fix a class, which Android don't need. This sounds not logic

2020-07-22 18:48 UTC, hannesa2 commented
And the CI is successful for Android ?

I guess at least for Android the command `./gradlew build` would be the right command

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/3314607/88215847-8cd44300-cc5c-11ea-8e74-7a7debc70e3e.png">

2020-07-22 20:51 UTC, frankchn commented
> I've the feeling that it's a way in the wrong direction. I should run a generator, to fix a class, which Android don't need. This sounds not logic

Deleting a file that builds and tests in the normal TensorFlow environment with the standard TensorFlow build tooling is correct either.

> I guess at least for Android the command ./gradlew build would be the right command. This one will fail

ZerosTest.java will fail if you delete Zeros.java in the main TensorFlow build, and this will break the main TensorFlow Java build.

2020-07-23 03:53 UTC, hannesa2 commented
Ok, I keep the `Zeros.java` untouched. 
As long, as I don't really understand why it's included, I'm unable to fix this.

The Android CI builds now properly (but on local machine it fails because of untouched `Zeros.java`)

Now the pull request only fix the Gradle setup and update to recent Android Studio build tools

2020-07-23 07:55 UTC, frankchn commented
Thanks @hannesa2! Just one comment: for the `tensorflow/examples/android/gradlew` file, can we not have the chmod set to 0755 and leave it as 0644?

2020-07-23 08:28 UTC, hannesa2 commented
> Thanks @hannesa2! Just one comment: for the `tensorflow/examples/android/gradlew` file, can we not have the chmod set to 0755 and leave it as 0644?

Really ? If I don't do it, I can't run it locally 

<img width="409" alt="image" src="https://user-images.githubusercontent.com/3314607/88266191-0c025f00-cccf-11ea-9dcd-18a8562469be.png">

That's why I did ` chmod +x gradlew`

Short: At least for me it's necessary ! And when  you ever build it on CI, you will need it too

2020-07-23 23:17 UTC, frankchn approved these changes

2020-07-24 17:06 UTC, merged