Added Prototype for Tensorflow Program (tf_program)
tensorflow/tensorflow pull request #39105
Opened 2020-05-02 20:08 UTC by shraiysh

This PR attempts to add the first prototype for Tensorflow program. It is a direct conversion from a python function to mlir module. The target dialect is `tf dialect` (with some added operations such as tfp.If, tfp.While, tfp.And and tfp.Or).

Signed-off-by: Shraiysh Vaishay <cs17btech11050@iith.ac.in>

2020-05-04 14:50 UTC, alextp requested changes
I'd rather this work be done in a separate git repository since TF doesn't need to depend on it.

2020-05-04 22:19 UTC, mdanatg submitted a review, later dismissed

2020-05-08 15:11 UTC, gbaned commented
@shraiysh Can you please check build failures. Thanks!

2020-05-08 18:42 UTC, mdanatg submitted a review, later dismissed

2020-05-08 23:38 UTC, shraiysh commented
I think I messed up while trying to change my parent commit and syncing my forked repository! I will close this and open a new PR. Apologies for the error.

2020-05-08 23:39 UTC, closed without merging

2020-05-09 00:22 UTC, joker-eph commented
You can always force push a new revision to the original branch, it should never be needed to close a PR and open a new one for this purpose I think.

2020-05-09 07:00 UTC, shraiysh commented
Okay, will force push next time onwards! Thanks! (Although, I am not sure if force pushing will alter the participants)