Removing unreachable return
tensorflow/tensorflow pull request #39127
Opened 2020-05-03 18:17 UTC by Anselmoo

Removed the unreachable `return original_index`

```python
def _get_correct_mapping(original_index, nodes):
  # Special handle for the index is -1 case.
  # If it is -1, return the last index.
  if original_index == -1:
    node_indices = nodes.keys()
    node_indices = sorted(node_indices)
    return node_indices[-1]
  else:
    return original_index
```

2020-05-04 16:18 UTC, mihaimaruseac requested changes
I would rather remove the `else` block to be future proof.

2020-05-04 17:22 UTC, mihaimaruseac commented on tensorflow/lite/python/op_hint.py
>      return original_index
Please remove these instead

2020-05-04 17:50 UTC, mihaimaruseac approved these changes

2020-05-12 02:53 UTC, rthadur approved these changes

2020-05-14 17:12 UTC, merged