Implementation of relational operator for complex numbers in XLA
tensorflow/tensorflow pull request #39133
Opened 2020-05-03 21:36 UTC by joschkabraun

This is the suggestion to implement relational operators for complex numbers (<, <=, >, >=) as in numpy, i.e., the lexicographical order. In this PR only the ">" relation was implemented as feedback from the community is important to evaluate if this functionality is wished for and makes sense.

This could be leveraged for the implementation of [np.unique in JAX](https://github.com/google/jax/pull/2760) as comparison and sorting of complex arrays is not supported by XLA but possible with numpy. Another usage could be an implementation of [complex QR decomposition in JAX](https://github.com/google/jax/issues/1274).

The remaining comparisons for complex numbers and tests for it, will be added if this functionality makes sense.

2020-05-15 17:31 UTC, cheshire commented
Matching numpy semantics makes sense to me, could we add tests?

2020-05-19 13:58 UTC, gbaned commented
@joschkabraun Can you please check @cheshire's comments and keep us posted. Thanks!

2020-05-21 15:10 UTC, joschkabraun commented
Okay, perfect! I’m currently working on it and will finish this weekend!

2020-05-28 20:52 UTC, joschkabraun commented
I have been looking through the code. Am I correct in assuming the tests for that should be placed into the file elemental_ir_emitter_test.cc?

2020-05-29 17:17 UTC, cheshire requested changes
Yes, adding tests to `elemental_ir_emitter_test` would make sense.

2020-05-29 17:17 UTC, cheshire commented on tensorflow/compiler/xla/service/elemental_ir_emitter.cc
> +          return Or(llvm_ir::EmitComparison(llvm::CmpInst::FCMP_OGT,
Could you add a comment that we are using lexicographical comparison which is consistent with numpy behavior?

2020-05-29 17:17 UTC, cheshire commented on tensorflow/compiler/xla/service/elemental_ir_emitter.cc
> +	case ComparisonDirection::kGt:
What happens to other cases? kLt? Less-or-equal? You could also support this by implementing a normalization pass in algebraic_simplifier

2020-06-02 15:38 UTC, gbaned commented
@joschkabraun Can you please check @cheshire's comments and keep us posted. Thanks!

2020-06-24 03:55 UTC, tensorflowbutler commented
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-07-03 16:16 UTC, gbaned commented
@joschkabraun, Any update on this PR? Please. Thanks!

2020-07-04 23:52 UTC, joschkabraun commented
Unfortunately, I am currently very busy and seems advisable if someone else could take this over. I am sorry for answering so late!

2020-07-12 14:27 UTC, gbaned commented
@joschkabraun Thanks for the confirmation. Closing the PR.

2020-07-12 14:27 UTC, closed without merging