[ROCm] hip-clang / ROCm 3.5 build fixes
tensorflow/tensorflow pull request #39427
Opened 2020-05-11 20:52 UTC by ekuznetsov139

ROCm migrates from hcc to hip-clang in version 3.5, and these changes are needed to support the transition. 

Summary of the changes:
* ROCm 3.5 includes gtest and gmock in its install tree, and we have to delete them when copying over the headers, otherwise they take precedence over tensorflow's own gtest/gmock
* Adding rccl's dependency on librt
* The XLA compiler is switched from code object v2 to v3
* A resource handling issue is fixed (it was present all along but it got exposed by the transition)
* An unneeded command-line warning flag is removed

2020-05-15 17:34 UTC, cheshire requested changes

2020-05-15 17:34 UTC, cheshire commented on third_party/gpus/cuda_configure.bzl
> +def make_copy_dir_rule(repository_ctx, name, src_dir, out_dir, exceptions=None):
Could you extend the docstring to clarify the semantics of `exceptions`?

2020-05-15 17:34 UTC, cheshire commented on tensorflow/stream_executor/rocm/rocm_gpu_executor.cc
> +    for (auto x : in_memory_modules_)
XLA code style is curly braces in this case

2020-05-15 20:04 UTC, cheshire approved these changes

2020-05-16 01:38 UTC, rthadur approved these changes

2020-05-18 20:22 UTC, merged