Move training op helpers to framework and fix linking issues
tensorflow/tensorflow pull request #39422
Opened 2020-05-11 17:41 UTC by samikama

Hi, this PR encompasses the PR #37873 and fixes the linking issues. @alextp @Squadrick @spidyDev

2020-05-11 17:44 UTC, samikama commented
@vcarpani @Squadrick Since I keep your commits from earlier PR to credit your work, could you please approve the CLA?

2020-05-11 17:45 UTC, vcarpani commented
@googlebot I consent.

2020-05-11 18:20 UTC, spidyDev commented
@samikama  Thanks for making this change. The PR works fine with custom ops  in TF addons.

2020-05-11 18:28 UTC, alextp submitted a review, later dismissed

2020-05-12 02:59 UTC, rthadur commented
@samikama can you please sign CLA ?

2020-05-13 02:34 UTC, samikama commented
@googlebot I consent

2020-05-13 02:35 UTC, samikama commented
@Squadrick do you consent to include your commits in PR or should I open a new one without your changes?

2020-05-13 03:00 UTC, samikama commented
@googlebot I consent.

2020-05-13 06:51 UTC, Squadrick commented
@googlebot I consent.

2020-05-13 15:56 UTC, alextp submitted a review, later dismissed

2020-05-14 15:41 UTC, alextp approved these changes

2020-05-15 00:04 UTC, rthadur approved these changes

2020-05-15 03:43 UTC, samikama commented
@rthadur, it looks like copybara failed but can't see the reason. Is there anything on my side to help?

2020-05-15 05:09 UTC, rthadur submitted a review, later dismissed

2020-05-18 15:42 UTC, alextp submitted a review, later dismissed

2020-05-18 18:52 UTC, samikama commented
@rthadur and @alextp There seems to be an issue with copybara but I can't see the error. Is there anything I can do to help?

2020-05-19 17:42 UTC, mihaimaruseac commented
Copybara fails because we no longer have `contrib`. Can we remove the `contrib` files from the PR?

2020-05-19 19:18 UTC, samikama commented
@mihaimaruseac Thanks for catching that. I thought these were removed in earlier PRs that this is based on. I removed contrib directory now.

2020-05-19 19:24 UTC, mihaimaruseac submitted a review, later dismissed

2020-05-19 21:13 UTC, samikama commented
@mihaimaruseac I believe current failures are not related with this PR, since there wasn't any change that would have caused them wrt previous commit. Is that correct?

2020-05-20 16:39 UTC, mihaimaruseac commented
The MacOS failures are not related. They also won't block merging this. Currently this is waiting import approval, but it shouldn't take longer.

2020-05-22 00:27 UTC, rthadur requested changes
@samikama can you please check below errors ?

2020-05-22 00:27 UTC, rthadur commented on tensorflow/core/kernels/stateful_random_ops.cc
> +#include "tensorflow/core/framework/training_op_helpers.h"
`tensorflow/core/kernels:stateful_random_ops does not depend on a module exporting 'third_party/tensorflow/core/framework/training_op_helpers.h'`

2020-05-22 00:27 UTC, rthadur commented on tensorflow/core/kernels/resource_variable_ops.cc
> +#include "tensorflow/core/framework/resource_var.h"
`tensorflow/core/kernels:resource_variable_ops does not depend on a module exporting 'third_party/tensorflow/core/framework/resource_var.h'`

2020-05-22 00:27 UTC, rthadur commented on tensorflow/core/kernels/resource_variable_ops.cc
>  #include "tensorflow/core/kernels/dense_update_functor.h"
`tensorflow/core/kernels:resource_variable_ops does not depend on a module exporting 'third_party/tensorflow/core/kernels/dense_update_functor.h'`

2020-05-22 00:27 UTC, rthadur commented on tensorflow/core/kernels/count_up_to_op.cc
> +#include "tensorflow/core/framework/resource_mgr.h"
`/tensorflow/core/kernels/variable_ops.cc:19:10: error: use of private header from outside its module: '/tensorflow/core/framework/op_kernel.h'; 
         ^/tensorflow/core/kernels/variable_ops.cc:20:10: error: use of private header from outside its module: '/tensorflow/core/framework/register_types.h';

2020-05-22 00:27 UTC, rthadur commented on tensorflow/core/kernels/scatter_nd_op.cc
> +#include "tensorflow/core/framework/resource_var.h"
`/tensorflow/core/kernels/scatter_nd_op.cc:29:10: error: module //
/tensorflow/core/kernels:scatter_nd_op does not depend on a module exporting '/tensorflow/core/framework/resource_var.h'

/tensorflow/core/kernels/scatter_nd_op.cc:33:10: error: module //
/tensorflow/core/kernels:scatter_nd_op does not depend on a module exporting '/tensorflow/core/kernels/dense_update_functor.h'`

2020-05-22 00:27 UTC, rthadur commented on tensorflow/core/kernels/strided_slice_op.cc
> -#include "tensorflow/core/kernels/dense_update_functor.h"
`tensorflow/core/kernels/strided_slice_op.cc:29:10: error: module //
/tensorflow/core/kernels:strided_slice_op does not depend on a module exporting '/tensorflow/core/framework/resource_var.h`

2020-05-22 00:27 UTC, rthadur commented on tensorflow/core/kernels/training_ops.cc
> -#include "tensorflow/core/kernels/training_op_helpers.h"
`tensorflow/core/framework/training_op_helpers.cc:18:10: error: module //
/tensorflow/core:training_op_helpers does not depend on a module exporting '
/tensorflow/core/util/ptr_util.h`

2020-05-22 03:59 UTC, samikama commented
@rthadur I just did a clean build and can't reproduce the issue. I am using bazel 2.0.0? Is this observed in internal build? If not can you tell me how can I reproduce it?

2020-05-27 19:55 UTC, samikama commented
@rthadur any help on this? If I can't see the errors I can't know what is wrong or verify if they are fixed.

2020-05-27 21:05 UTC, mihaimaruseac commented
These seem to be caused by `BUILD` files not mirroring the include hierarchy. I'll try to import and fix manually later today/this week

2020-05-28 20:56 UTC, mihaimaruseac commented
Unfortunately I have to give up trying to manually import. Errors are either of this form:

```
...$ bazel build //tensorflow/core/kernels:variable_ops
...
ERROR: .../tensorflow/core/kernels/BUILD:5716:18: C++ compilation of rule '//tensorflow/core/kernels:variable_ops' failed (Exit 1)[..] 
tensorflow/core/kernels/variable_ops.cc:19:10: error: use of private header from outside its module: 'tensorflow/core/framework/op_kernel.h'. [-Wprivate-header]
#include "tensorflow/core/framework/op_kernel.h"
         ^
...
FAILED: Build did NOT complete successfully
```

or errors of the form

```
...$ bazel build //tensorflow/core/kernels:count_up_to_op  
...                                                                                                                                                                                                       
ERROR: .../tensorflow/core/kernels/BUILD:5640:18: C++ compilation of rule '//tensorflow/core/kernels:count_up_to_op' failed (Exit 1)[..]                                                                              
tensorflow/core/kernels/count_up_to_op.cc:18:10: error: module //tensorflow/core/kernels:count_up_to_op does not depend on a module exporting 'tensorflow/core/framework/resource_var.h'                                                              
#include "third_party/tensorflow/core/framework/resource_var.h"                                                                    
         ^         
...                           
FAILED: Build did NOT complete successfully  
```

This results in over 16000 tests failing internally.

Can we try splitting this PR into smaller components and merging them one by one. Can assign me as reviewer for each component.

2020-05-29 18:37 UTC, samikama commented
Thanks for looking into that @mihaimaruseac. I can try to give another go if I can have a way to reproduce the problem. I believe these issues are originating from an incomplete refactoring in the past. If is it possible to have a small reproducer, it might be easier to solve these issues. Could you provide a simple example manifesting the errors?

2020-05-29 19:04 UTC, mihaimaruseac commented
Sure. The errors I got were reproduceable when building the equivalent of `bazel build //tensorflow/core/kernels:variable_ops` and `bazel build //tensorflow/core/kernels:count_up_to_op`,

If you cannot reproduce, can we try a different approach where we duplicate the code first (one PR), slowly migrate targets to use the new code (multiple PRs), then we do one more PR to sync the duplicates and remove the old copy? I could attempt to do that internally but not in the next 1-2 weeks :(

2020-05-29 20:04 UTC, samikama commented
@mihaimaruseac, thanks. I just did another clean build and the targets you mention. They all went through without any problems. I used bazel 2.0.0 as well as 3.2.0. I wonder what is so different between imported code and OSS. Could it be an import issue?

2020-05-29 20:06 UTC, samikama commented
Also I extended the visibility of the framework header exports to core/kernels. Perhaps this helps

2020-05-29 20:18 UTC, mihaimaruseac commented
Let's try a new pull with the visibility extended.

2020-05-29 20:18 UTC, mihaimaruseac approved these changes

2020-06-01 17:27 UTC, rthadur commented
@mihaimaruseac there are still internal errors , can you please check.

2020-06-17 13:40 UTC, gbaned commented
@samikama Can you please check @rthadur's comments and keep us posted. Thanks!

2020-07-03 01:28 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-07-08 21:52 UTC, samikama commented
@gbaned This is a bit hard to resolve since we can not reproduce the issue with public TF release and bazel.

2020-07-15 16:32 UTC, rthadur commented
@mihaimaruseac can you please with internal errors ?

2020-07-15 23:28 UTC, mihaimaruseac commented
I will need to find some uninterrupted time without any urgent priority. Unfortunately this has not been the case yet, sorry about this.

I have the PR on my list and will surely get to fixing it.

There is a merge conflict, can we fix it?

2020-07-17 08:13 UTC, gbaned commented
@samikama Can you please resolve conflicts? Thanks!

2020-07-29 15:56 UTC, gbaned commented
@samikama, Any update on this PR? Please. Thanks!

2020-08-03 16:26 UTC, samikama commented
I will rework this PR when I have time.

2020-08-25 17:55 UTC, gbaned commented
@samikama  Any update on this PR? and please resolve conflicts. Thanks!

2020-08-27 09:01 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-08-27 09:01 UTC, closed without merging