[Intel MKL] Adding MklTanh op
tensorflow/tensorflow pull request #39563
Opened 2020-05-14 22:49 UTC by nhasabni

This PR adds Tanh op to MKL CPU backend.

2020-06-02 15:57 UTC, gbaned commented
@penpornk Can you please take a look on this PR ? Thanks!

2020-06-06 21:44 UTC, penpornk requested changes
Thank you for your PR and sorry for my delay! I also appreciate the detailed comments in the code.

2020-06-09 21:02 UTC, nhasabni commented on tensorflow/core/common_runtime/mkl_layout_pass_test.cc
> +            "B->C;B:1->C:2;B:control->DMT/_1:control;C->D:1;DMT/_0->B:1;"      \
B:1->C:2 carries meta-tensor output for actual tensor output carried by B->C.

2020-06-10 09:49 UTC, gbaned commented
@nhasabni Can you please check @penpornk's comments and keep us posted. Thanks!

2020-06-12 16:25 UTC, penpornk commented on tensorflow/core/kernels/mkl_relu_op_test.cc
> +//   export OMP_NUM_THREADS=${num_threads}
Got it. I see that `mkl_conv_ops_test.cc` also has this problem. I'll fix them both later then. (If I can get to it before we fully switch to custom thread pool.)

2020-06-12 16:25 UTC, penpornk commented on tensorflow/core/common_runtime/mkl_layout_pass_test.cc
> +            "B->C;B:1->C:2;B:control->DMT/_1:control;C->D:1;DMT/_0->B:1;"      \
Thank you for the clarification!

2020-06-12 16:27 UTC, penpornk approved these changes
Thank you again for the PR!

2020-06-12 17:07 UTC, nhasabni commented
> Thank you again for the PR!

Thanks for review and approval!

2020-06-15 21:36 UTC, merged