Yashlocal
tensorflow/tensorflow pull request #39700
Opened 2020-05-20 04:08 UTC by yashjain1129

fixed debugging statement and space format

2020-05-20 07:29 UTC, gbaned commented
@yashjain1129 Thank you for your contribution. Can you please sign CLA? Thanks!

2020-05-20 16:50 UTC, mihaimaruseac commented
Can you also use a relevant title for the PR please? Also, can you edit the first message field to include a short description?

2020-05-28 15:46 UTC, mihaimaruseac requested changes

2020-05-28 15:46 UTC, mihaimaruseac commented on tensorflow/compiler/mlir/xla/transforms/hlo_legalize_to_lhlo.cc
> +//      entry_block.eraseArgument(i);
```suggestion
```

2020-05-28 15:46 UTC, mihaimaruseac commented on tensorflow/compiler/mlir/xla/transforms/hlo_legalize_to_lhlo.cc
> +      entry_block.eraseArgument(2*original_arg_count -1);
This should be outside of the loop since it does not depend on the loop counter?

2020-05-28 15:48 UTC, mihaimaruseac commented
- [ ] Please sign CLA
- [ ] Please change issue title
- [ ] Please describe what the change is doing and why. What issue does it solve? What feature does it bring?

Until the above checkboxes are ticked, we won't be able to land this.

2020-05-28 15:52 UTC, closed without merging

2020-05-28 15:56 UTC, yashjain1129 commented
I will add more to it then again create another Pull Request. For the above point yes the above suggestion for 'i' instead of 1 so it would be in for loop. Thanks for your response. Although in Reduce Op there is a bug. Can you also look at the issue [https://github.com/tensorflow/tensorflow/issues/39792](url)