[XLA] Extra VLOG for PTXAS calls
tensorflow/tensorflow pull request #39734
Opened 2020-05-20 20:50 UTC by nouiz

This PR does a few changes related to PTXAS:
- print the PTXAS command line used via VLOG
- It will also output the verbose output of PTXAS as already asked on line 210, but not displayed.
- Add the TF_EXTRA_PTXAS_OPTIONS environment variable that allows to pass extra parameter to PTXAS.

I tag this XLA as to my knowledge this code is only used by XLA.

2020-05-29 20:53 UTC, timshen91 requested changes

2020-05-29 20:53 UTC, timshen91 commented on tensorflow/stream_executor/gpu/asm_compiler.cc
> +    env = getenv("TF_EXTRA_PTXAS_OPTIONS");
If it's only for XLA, the flag should go through XLA_FLAGS. See https://github.com/tensorflow/tensorflow/blob/13645c7fd2a7c151b82a9bfa144b0e682122ed7b/tensorflow/compiler/xla/xla.proto#L25

`GpuAsmOpts` already has a member `extra_flags`, which can be plumbed through XLA_FLAGS.

2020-06-01 08:57 UTC, gbaned commented
@nouiz  Can you please check @timshen91's comments and keep us posted. Thanks!

2020-06-01 13:09 UTC, nouiz commented
Will do. But it could take a few days.

2020-06-08 21:00 UTC, nouiz commented
Updated per instruction. I tested manually with run_hlo_modules and it behave as expected.

Note, I tested with replay_computation and now the XLA_FLAGS aren't passed correctly for it. So it doesn't behave correctly. But this isn't related to this PR.

2020-06-08 21:03 UTC, nouiz commented
run_hlo_module seems to replace replay_computation. As replay_computation is partially broken, why not just remove it and point to the new tools?

2020-06-09 19:23 UTC, timshen91 reviewed
> Updated per instruction. I tested manually with run_hlo_modules and it behave as expected.
> 
> Note, I tested with replay_computation and now the XLA_FLAGS aren't passed correctly for it. So it doesn't behave correctly. But this isn't related to this PR.

I just tried and at least XLA_FLAGS="--xla_dump_to=..." works.

2020-06-09 19:23 UTC, timshen91 commented on tensorflow/compiler/xla/service/gpu/stream_executor_util.cc
> +  extra_flags = absl::StrSplit(extra_string, " ", absl::SkipEmpty());
Can you use comma delimiter? Using spaces makes it hard in mix with other options, e.g. XLA_FLAGS="--xla_gpu_gpuasm_extra_flags=a b c --xla_hlo_profile"

2020-06-09 19:23 UTC, timshen91 commented on tensorflow/compiler/xla/xla.proto
> +  string xla_gpu_gpuasm_extra_flags = 141;
xla_gpu_asm_extra_flags

2020-06-10 17:53 UTC, timshen91 approved these changes

2020-06-11 18:28 UTC, merged