Type annotations for tf.saturate_cast & tf.constant ops
tensorflow/tensorflow pull request #40132
Opened 2020-06-03 21:08 UTC by rahul-kamat

**Changes:**
- `c8f92e1` - modify Tensor class to be a Generic class with a DataType parameter which represents the dtype of the Tensor
- `b62fb43` - create classes for each TF dtype to extend `DType` base class
- `ce3dae0` - add stub file to give each TF dtype their respective type
- `6dceb41` - annotations for dtype argument and return tensor for `tf.saturate_cast` op
- `23ebb34` & `c633769` - type decorators
- `6439ae7` - annotations for dtype argument and return tensor for `tf.constant` op

2020-06-04 02:02 UTC, mdanatg submitted a review, later dismissed
Looks good, but there are a few things we need to set up before merging.

2020-06-12 13:05 UTC, mdanatg commented
Note: temporarily approving to trigger the import process - the PR is not ready to merge yet.

2020-06-12 13:05 UTC, mdanatg approved these changes

2020-06-12 13:10 UTC, mdanatg requested changes
Resetting approval flag while we fix the blocking tests.

2020-06-12 21:13 UTC, jaingaurav commented on tensorflow/python/ops/math_ops.py
> +                            dtypes.UInt8, dtypes.UInt16, dtypes.UInt32,
Rather than having to list out all the types, can we have the API support merging groups of types such as complex/real etc?

2020-06-12 21:14 UTC, jaingaurav commented on tensorflow/python/framework/ops.py
> +    self._dtype = dtypes.as_dtype(dtype) # type: DataType
Why is this type annotation needed? `as_dtype` is used in many places so it'd be nice to get the annotations all over the place.

2020-06-15 17:26 UTC, rthadur commented
@rahul-kamat can you please check latest review comments.

2023-03-28 06:58 UTC, vrunm commented
@rahul-kamat Can I work on this PR?

2023-03-28 17:54 UTC, rahul-kamat commented
> @rahul-kamat Can I work on this PR?

I don't work on tensorflow anymore. Going to redirect this to @rohan100jain. Rohan wdyt?

2024-04-26 06:06 UTC, gbaned commented
Hi @rahul-kamat I'm going to go ahead and close this PR. Thank you for your contribution!
Hi @vrunm If you're still interested in pursing this, please feel free to create new PR.  Thank you!

2024-04-26 06:06 UTC, closed without merging