TFLM: To support Himax WE1 EVB
tensorflow/tensorflow pull request #40299
Opened 2020-06-09 01:58 UTC by CKHSUinHimax

In this pull request support Himax WiseEye Plus platform is added.

2020-06-09 02:14 UTC, CKHSUinHimax commented
@googlebot I signed it!

2020-06-09 02:45 UTC, CKHSUinHimax commented
@googlebot I fixed it.

2020-06-09 02:53 UTC, bigcat-himax commented
@googlebot I consent.

2020-06-09 02:58 UTC, bigcat-himax reviewed
The modification is okay. In this pull request support Himax WiseEye Plus platform is added.

2020-06-09 02:59 UTC, bigcat-himax commented
@googlebot I consent.

2020-06-10 23:37 UTC, petewarden requested changes

2020-06-10 23:37 UTC, petewarden commented on tensorflow/lite/micro/examples/person_detection_experimental/himax_we1_evb/image_provider.cc
> +    {
Can you run something like clang-format with the google style option over this code, to make sure it passes our internal formatting tests?

2020-06-10 23:37 UTC, petewarden commented on tensorflow/lite/micro/examples/person_detection_experimental/himax_we1_evb/main_functions.cc
> +#pragma Bss(".tensor_arena")
As discussed on the call, can you confirm what the differences are between this and the regular main_functions.cc file? If the differences are minor, let's figure out what the simplest way to include them without a full copy is.

2020-06-16 22:12 UTC, petewarden approved these changes

2020-06-17 23:47 UTC, merged