[ROCm][mlir] Disable mlir saved model test
tensorflow/tensorflow pull request #40367
Opened 2020-06-10 21:12 UTC by jerryyin

Adding `no-rocm` tag to saved model test. There is flaky OOM failures yet to be investigated in the following unit tests in ROCm CI:

- basic_v1.py.test
- multi_variables_v1.py.test
- shared_variables_v1.py.test

The added tag disables those unit tests.

2020-06-11 20:47 UTC, gunan approved these changes

2020-06-12 04:00 UTC, joker-eph commented
> ROCm backend does not have a working mlir backend yet

What does that mean? These tests are not (mostly?) runtime tests and are intended to be "backend" agnostic.

2020-06-12 04:00 UTC, joker-eph requested changes
(needs clarification)

2020-06-17 16:23 UTC, gbaned commented
@jerryyin Can you please check @joker-eph's comments and keep us posted. Thanks!

2020-06-18 19:35 UTC, jerryyin commented
Was working on a number of things sorry for the late reply. 
> > ROCm backend does not have a working mlir backend yet
> 
> What does that mean? These tests are not (mostly?) runtime tests and are intended to be "backend" agnostic.

That part of story remains a mystery. It *shouldn't* run into any issues into this. To give more details, of the[ two most recent CI runs](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1010) in our CI, one of which is failing on all `basic_v1.py.test`, `multi_variables_v1.py.test` and `shared_variables_v1.py.test`. Another is doing all fine. Before we can find time to understand why those tests have flaky OOM failures the easy way ahead is to just disable them. It does not make the situation worse because there's already a `no_rocm` flag when it is an empty list, kind of confirming the existence of flakiness.

2020-06-22 17:55 UTC, joker-eph commented
> Before we can find time to understand why those tests have flaky OOM failures the easy way ahead is to just disable them. It does not make the situation worse because there's already a no_rocm flag when it is an empty list, kind of confirming the existence of flakiness.

What is the plan for investigating and fixing this? Do you have a timeline? I would be concerned to sweep this under the rug and forget it.

2020-06-22 18:48 UTC, jerryyin commented
> What is the plan for investigating and fixing this? Do you have a timeline? I would be concerned to sweep this under the rug and forget it.

That's reasonable questions to ask. Internally, we do keep track of all `no-rocm` tags, and work to re-enable them. I don't think it can just got forgotten. What this PR does is to minimize diff between upstream and downstream forks and bring the state up to the latest. Speaking of the specific one, it comes as lower priority than the general functionality of mlir ROCm backend. I'm not the right person to comment on the timeline as it has to conform with team's priorities, and is probably out-of-scope for this PR. @deven-amd also for awareness.

2020-06-23 03:56 UTC, joker-eph commented
> Speaking of the specific one, it comes as lower priority than the general functionality of mlir ROCm backend

As we already established (I think): this is entirely orthogonal to a "MLIR Backend" of any sort. 

Can we start by updating the CL description with an accurate description of the problem, including information about what fails and how?

2020-06-23 17:59 UTC, jerryyin commented
> Can we start by updating the CL description with an accurate description of the problem

Done

2020-06-23 18:55 UTC, merged