Fix wrong comments
tensorflow/tensorflow pull request #40450
Opened 2020-06-14 16:11 UTC by dataabc

Reference
[Probot: Stale](https://github.com/probot/stale)

2020-06-15 17:27 UTC, mihaimaruseac requested changes

2020-06-15 17:27 UTC, mihaimaruseac commented on .github/stale.yml
> +# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
```suggestion
# Only issues or pull requests with all of these labels are checked if stale. Defaults to `[]` (disabled)
```

2020-06-16 03:56 UTC, dataabc commented on .github/stale.yml
> +# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
Thanks and I have updated stale.yml.

2020-06-16 04:14 UTC, rthadur approved these changes

2020-06-16 15:15 UTC, mihaimaruseac approved these changes

2020-06-16 15:56 UTC, merged