[TFTRT] Add Dynamic Shape Testing for ConvertSquare
tensorflow/tensorflow pull request #40483
Opened 2020-06-15 18:27 UTC by MattConley

Changes the ConvertSquare test to use the new testing API

2020-06-17 19:03 UTC, bixia1 approved these changes

2020-06-17 19:03 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
> +#if IS_TRT_VERSION_GE(6, 0, 1, 0)
We have a plan to provide a way to get the supported data types for all op converters. The code here is fine for this reason.

2020-06-17 19:49 UTC, bixia1 requested changes
would you please squash the commits into one commit?

2020-06-17 20:06 UTC, MattConley commented
Thanks for the review, the changes have been consolidated into one commit

2020-06-17 20:56 UTC, bixia1 approved these changes

2020-06-18 05:03 UTC, rthadur approved these changes

2020-06-18 16:05 UTC, merged