[Grappler] improve HoistCWiseUnaryChainsStage to support Reshape
tensorflow/tensorflow pull request #40542
Opened 2020-06-17 12:16 UTC by xinan-jiang

This is a PR from JIZHI, the AI platform in Tencent.

This allows the reshape nodes in the unary op chain to be processed by the optimizer HoistCWiseUnaryChainsStage.

2020-06-17 21:05 UTC, ezhulenev approved these changes

2020-07-02 02:43 UTC, rthadur approved these changes

2020-07-06 21:06 UTC, rthadur requested changes
@xinan-jiang can you please check review comments.

2020-07-06 21:06 UTC, rthadur commented on tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
> +    CHECK(IsReshape(*wrapped_node));
`New CHECK or LOG(FATAL) statements inserted in code! Prefer using DCHECK, LOG(DFATAL), or DLOG(FATAL) instead`

2020-07-06 21:06 UTC, rthadur commented on tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
> +    CHECK(IsReshape(*wrapped_node));
`New CHECK or LOG(FATAL) statements inserted in code! Prefer using DCHECK, LOG(DFATAL), or DLOG(FATAL) instead`

2020-07-09 14:43 UTC, gbaned commented
@xinan-jiang Can you please check @rthadur's comments and keep us posted. Thanks!

2020-07-21 14:47 UTC, gbaned commented
@xinan-jiang  Any update on this PR? Please. Thanks!

2020-08-07 01:20 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-08-18 16:40 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-08-18 16:40 UTC, closed without merging