[-Wsign-compare] warning fixes batch 3
tensorflow/tensorflow pull request #40697
Opened 2020-06-23 02:37 UTC by tg-at-google

@mihaimaruseac

2020-06-23 16:16 UTC, mihaimaruseac requested changes

2020-06-23 16:16 UTC, mihaimaruseac commented on indexed_warning_files.json
> +{"0": "tensorflow/lite/arena_planner.cc", "1": "tensorflow/core/platform/protobuf.cc", "2": "tensorflow/core/platform/protobuf.cc", "3": "tensorflow/core/platform/default/logging.cc", "4": "tensorflo
I think you don't want this file included in the PR

2020-06-23 16:16 UTC, mihaimaruseac commented on tensorflow/core/grappler/optimizers/generic_layout_optimizer_transposer.cc
> +    int dims_size = dims.size();
```suggestion
    const int dims_size = dims.size(); 
```

Let's try to make these const if they don't change to enable a few compiler optimizations.

2020-06-23 16:16 UTC, mihaimaruseac commented on tensorflow/core/grappler/optimizers/generic_layout_optimizer_transposer.cc
> +  int permutation_size = permutation.size();
```suggestion
  const int permutation_size = permutation.size();
```

2020-06-23 16:16 UTC, mihaimaruseac commented on tensorflow/core/grappler/optimizers/generic_layout_optimizer_transposer.cc
> +  int axis_size = axis.size();
```suggestion
  const int axis_size = axis.size();
```

2020-06-23 16:16 UTC, mihaimaruseac commented on tensorflow/core/grappler/optimizers/shape_optimizer.cc
> +        int prop_size = prop.size();
```suggestion
        const int prop_size = prop.size();
```

2020-06-24 19:45 UTC, mihaimaruseac requested changes

2020-06-24 19:45 UTC, mihaimaruseac commented on indexed_warning_files.json
> +{"0": "tensorflow/lite/arena_planner.cc", "1": "tensorflow/core/platform/protobuf.cc", "2": "tensorflow/core/platform/protobuf.cc", "3": "tensorflow/core/platform/default/logging.cc", "4": "tensorflo
You might want to add this file to `.git/config/ignore` or use `git add ..` instead of `git commit -a ...`

2020-06-24 19:51 UTC, tg-at-google commented
A little strange @mihaimaruseac ,  I deleted it the first time. Nothing changed. I delete it now, and it the changes reflect. No problem though, the file is gone. 👍

2020-06-24 19:58 UTC, mihaimaruseac approved these changes

2020-06-24 21:46 UTC, merged