Sign compare warning fixes batch 1 fix2
tensorflow/tensorflow pull request #40741
Opened 2020-06-24 02:10 UTC by tg-at-google

Not ready for merge just yet, 35 files changes expected. Please await these changes.

2020-06-24 02:11 UTC, tg-at-google commented
@joker-eph The mlir related changes are just copies of what is currently at tensorflow/tensorflow:master, i.e. they are actually not changes at all.

2020-06-24 06:27 UTC, gbaned commented
@tg-at-google Can you please resolve conflicts? Thanks!

2020-06-24 19:05 UTC, tg-at-google reviewed
This represents completion of my review of this set of warning resolutions. 
Again, please note that the mlir changes are just mirror of tensorflow/tensorflow:master and are thus not changes at all. 

@mihaimaruseac @joker-eph

2020-06-24 19:12 UTC, mihaimaruseac requested changes

2020-06-24 19:12 UTC, mihaimaruseac commented on tensorflow/core/kernels/quantization_utils.h
> +  for (size_t index = 0; static_cast<tensorflow::int64>(index) < count; ++index) {
Let's change type of `index` to `int64` instead.

2020-06-24 19:12 UTC, mihaimaruseac commented on tensorflow/lite/toco/graph_transformations/resolve_batch_normalization.cc
> +  CHECK(static_cast<int>(offset_float_data.size()) == buffer_size);
Let's change `buffer_size`'s type instead

2020-06-24 19:12 UTC, mihaimaruseac commented on tensorflow/lite/toco/graph_transformations/unpartition_embedding_lookup.cc
> +  std::vector<string> stitch_data_inputs;
We should keep `std::string` here

2020-06-25 23:01 UTC, mihaimaruseac approved these changes

2020-06-25 23:01 UTC, mihaimaruseac requested changes
Forgot the other 2 items

2020-06-25 23:03 UTC, tg-at-google commented
> Forgot the other 2 items

Hey, yeah, wasn't done yet. 😅

2020-06-25 23:06 UTC, tg-at-google commented
> > Forgot the other 2 items
> 
> Hey, yeah, wasn't done yet. 😅

Alright @mihaimaruseac  good to go.

2020-06-25 23:07 UTC, mihaimaruseac approved these changes

2020-06-26 18:42 UTC, merged