TF Chat Room
tensorflow/tensorflow pull request #40828
Opened 2020-06-26 12:15 UTC by Rishit-dagli

Added the [TensorFlow Chat Room on Stackoverflow](https://chat.stackoverflow.com/rooms/216694/tensorflow) URL in the resources section.

2020-06-26 18:16 UTC, mihaimaruseac commented
I'm unsure where we draw the line on what we include in the README and what not. Adding wicke@ for policy

2020-06-30 16:04 UTC, mihaimaruseac requested changes
Why add this image?

2020-06-30 16:37 UTC, martinwicke commented
The initial commit (f5d859777b3340319d44cc4f8897cad9039d0ddd) is fine, although we should add something like "(not actively monitored by the TensorFlow team)". 

@theadactyl where do you think this pointer would be best? I'm actually thinking the community site: https://www.tensorflow.org/community/forums, rather than resources, which seems to be more about consumable content than interactive forums.

2020-06-30 16:37 UTC, martinwicke commented
But yeah, the other two commits look like a mistake to me.

2020-06-30 16:39 UTC, Rishit-dagli commented
@martinwicke @mihaimaruseac The other two commits are indeed a mistake, I messed up my TensorFlow fork branches while working on another contribution to the repo, I will fix this.

2020-06-30 16:44 UTC, Rishit-dagli commented
@martinwicke @mihaimaruseac I have fixed the accidental commits. I apologize yet again for this confusion.

2020-06-30 16:45 UTC, mihaimaruseac reviewed
Adding the suggestion that this is not something we actively monitor (at least now)

2020-06-30 16:45 UTC, mihaimaruseac commented on README.md
> +*   [TensorFlow Chat Room on StackOverflow](https://chat.stackoverflow.com/rooms/216694/tensorflow)
```suggestion
*   [TensorFlow Chat Room on StackOverflow (not actively monitored by the TensorFlow team)](https://chat.stackoverflow.com/rooms/216694/tensorflow)
```

2020-06-30 17:15 UTC, mihaimaruseac approved these changes

2020-06-30 17:54 UTC, theadactyl commented
LGTM

On Tue, Jun 30, 2020 at 10:16 AM Mihai Maruseac <notifications@github.com>
wrote:

> *@mihaimaruseac* approved this pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/40828#pullrequestreview-440227196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABREJVPWU5U6URIBVIEGUITRZIMV7ANCNFSM4OJIYOCQ>
> .
>

2020-07-01 18:20 UTC, merged