fix docker envs
tensorflow/tensorflow pull request #41064
Opened 2020-07-03 13:19 UTC by fsx950223

Related https://github.com/tensorflow/tensorflow/issues/4078 https://github.com/tensorflow/tensorflow/issues/4267

```libcuda.so``` always located at ```/usr/lib/x86_64-linux-gnu/```

2020-07-09 15:48 UTC, gbaned commented
@angerson Can you please review this PR ? Thanks!

2020-08-03 16:49 UTC, gbaned commented
@angerson Can you please review this PR ? Thanks!

2020-08-03 21:13 UTC, angerson requested changes
Thanks! Can you follow the directions in the tools/dockerfiles directory to update the partials and regenerate all the relevant files, please?

2020-08-06 17:57 UTC, angerson approved these changes

2020-08-07 05:28 UTC, gbaned approved these changes

2020-08-07 06:59 UTC, merged