Sign compare warning fixes batch 11
tensorflow/tensorflow pull request #41167
Opened 2020-07-07 20:16 UTC by tg-at-google

2020-07-08 15:59 UTC, mihaimaruseac submitted a review, later dismissed

2020-07-09 14:57 UTC, mihaimaruseac commented
This also has build failures

```
tensorflow/compiler/xla/service/hlo_creation_utils.cc:408:55: error: 'it' was not declared in this scope
   for (int64 i = 0, iter_limit = operands.size(); i < it; ++i) {
                                                       ^~
tensorflow/compiler/xla/service/hlo_creation_utils.cc:408:55: note: suggested alternative: 'i'
   for (int64 i = 0, iter_limit = operands.size(); i < it; ++i) {
                                                       ^~
                                                       i
```

2020-07-10 16:05 UTC, mihaimaruseac requested changes

2020-07-10 16:05 UTC, mihaimaruseac commented on tensorflow/core/kernels/data/captured_function.cc
> +         i < end; ++i) {
This could fit in a single line?

2020-07-10 16:05 UTC, mihaimaruseac commented on tensorflow/core/profiler/utils/derived_timeline.cc
>         ++i) {
Could fit in a single line?

2020-07-10 16:05 UTC, mihaimaruseac commented on tensorflow/core/tpu/tpu_embedding_optimization_parameters_utils.cc
>         ++i) {
Single line

2020-07-10 16:05 UTC, mihaimaruseac commented on tensorflow/core/tpu/tpu_embedding_optimization_parameters_utils.cc
> +  for (int j = 0, end = state_variable_specs.size(); j < end;
single line

2020-07-10 16:05 UTC, mihaimaruseac commented on tensorflow/lite/toco/graph_transformations/drop_fake_quant.cc
>         i++) {
single line?

2020-07-10 16:05 UTC, mihaimaruseac commented on tensorflow/python/client/session_ref.cc
>           ++i) {
single line

2020-07-13 19:56 UTC, tg-at-google commented
@mihaimaruseac

2020-07-15 23:02 UTC, mihaimaruseac approved these changes

2020-07-16 15:55 UTC, mihaimaruseac submitted a review, later dismissed

2020-07-16 20:13 UTC, tg-at-google commented
diagnosing

2020-07-17 02:15 UTC, mihaimaruseac approved these changes

2020-07-17 02:16 UTC, mihaimaruseac requested changes

2020-07-17 02:16 UTC, mihaimaruseac commented on tensorflow/compiler/xla/service/dynamic_dimension_inference.cc
> +        for (int64 i = 0, iter_end = common_factors.size() - 1; i < iter_enditer_end; ++i) {
This has a typo

2020-07-17 02:34 UTC, tg-at-google commented on tensorflow/compiler/xla/service/dynamic_dimension_inference.cc
> +        for (int64 i = 0, iter_end = common_factors.size() - 1; i < iter_enditer_end; ++i) {
updated.

2020-07-17 02:43 UTC, mihaimaruseac submitted a review, later dismissed

2020-07-29 23:53 UTC, mihaimaruseac commented
Closing as it has been handled by new PRs.

2020-07-29 23:53 UTC, closed without merging