Pull Request
tensorflow/tensorflow pull request #41236
Opened 2020-07-09 11:27 UTC by Tyorden

New Pull Request

2020-07-09 16:17 UTC, mihaimaruseac requested changes

2020-07-09 16:17 UTC, mihaimaruseac commented on RELEASE.md
> +tomguluson92, Tongxuan Liu, TungJerry, Tyler Satchel Orden, v1incent, Vagif, vcarpani, Vikram Tiwari,
This is for an older release. You might want to add the github username on the part corresponding to the next release, at the beginning of the file. Although, the names listed here are for functional changes, not typo fixes.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Output.java
> +import java.lang.reflect.Method;
Why these imports?

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Session.java
> +import java.lang.reflect.Method;
Why these imports?

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Session.java
> + *       System.out.println(y.floatValue()); // Will print 6.0f
Coding style mandates 2 spaces before start of inline comments

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Session.java
> + *       System.out.println(y.floatValue()); // Will print 3.3f
Coding style mandates 2 spaces before start of inline comments

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +   return new Shape(null);
Coding style mandates 2 space indentation.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +   return new Shape(new long[0]);
Coding style mandates 2 space indentation.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +   return shape[i];
Coding style mandates 2 space indentation.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +   return Arrays.hashCode(shape);
Coding style mandates 2 space indentation.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +     return "<unknown>";
Coding style mandates 2 space indentation.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +     return !hasUnknownDimension();
Coding style mandates 2 space indentation.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +     return true;
Coding style mandates 2 space indentation.

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/java/src/main/java/org/tensorflow/Shape.java
> +    this.shape  =  shape;
Coding style mandates exactly one space around binary operators and assignments

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/python/tools/freeze_graph.py
> +This script is designed to take a GraphDef proto, a SaverDef proto, as well as a set of
Let's keep `and`

2020-07-09 16:17 UTC, mihaimaruseac commented on tensorflow/python/tools/freeze_graph.py
> +mobile or embedded environments where we may not have access to the
Should revert as the proposed changes eliminate a class of environments

2020-07-14 16:02 UTC, gbaned commented
@Tyorden  Can you please check @mihaimaruseac's comments and keep us posted. Thanks!

2020-07-22 13:44 UTC, gbaned commented
@Tyorden Any update on this PR? Please. Thanks!

2020-08-07 01:20 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-08-13 16:17 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2020-08-13 16:17 UTC, closed without merging