[TFLite] Quantization of PAD operator for 16x8 quantization scheme.
tensorflow/tensorflow pull request #41277
Opened 2020-07-10 11:40 UTC by wwwind

This PR enables quantization of PAD operator for 16x8 quantization scheme.
The reference kernel for 16-bit has been merged early.
This PR adds tests that need changes to the testing functions from this PR: https://github.com/tensorflow/tensorflow/pull/39543

2020-07-15 19:27 UTC, jdduke requested changes

2020-07-15 19:27 UTC, jdduke commented on tensorflow/lite/testing/op_tests/pad.py
> +          "quant_16x8": [False]
Is there a reason we can't use [False, True] here for quant_16x8? Rather than duplicating the test? Which parameters are different?

2020-07-16 10:49 UTC, wwwind commented
Hi @jdduke Thanks, corrected.

2020-07-21 09:12 UTC, wwwind commented
Hi @jdduke Could you please re-review this PR ?
tensorflowbutler removed "awaiting review" tag for unknown reasons.

2020-07-24 16:40 UTC, suharshs approved these changes

2020-07-26 05:55 UTC, merged