[TFLite] Added op tests for conv_activations
tensorflow/tensorflow pull request #41344
Opened 2020-07-13 15:51 UTC by wwwind

Op tests for conv operator with activation for 16x8 quantization mode.

Command to run them:
bazel run //tensorflow/lite/testing:generate_examples -- /tmp --zip_to_output=conv_activation --toco=$(pwd)/bazel-bin/tensorflow/lite/toco/toco

Follow up of #39543

2020-07-24 16:33 UTC, suharshs submitted a review, later dismissed

2020-08-10 16:16 UTC, rthadur commented
@wwwind can you please check below error ?
```
tensorflow/lite/testing/op_tests/conv_activation.py", line 143, in make_conv_relu_tests
    return make_conv_activation_tests(tf.nn.relu)(options)
  tensorflow/lite/experimental/mlir/testing/generate_examples.runfiles/google3/third_party/tensorflow/lite/testing/op_tests/conv_activation.py", line 129, in f
    expected_tf_failures=60)
  tensorflow/lite/experimental/mlir/testing/generate_examples.runfiles/google3/third_party/tensorflow/lite/testing/zip_test_utils.py", line 310, in make_zip_of_tests
    (zip_path, all_parameter_count, _MAX_TESTS_PER_ZIP))
RuntimeError: Too many parameter combinations for generating 'blaze-out/k8-opt/genfiles/third_party/tensorflow/lite/experimental/mlir/testing/conv_relu.zip'.
```

2020-08-10 16:36 UTC, wwwind commented
Hi @rthadur Could you please mention which bazel test task is failing ? 
What bazel test command should I call to reproduce these failures ?
Thanks!

2020-08-10 17:13 UTC, rthadur commented
@wwwind this tests are failing `https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/testing/zip_test_utils.py#L259` 

cc @suharshs

2020-08-18 12:14 UTC, wwwind commented
I found the source of problems. They should be fixed now.
I used the following commands to run these tests locally:

bazel test --compilation_mode=opt //tensorflow/lite/testing:zip_test_conv_relu
bazel test --compilation_mode=opt //tensorflow/lite/testing:zip_test_conv_relu1
bazel test --compilation_mode=opt //tensorflow/lite/testing:zip_test_conv_relu6

If I combine parameters like it was before, then I hit the error:
"There are at least 744 combinations while the upper limit is 500.
Having too many combinations will slow down the tests."

Hi @suharshs, @rthadur Could you please re-approve this PR ? Thanks

2020-08-18 16:48 UTC, rthadur approved these changes

2020-08-19 18:14 UTC, rthadur requested changes

2020-08-19 18:14 UTC, rthadur commented on tensorflow/lite/testing/op_tests/conv_activation.py
> +            "data_format": ["NHWC"],  # TODO(aselle): NCHW  would be good
can you please remove TODO

2020-08-20 08:20 UTC, wwwind commented
Hi @rthadur ! I have removed TODO comment. Could you please re-approve ? Thanks!

2020-08-20 16:58 UTC, rthadur approved these changes

2020-09-23 18:07 UTC, jdduke commented
Were you able to run this test locally using bazel? We're seeing a failure in the archive extraction:

```
F0923 04:56:40.382512    9627 generated_examples_zip_test.cc:244] Non-OK-status: archive_environment()->UnArchive(zip_file, tar_file, &decompress_tmp_dir) status: Unknown: unzip failed. stdout:
```

2020-09-23 18:17 UTC, jdduke commented
I think you can repro by trying:

```
bazel test //tensorflow/lite/testing:zip_test_conv_relu_forward-compat
```

2020-09-25 15:11 UTC, gbaned commented
@wwwind  Can you please check @jdduke's comments and keep us posted ? Thanks!

2020-09-25 15:13 UTC, wwwind commented
Sure, I will check these failures!

2020-09-30 16:41 UTC, wwwind commented
Hi @jdduke I can reproduce this error and it is due to the OS Error "File name too long", that happened during Archive -> Unzip.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/testing/generated_examples_zip_test.cc#L280

It has happened after recent updating with the master branch, when the new parameter 'dynamic_range_quantize=False' is added. 
with 'quant_16x8' is just too much.
Example of the file name:

conv_relu_forward-compat_channel_multiplier=2,constant_filter=True,data_format='NHWC',dilations=[1,1,1,1],dynamic_range_quantize=True,filter_shape=[3,3],fully_quantize=False,input_shape=[1,3,4,3],padding='VALID',quant_16x8=False,strides=[1,2,3,1]_tests.txt
        
There are two ways to solve:
- replace the name of some params with the shorter version - I don't know which one should I dio
- split arrays of dilations, input_shapes, strides into 1 per test/file
- implement a special check and a fallback code in the generated_examples_zip_test.cc

Could you please advise how should I go forward with this PR ? Thanks

2020-10-05 13:31 UTC, gbaned commented
@jdduke Can you please assist on above comments from @wwwind. Thanks!

2020-10-20 16:21 UTC, gbaned commented
@jdduke Any update on this CL? Please. Thanks!

2020-10-20 16:26 UTC, jdduke commented
Apologies, this one had been assigned to @suharshs, will reassign for landing!

2020-11-02 12:33 UTC, gbaned commented
Seems auto-merge is not happening but the changes are merged into master now, so we can close this. Thank you for the PR.

2020-11-02 12:33 UTC, closed without merging