[TFLite] Added op tests for leaky_relu
tensorflow/tensorflow pull request #41342
Opened 2020-07-13 15:43 UTC by wwwind

Op tests for leaky_relu operator for 16x8 quantization mode.

Command to run them:
bazel run //tensorflow/lite/testing:generate_examples -- /tmp --zip_to_output=leaky_relu --toco=$(pwd)/bazel-bin/tensorflow/lite/toco/toco

Follow up of https://github.com/tensorflow/tensorflow/pull/39543

2020-07-24 16:34 UTC, suharshs commented on tensorflow/lite/testing/op_tests/leaky_relu.py
> +          "input_shape": [[1, 10, 10, 3]],
Is it possible to group these last two cases into [False, True]?

2020-08-17 16:04 UTC, jdduke approved these changes

2020-08-18 17:42 UTC, jdduke requested changes
The test is failing. Can you try running:
```
bazel test //tensorflow/lite/testing:zip_test_leaky_relu  --compilation_mode=opt --test_env=TF2_BEHAVIOR=1
```

2020-08-24 07:46 UTC, wwwind commented
Hi @jdduke , @gbaned Could you please re-approve this PR ? This failure has been fixed.

2020-08-24 15:49 UTC, jdduke approved these changes

2020-08-27 08:13 UTC, merged