set attr num_sampled <= range_max
tensorflow/tensorflow pull request #4142
Opened 2016-09-01 02:01 UTC by shkr

For Log Uniform Candidate sampler the num_sampled cannot be more than the range_max as mentioned in #4112

2016-09-01 03:27 UTC, shkr commented
I signed it!

2016-09-06 21:00 UTC, danmane commented
@tensorflow-jenkins test this please

2016-09-06 21:04 UTC, zffchen78 commented
I think a better fix is to add a validation check on 
third_party/tensorflow/core/kernels/candidate_sampler_ops.cc:113

OP_REQUIRES(context, num_samples_ < range_max, ...)

2016-09-06 23:33 UTC, shkr commented
@zffchen78 I am unable to find third_party/tensorflow. Can you provide a link to the file where you think the validation will be better off ?

2016-09-10 00:37 UTC, danmane commented
@shkr look here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/candidate_sampler_ops.cc

2016-09-10 01:40 UTC, shkr commented
Thanks @danmane I will commit the change

2016-09-15 06:37 UTC, shkr commented
@danmane let me know if any other changes are required

2016-09-19 18:22 UTC, martinwicke commented
ping @danmane

2016-09-21 00:58 UTC, zffchen78 commented on tensorflow/core/kernels/candidate_sampler_ops.cc
> +    CHECK_LE(num_sampled_, range_max);
Can you use OP_REQUIRES(ctx, num_sampled_, range_max, errors::InvalidArgument("...", )) instead? 

It'll also better to add a test case in the corresponding python test to check the expected exception is raised.

2016-09-21 00:58 UTC, zffchen requested changes

2016-09-27 15:52 UTC, shkr commented on tensorflow/core/kernels/candidate_sampler_ops.cc
> +    CHECK_LE(num_sampled_, range_max);
Okay

2016-10-03 16:31 UTC, shkr commented
@zffchen78 I have made the requisite change

2016-10-22 17:58 UTC, drpngx commented
Jenkins, test this please.

2016-10-22 17:59 UTC, drpngx commented
@zffchen78 does this look good now?

2016-10-24 03:50 UTC, zffchen78 commented
No. I requested a test.

2016-10-25 17:34 UTC, shkr commented
@zffchen78 Did I miss anything or are you waiting for a jenkins test ?

2016-10-27 18:49 UTC, danmane commented
@shkr I believe @zffchen78 means, he requests that you add a Python unit test (probably in python/kernel_tests) to verify the new behavior.

2016-10-27 21:19 UTC, shkr commented
@danmane thanks I will add a unit test

2016-11-03 17:00 UTC, vrv commented
Any updates?

2016-11-04 18:31 UTC, vrv commented
Closing to help clear out our backlog, feel free to send a new PR once you've addressed these changes, or ping this thread and we'll reopen.

2016-11-04 18:31 UTC, closed without merging