Add minor TODO comment - test PR
tensorflow/tensorflow pull request #41517
Opened 2020-07-18 00:34 UTC by jonathanchu33

Test PR

2020-07-18 00:40 UTC, kkimdev requested changes

2020-07-18 00:40 UTC, kkimdev commented on tensorflow/python/eager/function.py
> +    # TODO: implement in C++
TODO needs ldap or a bug number
```
# TODO(jlchu): Implement in C++.
```

2020-07-20 16:36 UTC, kkimdev approved these changes

2020-07-20 18:50 UTC, sun51 approved these changes

2020-07-21 06:50 UTC, merged