[TFLite] Added coverage test for 16x8 quantizaion post-training mode.
tensorflow/tensorflow pull request #41560
Opened 2020-07-20 13:27 UTC by wwwind

Added a coverage test for 16x8 post-training quantization mode.

2020-07-31 08:52 UTC, akarmi commented
@jdduke, please check this change. We discussed it as one of the requirements for the stable release of 16x8-bit quantization.

2020-07-31 17:37 UTC, jdduke commented on tensorflow/lite/testing/model_coverage/model_coverage_lib.py
> +       "quantize_to_float16", "quant_16x8", "model_input_size"}.
Nit: Can we at least call this "quantize_16x8" or "post_training_quantize_16x8" for consistency with other "quantize" flags?

2020-07-31 17:37 UTC, jdduke requested changes
Looks good just one minor point on naming.

2020-07-31 19:16 UTC, wwwind commented
Hi @jdduke Thanks for the review. I renamed. Please take a look.

2020-08-07 23:23 UTC, jdduke approved these changes

2020-08-10 13:34 UTC, gbaned commented
@wwwind Can you please address Ubuntu Sanity errors? Thanks!

2020-08-10 15:53 UTC, wwwind commented
Hi @gbaned 
This failure does not look relevant to my changes.

The test //tensorflow/core/grappler/costs:op_level_cost_estimator_test is failing, but this failure is due to timeout. 
`tensorflow/core/grappler/costs/op_level_cost_estimator_test.cc:984
Expected equality of these values:
  cost.compute_time
    Which is: 5000ns
  Costs::Duration(expected_compute_time)
    Which is: 4300ns
Softmax`

I checked that is passes locally.
Could you please re-run Ubuntu Sanity Checks on this PR ?

2020-08-12 20:44 UTC, jdduke requested changes

2020-08-12 20:44 UTC, jdduke commented on tensorflow/lite/testing/model_coverage/model_coverage_lib.py
> +       "quantize_to_float16", "post_training_quantize_16x8", "model_input_size"}.
This is longer than 80 lines, can you fix?

2020-08-13 12:02 UTC, wwwind commented
@jdduke fixed. Could you please re-approve ? Thanks!

2020-08-18 17:36 UTC, jdduke approved these changes

2020-08-19 04:03 UTC, merged