add specialized size_t comparison macros to reduce number of warnings
tensorflow/tensorflow pull request #4157
Opened 2016-09-01 22:04 UTC by Mistobaan

2016-09-06 20:21 UTC, danmane commented
@keveman Can you please take a look?

2016-09-19 21:06 UTC, martinwicke commented on tensorflow/core/platform/default/logging.h
> +// comparison errors while still being through with the comparison.
through -> thorough

2016-09-19 21:09 UTC, martinwicke approved these changes
LGTM

2016-09-19 21:10 UTC, martinwicke requested changes
Please fix the typo though.

2016-09-20 09:39 UTC, Mistobaan commented
@martinwicke fixed

2016-09-20 15:55 UTC, martinwicke commented
Jenkins, test this please.

2016-09-20 15:55 UTC, martinwicke approved these changes

2016-09-20 17:55 UTC, merged