Modified oneDNN build so as to not include the MKL blob when building…
tensorflow/tensorflow pull request #41645
Opened 2020-07-23 01:13 UTC by agramesh1

… with Eigen threadpool.

2020-07-27 23:10 UTC, penpornk requested changes
Thank you for the PR! The new configurations make it less confusing. 👍 
I have two minor nits please.

2020-07-27 23:10 UTC, penpornk commented on tensorflow/core/kernels/mkl_batch_matmul_op.cc
> +// cases with oneDNN, CBLAS calls will be removed.
Thank you for the detailed documentation!

2020-07-28 00:35 UTC, penpornk submitted a review, later dismissed
Thank you!

2020-07-29 23:53 UTC, agramesh1 commented
> @agramesh1 Can you please check build failures. Thanks!

@gbaned thank you, I will take a look at it.

2020-07-31 19:44 UTC, penpornk approved these changes
Thank you for the fix!

2020-07-31 22:05 UTC, rthadur approved these changes

2020-08-05 00:05 UTC, merged