[Wsign-compare] warning resolutions, by directory, 6
tensorflow/tensorflow pull request #41753
Opened 2020-07-26 22:21 UTC by tg-at-google

Resolution affecting directories:
`tensorflow/compiler/xla`,
`tensorflow/compiler/xla/service`

@mihaimaruseac

2020-07-27 16:32 UTC, mihaimaruseac commented
`tensorflow/compiler/xla` is also covered y #41752.

2020-07-27 16:38 UTC, mihaimaruseac requested changes

2020-07-27 16:38 UTC, mihaimaruseac commented on tensorflow/compiler/xla/service/llvm_ir/llvm_loop.cc
> +    if (dimension == dimension_to_skip_int) {
`dimension_to_skip` is already `int64`.

2020-07-27 16:38 UTC, mihaimaruseac commented on tensorflow/compiler/xla/service/memory_space_assignment.cc
> +    if (logical_time >= instructions_elapsed_time_size) {
```suggestion
    const int64 actual_time = instructions_elapsed_time.size();
    if (logical_time >= actual_time) {
```

2020-07-27 16:38 UTC, mihaimaruseac commented on tensorflow/compiler/xla/service/memory_space_assignment.cc
>           ++instruction_index) {
These two lines can now be merged

2020-07-28 00:19 UTC, tg-at-google commented
> `tensorflow/compiler/xla` is also covered y #41752.

Yes, they are essentially 2 batches.

2020-07-28 19:45 UTC, tg-at-google commented on tensorflow/compiler/xla/service/llvm_ir/llvm_loop.cc
> +    if (dimension == dimension_to_skip_int) {
update appled.

2020-07-28 19:51 UTC, tg-at-google commented on tensorflow/compiler/xla/service/memory_space_assignment.cc
>           ++instruction_index) {
update appled.

2020-07-28 19:55 UTC, tg-at-google commented
updates applied.

2020-07-28 22:59 UTC, mihaimaruseac requested changes

2020-07-28 22:59 UTC, mihaimaruseac commented on tensorflow/compiler/xla/service/llvm_ir/llvm_loop.cc
> +  for (int64 dimension = 0; dimension < multi_index.size(); ++dimension) {
I don't think we need to change anything here. Both the loop counter and the limit should be unsigned

2020-07-29 01:21 UTC, tg-at-google commented
updates applied, 2.

2020-07-29 16:24 UTC, mihaimaruseac approved these changes

2020-07-29 17:14 UTC, mihaimaruseac commented
This seems to cause build failures. Can you investigate please?

2020-07-29 20:25 UTC, tg-at-google commented
> This seems to cause build failures. Can you investigate please?

++, will investigate.

2020-07-31 04:01 UTC, closed without merging