[Wsign-compare] warning resolutions, by directory, 8
tensorflow/tensorflow pull request #41756
Opened 2020-07-27 00:04 UTC by tg-at-google

Resolution affecting directories:
`tensorflow/core/`

set 3 of 3

2020-07-27 00:05 UTC, tg-at-google commented
@mihaimaruseac

2020-07-27 16:47 UTC, mihaimaruseac requested changes
Please remove unrelated changes

2020-07-28 19:05 UTC, tg-at-google commented
> Please remove unrelated changes

Unrelated changes removed.

2020-07-28 23:18 UTC, mihaimaruseac requested changes

2020-07-28 23:18 UTC, mihaimaruseac commented on tensorflow/core/profiler/convert/op_stats_to_overview_page.cc
>        static_cast<decltype(candidates)::size_type>(3), candidates.size());
This should be kept as `auto` since it is supposed to be the same as the `decltype...`

2020-07-28 23:18 UTC, mihaimaruseac commented on tensorflow/core/profiler/convert/xplane_to_memory_profile.cc
> +    while (i < active_allocs_size &&
```suggestion
    const int last_alloc = active_allocs.size() - 1;
    while (i < last_alloc &&
```

2020-07-28 23:18 UTC, mihaimaruseac commented on tensorflow/core/profiler/convert/xplane_to_memory_profile.cc
> +    while (i < active_allocs_size &&
And then everything can go on the same line

2020-07-28 23:18 UTC, mihaimaruseac commented on tensorflow/core/profiler/internal/tfprof_code.cc
> +      if (i == max_stack_trace_allowed_size) {
```suggestion
      const int64 last_trace = fn->call_stack()->traces().size() - 1;
      if (i == last_trace) {
```

2020-07-28 23:18 UTC, mihaimaruseac commented on tensorflow/core/util/padding.cc
> +    if (explicit_paddings_size != 2 * num_dims) {
```suggestion
    const int num_paddings = explicit_paddings.size();
    if (num_paddings != 2 * num_dims) {
```

2020-07-29 01:06 UTC, tg-at-google commented
updates applied.

2020-07-29 01:11 UTC, tg-at-google commented
updates applied, 2.

2020-07-29 16:28 UTC, mihaimaruseac requested changes

2020-07-29 16:28 UTC, mihaimaruseac commented on tensorflow/core/profiler/convert/op_stats_to_overview_page.cc
> +  for (int64 i = 0, end = num_functions_shown; i < end; i++) {
```suggestion
  for (decltype(candidates)::size_type i = 0; i < num_functions_shown; i++) {
```

2020-07-29 16:28 UTC, mihaimaruseac commented on tensorflow/core/profiler/convert/op_stats_to_overview_page.cc
> +  if (candidates_size > num_functions_shown)
I am not sure this is needed, both should now have the same type

2020-07-29 16:32 UTC, tg-at-google commented
recommended updates applied.

2020-07-29 17:16 UTC, mihaimaruseac approved these changes

2020-07-29 22:09 UTC, merged