[Wsign-compare] warning resolutions, by directory, 7
tensorflow/tensorflow pull request #41754
Opened 2020-07-26 23:53 UTC by tg-at-google

Resolution affecting directories:
`tensorflow/core/`

set 1 of 3

2020-07-26 23:53 UTC, tg-at-google commented
@mihaimaruseac

2020-07-27 16:41 UTC, mihaimaruseac requested changes

2020-07-27 16:41 UTC, mihaimaruseac commented on tensorflow/core/distributed_runtime/collective_rma_distributed.cc
> +      if (num_bytes != to_tensor_TotalBytes) {
```suggestion
      const int64 total_bytes = to_tensor->TotalBytes();
      if (num_bytes != total_bytes) {
```

2020-07-27 16:41 UTC, mihaimaruseac commented on tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc
> +      if (default_now_micros > expired_time_micros && timeout_in_ms > 0) {
```suggestion
      const int64 now = Env::Default()->NowMicros();
      if (now > expired_time_micros && timeout_in_ms > 0) {
```

2020-07-28 19:38 UTC, tg-at-google commented
All updates applied

2020-07-28 23:00 UTC, mihaimaruseac approved these changes

2020-07-30 16:09 UTC, merged