[Intel MKL] BF16 enabling for MklLayoutPass test - v5
tensorflow/tensorflow pull request #41872
Opened 2020-07-29 19:47 UTC by noim210

[Intel MKL] BF16 enabling for MklLayoutPass test - v5
Signed-off-by: mazharul <mazharul.islam@intel.com>

2020-07-29 22:19 UTC, nhasabni commented
@googlebot I consent.

2020-08-27 01:03 UTC, penpornk requested changes
Thank you for the PR and I'm so sorry for my long delay!

2020-09-02 18:30 UTC, gbaned commented
@noim210 Can you please check @penpornk's comments and keep us posted ? Thanks!

2020-09-11 17:55 UTC, gbaned commented
@noim210  Any update on this PR? Please. Thanks!

2020-09-11 18:41 UTC, noim210 commented
Yes, I am almost done with the requested review. I am going to push soon.

2020-09-11 18:42 UTC, noim210 commented on tensorflow/core/common_runtime/mkl_layout_pass_test.cc
> +REGISTER_TEST_FLOAT32(MaxPoolLRN_Positive);
Yes, we might expand it to bfloat16, when bfloat16 will be available for this.

2020-09-11 22:44 UTC, noim210 commented on tensorflow/core/common_runtime/mkl_layout_pass_test.cc
> +#define REGISTER_TEST(NAME, T, INPUT)                                         \
I updated the code according to your suggestion

2020-09-11 22:44 UTC, noim210 commented on tensorflow/core/common_runtime/mkl_layout_pass_test.cc
> +#define REGISTER_TEST(NAME, T, INPUT)                                         \
I updated the code according to your suggestion

2020-09-11 22:45 UTC, noim210 commented on tensorflow/core/common_runtime/mkl_layout_pass_test.cc
> +#define REGISTER_TEST(NAME, T, INPUT)                                         \
I updated the code according to your suggestion

2020-09-11 23:19 UTC, penpornk approved these changes
Thank you again for the PR!

2020-09-11 23:19 UTC, penpornk commented on tensorflow/core/common_runtime/mkl_layout_pass_test.cc
> +REGISTER_TEST_FLOAT32(MaxPoolLRN_Positive);
Thank you for the clarification!

2020-09-14 18:38 UTC, merged