[Intel MKL] Supporting native format in Convolution Bwd
tensorflow/tensorflow pull request #42072
Opened 2020-08-05 20:10 UTC by mahmoud-abuzaina

This PR adds support for native(user) format in convolution backward ops. _MklNative* ops will be used in both graph and eager modes. 
This PR needs to be merged after "DNNL 1.5.1 Upgrade" PR is merged. Link is coming soon.

2020-08-18 17:04 UTC, penpornk requested changes
Thank you for the PR and I'm sorry for the delay! I have a few comments.

2020-08-19 00:29 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_grad_filter_ops.cc
> +template <typename T, bool native_format>
Done.

2020-08-19 00:29 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_grad_input_ops.cc
> +template <typename T, bool native_format>
Done.

2020-08-19 00:29 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_grad_filter_ops.cc
> +template <typename T, bool native_format>
Done.

2020-08-19 00:29 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_grad_input_ops.cc
> +template <typename T, bool native_format>
Done.

2020-08-19 00:30 UTC, mahmoud-abuzaina commented
Thank you for the review. I have made the changes based on your comments.

2020-08-19 19:39 UTC, penpornk approved these changes
Thank you for the quick changes!

2020-08-20 01:15 UTC, penpornk commented
@mahmoud-abuzaina Could you please help resolve the merge conflict? Thank you!

2020-08-20 01:43 UTC, mahmoud-abuzaina commented
Actually I did not find any conflict but did merge with master. Can you check now?

2020-08-20 03:52 UTC, penpornk approved these changes
Thank you! I'll try pulling it in again. If this doesn't work, I'll take care of it internally.

2020-08-20 05:12 UTC, merged