Fix segmentation fault in tf.image.crop_and_resize when boxes is inf or nan
tensorflow/tensorflow pull request #42143
Opened 2020-08-08 00:51 UTC by yongtang

This fix tries to address the issue raised in #42129 where segmentation fault
happened in tf.image.crop_and_resize when boxes is inf or nan.

This fix adds the check to make sure boxes is not inf or nan (isfinite)

This fix fixes #42129.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2020-08-09 01:09 UTC, mihaimaruseac submitted a review, later dismissed

2020-08-09 01:09 UTC, mihaimaruseac commented on tensorflow/core/kernels/crop_and_resize_op.cc
> +
```suggestion
```

2020-08-09 01:10 UTC, mihaimaruseac submitted a review, later dismissed

2020-08-12 17:35 UTC, gbaned commented
@yongtang Can you please resolve conflicts? Thanks!

2020-08-20 02:57 UTC, gbaned commented
@yongtang, Any update on this PR? Please. Thanks!

2020-08-25 20:35 UTC, yongtang commented
Due to the way GPU/CPU pipeline works in the kernel, it looks like to do a nan check on GPU is not exactly straightforward. That was causing the GPU test failure.

Let me take another look and see how to resolve this issue.

2020-08-27 18:44 UTC, mihaimaruseac submitted a review, later dismissed

2020-08-27 18:44 UTC, mihaimaruseac commented on tensorflow/core/kernels/image/crop_and_resize_op.cc
> +
```suggestion
```

2020-08-27 18:45 UTC, mihaimaruseac approved these changes

2020-10-12 06:13 UTC, sanjoy requested changes
This PR is failing some tests.  Are you sure that the `boxes.tensor<float, 2>().isfinite().all()` line is correct even when the operation is running on a GPU?

2020-10-14 10:26 UTC, gbaned commented
@yongtang  Can you please check @sanjoy's comments and keep us posted ? Thanks!

2020-10-18 21:31 UTC, mihaimaruseac commented
The test added by the PR does not fail in CUDA if I remove the C++ check that causes the segfaults

2020-10-19 05:15 UTC, mihaimaruseac commented
I think I got this fully fixed internally. Running a full suite of tests and sending for review tomorrow.

2020-10-19 21:04 UTC, merged