Add Python kernel and tests for decode_image
tensorflow/tensorflow pull request #4222
Opened 2016-09-06 03:55 UTC by samjabrahams

For #4009: Automatically detects whether the bytes passed in are JPEG, PNG, or neither and returns a `decode_jpeg` op, `decode_png` op, or ValueError respectively.

Before merging, need to hard-code the [`imghdr.what()`](https://docs.python.org/2/library/imghdr.html#imghdr.what) function, which is luckily already [written in pure Python](https://hg.python.org/cpython/file/2.7/Lib/imghdr.py)

2016-09-06 04:57 UTC, samjabrahams commented on tensorflow/python/ops/image_ops.py
> +
Need to add more documentation here.

2016-09-06 05:45 UTC, samjabrahams commented
The `_image_type()` function placeholder logic that needs to go into a separate TensorFlow operation. The code currently pushed works if pre-loaded bytes are sent to the Op, but will crash and burn if the output from another op is passed in (say, from `tf.read_file()`)

2016-09-06 20:03 UTC, danmane commented
I'm assuming that since this is still a WIP we should hold off on reviewing and testing it. Let me know if that isn't the case.

2016-09-06 22:13 UTC, samjabrahams commented
@danmane That's correct. The current code works if you load the bytes of a file ahead of time, but would throw an error if you passed in code from a function like `tf.read_file`.

The current game plan is to write a `tf.substr` Op and then utilize it in this function. [Here's that conversation for context.](https://github.com/tensorflow/tensorflow/issues/4009#issuecomment-244863602)

Thanks!

2016-10-11 23:55 UTC, rohan100jain commented
Any updates on this?

2016-10-12 16:46 UTC, samjabrahams commented
@rohan100jain Waiting for feedback on #4338: I can close this in the meantime if you'd prefer.

2016-11-04 21:52 UTC, samjabrahams commented
@rohan100jain @danmane - `tf.substr` has been merged, and I've update this Op to utilize it. There are a few things left to do, but the main functionality of the op is here. Left to do:

* More/better documentation
* More tests (should we test with small jpeg/png/gif files in addition to hard-coding in bytes?)
* Tests for gifs

2016-11-09 00:20 UTC, vrv commented
Thanks @samjabrahams !  Ping us when you think this is ready for a final review.

2016-11-12 08:07 UTC, samjabrahams commented
@vrv ready for review! Couple of judgement calls:

* Included GIF support. `decode_gif` returns a 4-D tensor as opposed to 3-D for `decode_jpeg` and `decode_png` due to the extra "number-of-frames" dimension. I'm also not sure if `decode_gif` is supposed to be exposed publicly yet (currently not in the API).
* Did not add actual image files to be read from disk and tested- stuck with hard-coded byte strings.

2016-11-12 16:12 UTC, vrv commented
@girving let me know if you have time to look at this.  I worry that the variable shape output of this convenience op will make it inconvenient :), but maybe it'll be alright.  Also, it might make sense to think about how to pass the options to decode_image in a better way -- otherwise the op's arguments are going to keep increasing to account for every image option that is added.

2016-11-12 16:26 UTC, samjabrahams commented
The different shaped output definitely seems a bit clunky. Couple options (which may or may not be any less clunky):

1. Return `tf.squeeze(tf.decode_gif(...))`. Since the `decode_gif` option always has three color channels, this will return a 3-D tensor for single-framed gifs (assuming the image is larger than 1x1) and 4-D tensors otherwise. If `decode_gif` ever gets an option for number of color channels, this will have to be modified.
2. Reshape the png and jpeg results to be 4-D. This keeps it consistent, but means that this Op requires a different workflow to the standard `decode_png` and `decode_jpeg`
3. Remove the `decode_gif` portion 
4. Leave it as is and have the end user figure it out.

For the growing number of parameters: I could use `**kwargs` and either let the user look up the options, or just leave the options out of the function signature but include them in the documentation.

2016-11-14 16:19 UTC, girving commented
I can look at it, but could we squash it before the initial review?

2016-11-14 19:34 UTC, samjabrahams commented
@girving Squashed!

2016-11-14 20:51 UTC, girving requested changes

2016-11-14 20:51 UTC, girving commented on tensorflow/python/kernel_tests/decode_image_op_test.py
> +                   b'\x00\x00\x00\x02\x00\x02\x00\x00\x02\x03D4\x05\x00;')
Please use the same test files as `image_ops_test.py`: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_test.py#L1953

2016-11-14 20:51 UTC, girving commented on tensorflow/python/kernel_tests/decode_image_op_test.py
> +                   b'\xd9')
Use test files as above.

2016-11-14 20:51 UTC, girving commented on tensorflow/python/kernel_tests/decode_image_op_test.py
> +                   b'\x00\x00\x00IEND\xaeB`\x82')
Use test files.

2016-11-14 20:51 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +                 try_recover_truncated=None, acceptable_fraction=None,
I think we should just drop the `ratio`, `fancy_upscaling`, `try_recover_truncated`, and `acceptable_fraction` arguments.  If you want these details you should use the underlying format op.

2016-11-14 20:51 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +      return gen_image_ops.decode_gif(contents)
The `_gif` case should handle channels somehow.

2016-11-14 20:51 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +      return gen_image_ops.decode_png(contents, channels, dtypes.uint8)
`dtypes.uint8` should be unnecessary since it's the default, right?

2016-11-14 20:51 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +      return gen_image_ops.decode_gif(contents)
Don't use `gen_image_ops` and `gen_string_ops` in this function.  It should use the normal exposed names.

2016-11-14 20:51 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +                            b'\xff\xd8\xff\xe0')
Only do `substr(contents, 0, 4)` once.

2016-11-14 20:51 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +                                   name=scope)
Use nested cases in the following order for speed:

1. Check for jpeg, decode jpeg if so.
2. Check for png, decode png if so.
3. Check for gif, decode gif if so.
4. Throw the assertion.

The point is that we should waste time checking for gif or png in the jpeg case, which is the most common.

2016-11-14 21:21 UTC, samjabrahams commented on tensorflow/python/ops/image_ops.py
> +      return gen_image_ops.decode_gif(contents)
For `_gif`: Should I use `tf.image.rgb_to_grayscale` and `tf.image.grayscale_to_rgb`, and limit `channels` to 0, 1, or 3 (exclude alpha channels for PNG)?

2016-11-14 21:43 UTC, samjabrahams commented on tensorflow/python/ops/image_ops.py
> +                                   name=scope)
@girving Was something like this what you had in mind?

```python
def _fail():
    return tf.Assert(False, [b'Not decodable!'])
def _try_gif():
    return tf.cond(is_gif, _gif, _fail)
def _try_png_gif():
    return tf.cond(is_png, _png, _try_gif)

return tf.cond(is_jpeg, _jpeg, _try_png_gif)
```

The reason I haven't set it up this way was that `tf.cond` and `tf.case` need all of the callable functions to return `Tensor` objects with the same type (so the above code wouldn't work when it tries to use the `_fail` function). I might be able to do it in a hacky way by having `_fail` call a dummy Op nested inside of a control dependency:

```python
def _fail():
    with tf.control_dependencies(tf.Assert(False, b'Not decodable!')):
        return tf.zeros([], dtype=tf.uint8)
```

2016-11-14 22:50 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +                                   name=scope)
You can put an assert that it's a gif before the decode gif path.

2016-11-14 23:11 UTC, samjabrahams commented on tensorflow/python/ops/image_ops.py
> +      return gen_image_ops.decode_gif(contents)
I don't think so? I'm digging around the[ `decode` implementation in tensorflow/core/lib/gif](https://github.com/tensorflow/tensorflow/blob/6b1d4fd8090d44d20fdadabf06f1a9b178c3d80c/tensorflow/core/lib/gif/gif_io.cc#L35), which currently has the number of channels hard coded to three. If you try to pass in a `channels` argument to `decode_gif`, you get an error, as [`channels` isn't registered as a parameter](https://github.com/tensorflow/tensorflow/blob/816ecb7a342c25c19daa8b19627346e1fb38e56f/tensorflow/core/ops/image_ops.cc#L522-L524). Additionally, the [`DecodeGifOp` only reads one value (the image contents) from the context](https://github.com/tensorflow/tensorflow/blob/6b1d4fd8090d44d20fdadabf06f1a9b178c3d80c/tensorflow/core/kernels/decode_gif_op.cc#L36).

2016-11-14 23:17 UTC, samjabrahams commented on tensorflow/python/ops/image_ops.py
> +      return gen_image_ops.decode_gif(contents)
Got it!

2016-11-15 00:55 UTC, samjabrahams commented on tensorflow/python/ops/image_ops.py
> +      return gen_image_ops.decode_gif(contents)
I had to do the channels check with another assert message due to how `cond` runs it's function parameters. It seems like the Op-returning functions (`_gif`, `_png`,` _jpeg`) all run at Op creation time, which means that `_jpeg` gets unhappy when `channels` is 4 (granted, the user should probably just be using `decode_png` at that point). How does `if channels is not None or channels not in (0, 1, 3)`, throw an error at the beginning sound?

2016-11-15 00:57 UTC, girving requested changes

2016-11-15 00:57 UTC, girving commented on tensorflow/python/kernel_tests/decode_image_op_test.py
> +          gt[start:end, :, :] = 255
What does this bit do?

2016-11-15 00:57 UTC, girving commented on tensorflow/python/ops/image_ops.py
> +      if channels is not None and channels not in (0, 3):
`if channels not in (None, 0, 3):`

2016-11-15 01:08 UTC, samjabrahams commented on tensorflow/python/kernel_tests/decode_image_op_test.py
> +          gt[start:end, :, :] = 255
I grabbed this from the GIF tests in python/ops/image_ops_test.py. The [test image](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/gif/testdata/scan.gif) is a multi-framed image of a white bar travelling across a black background. It looks like this test starts with an all-black (zeros) array and then fills in the appropriate pixels with white (255) depending on which frame it is.

I can comment an explanation in or remove this check if you want.

2016-11-29 23:11 UTC, danmane commented
@samjabrahams What's the status here? I think @girving is on vacation but I can likely find someone else to review if you're ready to move forward. Also, please rebase and fix conflicts.

2016-11-30 00:15 UTC, girving commented
@danmane Sorry, Github state machine failure.  I had forgotten about this.  Looking now.

2016-11-30 00:18 UTC, girving approved these changes

2016-11-30 00:18 UTC, girving commented
Jenkins, test this please.

2016-11-30 00:18 UTC, girving commented
@samjabrahams Looks like I've delayed long enough that it needs conflict resolution.  Sorry about that. :/

2016-11-30 05:45 UTC, samjabrahams commented
@girving No worries- I've rebased and cleaned up the implementation a bit. The last major headache here is dealing with `channels` along the GIF path. Unfortunately, creating the path isn't as simple as the following:

```python
def _gif():
    if channels not in (None, 0, 3):
        raise ValueError('GIF images must be decoded with channels in (None, 0, 3)
    # ... do the op
```

Because `tf.cond` always ends up running the `_gif` function, the check happens even if there are no GIF files being decoded. That means that `channels` can't be set to 1 if we go with this approach. 

If we try using `tf.Assert` instead, it might look like this:

```python
good_op = tf.not_equal(channels, 1)   # Already checked that channels in (None, 0, 1, 3)
assert_good = tf.Assert(good_op, ['channels can't be 1!'])
with tf.control_dependencies([assert_good]):
    # ...do the rest
```
This doesn't work either, as we run into the issue of `channels` being set to `None`, which can't be passed into `equal` or `not_equal`.

In short, I'm not sure how I'd allow different channels for different image types. Here are two different ways to handle `channels` I know I can make work:

1. Use `rgb_to_grayscale` to convert the GIF image to black/white if `channels` is set to 1. It might be a little bit much going on under-the-hood, but I imagine it accomplishes the intent of what users want. The current code does this.
2. Only allow channels to be in (None, 0, 3), excluding 1 for all image types. This is a bit cleaner, though it reduces the functionality.

2016-11-30 05:50 UTC, samjabrahams commented
Also, after the move to image_ops_impl.py, it's no longer possible to use `decode_*` without prefixing with `gen_image_ops`, hence their return.

2016-11-30 15:36 UTC, girving commented
I think you should be able to use a `tf.Assert(false, ...)` as long as it has enough control dependencies to only run in the gif case (which should happen automatically if the assert is placed in try_gif).

2016-11-30 15:39 UTC, girving commented
I'm also fine with only allowing `(None, 0, 3)` channels.

2016-11-30 18:48 UTC, samjabrahams commented
@girving I believe I've got it working with an Assert checking that `channels` isn't set to 1 along the gif path.   I was being a dummy, since `None` can be interpreted as `0` by default. Let me know if this looks alright!

2016-11-30 19:11 UTC, girving approved these changes

2016-11-30 19:12 UTC, girving commented
Jenkins, test this please.

2016-11-30 20:01 UTC, girving approved these changes

2016-11-30 20:03 UTC, girving commented
@mrry: The newly added `decode_image` tests are failing to find the test files on Windows.  Do you know why that would happen on Windows but not on other platforms?

2016-11-30 20:11 UTC, samjabrahams commented
Looks like it's a path issue: `tensorflow/core/lib/gif/testdata/scan.gif : The system cannot find the path specified.` Curse you backslashes! I'll wrap the files with `os.path.join` and see if that works.

2016-11-30 20:14 UTC, mrry commented
I assume it's because the working directory isn't what the test expects. (It looks like the similar code `image_ops_test.py` isn't running as part of the Windows build because it's in `python/ops` rather than `python/kernel_tests`.)

As a quick workaround, you might try adding `WORKING_DIRECTORY ${tensorflow_source_dir}` to [this line](https://github.com/tensorflow/tensorflow/blob/9d5c3b35f59c42445a0d1e01d46e606d27ae6f7c/tensorflow/contrib/cmake/tf_tests.cmake#L102) and see if it fixes things.

2016-11-30 21:01 UTC, samjabrahams commented
@girving @mrry I pushed the change to `tf_tests.cmake` so we can see if that does the trick.

2016-11-30 21:02 UTC, girving commented
Jenkins, test this please.

2016-11-30 22:15 UTC, samjabrahams commented
May need to rerun- the GPU test had an aneurysm when trying to `git fetch`

2016-11-30 22:23 UTC, girving commented
Jenkins, test this please.

2016-11-30 23:10 UTC, girving commented
@zffchen78 The Linux GPU build has twice failed during git fetch.  Do you know what might be going wrong?

2016-11-30 23:20 UTC, Mistobaan commented
The fact that it returns different tensors shapes based on the  file format is not the 'usual' tensoflow way.
Can we just return the first frame in case of a gif image instead? If the user *really* wants the whole gif sequence then they can use the specialized version. This function will be very useful when you have mixed images formats in your data folder.

2016-11-30 23:24 UTC, girving commented
@Mistobaan What fixed shape do the other image decode functions return?

2016-11-30 23:32 UTC, samjabrahams commented
Right now `decode_jpeg` and `decode_png` return tensors with rank 3, while `decode_gif` returns one with rank 4, as it can decode multiple frames from a gif image.

2016-11-30 23:45 UTC, girving commented
Jenkins, test this please.

2016-12-01 00:12 UTC, samjabrahams commented
@Mistobaan you can always `tf.squeeze` the output of this Op of you know that you have gifs that only contain a single frame. Personally, I don't really know what the "TensorFlowian" way to do it would be, but it seems wrong to discard image data (by automatically only keeping the first frame of multi-frame gifs). That said, I wasn't sure I should even include gif support when I started this Op due to the rank differences. Here are my thoughts for options:

1. Leave it as is. Let users figure out how they want to handle gifs
2. Don't allow multi-frame gifs. Throw an assertion error if the number of frames is greater than 1, and squeeze the first dimension out
3. Leave it as is, and create a `contrib` layer that does extra work to ensure that the output ranks match for jpeg, png, and gif

2016-12-01 00:25 UTC, girving commented
I'd prefer to either leave it as is or automatically squeeze the first dimension of the gif if it's a single frame (unfortunately that requires another `tf.cond`).  Silently discarding data by picking the first frame is not a good idea.

2016-12-01 00:57 UTC, girving commented
If we want to add the optional squeeze to gif I think it can be done in a second pass.  I'm going to merge for now.

2016-12-01 00:58 UTC, merged