Prevent Aborted (core dumped) in tf.nest.assert_same_structure for type mismatch in passed args
tensorflow/tensorflow pull request #42397
Opened 2020-08-15 19:15 UTC by yongtang

This PR tries to address the issue raised in #42329 where
tf.nest.assert_same_structure will abort with core dump when
check_types is passed with a non-bool value.

The issue is related to pybind where type mismatch will
throw out an error and further cause 'pybind11::error_already_set' error.

This PR explicitly convert check_types to bool before passing to pybind,
and, in case check_types is not bool, an ValueError will be thrown out
gracefully by python itself.

This will be better than process abort (core dump).

This PR fixes #42329.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2020-08-17 13:36 UTC, mdanatg submitted a review, later dismissed

2020-08-17 22:18 UTC, rthadur commented
@yongtang can you please check sanity build failures ?

2020-08-18 15:13 UTC, yongtang commented
Thanks  @mdanatg @rthadur for the review. The PR has been updated with pylint failure fixed. Please take a look and let me know if there is any other issues.

2020-08-18 15:30 UTC, mdanatg approved these changes

2020-08-19 19:28 UTC, mdanatg requested changes

2020-08-19 19:28 UTC, mdanatg commented on tensorflow/python/util/nest_test.py
> +    with self.assertRaises(ValueError):
This got flagged by internal tests: in graph mode, attempting to `bool()` cast a Tensor raises a specific error instead (`OperatorNotAllowedInGraphError`, a subclass of `TypeError`). I think the easiest way is to test that either ValueError os TypeError is raised.

2020-08-19 20:04 UTC, yongtang commented
Thanks @mdanatg for the help! The PR has been updated with captured exceptions expanded. Please take a look and see if the issue still exists.

2020-08-19 20:10 UTC, mdanatg approved these changes

2020-08-20 00:50 UTC, merged