port TF Lite micro speech example to CEVA-DSP BX1
tensorflow/tensorflow pull request #42414
Opened 2020-08-16 14:22 UTC by yair-ehrenwald

This is a port of the Micro Speech example to CEVA-DSP BX1.
the PR is a continuation of PR37831 (https://github.com/tensorflow/tensorflow/pull/37831)

The issues raised there should be resolved now.

2020-09-08 18:59 UTC, advaitjain approved these changes
Approving since we do not have a better solution at this time and this PR was created before we updated our contribution guidelines.

We are trying to find time to revisit how TFLM fits with examples and project generation so expect some breaking changes in the coming months. We will give an appropriate heads-up on the SIG-micro mailing list.

2020-09-09 13:11 UTC, advaitjain requested changes
automated internal checks caught what I missed in the review. please use the TF_LITE_REPORT_ERROR macro instead of direct calls to error_reporter->Report

2020-09-09 13:11 UTC, advaitjain commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +        model->version(), TFLITE_SCHEMA_VERSION);
replace with TF_LITE_REPORT_ERROR(error_reporter, "...")

2020-09-09 13:11 UTC, advaitjain commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +    error_reporter->Report("AllocateTensors() failed");
replace with TF_LITE_REPORT_ERROR(error_reporter, "...")

2020-09-09 13:11 UTC, advaitjain commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +    error_reporter->Report("Feature generation failed");
replace with TF_LITE_REPORT_ERROR(error_reporter, "...")

2020-09-09 13:11 UTC, advaitjain commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +    error_reporter->Report("Invoke failed");
replace with TF_LITE_REPORT_ERROR(error_reporter, "...")

2020-09-09 16:06 UTC, yair-ehrenwald commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +        model->version(), TFLITE_SCHEMA_VERSION);
Done

2020-09-09 16:06 UTC, yair-ehrenwald commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +    error_reporter->Report("AllocateTensors() failed");
Done

2020-09-09 16:06 UTC, yair-ehrenwald commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +    error_reporter->Report("Feature generation failed");
Done

2020-09-09 16:07 UTC, yair-ehrenwald commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +    error_reporter->Report("Invoke failed");
Done :)

2020-09-09 16:44 UTC, advaitjain commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +	   return;
this will need a clang-format.

```
clang-format -i -style=google main_functions.cc
```

2020-09-09 17:02 UTC, yair-ehrenwald commented on tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
> +	   return;
Done :)

2020-09-09 17:47 UTC, advaitjain approved these changes

2020-09-09 20:06 UTC, advaitjain approved these changes

2020-09-09 20:17 UTC, advaitjain approved these changes

2020-09-10 01:33 UTC, rthadur commented
@yair-ehrenwald can you please update the branch , seems to be branch out of date ?

2020-09-10 09:57 UTC, yair-ehrenwald commented
> @yair-ehrenwald can you please update the branch , seems to be branch out of date ?


Should be ok I think, @advaitjain merged and pushed to the branch? Let me know is there's something I should do.

2020-09-10 16:13 UTC, advaitjain commented
> > @yair-ehrenwald can you please update the branch , seems to be branch out of date ?
> 
> Should be ok I think, @advaitjain merged and pushed to the branch? Let me know is there's something I should do.

@yair-ehrenwald it looks like there are some conflicts since my last merge. If you could merge again then I'll approve and we can get this in.

2020-09-11 08:30 UTC, yair-ehrenwald commented
> @yair-ehrenwald it looks like there are some conflicts since my last merge. If you could merge again then I'll approve and we can get this in.

Done....

2020-09-11 16:50 UTC, advaitjain approved these changes

2020-09-11 18:12 UTC, merged