Ported TFLM Micro Speech example to CEVA-DSP SP500
tensorflow/tensorflow pull request #42469
Opened 2020-08-18 17:30 UTC by yair-ehrenwald

This is a port of the Micro Speech example to CEVA-DSP SP500 processor.

2020-09-11 18:18 UTC, gbaned commented
@yair-ehrenwald Can you please resolve conflicts? Thanks!

2020-09-13 09:06 UTC, yair-ehrenwald commented
> @yair-ehrenwald Can you please resolve conflicts? Thanks!

Done :)

2020-10-01 22:51 UTC, advaitjain requested changes

2020-10-01 22:51 UTC, advaitjain commented on tensorflow/lite/micro/examples/micro_speech/ceva/audio_provider.cc
> +	{
this seems to be counter to the formatting that we normally have.

Can you confirm that you're using -style=google with clang-format?

```
clang-format -i -style=google audio_provider.cc
```

2020-10-01 22:55 UTC, advaitjain requested changes
also, it might be worth investigating what in your workflow is making the files executables.

This pull request has made main_functions.cc and executable and when I looked, ceva/audio_provider.cc is also an executable on master.

2020-10-06 23:55 UTC, advaitjain commented on tensorflow/lite/micro/tools/make/targets/ceva_SP500_makefile.inc
> +
@yair-ehrenwald, any thoughts on the feasibility of this?

2020-10-07 19:08 UTC, yair-ehrenwald commented on tensorflow/lite/micro/tools/make/targets/ceva_SP500_makefile.inc
> +
@advaitjain I don't see a reason why not, I'll update tomorrow, thanks :)

2020-10-25 00:41 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-10-28 16:08 UTC, gbaned commented
@yair-ehrenwald  Any update on this PR? Please. Thanks!

2020-11-05 13:40 UTC, gbaned commented
@yair-ehrenwald Any update on this PR? Please. Thanks!

2020-12-06 00:46 UTC, closed without merging

2020-12-06 00:46 UTC, tensorflowbutler commented
It has been 29 days that this pull-request has stalled. Please create a new pull-request with the requested changes.