Fix a bug that the file copied by TF from HDFS to local may be wrong,…
tensorflow/tensorflow pull request #42599
Opened 2020-08-23 12:45 UTC by yuanbopeng

This is a PR from TaiJi AI platform in Tencent.

The file copied by TF from HDFS to local may be wrong, when HDFS file is being overwritten, may be a better way [#42597](https://github.com/tensorflow/tensorflow/issues/42597)

2020-08-24 10:09 UTC, gbaned commented
@yuanbopeng Thank you for your contribution. Can you please sign CLA? Thanks!

2020-08-24 10:44 UTC, yuanbopeng commented
@googlebot I signed it!

2020-08-24 16:31 UTC, mihaimaruseac requested changes
I don't like that we are removing a test. The test was added to prevent a bug regression

2020-08-25 04:51 UTC, yuanbopeng commented
> I don't like that we are removing a test. The test was added to prevent a bug regression
@mihaimaruseac 
Deleted the test case of data in the file append scene. Because I think that the latest data should not be obtained in READ through the new file handle. This method works well in the file append scenario, but it may cause the file to be wrong when the file is overwritten. Please refer to [the reply](https://github.com/tensorflow/tensorflow/issues/42597#issuecomment-679463880) for more

2020-09-04 02:05 UTC, yuanbopeng commented
This problem is fixed by [patch-3](https://github.com/tensorflow/tensorflow/pull/42860).

2020-09-04 02:06 UTC, closed without merging