[T.F 2.0 API Docs] Modifying python math_ops.py documentation
tensorflow/tensorflow pull request #42619
Opened 2020-08-24 10:29 UTC by Harsh188

PR for issue #25802.

Modifying the following existing functions:
-  `math.subtract`

Adding new functions:
- `math.acos`
- `math.add`
- `math.floor`

2020-08-24 13:53 UTC, hamelsmu submitted a review, later dismissed

2020-08-24 13:54 UTC, hamelsmu commented
Sorry about the random approval, that was a mistake on my part.  Please ignore

2020-08-24 16:22 UTC, mihaimaruseac requested changes
I would actually remove the `# ... tensors have shape ..` lines in the example as they can create confusion w.r.t. allowed input shapes.

2020-08-24 16:22 UTC, mihaimaruseac commented on tensorflow/python/ops/math_ops.py
> +  # `x` and `y` are tensors of shape (1)
```suggestion
  # `x` and `y` are tensors of shape `(5,)`
```

2020-08-24 16:22 UTC, mihaimaruseac commented on tensorflow/python/ops/math_ops.py
> +  # `x` and `y` are tensors of shape (1)
```suggestion
  # `x` and `y` are tensors of shape `(5,)`
```

2020-08-24 16:22 UTC, mihaimaruseac commented on tensorflow/python/ops/math_ops.py
> +  Both input and output have a range `(-inf, inf)`.
```suggestion
  Both input and output have a range `(-inf, inf)`.

  For example:
```

2020-08-24 16:22 UTC, mihaimaruseac commented on tensorflow/python/ops/math_ops.py
> +  Both input and output have a range `(-inf, inf)`.
```suggestion
  Both input and output have a range `(-inf, inf)`.

  For example:
```

2020-08-24 16:22 UTC, mihaimaruseac commented on tensorflow/python/ops/math_ops.py
> +  # `x` is a tensor of the shape(1)
```suggestion
  # `x` is a tensor of the shape `(6,)`
```

2020-08-26 10:18 UTC, Harsh188 commented
Just finished making all the requested changes. I took your advice and removed the `# ... tensors have shape ..` to avoid confusion.

2020-08-27 18:48 UTC, mihaimaruseac submitted a review, later dismissed

2020-08-27 19:02 UTC, rthadur commented
@Harsh188 can you please check ubuntu sanity build failures ?

2020-08-30 18:19 UTC, Harsh188 commented
I'm not too sure if fixing the pylint issues will fix the Ubuntu Sanity build failure. I went through the logs and saw that they were causing an error so that's what I ended up fixing. I'm still new contributing so, please forgive me for my small mistakes :)

2020-08-30 22:59 UTC, mihaimaruseac submitted a review, later dismissed

2020-08-31 17:35 UTC, mihaimaruseac submitted a review, later dismissed

2020-08-31 22:19 UTC, rthadur submitted a review, later dismissed

2020-09-11 02:42 UTC, Harsh188 commented
I still can't figure out why I'm getting these build failures and if they are fatal or if I should just ignore them. The build that's failing is `tensorflow/tools/ci_build/builds:gen_win_out` but I'm not sure how that relates to the files that I have made changes to. 

@rthadur can you help me sort this out?

2020-09-11 03:36 UTC, rthadur commented
I am not sure about the errors , @mihaimaruseac can you please help ?

2020-09-11 16:14 UTC, mihaimaruseac commented
Looks like an import failure. Let's try again and if this still does not work let's try rebasing back on master. If that still does not work, we might need to manually import

2020-09-11 17:42 UTC, Harsh188 commented
@mihaimaruseac I rebased to master.

2020-09-11 17:54 UTC, rthadur approved these changes, later dismissed

2020-09-20 18:27 UTC, Harsh188 commented
> Looks like an import failure. Let's try again and if this still does not work let's try rebasing back on master. If that still does not work, we might need to manually import

@mihaimaruseac how should I go about and manually import? It doesn't look like rebasing back on master has been effective.

2020-09-21 17:06 UTC, mihaimaruseac commented
I am going to import it manually, there are some steps that need to be done from inside Google. Sorry for the delay.

2020-09-21 21:06 UTC, mihaimaruseac approved these changes

2020-09-21 22:54 UTC, mihaimaruseac commented
Found the issue. You also needed to change `tensorflow/core/api_def/python_api/api_def_Add.pbtxt` and for the other ops you add the entire glue code in Python (see the example for `Sub`)

I did the changes manually on import, so no need to do anything here now. It is pending review now, though likely this would be Wednesday.

2020-09-22 11:07 UTC, Harsh188 commented
> Found the issue. You also needed to change `tensorflow/core/api_def/python_api/api_def_Add.pbtxt` and for the other ops you add the entire glue code in Python (see the example for `Sub`)
> 
> I did the changes manually on import, so no need to do anything here now. It is pending review now, though likely this would be Wednesday.

@mihaimaruseac awesome!

Regarding the changes in `tensorflow/core/api_def/python_api/api_def_Add.pbtxt` I'm assuming I have to remove the endpoints and add `visibility: HIDDEN`? That's what the other .pbtxt files seem to do but I'm not too sure.

Is glue code the [`@deprecation.deprecated`](https://github.com/tensorflow/tensorflow/blob/712fd5cfe4a5de420a4226c874664423eba4cb1a/tensorflow/python/ops/math_ops.py#L557) section in `sub`?

I'm new to contributing to open source and to the field in general, I apologize for the trouble.

2020-09-23 17:21 UTC, mihaimaruseac commented
Sorry again for the delayed response.

By glue code I meant the python function which has the docstring and just returns from `gen_*_ops`.

The dispatch decorator seems to be causing another test to fail, I'll try to debug by end of the week

2020-09-25 13:03 UTC, Harsh188 commented
> By glue code I meant the python function which has the docstring and just returns from `gen_*_ops`.
> 
> The dispatch decorator seems to be causing another test to fail, I'll try to debug by end of the week

Great, thank you! I could definitely learn quite a lot from you :)

2020-09-25 19:27 UTC, mihaimaruseac commented
Unfortunately, due to the way `add` is used in dispatch (something internal, not yet exported externally), I had to remove that from the PR, during manual import.

Once dispatch is fixed, we'll add back documentation for add.

2020-09-25 19:33 UTC, merged