fix the pylint hang issue while performing sanity checks
tensorflow/tensorflow pull request #42938
Opened 2020-09-03 22:01 UTC by kvignesh1420

This PR addresses the issue: https://github.com/tensorflow/tensorflow/issues/41600 by updating the pylint version for python3 while performing sanity checks. This resolves the issue where pylint hangs indefinitely during step 2 of the checklist in `tensorflow/tools/ci_build/ci_sanity.sh`

2020-09-03 22:28 UTC, angerson requested changes
Thanks for the fix. I added one small request.

FWIW we don't use this system internally any more; we use tensorflow/tools/ci_build/release/ubuntu_16/sanity/build.sh (mirrored in tensorflow/tools/ci_build/rel/ubuntu/sanity.sh).

2020-09-03 22:28 UTC, angerson commented on tensorflow/tools/ci_build/ci_sanity.sh
> +  ${PYLINT_BIN} --version
Small request: change [ to [[

2020-09-04 07:04 UTC, kvignesh1420 commented on tensorflow/tools/ci_build/ci_sanity.sh
> +  ${PYLINT_BIN} --version
addressed in the commit

2020-09-04 07:16 UTC, kvignesh1420 commented
@angerson since this instruction was present in the contributing docs to run the sanity checks using docker, I thought of fixing it. Just wondering if this should be changed or is it fine now that the fix is there. Let me know, thanks.

Ref: https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#running-sanity-check

2020-09-08 17:25 UTC, angerson commented
Ah, thank you for the pointer. This will definitely help until we get a chance to review those docs.

2020-09-08 17:25 UTC, angerson approved these changes

2020-09-09 04:07 UTC, merged