[hlo] Unbreak hlo-legalize-to-lhlo test
tensorflow/tensorflow pull request #43069
Opened 2020-09-09 10:02 UTC by dfki-ehna

The legalization of mlhlo.ReturnOp to lhlo.TerminatorOp by using BufferAssignmentReturnOpConverter fails since the Memref typed results (or the Memref typed operands of Return operation) are set to stay as results after legalization but lhlo.TerminatorOp doesn't accept any operands. Therefore, BufferAssignmentReturnOpConverter must be replaced with a manual conversion that removes all operands of mlhlo.ReturnOp and inserts copy operations in their places.

2020-09-09 11:08 UTC, pifon2a approved these changes, later dismissed

2020-09-09 14:24 UTC, sherhut commented
Please resolve conflicts with the recent LLVM integrate.

2020-09-09 16:01 UTC, sherhut requested changes
Please also fix the style. Sorry, I missed this the first time round.

2020-09-09 16:01 UTC, sherhut commented on tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/hlo_legalize_to_lhlo.cc
> +    Block& entryBlock = returnOp.getParentRegion()->front();
Google style (other than LLVM/MLIR) uses lower case like `entry_block`. Same for all other locals and function arguments.

2020-09-10 08:44 UTC, sherhut approved these changes
Thanks!

2020-09-10 11:16 UTC, merged