Fix for a deadlock in XlaDeviceContext
tensorflow/tensorflow pull request #43134
Opened 2020-09-11 07:10 UTC by ekuznetsov139

This supplies a default implementation of XlaDeviceContext::ThenExecute(). Without it, a host callback may fail to execute in some scenarios (because there's no one to execute it), causing a deadlock if anyone is waiting for that callback.

2020-09-11 20:52 UTC, sanjoy requested changes
I'd suggest updating the CL description a bit -- this implements a missing hook for XLA devices.  A deadlock is just one possible thing that goes wrong because of this missing hook.

CC @cheshire

2020-09-11 20:52 UTC, sanjoy commented on tensorflow/compiler/jit/xla_device_context.h
> +  virtual Status ThenExecute(Device* device, stream_executor::Stream* stream,
You don't also need a `virtual` here.

2020-09-16 16:02 UTC, gbaned commented
@ekuznetsov139  Can you please check @sanjoy's comments and keep us posted ? Thanks!

2020-09-16 17:03 UTC, sanjoy requested changes
Would it be too difficult to add a test case for this?

2020-09-16 19:06 UTC, cheshire commented
I don't mean to block this, but how did you even manage to use XLA devices? They are disabled now, and there shouldn't really be a reason for using them?..

2020-09-16 19:08 UTC, cheshire commented
Or is it deadlocking in `compiler/tests` and somehow only using ROCm?

2020-09-16 19:30 UTC, ekuznetsov139 commented
I am upstreaming a change that's been in the ROCm repo for a while. It was causing a deadlock in one of the unit tests. If it is irrelevant now, we can close this and I'll delete the corresponding code in the ROCm fork instead.

2020-09-16 20:48 UTC, cheshire commented
> If it is irrelevant now

Could you check whether it is relevant and whether the test is deadlocking now?

2020-09-16 21:54 UTC, ekuznetsov139 commented
I can confirm that the function is still being called during execution of some //tensorflow/compiler/... tests. It'll take some time to determine which (if any) tests deadlock as a result.

2020-09-16 21:59 UTC, cheshire commented
I'm personally fine with taking this change.

2020-09-17 00:18 UTC, ekuznetsov139 commented
Confirmed. The following tests time out on ROCm without this patch:
//tensorflow/compiler/tests:eager_test_gpu
//tensorflow/compiler/tests:while_test_gpu

2020-09-17 00:47 UTC, cheshire approved these changes

2020-09-18 12:21 UTC, merged