add suport for mips64 platform
tensorflow/tensorflow pull request #43231
Opened 2020-09-15 06:40 UTC by zhangqiang-hf

Since tensorflow is not supported on MIPS64 platform， use this patch，it can be build pass on MIPS64 platform。
and then， tensorflow can be supported on MIPS64 platform！

2020-09-15 16:15 UTC, gunan requested changes

2020-09-15 16:15 UTC, gunan commented on third_party/remote_config/remote_platform_configure.bzl
> +	cpu = "mips64"
please use spaces instead of tabs and match the above indentation.

2020-09-15 16:15 UTC, gunan commented on third_party/cpuinfo/BUILD.bazel
> +	":linux_mips64": COMMON_SRCS + LINUX_SRCS,
please use spaces instead of tabs and match the above indentation.

2020-09-18 07:28 UTC, zhangqiang-hf commented
dear sir，
 Can this patch be merged？

2020-09-18 15:36 UTC, gunan commented
@zhangqiang-hf please edit your change according to the comments, then we can start merging.

2020-09-21 06:12 UTC, closed without merging