Sagemaker resolver
tensorflow/tensorflow pull request #43251
Opened 2020-09-15 21:47 UTC by sboshin

This is a Cluster Resolver for AWS SageMaker. 

SageMaker currently only supports Homogeneous clusters, so this cluster resolver only resolves to all nodes in the cluster to be workers.

2020-09-16 05:05 UTC, frankchn requested changes
Thank you for your contribution! I've left a few comments, mostly about style.

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +# Copyright 2018 The TensorFlow Authors. All Rights Reserved.
nit: 2018 -> 2020

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +#List of envs: https://github.com/aws/sagemaker-training-toolkit/blob/master/ENVIRONMENT_VARIABLES.md
Add a space between # and start of comment. This may also exceed 80 character line limit, so URL might need to be on a separate line.

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +_SM_CURRENT_HOST = "SM_CURRENT_HOST"
Use quotes consistently, either " or ' throughout the file.

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +  #Create a tf_config from SM Variables
Space between `#` and `Create`

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +  hosts = sorted(json.loads(os.environ[_SM_HOSTS])) if os.environ[_SM_HOSTS] != '' else []
Exceeds 80 character per line limit.

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +  assert all([x in os.environ for x in [_SM_CURRENT_HOST, _SM_HOSTS]]),\
According to the Google Python style guide, no blackslash continuations here. Consider using implicit line joining inside parentheses instead.

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +  #Assign ports
Space between `#` and `Create`

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver.py
> +
extra line

2020-09-16 05:05 UTC, frankchn commented on tensorflow/python/distribute/cluster_resolver/sagemaker_cluster_resolver_test.py
> +# Copyright 2018 The TensorFlow Authors. All Rights Reserved.
2018 -> 2020

2020-09-16 16:44 UTC, sboshin commented
@frankchn Thank you for the quick response. I have added those changes.

2020-09-17 00:29 UTC, frankchn submitted a review, later dismissed

2020-09-17 00:30 UTC, frankchn commented
Thanks for the update! We will have to wait for some internal tests to pass before merging, but this should get in within the next few days.

2020-09-17 12:36 UTC, gbaned commented
@sboshin Can you please address Ubuntu Sanity errors? Thanks!

2020-09-17 16:53 UTC, frankchn approved these changes

2020-09-18 03:31 UTC, merged