[Intel MKL] Adding support for FusedBatchNorm op with native format
tensorflow/tensorflow pull request #43504
Opened 2020-09-23 20:59 UTC by mahmoud-abuzaina

2020-09-25 16:55 UTC, gbaned commented
@mahmoud-abuzaina  Can you please resolve conflicts? Thanks!

2020-09-29 06:45 UTC, mahmoud-abuzaina commented
@gbaned I have resolved the conflicts. Thanks!

2020-10-03 00:45 UTC, penpornk requested changes
Thank you for the PR and sorry for my delay! I have a few nits.

2020-10-03 04:22 UTC, penpornk requested changes
I have a few more comments that came up when I reviewed #43505.

2020-10-06 04:13 UTC, mahmoud-abuzaina commented on tensorflow/core/ops/mkl_nn_ops.cc
> +    })
yes, done.

2020-10-06 04:13 UTC, mahmoud-abuzaina commented on tensorflow/core/ops/mkl_nn_ops.cc
> +      return Status::OK();
Fixed.

2020-10-06 04:14 UTC, mahmoud-abuzaina commented on tensorflow/core/ops/mkl_nn_ops.cc
> +MKL version of FusedBatchNormGrad operator that does not depend
Done.

2020-10-06 04:14 UTC, mahmoud-abuzaina commented on tensorflow/core/ops/mkl_nn_ops.cc
> +batch normalization.
Done.

2020-10-06 04:14 UTC, mahmoud-abuzaina commented on tensorflow/core/ops/mkl_nn_ops.cc
> +MKL version of FusedBatchNormEx operator that does not depend on layout propagation.
Done.

2020-10-06 04:14 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_fused_batch_norm_op.cc
> +      if (IS_SRC_REORDER_NEEDED(src_md, bn_fwd_pd, bn_fwd) && !native_format) {
Done.

2020-10-06 04:14 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_fused_batch_norm_op.cc
> +          !native_format) {
Done.

2020-10-06 04:14 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_fused_batch_norm_op.cc
> +      if (IS_SRC_REORDER_NEEDED(src_md, bn_bwd_pd, bn_bwd) && !native_format) {
Done.

2020-10-06 04:15 UTC, mahmoud-abuzaina commented
Thank you for the suggestions. I have addressed your comments.

2020-10-07 21:08 UTC, penpornk approved these changes
Thank you for the changes!

2020-10-08 21:44 UTC, merged

2020-10-08 21:52 UTC, gzmkl commented
@penpornk thank you for the notification. I will work on the "cleanup" PR.