TFLu: Port TFL detection postprocess operator
tensorflow/tensorflow pull request #43566
Opened 2020-09-25 13:35 UTC by mansnils

This is fixing issue: https://github.com/tensorflow/tensorflow/issues/43565

It is also updating Flexbuffers in third party downloads because this PR is needed: https://github.com/google/flatbuffers/commit/dca12522a9f9e37f126ab925fd385c807ab4f84e

2020-10-01 12:28 UTC, mansnils commented on tensorflow/lite/micro/test_helpers.cc
> -  result.bytes = ElementCount(*dims) * sizeof(float);
You are right, it is not needed. Removing it.

2020-10-01 12:29 UTC, mansnils commented on tensorflow/lite/micro/tools/make/third_party_downloads.inc
> +FLATBUFFERS_URL := "https://github.com/google/flatbuffers/archive/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip"
I only tested it on Linux. So I am proposing to revert the change in this file and suppress the error in the operator with a comment about this.

2020-10-06 16:40 UTC, gbaned commented
@mansnils  Can you please resolve conflicts? Thanks!

2020-10-14 15:57 UTC, gbaned commented
@mansnils Any update on this PR? Please. Thanks!

2020-10-16 10:07 UTC, mansnils commented
Removing support for unknown output dimensions. Because it does not work with TFLiteEvalTensor API and it would require major changes in TFLu.
Most models seen with this operator have unknown output dimensions. So to run those they have to be modified first so that the out dimensions are known beforehand.

2020-10-27 17:24 UTC, njeffrie approved these changes

2020-11-05 19:02 UTC, advaitjain requested changes
apologies for the delayed review here. Mostly Google-style nits.

I have also triggered the CI build so you can see the CI failure log.

2020-11-09 15:16 UTC, mansnils commented on tensorflow/lite/micro/all_ops_resolver.cc
> +            tflite::ops::micro::custom::Register_DETECTION_POSTPROCESS());
All right

2020-11-09 15:16 UTC, mansnils commented on tensorflow/lite/micro/kernels/detection_postprocess_test/readme
> +#
ok

2020-11-10 19:41 UTC, advaitjain approved these changes

2020-11-10 22:57 UTC, rthadur commented
@mansnils can you please check sanity build failures ?

2020-11-11 00:58 UTC, advaitjain commented
A few of the CI failures:
 * the x86 build is failing for the TfLite Micro CI build. I think you need the arrays to be unsigned char instead of char.
 * the other two (MacOS CPU Python3 and Ubuntu Sanity) are related to the bazel build and BUILD file formatting.

I think you can recreate with:
```
bazel test tensorflow/lite/micro:micro_interpreter_test
```

And buildifier can be installed using instructions from [here](https://github.com/bazelbuild/buildtools/tree/master/buildifier).

I can help tomorrow if you have trouble reproducing these errors locally.

2020-11-11 00:59 UTC, advaitjain commented
> 
> ```
> bazel test tensorflow/lite/micro:micro_interpreter_test
> ```
> 

This one likely needs the arena size to be updated.

2020-11-11 10:35 UTC, mansnils commented
@advaitjain Thanks for the tip about: bazel test tensorflow/lite/micro:micro_interpreter_test. It turns out that it TestIncompleteInitializationAllocationsWithSmallArena that fails in this line:
   TF_LITE_MICRO_EXPECT_EQ(
      static_cast<size_t>(128),
       allocator->GetSimpleMemoryAllocator()->GetHeadUsedBytes()); And it turns out this is caused by the change of kMaxScratchBuffersPerOp  in micro_allocator.cc. It seems allocator->GetSimpleMemoryAllocator()->GetHeadUsedBytes() will change depending on kMaxScratchBuffersPerOp in this test.

2020-11-11 12:43 UTC, mansnils commented
I am pushing the fix for the micro_interpreter_test to see what tests it is fixing

2020-11-11 23:38 UTC, advaitjain commented
@mansnils, I have pushed a commit fixing some remaining issues with https://github.com/tensorflow/tensorflow/pull/43566/commits/5491648d7f710d445ffe873afbec0b9c7834be47.

This PR should be ready to go now.

2020-11-11 23:39 UTC, advaitjain approved these changes

2020-11-12 00:29 UTC, advaitjain commented
Unfortunately, the TFLM build is still failing. I think we're going to have to take a second look at the kernel runner and see how we can fix this.

I'll take a look tomorrow.

2020-11-12 13:08 UTC, mansnils commented
There is error: narrowing conversion of '-108' from 'int' to 'char' inside { } [-Wnarrowing] because of
const char g_gen_data_none_regular_nms[] = { .. -108
Normally that would be wrong but in this case it is actually intentional so I figure it is ok to use
#pragma GCC diagnostic ignored "-Wnarrowing"
in the generated code.

2020-11-12 13:11 UTC, mansnils commented
@advaitjain  To get consistent results between TFL and TFLM I am considering changing this in both kernels.
From:
    float ycenter = box_centersize.y / scale_values.y * anchor.h + anchor.y;
    float xcenter = box_centersize.x / scale_values.x * anchor.w + anchor.x;
    float half_h =
        0.5f * static_cast<float>(std::exp(box_centersize.h / scale_values.h)) *
        anchor.h;
    float half_w =
        0.5f * static_cast<float>(std::exp(box_centersize.w / scale_values.w)) *
 anchor.w;
To:
    float ycenter = static_cast<float>(
        static_cast<double>(box_centersize.y) /
        static_cast<double>(scale_values.y) *
        static_cast<double>(anchor.h) + static_cast<double>(anchor.y));

    float xcenter =  static_cast<float>(
        static_cast<double>(box_centersize.x) /
        static_cast<double>(scale_values.x) *
        static_cast<double>(anchor.w) + static_cast<double>(anchor.x));

    float half_h = static_cast<float>(
        0.5 * (std::exp(static_cast<double>(box_centersize.h) /
                        static_cast<double>(scale_values.h))) *
        static_cast<double>(anchor.h));
    float half_w =  static_cast<float>(
        0.5 * (std::exp(static_cast<double>(box_centersize.w) /
                        static_cast<double>(scale_values.w))) *
                        static_cast<double>(anchor.w));
Question: Would it it be ok to change this in the TFL kernel or could it break some test?

2020-11-12 13:49 UTC, mansnils commented
Sorry, forget the comment about: #pragma GCC diagnostic ignored "-Wnarrowing"

2020-11-12 14:56 UTC, mansnils commented
@advaitjain  To get rid of -Wnarrowing we should generate const int8_t* and cast back to const char* in detection_postprocess_test.cc. I was about to push this (after downloading your last commit) but have some problem:

error: failed to push some refs to 'git@github.com:mansnils/tensorflow.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

How do I pull your changes?

2020-11-12 19:57 UTC, advaitjain commented
> @advaitjain To get rid of -Wnarrowing we should generate const int8_t* and cast back to const char* in detection_postprocess_test.cc. I was about to push this (after downloading your last commit) but have some problem:
> 
> error: failed to push some refs to '[git@github.com](mailto:git@github.com):mansnils/tensorflow.git'
> hint: Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> 
> How do I pull your changes?

I think if you git pull that would do the trick. I had pushed to your remote branch so you local branch was a couple commits behind.

I have made the fix that you suggested with https://github.com/tensorflow/tensorflow/pull/43566/commits/aad242613d71dbc38bc7a8a0633e31fb192ebb85 so this issue is resolved.

2020-11-12 20:00 UTC, advaitjain commented
> @advaitjain To get consistent results between TFL and TFLM I am considering changing this in both kernels.
> From:
> 
> ```
> float ycenter = box_centersize.y / scale_values.y * anchor.h + anchor.y;
> float xcenter = box_centersize.x / scale_values.x * anchor.w + anchor.x;
> float half_h =
>     0.5f * static_cast<float>(std::exp(box_centersize.h / scale_values.h)) *
>     anchor.h;
> float half_w =
>     0.5f * static_cast<float>(std::exp(box_centersize.w / scale_values.w)) *  anchor.w;
> ```
> 
> To:
> 
> ```
> float ycenter = static_cast<float>(
>     static_cast<double>(box_centersize.y) /
>     static_cast<double>(scale_values.y) *
>     static_cast<double>(anchor.h) + static_cast<double>(anchor.y));
> float xcenter =  static_cast<float>(
>     static_cast<double>(box_centersize.x) /
>     static_cast<double>(scale_values.x) *
>     static_cast<double>(anchor.w) + static_cast<double>(anchor.x));
> float half_h = static_cast<float>(
>     0.5 * (std::exp(static_cast<double>(box_centersize.h) /
>                     static_cast<double>(scale_values.h))) *
>     static_cast<double>(anchor.h));
> float half_w =  static_cast<float>(
>     0.5 * (std::exp(static_cast<double>(box_centersize.w) /
>                     static_cast<double>(scale_values.w))) *
>                     static_cast<double>(anchor.w));
> ```
> 
> Question: Would it it be ok to change this in the TFL kernel or could it break some test?

Being explicit about float vs double math seems very reasonable to me. It would be nice if we could make this less verbose though. I'd be surprised if it breaks something.

Let's keep this change for a follow-on PR.

2020-11-12 20:12 UTC, advaitjain commented
Summarizing where we are with this PR for @mansnils @njeffrie and me:

 * the flex buffer generation and char vs unsinged char is resolved and all tests pass with both bazel and make (on x86)
 * build files etc are all formatted

We are still back to a different version of the original problem on bluepill:
```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=bluepill kernel_detection_postprocess_test
```

gives the following error:
```
`__lock___malloc_recursive_mutex' referenced in section `.text.__malloc_lock' of /home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-mlock.o): defined in discarded section `COMMON' of /home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-lock.o)
`__lock___malloc_recursive_mutex' referenced in section `.text.__malloc_unlock' of /home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-mlock.o): defined in discarded section `COMMON' of /home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-lock.o)
`errno' referenced in section `.text._sbrk_r' of /home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-sbrkr.o): defined in discarded section `COMMON' of /home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-reent.o)
/home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/lib/thumb/v7-m/libc.a(lib_a-sbrkr.o): In function `_sbrk_r':
sbrkr.c:(.text._sbrk_r+0xc): undefined reference to `_sbrk'
```

The error message is puzzling to me since it is saying something about being in the discarded section which makes me wonder why its an issue.

@mansnils: you should be able to `git pull` and have my changes appear on your local branch as well. If you can debug this _sbrk issue, that would be great.

2020-11-13 13:12 UTC, mansnils commented
It turns out the _sbrk issue is caused by the called to Flexbuffers AsFloat() in PPD. That call will reference  flatbuffers::StringToNumber(), which is the culprit. flatbuffers::StringToNumber() is not called directly so it can be removed with the unit test for PPD still passing. I am not sure how to resolve this issue in the best way. However I am proposing a temporary workaround to patch flexbuffers.h for Bluepill.

2020-11-14 01:09 UTC, advaitjain commented
Agreed that we should patch flatbuffers as a workaround for now.

I'd prefer having the patching be centralized instead of in the bluepill makefile.

I'm going to do this in two steps:
 1. https://github.com/tensorflow/tensorflow/pull/44860 pulls the flatbuffer downloads into its own script.
 2. I'll add a follow-on PR that does the patching. I have some prototyping commands here and will put them into a PR on Monday:
```bash
string_to_num_line=`awk '/StringToNumber/{ print NR; }' flexbuffers.h`
case_string_line=$((${string_to_num_line} - 2))

head -n ${case_string_line} flexbuffers.h > new_flexbuffers.h

echo "#if 1" >> new_flexbuffers.h
echo "          // Introduce a segfault for an unsupported code path for TFLM." >> new_flexbuffers.h
echo "          return *(static_cast<double*>(nullptr));" >> new_flexbuffers.h
echo "#else" >> new_flexbuffers.h
echo "          // This is the original code" >> new_flexbuffers.h
sed -n -e $((${string_to_num_line} -  1)),$((${string_to_num_line} + 1))p flexbuffers.h >> new_flexbuffers.h
echo "#endif" >> new_flexbuffers.h

total_num_lines=`wc -l flexbuffers.h | awk '{print $1}'`
sed -n -e $((${string_to_num_line} + 2)),${total_num_lines}p flexbuffers.h >> new_flexbuffers.h
```

2020-11-16 21:29 UTC, advaitjain commented on tensorflow/lite/micro/kernels/test_data_generation/generate_flexbuffers_data.cc
> +    }
I think we can skip this formatting code. Its easier to clang-format the output file.

2020-11-16 21:32 UTC, advaitjain commented
Created #44915 to patch flatbuffers to avoid pulling in strtod. Once that is merged, we should be able to revert 18ec320.

@mansnils, I'd suggest removing 18ec320 and then force-push.

2020-11-17 08:01 UTC, mansnils commented
@advaitjain Ok, will do. Will just correct the name of the readme file.

2020-11-18 00:48 UTC, advaitjain approved these changes

2020-11-18 12:54 UTC, gbaned commented
@mansnils  Can you please address Ubuntu Sanity errors? Thanks!

2020-11-18 14:58 UTC, mansnils commented
@gbaned Ubuntu Sanity error fixed

2020-11-18 17:31 UTC, advaitjain approved these changes

2020-11-19 06:29 UTC, advaitjain approved these changes

2020-11-19 06:30 UTC, advaitjain commented
Pushed a commit to fix internal errors. Let's see how the merging goes this time.

2020-11-19 10:12 UTC, mansnils commented
@advaitjain After pulling your changes, ci_sanity.sh no longer passed so I pushed https://github.com/tensorflow/tensorflow/pull/43566/commits/0bc6594e93d9f1326d1e359f274ab531b2da4730. At least now Ubunty Sanity passed but Windows and Mac builds still failed. Is it stability issues or what has changed?

2020-11-19 17:12 UTC, advaitjain approved these changes

2020-11-19 17:13 UTC, advaitjain commented
> @advaitjain After pulling your changes, ci_sanity.sh no longer passed so I pushed [0bc6594](https://github.com/tensorflow/tensorflow/commit/0bc6594e93d9f1326d1e359f274ab531b2da4730). At least now Ubunty Sanity passed but Windows and Mac builds still failed. Is it stability issues or what has changed?

Thanks Mans. The Win and Mac errors look like existing failures. Approved this PR and will see what the internal checks have to say.

2020-11-19 18:44 UTC, advaitjain commented
***(sigh)*** Internal checks failed but the external CI for Micro passed due to discrepancy between internal and external.

This PR makes the external CI closer to the internal checks: https://github.com/tensorflow/tensorflow/pull/45018

2020-11-24 12:55 UTC, mansnils commented
@advaitjain It seems the iOS error is an existing error, right?

2020-11-24 17:36 UTC, advaitjain approved these changes

2020-11-24 17:41 UTC, advaitjain commented
Thanks for the fix. Yes, the iOS error is existing and unrelated.

2020-11-24 21:43 UTC, advaitjain commented
Still having issues unfortunately :-/

The CI is failing with:
```
tensorflow/lite/micro/kernels/detection_postprocess.cc: In function ‘TfLiteStatus tflite::{anonymous}::Eval(TfLiteContext*, TfLiteNode*)’:
tensorflow/lite/micro/kernels/detection_postprocess.cc:591:58: error: potential null pointer dereference [-Werror=null-dereference]
   tflite::micro::GetTensorData<float>(num_detections)[0] =
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
       size_of_sorted_indices;
       ~~~~~~~~~~~~~~~~~~~~~~                              
tensorflow/lite/micro/kernels/detection_postprocess.cc:687:58: error: potential null pointer dereference [-Werror=null-dereference]
   tflite::micro::GetTensorData<float>(num_detections)[0] = output_box_index;
```

but it is not reproducible locally.

My current guess is that the gcc version used as part of CI is old (gcc-6.3.0). I have a change under review that updates https://github.com/tensorflow/tensorflow/blob/3d3c4aaaedaf117b3b8cc9c30a594889094db6f1/tensorflow/tools/ci_build/Dockerfile.micro#L4

to
```
python:3.9.0-buster
```

which should mean that we use gcc 8.3.0 as part of CI. Let's see what happens when that change get merged.

2020-11-26 14:19 UTC, mansnils commented
@advaitjain It seems like the updated docker didn't help, or do we need to rebase?

2020-12-01 00:12 UTC, advaitjain commented
> Still having issues unfortunately :-/
> 
> The CI is failing with:
> 
> ```
> tensorflow/lite/micro/kernels/detection_postprocess.cc: In function ‘TfLiteStatus tflite::{anonymous}::Eval(TfLiteContext*, TfLiteNode*)’:
> tensorflow/lite/micro/kernels/detection_postprocess.cc:591:58: error: potential null pointer dereference [-Werror=null-dereference]
>    tflite::micro::GetTensorData<float>(num_detections)[0] =
>    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
>        size_of_sorted_indices;
>        ~~~~~~~~~~~~~~~~~~~~~~                              
> tensorflow/lite/micro/kernels/detection_postprocess.cc:687:58: error: potential null pointer dereference [-Werror=null-dereference]
>    tflite::micro::GetTensorData<float>(num_detections)[0] = output_box_index;
> ```
> 
> but it is not reproducible locally.
> 
> My current guess is that the gcc version used as part of CI is old (gcc-6.3.0). I have a change under review that updates
> 
> https://github.com/tensorflow/tensorflow/blob/3d3c4aaaedaf117b3b8cc9c30a594889094db6f1/tensorflow/tools/ci_build/Dockerfile.micro#L4
> 
> to
> 
> ```
> python:3.9.0-buster
> ```
> 
> which should mean that we use gcc 8.3.0 as part of CI. Let's see what happens when that change get merged.


I wasn't able to reproduce locally because I hadn't done a `make clean_downloads`.

Created https://github.com/tensorflow/tensorflow/pull/45286 to address this issue. [This comment](https://github.com/tensorflow/tensorflow/issues/44971#issuecomment-736130061) has some additional context.

2020-12-02 21:15 UTC, advaitjain approved these changes

2020-12-03 02:04 UTC, merged