[tf.data server] prevent restart of the dispatcher server w/o fault-tolerance, in the test bed
tensorflow/tensorflow pull request #43714
Opened 2020-10-01 23:47 UTC by kvignesh1420

This PR is a follow up of https://github.com/tensorflow/tensorflow/pull/43691 and prevents a restart of the dispatcher if it has been configured without fault-tolerance. Failing to do so will lead to a perpetual stream of `warn` messages on a dispatcher restart and unnecessarily extend the testing time without an immediate exit.

@aaudiber until the enhancements are implemented to handle such scenarios (as per our discussion), this will help us in handling the upcoming test cases.

2020-10-02 00:15 UTC, aaudiber requested changes
Thanks @kvignesh1420

2020-10-02 00:15 UTC, aaudiber commented on tensorflow/python/data/experimental/kernel_tests/data_service_test_base.py
> +    When the dispatcher is restarted with `fault-tolerant_mode=False`,
This scenario is too specific, can we make the docstring more general, e.g. "Restarting is only supported when the dispatcher is configured with `fault_tolerant_mode=True`"?

2020-10-02 13:08 UTC, kvignesh1420 commented
Made the change, @aaudiber.

2020-10-02 16:36 UTC, aaudiber approved these changes

2020-10-05 17:14 UTC, merged

2020-10-31 09:34 UTC, kvignesh1420 commented
@aaudiber, I had a quick question regarding the updates to the workers based on the task list.
Reference: https://github.com/tensorflow/tensorflow/blob/377434ff41473a33f7bedd1c08199d5af1fd33e9/tensorflow/core/kernels/data/experimental/data_service_dataset_op.cc#L326

How would we identify whether the task list changed or not if we don't poll for changes?
Please let me know.