[T.F 2.0 API Docs] Adds usage example for log_sigmoid
tensorflow/tensorflow pull request #43758
Opened 2020-10-03 16:32 UTC by RonLek

PR for issue #25802

Adds usage example for `math.log_sigmoid`

2020-10-04 09:02 UTC, Harsh188 requested changes

2020-10-04 18:33 UTC, RonLek commented
Thanks for reviewing @Harsh188. Made the changes.

2020-10-05 02:42 UTC, Harsh188 submitted a review, later dismissed

2020-10-05 10:15 UTC, Harsh188 approved these changes

2020-10-05 16:54 UTC, mihaimaruseac approved these changes

2020-10-06 13:43 UTC, merged