Fixed inputs not being cast to tuple
tensorflow/tensorflow pull request #43774
Opened 2020-10-04 16:16 UTC by juulie

Fix for #43773 

RNN's __call__  when deserialized from H5 and reconstructed from config will have the layers multiple inputs contained within a list instead of a tuple. This is due to the JSON decoder always creating lists when deserializing array. This change makes sure that its always typecast back to a tuple.

2020-10-04 16:20 UTC, juulie commented
This serializing-deserializing to JSON might also be an issue for other layers, so a better fix might be writing a custom JSONEncoder that has custom logic for handling tuples

2020-10-09 02:57 UTC, Dynmi approved these changes

2020-10-15 21:18 UTC, qlzh727 requested changes
Very sorry for the late reply. Could u update the unit test to demonstrate what has been fixed by this change? Thanks.

2020-10-23 18:22 UTC, gbaned commented
@juulie Can you please check @qlzh727's comments and keep us posted ? Thanks!

2020-11-05 14:35 UTC, gbaned commented
@juulie Any update on this PR? Please. Thanks!

2020-11-20 04:53 UTC, qlzh727 approved these changes
Ah, very sorry for the late reply. I took a closer look for the attached issue. Thanks for the PR.

2020-11-28 04:25 UTC, qlzh727 commented
Hum, it seems that the unit tests are failing for this change. Can u please take a look?

https://source.cloud.google.com/results/invocations/7edd6a34-af6c-4067-91ba-e9b521f8e3f4/targets

2020-12-03 10:46 UTC, gbaned commented
@juulie  Can you please check @qlzh727's comments and keep us posted ? Thanks!

2020-12-14 15:27 UTC, gbaned commented
@juulie  Any update on this PR? Please. Thanks!

2020-12-20 22:05 UTC, juulie commented
Sorry ive been working on other things and havent had the chance to look into the unit tests, ill get back to it later this month

2021-01-08 01:10 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-01-13 14:39 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-01-13 14:40 UTC, closed without merging