added einsum op and allow more broadcasting dims
tensorflow/tensorflow pull request #4378
Opened 2016-09-14 08:08 UTC by nikhilmishra000

This was meant to solve: https://github.com/tensorflow/tensorflow/issues/175
And I think it addresses this too: https://github.com/tensorflow/tensorflow/issues/1519

2016-09-16 22:10 UTC, andrewharp commented
@tensorflow-jenkins Test this please.

2016-09-17 21:34 UTC, nikhilmishra000 commented
I'm not too sure why `//tensorflow/contrib/learn:graph_io_test` is failing on python 3 only. Is there a log file from that specific test that I could take a look at? I can't seem to reproduce the failure locally...

2016-09-17 22:04 UTC, andrewharp commented
The //tensorflow/contrib/learn:graph_io_test failure is most likely unrelated. It's already failing on the nightly builds for Mac python3.

2016-09-19 21:43 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops.py
> +  r"""
You don't have escapes in this string, so remove the r.

2016-09-19 21:52 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops_test.py
> +class EinsumTestGpu(EinsumTest):
You should remove this class, and always enable processing on the GPU. We run the tests on CPU only and GPU machines. The other tests using the same pattern are vestigial.

2016-09-19 22:03 UTC, martinwicke requested changes
LGTM. Small changes. Sorry about the GPU confusion, we're in the process of changing how we do GPU tests, hence those leftover things. @gunan FYI.

2016-09-19 23:50 UTC, nikhilmishra000 commented
@martinwicke done

2016-09-20 15:53 UTC, martinwicke approved these changes

2016-09-20 15:53 UTC, martinwicke commented
Thanks! Jenkins, test this please.

2016-09-20 17:16 UTC, nikhilmishra000 commented
only failure is `//tensorflow/contrib/learn:graph_io_test`, which we said was unrelated

2016-09-20 17:23 UTC, martinwicke commented
Hooray.

2016-09-20 17:23 UTC, merged

2016-09-20 20:21 UTC, pannous commented
Fantastic! 
Any reasons against an alias 'contraction' ?

2016-09-20 20:59 UTC, nikhilmishra000 commented
nope, I had named it `einsum` because of similarity to `numpy.einsum`