Use enueration for policy items
tensorflow/tensorflow pull request #43836
Opened 2020-10-07 06:22 UTC by porridge

2020-10-07 12:47 UTC, sulenn approved these changes

2020-10-07 12:50 UTC, sulenn approved these changes

2020-11-05 18:42 UTC, mihaimaruseac requested changes

2020-11-05 18:42 UTC, mihaimaruseac commented on ISSUES.md
> +1. It must be a bug/performance issue or a feature request or a build issue or a documentation issue (for small doc fixes please send a PR instead).
```suggestion
If you open a GitHub Issue, here is our policy:

1. It must be a bug/performance issue or a feature request or a build issue or a documentation issue (for small doc fixes please send a PR instead).
```

2020-11-10 17:53 UTC, mihaimaruseac approved these changes

2020-11-10 18:12 UTC, mihaimaruseac commented
@porridge it seems you have changed your email address on GitHub/commits? CLA bot says you have to sign CLA again.

2020-11-23 11:44 UTC, gbaned commented
@porridge  Any update on this PR? Please. Thanks!

2020-11-23 15:14 UTC, porridge commented
@googlebot I signed it!

2020-11-23 15:16 UTC, MarkDaoust approved these changes

2020-11-23 18:11 UTC, merged