update and fix problem in API doc.
tensorflow/tensorflow pull request #4404
Opened 2016-09-15 23:16 UTC by perhapszzy

The parameters in bounding box should be [y_min, x_min, y_max, x_max]

2016-09-15 23:19 UTC, vrv commented on tensorflow/g3doc/api_docs/python/functions_and_classes/shard8/tf.image.draw_bounding_boxes.md
> -`[0.1, 0.5, 0.2, 0.9]`, the bottom-left and upper-right coordinates of the
You should update the original code in image_ops.py, the .md files are autogenerated.

2016-09-15 23:19 UTC, vrv requested changes

2016-09-15 23:32 UTC, perhapszzy commented on tensorflow/g3doc/api_docs/python/functions_and_classes/shard8/tf.image.draw_bounding_boxes.md
> -`[0.1, 0.5, 0.2, 0.9]`, the bottom-left and upper-right coordinates of the
changed this at image_ops.cc.

2016-09-15 23:36 UTC, vrv approved these changes

2016-09-15 23:36 UTC, vrv commented
@tensorflow-jenkins test this please

2016-09-19 22:20 UTC, martinwicke commented
Last test failure was infrastructure. Overriding.

2016-09-19 22:20 UTC, merged