[INTEL MKL] Removing MKL blob for Window.
tensorflow/tensorflow pull request #44149
Opened 2020-10-19 17:47 UTC by agramesh1

This updates https://github.com/tensorflow/tensorflow/pull/43586 with changes for windows. This PR
1) Removes MKL blob completely
2) Enables Windows build to use llvm_openmp and fixes some openMP build issues.
3) Replaces /w with /W0 for windows build in .bazelrc.  as they are equivalent for MSVC. When /w is passed on to the assembler ml64.exe,it is interpreted differently (treats warnings as errors).

2020-10-19 21:18 UTC, penpornk requested changes
Thank you for the PR! I have some minor comments.

2020-10-19 21:18 UTC, penpornk commented on third_party/mkl/BUILD
> +    srcs = ["MKL_LICENSE"] + ["@llvm_openmp//:LICENSE.txt"],
Nit: This can be in the same list
```suggestion
    srcs = [
        "MKL_LICENSE",
        "@llvm_openmp//:LICENSE.txt",
    ],
```

2020-10-19 21:27 UTC, agramesh1 commented on tensorflow/core/common_runtime/mkl_cpu_allocator.cc
> -#endif
It is related to the binary blob and is no longer needed.

2020-10-19 21:48 UTC, penpornk commented on tensorflow/core/kernels/mkl/mkl_quantized_conv_ops.h
> +  for (ssize_t n = 0; n < n_channel; ++n) {
Actually, just `int64` would work too.

2020-10-19 21:48 UTC, penpornk commented on tensorflow/core/common_runtime/mkl_cpu_allocator.cc
> -#endif
Thank you for the clarification!

2020-10-20 00:29 UTC, agramesh1 commented
Hi @penpornk, I made the requested. Please review again. Thanks.

2020-10-20 00:30 UTC, penpornk approved these changes
Thank you for the changes!

2020-10-20 19:17 UTC, agramesh1 commented
Hi @penpornk It looks like there was a failure in the internal testing. Please let me know if the PR needs changes.

2020-10-20 19:25 UTC, penpornk commented
@agramesh1 I'm fixing it internally. It should be fine. Thank you for bringing this up! :)

2020-10-21 06:06 UTC, merged