Add idempotent based folding to TF
tensorflow/tensorflow pull request #44466
Opened 2020-10-30 19:31 UTC by ahmedsabie

This trait label will allow idempotent optimizations (i.e. multiples copies of op folded to one copy) to run automatically from the MLIR side

2020-10-30 19:31 UTC, ahmedsabie commented
@andyly  @smit-hinsu

2020-10-30 19:36 UTC, andyly approved these changes

2020-10-31 04:28 UTC, andyly approved these changes

2020-11-03 16:45 UTC, andyly requested changes

2020-11-03 16:45 UTC, andyly commented on tensorflow/compiler/mlir/tensorflow/tests/tf_trait_folds.mlir
> +// CHECK-SAME:  ([[ARG0:%.+]]: tensor<f1>)
`f1` is not a defined type (and is failing this test). Did you mean to use `f32`?

2020-11-05 15:37 UTC, gbaned commented
@ahmedsabie Can you please check @andyly's comments and keep us posted ? Thanks!

2020-11-22 00:56 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2020-11-25 11:31 UTC, gbaned commented
@ahmedsabie Any update on this PR? Please. Thanks!

2020-11-25 20:12 UTC, closed without merging