Add an additional arg to tf.experimental.register_filesystem_plugin to take plugin function name
tensorflow/tensorflow pull request #44507
Opened 2020-11-01 22:24 UTC by yongtang

This PR proposes to add an additional arg `plugin_function` to
tf.experimental.register_filesystem_plugin so that it is possible to load
a file system plugin with a different function name, i.e., a name other than
default `TF_InitPlugin` (e.g., `TF_InitPlugin_AzureFileSystem`, `TF_InitPlugin_HTTPFileSystem`, etc).

There are several reasons for a need to have the flexibility of using a different function name.
But the biggest reason is that, by allowing passing function name as the parameter, it is possible
to bundle several file systems into one shared object library and reduce the total size of the
package (e.g., one `.so` file with multiple file system support for Azure FS, HTTP FS, etc).

Since thie PR will only add an optional args, users may still pass the `library_pathname`
only (and `TF_InitPlugin` function name will automatically be used).

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2020-11-02 17:54 UTC, mihaimaruseac requested changes

2020-11-02 17:54 UTC, mihaimaruseac commented on tensorflow/c/c_api.h
> +    const char* plugin_filename, const char* plugin_function, TF_Status* status);
Let's add `plugin_function` to the docstring. Default could be `nullptr` or `""`, we should handle both and document that in these cases we use `TF_InitPlugin`.

2020-11-02 17:54 UTC, mihaimaruseac commented on tensorflow/python/framework/load_library.py
> +    py_tf.TF_RegisterFilesystemPlugin(plugin_location, plugin_function)
We should an if to convert `plugin_function=None` to the default `TF_InitPlugin`.

2020-11-02 17:56 UTC, mihaimaruseac commented
Note though that you can load all filesystems in a single `TF_InitPlugin`, you don't need separate functions.

This will increase cognitive load on users, now they'll need to know which plugin function to call to register a filesystem instead of knowing that they just need to call the load python call and get all filesystems from the dso loaded.

2020-11-02 18:10 UTC, yongtang commented
> Note though that you can load all filesystems in a single `TF_InitPlugin`, you don't need separate functions.

Thanks @mihaimaruseac for the pointers. I didn't know that before. Let me take a look and see if it works. If works I think this PR might potentially be closed.

2020-11-02 18:57 UTC, mihaimaruseac commented
You control how many schemes are registered in a DSO: https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/experimental/filesystem/plugins/posix/posix_filesystem.cc;l=454-458;drc=f64e839687b6129dfe2a9e21ef965593c7f3a3c2

For each scheme you can then provide different operations. In the example they are the same, but there's no reason why some might change.

2020-11-03 16:09 UTC, yongtang commented
Thanks @mihaimaruseac for the help. I will close this PR.

2020-11-03 16:09 UTC, closed without merging