Fix farmhash, jpeg, png build on Windows
tensorflow/tensorflow pull request #4460
Opened 2016-09-19 13:32 UTC by meteorcloudy

I tried to add windows `config_setting` in `tensorflow/BUILD`, but it's not accessible from external library, so I had to add into every relevant BUILD file. @mrry @damienmg @dslomov

2016-09-21 01:55 UTC, mrry commented on farmhash.BUILD
> +    copts = ["/DFARMHASH_OPTIONAL_BUILTIN_EXPECT"],
Should this copt be Windows-only? (I'd have guessed that gcc would balk at a flag like this....)

2016-09-21 01:56 UTC, mrry commented on png.BUILD
>      linkopts = ["-lz"],
Should `linkopts = ["-lz"]` be gcc-only?

2016-09-21 08:11 UTC, meteorcloudy commented on png.BUILD
>      linkopts = ["-lz"],
Since we already depend on `@zlib_archive//:zlib`, how about just remove this flag?

2016-09-21 08:11 UTC, meteorcloudy commented on farmhash.BUILD
> +    copts = ["/DFARMHASH_OPTIONAL_BUILTIN_EXPECT"],
That's right! Thanks!e

2016-09-21 20:51 UTC, mrry commented on png.BUILD
>      linkopts = ["-lz"],
SGTM.

2016-09-21 20:52 UTC, mrry requested changes
Just remove the link flag, on `"png"` and we should be good to merge this.

2016-09-21 20:56 UTC, meteorcloudy commented
I've already removed it in the last commit. 😁

2016-09-21 21:24 UTC, mrry approved these changes

2016-09-21 21:24 UTC, mrry commented
@meteorcloudy Thanks! Didn't see it in the review view :).

2016-09-21 21:24 UTC, mrry commented
@tensorflow-jenkins test this please.

2016-09-23 08:39 UTC, meteorcloudy commented
Can we test this again please?

2016-09-23 15:43 UTC, mrry commented
@tensorflow-jenkins test this please.

2016-09-27 16:44 UTC, jhseu commented
Mind resolving the new conflicts? That flaky test should be fixed now.

2016-09-27 18:12 UTC, meteorcloudy commented
Conflicts resolved!  jpeg, png are already buildable after rebase, only need to fix farmhash. Please test again!

2016-09-27 18:25 UTC, jhseu commented
Jenkins, test this please

2016-09-27 20:30 UTC, jhseu commented
Can you merge the latest master into your pull request? We have commits there that fix the jenkins test.

2016-09-27 20:32 UTC, jhseu commented
Hmm, nevermind, weird, your change is already up-to-date. Let's try this again:

Jenkins, test this please

2016-09-28 02:10 UTC, merged