Updated optimized ARC fully_connected kernel to use the new TfLiteEvalTensor API.
tensorflow/tensorflow pull request #44619
Opened 2020-11-05 14:54 UTC by gerbauz

This pull request is part of porting ARC optimized kernels to the new TfLiteEvalTensor API.
This one is related to fully connected kernel.

PR number: [3/5]

Fixes #43910

2020-11-05 21:28 UTC, advaitjain requested changes
minor nit

2020-11-05 21:28 UTC, advaitjain commented on tensorflow/lite/micro/kernels/arc_mli/fully_connected.cc
> +        context->AllocatePersistentBuffer(context, sizeof(mli_tensor)));
static_cast

2020-11-09 09:48 UTC, gerbauz commented on tensorflow/lite/micro/kernels/arc_mli/fully_connected.cc
> +        context->AllocatePersistentBuffer(context, sizeof(mli_tensor)));
Fixed and committed.

2020-11-12 00:00 UTC, advaitjain approved these changes

2020-11-13 23:12 UTC, rthadur approved these changes

2020-11-13 23:46 UTC, merged