Fix slim record_writer compression type
tensorflow/tensorflow pull request #44786
Opened 2020-11-11 23:58 UTC by mkuchnik

The current code does not compile if the corresponding ifdef branch corresponding to SLIM is used.

2020-12-12 17:51 UTC, rohan100jain requested changes

2020-12-12 17:51 UTC, rohan100jain commented on tensorflow/core/lib/io/record_writer.cc
> +  if (options.compression_type != RecordWriterOptions::NONE) {
Thanks for catching this! But I believe this should be 

options.compression_type != compression::kNone

2020-12-14 09:11 UTC, gbaned commented
@mkuchnik  Can you please check @rohan100jain's comments and keep us posted ? Thanks!

2020-12-14 18:46 UTC, mkuchnik reviewed
@rohan100jain @gbaned I believe my PR is correct. I explain my reasoning above (e.g., the types do not match for suggested change). 
I further demonstrate this experimentally, I try the following snippet for the RecordWriter function, using the original line, my line, and @rohan100jain's suggestion. Code starts at line 60.

```C++
RecordWriter::RecordWriter(WritableFile* dest,                                                                                                                                                              
                           const RecordWriterOptions& options)                                                                                                                                              
    : dest_(dest), options_(options) {
  // 1. Pre-PR                                                                                                                                                                      
  if (compression_type != compression::kNone) {                                                                                                                                                             
  // 2. My PR
  // if (options.compression_type != RecordWriterOptions::NONE) {                                                                                                                                           
  // 3. Suggested Change
  // if (options.compression_type != compression::kNone) {                                                                                                                                                   
    LOG(FATAL) << "Compression is unsupported on mobile platforms.";                                                                                                                                        
  }                                                                                                                                                                                                         
}
```

Case 1 (original code):
```bash
tensorflow/core/lib/io/record_writer.cc: In constructor 'tensorflow::io::RecordWriter::RecordWriter(tensorflow::WritableFile*, const tensorflow::io::RecordWriterOptions&)':
tensorflow/core/lib/io/record_writer.cc:64:7: error: 'compression_type' was not declared in this scope
   if (compression_type != compression::kNone) {
       ^~~~~~~~~~~~~~~~
tensorflow/core/lib/io/record_writer.cc:64:7: note: suggested alternative: 'compressBound'
   if (compression_type != compression::kNone) {
       ^~~~~~~~~~~~~~~~
       compressBound
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

Case 2 (Original PR):
Build completes.

Case 3 (Suggested Change):
```bash
tensorflow/core/lib/io/record_writer.cc: In constructor 'tensorflow::io::RecordWriter::RecordWriter(tensorflow::WritableFile*, const tensorflow::io::RecordWriterOptions&)':
tensorflow/core/lib/io/record_writer.cc:68:32: error: no match for 'operator!=' (operand types are 'const tensorflow::io::RecordWriterOptions::CompressionType' and 'const char []')
   if (options.compression_type != compression::kNone) {
       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

As you can see, the types do not match. I suggest using the original PR.

2020-12-18 13:38 UTC, rohan100jain approved these changes

2020-12-21 14:40 UTC, merged