Serializing EagerTensors in model.save()
tensorflow/tensorflow pull request #45182
Opened 2020-11-25 11:45 UTC by stratomaster31

* This commit fixes problems when saving tf.keras.models coming from tensorflow 1.x
* If there are any EagerTensors in the graph, they are converted to numpy objects that can be serialized
* This fix has been tested and it works

2020-11-25 21:11 UTC, bhack requested changes
It requires a test.

2020-11-25 21:11 UTC, bhack commented on tensorflow/python/util/serialization.py
> +import tensorflow as tf
Please use `from tensorflow.python` like the other imports

2020-11-25 21:11 UTC, bhack commented on tensorflow/python/util/serialization.py
> +  if isinstance(obj, tf.python.framework.ops.EagerTensor):
You need to create a new test for this feature at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/tests/serialization_util_test.py

2021-01-05 18:10 UTC, mihaimaruseac requested changes
Please add test and follow review suggestions from @bhack.

2021-01-15 17:38 UTC, gbaned commented
@stratomaster31  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

2021-01-27 17:42 UTC, gbaned commented
@stratomaster31 Any update on this PR? Please. Thanks!

2021-02-22 00:37 UTC, tensorflowbutler commented
It has been 24 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-03-01 14:33 UTC, gbaned commented
@stratomaster31 Any update on this PR? Please. Thanks!

2021-03-17 19:05 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-03-17 19:05 UTC, closed without merging