Added colocate gradients argument to optimize_loss
tensorflow/tensorflow pull request #4522
Opened 2016-09-21 20:33 UTC by alexgkendall

This PR adds a colocate gradients argument to optimize_loss which is useful for multi GPU training where the model is split across multiple GPUs.

2016-09-21 20:36 UTC, alexgkendall commented
I signed it!

2016-09-22 04:02 UTC, martinwicke commented
Jenkins, test this please.

2016-09-22 04:04 UTC, martinwicke approved these changes

2016-09-22 04:05 UTC, vrv commented on tensorflow/contrib/layers/python/layers/optimizers.py
> +                  colocate_gradients=False):
maybe add documentation? also maybe name colocate_gradients_with_ops to match?

2016-09-22 04:09 UTC, martinwicke commented on tensorflow/contrib/layers/python/layers/optimizers.py
> +                  colocate_gradients=False):
Yes please. <shame, ding ding>

2016-09-22 04:09 UTC, martinwicke requested changes

2016-09-22 15:51 UTC, alexgkendall commented on tensorflow/contrib/layers/python/layers/optimizers.py
> +                  colocate_gradients=False):
Done.

2016-09-23 06:11 UTC, martinwicke approved these changes

2016-09-23 06:11 UTC, martinwicke commented
Jenkins, test this please.

2016-09-26 21:19 UTC, alexgkendall commented
@martinwicke do you know what is causing these tests to fail?

2016-09-26 22:28 UTC, martinwicke commented
The Linux/Py3 failure is unrelated. 

The Mac failure was a network problem, and should be just a flake. I re-ran it, with results eventually showing up at 
http://ci.tensorflow.org/job/tensorflow-pull-requests-mac/2023

Once that's clean we can merge. @jhseu, can you merge this if the above test comes back clean?

2016-09-26 22:32 UTC, jhseu commented
Yeah. The mac flakes are fixed internally, so I'll merge this and rerun the tests once I push the internal changes.

2016-09-27 04:28 UTC, merged