Update seq2seq tutorial
tensorflow/tensorflow pull request #4532
Opened 2016-09-22 11:26 UTC by amlankar

The seq2seq tutorial still refers to models/rnn/seq2seq.py, but it has been moved to tf.nn.seq2seq (python/ops/seq2seq.py) on master

2016-09-22 11:30 UTC, amlankar commented
I signed it!  
![](https://link.nylas.com/open/6w3qif55jsjyrccir1uuco8cz/local-8f07260e-a008?
r=cmVwbHkrMDA3NDc5M2NiMWQzNDRiZmFkM2U1MTA0MDI0ODQzNmVlMjMwYWVjNTE1MjVkZmYxOTJj
ZjAwMDAwMDAxMTNmYjgyNmU5MmExNjljZTBhYTRmYjFkQHJlcGx5LmdpdGh1Yi5jb20=)

  
On Sep 22 2016, at 4:58 pm, googlebot <notifications@github.com> wrote:  

> Thanks for your pull request. It looks like this may be your first
contribution to a Google open source project. Before we can look at your pull
request, you'll need to sign a Contributor License Agreement (CLA).

>

> 📝 **Please visit [https://cla.developers.google.com/](https://cla.developers
.google.com/&r=cmVwbHkrMDA3NDc5M2NiMWQzNDRiZmFkM2U1MTA0MDI0ODQzNmVlMjMwYWVjNTE
1MjVkZmYxOTJjZjAwMDAwMDAxMTNmYjgyNmU5MmExNjljZTBhYTRmYjFkQHJlcGx5LmdpdGh1Yi5jb
20=) to sign.**

>

> Once you've signed, please reply here (e.g. `I signed it!`) and we'll
verify. Thanks.

>

> * * *

>

>   * If you've already signed a CLA, it's possible we don't have your GitHub
username or you're using a different email address. Check [your existing CLA d
ata](https://cla.developers.google.com/clas&r=cmVwbHkrMDA3NDc5M2NiMWQzNDRiZmFk
M2U1MTA0MDI0ODQzNmVlMjMwYWVjNTE1MjVkZmYxOTJjZjAwMDAwMDAxMTNmYjgyNmU5MmExNjljZT
BhYTRmYjFkQHJlcGx5LmdpdGh1Yi5jb20=) and verify that your [email is set on your
git commits](https://help.github.com/articles/setting-your-email-in-git/&r=cmV
wbHkrMDA3NDc5M2NiMWQzNDRiZmFkM2U1MTA0MDI0ODQzNmVlMjMwYWVjNTE1MjVkZmYxOTJjZjAwM
DAwMDAxMTNmYjgyNmU5MmExNjljZTBhYTRmYjFkQHJlcGx5LmdpdGh1Yi5jb20=).

>   * If you signed the CLA as a corporation, please let us know the company's
name.

>

> --  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on GitHub](https://github.com/tensorflo
w/tensorflow/pull/4532#issuecomment-248876591&r=cmVwbHkrMDA3NDc5M2NiMWQzNDRiZm
FkM2U1MTA0MDI0ODQzNmVlMjMwYWVjNTE1MjVkZmYxOTJjZjAwMDAwMDAxMTNmYjgyNmU5MmExNjlj
ZTBhYTRmYjFkQHJlcGx5LmdpdGh1Yi5jb20=), or [mute the
thread](https://github.com/notifications/unsubscribe-auth
/AHR5PFsMhHIcUtPA76ka9hY-oOYX6oP2ks5qsmZugaJpZM4KDyQY&r=cmVwbHkrMDA3NDc5M2NiMW
QzNDRiZmFkM2U1MTA0MDI0ODQzNmVlMjMwYWVjNTE1MjVkZmYxOTJjZjAwMDAwMDAxMTNmYjgyNmU5
MmExNjljZTBhYTRmYjFkQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notificat
ions/beacon/AHR5PIEvGH7o7e8HYhWiyqBNVVHa0r7dks5qsmZugaJpZM4KDyQY.gif)

2016-09-27 03:53 UTC, jhseu requested changes

2016-09-27 03:53 UTC, jhseu commented on tensorflow/g3doc/tutorials/seq2seq/index.md
> +`python/ops/seq2seq.py` | Library for building sequence-to-sequence models.
Mind merging this into one list? Something like:

This tutorial references the following files:
python/ops/seq2seq.py ...
models/rnn/translate/...

2016-09-29 21:30 UTC, amlankar commented on tensorflow/g3doc/tutorials/seq2seq/index.md
> +`python/ops/seq2seq.py` | Library for building sequence-to-sequence models.
Done!

2016-09-29 21:32 UTC, jhseu approved these changes

2016-09-29 21:32 UTC, jhseu commented
Jenkins, test this please

2016-09-29 23:01 UTC, merged