Update _inferred_steps when recreating iterator.
tensorflow/tensorflow pull request #45338
Opened 2020-12-02 13:40 UTC by tabergma

closes https://github.com/tensorflow/tensorflow/issues/41019

In case your data generator returns different number of batches per epoch, we need to update the `inferred_steps` after recreating the iterator over the dataset. This allows users to create data generators that modify the datasets and update the batch size every epoch, for example, using an increasing batch size.

2020-12-03 16:06 UTC, tabergma commented
I have some trouble setting up the tests locally to see the actual failures. Do you have any guide for that? Or can you point me to the actual errors why tests are failing?

2021-04-15 17:14 UTC, fchollet requested changes
Thanks for the PR. Please add a unit test to check this change.

2021-04-21 16:51 UTC, gbaned commented
@tabergma Can you please check @fchollet's comments and keep us posted ? Thanks!

2021-04-21 17:39 UTC, tabergma commented
@gbaned @fchollet Thanks for the review! Not sure when I have time to add the unit test as I have a newborn. I'll keep you posted.

2021-05-10 09:03 UTC, gbaned commented
@tabergma  Any update on this PR? Please. Thanks!

2021-05-14 14:25 UTC, tabergma commented
I did not find time to add a test yet, try to do it in the next week.

2021-06-07 17:24 UTC, tabergma commented
I started looking into it, but had some problems running the tests locally. Not sure when I'll have time to finish it.

2021-06-25 15:14 UTC, gbaned commented
@tabergma Any update on this PR? Please. Thanks!

2021-06-25 19:56 UTC, tabergma commented
Unfortunately, no update. I guess I'm not able to find time any time soon. Will let you know when I start working on it again. Sorry for the delay.

2021-07-16 01:56 UTC, tensorflowbutler commented
It has been 19 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-07-28 15:00 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-07-28 15:00 UTC, closed without merging

2022-03-23 16:43 UTC, markus-hinsche commented
I would like to follow up with this PR. I work in @tabergma 's team. 
@gbaned @fchollet Would it be ok to re-open this PR? Would you still accept this contribution?

2022-03-24 07:15 UTC, gbaned commented
Hi @markus-hinsche  It looks like this PR relates to the Keras component. Please submit it to the github.com/keras-team/keras repository instead. Thankyou.
@fchollet, @qlzh727