Optimize MutableDenseHashTable's memory usage and performance in case of large value_shape
tensorflow/tensorflow pull request #45407
Opened 2020-12-04 14:49 UTC by rangjiaheng

When value_shape is very large, we store a pointer in key_buckets, and store table values into a vector of value_buckets, which containers no empty values. This optimize can decrease 15% memory usage in a test of value_dtype = int64 and value_shape = [16], also get better lookup/insert performance.

2021-01-28 03:18 UTC, rangjiaheng commented
@rohan100jain hi, any suggestions ?

2021-04-30 15:14 UTC, gbaned commented
@rangjiaheng  Can you please resolve conflicts? Thanks!

2021-05-10 09:11 UTC, gbaned commented
@rangjiaheng  Any update on this PR? Please. Thanks!

2021-05-19 04:46 UTC, rohan100jain requested changes
Thanks a lot for the contribution! Have you done some benchmarking on various workloads to see what the impact is?

2021-05-19 04:46 UTC, rohan100jain commented on tensorflow/core/kernels/lookup_table_op.cc
> +  int64 value_index_; TF_GUARDED_BY(mu_)
Add comments describing what these member variables are for

2021-05-19 04:46 UTC, rohan100jain commented on tensorflow/core/kernels/lookup_table_op.cc
> +        sizeof(K) <= sizeof(void*) && value_bytes_ > sizeof(void*)) {
The constraint of sizeok(K) <= sizeof(void*) is unclear to me....

2021-05-19 04:46 UTC, rohan100jain commented on tensorflow/core/kernels/lookup_table_op.cc
> +    const auto* default_flat_ptr = default_flat.data();
nit: Move this to line 435

2021-05-19 04:46 UTC, rohan100jain commented on tensorflow/core/kernels/lookup_table_op.cc
> +        key_dtype(), TensorShape({num_buckets_, allocate_size}), &key_buckets_,
Its unclear to me that when use_value_ptr_ is false also we are modifying key_buckets_?

2021-05-19 04:46 UTC, rohan100jain commented on tensorflow/core/kernels/lookup_table_op.cc
> +            if (*(void**) dst == nullptr) {              // reuse value chunk
So looks like we keep adding to the value_buckets_vec_ but do we ever reclaim that memory? Or does it keep on increasing? Would that cause adverse performance on workloads that have a lot of Inserts and Deletes?

2021-06-25 15:15 UTC, gbaned commented
@rangjiaheng Can you please check @rohan100jain's comments and resolve conflicts?. Thanks!

2021-07-07 18:27 UTC, gbaned commented
@rangjiaheng Any update on this PR? Please. Thanks!

2021-07-27 23:29 UTC, tensorflowbutler commented
It has been 19 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-07-28 16:19 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-07-28 16:20 UTC, closed without merging