Add classifier_activation param to applications
tensorflow/tensorflow pull request #45643
Opened 2020-12-14 00:17 UTC by ivallesp

I have noticed that the DenseNet and NasNet models did not have the possibility to specify the `classifier_activation` parameter, when the main classes have it implemented and the other models in `tf.keras.applications` also have them available, hence I have added those parameters. I have tested the code locally.

2020-12-17 22:09 UTC, fchollet requested changes
Thank you for the PR! Please add a unit test to check this change. Also, you may need to update the API pbtxt files since this is an API change.

2020-12-19 18:19 UTC, ivallesp commented
I have added the unit tests and squashed the commit with the previous one. Could you please elaborate on the pbtxt request? What do you need me to change?

2021-03-11 17:39 UTC, fchollet approved these changes
LGTM, thank you

2021-03-11 17:41 UTC, fchollet commented
> Could you please elaborate on the pbtxt request? What do you need me to change and where?

I've checked that we should be able to handle that on our side.

2021-03-11 23:06 UTC, rthadur commented
@ivallesp can you please check sanity build failures ?

2021-04-01 00:52 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-04-06 14:50 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-04-06 14:50 UTC, closed without merging