upgrade protobuf to 3.1.0
tensorflow/tensorflow pull request #4572
Opened 2016-09-25 10:08 UTC by kashif

2016-09-25 10:09 UTC, kashif commented
For issues #4561 and #4371

2016-09-26 01:01 UTC, jart commented
Mr. Jenkins: test this please

2016-09-27 08:03 UTC, kashif commented
@jart can you kindly try to run jenkins again?

2016-09-27 17:55 UTC, jhseu requested changes
Can you also modify:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py
To change the dependency to 3.1.0?

2016-09-27 17:55 UTC, jhseu commented on tensorflow/g3doc/get_started/os_setup.md
> +3.0.0. Protobuf's pip package downloaded from [PyPI](https://pypi.python.org)
Can you change this to 3.1.0?

2016-09-27 20:29 UTC, kashif commented on tensorflow/g3doc/get_started/os_setup.md
> +3.0.0. Protobuf's pip package downloaded from [PyPI](https://pypi.python.org)
as far as I see the protobuf pip package is still at 3.0.0. Or am I missing something?

2016-09-27 20:34 UTC, jhseu commented on tensorflow/g3doc/get_started/os_setup.md
> +3.0.0. Protobuf's pip package downloaded from [PyPI](https://pypi.python.org)
See my other comment about updating:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py

Seems like it's available on pypi to update:
https://pypi.python.org/pypi/protobuf/3.1.0

2016-09-27 20:41 UTC, kashif commented
@jhseu done

2016-09-27 20:47 UTC, jhseu commented
Jenkins, test this please

2016-09-27 20:58 UTC, jhseu approved these changes

2016-09-27 22:44 UTC, jhseu commented
Can you merge or rebase with the latest master? Tests are failing due to being on an old change.

2016-09-27 23:37 UTC, jhseu commented
Jenkins, test this please

2016-09-28 02:10 UTC, merged