Extract a function for parsing op DEPTH_TO_SPACE
tensorflow/tensorflow pull request #46026
Opened 2020-12-29 00:51 UTC by rkuester

Extract the parsing of op parameters from the flatbuffer out of a
switch statement case, into a standalone function which can be
called by the micro op resolver.

This PR is part of the work to port operator DEPTH_TO_SPACE
from lite to micro, as tracked in issue #46025.

2020-12-30 18:12 UTC, petewarden approved these changes

2020-12-30 22:53 UTC, advaitjain requested changes

2020-12-30 22:53 UTC, advaitjain commented on tensorflow/lite/core/api/flatbuffer_conversions.cc
> +    // old todo (b/157480169): We should either return kTfLiteError or fill in some
we do want to keep this TODO as is. If it is triggering some failure in the CI then we'll need to fix the CI. Can you please change it back to TODO(b/): and then I'll take a look at what the CI error is.

2021-01-02 23:20 UTC, advaitjain approved these changes

2021-01-03 05:12 UTC, advaitjain commented
All checks are passing.

Merging a PR needs two approvals from a Googler so we'll need to wait until @petewarden can approve the change in the internal review system before this can be merged.

2021-01-11 01:53 UTC, petewarden approved these changes

2021-01-13 20:00 UTC, rkuester commented
@advaitjain not sure what internal check this one is failing.

2021-01-13 20:46 UTC, advaitjain commented
The failing tests are internal, unrelated and currently flaky. I have set the internal change to submit while ignoring these tests. This PR should get merged shortly.

2021-01-13 21:01 UTC, merged