[TFLM] Added support for optimized quantize kernel for CEVA-BX1 and CEVA-SP500 cores
tensorflow/tensorflow pull request #46226
Opened 2021-01-06 16:53 UTC by yair-ehrenwald

see issue https://github.com/tensorflow/tensorflow/issues/45607

Started with quantize but more to follow
Also some fixes for CEVA makefiles in this PR.

2021-02-04 13:35 UTC, gbaned commented
@yair-ehrenwald  Can you please resolve conflicts? Thanks!

2021-02-22 00:37 UTC, tensorflowbutler commented
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-03-01 14:31 UTC, njeffrie requested changes
Please run:
clang-format --style=google tensorflow/lite/micro/kernels/ceva/CEVA_TFLM_lib.h

or 

tensorflow/lite/micro/tools/make/downloads/pigweed/pw_presubmit/py/pw_presubmit/format_code.py --fix /workspace/tensorflow/lite/micro/kernels/ceva/CEVA_TFLM_lib.h

These should be equivalent (at least in my experience).

2021-03-01 14:31 UTC, njeffrie commented on tensorflow/lite/micro/tools/make/templates/ceva_SP500/ceva_app_makefile.tpl
> +TARGET_TOOLCHAIN_ROOT := /home/yaire/CEVA-ToolBox/V20/SensPro
Seems like having a hardcoded path is likely an error? I notice this is also present in the other ceva template file as well.

2021-03-01 14:31 UTC, njeffrie commented on tensorflow/lite/micro/tools/make/targets/ceva/CEVA_SP500_TFLM.ld
> +OUTPUT(a.elf)
Please add copyright notice (see other ld files for reference)

2021-03-01 14:31 UTC, njeffrie commented on tensorflow/lite/micro/kernels/ceva/quantize.cc
> +#ifdef ORIGINAL_IMPLEMENTATION
I'm curious how this is different compared with running EvalQuantizeReference. Perhaps this is some dead test code?

2021-03-13 18:44 UTC, yair-ehrenwald commented
Closing this, opened a new PR https://github.com/tensorflow/tensorflow/pull/47781

2021-03-13 18:44 UTC, closed without merging