Speedup DepthToSpace
tensorflow/tensorflow pull request #46304
Opened 2021-01-09 04:17 UTC by WindQAQ

This PR speedups DepthToSpace with Eigen Tensor Generator. Below is my benchmark

On ***Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz***

| input_shape (`N_H_W_C`) | block_size | Old (M items/s) | New (M items/s) |
| ---------------------------- | ----------- | ---- | ----- |
| 1_64_64_64_2                     |  2             |  1123 | 1523 |
| 16_64_64_64_2                  | 2              | 1299 | 2137 |
| 32_64_64_64_2                     |  2             |  1123 | 1912|
| 1_128_128_64_2                  | 2              | 1306| 2644 |
| 16_128_128_64_2                     |  2             |   627| 1796 |
| 32_64_64_64_2                  | 2              | 618| 1827 |
| 1_64_64_64_2                     |  4             |  694| 1283|
| 16_64_64_64_2                  | 4             | 767 | 1953 |
| 32_64_64_64_2                     |  4             |  483 | 1515 |
| 1_128_128_64_2                  | 4              | 806| 1892 |
| 16_128_128_64_2                     |  4             |   478| 1525 |
| 32_64_64_64_2                  | 4              | 469| 1514 |

2021-03-01 18:29 UTC, mihaimaruseac approved these changes

2021-03-04 12:28 UTC, gbaned approved these changes

2021-03-08 18:48 UTC, mihaimaruseac commented on tensorflow/core/kernels/depthtospace_op.cc
> +  const Eigen::Index output_depth_;
```suggestion
  const Eigen::Index block_size;
  const Eigen::Index output_height;
  const Eigen::Index output_width;
  const Eigen::Index output_depth;
```

2021-03-08 18:50 UTC, mihaimaruseac commented on tensorflow/core/kernels/depthtospace_op.cc
> +  const Eigen::Index output_depth_;
We need this edit (and fixing the variables everywhere) to fix coding style.

Can you fix the other usages please?

2021-03-23 20:47 UTC, cantonios requested changes
The main benefit seems to be that this will allow multithreaded execution - is that correct?

Currently does not compile due to member name issue.  Please address that either by removing trailing underscores as @mihaimaruseac suggested, or by making a class with private members.

2021-03-23 20:47 UTC, cantonios commented on tensorflow/core/kernels/depthtospace_op.cc
> +  std::vector<std::pair<Eigen::Index, Eigen::Index>> ys_, xs_;
Technically you only need one of these, sized to the larger of `output_width` and `output_height`.

2021-03-23 20:47 UTC, cantonios commented on tensorflow/core/kernels/depthtospace_op.cc
> +    for (Eigen::Index i = 0; i < indices.size(); ++i) {
Can you benchmark without caching these to see if it makes a difference?  It might not be worth the extra storage.

2021-04-05 16:09 UTC, cantonios requested changes
@WindQAQ we are still awaiting the above changes to this PR.  What is the status?

2021-04-21 17:18 UTC, gbaned commented
@WindQAQ  Can you please check @cantonios's comments and keep us posted ? Thanks!

2021-04-30 15:32 UTC, gbaned commented
@WindQAQ Any update on this PR? Please. Thanks!

2021-06-25 16:34 UTC, gbaned commented
@WindQAQ Any update on this PR? Please. Thanks!

2021-07-16 01:56 UTC, tensorflowbutler commented
It has been 19 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-07-29 14:45 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-07-29 14:45 UTC, closed without merging