GridRNN cell uses tuples for output and states
tensorflow/tensorflow pull request #4631
Opened 2016-09-28 16:06 UTC by phvu

Added `state_is_tuple=True` and `output_is_tuple=True` into the constructor of GridRNNCell:

    > cell = tf.contrib.grid_rnn.Grid2LSTMCell(3, use_peepholes=True)
    > cell.state_size
           (LSTMStateTuple(c=3, h=3), LSTMStateTuple(c=3, h=3))
    > cell.output_size
           (3,)

This means there are 2 LSTM cells in the grid, and the state of each cell has size of `(c=3, h=3)`. There is only one output dimension, whose size is 3.

In contrast:

    > cell = tf.contrib.grid_rnn.Grid2BasicRNNCell(3)
    > cell.state_size
         (3, 3)
    > cell.output_size
         (3,)

This means there are 2 BasicRNN cell in the grid, and the state of each cell has size of 3. There is only one output dimension, whose size is 3.

Previous behaviour is maintained by using `state_is_tuple=False, output_is_tuple=False` when creating the cell.

    > cell = tf.contrib.grid_rnn.Grid2LSTMCell(3, use_peepholes=True, state_is_tuple=False, output_is_tuple=False)
        WARNING:tensorflow:<tensorflow.contrib.grid_rnn.python.ops.grid_rnn_cell.Grid2LSTMCell object at 0x10de68f50>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
        WARNING:tensorflow:<tensorflow.contrib.grid_rnn.python.ops.grid_rnn_cell.Grid2LSTMCell** object at 0x10de68f50>: Using a concatenated output is slower and will soon be deprecated.  Use output_is_tuple=True.

    > cell.state_size
        12
    > cell.output_size
        3

    > cell = tf.contrib.grid_rnn.Grid2BasicRNNCell(3, state_is_tuple=False, output_is_tuple=False)
        WARNING:tensorflow:<tensorflow.contrib.grid_rnn.python.ops.grid_rnn_cell.Grid2BasicRNNCell object at 0x10de4b950>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
        WARNING:tensorflow:<tensorflow.contrib.grid_rnn.python.ops.grid_rnn_cell.Grid2BasicRNNCell object at 0x10de4b950>: Using a concatenated output is slower and will soon be deprecated.  Use output_is_tuple=True.

    > cell.state_size
       6
    > cell.output_size
       3

This is to fix https://github.com/tensorflow/tensorflow/issues/4296

2016-09-29 11:53 UTC, StefOe commented on tensorflow/contrib/grid_rnn/python/ops/grid_rnn_cell.py
> +    if inputs is not None and inputs.get_shape().with_rank(2)[1].value > 0 \
This indeed fixes #4296

2016-10-04 15:32 UTC, ebrevdo commented
Jenkins, test this please.

2016-10-31 16:24 UTC, vrv commented
@tensorflow-jenkins test this please

2016-10-31 16:26 UTC, vrv commented
@ebrevdo do you give an LGTM?

2016-11-03 22:49 UTC, ebrevdo requested changes

2016-11-03 22:51 UTC, ebrevdo commented
there are many changes in this code.  before a more thorough review, can you tell me if this is fully backwards compatible with the original code?  if not, how?

2016-11-07 10:25 UTC, phvu commented
Sorry I screwed up this PR (lack of water and sleep apparently). Will close this and submit another PR, with responds to your comments.

2016-11-07 10:25 UTC, closed without merging