Add RFC for pre-allocated tensors.
tensorflow/tensorflow pull request #46399
Opened 2021-01-13 13:22 UTC by jenselofsson

Add a RFC-document for the pre-allocated tensors feature.

2021-01-13 14:48 UTC, jenselofsson commented on tensorflow/lite/micro/docs/preallocated_tensors.md
> +* When the tensor is to be consumed from a memory location outside the tensor arena, e.g. a separate memory bank DSP.
Add a line break after this line.

2021-01-13 19:01 UTC, advaitjain requested changes
looks good to me.

It might be worth a sub-folder in images called preallocated_tensors so that there is a bit of a directory structure there.

And could you also link to this from the top-level README (just add to the bottom of the list for now, and we'll reorganize later):
https://github.com/tensorflow/tensorflow/blob/78fdd635abb65422c5a4b72750e9fafccf8bee61/tensorflow/lite/micro/README.md#L65-L69

2021-01-15 13:51 UTC, gbaned commented
@jenselofsson  Can you please check @advaitjain's comments and keep us posted ? Thanks!

2021-01-18 13:07 UTC, jenselofsson commented
> looks good to me.
> 
> It might be worth a sub-folder in images called preallocated_tensors so that there is a bit of a directory structure there.
> 

Good idea!

> And could you also link to this from the top-level README (just add to the bottom of the list for now, and we'll reorganize later):
> 
> https://github.com/tensorflow/tensorflow/blob/78fdd635abb65422c5a4b72750e9fafccf8bee61/tensorflow/lite/micro/README.md#L65-L69

Sure!

2021-01-19 05:17 UTC, advaitjain approved these changes

2021-01-20 00:10 UTC, advaitjain commented
copybara failed, triggering it again.

2021-01-20 00:43 UTC, merged