[INTEL_MKL] Add `is_weight_const Attr` for QMatMulDequantize Op
tensorflow/tensorflow pull request #46476
Opened 2021-01-16 04:52 UTC by retonym

To add the missing `is_weight_const` attr in MklQuantizedMatMulAndDequantize registration.

2021-02-18 23:44 UTC, penpornk requested changes
Sorry for the delay and thank you for the PR! I have one minor nit.

2021-02-18 23:44 UTC, penpornk commented on tensorflow/core/common_runtime/mkl_layout_pass.cc
> +  // added "T" for facilitating MklToTf conversion.
Nit: 
```suggestion
  // Add "T" for facilitating MklToTf conversion.
```

2021-02-19 01:19 UTC, retonym commented
Thanks for the review.  Comments changed.

2021-02-19 01:20 UTC, penpornk approved these changes
Thank you!

2021-02-23 04:37 UTC, gbaned approved these changes

2021-02-23 06:47 UTC, merged