constant learning rate logging added to TensorBoard callback
tensorflow/tensorflow pull request #46571
Opened 2021-01-21 11:36 UTC by MatejHl

Allowing TensorBoard callback to log leraning rate (lr) even if there is no scheduler used. Tensorboard will log every lr even when it is a constant. This is especially important when using ReduceLROnPlateau callback as the lr is treated as constatnt in every iteration and changed by assigning a new constant.

2021-01-21 20:33 UTC, tomerk requested changes
Could you add tests for this?

And have you checked that the only options for `optimizer.lr` are "LearningRateSchedule", "numeric" and "None"? (This code might cause breakages if there are other possibilities)

2021-01-22 13:13 UTC, MatejHl commented
### `optimizer.lr` values:
According to the docs, learning rate should be one of "A Tensor, floating point value, or a schedule that is a tf.keras.optimizers.schedules.LearningRateSchedule, or a callable". Only problem for `tf.summary.scalar` could be a callable, but in case of a callable being passed as learning rate, [__getattribute__](https://github.com/tensorflow/tensorflow/blob/582c8d236cb079023657287c318ff26adb239002/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L785) of `keras.optimizers.Optimizer` (actually of OptimizerV2) is calling `self._get_hyper` and that returns the value after call if self._hyper[name] is callable. So if user is consistent with how optimizer should be used according to docs, it should work fine. 

In fact I think a better elif condition could be more future proof (although the proposed one should work), but I am not sure how to check if value is tf.summary.scalar consistent. Maybe you have an idea?

### Tests:
I ran local test using code below and I also performed test by running `keras.callbacks_test.py` (both in tensorflow:devel Docker image) and I put gist for output below. The only test fails are due to the fact, that 'epoch_learning_rate' is logged all the time (which is expected) so there is an extra element in summary output leading to *AssertionError: Items in the first set but not the second*

Please let me know if further tests are needed.

<details>
<summary>Local test code</summary>

``````
import tensorflow as tf
import datetime
import os

class SimpleModel(tf.keras.Model):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.Dense_in = tf.keras.layers.Dense(units = 50, 
                                activation=tf.nn.relu, 
                                use_bias=True)
        self.Dense_hidden = tf.keras.layers.Dense(units = 20, 
                                activation=tf.nn.relu, 
                                use_bias=True)
        self.Dense_out = tf.keras.layers.Dense(units = 1, 
                                activation=None, 
                                use_bias=True)

    def call(self, inputs, training = True):
        X = self.Dense_in(inputs)
        X = self.Dense_hidden(X)
        X = self.Dense_out(X)
        return X

dummy_data = tf.random.normal((10000, 50))
dummy_y = tf.random.uniform((10000,), minval=0, maxval=2, dtype=tf.dtypes.int32)


def test_tf_lr_logging(lr):
    model = SimpleModel()
    loss = tf.keras.losses.BinaryCrossentropy(name='binary_crossentropy', from_logits=True)

    opt = tf.keras.optimizers.SGD(learning_rate = lr)
    model.compile(optimizer = opt, loss = loss, metrics=["acc"])

    _datetime = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    log_dir = os.path.join('dummy_logs', _datetime)
    tb_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir)

    model.fit(x = dummy_data, y = dummy_y, epochs = 2,
        callbacks=[tf.keras.callbacks.ReduceLROnPlateau(monitor='acc', 
                        factor=0.5, patience=10, verbose=0, mode='auto', 
                        min_delta=0.0001, cooldown=0, min_lr=0),
                    tb_callback])


if __name__ == '__main__':
    ### schedule
    lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
        initial_learning_rate = 0.001,
        decay_steps=100000,
        decay_rate=0.96)
    test_tf_lr_logging(lr_schedule)

    ### callable
    def lr_callable():
      return .1
    test_tf_lr_logging(lr_callable)

    ### float
    le_constant = .05
    test_tf_lr_logging(le_constant)

``````

</details>

[gist](https://gist.github.com/MatejHl/c1f696791fa3bdcbccbb4ee69a6c56e8) for callbacks_test.

2021-01-22 19:20 UTC, tomerk commented
Hi @MatejHl ,

Okay that makes sense. Re: the cases, can you add a comment to your else branch noting these cases?

As for the tests: Can you make sure to include updates to the tensorboard tests in the callbacks_Test.py in your PR covering all of these cases? (Callable & constant). Local testing is insufficient because it won't get included in our automated test infrastructure, and it could break or regress really easily.

2021-01-27 20:59 UTC, omalleyt12 approved these changes
Thanks for the PR! LGTM

2021-02-16 16:22 UTC, gbaned approved these changes

2021-02-17 00:39 UTC, merged