Port int8 and float versions of batch_to_space to TFLM
tensorflow/tensorflow pull request #46681
Opened 2021-01-26 02:21 UTC by njeffrie

Commit 1 copies the TFLite operator into TFLM
Commit 2 implements basic float, int8 and error checking tests along with float and int8 implementations of batch_to_space_nd

This version requires that the flat size of input matches output, since TFLM does not support tensor resizing.

2021-01-26 07:48 UTC, stephanboner approved these changes
Looks really good!

2021-01-26 18:23 UTC, advaitjain requested changes
I don't see the test.cc file in the PR? And the bazel build is failing.

2021-01-26 18:32 UTC, advaitjain commented on tensorflow/lite/micro/micro_mutable_op_resolver.h
> +                      tflite::Register_BATCH_TO_SPACE_ND(),
nit: don't need `tflite::`

2021-01-26 18:32 UTC, advaitjain commented on tensorflow/lite/micro/kernels/batch_to_space_nd.cc
> +  const TfLiteTensor* crops = GetInput(context, node, kCropsTensor);
remove? we aren't really using these.

2021-01-26 22:39 UTC, njeffrie commented on tensorflow/lite/micro/kernels/batch_to_space_nd.cc
> +  const TfLiteTensor* crops = GetInput(context, node, kCropsTensor);
Done.

2021-01-26 22:39 UTC, njeffrie commented on tensorflow/lite/micro/micro_mutable_op_resolver.h
> +                      tflite::Register_BATCH_TO_SPACE_ND(),
Done.

2021-01-26 22:59 UTC, advaitjain requested changes
some more nits.

2021-01-26 22:59 UTC, advaitjain commented on tensorflow/lite/micro/kernels/batch_to_space_nd_test.cc
> +const int basic_input_output_size = 16;
```cc
constexpr int kBasicInputOutputSize = 16;
```
since it is used for array size?

2021-01-26 22:59 UTC, advaitjain commented on tensorflow/lite/micro/kernels/batch_to_space_nd_test.cc
> +  if (runner.InitAndPrepare() != kTfLiteOk || runner.Invoke() != kTfLiteOk) {
use the macros instead?
```cc
TF_LITE_ENSURE_STATUS(runner.InitAndPrepare());
TF_LITE_ENSURE_STATUS(runner.Invoke());
```

2021-01-26 22:59 UTC, advaitjain commented on tensorflow/lite/micro/kernels/batch_to_space_nd_test.cc
> +    if (golden[i] != output[i]) {
add the following comment?

```cc
// TODO(b/158102673): workaround for not having fatal test assertions.
```

2021-01-27 02:14 UTC, njeffrie commented on tensorflow/lite/micro/kernels/batch_to_space_nd_test.cc
> +  if (runner.InitAndPrepare() != kTfLiteOk || runner.Invoke() != kTfLiteOk) {
Done.

2021-01-27 03:00 UTC, advaitjain approved these changes

2021-01-27 03:07 UTC, gbaned commented
@njeffrie Can you please resolve conflicts? Thanks!

2021-01-27 18:47 UTC, advaitjain commented
an error with the merge caused a number of unnecessary files to show up in the PR, that has since been resolved and I have manually set the label to `cla: yes`

2021-01-27 18:47 UTC, advaitjain approved these changes

2021-01-27 19:50 UTC, advaitjain approved these changes

2021-01-28 02:36 UTC, gbaned approved these changes

2021-01-28 19:03 UTC, advaitjain approved these changes

2021-01-28 23:07 UTC, advaitjain commented on tensorflow/lite/kernels/internal/reference/batch_to_space_nd.h
> +      RuntimeShape::ExtendedShape(4, unextended_output_shape);
same as https://github.com/tensorflow/tensorflow/pull/46714#discussion_r566468233

2021-01-28 23:07 UTC, advaitjain reviewed
same as https://github.com/tensorflow/tensorflow/pull/46714#pullrequestreview-578817051

2021-01-29 00:36 UTC, advaitjain approved these changes

2021-02-02 16:55 UTC, advaitjain approved these changes

2021-02-02 21:56 UTC, advaitjain approved these changes

2021-02-03 01:08 UTC, merged