Lower ResizeNearestNeighbor when half_pixel_centers=true
tensorflow/tensorflow pull request #46836
Opened 2021-02-01 19:58 UTC by WindQAQ

Lower ResizeNearestNeighbor when `half_pixel_centers=true`. This PR makes the lowering pattern match the use in TF python library as combination of `align_corners=false` and `half_pixel_centers=true` is the only code path in `tf.image.resize`.

Also remove some unnecessary reshape
- Before AddV2: x_indices can be broadcasted
- Before and after GatherV2: indices can be 2D without back and forth reshape

2021-02-05 17:22 UTC, gbaned commented
@WindQAQ  Can you please resolve conflicts? Thanks!

2021-04-07 17:32 UTC, gbaned commented
@WindQAQ Can you please resolve conflicts? Thanks!

2021-04-21 18:04 UTC, gbaned commented
@WindQAQ Any update on this PR? Please. Thanks!

2021-06-23 17:03 UTC, tenjua commented on tensorflow/compiler/mlir/tensorflow/tests/lower_tf.mlir
> -  // CHECK: [[VAL1:%.+]] = "tf.Const"() {value = dense<[1, 3, 3, 1]>
Patch O. diff

2021-06-23 17:03 UTC, tenjua commented on tensorflow/compiler/mlir/tensorflow/transforms/lower_tf.cc
> -    gathered_values =
n Y p

2021-06-23 17:04 UTC, tenjua commented on tensorflow/compiler/mlir/tensorflow/tests/lower_tf.mlir
> -  // CHECK: [[VAL1:%.+]] = "tf.Const"() {value = dense<[1, 3, 3, 1]>
. Patch

2021-06-23 17:06 UTC, tenjua commented on tensorflow/compiler/mlir/tensorflow/transforms/lower_tf.cc
> -        loc, GetScalarOfFloatType(rewriter.getF32Type(), 1.0));
N Y P

2021-06-23 17:07 UTC, tenjua approved these changes

2021-06-23 17:07 UTC, tenjua commented on tensorflow/compiler/mlir/tensorflow/transforms/lower_tf.cc
>    }
N Y P

2021-06-23 17:09 UTC, tenjua requested changes

2021-06-23 17:09 UTC, tenjua commented on tensorflow/compiler/mlir/tensorflow/tests/lower_tf.mlir
> -  // CHECK: [[VAL2:%.+]] = "tf.Const"() {value = dense<9> : tensor<1xi32>}
. diff

2021-07-07 18:34 UTC, gbaned commented
@WindQAQ  Can you please check @tenjua's comments and keep us posted ? Thanks!

2021-07-16 14:28 UTC, gbaned commented
@WindQAQ  Any update on this PR? Please. Thanks!

2021-08-01 00:40 UTC, tensorflowbutler commented
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this PR still valid? Assigning the `stalled` label. Please comment to reassure me that this is still being worked on.

2021-08-06 17:09 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-08-06 17:10 UTC, closed without merging