Fix skflow resnet example to work on v0.10.0
tensorflow/tensorflow pull request #4684
Opened 2016-09-30 14:47 UTC by tyfkda

I tried to run `resnet.py` skflow example on TensorFlow v0.10.0,
but an error occurred.

I have fixed the code to run on v0.10.0:

  * `tensorflow.contrib.learn.ops.conv2d` was deprecated and has been removed in #4373 .
    So changed to use `contrib.layers.convolution2d` .

  * `classifier` wasn't created if no previous model existed in `models/resnet/graph.pbtxt`,
but it was failed to run at first time.
    `TensorFlowEstimator` creation was removed in #2863 , so revert the code removal.

2016-09-30 15:18 UTC, terrytangyuan commented
Could you change to use Estimator and make sure the changes work with the version on master branch?

2016-09-30 21:14 UTC, tyfkda commented
@terrytangyuan ,
Can I make your suggestion in other pull request to keep this change simple?

I am trying to modify the code to use `Estimator` instead of `TesorFlowEstimator`, but it looks the class lacks functionality. Especially I cannot pass `feed_fn` to it, which is used in [TensorFlowEstimator#fit](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/base.py#L254).

I have sent a pull request to add the functionality (#4696). When it is accepted, I will change this example code to use `Estimator`.

2016-09-30 21:37 UTC, terrytangyuan commented
Sure, perhaps could you follow other examples that are being tested (you can take a look at the shell script in examples folder) so this example is being tested going forward? You might need to make sure it doesn't take forever to run, using the smaller dataset provided in TF.Learn.datasets.

2016-10-04 23:33 UTC, tyfkda commented
@terrytangyuan 
I've added a commit which adds resnet.py to the shell script.
I use `100` for test count, I am not sure it is good for CI.

2016-10-04 23:37 UTC, terrytangyuan commented
Thanks @tensorflow-jenkins Test this please

2016-10-05 00:20 UTC, tyfkda commented
Test failed, I should add the target into `BUILD`.
I've fixed the commit.

2016-10-05 01:05 UTC, terrytangyuan commented
@tensorflow-jenkins test this please

2016-10-05 06:01 UTC, tyfkda commented
@terrytangyuan Would you please take a look?
Test failed because the code used `tensorflow.examples.tutorials` package.

I have changed the code to use `learn.datasets.load_dataset`,
referred mnist.py example.

2016-10-05 09:33 UTC, gideonite commented on tensorflow/examples/skflow/resnet.py
> +for step in xrange(100):
nit pick: I can see why you did this but it's besides the point. Not important either way since this is just an example after all.

2016-10-05 09:33 UTC, gideonite approved these changes
I'm not familiar with the new skflow API but LGTM.

2016-10-05 11:55 UTC, tyfkda commented on tensorflow/examples/skflow/resnet.py
> +for step in xrange(100):
This change avoids infinite loop for CI test.

2016-10-06 18:17 UTC, yifeif commented
Looks like there are some conflicts. @tyfkda could you resolve them? Thanks!

2016-10-06 20:33 UTC, tyfkda commented
@yifeif Thank you for the notice, I have fixed the conflict, would you please take a look?

It seems examples have moved from tensorflow/examples/skflow to tensorflow/examples/learn in d74cc130dd0ce5ecd1421ef126e4446f337a856c (#3364),
so I moved resnet.py example accordingly.

2016-10-06 23:37 UTC, martinwicke requested changes

2016-10-06 23:37 UTC, martinwicke commented on tensorflow/examples/learn/resnet.py
> +classifier = learn.TensorFlowEstimator(
We are trying to get rid of the (deprecated) TensorFlowEstimator. Can you rewrite this as an Estimator instead? It's a fairly straightforward translation -- include the optimize_loss call in your model_fn, which has to return also a train_op (which the optimize_loss call creates for you).

2016-10-06 23:37 UTC, martinwicke commented on tensorflow/examples/learn/resnet.py
> +for step in xrange(100):
fit() should never be called in a loop. I know this is from an old example and you didn't do it, but as part of moving this example to the learn/ directory we have to update it to current best practices.

Instead, use steps=100, and if you want to output a score regularly, use a ValidationMonitor.

2016-10-08 13:00 UTC, tyfkda commented on tensorflow/examples/learn/resnet.py
> +classifier = learn.TensorFlowEstimator(
OK, I have updated the code to use `Estimator`.

2016-10-11 20:18 UTC, tyfkda commented
@martinwicke Would you please take a look? Thanks!

2016-10-11 21:11 UTC, martinwicke requested changes
Looks good -- two small changes? Sorry it took me so long.

2016-10-11 21:11 UTC, martinwicke commented on tensorflow/examples/learn/resnet.py
> +tf.logging.set_verbosity(tf.logging.INFO)  # Show training logs. (avoid sirence)
sirence => silence

2016-10-11 21:11 UTC, martinwicke commented on tensorflow/examples/learn/resnet.py
> +# Calculate accuracy.
Can you use `classifier.evaluate(... metrics=[streaming_accuracy])`?

2016-10-12 08:42 UTC, tyfkda commented on tensorflow/examples/learn/resnet.py
> +tf.logging.set_verbosity(tf.logging.INFO)  # Show training logs. (avoid sirence)
Fixed.

2016-10-12 08:44 UTC, tyfkda commented on tensorflow/examples/learn/resnet.py
> +# Calculate accuracy.
I have updated the code to use `classifer.evaluate`.

2016-10-12 08:46 UTC, tyfkda commented
@martinwicke Would you please take a look? Thanks!

2016-10-12 17:16 UTC, martinwicke approved these changes

2016-10-12 17:17 UTC, martinwicke commented
Jenkins, test this please!

2016-10-12 17:17 UTC, martinwicke commented
Looks great, thanks for doing this!

2016-10-12 18:39 UTC, merged

2016-10-12 23:57 UTC, tyfkda commented
I can use `Estimator#fit` with passing `x` and `y` argument,
so solved the problem.

I am going to close this issue.