[Graph C API] Registration API
tensorflow/tensorflow pull request #46868
Opened 2021-02-03 03:19 UTC by ShengYang1

This PR is to add graph registration C API, which includes:
1. Registration C API in `tensorflow/c/experimental/grappler/`.
2. `PluginGraphOptimizerRegistry` in grappler to register and create optimizer.

This PR is following RFC [Modular TensorFlow Graph C API](https://github.com/tensorflow/community/blob/master/rfcs/20201027-modular-tensorflow-graph-c-api.md).

2021-02-03 03:25 UTC, ShengYang1 commented
Hi @penpornk @ezhulenev,  please help to have a review. Thanks very much!

2021-02-22 18:09 UTC, ezhulenev approved these changes

2021-02-23 13:32 UTC, ShengYang1 commented
@ezhulenev MacOS UT failure is fixed, please review again. Thanks!

2021-02-23 15:53 UTC, gbaned approved these changes

2021-02-24 00:59 UTC, ShengYang1 commented
@ezhulenev @gbaned Seems the two MacOS UT failures are not related to this PR, one is about gRPC server, and the other is about python ImportError. Could you please help check? What should I do to fix the failures?

2021-02-24 02:34 UTC, penpornk commented
@ShengYang1 It could be that the test instance was flaky. Let me rerun them.

2021-02-26 21:06 UTC, penpornk requested changes

2021-02-26 21:06 UTC, penpornk commented on tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc
> +    LOG(FATAL) << "PluginGraphOptimizer with device_type " << device_type
We don't allow `LOG(FATAL)` in new code. Can we just make TF warn that it finds a duplicate (which TF will ignore) and carry on without crashing? (Let's also remove `OrDie` from the function name.) If something can go wrong with this route, please explain why.

2021-02-27 01:17 UTC, penpornk approved these changes

2021-02-27 01:17 UTC, penpornk commented on tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc
> +    LOG(FATAL) << "PluginGraphOptimizer with device_type " << device_type
Taking back my comment. We agree it's okay to fail. Please ignore this. :)

2021-03-02 04:45 UTC, penpornk requested changes

2021-03-02 04:45 UTC, penpornk commented on tensorflow/c/experimental/grappler/grappler.cc
> +                       TP_OPTIMIZER_REGISTRARION_PARAMS_STRUCT_SIZE);
Please fix in other places as well.
```suggestion
                       TP_OPTIMIZER_REGISTRATION_PARAMS_STRUCT_SIZE);
```

2021-03-02 08:14 UTC, ShengYang1 commented on tensorflow/c/experimental/grappler/grappler.cc
> +                       TP_OPTIMIZER_REGISTRARION_PARAMS_STRUCT_SIZE);
Done.

2021-03-02 17:39 UTC, penpornk approved these changes
Thank you for the quick fixes!

2021-03-04 20:29 UTC, merged

2021-03-04 20:51 UTC, penpornk commented
Just a heads up that I've made several changes internally before the merge. Most of them won't have any effects on other code. There are two changes that can break other codes using this PR:
- Renamed `ConfigsList` to [ConfigList].(https://github.com/tensorflow/tensorflow/blob/88affffa8fc78966b4623f1e6e8c98045f94abfd/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h#L30)
- Changed the signature of `BufferToMessage` from
```c++
Status BufferToMessage(const TF_Buffer* in,
                       tensorflow::protobuf::MessageLite& out);
```
to
```c++
Status BufferToMessage(const TF_Buffer* in,
                       tensorflow::protobuf::MessageLite* out);
```

Thank you again for the PR!

2021-03-05 22:51 UTC, penpornk commented
One more minor change: Renamed the versioning variables from `SE_MAJOR`, etc. to `GO_MAJOR`, etc. https://github.com/tensorflow/tensorflow/commit/bca7074097cd86333cfb809e8b15d881afd83b69

2021-03-20 18:39 UTC, EmployedRussian commented
FYI, this code:

```
PluginRegistrationMap* registered_plugin_optimizers = nullptr;
PluginRegistrationMap* GetPluginRegistrationMap() {
  if (registered_plugin_optimizers == nullptr)
    registered_plugin_optimizers = new PluginRegistrationMap;
  return registered_plugin_optimizers;
}
```
is thread-unsafe (two threads calling `GetPluginRegistrationMap()` in parallel will race on `registered_plugin_optimizers`) and may result in a memory leak.

Fix forthcoming.