[Graph C API] Util API
tensorflow/tensorflow pull request #46869
Opened 2021-02-03 03:19 UTC by ShengYang1

This PR is to add graph util C API, which includes:
1. `TF_GrapplerItem` to get preserved/fetched nodes.
2. `TF_GraphProperties` to infer tensor shapes.
3. `TF_FunctionLibraryDefinition` to get OpDef.

This PR is following RFC [Modular TensorFlow Graph C API](https://github.com/tensorflow/community/blob/master/rfcs/20201027-modular-tensorflow-graph-c-api.md).

2021-02-03 03:25 UTC, ShengYang1 commented
Hi @penpornk @ezhulenev,  please help to have a review. Thanks very much!

2021-02-24 01:00 UTC, ShengYang1 commented
@ezhulenev Could you please have a look on this PR? Thanks.

2021-02-24 15:18 UTC, ezhulenev approved these changes

2021-02-25 01:15 UTC, ShengYang1 commented
@ezhulenev @penpornk Seems the test failure is caused by network issue, it cannot fetch Eigen repo. Could you please help rerun it?

2021-02-25 01:39 UTC, penpornk commented
@ShengYang1 Thank you for checking! Rerunning. :)

2021-02-25 07:41 UTC, ShengYang1 commented
> @ShengYang1 Thank you for checking! Rerunning. :)

Thanks! I find windows gpu is failed this time, but it passed last time. I'm afraid this failure is still not related to this PR.

2021-03-02 00:34 UTC, penpornk requested changes

2021-03-02 01:01 UTC, ShengYang1 commented on tensorflow/c/experimental/grappler/grappler.h
> +//       TP_OPTIMIZER_REGISTRARION_PARAMS_STRUCT_SIZE};
Thanks for your careful review. Done.

2021-03-02 01:01 UTC, ShengYang1 commented on tensorflow/c/experimental/grappler/grappler.h
> +//      params->struct_size = TP_OPTIMIZER_REGISTRARION_PARAMS_STRUCT_SIZE;
Done.

2021-03-02 20:17 UTC, penpornk approved these changes
Thank you!

2021-03-04 21:02 UTC, penpornk requested changes
Could you please address merge conflicts? Thank you!

2021-03-05 08:11 UTC, ShengYang1 commented
> Could you please address merge conflicts? Thank you!

OK, I have already rebased. Thanks!

2021-03-10 00:55 UTC, ShengYang1 commented
@penpornk May I know the status of this PR? What else should I do? Thanks.

2021-03-10 01:03 UTC, penpornk commented
@ShengYang1 Sorry for the long silence! It's undergoing API review internally.

2021-03-17 01:00 UTC, ShengYang1 commented
@penpornk I have checked and found that this PR is merged into master, so I guess it is approved, am I right? Can we close this PR now?

2021-03-17 01:02 UTC, penpornk commented
@ShengYang1 Yes, it was merged a while ago. I didn't notice that it doesn't show as merged here. Probably because we made some internal changes. I'll close this now. Thank you again for the PR! :)

2021-03-17 01:02 UTC, closed without merging