Fail configure script immediately on error.
tensorflow/tensorflow pull request #4699
Opened 2016-09-30 23:48 UTC by davidzchen

If any of the commands in the script fails, then exit immediately.

For lines such as `default_python_bin_path=$(which python)`, add a `|| true`
expression so that if the executable does not exist, the command will not exit
with a non-zero exit code, and the variable will be set to an empty string.

Fixes #4662

2016-10-01 01:36 UTC, jhseu reviewed
Thanks for the change! Looks like the GPU build failed during configure. Ping me in chat if you need help debugging that.

Also adjust the python_config... || exit -1 line to remove the || exit -1?

2016-10-03 09:55 UTC, davidzchen commented
Interesting, it looks like it is failing at the following line:

```sh
    read -p "Please specify which gcc should be used by nvcc as the host compiler. [Default is $default_gcc_host_compiler_path]: " GCC_HOST_COMPILER_PATH
```

which is exiting with exit code `1`.

It seems that the current approach of piping in an empty file to the invocation of the configure script makes subsequent `read` commands to exit with an error code.

I have added a `-d` flag to have the `configure` script use defaults when finding libraries and toolchains on the system and updating the `configured` script to invoke `configure` with that flag.

Another command that causes `configure` to fail is when the script tries to resolve `libcudnn`. I found that the script only covers the case where `libcudnn` is installed to a `lib`/`lib64` directory, such as `/usr/local/cuda-7.5/lib64`, but not case where it isn't, such as `/usr/lib/x86_64-linux-gnu`, which is, in fact, the cuDNN install dir on the GPU docker image.

2016-10-03 23:17 UTC, davidzchen commented
The tests are now passing. PTAL.

2016-10-03 23:53 UTC, jhseu requested changes

2016-10-03 23:53 UTC, jhseu commented on configure
> +  echo "-d Use default configuration settings."
Instead of adding a new flag, we could just run `yes "" | ./configured" in the CI build, right?

2016-10-03 23:53 UTC, jhseu commented on configure
> +  echo " g"
Leftover from debugging? :)

2016-10-04 21:33 UTC, davidzchen commented on configure
> +  echo "-d Use default configuration settings."
Great idea!

2016-10-04 21:33 UTC, davidzchen commented on configure
> +  echo " g"
Yes :)

2016-10-04 21:50 UTC, jhseu approved these changes
Thanks!

Jenkins, test this please

2016-10-04 22:42 UTC, davidzchen commented
The failing test in the Linux CPU Tests (Python 3) run, `//tensorflow/contrib/learn:graph_io_test`, does not appear to be related to this change.

2016-10-04 22:47 UTC, jhseu commented
Weird, I've seen that before where graph_io_test "fails", but all the tests in it passed. Feel free to ignore that test and merge @yifeif.

2016-10-04 22:55 UTC, yifeif commented
I have seen similar failure sporadically in nightly py3 builds as well. Will investigate separately. Merging. Thanks @davidzchen and @jhseu!

2016-10-04 22:55 UTC, merged