Add KL divergence for Categorical and Beta distributions.
tensorflow/tensorflow pull request #4730
Opened 2016-10-03 14:44 UTC by admcrae

2016-10-03 16:28 UTC, ebrevdo requested changes

2016-10-03 16:28 UTC, ebrevdo commented on tensorflow/contrib/distributions/python/kernel_tests/beta_test.py
> +  def testBetaBetaKL(self):
can you run these tests with bazel --runs_per_test=500 and ensure they never fail?

2016-10-03 16:28 UTC, ebrevdo commented on tensorflow/contrib/distributions/python/ops/beta.py
> +    name, "kl_beta_beta", inputs):
don't need this in a new line since the whole with declaration fits within 80 chars.

2016-10-03 16:28 UTC, ebrevdo commented on tensorflow/contrib/distributions/python/ops/categorical.py
> +    )
this can go at the end of the previous line

2016-10-03 16:28 UTC, ebrevdo commented on tensorflow/contrib/distributions/python/ops/beta.py
> +      log_betas = (math_ops.lgamma(d2.a) + math_ops.lgamma(d2.b)
Write in a comment above log_bets:

# ln((B(a', b') / B(a, b))

2016-10-03 16:28 UTC, ebrevdo commented on tensorflow/contrib/distributions/python/ops/beta.py
> +      digammas = ((d1.a - d2.a)*math_ops.digamma(d1.a)
Write in a comment above digammas:

(a - a') * psi(a) + (b - b') * psi(b) + (a' + b' - a - b) * psi(a + b)

2016-10-03 18:12 UTC, admcrae commented on tensorflow/contrib/distributions/python/kernel_tests/beta_test.py
> +  def testBetaBetaKL(self):
Confirmed.

2016-10-05 12:19 UTC, admcrae commented
I have cleaned up the code a bit along with adding another sanity check to the tests. I can confirm that running the tests 500 times results in no failures.

2016-10-11 20:44 UTC, ebrevdo commented
Jenkins, test this please.

2016-10-12 05:27 UTC, rohan100jain commented
@tensorflow-jenkins test this please

2016-10-17 04:44 UTC, ebrevdo approved these changes

2016-10-18 04:18 UTC, ebrevdo commented
Please resolve conflicts.

2016-10-19 11:16 UTC, admcrae commented
Done.

2016-10-19 16:17 UTC, drpngx commented
Jenkins, test this please.

2016-10-19 17:08 UTC, drpngx commented
(maybe docker bug?)

Jenkins, test this please.

2016-10-19 18:37 UTC, merged