Add a status badge for Arduino examples
tensorflow/tensorflow pull request #47367
Opened 2021-02-24 09:52 UTC by PiotrZierhoffer

This PR adds a status badge to TFLite Micro Readme.

The graphic style is slightly different to the current badges, but it's auto-generated by GitHub, so it requires no additional handling on the CI side.

2021-02-24 17:05 UTC, advaitjain requested changes
can you put this above Xtensa so that we have the list be alphabetically ordered?

2021-02-26 14:12 UTC, PiotrZierhoffer commented
Fixed

2021-02-26 16:01 UTC, advaitjain approved these changes

2021-03-01 18:27 UTC, advaitjain commented
copybara failed :-( reapplying the tags to trigger it again.

2021-03-01 18:59 UTC, merged