Modify Transpose kernel to work in TFLu
tensorflow/tensorflow pull request #47446
Opened 2021-02-27 08:01 UTC by patriklaurell

Modifications to the transpose kernel necessary to make it run in micro. This is PR 4/5 in delivering #45695

2021-03-01 20:06 UTC, abattery commented
This PR also impacts the performance changes on the TFLite. Could you use the micro macro to divide the logics? For example, keeping the original logic for the TFlite and using a new logics for only micro cases.

2021-03-02 15:43 UTC, patriklaurell commented
@abattery I am not sure I understand what you mean. The changes in this PR should only affect the micro kernel. How does this impact the performance changes on TFLite?

2021-03-02 21:06 UTC, abattery commented
Sorry @patriklaurell you are right. I misread the filename. Please ignore my comment.

2021-03-29 12:08 UTC, dmpiergiacomo commented
Hi, which is the status of this PR? Thank you.

2021-04-30 15:12 UTC, patriklaurell commented
@petewarden I updated this PR and added two commits for porting the tests and adding transpose to the micro build. It is ready for review.

2021-05-05 10:20 UTC, patriklaurell commented
@advaitjain @petewarden The MacOS CPU Python3 test is failing but there is very little information in the test log and I have no way of reproducing the error locally. Do you have any insight into why it fails?

2021-05-05 16:28 UTC, advaitjain requested changes

2021-05-05 16:28 UTC, advaitjain commented on tensorflow/lite/micro/kernels/transpose.cc
> +                           GetTensorData<type>(op_context.output))
remove this #define and directly call the reference function from the switch case.

2021-05-05 16:28 UTC, advaitjain commented on tensorflow/lite/micro/kernels/transpose.cc
>    switch (op_context.input->type) {
only add support for int8 and float32 for the initial port PR. Everything else should be done separately on an as-needed basis.

2021-05-05 16:29 UTC, advaitjain commented
> @advaitjain @petewarden The MacOS CPU Python3 test is failing but there is very little information in the test log and I have no way of reproducing the error locally. Do you have any insight into why it fails?

Unfortunately, I don't know why it is failing either. Let's have you address the review comments and then we can try and figure out what is going on with the MacOS build.

2021-05-07 17:27 UTC, patriklaurell commented
@advaitjain ready for review

2021-05-10 16:56 UTC, advaitjain approved these changes

2021-05-10 16:57 UTC, advaitjain commented
> @advaitjain ready for review. Did you find anything regarding the MacOS test?

I really do not know what is going on with the MacOS failure. @petewarden, any ideas?

2021-05-18 21:45 UTC, advaitjain commented
Can you merge master and then get this PR building again after changes from https://github.com/tensorflow/tensorflow/commit/822ddbf71817de64df9b6741e007a240e7b61c8d

That will fix the MacOS and internal CI errors.

2021-05-20 18:55 UTC, merged