Change cudnn version macros for RNN APIs
tensorflow/tensorflow pull request #47518
Opened 2021-03-03 03:22 UTC by kaixih

The new CUDNN RNN v8 APIs should be with CuDNN v8.0.2 as noted in : https://docs.nvidia.com/deeplearning/cudnn/api/index.html#release-802

fyi. @nluehr @benbarsdell

2021-03-03 03:23 UTC, kaixih commented
@sanjoy for visibility.

2021-03-03 04:53 UTC, sanjoy commented
Does this mean if we build against cuDNN 8.0.2 but run try to run with 8.0.0 we'll fail at runtime?  If yes, users might find it confusing: IIUC 8.0.x is generally forwards and backwards with 8.0.y (where x != y).  Maybe make the code conditional on cuDNN >= 8.1?

2021-03-04 06:49 UTC, sanjoy requested changes
See comment I made earlier.

2021-03-04 07:46 UTC, kaixih commented
I am actually sync'ing with our cudnn team about when these APIs were added, since I noticed that they also appeared in the v8.0.0: https://docs.nvidia.com/deeplearning/cudnn/api/index.html#release-800-preview.

2021-03-06 00:34 UTC, sanjoy approved these changes

2021-03-09 04:33 UTC, merged