[INTEL MKL] Execute small gemm's single threaded.
tensorflow/tensorflow pull request #47577
Opened 2021-03-04 22:08 UTC by Srini511

This PR introduces a simple cost metric to determine if dnnl_sgemm needs to be run with 1 thread or the whole threadpool.

Please note: Please dont merge this PR until https://github.com/tensorflow/tensorflow/pull/47543 is merged

2021-03-09 19:53 UTC, Srini511 commented
@penpornk I tried to fix the merge conflict online and it has cancelled the cla check. Can you please help resolve this?

2021-03-09 21:01 UTC, Srini511 commented
@googlebot I fixed it

2021-03-09 21:25 UTC, penpornk commented
Manually changing CLA to yes because the two commits in this PR are from the same github account which has CLA.

2021-03-20 00:12 UTC, penpornk requested changes
Thank you for the PR and I'm sorry for the delay!

2021-03-20 00:12 UTC, penpornk commented on tensorflow/core/kernels/mkl/mkl_matmul_ops_common.h
> +#define L1_SIZE 32 * 1024
Just FYI, TensorFlow can read cache sizes through Eigen, although that may come with some latency costs.
https://github.com/tensorflow/tensorflow/blob/add0a785e5af7d39cbb6801e2aefd83db39738b0/tensorflow/core/kernels/conv_grad_ops_3d.cc#L395

2021-03-20 00:12 UTC, penpornk commented on tensorflow/core/kernels/mkl/mkl_matmul_ops_common.h
> +  return ((sizeof(float) * (m * n + k * (m + n))) < L1_SIZE * 8);
Just curious, why is `L1_SiZE` multiplied by 8? If it's some magic constant, please say so in the comment (in the code).

2021-03-23 16:09 UTC, penpornk approved these changes
@Srini511 Since the branch cut is in two days, I'll just pull the PR in and make the modifications myself to save time. I'd appreciate if you could help answer the question about `L1_SIZE * 8` later when you have time though. :)

2021-03-23 16:33 UTC, Srini511 commented
@penpornk , Yes 8 is just a magic number that worked with internal workloads. I had made the changes internally and was testing them on specific models. Thanks!

2021-03-24 04:41 UTC, merged