Fix for issue #47216
tensorflow/tensorflow pull request #47667
Opened 2021-03-09 04:10 UTC by shivaditya-meduri

FIX TypeError if set the weights to the current weights via `set_weights, 
Incorporated suggestions by @qlzh727 i.e. included type checking to reduce overhead.
Simply, this change will allow users to use .weights to initialize the set_weights() method of a layer without any type error improving the versatility of keras.

2021-03-09 19:44 UTC, qlzh727 requested changes

2021-03-09 20:24 UTC, shivaditya-meduri commented on tensorflow/python/keras/engine/base_layer.py
> +          weights[index] = np.array(item)
Thank you for reviewing, I will make the changes!

2021-03-09 21:32 UTC, shivaditya-meduri commented on tensorflow/python/keras/engine/base_layer.py
> +          weights[index] = np.array(item)
Hey @qlzh727, I have made the changes as per your suggestions. Can you please take a look at it?

2021-03-10 22:04 UTC, fchollet reviewed
At line 1880, `weight = weights[weight_index]`, you should do:

```
if isinstance(weight, tf_variables.Variable):
   weight = weight.numpy()
elif not isinstance(weight, np.ndarray):
   raise ValueError(...)
```

You should also add a unit test for both the new functionality and the error message.

2021-03-11 02:00 UTC, shivaditya-meduri commented
@fchollet, Thank you for your advice, I will include the changes you suggested.

2021-03-11 22:43 UTC, fchollet commented
Please include a unit test.

2021-03-12 03:26 UTC, shivaditya-meduri commented
``"""
    >>> a = tf.keras.layers.Dense(1,
    ...   kernel_initializer=tf.constant_initializer(1.))
    >>> a_out = a(tf.convert_to_tensor([[1., 2., 3.]]))
    >>> a.get_weights()
    [array([[1.],
           [1.],
           [1.]], dtype=float32), array([0.], dtype=float32)]
    >>> b = tf.keras.layers.Dense(1,
    ...   kernel_initializer=tf.constant_initializer(2.))
    >>> b_out = b(tf.convert_to_tensor([[10., 20., 30.]]))
    >>> b.get_weights()
    [array([[2.],
           [2.],
           [2.]], dtype=float32), array([0.], dtype=float32)]
    >>> b.set_weights(a.weights)
    >>> b.get_weights()
    [array([[1.],
           [1.],
           [1.]], dtype=float32), array([0.], dtype=float32)]
    """

2021-03-12 03:33 UTC, shivaditya-meduri commented
"""
    >>> a = tf.keras.layers.Dense(1,
    ...   kernel_initializer=tf.constant_initializer(1.))
    >>> a_out = a(tf.convert_to_tensor([[1., 2., 3.]]))
    >>> a.get_weights()
    [array([[1.],
           [1.],
           [1.]], dtype=float32), array([0.], dtype=float32)]
    >>> b = tf.keras.layers.Dense(1,
    ...   kernel_initializer=tf.constant_initializer(2.))
    >>> b_out = b(tf.convert_to_tensor([[10., 20., 30.]]))
    >>> b.get_weights()
    [array([[2.],
           [2.],
           [2.]], dtype=float32), array([0.], dtype=float32)]
    >>> b.set_weights(a.weights)
    >>> b.get_weights()
    [array([[1.],
           [1.],
           [1.]], dtype=float32), array([0.], dtype=float32)]
"""
import doctest
doctest.testmod()
`

2021-03-12 03:38 UTC, shivaditya-meduri commented
@fchollet, I found this test on the tensorflow website for set_weights() method, I made modifications to the doctest to include .weights instead of get_weights() method to assign weights.

2021-08-30 18:06 UTC, qlzh727 commented
Sorry for the long wait. The Keras code base has actually been migrated to github.com/keras-team/keras. If you still would like to contribute the PR, feel free to post your change to the new repository. I am closing this PR for now.

2021-08-30 18:06 UTC, closed without merging