[Intel MKL] Make Vanilla TF and MKL-based TF use common oneDNN build
tensorflow/tensorflow pull request #47679
Opened 2021-03-09 17:20 UTC by mahmoud-abuzaina

2021-03-09 22:54 UTC, penpornk commented
@mahmoud-abuzaina Thank you for the PR!
https://github.com/tensorflow/tensorflow/pull/47543 might be reverted soon because of a nightly docker test build failure. I won't review this PR yet until we are sure the oneDNN v2.1 upgrade will stay.

2021-03-10 00:56 UTC, mahmoud-abuzaina commented
@penpornk Thank you for the update. If you can share the oneDNN-related failure details, that would help us to look at it and fix it.

2021-03-10 14:27 UTC, gbaned commented
@mahmoud-abuzaina Can you please resolve conflicts? Thanks!

2021-03-11 23:27 UTC, mahmoud-abuzaina commented
@gbaned this PR depends on https://github.com/tensorflow/tensorflow/pull/47743. I will need to resolve the conflicts anyway once that is merged.

2021-03-15 06:18 UTC, penpornk approved these changes
Thank you for the PR!

2021-03-15 17:01 UTC, penpornk requested changes
The test failures are similar to those of PR #47743 (which needed headers in `include/**/*` for `dnnl_single_threaded`).

2021-03-15 19:36 UTC, mahmoud-abuzaina commented on third_party/mkl_dnn/mkldnn_v1.BUILD
> -    ]),
Sure. Done.

2021-03-15 19:37 UTC, mahmoud-abuzaina commented
Thank you for pointing out the solution for the build error. I have made the changes.

2021-03-18 00:39 UTC, penpornk approved these changes
Thank you for the changes!

2021-03-18 03:50 UTC, gbaned commented
@mahmoud-abuzaina  Can you please resolve conflicts? Thanks!

2021-03-19 02:20 UTC, merged