bug fix when iterators stops at multiple of batch_size
tensorflow/tensorflow pull request #4777
Opened 2016-10-05 12:19 UTC by abhitopia

In contrib.learn framwork,  `Estmator.fit()` supports `x`, `y` and `batch_size` arguments where `x` and `y` could be iterators/generators. However, when iterator finishes right at the edge, after exactly integer multiple of batch_size, a run is made anyway with batch_size = 0. This causes NaN errors with following code snippet. 

[Gist Link](https://www.google.com/url?q=https%3A%2F%2Fgist.github.com%2Fabhitopia%2Fb6b60cb8bf9bab58a78b221fb3c4473b&sa=D&sntz=1&usg=AFQjCNEgS-muOb4Z0UC3SDBQ-F5KcfBMbQ) - to reproduce error.

For more information on the issue see
[Tensorflow google group discussion](https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/ZEzEa1TyYuE)

Simply skipping session.run when feed_dict is empty solves the problem.

2016-10-05 16:29 UTC, martinwicke commented
Thanks for sending a PR!

I think this is the wrong place to fix this. Instead, I think there is a bug in `StreamingDataFeeder`, `data_feeder.py` around line 510.

2016-10-05 21:03 UTC, abhitopia commented
@martinwicke  - Thanks for pointing out, please check new commits and let me know if that makes sense.

2016-10-05 21:16 UTC, martinwicke requested changes

2016-10-05 21:16 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
> +            raise StopIteration
Should this just be `raise` in to preserve the original stack?

2016-10-05 21:16 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/graph_actions.py
> +
Can you revert this completely? I think the break was there for the 80 character limit.

2016-10-05 21:16 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
> +          if i==0:
Please add spaces around `==`

2016-10-05 21:16 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
> +          else:
You don't need the `else:` (since `raise` never returns), and I would find it more legible without.

2016-10-05 21:16 UTC, martinwicke commented
This is the right change. Just a few small comments.

2016-10-05 21:29 UTC, abhitopia commented on tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
> +          else:
@martinwicke - done

2016-10-05 21:29 UTC, abhitopia commented on tensorflow/contrib/learn/python/learn/graph_actions.py
> +
@martinwicke - done.

2016-10-05 21:32 UTC, abhitopia commented on tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
> +            raise StopIteration
@martinwicke - Not sure if I understand your question very well. I presume StopIteration is automatically picked by `super_session.should_stop()` in graph_action.py line 287

2016-10-05 22:42 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
> +            raise StopIteration
I meant, omit the `StopIteration`. `raise StopIteration` will create a new `StopIteration` instance with a stack trace to line 511, while the original `StopIteration is discarded. If you instead simply write `if i == 0: raise`, you will reuse the original exception, which contains the full stack trace.

It doesn't matter much in this case (not much useful information in a `StopIteration` anyway, and it'll be caught shortly by ourselves), but it's better to preserve it anyway.

2016-10-06 08:34 UTC, abhitopia commented on tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py
> +            raise StopIteration
@martinwicke - Agreed. Omitted new `StopIteration` now. Thanks for explaining.

2016-10-06 21:39 UTC, martinwicke commented
Jenkins, test this please

2016-10-06 23:28 UTC, martinwicke approved these changes

2016-10-06 23:38 UTC, merged