fix datatypes in cwise and gather ops
tensorflow/tensorflow pull request #47835
Opened 2021-03-16 05:12 UTC by kushanam

cwise_ops_gpu_common and gather_functor kernels deduce loop variables from input template datatype. they cause overflows  and consequently result in Illegal CUDA memory access issues. Sample code to reproduce is added below. 

`import tensorflow as tf
tf.compat.v1.disable_eager_execution()
​
n = 13417677  # 13417676 works
h = 160
x = tf.compat.v1.get_variable('x', [n, h])
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())`

2021-03-16 06:56 UTC, sanjoy commented
Have you tested the performance impact of these changes (especially the changes to the cwise ops, I'm less worried about the changes to gather)?

CC @sherhut as FYI

2021-03-17 20:33 UTC, kushanam commented
> Have you tested the performance impact of these changes (especially the changes to the cwise ops, I'm less worried about the changes to gather)?
> 
> CC @sherhut as FYI

For what I was able to test, there was no effect for the LEFT and RIGHT performance. I used the random initializer (which calls mul, add, etc, internally ending up in cwise ops) over several session runs and actually `To64Bit` was 2-3% faster, (that might not be very meaningful as the variance was high and the call was in the order of few microseconds)

2021-03-18 03:45 UTC, sanjoy commented
> > Have you tested the performance impact of these changes (especially the changes to the cwise ops, I'm less worried about the changes to gather)?
> > CC @sherhut as FYI
> 
> For what I was able to test, there was no effect for the LEFT and RIGHT performance. I used the random initializer (which calls mul, add, etc, internally ending up in cwise ops) over several session runs and actually `To64Bit` was 2-3% faster, (that might not be very meaningful as the variance was high and the call was in the order of few microseconds)

I see, thanks.  I'd still prefer merging this after the branch cut for TF 2.5 (currently planned for March 25) to reduce the risk of a subtle regression & cherry picks.  If that's OK with you can you please reply on this PR after March 25?

2021-03-18 03:54 UTC, sanjoy requested changes
Requesting changes to get this off my queue, but please ping back after the TF 2.5 branch cut as stated.

2021-03-18 19:27 UTC, kushanam commented
> > > Have you tested the performance impact of these changes (especially the changes to the cwise ops, I'm less worried about the changes to gather)?
> > > CC @sherhut as FYI
> > 
> > 
> > For what I was able to test, there was no effect for the LEFT and RIGHT performance. I used the random initializer (which calls mul, add, etc, internally ending up in cwise ops) over several session runs and actually `To64Bit` was 2-3% faster, (that might not be very meaningful as the variance was high and the call was in the order of few microseconds)
> 
> I see, thanks. I'd still prefer merging this after the branch cut for TF 2.5 (currently planned for March 25) to reduce the risk of a subtle regression & cherry picks. If that's OK with you can you please reply on this PR after March 25?

Sure, will remind you then.

2021-04-21 19:00 UTC, gbaned commented
@kushanam Any update on this PR? Please. Thanks!

2021-04-21 19:08 UTC, kushanam commented
> @kushanam Any update on this PR? Please. Thanks!

@gbaned this doesn't wait for an action from me. @sanjoy proposed to postpone it to 2.6 and hence is the change request.

2021-05-18 09:21 UTC, akuegel commented
> > Have you tested the performance impact of these changes (especially the changes to the cwise ops, I'm less worried about the changes to gather)?
> > CC @sherhut as FYI
> 
> For what I was able to test, there was no effect for the LEFT and RIGHT performance. I used the random initializer (which calls mul, add, etc, internally ending up in cwise ops) over several session runs and actually `To64Bit` was 2-3% faster, (that might not be very meaningful as the variance was high and the call was in the order of few microseconds)

One thing to consider here is that we are switching away from the Eigen kernels for cwise ops (and have already done so for many kernels, including mul and add). It is possible that when you tested, you were already using the MLIR generated kernels, not the Eigen kernels (if you were testing with the latest changes available on March 16th).
Can you please try a kernel that is definitely using Eigen, e.g. from the cwise ops, this would be igamma, or explicitly disable MLIR generated kernels by passing the build flag --no=//tensorflow/core/kernels/mlir_generated:enable_gpu ?

2021-05-18 11:25 UTC, akuegel commented
I did now some performance benchmarking on a index-heavy kernel, namely:
add with shapes
lhs_shape = 10, 1, 10, 10, 100
rhs_shape = 1, 10, 10, 1, 100
So lots of broadcasting involved -> many index computations.
For Eigen, with 64 bits it takes 1.9 times longer than before, going from 163 microseconds to 314 microseconds
For the MLIR generated kernel, with 64 bits it takes about 1.5 times longer than before, going from 17 microseconds to 26 microseconds.

2021-05-18 18:42 UTC, kushanam commented
> I did now some performance benchmarking on a index-heavy kernel, namely:
> add with shapes
> lhs_shape = 10, 1, 10, 10, 100
> rhs_shape = 1, 10, 10, 1, 100
> So lots of broadcasting involved -> many index computations.
> For Eigen, with 64 bits it takes 1.9 times longer than before, going from 163 microseconds to 314 microseconds
> For the MLIR generated kernel, with 64 bits it takes about 1.5 times longer than before, going from 17 microseconds to 26 microseconds.

@akuegel and @sanjoy  Thanks for the benchmarks, I could repro the results for the cwise ops. Any suggestions on how to mitigate the issue then? Unless the datatypes change, randomizing big embedding would not fit in int32.

2021-05-31 11:20 UTC, akuegel commented
Unfortunately I don't have a suggestion on how to mitigate the issue. Given that the cases where it becomes slower are still faster with the MLIR generated kernels than with the Eigen kernels, maybe we can accept the slowdown?
@sanjoy what do you think?

2021-06-03 20:59 UTC, sanjoy commented
@akuegel we could also have the kernel generator JIT compile a kernel for 64bit indices if needed.

2021-06-25 16:55 UTC, gbaned commented
@akuegel, @sanjoy Any update on this PR? Please. Thanks!

2021-06-28 08:40 UTC, akuegel commented
> @akuegel, @sanjoy Any update on this PR? Please. Thanks!

I think the pull request as-is can be closed. It tries to adjust code that we are mostly not using anymore.
The index type choice for the MLIR generated kernels is hard-coded here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tools/kernel_gen/transforms/kernel_lowering_passes.cc#L56
JIT compiling is planned (I think) for Q3, then it might be possible to fix this for MLIR generated kernels.

2021-08-25 22:31 UTC, pkanwar23 submitted a review, later dismissed

2021-08-27 08:08 UTC, closed without merging