Lazy load optional modules to speedup pip package import
tensorflow/tensorflow pull request #47833
Opened 2021-03-16 00:13 UTC by lgeiger

This PR lazy loads optional external Python modules to speedup initial import times of the TF pip package.

These changes speedup initial import by roughly **24%**:

modules | percentage of TF import
---|---
kubernetes | 14.5 %
pandas | 6.9 %
scipy | 2.6 %

This partially addresses #37729, but import times are still quite slow. A large chunk is spent importing the `tf.compat` which I don't think is used a lot by the average user, so it would be great if this could be lazy loaded as well in the future.

/cc @mihaimaruseac

2021-03-16 00:23 UTC, lgeiger commented on tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver.py
> -
It is not possible to use the `LazyLoader` class here since we rely on the import throwing immediately to set `_KUBERNETES_API_CLIENT_INSTALLED`.

2021-03-16 23:57 UTC, frankchn approved these changes

2021-03-16 23:59 UTC, frankchn requested changes
You may also wish to catch the `ModuleNotFoundError` as well:

```
[31m[1mFAILED: [0m//tensorflow/python/distribute/cluster_resolver:kubernetes_cluster_resolver_py_test (Summary)
      /home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver_py_test/test.log
      /home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver_py_test/test_attempts/attempt_1.log
      /home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver_py_test/test_attempts/attempt_2.log
[32mINFO: [0mFrom Testing //tensorflow/python/distribute/cluster_resolver:kubernetes_cluster_resolver_py_test:
==================== Test output for //tensorflow/python/distribute/cluster_resolver:kubernetes_cluster_resolver_py_test:
Running tests under Python 3.6.13: /usr/bin/python3
[ RUN      ] KubernetesClusterResolverTest.testGetMasterWithOverrideParameters
INFO:tensorflow:time(__main__.KubernetesClusterResolverTest.testGetMasterWithOverrideParameters): 0.0s
I0316 02:55:24.963223 139702237902592 test_util.py:2083] time(__main__.KubernetesClusterResolverTest.testGetMasterWithOverrideParameters): 0.0s
[  FAILED  ] KubernetesClusterResolverTest.testGetMasterWithOverrideParameters
[ RUN      ] KubernetesClusterResolverTest.testMultiplePodSelectorsAndWorkers
INFO:tensorflow:time(__main__.KubernetesClusterResolverTest.testMultiplePodSelectorsAndWorkers): 0.01s
I0316 02:55:24.972226 139702237902592 test_util.py:2083] time(__main__.KubernetesClusterResolverTest.testMultiplePodSelectorsAndWorkers): 0.01s
[  FAILED  ] KubernetesClusterResolverTest.testMultiplePodSelectorsAndWorkers
[ RUN      ] KubernetesClusterResolverTest.testNonRunningPod
INFO:tensorflow:time(__main__.KubernetesClusterResolverTest.testNonRunningPod): 0.0s
I0316 02:55:24.978221 139702237902592 test_util.py:2083] time(__main__.KubernetesClusterResolverTest.testNonRunningPod): 0.0s
[  FAILED  ] KubernetesClusterResolverTest.testNonRunningPod
[ RUN      ] KubernetesClusterResolverTest.testSingleItemSuccessfulRetrieval
INFO:tensorflow:time(__main__.KubernetesClusterResolverTest.testSingleItemSuccessfulRetrieval): 0.0s
I0316 02:55:24.983499 139702237902592 test_util.py:2083] time(__main__.KubernetesClusterResolverTest.testSingleItemSuccessfulRetrieval): 0.0s
[  FAILED  ] KubernetesClusterResolverTest.testSingleItemSuccessfulRetrieval
[ RUN      ] KubernetesClusterResolverTest.testSuccessfulRetrievalWithSort
INFO:tensorflow:time(__main__.KubernetesClusterResolverTest.testSuccessfulRetrievalWithSort): 0.0s
I0316 02:55:24.989016 139702237902592 test_util.py:2083] time(__main__.KubernetesClusterResolverTest.testSuccessfulRetrievalWithSort): 0.0s
[  FAILED  ] KubernetesClusterResolverTest.testSuccessfulRetrievalWithSort
[ RUN      ] KubernetesClusterResolverTest.test_session
[  SKIPPED ] KubernetesClusterResolverTest.test_session
======================================================================
ERROR: testGetMasterWithOverrideParameters (__main__.KubernetesClusterResolverTest)
testGetMasterWithOverrideParameters (__main__.KubernetesClusterResolverTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver_py_test.runfiles/org_tensorflow/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver_test.py", line 125, in testGetMasterWithOverrideParameters
    self.assertEqual(cluster_resolver.master(), 'grpc://10.1.2.3:8470')
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver_py_test.runfiles/org_tensorflow/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver.py", line 139, in master
    self.cluster_spec().task_address(task_type, task_id),
  File "/home/tensorflow_ci_jenkins/workspace/workspace/workspace/tensorflow-mkl-linux-cpu-pr/bazel-ci_build-cache/.cache/bazel/_bazel_tensorflow_ci_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver_py_test.runfiles/org_tensorflow/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver.py", line 157, in cluster_spec
    from kubernetes import client as k8sclient  # pylint: disable=g-import-not-at-top
ModuleNotFoundError: No module named 'kubernetes'
```

2021-03-17 00:13 UTC, lgeiger commented
Good catch, I fixed it in 818acdd9416ccbde08d2330dbe3f4070c2b92ef9

2021-03-17 06:26 UTC, frankchn approved these changes

2021-03-17 09:12 UTC, lgeiger commented
@frankchn Thanks for approving. I fixed the pylint error in the latest commit, sorry about that.

2021-03-17 17:00 UTC, frankchn approved these changes

2021-03-19 15:40 UTC, merged

2021-03-19 18:44 UTC, lgeiger commented
This PR was rolled back in 9f95b52fe19eb4738043482ddd24f0ddee334065.

@gbaned @frankchn Could you give some context of why this was the case?

2021-03-19 20:30 UTC, frankchn commented
Hi @lgeiger -- an internal test failed causing an auto-rollback. I am investigating this issue now.

2021-03-22 17:04 UTC, frankchn commented
Hi @lgeiger, we have resolved the internal issue and the change has been re-committed as 5a737ab. Thanks!

2021-03-22 17:15 UTC, lgeiger commented
Awesome, thanks for taking care of re-commiting.