scope_alloctor bug fix with One binary support for v2.5
tensorflow/tensorflow pull request #47993
Opened 2021-03-22 23:03 UTC by nammbash

Patch for scope_allocator Fix that worked in TF2.3 and TF2.4.1. 
Modifying the same patch or TF2.5 / Master with some attention to one binary support here.

2021-03-22 23:06 UTC, nammbash commented
@penpornk Scope_allocator bug fix for v2.5

2021-03-22 23:17 UTC, penpornk commented
@nammbash Thank you for the PR!

Context for @ezhulenev : This is a TF-oneDNN fix for issue https://github.com/tensorflow/tensorflow/issues/34213#issuecomment-783857373

2021-03-23 03:19 UTC, ezhulenev approved these changes

2021-03-23 06:18 UTC, penpornk requested changes
This PR failed the [Ubuntu Sanity](https://source.cloud.google.com/results/invocations/fd97539c-57e0-48e6-81ec-dbd7d1330dc5/log) test.
```
FAIL: buildifier found errors and/or warnings in above BUILD files.
buildifier suggested the following changes:
tensorflow/core/grappler/optimizers/BUILD:
2c2
< load("//tensorflow:tensorflow.bzl", "tf_cc_test", "tf_cc_test_mkl", "tf_copts", "tf_cuda_cc_test","tf_kernel_library")
---
> load("//tensorflow:tensorflow.bzl", "tf_cc_test", "tf_cc_test_mkl", "tf_copts", "tf_cuda_cc_test", "tf_kernel_library")
```
Could you please fix the formatting?

2021-03-23 06:18 UTC, penpornk commented on tensorflow/core/grappler/optimizers/BUILD
> +load("//tensorflow:tensorflow.bzl", "tf_cc_test", "tf_cc_test_mkl", "tf_copts", "tf_cuda_cc_test","tf_kernel_library")
```suggestion
load("//tensorflow:tensorflow.bzl", "tf_cc_test", "tf_cc_test_mkl", "tf_copts", "tf_cuda_cc_test", "tf_kernel_library")
```

2021-03-23 15:26 UTC, nammbash commented
@penpornk Accepted your suggestion. Thank you. 
 We run clang internally on CPP files! Can we run buildifier BUILD file checks?

2021-03-23 15:46 UTC, penpornk approved these changes
Thank you for the quick fix! 
Yes, in the future, it'd be great if you could also run buildifier. It's part of the `Ubuntu Sanity` check. :)

2021-03-24 00:11 UTC, merged