Add GPU support for sparse reorder
tensorflow/tensorflow pull request #48028
Opened 2021-03-23 22:10 UTC by kaixih

This PR adds GPU support to `tf.sparse.reorder`.

cc. @nluehr @benbarsdell

2021-04-02 21:25 UTC, kaixih commented
@sanjoy This PR is related to the sparse_to_dense op. Can you help review? Thanks.

2021-04-03 03:38 UTC, sanjoy requested changes

2021-04-03 03:38 UTC, sanjoy commented on tensorflow/core/kernels/sparse_reorder_op_gpu.cu.cc
> +      auto permutes_data = permutes_tensor.template flat<int64>().data();
Maybe s/permutes/permutation/ ?

2021-04-05 18:29 UTC, sanjoy requested changes

2021-04-05 18:29 UTC, sanjoy commented on tensorflow/python/kernel_tests/sparse_reorder_op_test.py
> +    output_val = sess.run(sp_output, {sp_input: input_val})
Where is `sess` defined?

2021-04-05 18:29 UTC, sanjoy commented on tensorflow/core/kernels/sparse_reorder_op_gpu.cu.cc
> +    if (num_elems <= 0) return;
Why not `num_elems == 0`?

2021-04-07 21:18 UTC, kaixih commented on tensorflow/python/kernel_tests/sparse_reorder_op_test.py
> +    output_val = sess.run(sp_output, {sp_input: input_val})
Done.

2021-04-07 21:18 UTC, kaixih commented on tensorflow/core/kernels/sparse_reorder_op_gpu.cu.cc
> +    if (num_elems <= 0) return;
Done.

2021-04-07 22:21 UTC, sanjoy approved these changes

2021-04-07 23:41 UTC, merged