[GO] Memory leak when loading in a string source in encodeTensorWithSlices
tensorflow/tensorflow pull request #48051
Opened 2021-03-24 20:09 UTC by michaelboke

I noticed my GO application memory usage was growing very quickly when I was feeding in tensor with my webcam's data. In a couple of minutes my app grows about a few gigs per minute and my system started to swap memory.Finally the application terminated with OOM.

I could narrow down the origin of the memory leak to:
```go
tensor, err := tf.NewTensor(string(img))
```

The problem is not on the GO side but in the C++ side where a string buffer is created and not released from memory.

In the specific function `encodeTensorWithSlices`. There is a TF_TString being allocated and initialized. But is never deallocated. I created a new macro for it to deallocate when the used buffer is finalized/garbage collected.

I'm not 100% confident that this is the right object to register the finalizer on. If someone could check and explain to me if this is correct.

2021-06-25 20:44 UTC, gharibian commented
A finalizer for strings is already set on lines 101-107.  Can you provide a working example where that finalizer isn't being called to clear out a string Tensor?

2021-07-07 18:51 UTC, gbaned commented
@michaelboke  Can you please check @gharibian's comments and keep us posted ? Thanks!

2021-07-07 21:19 UTC, michaelboke commented
@gharibian I don't think that finalizer on line 101-107 is finalizing the temporary C.TF_TString on line 503.
Because the contents of that string are later being copied to the buffer on line 509. That newly allocated TF_TString on line 503 is nowhere finalized. That is why I created a finalizer for that. 

What do you think?...

2021-07-16 14:48 UTC, gbaned commented
@gharibian  Can you please assist on above comments from @michaelboke. Thanks!

2021-10-13 16:57 UTC, mihaimaruseac approved these changes

2021-10-30 17:38 UTC, mihaimaruseac approved these changes

2021-11-03 13:08 UTC, wamuir commented
I believe this was fixed by #49925

2021-11-10 05:16 UTC, mihaimaruseac requested changes
Can you make sure `bazel test //tensorflow/go:tensorflow_test` passes?

2021-11-12 12:25 UTC, gbaned commented
@michaelboke Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

2021-12-28 16:21 UTC, gbaned commented
@michaelboke Any update on this PR? Please. Thanks!

2022-02-09 09:26 UTC, gbaned commented
@michaelboke Any update on this PR? Please. Thanks!

2022-03-29 11:08 UTC, gbaned commented
@michaelboke Any update on this PR? Please. Thanks!

2022-04-19 08:53 UTC, gbaned commented
@michaelboke Any update on this PR? Please. Thanks!

2022-05-27 14:51 UTC, gbaned commented
@michaelboke Any update on this PR? Please. Thank you!

2022-06-03 13:10 UTC, closed without merging