Updated xnnpack to commit f7baa13a4a78fbaf7dd1664b5eb692b47512889a for cmake build.
tensorflow/tensorflow pull request #48097
Opened 2021-03-26 03:13 UTC by JerryShih

Update for fp16 downloading path.

2021-03-26 03:16 UTC, JerryShih commented
I don't know if we need to update other dependent library too.
The bazel build updating also changes the pthreadpool and cpu-info.
https://github.com/tensorflow/tensorflow/commit/8060cb22de7115f4cc3e140a057ee7412ea3bbca

2021-03-26 04:12 UTC, abattery commented
@multiverse-tf could you review this PR?

2021-03-29 02:54 UTC, multiverse-tf approved these changes

2021-03-31 03:10 UTC, multiverse-tf commented on tensorflow/lite/tools/cmake/modules/xnnpack.cmake
>    SOURCE_DIR "${CMAKE_BINARY_DIR}/xnnpack"
This file just got updated in https://github.com/tensorflow/tensorflow/commit/0834c9410bb83e967973ef74a53ceeb54c12d339 w/ a more recent XNNPACK git tag. @JerryShih, could you update your branch to the latest master? Thx!

2021-03-31 03:13 UTC, multiverse-tf requested changes
Need to resolve the conflict.

2021-03-31 03:31 UTC, JerryShih commented
@multiverse-tf
Do you mean use the latest XNNPACK commit or just rebase this pr?
If just rebase this pr, only the FP16 needs to be upgraded in this pr.

2021-03-31 03:55 UTC, multiverse-tf approved these changes

2021-03-31 03:56 UTC, multiverse-tf commented
> @multiverse-tf
> Do you mean use the latest XNNPACK commit or just rebase this pr?
> If just rebase this pr, only the FP16 needs to be upgraded in this pr.

Just rebase. Thx for the quick response!

2021-03-31 04:09 UTC, JerryShih commented
@multiverse-tf 
Do you close this pr accidentally or this pr is useless anymore?

2021-03-31 04:12 UTC, multiverse-tf commented
> @multiverse-tf
> Do you close this pr accidentally or this pr is useless anymore?

Sorry, I accidentally closed the PR :-(. Let me reopen it.

2021-03-31 15:59 UTC, merged