[tf.data] graduate experimental `bucket_by_sequence_length` API to tf.data
tensorflow/tensorflow pull request #48110
Opened 2021-03-26 16:48 UTC by kvignesh1420

UPDATED: This PR graduates the `tf.data.experimental.bucket_by_sequence_length` API into `tf.data.bucket_by_sequence_length` by making the following changes:

- [x] Adds "data.get_single_element" into the `tf_export` decorator of the current implementation and deprecates the experimental endpoint.
- [x] Updates example in documentation with new API.

2021-03-29 15:04 UTC, jsimsa approved these changes

2021-03-29 15:04 UTC, jsimsa commented
You will need to regenerate golden API files.

2021-03-29 17:04 UTC, kvignesh1420 commented
Sure, will update the PR.

2021-03-29 20:02 UTC, kvignesh1420 commented
@jsimsa the `.pbtxt` files have been updated!

2021-03-29 20:19 UTC, jsimsa approved these changes

2021-03-30 18:02 UTC, jsimsa requested changes
Actually, on a further thought, it would be better to surface this API as `tf.data.Dataset.bucket_by_sequence_length` so that instead of having to do:

```
dataset = dataset.apply(tf.data.bucket_by_sequence_length(...))
```

one could simply do:

```
dataset = dataset.bucket_by_sequence_length(...)
```

This could be implemented as follows:

```
class Dataset()
...
  def bucket_by_sequence_length(...)
  """ documentation here """
  return self.apply(grouping.bucket_by_sequence_length(...))
```

2021-03-30 18:51 UTC, kvignesh1420 commented
will take a look.

2021-03-30 19:57 UTC, kvignesh1420 commented
@jsimsa so to expose the API as `tf.data.Dataset.bucket_by_sequence_length` the `tensorflow/python/data/ops/dataset_ops.py` has to import `tensorflow/python/data/experimental/ops/grouping.py`. However, this would lead to a cyclic import. I can try with a `LazyLoader` but wouldn't it be messy?

2021-03-30 20:32 UTC, jsimsa commented
> @jsimsa so to expose the API as `tf.data.Dataset.bucket_by_sequence_length` the `tensorflow/python/data/ops/dataset_ops.py` has to import `tensorflow/python/data/experimental/ops/grouping.py`. However, this would lead to a cyclic import. I can try with a `LazyLoader` but, wouldn't it be messy?

I see. You can avoid the cyclic import by creating BucketBySequenceDataset in dataset_ops.py and moving the implementation there.. See `UnbatchDataset` and `unbatch` in dataset_ops.py and experimental/batching.py for an example how to do this.

2021-03-31 12:01 UTC, kvignesh1420 commented
@jsimsa the `bucket_by_sequence_length` API is having a dependency on `group_by_window` API for it's functionality. Lets graduate the `group_by_window` into `tf.data.Data.group_by_window` first so that graduating to `tf.data.Data.bucket_by_sequence_length` becomes straightforward.

2021-03-31 17:10 UTC, jsimsa commented
> @jsimsa the `bucket_by_sequence_length` API is having a dependency on `group_by_window` API for it's functionality. Lets graduate the `group_by_window` into `tf.data.Data.group_by_window` first so that graduating to `tf.data.Data.bucket_by_sequence_length` becomes straightforward.

sounds good

2021-04-21 06:38 UTC, kvignesh1420 commented
@jsimsa made the changes. Please take a look.

2021-04-21 15:13 UTC, jsimsa approved these changes

2021-04-27 17:48 UTC, merged