Update _index.yaml
tensorflow/tensorflow pull request #48215
Opened 2021-03-31 10:57 UTC by Saduf2019

Updated broken-link to mlir repo.

Fixes github issue #48189

2021-04-01 13:27 UTC, bhack requested changes
Can you fix also:
```
tensorflow/compiler/mlir/tosa/BUILD:#   https://github.com/llvm/llvm-project/blob/master/mlir/docs/Dialects/TOSA.md
tensorflow/compiler/mlir/lite/README.md:# The new [MLIR](https://github.com/llvm/llvm-project/tree/master/mlir) based
```

2021-04-06 11:22 UTC, Saduf2019 commented
@bhack 
Thank you for the suggestion, the mentioned two files have been updated.

2021-04-06 12:50 UTC, bhack approved these changes

2021-04-06 23:44 UTC, rthadur approved these changes

2021-04-07 17:56 UTC, merged