Fix a bug about opengles
tensorflow/tensorflow pull request #48270
Opened 2021-04-02 07:54 UTC by flyinskyin2013

### Notes:
As "include <EGL/egl.h>" import a macro 'Status' from there:</br>
&nbsp; In file EGL/egl.h: #include <EGL/eglplatform.h></br>
&nbsp; In file EGL/eglplatform.h: #include <X11/Xlib.h></br>
&nbsp; In file X11/Xlib.h(line:83): #define Status int</br>

### Why:
After we import it, if you define a var like 'absl::Status TestVar', the compiler will precompile it to 'absl::int TestVar'. It is a disaster.
we should undef it to avoid this disaster.

### Dependent Issues
https://github.com/tensorflow/tensorflow/issues/46650
https://github.com/google/mediapipe/issues/200

2021-04-02 08:58 UTC, flyinskyin2013 commented
> I signed it!

2021-04-02 09:00 UTC, flyinskyin2013 commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftensorflow%2Fpull%2F48270) for more info**.

I signed it!

2021-04-12 16:11 UTC, impjdi requested changes
You are pulling in X11 headers which have #define Status int.  rather than doing this, you should exclude those headers with preprocessor macros.

For anyone who is reviewing this PR, please do NOT approve.

2021-04-13 06:44 UTC, flyinskyin2013 commented
> You are pulling in X11 headers which have #define Status int. rather than doing this, you should exclude those headers with preprocessor macros.
> 
> For anyone who is reviewing this PR, please do NOT approve.

I can't understand it. 

How can I exclude those headers with preprocessor macros ? Could you please give me an example? Thanks.

You mean like this ?
`#ifdef  X11_XXXXXX`
`#include <X11/Xlib.h>`
`#endif `

The 'include <EGL/egl.h>' is written by file like 'portable_gl31.h' in tflite. The 'EGL/...' and 'X11/...' are a third-part open source lib. 

In my mind, there are three solutions :
- 1 undef macro 'Status' in 'tflite'.
- 2 undef macro 'Status' in 'libgles*-mesa'.
- 3 undef macro 'Status' in 'libx11-dev'.

2021-04-13 17:53 UTC, impjdi commented
You might need things like `-DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11` to make it work.  You may have to dig deeper into your version of X11 headers to find out the exact name of the variable though.

2021-04-14 02:12 UTC, flyinskyin2013 commented
OK! It's my fault. I will close this PR and delete it. 

The 'MESA_EGL_NO_X11_HEADERS' and 'EGL_NO_X11' isn't worked for me, because the 'eglplatform.h' is supplied by my supplier, it isn't supplied by libegl1-mesa-dev. The supplier modifies it.

like this:
`> dpkg-query -S eglplatform.h`
`libmali-rk-dev:arm64: /usr/include/EGL/eglplatform.h`
`libmali-rk-dev:arm64: /usr/include/eglplatform.h`

`apt-cache madison libmali-rk-dev`
`libmali-rk-dev |      1.7-1 | http://wiki.t-firefly.com/firefly-rk3399-repo bionic/main arm64 Packages`

2021-04-14 02:12 UTC, closed without merging