updates to einsum
tensorflow/tensorflow pull request #4837
Opened 2016-10-08 00:52 UTC by nikhilmishra000

Resolving https://github.com/tensorflow/tensorflow/issues/4722:
-- Fix bug where output indices are expected to be in alphabetical order
-- Add to docstring

2016-10-14 15:32 UTC, martinwicke requested changes

2016-10-14 15:32 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops.py
> +  -- ellipses (subscripts like 'ij...,jk...->ik...')
Can you turn those apostrophes into backticks? Then it'll render nicely as code. Also, please put `numpy.einsum` into backticks. All docstrings get rendered as markdown.

2016-10-14 15:32 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops.py
> +    "Unknown ouput axes: %s" % missing_idx
Can you make this into an exception (ValueError is fine), and add it to the docstring?

2016-10-14 15:38 UTC, nikhilmishra000 commented on tensorflow/python/ops/special_math_ops.py
> +    "Unknown ouput axes: %s" % missing_idx
@martinwicke should I do the same for all of the other assertions too?

2016-10-15 00:40 UTC, martinwicke reviewed
Sorry, missed some things earlier.

2016-10-15 00:40 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops.py
> +
Can you add an "Args:" section here, and after the args section, add a "Returns:" section. See other op docstrings for examples.

2016-10-15 00:40 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops.py
> +  Raises a ValueError if:
Can you reformat this to
```
Raises:
  ValueError: <all your text, reindented to flow after ValueError>
```

2016-10-15 00:40 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops_test.py
>          "An exception should have been thrown."
Can you rewrite this to use self.assertRaises?

2016-10-15 00:40 UTC, martinwicke commented on tensorflow/python/ops/special_math_ops_test.py
This too

2016-10-15 03:01 UTC, jart commented
Einsum is not a trivial abstraction. Numpy has 900 lines of test code for einsum ([test_einsum.py](https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_einsum.py)) and 100 lines of Pydoc tests ([einsumfunc.py](https://github.com/numpy/numpy/blob/master/numpy/core/einsumfunc.py)). Ideally we would just use their test cases to show that the behavior is identical. Especially if we document the function as being "like numpy.einsum."

Thank you for the work you put into bringing einsum to TensorFlow @nikhilmishra000 and for being responsive in addressing the concerns in #4722. I just can't help but wonder if this function is more appropriate for the contrib package, since it isn't on par with numpy in terms of functionality and test comprehensiveness. What do you think @martinwicke?

See also: #4886

2016-10-16 03:11 UTC, martinwicke commented
I think it is fine in core. There's no experimentation with the interface needed, which is usually the concern. If its functionality is not a complete mirror of numpy's we have to document the differences clearly. 

In this case, it should be noted that transpose doesn't work, are there other differences that are not documented yet?

2016-10-16 07:40 UTC, nikhilmishra000 commented
The docstring has been updated, and I have added some more tests.

Following this PR, I think the outstanding differences from numpy will be that:
* Ellipses will not be recognized. This shouldn't be too hard to implement, but I don't know that I have the bandwidth to get it done in the near future.
* Subscripts where an axis appears more than once (example: `ii->i` computes the trace of a matrix). Adding support for this seems a little bit more involved.

Exceptions are raised for both of these cases.

2016-10-16 07:48 UTC, martinwicke approved these changes

2016-10-16 07:48 UTC, martinwicke commented
Jenkins, test this please.

2016-10-17 07:25 UTC, nikhilmishra000 commented
The previous failure in python3 was my fault (I didn't realize that passing a comparator to `sorted()` had been disallowed). Not too sure what happened on linux gpu, but it seems unrelated?

2016-10-17 15:40 UTC, martinwicke commented
Jenkins, test this please!

2016-10-19 02:24 UTC, eaplatanios commented on tensorflow/python/ops/special_math_ops.py
>               for dim in tensor.get_shape().as_list()]
I would like to propose one more fix. I think this should be changed from:

```
shapes = [[dim if dim else -1
           for dim in tensor.get_shape().as_list()]
           for tensor in inputs]
```

to:

```
shapes = [[dim if dim is not None else -1
           for dim in array_ops.unpack(array_ops.shape(tensor))]
           for tensor in inputs]
```

in order to allow for dynamic tensor shapes. I run into an issue while using `tf.einsum` and this change fixed it for me.

2016-10-19 06:32 UTC, merged

2016-10-21 17:02 UTC, yunita15 reviewed
Good

2016-10-24 21:36 UTC, eaplatanios commented on tensorflow/python/ops/special_math_ops.py
>               for dim in tensor.get_shape().as_list()]
Sounds good! I made PR #5174 but without any test coverage. I have a paper deadline approaching and I'm not sure about your test conventions, so I thought I'd leave it there for now. This change alone seems to be working fine for me, although I haven't tried using it with any edge cases.