[Graph C API] Updating warning messages && Remove GrapplerItemMap
tensorflow/tensorflow pull request #48385
Opened 2021-04-08 00:48 UTC by ShengYang1

This PR is a patch for [Modular TensorFlow Graph C API](https://github.com/tensorflow/community/blob/master/rfcs/20201027-modular-tensorflow-graph-c-api.md). It includes 2 parts:
1. Updating warning messages. It continues https://github.com/tensorflow/tensorflow/pull/47969 which was reverted.
2. Removing global GrapplerItemMap. Optimizer API has changed from `void (*optimize_func)(void*, TF_Buffer*, TF_Buffer*, TF_Status*);` to `void (*optimize_func)(void*, const TF_Buffer*, const TF_GrapplerItem*, TF_Buffer*, TF_Status*);`

2021-04-08 00:49 UTC, ShengYang1 commented
Hi @penpornk @ezhulenev, please help to have a review. Thanks!

2021-04-08 01:16 UTC, penpornk requested changes
Thank you for the PR! Could you please split them into two separate PRs? That way if one thing failed a test, the other wouldn't get reverted too. It would make it easier to debug as well.

The warning message PR got reverted because it broke an internal test. So if we simply bring it back it will get reverted again. I'll have to find out why first.

2021-04-08 01:25 UTC, ShengYang1 commented
OK. Now this PR is only targeting removing global GrapplerItemMap.

2021-04-08 01:36 UTC, penpornk approved these changes
Thank you again for the PR! :)

2021-04-08 19:35 UTC, merged

2021-04-08 19:41 UTC, penpornk commented
@kulinseth FYI. We removed GrapplerItem map and just passed the GrapplerItem directly to the optimize function.

2021-04-08 23:22 UTC, kulinseth commented
> @kulinseth FYI. We removed GrapplerItem map and just passed the GrapplerItem directly to the optimize function.

Thanks! for letting us know @penpornk

2021-05-17 20:59 UTC, kulinseth commented
Hi @ShengYang1 , thanks for the PR.  Looks like this wasn't part of the v2.5 release. 
I am curious why this didn't make it to 2.5 release? Thanks.

Kulin

2021-05-17 21:54 UTC, penpornk commented
That was my fault. I got feedback to remove the map about a week before the branch cut, but I was worried it could complicate our already tight PluggableDevice-related PR merge/test schedule. So I waited until after 2.5 branch cut. And since cherrypick was technically for bug fixes, I didn't cherrypick it in. Sorry for making diverge code paths! :'(

2021-05-17 22:38 UTC, kulinseth commented
> That was my fault. I got feedback to remove the map about a week before the branch cut, but I was worried it could complicate our already tight PluggableDevice-related PR merge/test schedule. So I waited until after 2.5 branch cut. And since cherrypick was technically for bug fixes, I didn't cherrypick it in. Sorry for making diverge code paths! :'(

No issues, thanks for the clarification @penpornk . The only reason I brought up was that since there is an API change, it won't be a breaking change for v2.5 but for TF master we would at somepoint adopt this new change.