Fix few waves
tensorflow/tensorflow pull request #48383
Opened 2021-04-07 23:47 UTC by nouiz

@timshen91 

This re-enable what was meant to be enabled by https://github.com/tensorflow/tensorflow/pull/45343

I added extra tests to help make sure it continue to work.

2021-04-13 00:37 UTC, timshen91 approved these changes

2021-04-13 21:40 UTC, nouiz commented
One test is failing. But I have an updated version of this PR that also enable few_waves in combination of that recently merged PR:
https://github.com/tensorflow/tensorflow/pull/48381

I think it will be better to merge the both changes at the same time. I'll update this PR in a few days when I have checked that we do not have speed regression with it.

2021-04-21 14:52 UTC, gbaned commented
@nouiz  Any update on this PR? Please. Thanks!

2021-04-21 14:58 UTC, nouiz commented
I have the code working locally. I started today some new speed test to make sure it doesn't give regression in other cases. When it is all fine here, I'll update it.

2021-05-11 20:40 UTC, timshen91 requested changes

2021-05-25 22:34 UTC, timshen91 approved these changes

2021-05-26 11:45 UTC, merged