Add PIL formats(gif,png...) support for retrain.py
tensorflow/tensorflow pull request #4843
Opened 2016-10-08 08:56 UTC by elviswf

- Add PIL formats(gif,png...) support for retrain.py.
- Use PIL.Image to read images and io.BytesIO to serialize them.

2016-10-08 09:18 UTC, elviswf commented
**I signed it!**
Thank you!

2016-10-11 19:50 UTC, rohan100jain requested changes

2016-10-11 19:50 UTC, rohan100jain commented on tensorflow/examples/image_retraining/retrain.py
> +from PIL import Image
Might want to add in the comments above that PIL would need to be installed in order to be able to run this.

2016-10-11 19:50 UTC, rohan100jain commented on tensorflow/examples/image_retraining/retrain.py
> +    if (image_path.split('.')[-1] in jpgext):
Use os.path.splitext() instead to figure out extension?

2016-10-11 19:50 UTC, rohan100jain commented on tensorflow/examples/image_retraining/retrain.py
> +    jpgext = ['jpg', 'jpeg', 'JPG', 'JPEG']
Make this a separate helper method that takes in file_name and returns back image_data.

2016-10-11 19:50 UTC, rohan100jain commented on tensorflow/examples/image_retraining/retrain.py
> +    extensions = ['jpg', 'jpeg', 'JPG', 'JPEG', 'gif', 'png']
what about GIF and PNG (caps)

Maybe share this list between here and below? Might also not be a bad idea to make it a dictionary mapping extension to color depth (https://en.wikipedia.org/wiki/Color_depth). That way you can handle the conversion more generally...

2016-10-12 06:28 UTC, elviswf commented on tensorflow/examples/image_retraining/retrain.py
> +from PIL import Image
Sure. Thank you!

2016-10-12 06:56 UTC, elviswf commented on tensorflow/examples/image_retraining/retrain.py
> +    extensions = ['jpg', 'jpeg', 'JPG', 'JPEG', 'gif', 'png']
I have tested these formats. So it goes like:
`extensions = ['jpg', 'jpeg', 'JPG', 'JPEG', 'gif', 'GIF', 'png', 'PNG', 'bmp', 'BMP']`

2016-10-12 06:56 UTC, elviswf commented on tensorflow/examples/image_retraining/retrain.py
> +    jpgext = ['jpg', 'jpeg', 'JPG', 'JPEG']
Sure. I will try it.

2016-10-12 07:05 UTC, elviswf commented on tensorflow/examples/image_retraining/retrain.py
> +    if (image_path.split('.')[-1] in jpgext):
os.path.splitext()  returns '.jpg', so it has to be set [1:] to return 'jpg' like:
`os.path.splitext(image_path)[1][1:]` 
I think `image_path.split('.')[-1]` might be  clear enough.

2016-10-12 07:42 UTC, elviswf commented on tensorflow/examples/image_retraining/retrain.py
> +    if (image_path.split('.')[-1] in jpgext):
@rohan100jain @petewarden I have updated the changes. Please check it. Thank you!

2016-10-18 15:23 UTC, elviswf commented
@petewarden I have updated the code according to the reviews. Thank you!

2016-10-22 02:24 UTC, drpngx requested changes

2016-10-22 02:24 UTC, drpngx commented on tensorflow/examples/image_retraining/retrain.py
> +  """Read the image into bytes stream.
Minor nit: Reads (as per PEP8). Also, "into a bytes stream".

2016-10-22 02:24 UTC, drpngx commented on tensorflow/examples/image_retraining/retrain.py
> +   For jpg/jpeg, gfile.FastGFile is enough.
Minor nit, this line and the next: remove one leading space.

2016-10-27 16:34 UTC, drpngx commented
Jenkins, test this please.

2016-10-27 18:45 UTC, elviswf commented
` Log @: /workspace/pip_test/tests/logs/tensorflow/examples/image_retraining/retrain_test.py.log

============== BEGINS failure log content ==============
Traceback (most recent call last):
  File "/workspace/pip_test/tests/retrain_test.py", line 23, in <module>
    from tensorflow.examples.image_retraining import retrain
  File "/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/examples/image_retraining/retrain.py", line 81, in <module>
    from PIL import Image
ImportError: No module named PIL

============== ENDS failure log content ==============`

It shows `No module named PIL`. I wonder if there is a way to avoid using PIL package.

2016-10-31 17:02 UTC, vrv commented
@petewarden @gunan Should we install PIL as part of our CI infrastructure and add this as a dependency?

Part of me thinks that, serving as an example, this is not going to do everything that people want to do, so perhaps we leave a comment instead suggesting other ways to read images instead.

2016-10-31 17:11 UTC, gunan commented
I am not a fan of adding the dependency, as I think everyone will have their own favorite ways of reading images. And PIL is not a real requirement to core TF, so I don't think it is right to brand it like a requirement to TF.

As for installing it to ci, sure.
But that means it will be installed to TF docker images.

2016-10-31 17:19 UTC, vrv commented
Okay, closing for now but discussion can continue here if needed.

2016-10-31 17:19 UTC, closed without merging

2016-11-01 06:47 UTC, elviswf commented
Actually I fully agree that adding this dependency is not necessary for now. I just used it for a deep learning competition with png, gif data and wanted to shared a way to handle it directly. 
 I will go on with excellent TF. Thank you all!

2017-04-19 03:12 UTC, passerbythesun commented
I have the same problem, so this piece code is useful for me.