[r2.5] Update of oneDNN version for mkl_aarch64 build target
tensorflow/tensorflow pull request #48543
Opened 2021-04-15 14:05 UTC by alenik01

This PR noticeably improves the performance of CNNs on AArch64 (`--config=mkl_aarch64`). oneDNN version upgrade follows the PR #48035

2021-04-15 14:05 UTC, alenik01 commented
@penpornk @agramesh1 please have a look.

2021-04-15 17:15 UTC, penpornk commented
@alenik01 Oh, I thought you are going to upgrade this in master and not 2.5. 

For 2.5, I'm not sure if we can cherry-pick this, since cherry-picks are for security / bug fixes. Upgrading from a v2.1 release to v2.2 release might count more towards adding features rather fixes. (The upgrade we did [here](https://github.com/tensorflow/tensorflow/pull/48345) was from a random commit after `v2.2-rc` to `v2.2` for more stability and fixes.)

@mihaimaruseac What do you think?

2021-04-15 17:16 UTC, penpornk requested changes

2021-04-15 17:16 UTC, penpornk commented on tensorflow/workspace2.bzl
> +            "https://storage.googleapis.com/mirror.tensorflow.org/https://github.com/oneapi-src/oneDNN/archive/v2.2.tar.gz",
Typo:
```suggestion
            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/oneapi-src/oneDNN/archive/v2.2.tar.gz",
```

2021-04-15 19:19 UTC, alenik01 commented
@penpornk if it is possible to cherry-pick this for v2.5 release, then it would be nice (the problem was that oneDNN v2.2 had been release after TF feature freeze deadline). If not, then this PR can be merged in the master.

2021-04-15 20:16 UTC, penpornk commented
@alenik01 Could you please share how much performance improvements you observe from this update? Is this update for performance improvements alone or is it also fixing some issues?

2021-04-15 20:43 UTC, penpornk commented
@alenik01 Also, could you please create another PR for the `master` branch? We usually only merge a cherry-pick after seeing the same changes successfully merged (and passed nightly tests) in `master`. 

I will check with the team if this PR is eligible for cherry-picking when I hear back about the speedups and whether this fixes any issues as well. Thank you!

2021-04-15 20:54 UTC, alenik01 commented
@penpornk
> Could you please share how much performance improvements you observe from this update?

The speedup is noticeable, x1.7 (was measure for ResNet50 inference).

> Is this update for performance improvements alone or is it also fixing some issues?

Performance alone.

> Also, could you please create another PR for the master branch?

OK, I will create one.

> since cherry-picks are for security / bug fixes

Many thanks for clarifying, now I understand that the version update for `mkl_dnn_v1` was one-off case.

2021-04-16 07:13 UTC, nSircombe commented
@mihaimaruseac - this is the PR we briefly discussed at the SIG build meeting the other week.

2021-04-16 20:54 UTC, alenik01 commented
@penpornk
>Also, could you please create another PR for the master branch? 

Here it is: https://github.com/tensorflow/tensorflow/pull/48574

2021-04-20 16:51 UTC, mihaimaruseac approved these changes

2021-04-22 22:47 UTC, merged