Fix all conv layers when filters is 0
tensorflow/tensorflow pull request #48566
Opened 2021-04-16 16:24 UTC by around-star

Fix #48470. This PR raises a `ValueError` for all conv layers upon encountering `filters = 0`. @fchollet

2021-04-19 17:53 UTC, around-star commented
@fchollet can you review this ?

2021-04-19 18:41 UTC, fchollet commented on tensorflow/python/keras/layers/convolutional.py
> +      raise ValueError("The value of filters should not be zero")
"The value of the `filters` argument should not be zero."

2021-04-19 18:42 UTC, fchollet requested changes
Thank you for the PR.

2021-04-19 19:02 UTC, around-star commented on tensorflow/python/keras/layers/convolutional_test.py
> +    with self.assertRaises(ValueError):
@fchollet Made the necessary changes. Thank you for reviewing .

2021-04-19 21:58 UTC, bhack approved these changes

2021-04-19 23:42 UTC, rthadur approved these changes

2021-04-20 01:18 UTC, bhack requested changes

2021-04-20 01:18 UTC, bhack commented on tensorflow/python/keras/layers/convolutional_test.py
> +    with self.assertRaisesRegex(ValueError):
It has two params  `self.assertRaisesRegex(ValueError, <str>):`

2021-04-20 01:30 UTC, bhack approved these changes

2021-04-20 01:49 UTC, bhack approved these changes

2021-04-20 01:53 UTC, around-star commented
I guess I run into some pylint errors . Solved them. Please review @bhack

2021-04-20 01:53 UTC, bhack approved these changes

2021-04-20 18:09 UTC, fchollet approved these changes
LGTM, thanks

2021-04-20 18:42 UTC, merged