Symmetric Fake Quantization
tensorflow/tensorflow pull request #48580
Opened 2021-04-17 00:20 UTC by philipphack

Resolves model optimization issue [#635, Symmetric quantization returns nonzero value for 0 on GPU](https://github.com/tensorflow/model-optimization/issues/635) by modifying the fake-quantization functors. The new formulation is device-independent and produces on both CPUs and GPUs the same output as the CPU execution of the current implementation.

2021-04-27 09:19 UTC, lgeiger commented
Would be great to have this PR reviewed soon. Pinging @Xhark and @teijeong since I think this might fix #47193.

2021-05-21 11:29 UTC, Xhark requested changes
Hi, Thanks for your request!
Is there any test that it was failed before in this CLs?

2021-05-21 11:29 UTC, Xhark commented on tensorflow/core/kernels/fake_quant_ops_functor.h
> +        static_cast<int>(-nudged_min / nudged_scale + 0.5f);
I think technically no difference but floor seems be more comfortable.

2021-05-21 11:29 UTC, Xhark commented on tensorflow/core/kernels/fake_quant_ops_functor.h
> +        ((clamped_shifted / nudged_scale_repl + 0.5f).floor() - quant_zero) *
how about floor after compute with quant_zero? Is there any difference?

2021-05-21 21:15 UTC, philipphack commented
Thanks for the review. The PR includes 6 new unit tests for symmetric fake quantization that fail with the present implementation of the functors.

The updated implementation also passes the script in model optimization issue [#635](https://github.com/tensorflow/model-optimization/issues/635):

```
[10.039216   9.0196085  0.        10.039216 ]   
[10.         8.9763775  0.        10.       ]
[10.         8.9763775  0.        10.       ]
[10.039216   9.0196085  0.        10.039216 ]
[10.         8.9763775  0.        10.       ]
[10.         8.9763775  0.        10.       ]

2021-05-24 08:07 UTC, Xhark approved these changes
LGTM

2021-05-28 00:02 UTC, philipphack commented
@Xhark: Can you provide some insight regarding the failure of the internal checks?

2021-06-04 20:45 UTC, merged

2021-06-25 17:14 UTC, Xhark commented
Hi @philipphack,
This PR was rollbacked due to it breaks some existing internal test. I'm trying to remerge. (fix the internal test or fix the code on this PR.)
Would you please let me know how did you check the new test is failed with original the present implementation? I can't reproduce....

One comment during fixing this issue was: We prefer to use A * (1.0 / scale) because (1.0 / scale) can be cached, and * is much faster than /. (Some compiler optimize option may changes A / scale as A * (1.0 / scale), but it seems not optimized the tensor div op internal code by default.)
I've figured out just shifting the input value (as you did on this PR) of rounding function and use A * inv_scale form might be the best during this journey. WDYT?

2021-06-26 00:08 UTC, philipphack commented
@Xhark, thanks for your message. You're right that the present unit tests don't demonstrate the problem with the previous implementation since they run exclusively on the CPU. I've added a set of GPU specific tests which reproduce the issue.

It's certainly possible to precompute ` const float inv_nudged_scale = 1.0f / nudged_scale`. I had only removed it from `FakeQuantWithMinMaxArgsFunctor` since it wasn't done in `FakeQuantWithMinMaxVarsFunctor` and `FakeQuantWithMinMaxVarsFunctor` either.

Let me know how you wish to proceed. Should I push another commit with these changes to the original branch?

2021-06-28 01:39 UTC, Xhark commented
@philipphack 

For the best case:
It might be very helpful if you add `inv_nudged_scale` like things for all functions, and it also resolve the original problem, (because this PR shifted input of round function.) and adding GPU tests. 

Would you please update the PR? 
Or you can create new PR, I think that might be more clear.
(We can add the link on this thread.)