[ROCm] Reduction for complex types, dynamic warp setting
tensorflow/tensorflow pull request #48582
Opened 2021-04-17 02:50 UTC by ekuznetsov139

This PR supplies two related sets of ROCm-related changes:
* Reduction for complex data types
* Dynamic warp size setting (on ROCm, warp size is either 32 vs 64 depending on the GPU and the value is not known at compile time)

2021-06-14 20:59 UTC, ekuznetsov139 commented
gentle ping

2021-06-18 16:43 UTC, deven-amd commented
@chsigg @cheshire gentle ping

2021-06-18 20:04 UTC, cheshire requested changes
minor nit

2021-06-18 20:04 UTC, cheshire commented on tensorflow/core/util/gpu_kernel_helper_test.cu.cc
> +  const int TF_RED_WARPSIZE=isGfx10() ? 32 : 64;
It's a bit ugly how it's either macro or a variable. Can we just make it a variable in both cases, and change the naming convention?

2021-06-25 17:21 UTC, gbaned commented
@ekuznetsov139  Can you please check @cheshire's comments and keep us posted ? Thanks!

2021-07-16 15:03 UTC, gbaned commented
@ekuznetsov139 Any update on this PR? Please. Thanks!

2021-07-29 15:18 UTC, gbaned commented
I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen!

2021-07-29 15:18 UTC, closed without merging