[CherryPick:r2.5]Use the standard lib ast.unparse instead of astunparse, available in Python 3.9+.
tensorflow/tensorflow pull request #48623
Opened 2021-04-19 20:11 UTC by geetachavan1

PiperOrigin-RevId: 367434930
Change-Id: Ieab1c5b76e54f00986ea4e6467714b1ee71199d4

2021-04-19 20:12 UTC, mdanatg approved these changes

2021-04-19 20:14 UTC, mdanatg requested changes
Sorry. I think I specified the wrong CL in the CP request. Please stand by.

2021-04-19 20:20 UTC, mdanatg commented
Confirming, I listed the wrong CL number, sorry for the runaround - we should revert this PR.

2021-04-20 16:49 UTC, mihaimaruseac commented
Closing as it uses the wrong CL

2021-04-20 16:49 UTC, closed without merging