Removed orphaned declaration of extern "C" void RegisterOps(void *)
tensorflow/tensorflow pull request #4872
Opened 2016-10-10 12:43 UTC by andreas-eberle

In op.h the declaration of `extern "C" void RegisterOps(void *)` was missed when removing it's implementation in e774fa829a1d74ab2d410cefc62cbd47e20b0317. This PR removes the orphaned declaration.

2016-10-10 13:06 UTC, andreas-eberle commented
I signed it!

2016-10-11 04:42 UTC, rohan100jain requested changes

2016-10-11 04:42 UTC, rohan100jain commented on tensorflow/c/c_api.h
> +// Expects the symbols "RegisterKernels", and "GetOpList", to be
I think you probably want to leave out this entire line... look at tensorflow/core/framework/load_library.cc::LoadLibrary comment

2016-10-11 10:27 UTC, andreas-eberle commented on tensorflow/c/c_api.h
> +// Expects the symbols "RegisterKernels", and "GetOpList", to be
Thx for your hint. RegisterKernels was also a orphan and GetOpList was only in this comment.

2016-10-11 15:46 UTC, keveman approved these changes

2016-10-11 16:03 UTC, rohan100jain approved these changes

2016-10-11 16:04 UTC, rohan100jain commented
@tensorflow-jenkins test this please

2016-10-11 17:35 UTC, merged