Adding example for uniform_row_length in RaggedTensor
tensorflow/tensorflow pull request #49018
Opened 2021-05-09 10:54 UTC by ashutosh1919

There are total 6 schemes [here](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor#alternative_row-partitioning_schemes_2) for row-partitioning of RaggedTensor but the examples are only for 5. I have added missing example.

cc: @mihaimaruseac

2021-05-12 18:36 UTC, mihaimaruseac requested changes
Can you also change the docstring to also show the values of each one of the RaggedTensors?

I made a suggestion for the last one, but all should be done the same way.

2021-05-12 18:36 UTC, mihaimaruseac commented on tensorflow/python/ops/ragged/ragged_tensor.py
> +  >>> rt6 = RaggedTensor.from_uniform_row_length(values, uniform_row_length=2)
```suggestion
  >>> RaggedTensor.from_uniform_row_length(values, uniform_row_length=2)
  <output would go here, and we can test this so there are no regressions>
```

2021-05-13 05:13 UTC, ashutosh1919 commented on tensorflow/python/ops/ragged/ragged_tensor.py
> +  >>> rt6 = RaggedTensor.from_uniform_row_length(values, uniform_row_length=2)
done

2021-05-15 23:14 UTC, mihaimaruseac approved these changes

2021-05-18 16:20 UTC, merged