Update ICU to 69.1
tensorflow/tensorflow pull request #49026
Opened 2021-05-09 19:38 UTC by yongtang

This PR updates ICU from 64.2 to to 69.1.

Note this PR will cover CVE-2020-10531 (https://www.cvedetails.com/cve/CVE-2020-10531/) which exists through 66.1.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2021-05-12 18:32 UTC, mihaimaruseac approved these changes

2021-06-09 15:47 UTC, mihaimaruseac requested changes
Can you check the Ubuntu CPU failures?

https://source.cloud.google.com/results/invocations/ad1cfb4c-24ae-4d94-9486-9c3524995d5b/targets/%2F%2Ftensorflow%2Fpython%2Fkernel_tests:unicode_decode_op_test/tests;group=__main__.UnicodeDecodeTest;test=testDecodeWithOffsetsWithDifferentEncodings%28'SHIFT-JIS',%20%5B'Hello',%20'%E3%81%93%E3%82%93%E3%81%AB%E3%81%A1%E3%81%AF'%5D%29;row=2

https://source.cloud.google.com/results/invocations/ad1cfb4c-24ae-4d94-9486-9c3524995d5b/targets/%2F%2Ftensorflow%2Fpython%2Fkernel_tests:unicode_transcode_op_test/tests

```
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/unicode_decode_op_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/unicode_decode_op_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/unicode_decode_op_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not create converter for input encoding: SHIFT-JIS
	 [[{{node UnicodeDecodeWithOffsets/UnicodeDecodeWithOffsets}}]]
```

2021-06-30 15:01 UTC, gbaned commented
@yongtang  Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

2021-06-30 15:57 UTC, yongtang commented
Thanks @gbaned @mihaimaruseac for the reminder. I think I find out where the issue is. Static files within `tensorflow/third_party/icu/data/` directory will need to be updated manually and provided as a part of the PR.

However, there is no documentation on how to update those files so I am still in the process of understanding. I will provide update once I can make some progress.

2021-10-04 19:43 UTC, mihaimaruseac approved these changes

2021-11-12 10:39 UTC, gbaned commented
@yongtang Can you please resolve conflicts? Thanks!

2021-12-13 15:26 UTC, gbaned commented
@yongtang Any update on this PR? Please. Thanks!

2021-12-28 16:49 UTC, gbaned commented
@yongtang Any update on this PR? Please. Thanks!

2022-01-28 01:00 UTC, closed without merging

2022-01-30 00:48 UTC, mihaimaruseac commented
Sorry for duplicating the work, @yongtang . I was working to bump to 70.1, but due to some failing tests had to lower to 69.1 and then that closed this PR.

I think PR failed before because we didn't also update the datafiles, I added some instructions so we don't forget in the future.