VLOG() to Text File
tensorflow/tensorflow pull request #49200
Opened 2021-05-14 23:07 UTC by philipphack

Redirects the output of all active `VLOG()` calls to a text file specified by the environment variable `TF_CPP_VLOG_FILENAME`. If the environment variable is not set, or if it points to a location that cannot be opened for writing, the output continues to `stderr`.

Attn: @reedwm.

2021-05-15 00:13 UTC, reedwm requested changes

2021-05-15 00:13 UTC, reedwm commented on tensorflow/core/platform/default/logging.h
> +class VlogFileMgr {
I think this class can be in the `.cc` file

2021-05-15 00:13 UTC, reedwm commented on tensorflow/core/platform/default/logging.cc
>    // TODO(jeff,sanjay): Replace this with something that logs through the env.
You can remove this TODO now

2021-05-15 00:13 UTC, reedwm commented on tensorflow/core/platform/default/logging.cc
> +  mutex_lock l(mu);
This lock isn't needed. By the time this point is reached, the `VlogFileMgr` will be initialized, and fprintf is thread-safe.

2021-05-15 00:13 UTC, reedwm commented on tensorflow/core/platform/default/logging.cc
> +  static internal::VlogFileMgr vlog_file;
Make this const

2021-05-15 01:30 UTC, philipphack commented
Thanks, Reed. I believe the thread safety of `fprintf ` is linked to POSIX compliance.

2021-05-15 03:51 UTC, reedwm requested changes
According to [this StackOverflow response](https://stackoverflow.com/a/41131253), fprintf is thread-safe since C11 (although it's ambiguous whether logs interleave). I don't think a lock is necessary.

2021-05-15 03:51 UTC, reedwm commented on tensorflow/core/platform/default/logging.cc
> +class VlogFileMgr {
This can be put into the anonymous namespace up above

2021-05-17 18:04 UTC, reedwm approved these changes

2021-05-20 12:19 UTC, merged