Fix 'Illegal ambiguous match'
tensorflow/tensorflow pull request #49300
Opened 2021-05-19 12:25 UTC by salamaniibm

bazel build for pip package //tensorflow/tools/pip_package:build_pip_package  on s390x gives the following error:

```
Illegal ambiguous match on configurable attribute "deps" in //tensorflow/core/common_runtime:core_cpu_internal:
//tensorflow:linux_s390x
//tensorflow:no_aws_support
Multiple matches are not allowed unless one is unambiguously more specialized.
```

This is because the select statement [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/build_config.bzl#L678-L686) matches both //tensorflow:linux_s390x and //tensorflow:no_aws_support 

This pr is to to remove `clean_dep("//tensorflow:no_aws_support"): []` as AWS and HDFS support is disabled by default.

2021-05-19 12:33 UTC, bhack approved these changes
For Kokoro run

2021-06-02 13:32 UTC, salamani commented
@mihaimaruseac Please let us know the update

2021-06-02 13:47 UTC, bhack commented
/cc  @wdirons @jayfurmanek

2021-06-02 14:47 UTC, jayfurmanek commented
@Sidong-Wei FYI

2021-06-08 20:32 UTC, mihaimaruseac commented
There seems to be an error with the license checks, can you look at the sanity build log please?

```
FAIL: mismatch in packaged licenses and external dependencies
Missing the licenses for the following external dependencies:
@aws//
@aws-c-common//
@aws-c-event-stream//
@aws-checksums//
Please add the license(s) to //tensorflow/tools/lib_package:jnilicenses_generate.
```

https://source.cloud.google.com/results/invocations/4d313cfb-2451-4fe4-a6e8-268cf603fe0b/log

2021-06-08 20:33 UTC, mihaimaruseac requested changes
Cannot land this while it has issues with licenses in the sanity build

2021-06-22 05:16 UTC, salamaniibm commented
Closing this as latest master working fine.

2021-06-22 05:16 UTC, closed without merging