Added list functionality to registry object
tensorflow/tensorflow pull request #4946
Opened 2016-10-13 21:26 UTC by klattimer

Very small change which I'm personally going to find useful shortly, I think others will too.

2016-10-13 21:31 UTC, klattimer commented
I signed it!

2016-10-14 00:15 UTC, rohan100jain approved these changes

2016-10-14 00:16 UTC, rohan100jain commented
@tensorflow-jenkins test this please

2016-10-14 05:35 UTC, rohan100jain requested changes

2016-10-14 05:35 UTC, rohan100jain commented on tensorflow/python/framework/registry.py
> +      """List registered items.
Fix indent

2016-10-14 13:02 UTC, karlinnolabs commented on tensorflow/python/framework/registry.py
> +      """List registered items.
What's up with the 2 space indentation? Maybe my editor broke something

2016-10-14 20:48 UTC, rohan100jain submitted a review, later dismissed

2016-10-14 20:48 UTC, rohan100jain commented on tensorflow/python/framework/registry.py
> +      """List registered items.
hmm... the indentation seems to be 4 spaces here instead of 2. If you fix that, this change should be good to go!

2016-10-15 06:27 UTC, klattimer commented
OK Indentation fixed, my editor is set to 4 spaces.

2016-10-15 06:35 UTC, rohan100jain commented
@tensorflow-jenkins test this please

2016-10-18 12:45 UTC, karlinnolabs commented
@rohan100jain is there anything left to do on this?

2016-10-20 23:32 UTC, drpngx requested changes

2016-10-20 23:32 UTC, drpngx commented on tensorflow/python/framework/registry.py
> +    Returns:
We need a blank line here.

2016-10-20 23:32 UTC, drpngx commented on tensorflow/python/framework/registry.py
> +      List of names of registered objects
We need punctuation here.

2016-10-21 03:30 UTC, drpngx commented on tensorflow/python/framework/registry.py
> +    """List registered items.
Actually, we also need to use "Lists" as per PEP8, while you're at it.

2016-10-21 05:41 UTC, klattimer commented on tensorflow/python/framework/registry.py
> +    Returns:
Done

2016-10-21 05:46 UTC, drpngx commented
Jenkins, test this please.

2016-10-23 10:27 UTC, klattimer commented
Jenkins, test this please.

2016-10-23 16:02 UTC, drpngx approved these changes

2016-10-23 16:04 UTC, drpngx commented
Sorry, jenkins broken because of a broken merge. See thread on #5103

2016-10-28 06:07 UTC, drpngx commented
Jenkins, test this please.

2016-10-31 00:01 UTC, drpngx commented
Jenkins, test this please.

2016-10-31 17:06 UTC, merged