Update load_csv > load_csv_with_header for r 0.11
tensorflow/tensorflow pull request #4947
Opened 2016-10-13 22:01 UTC by dmathewwws

2016-10-13 22:04 UTC, dmathewwws commented
I signed it!

2016-10-14 00:11 UTC, rohan100jain requested changes

2016-10-14 00:11 UTC, rohan100jain commented on tensorflow/g3doc/tutorials/tflearn/index.md
> +                                                       target_dtype=np.int,
indent?

2016-10-14 00:11 UTC, rohan100jain commented on tensorflow/g3doc/tutorials/tflearn/index.md
> +                                                       features_dtype=np.float32)
from the old load_csv -> load_csv_with_header translation seems like this should perhaps be np.float64?

https://github.com/tensorflow/tensorflow/commit/2d4267507e312007a062a90df37997bca8019cfb#diff-8e7d29906b35612ebe283482505429d4

2016-10-14 03:23 UTC, terrytangyuan commented
You also need to change the actual code that's being tested

2016-10-29 07:42 UTC, tegg89 commented
I also found that load_csv() needed to be changed. However, DNNClassifier.fit()'s input has also brought ValueError: metrics. I am still looking forward it.

2016-10-31 17:11 UTC, vrv commented
Any updates @dmathewwws  ?

2016-11-04 18:32 UTC, vrv commented
Closing to clear out backlog, ping this thread and we can reopen (or send a new PR after resolving conflicts).

2016-11-04 18:32 UTC, closed without merging