refine builder.py
tensorflow/tensorflow pull request #4951
Opened 2016-10-14 01:11 UTC by frankfqchen

replace is with == for len()

2016-10-14 01:31 UTC, frankfqchen commented
I signed it!

2016-10-14 02:35 UTC, rohan100jain requested changes

2016-10-14 02:35 UTC, rohan100jain commented on tensorflow/python/saved_model/builder.py
> +    if len(asset_source_filepath_list) == 0:
how about 

if not asset_source_filepath_list ?

2016-10-15 20:28 UTC, jart requested changes
Please `git commit --amend` #4952, #4953, #4954, #4955, #4956, and #4958 into this commit. Then change the description of this commit to "Minor Python code health improvements"

2016-10-18 00:54 UTC, closed without merging

2016-10-18 01:05 UTC, jart commented
I'm sad to see this PR closed. These code health improvements would have been nice to have. We hope you'll consider contributing again in the future @frankfqchen.

2016-10-18 01:17 UTC, frankfqchen commented
@jart
 i close this cause i don't know how to do "Please git commit --amend #4952, #4953, #4954, #4955, #4956, and #4958 into this commit. Then change the description of this commit to "Minor Python code health improvements"    "

2016-10-18 01:51 UTC, frankfqchen commented
@jart   see my new pull request #5025