[PluggableDevice] Add DEVICE_DEFAULT registration for int32 Const
tensorflow/tensorflow pull request #50141
Opened 2021-06-08 07:56 UTC by PatriceVignola

Add DEVICE_DEFAULT registration for int32 Const so that pluggable devices don't have to register it themselves.

2021-06-15 03:30 UTC, sanjoy requested changes
Can we remove the registration for `DEVICE_GPU`?

CC @penpornk

2021-06-15 03:45 UTC, PatriceVignola commented
> Can we remove the registration for `DEVICE_GPU`?
> 
> CC @penpornk

Thanks for the review! I removed the GPU registration.

2021-06-15 15:30 UTC, sanjoy requested changes

2021-06-15 15:30 UTC, sanjoy commented on tensorflow/core/kernels/host_constant_op.cc
>  // A special GPU kernel for int32.
Update comment?

2021-06-17 23:26 UTC, sanjoy approved these changes

2021-06-18 23:32 UTC, PatriceVignola commented
@sanjoy Do I need to do anything to satisfy the import/copybara check?

2021-06-19 05:58 UTC, sanjoy commented
@rthadur Do you know what's going on with the import/copybara failure?

2021-06-21 06:46 UTC, merged

2021-06-21 19:50 UTC, rthadur commented
@sanjoy sorry I missed it