[TFLite]: Add missing cc file to Makefile
tensorflow/tensorflow pull request #50240
Opened 2021-06-12 15:28 UTC by cpcloud

This PR adds a missing file whose code is used in libedgetpu/libcoral
to the Tensorflow Lite `Makefile`.

2021-06-13 11:08 UTC, cpcloud commented
It looks like CI is failing because the host is running out of space:

```
10:49:57  ERROR: /workspace/tensorflow/core/BUILD:1883:11: Couldn't build file tensorflow/core/lib_strings_ordered_code_test/test.log:  failed due to unexpected I/O exception: write (No space left on device)
```

2021-06-13 23:50 UTC, abattery commented
@terryheo could you review this PR?

2021-06-14 00:13 UTC, terryheo requested changes
LGTM

2021-06-14 00:13 UTC, terryheo commented on tensorflow/lite/tools/make/Makefile
> +$(wildcard tensorflow/lite/schema/schema_conversion_utils.cc) \
plz alphabetize the order

2021-06-14 11:41 UTC, cpcloud commented on tensorflow/lite/tools/make/Makefile
> +$(wildcard tensorflow/lite/schema/schema_conversion_utils.cc) \
Done!

2021-06-15 01:09 UTC, terryheo approved these changes
LGTM

2021-06-15 14:06 UTC, gbaned approved these changes

2021-06-15 18:17 UTC, cpcloud commented
Is there anything else I need to do to get this merged?

2021-06-15 23:54 UTC, merged