Issue 1702 (code format)
tensorflow/tensorflow pull request #5026
Opened 2016-10-18 03:33 UTC by guotong1988

Please close [this](https://github.com/tensorflow/tensorflow/pull/4884) because I make a github mistake there.
Please tell me , if there exists some code format error.

2016-10-22 18:22 UTC, drpngx requested changes

2016-10-22 18:22 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +string SummarizeArray(int64 limit, int64 num_elts, const char* data,
Prefer const TensorShape&. Also, out parameters (data) should go at the end.

2016-10-22 18:22 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +//from left dim to right dim , recursive print
Here and below, please abide to google C++ style guide, to wit:
Need one space after '//'
Comments should be a full sentence, including punctuation, for instance "Loop every element of one dim."

2016-10-22 18:22 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +void PrintOneDim(T *data, int dim_index, gtl::InlinedVector<int64, 4> shape,
See below for parameter order:
dim_indx, shape, limit, shape_size, data, data_index, result.

2016-10-22 18:22 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +  gtl::InlinedVector<int64, 4> shape = tensor_shape.dim_sizes();
Not strictly required by our style guide, but prefer to use const gtl::InlinedVector... shape.

2016-10-22 18:22 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +  int shape_size = tensor_shape.dims();
As above, const int shape_size

2016-10-23 11:59 UTC, guotong1988 commented
I finish.

2016-10-23 16:01 UTC, drpngx requested changes
minor style nits

2016-10-23 16:01 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +string SummarizeArray(int64 limit, int64 num_elts, const TensorShape &tensor_shape,
we use const TensorShape* tensor_shape

2016-10-23 16:01 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +                 int shape_size, T *data, int64 *data_index, string *result) {
use T* data, int64* data_index, string* result

2016-10-23 16:01 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +// Recursive print from left dim to right dim
add punctuation + "Print ... recursively." is probably better phrasing, or Print recursively, from....

2016-10-24 02:03 UTC, guotong1988 commented
done

2016-10-24 02:11 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> -string SummarizeArray(int64 limit, int64 num_elts, const TensorShape &tensor_shape,
Sorry, it's fine to use a const ref, just collate the ampersand to the type, not the variable name.

2016-10-24 02:12 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +// Print recursively from left dim to right dim
Please put punctuation at the end of the comment ("." at the end), as per style guide.

2016-10-24 02:20 UTC, guotong1988 commented
finish

2016-10-24 03:07 UTC, guotong1988 commented
please wait a moment..

2016-10-24 05:28 UTC, guotong1988 commented
done

2016-10-31 17:23 UTC, vrv commented on tensorflow/core/framework/tensor.cc
> +  int element_count = shape[dim_index];
Use int64 here, shape is a vector of int64

2016-10-31 17:23 UTC, vrv commented on tensorflow/core/framework/tensor.cc
> +  // Reach the rightmost dim of the tensor.
// We have reached the right-most dimension of the tensor.

2016-11-01 02:33 UTC, guotong1988 commented
Done.

2016-11-01 02:33 UTC, drpngx commented
Jenkins, test this please.

2016-11-01 02:35 UTC, drpngx approved these changes

2016-11-01 03:31 UTC, drpngx commented
Please take a look at: https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/2051/consoleFull

2016-11-01 03:34 UTC, guotong1988 commented
OK

2016-11-01 03:59 UTC, guotong1988 commented
I know the reason of tensor_test.cc . But I don't know the reason of TIMEOUT.

2016-11-01 04:12 UTC, guotong1988 commented
I know the reason of tensor_test.cc . But I don't know the reason of TIMEOUT.

2016-11-01 04:54 UTC, drpngx commented
Github suffered an outage, and it likely affected jenkins as well, perhaps a repeat of the DDoS.

Jenkins, test this please.

2016-11-01 06:07 UTC, drpngx commented
Something wrong with the tests, let's try tomorrow.

2016-11-02 04:54 UTC, vrv commented
@tensorflow-jenkins test this please

2016-11-02 15:13 UTC, vrv commented
@tensorflow-jenkins test this please

2016-11-02 17:24 UTC, vrv commented
@tensorflow-jenkins test this please

2016-11-02 18:14 UTC, vrv commented
I think something about this change is indeed causing timeouts.  Possibly the new summarization code is too slow and is executed in some of the tests that are timing out.

2016-11-02 18:39 UTC, guotong1988 commented
So what should I do. Do you think it is a good idea to write two methods. One for print and another is the origin one.

2016-11-02 18:40 UTC, vrv commented
I would try to investigate whether this change is indeed causing runtime of those tests to increase (you can test locally to find out), and then see if there's something you can do about it?  I can't say which is better without knowing more information from your end.

2016-11-02 18:47 UTC, guotong1988 commented
Oh.. Would you please tell me the instructions to run all the test?
I only know how to run a single one:)

2016-11-02 18:52 UTC, drpngx commented
You need to run `bazel test -c opt tensorflow/...`, or select a test, like `//tensorflow/contrib/bayesflow:entropy_test` which took 300 seconds instead a just a few.

2016-11-02 18:52 UTC, guotong1988 commented
Oh..I 'm sorry. I think I can do it. It is 3 am now and I 'm a little slow with th brain.

2016-11-03 03:53 UTC, guotong1988 commented
I found the reason and fixed it.

2016-11-03 03:54 UTC, vrv commented
Nice!  Can you add a test to tensor_test.cc that would have caught the problem too?

2016-11-03 04:01 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +  if (shape.size() == 0) return "";
Prefer the idiomatic if (shape.empty()) return "";

2016-11-03 04:11 UTC, guotong1988 commented
Done.

2016-11-03 04:15 UTC, drpngx commented
Jenkins, test this please.

2016-11-03 04:45 UTC, guotong1988 commented
well I will fix it.

2016-11-03 04:52 UTC, guotong1988 commented
Next time I will run all tests before commit.

2016-11-03 07:27 UTC, guotong1988 commented
When the `shape` is empty , the `DebugString` method of the unit-test need the value to be return.

2016-11-04 01:37 UTC, drpngx commented
Jenkins, test this please.

2016-11-04 01:43 UTC, drpngx commented on tensorflow/core/framework/tensor.cc
> +  int64 data_index = 0;
Move this after if (shape.empty()) {...}

Thanks!

2016-11-04 02:16 UTC, guotong1988 commented
Done.

2016-11-04 02:18 UTC, drpngx commented
Jenkins, test this please.

2016-11-04 03:14 UTC, guotong1988 commented
I can't fix it because I don't know the reason.

2016-11-04 03:18 UTC, drpngx commented
Probably a transient error in the config. Trying again.

Jenkins, test this please.

2016-11-04 04:02 UTC, guotong1988 commented
I have run `bazel test -c opt //tensorflow/contrib/learn:dnn_linear_combined_test` locally , but it passed.
It used 116.2s.

2016-11-04 04:07 UTC, drpngx commented
Yeah, that test appears to have become flaky recently (failed last night's build). It seems to be a fairly recent problem.

2016-11-04 04:07 UTC, drpngx commented
Jenkins, test this please.

2016-11-04 18:09 UTC, merged