[INTEL MKL] Enable mkl group conv
tensorflow/tensorflow pull request #50333
Opened 2021-06-18 02:29 UTC by ShengYang1

Group conv is already enabled in CPU. This PR enables mkl group conv.

2021-07-08 12:19 UTC, gbaned commented
@penpornk  Can you please review this PR ? Thanks!

2021-07-19 23:29 UTC, penpornk requested changes
Thank you for the PR and sorry for the delay! I have a minor nit.

2021-07-20 10:39 UTC, ShengYang1 commented on tensorflow/core/kernels/mkl/mkl_conv_ops.h
> +        mkldnn_sizes[MKL_GROUP_FILTER_DIM_W] = filter_cols;
Thanks for review. Yes, we can directly set `filter_dims` to remove redundant vector copy. Also I have added a TODO and will submit another PR.

2021-07-20 17:27 UTC, penpornk approved these changes
Thank you for the change!

2021-07-28 19:53 UTC, penpornk commented
It looks like the [Linux GPU](https://source.cloud.google.com/results/invocations/bc5f88db-c0bb-429f-b5e2-7ac1b70fe5bd/targets) failure is related to this PR. Could you please help take a look at `//tensorflow/python/kernel_tests:conv_ops_test_gpu`? Thank you!

2021-07-29 05:40 UTC, ShengYang1 commented
> It looks like the [Linux GPU](https://source.cloud.google.com/results/invocations/bc5f88db-c0bb-429f-b5e2-7ac1b70fe5bd/targets) failure is related to this PR. Could you please help take a look at `//tensorflow/python/kernel_tests:conv_ops_test_gpu`? Thank you!

Looks like Eigen conv backward doesn't support group conv, so I removed the changes for gradient test case.

2021-07-29 20:27 UTC, penpornk approved these changes
Thank you for the fix!

2021-08-09 15:31 UTC, merged