[determinism] Add d9m-unimplemented exceptions to sparse/sparse matmul
tensorflow/tensorflow pull request #50355
Opened 2021-06-19 00:09 UTC by duncanriach

This current PR is a follow-on to closed PR [47749](https://github.com/tensorflow/tensorflow/pull/47749) (Add GPU determinism for fp types in GPU SparseTensorDenseMatMul). This current PR adds and tests determinism-unimplemented exception-throwing for `tf.sparse.sparse_dense_matmul` when is running on a GPU. This current PR also adds tests for the bit-exact reproducibility (determinism) of `tf.sparse.sparse_dense_matmul` (forward direction only, not gradients) when running a CPU.

This PR is related to [RFC: Enabling Determinism in TensorFlow](https://github.com/tensorflow/community/blob/master/rfcs/20210119-determinism.md). For status and history of GPU-determinism for this op, see [here](https://github.com/NVIDIA/framework-determinism/blob/master/tensorflow_status.md#sparse-dense-matmul).

CC @reedwm, @sanjoy, @nluehr

2021-06-21 20:47 UTC, reedwm requested changes

2021-06-21 20:47 UTC, reedwm commented on tensorflow/python/kernel_tests/sparse_tensor_dense_matmul_op_deterministic_test.py
> +  test cases when deterministic ops are not enavbled and will therefore detect
```suggestion
  test cases when deterministic ops are not enabled and will therefore detect
```

2021-06-22 01:26 UTC, reedwm approved these changes

2021-06-22 13:04 UTC, gbaned approved these changes

2021-06-23 18:15 UTC, merged