Update resource_handle.h
tensorflow/tensorflow pull request #50560
Opened 2021-07-01 13:59 UTC by Saduf2019

Changed access modifier to "private"

Fix for #50481

2021-07-13 18:17 UTC, mihaimaruseac requested changes
Why?

2021-07-14 15:46 UTC, Saduf2019 commented
> Why?

Hi Mihai,
Submitted pr on behalf on user as he did not want to contribute them self.
Please let me know if this is invalid, so i could close this pr and update the same to the user.

2021-07-14 15:53 UTC, mihaimaruseac approved these changes

2021-07-14 15:53 UTC, mihaimaruseac commented
Looked through the history change and indeed it looks like a typo. Also, tests are passing, so let's go ahead with this one.

Thank you for the PR.

2021-07-15 15:57 UTC, merged