[PluggableDevice]add default device for function ops
tensorflow/tensorflow pull request #50578
Opened 2021-07-02 08:18 UTC by quintinwang5

Add default device registers for function ops. This is for PluggableDevice.

2021-09-16 08:03 UTC, jzhoulon commented
Hi, @penpornk @saxenasaurabh can you help to review this PR and PR[50601](https://github.com/tensorflow/tensorflow/pull/50601)? Some models will crash if the ArgOp and DestroyResourceOp not registered as DEVICE_DEFAULT. Thanks very much

2021-10-28 13:42 UTC, mdanatg approved these changes

2021-10-28 14:58 UTC, penpornk requested changes
I'm so sorry for the delay! This PR looks good to me. I have a minor comment on formatting.

2021-10-29 15:59 UTC, penpornk approved these changes

2021-10-30 17:34 UTC, mihaimaruseac approved these changes

2021-10-30 18:46 UTC, merged