Cudnn frontend v0.4: Support of int8x4, API updates
tensorflow/tensorflow pull request #50570
Opened 2021-07-01 21:00 UTC by kaixih

Cudnn frontend v0.4 released: https://github.com/NVIDIA/cudnn-frontend/releases/tag/v0.4

Accordingly, this PR does the following things:
- Support vector data type (Currently only int8x4);
- Change setDataType() in OperationBuilder to setComputePrecision()
- Update setAlpha/Beta which can deduce the datatype from the compute precision instead of given alpha/beta.

cc. @nluehr

2021-07-02 20:24 UTC, timshen91 commented
Also add awpr@ since he is working on these files as well.

2021-07-03 02:19 UTC, awpr requested changes

2021-07-04 09:06 UTC, kaixih commented
@awpr Thanks for your comments. Most of your feedback are resolved. PTAL.

For the int8x32 support, the IMMA kernels require the reordered filter/bias (more can be found https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnReorderFilterAndBias). So, for the frontend API, we are still working on if/how we should expose the reordering things to users. That is why in the v0.4 release note only contains the int8x4 samples.

2021-07-04 15:18 UTC, jlebar commented
> So, for the frontend API, we are still working on if/how we should expose the reordering things to users.

At the risk of distracting from the PR: I'd like the ability to say "I have already reordered it" to be exposed in the frontend API.

Ideally in XLA we will do the reordering ourselves.  That is, we'd like you to tell us what the reordering is (or I guess we'll figure it out by observing what ReorderFilterAndBias does).  Then we'll teach XLA to do this reordering itself.

By doing so, we'll be able to fuse the reordering operation into other ops, hopefully making it free.

2021-07-04 21:13 UTC, kaixih commented
> > So, for the frontend API, we are still working on if/how we should expose the reordering things to users.
> 
> At the risk of distracting from the PR: I'd like the ability to say "I have already reordered it" to be exposed in the frontend API.
> 
> Ideally in XLA we will do the reordering ourselves. That is, we'd like you to tell us what the reordering is (or I guess we'll figure it out by observing what ReorderFilterAndBias does). Then we'll teach XLA to do this reordering itself.
> 
> By doing so, we'll be able to fuse the reordering operation into other ops, hopefully making it free.

Exactly, we would like exposing this feature for advanced users like XLA who knows what's going on with manual filter/bias reordering. For now, the API will just assume filter/bias has already reordered if we simply change the `vectorCount` to 32 in the cudnn code sample or if we enable int8x32 in this PR.

2021-07-07 17:24 UTC, awpr approved these changes

2021-07-12 20:57 UTC, merged

2021-07-13 21:26 UTC, jlebar commented
@kaixih hey, when I turn this on and try to use it, the graphs fail to build: `CUDNN_BACKEND_OPERATIONGRAPH_DESCRIPTOR: cudnnFinalize Failed`

Do you know how to debug this?

2021-07-13 21:58 UTC, kaixih commented
Can you try the `TF_CPP_VMODULE=cuda_dnn=4` to output the logs? Then, at lease we can get an idea of the conv shape. Also the cudnn logs would help us to repro the issue if we know it is a cudnn issue.

May I ask if this is for the normal convolution or fused conv?

2021-07-13 22:20 UTC, jlebar commented
Hi, thanks so much for the reply!

I'm looking at fused convs.  Here is a failure chosen at random.  This has cudnn logging plus some logs from TensorFlow showing the conv shape.

https://gist.github.com/jlebar/a63d912cf20a422772e39f5c6d82c8c8

2021-07-13 23:10 UTC, kaixih commented
Hi Justin, I did a quick check and it seems the problem is the bias tensor doesn't get vectorized:
https://gist.github.com/jlebar/a63d912cf20a422772e39f5c6d82c8c8#file-gistfile0-txt-L3002-L3009 (The vectorCount and vectorDim lines are missing for this tensor.)

Could you please check if the bias tensor is correctly vectorized? For example, here the `vector_size` should be 4: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_dnn.cc#L3583

2021-07-14 01:45 UTC, jlebar commented
Thank you, @kaixih.  That gets me further.  Now the convs run but fail the test because of "wrong" results.  I think something is still wrong, but let me debug that first.

In the meantime, one other question if you don't mind.  For the legacy API, if you do a fused convolution with the identity activation, you must use `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM`.  The other algorithms appear to do an implicit relu even if you don't ask for it.

I'm seeing the same thing with the new API.  Some algorithm choices are doing a relu when I don't ask for it.

In the new API, what's the right way to check that I'm doing CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM?

2021-07-14 03:59 UTC, jlebar commented
> Now the convs run but fail the test because of "wrong" results. I think something is still wrong, but let me debug that first.

Turns out this was actually also the "I ask for identity activation function but it does relu anyway" problem.  That is, int8x4+relu seems to work fine with the fix you suggested!

Yay, we're almost there.

I really appreciate your help, @kaixih.

2021-07-16 23:21 UTC, jlebar commented
OK, an update on this.  We've figured out how to read the algorithm id!

New-algorithm 11 seems to correspond to the old IMPLICIT_PRECOMP_GEMM.

If the activation function is the identity function, is it correct to ignore all algs that are not new-algorithm-11?

2021-07-19 04:05 UTC, kaixih commented
Yes, I just checked that the engine index 11 (or "new algorithm" in your comment) is an IMPLICIT_PRECOMP_GEMM_XXX engine, meaning it's just one of many IMPLECIT_PRECOMP_GEMM engines used inside the legacy algorithm IMPLICIT_PRECOMP_GEMM.

For the identity activation issue, I think the cudnn fusion still has limitation on supporting arbitrary no-op in the supported fusion pattern (but as mentioned in the email, the plan is to have more comprehensive support for runtime fusion for NHWC, at least for this particular pattern.).

Also, if your observation holds that ConvBiasAdd+No-op actually works when using engine 11 via the pattern of ConvBiasAddRelu (sorry, I couldn't confirm it right now), I think it is a good idea to file a bug towards cudnn to support this variant pattern (i.e. allowing Relu to be Indentity/No-Op) via an update over the heuristics/fallback, which IMO seems to be straightfoward.

2021-07-22 00:56 UTC, jlebar commented
Thank you again, @kaixih.

We now have a new issue, sent on the google/nvidia mailing list, but in case you're not checking that right now:

We're encountering a strange issue when we combine

 - cudnn 8.2.1
 - the cudnn frontend, and
 - int8x4 fused-conv-bias-add operations.

The issue seems to have to do with the lifetime of cudnn frontend plans.

We observe that when we enable the cudnn frontend, then during and immediately after autotuning, our int8x4 convolutions behave as expected and output the correct result.  But when we come back and rerun the same conv at some point after, the conv with a saved ExecutionPlan gives the wrong answer.  Many values in the output are wrong by large amounts; I can't see a pattern in the wrong output.

When the conv gives the wrong answer, we can rebuild a new ExecutionPlan and use it to get the *right* answer.  Unfortunately, this is very slow.

As far as I can tell, this doesn't affect fp32 or fp16 convs, only int8 convs.

We've done most of our testing on cudnn 8.2.1, but I also just this afternoon verified that 8.2.2 has the same behavior.  We can reproduce on V100 and sm75 with CUDA 11.3.

Do you have any idea what might be going on?  Maybe there's some implicit lifetime in the ExecutionPlan that we're not respecting?  Or maybe there's something subtle that's broken with int8x4?

2021-07-22 01:34 UTC, kaixih commented
Yes, sounds like a execution plan lifetime issue. Let me reply it in the email thread.