add device_vendor to the GpuDevice in JAX runtime
tensorflow/tensorflow pull request #50799
Opened 2021-07-16 07:26 UTC by reza-amd

With this PR, device vendor will be exposed from JAX GpuDevice into Python

@hawkinsp

2021-07-19 15:11 UTC, hawkinsp requested changes
One tiny typo needs fixing.

2021-07-19 15:11 UTC, hawkinsp commented on tensorflow/compiler/xla/pjrt/gpu_device.h
> +            std::string device_kind, std::string device_vensor, int node_id);
Nit: typo `device_vendor`

2021-07-19 16:14 UTC, reza-amd commented on tensorflow/compiler/xla/pjrt/gpu_device.h
> +            std::string device_kind, std::string device_vensor, int node_id);
Done.

2021-07-19 16:18 UTC, hawkinsp approved these changes

2021-07-21 12:27 UTC, hawkinsp commented
One of our internal presubmits reminded me that you also need to update the Python type stub for pybind code:
https://github.com/tensorflow/tensorflow/blob/0c13207eeda65754532bab5888cc33693fb06834/tensorflow/compiler/xla/python/xla_extension/__init__.pyi#L248
to add `device_vendor`

2021-07-21 22:04 UTC, hawkinsp approved these changes

2021-07-22 13:04 UTC, gbaned approved these changes

2021-07-23 18:16 UTC, hawkinsp commented
Our presubmits are still unhappy, with this error:
```
error: field 'device_vendor_' will be initialized after base 'xla::PjRtStreamExecutorDevice' [-Werror,-Wreorder-ctor]
```

2021-07-26 13:45 UTC, hawkinsp approved these changes

2021-07-26 15:16 UTC, merged