Update stale.yml
tensorflow/tensorflow pull request #50830
Opened 2021-07-19 06:08 UTC by rmothukuru

Simplified the Message to the User

2021-07-19 16:39 UTC, rthadur requested changes

2021-07-19 16:39 UTC, rthadur commented on .github/stale.yml
> +  This issue has been automatically marked as stale because it had no
Can you please make it * has no

2021-07-20 04:55 UTC, rmothukuru commented on .github/stale.yml
> +  This issue has been automatically marked as stale because it had no
Done

2021-07-21 16:02 UTC, rthadur approved these changes

2021-07-22 13:07 UTC, merged