Fix unchecked int32 indexing in some GPU kernels
tensorflow/tensorflow pull request #50917
Opened 2021-07-23 02:53 UTC by benbarsdell

- Many op kernels use the `To32Bit()` function, which does not do any bounds checking and can cause silent corruption due to int32 overflow.
  E.g., `tf.zeros/ones/fill` silently give incorrect results when the number of elements is >= 2**31.
- This commit adds a new helper function `MaybeWith32BitIndexing()` that checks the indexing bounds and converts tensors to 32-bit only if it is safe to do so (and only for GPU devices). This fixes the cases that were previously broken, and simplifies the ones that already had explicit bounds checks.

cc @nluehr @sanjoy

2021-07-23 21:03 UTC, sanjoy requested changes
We have an ongoing engagement with @kushanam and @sherhut to do this without bloating the binary size by JIT compiling the rarely used codepaths.  So I would rather invest into that effort unless we've already judged the JIT-based approach to be infeasible.

2021-07-26 08:49 UTC, benbarsdell commented on tensorflow/core/framework/tensor_types.h
> +    if (all((SafeFor32BitIndexing(std::forward<Args>(args)))...)) {
Nope, fixed.

2021-07-26 08:49 UTC, benbarsdell commented on tensorflow/core/framework/tensor_types.h
> +      int unpack[] = {0, (result = result && bool_vals, 0)...};
Good idea, done.

2021-07-26 08:50 UTC, benbarsdell commented
> We have an ongoing engagement with @kushanam and @sherhut to do this without bloating the binary size by JIT compiling the rarely used codepaths. So I would rather invest into that effort unless we've already judged the JIT-based approach to be infeasible.

OK I was wondering about that. If the timeline is not too long then that would be the way to go.

2021-07-30 06:17 UTC, benbarsdell commented
My take on this is that we can close it if the new JIT kernels work will be enabled before the release of 2.7.
If that won't make 2.7, then we should either merge this PR or modify it to simply throw a fatal error when 32-bit indexing is insufficient.

For reference, I checked the effect of this PR on binary size (_pywrap_tensorflow_internal.so) in my build:
Before: 547MB
After:  566MB (+3.5%)

2021-08-02 10:09 UTC, sherhut commented
We should land this change independently of the kernel generator work, as it also covers other operations (like reductions) that are not currently covered by kernel generator.

I suspect that the (relatively) small change in size is due to us not generating all the cwise operations via the eigen code path anymore, so the generation of two kernels due to `cwise_cpu_common` does not hit us.

2021-08-04 22:51 UTC, sanjoy approved these changes

2021-08-11 17:13 UTC, merged