Fix tf.tile crash when n is large
tensorflow/tensorflow pull request #51138
Opened 2021-08-04 03:23 UTC by yongtang

This PR tries to fix the issue raised in #46911 where tf.tile
will crash when n is large. This PR add additional check
to make sure an error message is rendered (instead of crash).

This PR fixes #46911.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2021-08-04 17:14 UTC, mihaimaruseac requested changes

2021-08-04 17:14 UTC, mihaimaruseac commented on tensorflow/core/kernels/tile_ops.cc
>        output_shape.AddDim(input.dim_size(i) * multiples_array[i]);
Let's instead change this to use [`AddDimWithStatus`](https://github.com/tensorflow/tensorflow/blob/51d911b4661b290f0e207fc7cf1ec79b9e411a58/tensorflow/core/framework/tensor_shape.h#L208-L210) and wrap that in `OP_REQUIRES_OK`.

Also, if we want to display a shape in an error message, `shape.DebugString()` is the best API to use.

2021-08-04 22:36 UTC, yongtang commented
Thanks @mihaimaruseac. The PR has been updated. Please take a look.

2021-08-05 15:42 UTC, mihaimaruseac approved these changes

2021-08-24 13:37 UTC, gbaned approved these changes

2021-09-21 01:51 UTC, merged