Fix overflow/crash in tf.range when limits is large
tensorflow/tensorflow pull request #51359
Opened 2021-08-07 17:25 UTC by yongtang

This PR tries to address the issue raised in #46913 where
tf.range (and implicitly tf.keras.layers.RepeatVector)
will overflow/crash when limits is large.

The reason of the overflow is that while calculating
the size within the kernel, the conditional statements
comes with `int64 = cond ? int64 : double` will implicitly
convert to double first and then cast back to int64, causing
the overflow and crash.

This PR fixes the issue by casting to int64 in both selections
within the conditional statements first.

This PR fixes #46913.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2021-08-09 15:01 UTC, mihaimaruseac requested changes

2021-08-09 15:01 UTC, mihaimaruseac commented on tensorflow/core/kernels/sequence_ops.cc
> +                            std::ceil(std::abs((limit - start) / delta))));
Let's separate each branch to a separate expression to ease in readability.

2021-08-09 15:54 UTC, yongtang commented
Thanks @mihaimaruseac . The PR has been updated.

2021-08-17 15:54 UTC, mihaimaruseac approved these changes

2021-08-18 15:15 UTC, merged