TF-TRT: Remove dangerous const_cast in TRT_ShapedWeights::GetValues
tensorflow/tensorflow pull request #51478
Opened 2021-08-13 04:28 UTC by christopherbate

This PR splits `TRT_ShapedWeights::GetValues()` into const and non-const methods to obey `const` requirements without using`const_cast`. It changes the method to a template which returns a `T*` or `const T*` pointer (rather than void*), 
eliminating pointer casting throughout code base when using GetValues().

A regex find-and-replace update was used to update all the call sites.

@bixia1, @tfeher for review

2021-08-13 14:13 UTC, pranavm-nvidia approved these changes

2021-08-13 15:02 UTC, bixia1 requested changes

2021-08-13 15:02 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h
> +  // Returns a pointer of type T to the underlying buffer of the tensor.
s/T/const T/

2021-08-13 15:02 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h
> +  const T* GetValues() const {
So it actually returns a pointer not values. Would it be better to rename this to GetPointer?

2021-08-13 15:32 UTC, christopherbate commented
@bixia1, I applied your recommended changes.

2021-08-13 16:25 UTC, bixia1 approved these changes
Thanks for the PR!

2021-08-16 21:35 UTC, bixia1 requested changes
I got this error (the line number may not be exact)
In file included from third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:16:
./third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h:191:45: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'long' in initializer list [-Wc++11-narrowing]
    return tensor_.bit_casted_shaped<T, 1>({num_elem}).data();
                                            ^~~~~~~~
third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:783:35: note: in instantiation of function template specialization 'tensorflow::tensorrt::convert::TRT_ShapedWeights::GetPointer<signed char>' requested here
  return nvinfer1::Weights{type_, GetPointer<int8>(), count()};

2021-08-16 23:17 UTC, christopherbate commented
OK I will change from `size_t` to `int` then. Was this caught by internal CI or your build? What is the warning/copt set so this doesn't happen in the future? I am just using default.

2021-08-17 19:17 UTC, christopherbate commented
@bixia1 updated from `size_t` to `int64`. I built with GCC option `-Werror=narrowing`, and it appears to be fixed. I think you're on Clang, for which I don't have env setup right now. I can add that to my build setup. Do you have non default `cxxopts/copts` settings for Bazel? Thanks. Let me know if you have any other concerns.

2021-08-17 20:08 UTC, bixia1 approved these changes

2021-08-18 10:40 UTC, gbaned approved these changes

2021-08-20 13:18 UTC, merged