Fix merging of summaries to match the tutorial "TensorFlow Mechanics 101"
tensorflow/tensorflow pull request #5148
Opened 2016-10-23 11:26 UTC by nikikilbertus

The example does not work with `tf.summary.merge_all()`. Changing it to `tf.merge_all_summaries()` like in the [tutorial](https://www.tensorflow.org/versions/r0.11/tutorials/mnist/tf/index.html#train-loop) fixes the issue.

2016-10-23 11:33 UTC, nikikilbertus commented
I signed it.

2016-10-23 17:28 UTC, drpngx approved these changes

2016-10-25 20:41 UTC, zheng-xq commented
@tensorflow-jenkins test this please

2016-10-27 16:33 UTC, drpngx requested changes

2016-10-27 16:33 UTC, drpngx commented on tensorflow/models/image/cifar10/cifar10_eval.py
> -    # Start the queue runners.
That code block is not reachable since it's after `return`?

2016-10-27 16:49 UTC, nikikilbertus commented on tensorflow/models/image/cifar10/cifar10_eval.py
> -    # Start the queue runners.
Sorry, my bad. I had it dedented in my fork and then accidentally indented one level too much.

2016-10-27 18:46 UTC, danmane commented
I made this change originally. Using tf.summary.merge_all() is definitely intended, as for tf1.0 we are moving all the summary ops into the tf.summary namespace. I will dig into why the example is broken and fix it while keeping usage of tf.summary.merge_all()

2016-10-27 18:46 UTC, closed without merging