Add --config=tf_lite_linux in .bazelrc
tensorflow/tensorflow pull request #51567
Opened 2021-08-19 07:31 UTC by coeuvre

Both `--config=rbe_cpu_linux` and `--config=rbe_linux_py3` expand to `--config=rbe_linux` which includes link opts for avx instructions. However that won't compile Tensorflow Lite. 

This PR adds `--config=tf_lite_linux` which reuses most of existing flags for build Tensorflow Lite with RBE.

Context: b/195294181

2021-08-19 18:25 UTC, mihaimaruseac requested changes
Can you also document these options in the comments at the beginning of the file please?

2021-08-25 03:47 UTC, coeuvre commented
Added document for the option `rbe_lite_linux`.

2021-08-25 15:26 UTC, mihaimaruseac approved these changes

2021-08-27 11:20 UTC, gbaned approved these changes

2021-08-30 15:24 UTC, merged