Update workspace.bzl
tensorflow/tensorflow pull request #51577
Opened 2021-08-19 17:14 UTC by Saduf2019

Updated Flatbuffers to "2.0" Uas dependency change to "https://github.com/tensorflow/tensorflow/pull/51504"

2021-08-19 17:18 UTC, lgeiger requested changes

2021-08-19 17:18 UTC, lgeiger commented on third_party/flatbuffers/workspace.bzl
>              "https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.12.0.tar.gz",
The download URLs and hash, will also require an update, otherwise the build will fail.

2021-08-19 21:52 UTC, mihaimaruseac commented on third_party/flatbuffers/workspace.bzl
>              "https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v1.12.0.tar.gz",
```suggestion
            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/flatbuffers/archive/v2.0.0.tar.gz",
```

2021-08-19 21:52 UTC, mihaimaruseac commented on third_party/flatbuffers/workspace.bzl
>              "https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz",
```suggestion
            "https://github.com/google/flatbuffers/archive/v2.0.0.tar.gz",
```

2021-08-19 21:53 UTC, mihaimaruseac commented on third_party/flatbuffers/workspace.bzl
>          sha256 = "62f2223fb9181d1d6338451375628975775f7522185266cd5296571ac152bc45",
```suggestion
        sha256 = "9ddb9031798f4f8754d00fca2f1a68ecf9d0f83dfac7239af1311e4fd9a565c4",
```

2021-08-19 21:53 UTC, mihaimaruseac approved these changes

2021-08-19 22:15 UTC, mihaimaruseac commented on third_party/flatbuffers/workspace.bzl
> +        strip_prefix = "flatbuffers-2.0",
```suggestion
        strip_prefix = "flatbuffers-2.0.0",
```

2021-08-19 22:15 UTC, mihaimaruseac approved these changes

2021-08-24 13:34 UTC, gbaned approved these changes

2021-09-15 23:02 UTC, lu-wang-g commented
Flatbuffer 2.0 has some incompatible changes that we need to resolve from internally first. It will be difficult to debug and test from external contribution. Therefore I'll reject this PR for now, and we'll do the upgrade later.

2021-09-15 23:02 UTC, closed without merging