[TFLite] Add TRANSPOSE_CONV_3D operator with int8 and int16 support
tensorflow/tensorflow pull request #51572
Opened 2021-08-19 10:51 UTC by georgeedward2000

Hello,

This PR adds quantizable int8 and int16x8 implementations of Conv3DTranspose operator.
The implementations need code snippets that are present in the PR that adds support for int8 and int16x8 Conv3D operator.

Cheers,
Eddie

2021-08-19 11:18 UTC, abattery commented
@teijeong @thaink could you review this PR?

2021-11-16 13:57 UTC, gbaned commented
@teijeong, @thaink  Can you please review this PR ? Thanks!

2021-12-31 15:32 UTC, gbaned commented
@georgeedward2000 Can you please resolve conflicts? Thanks!

2022-02-09 11:48 UTC, gbaned commented
@georgeedward2000 Can you please resolve conflicts? Thanks!

2022-03-29 11:28 UTC, gbaned commented
@georgeedward2000 Can you please resolve conflicts? Thanks!

2022-04-12 09:46 UTC, SaoirseARM commented
> @georgeedward2000 Can you please resolve conflicts? Thanks!

Thanks, The merge conflict has now been resolved.
Best regards,
Saoirse

2022-06-02 15:16 UTC, gbaned commented
@teijeong, @thaink Can you please review this PR ? Thanks!

2022-09-26 08:52 UTC, abattery commented
@alankelly could you review this PR request?

2022-10-24 14:31 UTC, abattery requested changes

2022-10-24 14:31 UTC, abattery commented on tensorflow/compiler/mlir/lite/ir/tfl_ops.td
> +    AffineOpCoefficient<3, 1>,
Apparently, there are more discussions for which the per channel dimension location should be supported in this operator in the long term.

Could you provide the rationale for your choice here?

2022-11-24 19:16 UTC, gbaned commented
@georgeedward2000 Can you please check @abattery's comments and keep us posted ? Thank you!

2022-12-14 17:09 UTC, gbaned commented
Hi @georgeedward2000 Any update on this PR? Please. Thank you!

2022-12-14 17:28 UTC, Tessil commented
@gbaned We're currently waiting for a reply of @abattery on https://github.com/tensorflow/tensorflow/pull/51527#discussion_r1003403774 which is a similar question. Once we know how to proceed with this other PR, we'll update this one if necessary.

2023-06-23 04:42 UTC, gbaned commented
Hi @abattery Any update on this PR? Please. Thank you!

2023-08-24 08:08 UTC, gbaned commented
Hi @abattery Any update on this PR? Please. Thank you!

2023-09-25 06:51 UTC, gbaned commented
Hi @abattery Any update on this PR? Please. Thank you!

2023-12-22 05:58 UTC, gbaned commented
Hi @grantjensen Any update on this PR? Please. Thank you!

2023-12-29 04:51 UTC, gbaned commented
Hi @grantjensen / @abattery Any update on this PR? Please. Thank you!

2024-02-07 20:20 UTC, grantjensen commented
Dependent on https://github.com/tensorflow/tensorflow/pull/51527. Will wait to give final review until after it is merged...

2024-07-09 06:41 UTC, keerthanakadiri commented
Hi @Linchenn ,Can you please review this PR? Thank you !

2024-07-16 09:16 UTC, keerthanakadiri commented
Hi @georgeedward2000, Can you please resolve the conflicts? Thank you!

2024-07-23 10:07 UTC, keerthanakadiri commented
Hi @georgeedward2000, Can you please resolve the conflicts? Thank you!

2024-08-06 10:04 UTC, keerthanakadiri commented
Hi @georgeedward2000, Can you please resolve the conflicts? Thank you!

2024-09-04 01:58 UTC, closed without merging