Refactor Slice reference op for port to TFLM
tensorflow/tensorflow pull request #51672
Opened 2021-08-25 12:56 UTC by annietllnd

Solves second part of issue #51669, PR2:  Extract the reference implementation out of tensorflow/lite/kernels/internal/reference/reference_ops.h into its own header which can be included without dragging in reference_ops.h's dependences

Change-Id: I1c8e2a4550d9c6fd792b2d5ad0361579b9d437dd

2021-08-27 23:02 UTC, advaitjain requested changes
minor change requested then we're ready to merge. Please feel free to directly tag me on future PRs.

2021-09-02 14:07 UTC, annietllnd commented
@advaitjain Thank you for reviewing, I'm currently working on fixing the Ubuntu Sanity build fail. Did you suggest any other changes for this patch? I am unable to find it in the changes view, therefore I wanted to double-check that I'm not missing anything. BR Annie

2021-09-02 21:00 UTC, advaitjain commented on tensorflow/lite/kernels/internal/reference/slice.h
> +
It appears that I didn't actually comment last time I reviewed.

Can you please add `#include` for the headers that declare SliceParams, RuntimeShape and SequentialTensorWriter?

That will ensure that slice.h follows https://google.github.io/styleguide/cppguide.html#Include_What_You_Use

2021-09-02 21:05 UTC, advaitjain commented
> @advaitjain Thank you for reviewing, I'm currently working on fixing the Ubuntu Sanity build fail. Did you suggest any other changes for this patch? I am unable to find it in the changes view, therefore I wanted to double-check that I'm not missing anything. BR Annie

Apologies, looks like my previous comments got lost. Added a comment this time to IWYU.

The Ubuntu sanity build can sometimes fail for unrelated reasons. Once I approve the PR, it will be imported internally and that is a place where more exhaustive tests run.

2021-09-03 07:54 UTC, advaitjain approved these changes

2021-09-03 07:55 UTC, annietllnd commented
> > @advaitjain Thank you for reviewing, I'm currently working on fixing the Ubuntu Sanity build fail. Did you suggest any other changes for this patch? I am unable to find it in the changes view, therefore I wanted to double-check that I'm not missing anything. BR Annie
> 
> Apologies, looks like my previous comments got lost. Added a comment this time to IWYU.
> 
> The Ubuntu sanity build can sometimes fail for unrelated reasons. Once I approve the PR, it will be imported internally and that is a place where more exhaustive tests run.

Thank you for the helpful reply and for your comments!

2021-09-13 19:43 UTC, advaitjain approved these changes

2021-09-13 19:44 UTC, advaitjain commented
apologies for the delay. [`5a6b185` (#51672)](https://github.com/tensorflow/tensorflow/pull/51672/commits/5a6b185bab38c888a9d487cee9c773d2e7b759f9) fixes a lint error about not having a newline at the end of the file. This PR should be ready to go now.

2021-09-15 19:31 UTC, merged