[PluggableDevice] Add TF_IsHostMemoryInput and TF_IsHostMemoryOutput to the C API
tensorflow/tensorflow pull request #51759
Opened 2021-08-31 03:20 UTC by PatriceVignola

This reduces boilerplate logic in pluggable devices code that decouple operator registration from kernel implementation. This also makes the transition from TF 1.15 to 2.x easier since the same device code in 1.15 would have been able to use `OpKernelContext::input_memory_type`.

2021-11-16 14:17 UTC, gbaned commented
@penpornk Can you please review this PR ? Thanks!

2021-12-31 15:56 UTC, gbaned commented
@penpornk Can you please review this PR ? Thanks!

2022-02-09 11:53 UTC, gbaned commented
@penpornk Can you please review this PR ? Thanks!

2022-03-14 17:00 UTC, penpornk commented
I'm sorry I get to this PR so late. Is this required for TF-DirectML for TF 2.9? Asking because we are having an API freeze starting tomorrow.

2022-03-15 21:24 UTC, rohan100jain commented on tensorflow/c/kernels.cc
> +  CHECK_GE(i, 0);
I'm a little wary of a CHECK failure here - could we return a TF_Status* instead? Here and below

2022-03-15 21:24 UTC, rohan100jain requested changes
Overall looks good!

2022-03-24 01:55 UTC, penpornk commented
@PatriceVignola Could you please help address @rohan100jain's comment? Thank you very much!

2022-03-26 03:01 UTC, PatriceVignola commented
@rohan100jain Thanks for the review! I removed the fatal checks and added a status instead.

2022-06-02 15:17 UTC, gbaned commented
Hi @rohan100jain Can you please review this PR ? Thank you!

2022-07-18 14:03 UTC, gbaned commented
Hi @rohan100jain Can you please review this PR ? Thank you!

2022-07-29 23:46 UTC, rohan100jain approved these changes

2022-08-02 19:58 UTC, merged