Updated log_poisson_loss() function
tensorflow/tensorflow pull request #51765
Opened 2021-08-31 11:01 UTC by Aravind-11

result is updated in the log_poisson_loss(targets, log_input, compute_full_loss=False, name=None) function. For input values too large, error message is displayed instead of returning NaN.

2021-08-31 13:48 UTC, old-school-kid commented
@Aravind-11 
Line 98 
`result = math_ops.exp(log_input) - log_input * target` 
It should be targets instead of target.

2021-08-31 16:12 UTC, mihaimaruseac requested changes
Please also add unit test that fails without this patch and passes with it.

2021-08-31 16:12 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +
Please, no trailing whitespace

2021-08-31 16:12 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +    result = math_ops.exp(log_input) - log_input * target
Typo? This changes semantics

2021-08-31 16:12 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +          (log_input.get_shape(), targets.get_shape()))
Was this discovered as an issue?

2021-09-02 17:20 UTC, mihaimaruseac requested changes
Still no unit test

2021-09-02 17:20 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +
Trailing space is still here

2021-10-04 16:22 UTC, mihaimaruseac requested changes
Still missing unit test.

Also, please make sure to follow Python style guide.

2021-11-16 14:41 UTC, gbaned commented
@Aravind-11 Any update on this PR? Please. Thanks!

2021-11-16 15:43 UTC, Aravind-11 commented
I'm not sure how to add unit test. Can someone help?

2021-11-30 12:25 UTC, gbaned commented
@Aravind-11, @mihaimaruseac Any update on this PR? Please. Thanks!

2021-12-31 15:57 UTC, gbaned commented
@Aravind-11, @mihaimaruseac Any update on this PR? Please. Thanks!

2022-02-09 11:53 UTC, gbaned commented
@Aravind-11, @mihaimaruseac Any update on this PR? Please. Thanks!

2022-03-29 11:30 UTC, gbaned commented
@Aravind-11, @mihaimaruseac Any update on this PR? Please. Thanks!

2022-03-29 14:14 UTC, Aravind-11 commented
Error message is the way to go.

On Tue, 29 Mar 2022 at 7:18 PM, Surya Prakash Mishra <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tensorflow/python/ops/nn_impl.py
> <https://github.com/tensorflow/tensorflow/pull/51765#discussion_r837499362>
> :
>
> > +    if(!result.is_nan()):
> +      raise ValueError(
> +          "Input contains NaN, infinity or a value too large for dtype('float64') (%s vs %s)" %
> +          (log_input.get_shape(), targets.get_shape()))
>
> @Aravind-11 <https://github.com/Aravind-11> can you please answer to
> this. Should it return NaN or an error message is a better way to go?
> TIA
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/51765#discussion_r837499362>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKDCEOVSLAXUBJAXPV6DSSTVCMC2ZANCNFSM5DD3FICQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-29 19:59 UTC, mihaimaruseac commented
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_test.py

2022-03-29 20:00 UTC, mihaimaruseac commented
Also, please change PR title, https://cbea.ms/git-commit/

2022-03-30 05:22 UTC, Aravind-11 commented
Sure!

On Wed, 30 Mar 2022 at 1:30 AM, Mihai Maruseac ***@***.***>
wrote:

> Also, please change PR title, https://cbea.ms/git-commit/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/51765#issuecomment-1082318461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKDCEOW5G36ITHPRGD3S7JDVCNONZANCNFSM5DD3FICQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-19 09:10 UTC, gbaned commented
@Aravind-11 Any update on this PR? Please. Thank you!

2022-06-02 15:18 UTC, gbaned commented
@Aravind-11 Any update on this PR? Please. Thank you!

2022-07-02 00:59 UTC, closed without merging