[PluggableDevice] TensorList support with DEVICE_DEFAULT
tensorflow/tensorflow pull request #51822
Opened 2021-09-03 13:05 UTC by i8run

Use stream apis to enable the TensorList with DEVICE_DEFAULT including memzero, memset and memset32 and it's only enabled with pluggable device.

2021-09-03 13:28 UTC, i8run commented
@penpornk @saxenasaurabh Could you please help to review this PR? It implements the TensorList with stream APIs instead of exposing C APIs when using pluggable device. Thanks.

2021-09-16 16:02 UTC, penpornk requested changes
I'm so sorry for the delay! I have a few quick comments. Will take a closer look later.

2021-09-17 06:46 UTC, i8run commented on tensorflow/core/kernels/list_kernels.cc
> -                            .Device(DEVICE_GPU)
Done. Add `DEVICE_DEFAULT` below the GPU registration.

2021-09-17 06:50 UTC, i8run commented on tensorflow/core/kernels/list_kernels.h
> +      CopyTensor<Device, T>(c, tmp, aligned);
I use a function pointer to implement this in kernels. Do you think it's OK ?

2021-09-17 13:08 UTC, i8run commented on tensorflow/core/kernels/list_kernels.h
> +    CHECK_EQ(true, stream->ThenMemZero(&ptr, tensor.TotalBytes()).ok());
Done.

2021-09-22 20:32 UTC, penpornk approved these changes
Thank you for the changes. I have some more comments but I think I'll just pull the PR and make additional changes internally given that the TF 2.7 branch cut is tomorrow. (Sorry for the delay!)

2021-09-22 20:32 UTC, penpornk commented on tensorflow/core/kernels/list_kernels.h
> +    }
This `if` should be outside the for loop.

2021-09-23 06:37 UTC, merged