extend multi-threaded MapDataset based tests to eager mode
tensorflow/tensorflow pull request #51873
Opened 2021-09-08 05:15 UTC by kvignesh1420

This PR attempts to extend the multi-threaded map dataset tests to eager mode.

The `cached_session` context is left untouched as it yields a dummy eager session that simulates execution in eager mode.
TEST LOG
```
INFO: Build completed successfully, 20 total actions
//tensorflow/python/data/kernel_tests:map_test                           PASSED in 33.1s
  Stats over 19 runs: max = 33.1s, min = 15.3s, avg = 20.5s, dev = 4.2s

INFO: Build completed successfully, 20 total actions
```

cc: @aaudiber I tried removing the session context and executing these tests with eager only combinations and it worked fine. However, the tests fail when the `cached_session` is not used during thread `start` and `join` steps in graph mode. Thus, I kept the `cached_session` intact and let it handle the eager scenarios. Let me know what you think of this approach.

2021-09-08 15:23 UTC, aaudiber approved these changes

2021-09-14 14:51 UTC, gbaned approved these changes

2021-09-14 15:00 UTC, jsimsa requested changes
This PR should not be submitted as is. To add both graph and eager mode coverage, the tests should be refactored to use self.evaluate() (which abstracts away the mode of execution) instead of relying on sessions explicitly. While using session in eager mode is technically possible (which is why this PR passes test), it is not how eager mode is normally used.

2021-09-15 10:03 UTC, kvignesh1420 commented
@jsimsa I tried to run the test cases without explicitly using the session and by using the `self.evaluate` method in both eager and graph modes. However, the `graph` mode execution fails with:

```console
AssertionError: Error in checkedThread: Unsupported type <class 'tensorflow.python.framework.ops.Tensor'>.

AssertionError: A checked thread was not joined.
```

Also, the eager mode execution was a bit flaky when it comes to multi-threaded iterations.
cc: @aaudiber

2021-10-06 15:33 UTC, jsimsa commented
I do not have bandwidth to assist @kvignesh1420 to figure out how to add support for the missing test. If he is blocked resolving the issues he has encountered, my suggestion would be to close this PR.

2022-02-09 11:59 UTC, gbaned commented
@kvignesh1420  Any update on this PR? Please. Thanks!

2022-02-09 18:18 UTC, kvignesh1420 commented
@gbaned I think it's better to close this PR as I currently don't have access to the computing systems that I previously had at IBM.

2022-02-09 18:18 UTC, closed without merging