[issue#4453]Get rid of the variable_op wrapper.
tensorflow/tensorflow pull request #5198
Opened 2016-10-25 17:26 UTC by DjangoPeng

PR for the `  # TODO(mrry): Move this to where it is used, so we can get rid of this op wrapper?`
in the [state_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/state_ops.py#L151)

Details refer to [issue#4453](https://github.com/tensorflow/tensorflow/issues/4453)

Changed file list which call the `state_ops.variable_op()`:
```
Variables.py
Variables_test.py
Tensor_util_test.py
Moving_averages_test.py
Learning_rate_decay_test.py
Graph_util_test.py
Control_flow_ops_py_test.py
```

@drpngx Please review

2016-10-25 21:41 UTC, mrry commented
I think @drpngx has been looking at the necessary API changes for the internal version, so I'll defer to his good judgement on this PR :).

2016-10-25 22:36 UTC, drpngx requested changes
Thanks! Some suggestions to have more informative names.

2016-10-25 22:36 UTC, drpngx commented on tensorflow/python/framework/graph_util_test.py
> +          name="Variable", set_shape=True, container="", shared_name="")
Prefer using name="var_1" etc to have more informative names in the graph.

2016-10-25 22:36 UTC, drpngx commented on tensorflow/python/kernel_tests/variables_test.py
> +              name="Variable", set_shape=True, container="l3", shared_name="")
Use something like VariableInL3

2016-10-25 22:36 UTC, drpngx commented on tensorflow/python/training/learning_rate_decay_test.py
> +          name="Variable", set_shape=True, container="", shared_name="")
Use name="Step" and everywhere below

2016-10-26 15:19 UTC, DjangoPeng commented
@drpngx Update `name` of all variables with more info.

2016-10-26 15:22 UTC, drpngx commented
Jenkins, test this please.

2016-10-26 15:53 UTC, drpngx commented
Oh, there's no set_shape. Could you fix & check?

2016-10-26 15:58 UTC, DjangoPeng commented
It seems like that I have to use `var.set_shape()` instead of passing the `set_shape` arg into `gen_state_ops._variable()`.

2016-10-26 16:44 UTC, DjangoPeng commented on tensorflow/python/training/moving_averages_test.py
> +      v1.set_shape([1])
Only this test need to set shape, so I don't `set_shape` for other tests. 
I have run all test scripts at local, and I think they would pass the test this time.

2016-10-26 16:44 UTC, DjangoPeng commented
@drpngx Fixed, please check and test.

2016-10-26 17:10 UTC, drpngx commented
Jenkins, test this please.

2016-10-26 17:47 UTC, drpngx commented
You need to change the `control_flow_ops_test`.

2016-10-26 18:06 UTC, drpngx commented
We also have internal changes that might interfere with this. We'll merge them soon. Stay tuned.

2016-10-27 14:54 UTC, DjangoPeng commented
@drpngx Sorry, I forget `Control_flow_ops_py_test.py`.  
Look forward to your good news :).

2016-10-27 16:27 UTC, drpngx commented
Jenkins, test this please.

2016-10-28 14:50 UTC, DjangoPeng commented
@drpngx It says there is a conflicting file named `variables.py`, while I can't find where to check the conflicts. Do you know how to handle it?

2016-10-28 15:23 UTC, drpngx commented
If you pull the latest and rebase , it should show you. if there is no
conflict,then just check the tests and push

On Oct 28, 2016 7:52 AM, "Jingtian Peng" <notifications@github.com> wrote:

> @drpngx <https://github.com/drpngx> It says there is a conflicting file
> named variables.py, while I can't find where to check the conflicts. Do
> you know how to handle it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/5198#issuecomment-256941107>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT_SbRZOywVdquuLJwEKUsp1PeJ05QQHks5q4gw5gaJpZM4KgQsV>
> .
>

2016-10-28 16:16 UTC, DjangoPeng commented
@mrry updated `variables.py` yesterday. Luckily, I find the conflict and work on it.@drpngx

2016-10-28 16:34 UTC, drpngx commented
Jenkins, test this please.

2016-10-28 16:40 UTC, DjangoPeng commented
@drpngx I resolved the conflicts manually. Do I need to `reset --hard origin/master` and update code to push a new commit?

2016-10-30 03:02 UTC, DjangoPeng commented
@drpngx I reset the branch and `commit -am`. Please test the change, thanks.

2016-10-30 06:51 UTC, drpngx commented
Jenkins, test this please.

2016-10-30 07:28 UTC, drpngx commented
Jenkins, test this please.

2016-10-31 00:45 UTC, DjangoPeng commented
@drpngx LGTM

2016-10-31 00:48 UTC, drpngx approved these changes

2016-10-31 00:48 UTC, merged