Refactor SparseSliceGradOp to use a functor
tensorflow/tensorflow pull request #52007
Opened 2021-09-15 12:00 UTC by benbarsdell

- This is in preparation for adding a GPU implementation.
- No functional change.
- Also adds some explicit tests.

cc @nluehr

2021-10-06 15:15 UTC, gbaned commented
@penpornk Can you please review this PR ? Thanks!

2021-11-30 12:39 UTC, gbaned commented
@benbarsdell Can you please resolve conflicts? Thanks!

2021-12-09 11:13 UTC, benbarsdell commented
Rebased (strangely I didn't get any conflicts).

2021-12-13 11:09 UTC, benbarsdell commented
Rebased again.

2022-02-23 23:08 UTC, penpornk requested changes
Thank you for the PR and I'm so, so sorry for the delay!
I have one nit.

2022-02-23 23:08 UTC, penpornk commented on tensorflow/python/kernel_tests/sparse_ops/sparse_slice_op_test.py
> +
Thank you for formatting them this way! This is easy to read.

2022-02-25 17:55 UTC, penpornk approved these changes
Thank you again for your patience!

2022-03-03 12:25 UTC, benbarsdell commented
Rebased.

2022-03-03 15:56 UTC, penpornk approved these changes
Thank you for rebasing!

2022-03-03 20:02 UTC, merged

2022-03-04 03:18 UTC, benbarsdell commented
Out of interest, what's up with all the `FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/tensorflow/tensorflow/pull/52007` in unrelated commits?