Fix segfault with static unpack nodes
tensorflow/tensorflow pull request #52039
Opened 2021-09-16 18:57 UTC by dimitarz

Models that have dequantize operations can occasionally cause a segfault because the tensors are skipped in the delegate creation process and the code tries to get an element from an empty array which is undefined.

2021-09-20 04:59 UTC, gbaned commented
@dimitarz Can you please sign CLA. Thanks!

2021-09-29 16:08 UTC, dimitarz commented
@googlebot I fixed it.

2021-09-29 16:09 UTC, dimitarz commented
@googlebot I consent.

2021-09-29 16:55 UTC, dimitarz commented
@googlebot I consent.

2021-10-01 17:01 UTC, dimitarz commented
@mihaimaruseac The AMD ROCm build failed. I can't seem to be able to access the build job to see what went wrong. Any guidance would be appreciated.

2021-10-04 19:35 UTC, mihaimaruseac requested changes

2021-10-04 19:35 UTC, mihaimaruseac commented on tensorflow/lite/delegates/xnnpack/xnnpack_delegate.cc
> +    std::vector<uint32_t> xnnpack_tensors(tensor_size);
Shouldn't `tensor_size` be `tensors.size()`? (and then potentially check that this is equal to `tensors.back() + 1`)

Imagine a scenario where `tensors` has 4 elements but the last one is 2 (e.g., it is `[0,0.1.2]` after above sorting). We make `xnnpack_tensors` have 3 elements but then the for loop below runs for 4 iterations, so it writes outside of bounds.

2021-11-30 12:41 UTC, gbaned commented
@dimitarz Any update on this PR? Please. Thanks!

2021-12-31 00:53 UTC, closed without merging