[oneDNN] Fixing eager-related nightly test failures
tensorflow/tensorflow pull request #52204
Opened 2021-09-30 18:19 UTC by mahmoud-abuzaina

This PR fixes : //tensorflow/python/kernel_tests:matmul_op_test and run_eager_op_as_function_test,
These tests which are run with eager op as function enabled, fail with error , "Could not find device for node:"

With a recent commit on public tensorflow : tensorflow/tensorflow@1224326
Eager ops are wrapped, inside function WrapInCallOp, after the device has been inferred for op.

For MKL : we expect WrapInCallOp to be called before we infer device, which marks the '_kernel' attribute as NameChangeOp label for nodeDef of funcDef.
Since with new commit, WrapInCallOp is called AFTER the device inference, no device is found for the MKL Op as no kernel match is found without namechange label.

In this PR: we mark nodeDef with '_kernel' attribute as NameChange label at both places : a) before inferring the device and b) inside WrapInCallOp (already present in current code base)

2021-10-01 05:57 UTC, kkimdev commented
@saxenasaurabh It sounds like related to the eager-op-as-function project, Could you take a look at this?

2021-10-06 07:03 UTC, penpornk requested changes
Thank you for the fix!

2021-10-06 07:03 UTC, penpornk commented on tensorflow/core/common_runtime/eager/execute.cc
> +void GetMKLNodeDef(NodeDef* ndef) {
Can we make this an inline function?

2021-10-06 19:06 UTC, sachinmuradi commented
@googlebot I consent.

2021-10-06 19:17 UTC, sachinmuradi commented on tensorflow/core/common_runtime/eager/execute.cc
> +void GetMKLNodeDef(NodeDef* ndef) {
Changes done.

2021-10-07 12:31 UTC, penpornk approved these changes
Thank you for the change!

2021-10-11 17:01 UTC, merged