fix moments float16 cast bug
tensorflow/tensorflow pull request #52217
Opened 2021-10-01 13:11 UTC by fsx950223

Related https://github.com/tensorflow/addons/issues/2550.
Reproduce example:
```python
tf.debugging.enable_check_numerics()
tf.nn.moments(tf.constant([[[[[ -741., 353.2, 1099., -1807. ,502.8, -83.4, 333.5, -130.9]]]]], dtype=tf.float16), [1, 2, 4], True)
```

2021-10-04 20:03 UTC, mihaimaruseac requested changes
Can you also add a test please?

2021-10-05 15:41 UTC, mihaimaruseac approved these changes

2021-11-30 14:43 UTC, gbaned approved these changes

2021-11-30 17:42 UTC, mihaimaruseac approved these changes

2022-01-31 06:47 UTC, shkarupa-alex commented
Still waiting for merging this fix

2022-02-11 10:40 UTC, bhack commented
@mihaimaruseac What issue we have internally?

2022-03-08 18:43 UTC, bhack commented
Just a reminder: we don't have copybara visibility, any feedback here?

2022-08-26 07:17 UTC, shkarupa-alex commented
Any plans to merge this fix?

2022-12-28 18:29 UTC, mihaimaruseac commented
@gbaned another one which had the old CLA and failed to import. Needed to force trigger new CLA scan and then it works

2022-12-28 18:33 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_test.py
> +
```suggestion
```

2022-12-28 18:33 UTC, mihaimaruseac approved these changes

2022-12-28 18:47 UTC, mihaimaruseac requested changes
This fails test `MomentsTest.testFloat16` in `//tensorflow/python:nn_test_cpu`:

```
...tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: Using a symbolic `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

Please fix

2023-02-22 11:24 UTC, gbaned commented
Hi @fsx950223 Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

2023-03-21 17:51 UTC, gbaned commented
Hi @fsx950223 Any update on this PR? Please. Thank you!

2023-03-25 09:25 UTC, closed without merging

2023-03-27 06:56 UTC, shkarupa-alex commented
Can anybody tell the reason why this PR was rejected?