Update MklMatMulPrimitiveFactory to support Arm Compute Library backend
tensorflow/tensorflow pull request #52261
Opened 2021-10-05 14:22 UTC by cfRod

Related to issue #47415 and PR #47775. Adding support for caching matmul primitives.
Updates onednn_acl_primitives.patch to include matmul primitives.

2021-10-06 08:56 UTC, penpornk requested changes
Thank you for the PR!

2021-10-06 08:56 UTC, penpornk commented on tensorflow/core/kernels/mkl/mkl_matmul_ops_common.h
> +  key_creator.AddAsKey(params.randn);
Nit: Indentation seems to be off.

2021-10-06 16:26 UTC, cfRod commented on tensorflow/core/kernels/mkl/mkl_batch_matmul_op.cc
> +    params->randn = rand();
Thanks I will resolve this!

2021-10-07 10:52 UTC, penpornk approved these changes
Thank you for the changes! :)

2021-10-08 14:58 UTC, merged

2021-10-11 09:23 UTC, cfRod commented
@penpornk thanks!
If this can be cherry-picked onto 2.7 rls that would be great!