Remove C++ content from tensorflow/c/c_api_macros.h
tensorflow/tensorflow pull request #52313
Opened 2021-10-09 23:10 UTC by yongtang

This PR tries to remove C++ conent from tensorflow/c/c_api_macros.h
so that it is possible to include this file from an external plugin
without depending on tensorflow's C++ headers (tensorflow/core/platform/status.h).

The reason for this move is that for external plugins (e.g., file systems plugins)
that utilize C API, it cannot include status.h as otherwise the whole tensorflow's
C++ library will be a dependency. This defeat the purpose of C APi modular plugin.

This PR place C++ content to tensorflow/core/platform/status.h instead so that
everything will still be combined both for C external plugins and C++ plugins.

(Note the C++ inclusion was added in PR #51647.)

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2021-10-13 16:53 UTC, mihaimaruseac commented
Hmm, can you post what the error message is?

These lines got added recently via #51647 (manual import + fix) as Intel needed this for the 2.7 release.

CC @penpornk

2021-10-15 10:22 UTC, penpornk requested changes
@yongtang Thank you for the explanation! I agree with refactoring them out. However, I don't think `platform/status.h` is the right place. 

Would you mind creating a new file `//tensorflow/c/c_api_macros_internal.h`? (This will also require updating the dependencies to `c_api_macros.h` for `//tensorflow/c/experimental/stream_executor` and `//tensorflow/c/experimental/pluggable_profiler`.) -- Or I can also do it. Let me know.

2021-10-15 14:46 UTC, penpornk approved these changes
Thank you very much!

2021-10-18 17:28 UTC, mihaimaruseac approved these changes

2021-10-22 21:43 UTC, merged