[tensorflow/compiler/xla/service/shape_inference.cc] Add calls to `reserve()` before populating vectors
tensorflow/tensorflow pull request #52418
Opened 2021-10-15 03:29 UTC by SamuelMarks

https://github.com/tensorflow/tensorflow/pull/51739#issuecomment-940389562 told me to split the larger PR into one PR per file; thus this (thanks `bash`, `git` and `gh`!)

2021-10-15 11:11 UTC, akuegel requested changes

2021-10-18 06:29 UTC, akuegel requested changes

2021-10-20 14:18 UTC, SamuelMarks commented
@gbaned / @akuegel With no leading spaces?! - Ok, you're the boss

2021-10-20 14:32 UTC, akuegel requested changes

2021-10-20 14:34 UTC, akuegel requested changes

2021-10-25 07:35 UTC, akuegel approved these changes

2021-10-26 08:46 UTC, merged