[tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc] Add calls to `reserve()` before populating vectors
tensorflow/tensorflow pull request #52437
Opened 2021-10-15 03:33 UTC by SamuelMarks

https://github.com/tensorflow/tensorflow/pull/51739#issuecomment-940389562 told me to split the larger PR into one PR per file; thus this (thanks `bash`, `git` and `gh`!)

2021-10-15 10:43 UTC, akuegel requested changes

2021-10-18 06:17 UTC, akuegel approved these changes

2021-10-19 07:54 UTC, akuegel requested changes

2021-10-21 07:53 UTC, gbaned commented
@SamuelMarks Can you please check @joker-eph's comments and keep us posted ? Thanks!

2021-10-21 23:51 UTC, SamuelMarks commented
@gbaned Done

2021-10-22 01:40 UTC, joker-eph approved these changes

2021-10-25 07:44 UTC, akuegel approved these changes

2021-10-25 08:28 UTC, merged