[tensorflow/compiler/xla/service/gpu/ir_emission_utils.cc] Add calls to `reserve()` before populating vectors
tensorflow/tensorflow pull request #52439
Opened 2021-10-15 03:33 UTC by SamuelMarks

https://github.com/tensorflow/tensorflow/pull/51739#issuecomment-940389562 told me to split the larger PR into one PR per file; thus this (thanks `bash`, `git` and `gh`!)

2021-10-15 10:44 UTC, akuegel approved these changes

2021-10-20 14:19 UTC, akuegel requested changes

2021-10-20 14:45 UTC, akuegel approved these changes

2021-10-22 01:35 UTC, joker-eph requested changes

2021-11-09 22:40 UTC, SamuelMarks commented on tensorflow/compiler/xla/service/gpu/ir_emission_utils.cc
> +  for (const llvm::APInt& d : dimensions) {
Fixed

2021-11-09 22:41 UTC, SamuelMarks commented on tensorflow/compiler/xla/service/gpu/ir_emission_utils.cc
> +  for (const llvm::APInt& d : dimensions) {
Fixed, though I'm not sold on `SmallVector` not needing reservations.

2021-11-09 23:31 UTC, joker-eph approved these changes

2021-11-09 23:33 UTC, joker-eph commented on tensorflow/compiler/xla/service/gpu/ir_emission_utils.cc
> +  for (const llvm::APInt& d : dimensions) {
You could collect statistics if you wanted:

Just collect the `vector.capacity()` before and after the loop to see if it changed, and print it out to a file. Then run all the tests and see...

2021-11-11 14:06 UTC, gbaned approved these changes

2021-11-11 14:44 UTC, merged