[tensorflow/compiler/xla/client/lib/comparators_test.cc] Add calls to `reserve()` before populating vectors
tensorflow/tensorflow pull request #52523
Opened 2021-10-15 21:28 UTC by SamuelMarks

https://github.com/tensorflow/tensorflow/pull/51739#issuecomment-940389562 told me to split the larger PR into one PR per file; thus this (thanks `bash`, `git` and `gh`!)

2021-10-15 21:53 UTC, bhack commented
I think that you could group your change with 1 PR x folder. Eg 1 PR for all the changes for the `xla` folder. 
If you still have too much PRs I think that you could open 1 PR for the whole parent folder `compiler`

2021-10-21 08:46 UTC, akuegel requested changes

2021-10-25 07:36 UTC, akuegel approved these changes

2021-10-26 13:22 UTC, gbaned approved these changes

2021-10-28 06:58 UTC, merged