Fixes #37768 by updating '>" with ">="
tensorflow/tensorflow pull request #53065
Opened 2021-11-15 11:58 UTC by mohantym

Compiling issue #37768 on epsilon condition as per users input `"the value of epsilon is required to be greater or equal to CUDNN_BN_MIN_EPSILON which was defined in the cudnn.h file to the value 1e-5. This threshold value is now lowered to 0.0 to allow a wider range of epsilon value.` in this [document ](https://docs.nvidia.com/deeplearning/cudnn/release-notes/)

2021-11-15 15:47 UTC, mihaimaruseac approved these changes

2021-11-16 07:51 UTC, ppwwyyxx commented
This is not what the issue meant. 
CuDNN doc says "This threshold value is now lowered to 0.0 to allow a wider range of epsilon value". So the correct fix is to change `min_epsilon` to 0.

2021-11-16 17:03 UTC, mihaimaruseac requested changes

2021-11-16 17:03 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
>    # Set a minimum epsilon to 1.001e-5, which is a requirement by CUDNN to
Comment is now wrong.

2021-11-17 11:03 UTC, mohantym commented on tensorflow/python/ops/nn_impl.py
>    # Set a minimum epsilon to 1.001e-5, which is a requirement by CUDNN to
updated comment. Thanks!

2021-11-17 17:02 UTC, mihaimaruseac requested changes
Now you are no longer following the review from this comment https://github.com/tensorflow/tensorflow/pull/53065#issuecomment-969971493

2021-11-17 17:02 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +
Please don't add new empty lines

2021-11-18 15:56 UTC, mihaimaruseac commented
Still not following the comment review

2021-11-29 22:03 UTC, mihaimaruseac approved these changes

2021-12-21 21:28 UTC, mihaimaruseac requested changes

2021-12-21 21:28 UTC, mihaimaruseac commented on tensorflow/python/eager/backprop.py
> +  >>> dz_dw = tape.gradient(z, w)
This change does not matter

2021-12-22 18:20 UTC, mihaimaruseac approved these changes

2022-01-06 13:45 UTC, gbaned approved these changes

2022-03-22 11:56 UTC, mohantym commented
Hi @mihaimaruseac ! Shall we close this pull request? it has been going through a lot of loops for a long time now. I am afraid it might disturb the peace of processes happening here.

2022-03-22 17:40 UTC, mihaimaruseac commented
I don't have time to see why the internal tests are failing. If you can take a look and fix them that would be great.

2022-10-22 01:32 UTC, mihaimaruseac commented
Let's just close this, unless you can check why the internal tests are failing.

2022-10-23 00:47 UTC, mohantym commented
@mihaimaruseac !
Agreed ! Closing this PR as internal testing are failing.
Thank you!

2022-10-23 00:47 UTC, closed without merging