Extend TF:TRT C++ API to handle non-frozen models
tensorflow/tensorflow pull request #53082
Opened 2021-11-16 14:06 UTC by tfeher

This PR extends the C++ converter API of TF-TRT #52012 to handle models that are not frozen (i.e. contain variables).

Depends on #52595. Tracker #45481.

2021-12-07 20:35 UTC, rthadur commented
@tfeher could you please resolve conflicts ?

2021-12-08 11:29 UTC, tfeher commented
Conflicts resolved, tagging @bixia1 for review.

2022-02-14 04:51 UTC, bixia1 approved these changes

2022-02-14 14:03 UTC, gbaned commented
@tfeher Can you please address Ubuntu Sanity errors? Thanks!

2022-02-15 16:44 UTC, tfeher commented
Addressed sanity errors. Also rebased and fixed missing argument that was introduced in #53507.

2022-03-01 18:52 UTC, bixia1 approved these changes

2022-03-01 21:29 UTC, bixia1 requested changes

2022-03-01 21:29 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/BUILD
> +        "//tensorflow/cc/tools:freeze_saved_model",
this causes a cycle in dependency.

2022-03-07 19:02 UTC, tfeher reviewed
@bixia1 I have fixed the issue. Let me know if you have a different suggestion for resolving the cycle.

2022-03-08 16:26 UTC, bixia1 approved these changes

2022-03-09 17:35 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/BUILD
> +
This filegroup is not used?

2022-03-09 17:35 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/BUILD
> -        ":trt_convert_api",
Can you pass tensorflow/compiler/tf2tensorrt:convert_qdq_test_gpu?
I got this error: third_party/tensorflow/compiler/tf2tensorrt/convert/ops/quantization_ops_test.cc:33:10: fatal error: 'third_party/tensorflow/compiler/tf2tensorrt/trt_convert_api.h' file not found
#include "third_party/tensorflow/compiler/tf2tensorrt/trt_convert_api.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2022-03-09 17:35 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/trt_convert_api.h
> +#include "tensorflow/cc/saved_model/loader.h"
I need to remove this line, and instead just add a forward declaration
struct SavedModelBundle;

2022-03-11 13:53 UTC, gbaned commented
@tfeher Can you please check @bixia1's comments and keep us posted ? Thanks!

2022-03-15 23:13 UTC, merged