[TF:TRT] Fix TrtUniquePtr warnings/error for TRT 8.2
tensorflow/tensorflow pull request #53117
Opened 2021-11-18 21:22 UTC by christopherbate

In TensorRT 8.2, the `destroy` method was deprecated for API objects. Instead, API users are expected to use `delete` or standard managed pointers after receiving a pointer to an API object created by TensorRT. This change is applied to the `TrtUniquePtr` type used through TF-TRT.

2021-11-18 21:22 UTC, christopherbate commented
Request review from @bixia1

2021-11-18 22:00 UTC, bixia1 approved these changes

2021-11-19 00:30 UTC, christopherbate commented
Please hold off on merging this

2021-11-19 17:54 UTC, bixia1 commented
I requested change, that is the only way I can hold off the merge.

2021-11-22 15:39 UTC, bixia1 requested changes
Per the author's request, holding this back from merging

2021-11-22 20:51 UTC, christopherbate commented
This is fine to merge

2021-11-23 16:11 UTC, bixia1 approved these changes

2021-11-23 19:21 UTC, merged