[MHLO]: variadic length input and different types of reduce op lower …
tensorflow/tensorflow pull request #53232
Opened 2021-11-29 13:19 UTC by lipracer

…to linalg

2021-12-01 04:05 UTC, lipracer commented on tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc
>      }
all of reduce's inputs has same rank, I think just need to find the ranked tensor.

2021-12-02 05:08 UTC, stellaraccident approved these changes
Thank you so much - this was a pleasant surprise to find that someone had fixed https://github.com/google/iree/issues/7748

2021-12-02 05:38 UTC, jpienaar approved these changes

2021-12-02 21:17 UTC, joker-eph approved these changes
Approving again, there seems to be an issue with the infra, if it does not go through we may need to rebase this (or I'll import manually)

2021-12-03 02:40 UTC, lipracer commented
I have rebased on the latest.

2021-12-03 04:49 UTC, joker-eph requested changes

2021-12-03 04:49 UTC, joker-eph commented on tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc
> +    for (auto it : llvm::enumerate(adaptor.inputs())) {
You marked it as resolved but the code isn't updated?

2021-12-03 04:49 UTC, joker-eph commented on tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc
> +    for (auto it : llvm::enumerate(op.getOperation()->getOperands()))
clang-tidy complains about this (and annoyingly this is blocking the commit), it wants `const auto &it` here.

2021-12-04 01:14 UTC, joker-eph commented on tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc
> +    for (auto it : llvm::enumerate(adaptor.inputs())) {
Can you comment on this? You updated the PR again but you didn't answer here, nor applied the change I believe?

2021-12-04 01:15 UTC, joker-eph commented
See the conversion inline above : https://github.com/tensorflow/tensorflow/pull/53232#discussion_r758829334

2021-12-04 04:15 UTC, lipracer commented
> See the conversion inline above : [#53232 (comment)](https://github.com/tensorflow/tensorflow/pull/53232#discussion_r758829334)

Sorry. I misread it.

2021-12-07 12:47 UTC, lipracer commented
> See the conversion inline above : [#53232 (comment)](https://github.com/tensorflow/tensorflow/pull/53232#discussion_r758829334)

@joker-eph  Sorry. I misread it. please review again.

2021-12-07 20:32 UTC, rthadur approved these changes

2021-12-08 02:34 UTC, lipracer commented
Rebase on latest.

2021-12-08 15:42 UTC, rthadur approved these changes

2021-12-08 16:34 UTC, lipracer commented
windows bazel build error log:
 ```external/llvm-project/llvm/lib/IR/AutoUpgrade.cpp(3726): fatal error C1061: compiler limit: blocks nested too deeply```
It seems that visual studio does not support variadic templates very well。：）
Should I update the code base? I think it's not my PR problem.

2021-12-09 14:36 UTC, lipracer commented
I found the llvm build in the error log.I think it’s not caused by my code. I don't have a windows environment, should I build one or update my code base?

2021-12-13 22:49 UTC, rthadur approved these changes

2021-12-14 00:13 UTC, merged