Extract a function for parsing operator MIRROR_PAD
tensorflow/tensorflow pull request #53311
Opened 2021-12-06 08:35 UTC by mansnils

Extract the parsing of op parameters from the flatbuffer out of a
switch statement case, into a standalone function which can be
called by the micro op resolver.

This PR is part of the work to port operator MIRROR_PAD
from TFL to TFLM, as tracked in issue https://github.com/tensorflow/tflite-micro/issues/741.

2021-12-06 19:46 UTC, advaitjain requested changes
minor comment, and then we can merge this PR.

2021-12-06 19:46 UTC, advaitjain commented on tensorflow/lite/core/api/flatbuffer_conversions.cc
> +// selective registration for the OpResolver implementation in micro.
remove this comment

2021-12-07 06:52 UTC, mansnils commented on tensorflow/lite/core/api/flatbuffer_conversions.cc
> +// selective registration for the OpResolver implementation in micro.
done!

2021-12-07 07:04 UTC, advaitjain approved these changes

2021-12-08 00:39 UTC, merged