Explicitly reset interpreter to prevent memory leaks when using delegate
tensorflow/tensorflow pull request #53376
Opened 2021-12-09 19:08 UTC by NAgarwalla

Internally at Broadcom, we ran into a memory leak when running the label_image app using an external HW delegate.  The delegate was freed/released before the some of the graph data, causing our libraries to report an memory leak.

The fix, calling "Interpreter.reset()" is already done in other test apps.  E.g. see: https://github.com/tensorflow/tensorflow/commit/23873d4d6518a6f169600a076001dc2d7a661dd0 by @terryheo 

Change-Id: I884cde7e31d84b1bcd7b90fe77eb4b2321f3df0c

2021-12-09 23:12 UTC, mihaimaruseac requested changes
`interpreter` is a `std::uniqe_ptr`. Calling `reset` or reaching end of scope are equivalent, both should call the destructor of the internal object wrapped by the smart pointer.

Are we sure this is the right fix?

2021-12-10 00:26 UTC, NAgarwalla commented
@mihaimaruseac, Yes, the destructor called at the end of scope, but the order of freeing memory matters when using a delegate because the memory may be owned/managed by the delegate itself.  The interpreter contains references to data structures that may have been allocated by the delegate.  Without this fix, the delegate is destroyed **before** the interpreter.  Our delegate detects and reports a warning about the memory leak.  The proposed fix forces the interpreter to free the memory before the delegate is destroyed.

Technically, in either case, the memory is _eventually_ freed, but the current implementation is simply not correct since the memory might be end up being used elsewhere.  

You'll see that many other example apps also explicitly call interpreter.reset().  I'm only adding the same fix to the label_image example app.

Perhaps a better solution is, at the end of scope, to somehow destroy interpreter before the delegate.

2021-12-10 01:24 UTC, terryheo commented on tensorflow/lite/examples/label_image/label_image.cc
> +
Could you add comment like below?
```
  // Destory the interpreter earlier than delegates objects.
```

2021-12-10 23:29 UTC, mihaimaruseac approved these changes

2021-12-11 22:13 UTC, Neilblaze approved these changes

2021-12-13 00:25 UTC, terryheo approved these changes

2021-12-13 18:24 UTC, merged