Update gpu_advanced.md
tensorflow/tensorflow pull request #53797
Opened 2022-01-17 18:16 UTC by Saduf2019

Updating "thThis" "This" as per #53775

2022-01-18 03:49 UTC, gbaned approved these changes

2022-01-19 15:23 UTC, mihaimaruseac approved these changes

2022-01-19 15:23 UTC, mihaimaruseac commented
In the future, can you try to fix multiple typos at once, please? It doesn't make sense to run all of these hours of CI for just 1-2 letters changes.

2022-01-20 13:14 UTC, gbaned commented
@Saduf2019  Can you please check @mihaimaruseac's comments and resolve conflicts?. Thanks!

2022-01-20 16:25 UTC, mihaimaruseac requested changes

2022-01-20 16:25 UTC, mihaimaruseac commented on tensorflow/lite/g3doc/performance/gpu_advanced.md
> +This improvement is is achieved by exchanging disk space for time savings. You
```suggestion
This improvement is achieved by exchanging disk space for time savings. You
```

2022-01-20 16:27 UTC, mihaimaruseac commented
6eb4c6bc38c81b54b93b063bee41dbe530b4174f

2022-01-20 16:27 UTC, closed without merging