[TFLite] Check that the SameOperandsAndResultsScale trait of the Maximum/Minimum ops is respected
tensorflow/tensorflow pull request #54077
Opened 2022-01-25 16:57 UTC by Tessil

Hello,

The Maximum/Minimum ops requires the scaling and zero-point to be the same for the inputs and outputs. This PR adds an extra check in the Prepare method of the ops to avoid failing silently if it isn't the case due to wrongly set quantization parameters in a TFLite file.

Thibaut

2022-04-19 12:00 UTC, gbaned commented
@renjie-liu Can you please review this PR ? Thank you!

2022-04-20 02:08 UTC, renjie-liu approved these changes

2022-10-24 14:36 UTC, abattery requested changes

2022-10-24 15:21 UTC, Tessil commented on tensorflow/lite/kernels/maximum_minimum.cc
> +  TF_LITE_ENSURE_EQ(context, op_context.input1->params.scale,
Thanks for the review. 

I double-checked the max and min kernel and I might be missing something but I don't see any scale nor zero-point handling. Just raw comparisons which would not work with some different scaling.

`TFL_MaximumOp` has a `SameOperandsAndResultsScale` trait while `BuiltinOperator_MAXIMUM` in `tensorflow/lite/tools/optimize/operator_property.cc` has `property.restrict_same_input_output_scale = [](TensorType) { return true; };` (still used for int16).

2022-10-25 04:49 UTC, abattery approved these changes

2022-10-29 02:58 UTC, abattery commented
Due to the historical reasons, there are a few cases that still do not meet non same scale requirements. It will take some times..

2022-10-29 02:59 UTC, abattery requested changes
Making it unresolved for now

Due to the historical reasons, there are a few cases that still do not meet non same scale requirements. It will take some times to resolve..

2022-11-24 20:35 UTC, gbaned commented
Hi @abattery Any update on this PR? Please. Thank you!

2022-12-14 17:53 UTC, gbaned commented
Hi @abattery Any update on this PR? Please. Thank you!

2023-02-22 11:29 UTC, gbaned commented
Hi @abattery Any update on this PR? Please. Thank you!

2023-03-21 17:54 UTC, gbaned commented
Hi @abattery Any update on this PR? Please. Thank you!

2023-07-31 15:40 UTC, Tessil commented
@renjie-liu @abattery Any news on this? Some old models are silently failing due to that as the inputs have different zero-point and scaling but the kernel assumes they are the same. The wrong minimum is then returned. It'll error on some older models but I think a hard failure is easier to manage than such silent failures/bugs.

2023-08-24 08:14 UTC, gbaned commented
Hi @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2023-09-25 07:09 UTC, gbaned commented
Hi @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2023-11-07 08:21 UTC, gbaned commented
Hi @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2023-11-07 08:23 UTC, gbaned commented
Hi @yyoon / @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2023-12-14 05:58 UTC, gbaned commented
Hi @yyoon / @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2023-12-29 04:57 UTC, gbaned commented
Hi @yyoon / @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2024-01-19 04:58 UTC, gbaned commented
Hi @yyoon / @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2024-03-08 14:51 UTC, gbaned commented
Hi @yyoon / @renjie-liu / @abattery Any update on this PR? Please. Thank you!

2024-04-26 06:36 UTC, gbaned commented
Hi @Tessil Can you please confirm if this PR is still valid? Thank you!

2024-05-25 01:49 UTC, closed without merging