kernel_tests/linalg:self_adjoint_eig_op_test.py
tensorflow/tensorflow pull request #54140
Opened 2022-01-27 09:05 UTC by K1504296

Updating delta variable according to the following PR: https://github.com/tensorflow/tensorflow/issues/52544

This is addressing a bug when running the self_adjoint_eig_op_test bazel test on aarch64 devices.
Reducing the delta variable from .1 to .08 resolves this. This bug is confirmed to be present on master branch and resolved by this change on master.

Signed-off-by: Theodore Grey <theodore.grey@gmail.com>

2022-01-27 09:10 UTC, elfringham commented
@penpornk tagging you on this PR as you requested. Thanks.

2022-01-27 11:44 UTC, penpornk approved these changes
Thank you! Approving the PR now since @cantonios is still out of office and has already [confirmed he's okay with a 0.08 delta](https://github.com/tensorflow/tensorflow/issues/52544#issuecomment-1014892980).

2022-02-22 21:37 UTC, cantonios approved these changes

2022-02-23 18:22 UTC, penpornk requested changes
Could you please address the [Ubuntu CPU](https://source.cloud.google.com/results/invocations/720d0338-6eca-4865-bdaf-047938ae32e0) failures? Thank you!

2022-02-24 14:44 UTC, elfringham commented
@penpornk I cannot reproduce the Ubuntu failures. My tests on x86 including Ubuntu 20.04 all pass. Is there a way to re-run that test?

2022-04-19 12:05 UTC, gbaned commented
@K1504296 Can you please resolve conflicts? Thank you!

2022-04-19 13:34 UTC, elfringham commented
The original issue #52544 has been fixed by https://github.com/tensorflow/tensorflow/commit/f2debbd864374477fa45e892173bf1d0ddfb5a47 so I think this PR should just be dropped now. @K1504296 I think you can just close this PR now.

2022-04-19 15:53 UTC, closed without merging