[oneDNN] No bfc env variable.
tensorflow/tensorflow pull request #54169
Opened 2022-01-28 06:09 UTC by Srini511

This PR implements an env variable to switch back to the default system allocator. We recently. found a few usages where the lock overhead in BFC allocator was significant and switching back to default allocator helped performance.

2022-01-28 17:00 UTC, josephykwang commented
We have found this patch allowed us to improve CPU utilization and reduce tailed latency considerably.

2022-02-16 18:23 UTC, Srini511 commented
@rohan100jain checking if you had the chance to review the PR.

2022-02-20 19:56 UTC, rohan100jain requested changes
Please follow how we've done the other environment variable in this file.

[tensorflow/core/common_runtime/mkl_cpu_allocator.h](https://github.com/tensorflow/tensorflow/pull/54169/files#diff-7d94e9af8c62e6e35fd73caed70601a508c45f98321aed7bad37b4d7539f2515)

Make sure we can document what the flag means etc. I'm not too familiar with this code, but seems like we're using the small_size_allocator for all if the flag is on? The name "system" allocator in the flag name seems a bit misleading then?

2022-02-23 20:25 UTC, Srini511 commented
@rohan100jain Thanks for reviewing the PR.
The lambda implementation in the PR is consistent with some of the newer env variable implementations. For example
https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/util/util.cc#L146
The implementation for the other variable in this file is pretty old.
The small size allocator is eventually using the system allocator and I felt including small_size_allocator in the name is too implementation specific. System allocator can be a generic option even if the MklCPUAllocator implementation changes in the future.

2022-02-23 21:07 UTC, penpornk requested changes
> I'm not too familiar with this code, but seems like we're using the small_size_allocator for all if the flag is on? The name "system" allocator in the flag name seems a bit misleading then?

@rohan100jain The code chooses between system allocator and BFC allocator, which allocates large chunks, so the system allocator is referred to as the small-size allocator here. I have no preference on the naming so up to you. :)

@Srini511 Thank you for the PR! I have some minor nits. 

Please remove the other environment variable (`TF_MKL_ALLOC_MAX_BYTES`) since it's not used anymore.

2022-02-23 21:07 UTC, penpornk commented on tensorflow/core/common_runtime/mkl_cpu_allocator.h
> +    TF_CHECK_OK(ReadBoolFromEnvVar("TF_USE_SYSTEM_ALLOCATOR", false, &value));
The name should probably be "TF_ONEDNN_USE_SYSTEM_ALLOCATOR" (or "TF_MKL_USE_SYSTEM_ALLOCATOR", etc.) since this only controls TF-oneDNN code.

2022-02-23 21:07 UTC, penpornk commented on tensorflow/core/common_runtime/mkl_cpu_allocator.h
> +  bool always_use_system_allocator_ = [] {
Can we move the implementation of this lambda function to a .cc file? (`TF_ENABLE_ONEDNN_OPTS` is also in a .cc file.)

2022-03-02 18:40 UTC, Srini511 commented
@penpornk and @rohan100jain  I have made the changes requested. Please take a look.

2022-03-23 04:42 UTC, penpornk approved these changes
Thank you for refactoring and sorry for the delay!

2022-03-23 18:32 UTC, sachinmuradi commented
> @Srini511 Can you please address Ubuntu Sanity errors? Thanks!

@gbaned Since Srini is on vacation , I pushed the changes to address Ubuntu sanity errors

2022-03-24 16:11 UTC, penpornk approved these changes
Thank you for the changes!

2022-03-25 22:01 UTC, penpornk commented
@sachinmuradi Could you please help take a look at the [Windows error](https://source.cloud.google.com/results/invocations/c660e49d-7006-420f-88be-9f450ec8c666/targets/%2F%2Ftensorflow%2Ftools%2Fci_build%2Fbuilds:gen_win_out/log) as well? It has cyclic dependency error.

```
ERROR: T:/src/github/tensorflow/tensorflow/core/common_runtime/BUILD:1779:16: in cc_library rule //tensorflow/core/common_runtime:core_cpu_impl: cycle in dependency graph:
    //tensorflow/tools/pip_package:build_pip_package (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/tpu:tpu (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/tpu:tpu_estimator (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python:function (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/framework:function (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/framework:graph_to_function_def (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/framework:op_def_registry (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/framework:_op_def_registry (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/framework:_op_def_registry.pyd (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/framework:_op_def_registry_pyd_copy (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/framework:_op_def_registry.so (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/lib/core:pybind11_status (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/python/lib/core:pybind11_status_headers (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/core/common_runtime:core_cpu_headers_lib (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/core/common_runtime:core_cpu_headers_lib_gather (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
    //tensorflow/core/common_runtime:core_cpu_lib (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
.-> //tensorflow/core/common_runtime:core_cpu_impl (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
|   //tensorflow/core/common_runtime:threadpool_device_factory (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
|   //tensorflow/core/common_runtime:threadpool_device (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
|   //tensorflow/core/common_runtime:mkl_cpu_allocator (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
|   //tensorflow/core/util:onednn_env_vars (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
|   //tensorflow/core:core_cpu (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
|   //tensorflow/core/common_runtime:core_cpu (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
|   //tensorflow/core/common_runtime:core_cpu_internal (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
`-- //tensorflow/core/common_runtime:core_cpu_impl (9ac86ca5448b6ce48b067072aa0b958763639077f6985cad58583d5a07d0ae27)
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
```

2022-03-26 02:48 UTC, penpornk approved these changes
Thank you!

2022-03-28 06:06 UTC, merged