fix msvc build break on non en-US codepage (#53219)
tensorflow/tensorflow pull request #54377
Opened 2022-02-14 18:26 UTC by fo40225

#53219 it's not complete.

2022-02-15 17:17 UTC, karimnosseir approved these changes

2022-02-20 18:45 UTC, mihaimaruseac approved these changes

2022-02-23 15:39 UTC, karimnosseir requested changes
The PR is failing test. You need to update the test here
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/analyzer_test.py#L183

2022-03-01 15:30 UTC, karimnosseir approved these changes

2022-03-04 12:28 UTC, gbaned approved these changes

2022-03-23 13:33 UTC, gbaned approved these changes

2022-04-15 18:26 UTC, merged