Update sonartype Maven repo URL to HTTPS
tensorflow/tensorflow pull request #54425
Opened 2022-02-17 19:17 UTC by sachinprasadhs

Update sonartype Maven repo URL to HTTPS.
Additional files to the fix https://github.com/tensorflow/examples/commit/d315ddb

2022-02-17 19:59 UTC, lu-wang-g approved these changes

2022-12-28 09:59 UTC, gbaned approved these changes

2022-12-29 05:09 UTC, mihaimaruseac approved these changes

2022-12-29 05:09 UTC, mihaimaruseac commented
```
import/copybara — Import didn't affect any internal file

```

Will take a look at this tomorrow

2022-12-29 16:36 UTC, mihaimaruseac requested changes
Seems to have been manually imported (without using Copybara) in https://github.com/tensorflow/tensorflow/commit/d0dcd3ae907c584e0744aca49ea35f285da48aa6

2022-12-29 16:36 UTC, mihaimaruseac commented on tensorflow/lite/java/demo/app/build.gradle
> +        url 'https://oss.sonatype.org/content/repositories/snapshots'
https://github.com/tensorflow/tensorflow/blob/8d63ee9faeaf5af704d1081554678cae93cffe4f/tensorflow/lite/java/demo/app/build.gradle#L37

2022-12-29 16:36 UTC, mihaimaruseac commented on tensorflow/lite/java/demo/build.gradle
> +            url 'https://oss.sonatype.org/content/repositories/snapshots'
https://github.com/tensorflow/tensorflow/blob/8d63ee9faeaf5af704d1081554678cae93cffe4f/tensorflow/lite/java/demo/build.gradle#L22

2022-12-29 16:36 UTC, mihaimaruseac commented on tensorflow/lite/java/ovic/demo/app/build.gradle
> +        url 'https://oss.sonatype.org/content/repositories/snapshots'
https://github.com/tensorflow/tensorflow/blob/8d63ee9faeaf5af704d1081554678cae93cffe4f/tensorflow/lite/java/ovic/demo/app/build.gradle#L36

2022-12-29 16:36 UTC, closed without merging