[oneDNN] Enable BF16 for DepthwiseConv2D* ops
tensorflow/tensorflow pull request #54453
Opened 2022-02-18 20:32 UTC by gaurides

2022-04-19 12:44 UTC, gbaned commented
@rohan100jain Can you please review this PR ? Thank you!

2022-04-21 18:33 UTC, cantonios commented
Please provide a description and justification for the added kernels.

2022-04-21 22:31 UTC, gaurides commented
> Please provide a description and justification for the added kernels.

@cantonios : added details in the description. Mainly to prevent crash in some models for bf16.

2022-04-22 18:18 UTC, cantonios requested changes

2022-04-22 18:18 UTC, cantonios commented on tensorflow/core/kernels/depthwise_conv_ops_test.cc
> +      test::ExpectTensorNear<T>(expected, output, 1e-5);
nit: please add braces as per https://google.github.io/styleguide/cppguide.html#Conditionals

2022-04-22 21:43 UTC, gaurides commented on tensorflow/core/kernels/depthwise_conv_ops_test.cc
> +      test::ExpectTensorNear<T>(expected, output, 1e-5);
@cantonios done.

2022-04-22 21:51 UTC, cantonios commented
Thanks for getting rid of the `NoOp` registration.

2022-04-22 21:51 UTC, cantonios approved these changes

2022-04-25 20:24 UTC, merged