Made rounding in convert_image_dtype for numbers close to zero
tensorflow/tensorflow pull request #54484
Opened 2022-02-22 19:24 UTC by shkarupa-alex

Fixes https://github.com/tensorflow/tensorflow/issues/48701

That issue already was fixed by https://github.com/tensorflow/tensorflow/issues/48701
But after merging all changes were overwritten in https://github.com/tensorflow/tensorflow/commit/56ab2308f72da337865cf765a1844ed9e990d02e#diff-a5a22434f0c18768fc2e10c0e0420ac6f111a5802f67e3df54f155bfefc7094f and now issue raises again

2022-04-13 06:28 UTC, shkarupa-alex commented
Any update on merging this PR?

2022-04-18 15:55 UTC, edloper commented
I'm not familiar with this code, so I'm probably not the right person to review it.  

But it looks like the original change was automatically rolled back because it caused a test in this file to fail: https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/compiler/tests/image_ops_test.py.  (Unfortunately, since it was rolled back several months ago, the logs from the failed test aren't available anymore.)

2022-04-19 12:46 UTC, gbaned commented
@rohan100jain Can you please review this PR ? Thank you!

2022-06-03 12:50 UTC, gbaned commented
@rohan100jain Can you please review this PR ? Thank you!

2022-11-15 10:21 UTC, gbaned commented
Hi @rohan100jain Can you please review this PR ? Thank you!

2023-02-22 11:45 UTC, gbaned commented
Hi @jsmeredith Can you please review this PR ? Thank you!

2023-03-21 17:56 UTC, gbaned commented
Hi @jsmeredith Can you please review this PR ? Thank you!

2023-06-23 15:53 UTC, cantonios commented
@shkarupa-alex have you addressed the compiler test failure?

2023-06-28 09:34 UTC, shkarupa-alex commented
@cantonios , i don't see any test failures

2023-08-24 08:16 UTC, gbaned commented
Hi @cantonios Can you please assist on above comments from @shkarupa-alex. Thank you!

2023-08-24 15:39 UTC, cantonios approved these changes

2023-08-28 16:02 UTC, cantonios requested changes

2023-08-28 16:02 UTC, cantonios commented on tensorflow/python/ops/image_ops_test.py
> +    y_data = [7, 9, 13, 140, 181, 226, 135, 121, 234, 172, 255, 128]
This is also failing, same as above.

2023-09-12 15:40 UTC, cantonios requested changes
See above mentioned failure

2023-09-25 07:10 UTC, gbaned commented
Hi @shkarupa-alex Can you please check @cantonios's comments and keep us posted ? Thank you!

2023-10-11 06:32 UTC, gbaned commented
Hi @shkarupa-alex Any update on this PR? Please. Thank you!

2023-10-11 09:41 UTC, shkarupa-alex commented
I'm not sure how to fix that, due to different behavior with CPU and GPU.
Current tests work well with CPU. But with GPU fail with error (difference in 1 unit for some values).

2023-10-11 10:16 UTC, shkarupa-alex commented
The issue comes from rescaling between dtypes
When using multiplication with inverse scale GPU and CPU ops produce different results.
Here is a short example:

```python
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import gen_image_ops


def convert_image_dtype(image, dtype, saturate=False, invscale=True, name=None):
    cast = tf.cast(image, dtype)
    
    if invscale:
        return tf.math.multiply(cast, 1. / image.dtype.max, name=name)
    else:
        return tf.math.divide(tf.cast(image, dtype), 255.)


def adjust_saturation(image, saturation_factor, invscale=True, name=None):
    flt_image = convert_image_dtype(image, tf.dtypes.float32, invscale=invscale)
    adjusted = gen_image_ops.adjust_saturation(flt_image, saturation_factor)

    return adjusted
    
def test(invscale=True):
    x_shape = [2, 2, 3]
    x_data = [0, 5, 13, 54, 135, 226, 37, 8, 234, 90, 255, 1]
    x_np = np.array(x_data, dtype=np.uint8).reshape(x_shape)

    saturation_factor = 0.5
    y_data = [7, 9, 13, 140, 181, 226, 135, 121, 234, 172, 255, 128]
    y_np = np.array(y_data, dtype=np.uint8).reshape(x_shape)

    x = tf.constant(x_np, shape=x_shape)
    # x = tf.cast(x, 'float32') / 255.
    y = adjust_saturation(x, saturation_factor, invscale=invscale)
    y_tf = y.numpy()
    print(y_tf[0, 1, 1] * 255.)


print('With inv scale')
with tf.device("/cpu:0"):
    test()
with tf.device("/gpu:0"):
    test()
    
print('\nWithout inv scale')
with tf.device("/cpu:0"):
    test(invscale=False)
with tf.device("/gpu:0"):
    test(invscale=False)
```
and it's output:
```
With inv scale
180.50001204013824
180.49999684095383

Without inv scale
180.49999684095383
180.49999684095383
```

2023-10-11 16:43 UTC, cantonios commented
You should change the test so it is not so sensitive to these numerical perturbations - essentially, avoid results that are expected to be at `X.5` when math+rounding is involved.

2023-11-07 08:26 UTC, gbaned commented
Hi @shkarupa-alex Can you please check @cantonios's comments and keep us posted ? Thank you!

2023-12-14 05:59 UTC, gbaned commented
Hi @shkarupa-alex Any update on this PR? Please. Thank you!

2023-12-29 03:33 UTC, gbaned commented
Hi @shkarupa-alex Any update on this PR? Please. Thank you!

2024-01-19 05:01 UTC, gbaned commented
Hi @shkarupa-alex  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

2024-01-19 05:01 UTC, closed without merging