[hlo] algebraic simplifier add pattern select(not(pred), on_true, on_…
tensorflow/tensorflow pull request #54572
Opened 2022-02-25 06:31 UTC by lipracer

…false) => select(pred, on_false, on_true)

2022-02-28 09:50 UTC, akuegel requested changes
Thanks for adding this simplification rule :)

2022-02-28 09:50 UTC, akuegel commented on tensorflow/compiler/xla/service/algebraic_simplifier.cc
> +    auto on_fasle = select->mutable_operand(2);
nit: typo, on_fasle -> on_false

2022-02-28 09:55 UTC, akuegel approved these changes

2022-02-28 11:33 UTC, lipracer commented
I got below error message.
```
The specified bucket does not exist.
````

2022-02-28 11:45 UTC, akuegel commented
> I got below error message.
> 
> ```
> The specified bucket does not exist.
> ```

I guess it is an infrastructure problem. I have notified our infrastructure team.

2022-02-28 11:46 UTC, lipracer commented
> > I got below error message.
> > ```
> > The specified bucket does not exist.
> > ```
> 
> I guess it is an infrastructure problem. I have notified our infrastructure team.

Thanks.

2022-02-28 18:34 UTC, angerson commented
There was indeed an error in our infrastructure configuration, which I've now fixed -- the "Details" link for that job was pointing to the wrong place. It should be fixed for any future check runs.

FYI, Code Check - Changed Files is not a blocking presubmit. It suggests clang and python format changes that may be needed to merge, but since we're still working on finding similar linter settings for internal and external presubmits it's not guaranteed that the suggested changes are necessary.

2022-03-01 07:45 UTC, akuegel reviewed
Now that we can see the presubmit error, it seems to indicate that algebraic_simplifier has the wrong chmod config. It seems it has 755, but should have 644. Can you maybe check that, and if that is true, change it to 644?

2022-03-01 07:50 UTC, akuegel commented
> Now that we can see the presubmit error, it seems to indicate that algebraic_simplifier.cc has the wrong chmod config. It seems it has 755, but should have 644. Can you maybe check that, and if that is true, change it to 644?

Ok, I just checked that this wrong mode is pre-existing, still it seems this blocks merging of this PR. I could also try to change it, but then you would have to rebase once my change lands (and I am not sure if rebasing will do the right thing). Please let me know if you need help with changing the mode.

2022-03-01 12:48 UTC, akuegel commented
I have fixed the permissions now in f4b9d3dbb2d55b73a9a02b4e31cbbf9d02bee32e
Can you please rebase your PR? Lets hope this will keep the new file mode.

2022-03-01 13:01 UTC, lipracer commented
Done.

2022-03-01 14:52 UTC, akuegel approved these changes

2022-03-02 09:56 UTC, merged