Update custom_gradient.py
tensorflow/tensorflow pull request #54669
Opened 2022-02-28 10:04 UTC by RenuPatelGoogle

Updated tf.gradients with tf.GradientTape to fix the error. (RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.)

2022-02-28 15:24 UTC, mihaimaruseac requested changes
Please retitle the PR message (and in the future use a better commit message). See for example https://cbea.ms/git-commit/

2022-03-23 18:33 UTC, RenuPatelGoogle commented
> Please retitle the PR message (and in the future use a better commit message). See for example https://cbea.ms/git-commit/

I tried to mention meaningful information now. Please check.

2022-03-23 18:34 UTC, RenuPatelGoogle commented
> @RenuPatelGoogle Can you please check @mihaimaruseac's comments and keep us posted ? Thanks!

Sure,  Thank you.

2022-03-25 15:50 UTC, mihaimaruseac commented
The title of the PR is unchanged

2022-06-03 14:59 UTC, mihaimaruseac commented
Unassigning as I no longer work in TF

2022-07-27 20:43 UTC, rohan100jain commented on tensorflow/python/ops/custom_gradient.py
> +  dy_dx = tf.GradientTape(y, x) # Will be NaN when evaluated.
Thanks for the PR but this is not the right way to use the tf.GradientTape API. Please take a look at https://www.tensorflow.org/api_docs/python/tf/GradientTape. Mostly you need to open a GradientTape context.

2022-11-15 10:20 UTC, gbaned commented
Hi @RenuPatelGoogle Can you please check @rohan100jain's comments. Thank you!

2022-12-29 05:07 UTC, mihaimaruseac commented
Closing as it stalled

2022-12-29 05:07 UTC, closed without merging