ExtractImagePatches grad fails when batch size is unknown
tensorflow/tensorflow pull request #5502
Opened 2016-11-09 19:58 UTC by liuyipei

Mentioned in
#5501
#3672
Solution was by @mohamedadaly

2016-11-09 20:02 UTC, liuyipei commented
I signed it!

2016-11-09 20:10 UTC, liuyipei commented
I signed it!

2016-11-10 00:40 UTC, benoitsteiner requested changes

2016-11-10 00:40 UTC, benoitsteiner commented on tensorflow/python/ops/array_grad.py
> +
To be consistent, you should also use array_ops.shape() to extract rows_in, cols_in, and channels

2016-11-10 01:40 UTC, liuyipei commented
@benoitsteiner 
I changed `channels` as per your request;  sadly, there is a distinction for the others. 
`rows_out`, `rows_in`, and etc are actually used as scalar underneath, where they do scalar-ish things like serving as for-loop constraints, getting passed into `range`, and etc.  So, a significant rewrite would be required if I wanted to let `rows_in` to be a tensor.

2016-11-10 01:47 UTC, benoitsteiner approved these changes

2016-11-10 03:08 UTC, benoitsteiner commented
Jenkins, test this please.

2016-11-10 15:35 UTC, merged