Removed unnecessary classproperty decorator and used deprecated inste…
tensorflow/tensorflow pull request #5510
Opened 2016-11-10 03:35 UTC by terrytangyuan

…ad of logging

2016-11-10 15:40 UTC, benoitsteiner requested changes

2016-11-10 15:40 UTC, benoitsteiner commented on tensorflow/python/framework/ops.py
> +from tensorflow.contrib.framework import deprecated
This causes several test failures on Mac:
==================== Test output for //tensorflow/tensorboard/lib/python:http_test:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/bin/tensorflow/tensorboard/lib/python/http_test.runfiles/org_tensorflow/tensorflow/tensorboard/lib/python/http_test.py", line 27, in <module>
    from tensorflow.python.platform import test
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/bin/tensorflow/tensorboard/lib/python/http_test.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 67, in <module>
    from tensorflow.python.framework import test_util as _test_util
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/bin/tensorflow/tensorboard/lib/python/http_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 37, in <module>
    from tensorflow.python.client import session
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/bin/tensorflow/tensorboard/lib/python/http_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 30, in <module>
    from tensorflow.python.framework import ops
  File "/private/var/tmp/_bazel_jenkins/13e370a18c169b19baeafefb05212b85/execroot/tensorflow-pull-requests-mac/bazel-out/local-opt/bin/tensorflow/tensorboard/lib/python/http_test.runfiles/org_tensorflow/tensorflow/python/framework/ops.py", line 47, in <module>
    from tensorflow.contrib.framework import deprecated
ImportError: No module named contrib.framework

2016-11-10 23:59 UTC, terrytangyuan commented
Thanks! Could you check again? I don't think the new errors are related to this PR

2016-11-11 00:06 UTC, ilblackdragon approved these changes
Remove decorator_utils import as it's unused?

Fails are seem to be in Windows and not related to this.

2016-11-11 13:58 UTC, terrytangyuan commented
Sure, removed.

2016-11-17 01:13 UTC, merged

2016-11-28 17:34 UTC, ilblackdragon commented
Seems like this fails - #5877