Saving Resource Variables without Copy
tensorflow/tensorflow pull request #55206
Opened 2022-03-11 17:55 UTC by philipphack

Provides a solution for the increase in memory usage when saving models with large sparsely accessed resource variables by avoiding the copying of the variables. The kernel of `ReadVariableOp` is modified to convert variables that were sparsely accessed from copy-on-read mode to copy-on-write mode under an exclusive lock. The conversion is disabled in the default setting and only occurs when the Python function `_read_variable_op` is called from class `ResourceVariableSaveable` during the saving of resource variables.

See issue [#54104](https://github.com/tensorflow/tensorflow/issues/54105).

2022-03-22 00:59 UTC, wangpengmit commented
I don't like that `ReadVariableOp` does this COR-to-COW conversion as a side effect (even if it only happens when `no_copy` is true). How about adding a new op `TurnOffCopyOnRead` to do this job?

2022-03-24 23:18 UTC, philipphack commented
Thanks for the comment. I've introduced a new `ReadVariableWithoutCopyOp`, which is exclusively called when saving resource variables. For copy-on-write variables, the op behaves like `ReadVariableOp`. For copy-on-read variables, the kernel again acquires an exclusive mutex, but avoids the side effect by directly reading the variable instead of changing its type.

2022-03-24 23:57 UTC, wangpengmit commented on tensorflow/core/kernels/resource_variable_ops.cc
> +    ctx->set_output(0, *t);
The output tensor will be unstable. When the COR variable's buffer got modified, the output tensor's value will silently change, which breaks TF tensors' immutability guarantee.

My preferred solution is to add a `TurnOffCopyOnRead` (or `DisableCopyOnRead`) op to turn off a variable's copy_on_read_mode.

2022-03-25 01:26 UTC, philipphack commented
The new `DisableCopyOnReadOp` is called when a resource variable is saved.

2022-03-25 22:45 UTC, wangpengmit commented
Thanks for the update! Overall looks good, except for some minor issues.

2022-03-26 00:00 UTC, philipphack commented
I can't reproduce the PyLint error, and I also don't see any lines that are longer than 80 characters in the diff.

2022-03-26 00:09 UTC, wangpengmit commented
Maybe the test was against an older version. Or maybe it's caused by whitespaces. (CCing @mihaimaruseac who may know more.)

2022-03-28 15:05 UTC, mihaimaruseac commented
Rerunning the pylint job, seems to have been using an old version?

Anyway, if still broken, please ignore.

2022-03-29 23:35 UTC, wangpengmit commented on tensorflow/core/kernels/resource_variable_ops.cc
> +REGISTER_KERNEL_BUILDER(Name("DisableCopyOnReadOp").Device(DEVICE_CPU),
Op name needs to be updated.

2022-03-29 23:35 UTC, wangpengmit commented on tensorflow/python/ops/resource_variable_ops.py
> +    """Reads the value of the variable. If the variable is in copy-on-read mode
The docstring needs to be in the format of the [Google Python Style Guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#383-functions-and-methods) to pass linters.

2022-03-30 00:00 UTC, wangpengmit approved these changes

2022-03-30 00:49 UTC, wangpengmit requested changes

2022-03-30 00:49 UTC, wangpengmit commented on tensorflow/python/ops/resource_variable_ops.py
> +    """Reads the value of the variable. If the variable is in copy-on-read mode
There needs to be a one-line summary.

2022-03-30 01:19 UTC, wangpengmit requested changes

2022-03-30 01:19 UTC, wangpengmit commented on tensorflow/python/ops/resource_variable_ops.py
> +    """Constructs an op which reads the value of this variable
One-liner here also.

2022-03-30 01:19 UTC, wangpengmit commented on tensorflow/python/ops/resource_variable_ops.py
> +     the read operation.
Should be "The value of the variable." (`read_value`'s docstring is outdated.)

2022-03-30 02:02 UTC, wangpengmit approved these changes

2022-04-01 00:41 UTC, wangpengmit commented
There are some `api_compatibility_test` CI failures. Please run `bazel run //tensorflow/tools/api/tests:api_compatibility_test -- --update_goldens True` to update the API golden files.

2022-04-02 00:58 UTC, philipphack commented
This fails with `ModuleNotFoundError: No module named 'tensorflow.core.kernels'`.

2022-04-04 20:22 UTC, wangpengmit commented
Seems your Python paths are not set up properly. I'll try fixing the CI errors internally.

2022-04-08 21:38 UTC, merged