Fix invalid input for tf.gather_nd with batch_dims
tensorflow/tensorflow pull request #55210
Opened 2022-03-12 02:45 UTC by yongtang

This PR tries to address the issue raised in #55203 where
invalid batch_dim (bool) was passed to  tf.gather_nd
with error output returned silently.
The reason was that `int()` was applied incorrectly, which always cast
any value to integer.
This PR fixes #55203.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2022-03-21 21:58 UTC, mihaimaruseac approved these changes
We probably need that call?

2022-03-29 21:19 UTC, mihaimaruseac requested changes
```
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/array_ops/array_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/array_ops/array_ops_test.py", line 2143, in testBatchDimsAsTensor
    batch_gather_nd_tensor_batch_dims_result = array_ops.gather_nd(
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/array_ops/array_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/util/traceback_utils.py", line 141, in error_handler
    return fn(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/array_ops/array_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/util/dispatch.py", line 1082, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/array_ops/array_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/array_ops.py", line 5690, in gather_nd
    return batch_gather_nd(params, indices, batch_dims=batch_dims, name=name)
  File "/b/f/w/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/array_ops/array_ops_test_cpu.runfiles/org_tensorflow/tensorflow/python/ops/array_ops.py", line 5709, in batch_gather_nd
    raise TypeError(f"Argument `batch_dims` must be an int; got {batch_dims}")
TypeError: Argument `batch_dims` must be an int; got [1]
```

2022-04-19 14:10 UTC, gbaned commented
Hi @yongtang Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

2022-06-03 13:35 UTC, gbaned commented
Hi @yongtang Any update on this PR? Please. Thank you!

2022-07-18 15:55 UTC, gbaned commented
Hi @yongtang Any update on this PR? Please. Thank you!

2022-09-09 01:01 UTC, closed without merging