Fix invalid examples for tf.RaggedTensor __abs__
tensorflow/tensorflow pull request #55222
Opened 2022-03-14 09:42 UTC by gadagashwini

This PR tries to address the issue raised in [#53828](https://github.com/tensorflow/tensorflow/issues/53828) where
tf.tensor Examples was added to tf.RaggedTensor __abs__
Replacing the tensor examples with tf.RaggedTensor examples
This PR fixes [#53828](https://github.com/tensorflow/tensorflow/issues/53828).

2022-03-21 21:57 UTC, mihaimaruseac requested changes
Why remove the dense tensor examples?

2022-03-24 09:16 UTC, gadagashwini commented
[tf.RaggedTensor](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor) represents usage and examples for RaggedTensor. Since few methods of tf.RaggedTensor such as https://www.tensorflow.org/api_docs/python/tf/RaggedTensor#__abs__ has Dense Tensor examples. 

This PR fixes issue https://github.com/tensorflow/tensorflow/issues/53828.

2022-03-30 02:40 UTC, gadagashwini commented
`tf.RaggedTensor` doc has symbol `__abs__`. Can you please take a look https://www.tensorflow.org/api_docs/python/tf/RaggedTensor#__abs__. Thanks!

2022-03-30 15:48 UTC, mihaimaruseac commented
```python
@tf_export("math.abs", "abs")
```

This means this docstring is attached to `tf.math.abs` and `tf.abs`

2022-03-31 02:34 UTC, gadagashwini commented
Thank you !
Only ask here is symbols like `__abs__`, `__add__`, `__and__` ,`__bool__` and etc, are appearing under [tf.RaggedTensor](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor) document. How do we justify the examples given there. Since examples has Dense tensor but document is explaining about the RaggedTensor

2022-03-31 15:48 UTC, mihaimaruseac commented
A RaggedTensor is a subclass of Tensor. If the method is not redefined, the parent class method is used.

2022-05-02 16:20 UTC, mihaimaruseac commented
Since https://github.com/tensorflow/tensorflow/pull/55222#issuecomment-1084771301 showed up in #53828: the comment here is to help in solving the issue properly: you need to subclass the methods for the ragged tensor and attach docstring to the new methods.

2022-05-04 02:36 UTC, gadagashwini commented
My bad, I misinterpreted the [comment.](https://github.com/tensorflow/tensorflow/pull/55222#issuecomment-1084771301)

2022-09-09 01:01 UTC, closed without merging