[INTEL oneDNN] user mode scratchpad implementation for inner-product
tensorflow/tensorflow pull request #55236
Opened 2022-03-15 04:03 UTC by gzmkl

Enable user mode scratchpad for inner-product (matmul fused & quantized matmul) for better memory usage control.

Note: code change with mkl_util.h is NOT needed once PR

   https://github.com/tensorflow/tensorflow/pull/54381

is merged.

2022-03-15 20:01 UTC, gzmkl commented
@penpornk  The new code in mkl_util.h causes Windows compilation failure (same code in the recently reverted PR).
We will fix it.

So please hold on the review.  Thanks!

2022-03-21 23:02 UTC, gzmkl commented
@penpornk  This PR is ready for review. 

You can combine it with a related scratchpad PR 

https://github.com/tensorflow/tensorflow/pull/55256

2022-03-23 21:03 UTC, penpornk requested changes
Thank you for the PR!

2022-03-24 22:43 UTC, gzmkl commented on tensorflow/core/util/mkl_util.h
> +        (spad_size / sizeof(T)) + ((spad_size % sizeof(T) > 0) ? 1 : 0);
@penpornk  Made code change per suggestion. Thanks!

I also committed the same change to my other scratchpad PR (for conv op).

2022-03-24 22:44 UTC, gzmkl commented
Done with change

2022-03-25 16:20 UTC, penpornk approved these changes
Thank you for the change!

2022-03-25 20:39 UTC, penpornk commented
@gzmkl Could you please help resolve merge conflict? Thank you very much!

2022-03-25 22:59 UTC, penpornk approved these changes
Thank you!

2022-03-29 00:22 UTC, penpornk commented
Manually close this PR since it is merged in https://github.com/tensorflow/tensorflow/commit/2ed1ca2e69a3200f70d7025f260e5d97f82b18b9.

2022-03-29 00:22 UTC, closed without merging