Add maxout op to tf.contrib.layers
tensorflow/tensorflow pull request #5528
Opened 2016-11-10 20:32 UTC by gokceneraslan

2016-11-10 21:07 UTC, gokceneraslan commented
Small demonstration: 

![image](https://cloud.githubusercontent.com/assets/1140359/20194275/fb51abb8-a791-11e6-905c-68e53ff7849f.png)

2016-11-19 08:02 UTC, Mistobaan commented
add a reference to the paper? https://arxiv.org/abs/1302.4389

2016-12-13 07:46 UTC, martinwicke commented
@ilblackdragon, can you review?

2016-12-13 17:20 UTC, ilblackdragon requested changes
Thanks for the contribution!

Can you also please add tests. Specifically to check that reshape works correctly for 4-5d tensors with axis in the middle (as it's easy to mix up axis when reshaping).

2016-12-13 17:20 UTC, ilblackdragon commented on tensorflow/contrib/layers/python/layers/layers.py
> +    """
the `"""` should be 2 spaces left.

2016-12-13 17:20 UTC, ilblackdragon commented on tensorflow/contrib/layers/python/layers/layers.py
> +    num_channels = shape[axis]
`num_channels` here can be `None`, e.g. undefined in shape inference. if it's None, you can still implement this via `tf.shape()` and `tf.pack` later.

2016-12-13 17:20 UTC, ilblackdragon commented on tensorflow/contrib/layers/python/layers/layers.py
> +    A `Tensor` representing the results of the pooling operation.
please describe shape of output tensor.

also may be in description add a formula e.g. out[..., i, ..., j] = max(in[...]) (similar how https://www.tensorflow.org/versions/r0.12/api_docs/python/nn.html#conv2d)

2016-12-13 17:20 UTC, ilblackdragon commented on tensorflow/contrib/layers/python/layers/layers.py
> +    shape[axis] = -1
should it be `= num_units`?
[it's better not to have -1 in reshape, as it's easy to wrongly reshape and not know about it]

2017-01-11 23:42 UTC, drpngx commented
@gokceneraslan any luck with this?

2017-01-15 19:23 UTC, drpngx commented
Closing due to inactivity. Please re-open when updates are available.

2017-01-15 19:23 UTC, closed without merging

2017-05-10 06:46 UTC, StefanoD commented
@gokceneraslan Would be interested in this feature! Would be cool, if you would finish this PR! :)

2017-07-24 19:56 UTC, tiagofrepereira2012 commented
Hi,

I'm interested in this feature.

Is it just a matter of implement some test units and improve the documentation?

2017-08-03 21:38 UTC, martinwicke commented
Yes, basically the work to do is to address @ilblackdragon's comments. 

I saw you made a PR, but it was closed, not sure what happened.

2017-08-04 08:58 UTC, tiagofrepereira2012 commented
I don't know what happened to; I'll reopen it