Avoid loss of precision from using reciprocal
tensorflow/tensorflow pull request #55310
Opened 2022-03-21 14:49 UTC by elfringham

Taking the reciprocal of the calculated value results in a loss of precision. This causes the unit test prepare-tf.mlir.test to fail on AARCH64. So instead of taking the reciprocal of the calculated nudged_scale to get the inv_nudged_scale, calculate this value from the input values.

2022-03-21 17:03 UTC, elfringham commented
@cfRod @nSircombe

2022-03-22 16:40 UTC, cfRod commented
Adding @penpornk

2022-03-22 16:59 UTC, penpornk requested changes
Thank you for the PR!

2022-03-22 16:59 UTC, penpornk commented on tensorflow/core/kernels/fake_quant_ops_functor.h
> +    const float inv_nudged_scale = (quant_max - quant_min) / (max - min);
Computing this here risks being out of sync with `nudge_scale` if its computation is updated in the future. Please modify the `Nudge` function to also return `inv_nudge_scale` instead. Please also add a comment there that `inv_nudge_scale` is computed separately to preserve precision.

2022-03-22 17:44 UTC, elfringham commented
@penpornk Updated as requested.

2022-03-25 22:16 UTC, penpornk approved these changes
Thank you for the changes!

2022-03-28 06:06 UTC, merged

2022-03-28 08:22 UTC, elfringham commented
@penpornk What happened here? Why the rollback?

2022-03-28 15:16 UTC, penpornk commented
@elfringham It broke some internal tests which use fixed golden values. I'll do a more thorough test before bringing this PR back. You don't need to do anything.