Update GPU details for ctc_loss
tensorflow/tensorflow pull request #55365
Opened 2022-03-24 19:57 UTC by sachinprasadhs

Updated GPU details for ctc_loss which supports dense padded labels and SparseTensor.
Closes #55290

2022-03-25 19:34 UTC, f90 commented
Hey, thanks for looking into this. Can we add to the docs here a note that the code paths for sparse labels and dense labels are different on GPU? I.e. if you provide sparse labels, you are using the cuDNN implementation and you can be 50x faster than with dense labels. People will otherwise keep using dense labels and have no way of knowing why the loss is so slow even with a GPU

2022-04-19 14:35 UTC, gbaned commented
@Rohan Jain Can you please review this PR ? Thank you!

2022-06-01 11:29 UTC, gbaned commented
@rohan100jain Can you please review this PR ? Thank you!

2022-08-30 16:13 UTC, cantonios requested changes

2022-08-30 16:13 UTC, cantonios commented on tensorflow/python/ops/ctc_ops.py
>    - On CPU: Caller may use SparseTensor or dense padded labels but calling with
Change this to "On CPU and GPU:  Caller may..."

since (as noted by other commenters) using sparse labels will be significantly faster.

2022-08-30 16:29 UTC, cantonios approved these changes

2022-09-02 05:08 UTC, merged