[TF:TRT] Improve dynamic shape INT8 calibration API
tensorflow/tensorflow pull request #55498
Opened 2022-04-05 13:02 UTC by tfeher

This PR moves the calibration function argument to the build function.

In dynamic shape mode we need to provide profile information before we can calibrate the TensorRT engine. The `build()` method of `TrtGraphConverterV2` can be used to provide the shape information. Previously, the calibration function had to be passed to `convert()`, where a reference was stored. But calibration actually happens in build, after the shape information is collected. This motivates to move the `calibration_fn` arg to `build()`, where it is actually used.

2022-04-05 13:03 UTC, tfeher commented
Tagging @bixia1 and @DEKHTIARJonathan for review.

2022-04-05 13:05 UTC, tfeher commented
This PR builds on #55166.

2022-04-19 14:47 UTC, gbaned commented
@tfeher Can you please resolve conflicts? Thank you!

2022-07-08 16:32 UTC, gbaned commented
Hi @tfeher Any update on this PR? Please. Thank you!

2022-07-18 16:12 UTC, gbaned commented
Hi @tfeher Any update on this PR? Please. Thank you!

2022-08-05 15:10 UTC, gbaned commented
Hi @tfeher Any update on this PR? Please. Thank you!

2022-09-14 21:09 UTC, tfeher commented
I have resolved the conflicts and added more tests. Sorry for the delay.
@bixia1 this is ready for review

2022-09-19 04:42 UTC, bixia1 approved these changes

2022-09-21 11:13 UTC, gbaned commented
Hi @tfeher Can you please resolve conflicts? Thank you!

2022-10-14 19:07 UTC, gbaned commented
Hi @tfeher Can you please resolve conflicts? Thank you!

2022-10-14 21:28 UTC, tfeher commented
Conflicts resolved.

2022-10-18 22:27 UTC, bixia1 approved these changes

2022-12-14 14:46 UTC, mihaimaruseac commented
Can you rebase this on master again, please?

2022-12-28 10:40 UTC, gbaned commented
Hi @tfeher Can you rebase this on master again, please? Thank you!

2022-12-28 17:44 UTC, mihaimaruseac requested changes

2022-12-28 17:44 UTC, mihaimaruseac commented on RELEASE.md
> +
These need to be moved to the new section

2023-01-12 18:18 UTC, gbaned commented
Hi @tfeher Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

2023-03-21 18:34 UTC, gbaned commented
Hi @tfeher Any update on this PR? Please. Thank you!

2023-04-19 01:57 UTC, closed without merging