[TF:TRT] Binary op converter formatting and code style cleanup
tensorflow/tensorflow pull request #55758
Opened 2022-04-26 18:20 UTC by christopherbate

Converts various `typedef`s in `convert_nodes.h to C++ type aliases.
Applies `clang-format` to `convert/ops/binary_ops.cc`.
Changes use of C-style array to C++ `std::array` in `convert/ops/binary_ops.cc`.

2022-04-27 18:20 UTC, bixia1 approved these changes

2022-05-09 16:39 UTC, bixia1 approved these changes

2022-05-10 22:12 UTC, bixia1 requested changes
[third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc:1845](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc?l=1845&ws=tap-prod-presubmit/185213972&snapshot=2):37: error: no template named 'operationMap'; did you mean 'OperationMap'?
      const string& testName, const operationMap<S>& map,
                                    ^~~~~~~~~~~~
                                    OperationMap
[./third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h:512](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h?l=512&ws=tap-prod-presubmit/185213972&snapshot=2):1: note: 'OperationMap' declared here
using OperationMap = std::unordered_map<std::string, T>;
^
1 error generated.

2022-05-11 18:00 UTC, christopherbate commented
I fixed the issues, thanks.

2022-05-12 16:24 UTC, bixia1 approved these changes

2022-05-13 14:30 UTC, merged