build: add `ios_arm_64` configuration, fix build issues for TFLite
tensorflow/tensorflow pull request #55777
Opened 2022-04-27 17:05 UTC by ccarpita

This patch makes it possible to build `TensorFlowLiteC_framework` for arm64-simulator using the command `bazel-5.0.0-darwin-arm64 build --config=ios_sim_arm64 -c opt  //tensorflow/lite/ios:TensorFlowLiteC_framework`

2022-04-27 21:31 UTC, mihaimaruseac commented
Can you make this on master please? If it needs to be cherrypicked to fix 2.9 we can cherrypick from master afterwards.

2022-04-28 15:03 UTC, mihaimaruseac requested changes
This should be made on `master` branch, not `r2.9`

2022-04-29 16:26 UTC, mihaimaruseac approved these changes

2022-05-01 01:26 UTC, mihaimaruseac approved these changes

2022-05-09 21:05 UTC, mself commented
Does this PR need to be modified or are the CI failures transitory?

2022-05-09 22:39 UTC, merged