Ensure there are more elements in the dataset than twice CPU core count
tensorflow/tensorflow pull request #55790
Opened 2022-04-28 17:15 UTC by elfringham

Fixes //tensorflow/python/data/experimental/kernel_tests/service:fault_tolerance_test on machines with more than 50 CPU cores
This test reads half of the elements and assumes that the amount left
is more than will be prefectched which can be equal to the number
of CPU cores. For high CPU core count machines (>50) this is not
true when there are only 100 elements in the dataset.
So instead set the size of the dataset based on the CPU core count
to ensure that the remaining elements in the dataset are always
more than will be prefetched.

2022-04-28 17:16 UTC, elfringham commented
@cfRod @nSircombe @penpornk

2022-04-29 16:14 UTC, aaudiber requested changes
Thanks for catching this! It's a really subtle bug. Your fix lgtm, just one small comment about removing a debug log

2022-04-29 16:14 UTC, aaudiber commented on tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py
> +    print("Creating test cluster", flush=True)
remove

2022-04-29 16:22 UTC, elfringham commented on tensorflow/python/data/experimental/kernel_tests/service/fault_tolerance_test.py
> +    print("Creating test cluster", flush=True)
Sorry, yes, removed

2022-04-29 16:53 UTC, aaudiber approved these changes

2022-05-02 17:01 UTC, merged

2022-05-03 21:43 UTC, mihaimaruseac commented
Made https://github.com/tensorflow/tensorflow/pull/55850 to cherrypick to 2.9