Disable where ops in xla auto-clustering
tensorflow/tensorflow pull request #55808
Opened 2022-04-30 03:50 UTC by wenscarl

This PR mainly aims at disabling where op in XLA auto-clustering. A possible issue caused by where being included in auto-clustering is [here](https://github.com/tensorflow/tensorflow/issues/55610). A TF_XLA_FLAGS, called `tf_xla_cluster_remove_from_blacklist` is added, which can only take string values from `Where`, `Unique`, and`CollectiveReduceV2`(separate by comma). By default, where op is disabled from auto-clustering. The way to enable it in auto-clustering looks like,
`TF_XLA_FLAGS=--tf_xla_cluster_remove_from_blacklist=Where` .

2022-05-04 22:08 UTC, nluehr commented
CC @jurahul

2022-05-04 22:35 UTC, smit-hinsu approved these changes

2022-05-16 14:33 UTC, cheshire commented
Do you think we could do something much simpler, without a flag, and just disabling tf.where?

2022-05-16 16:44 UTC, wenscarl commented
> Do you think we could do something much simpler, without a flag, and just disabling tf.where?

The reasons I made the disabling of tf.where with a flag are:
1) Make the change scalable and extensible to other ops if perf regression is spotted in the future. Adding too many env vars(per op) doesn't look clean. 

2) The use may have a option to turn off or on. I don't think tf.where in auto-clustering will always hurt.

2022-05-26 18:05 UTC, cheshire requested changes
Maybe add a test that tf.where is not actually autoclustered?

2022-06-16 01:09 UTC, wenscarl commented
> Forking a process and writing to a global directory for a test is really not great. Maybe look at existing C++ tests for autoclustering?
Could you give me a pointer where to add the C++ test? How about `compilability_check_util_test.cc` ?

2022-06-16 06:03 UTC, cheshire commented
I would expect something along the lines of https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/jit/mark_for_compilation_pass_test.cc;l=180-197

2022-06-17 03:22 UTC, wenscarl commented
> I would expect something along the lines of https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/jit/mark_for_compilation_pass_test.cc;l=180-197

Test fail with
`bazel test -test_env=TF_XLA_FLAGS=--tf_xla_cluster_exclude_ops=Where   --config=cuda  -c opt //tensorflow/compiler/jit:compilation_passes_test 
`
and pass with 
`bazel test  --config=cuda  -c opt //tensorflow/compiler/jit:compilation_passes_test 
`
which are as expected.

2022-07-08 18:32 UTC, wenscarl commented on tensorflow/compiler/jit/mark_for_compilation_pass_test.cc
> +TEST(XlaCompilationTest, WhereUnsupported) {
This test was added.

2022-07-08 20:14 UTC, cheshire approved these changes

2022-07-11 10:12 UTC, merged