Converter for LogicalOr and LogicalAnd operations.
tensorflow/tensorflow pull request #55849
Opened 2022-05-03 18:42 UTC by drivanov

Implementation of the converters for LogicalOr and LogicalAnd operations.

2022-05-03 18:43 UTC, drivanov commented
Replacement for [PR#55548](https://github.com/tensorflow/tensorflow/pull/55548)

2022-05-03 18:50 UTC, bixia1 approved these changes

2022-05-03 22:10 UTC, bixia1 requested changes
Test still fail.

2022-05-05 03:01 UTC, drivanov commented
@bixia1 : I fixed it. In my previous check-in I was using 
```
#if IS_TRT_VERSION_GE(8, 2, 0, 0)
    return ValidateImpl(....);
#else
    return errors::Unimplemented("Boolean op: ", params_->node_def.op(),
                                 " is not supported in TRT version < 8.2");
#endif
```
for the wrong class (`ConvertBinary` instead of `ConvertBooleanBinary`)

2022-05-05 15:30 UTC, bixia1 approved these changes

2022-05-05 16:17 UTC, merged