[TF-TRT] Variable converters follow-up: INT8 support and edge cases
tensorflow/tensorflow pull request #56050
Opened 2022-05-10 15:28 UTC by Nyrio

This PR is a follow-up of #55337 and #55608.
I will mark this as draft until the aforementioned PRs are reviewed and merged, to facilitate the review of this one.

It includes test and fixes for the following cases:

- INT8 support
- Variables shared by multiple engines
- `BiasAdd`, `BatchMatMul`, and binary ops with two constant inputs
- Segments with only resource inputs

2022-06-01 10:16 UTC, gbaned commented
@Nyrio This PR is in draft, any update on this? Please. Thank you!

2022-08-22 13:54 UTC, Nyrio commented
@bixia1  Following the merge of #55608, this one is now up for review.

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/testdata/gen_tf_variablev2_copy_model.py
> +import numpy as np
Please add copyright header.

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/testdata/gen_tf_variablev2_copy_model.py
> +  """Generate a model to test 1 VariableV2 node used in 2 engines."""
s/Generate/Generates/

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/testdata/gen_tf_variablev2_copy_model.py
> +    """Define model with a TF graph."""
s/Define/Defines/

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +  """Execute test with model freezing disabled.
s/Execute/Executes/

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +  """Execute all tests in a class with model freezing disabled."""
s/Execute/Executes/

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +  The engines comprise ops that require constant inputs, so this checks that
maybe s/so this checks/the tests check/ ?

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +  # TODO: figure out why the two engines seem to have resource inputs
Please add a period to the end of the TODO.

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    """Return the expected engines to build."""
s/Return/Returns/

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +  If the model were frozen, this would be constant-folded. This checks that
s/This/The tests/ ?

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +  If the model were frozen, this would be constant-folded. This checks that
s/This/The tests/ ?

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/trt_convert_test.py
> +    """Test conversion of ReadVariableOp nodes in INT8 precision."""
s/Test/Tests/

2022-08-23 19:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/trt_convert_test.py
> +    """Special."""
Can you expand this doc string?

2022-08-24 14:35 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/trt_convert_test.py
> +        # Return a list of input tensors
Please add a period to the end.

2022-08-24 15:36 UTC, bixia1 approved these changes

2022-08-24 16:51 UTC, gbaned commented
Hi @Nyrio Can you please resolve conflicts? Thank you!

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc
> +        // variable node, copy all to the graphdef.
s/all/the Identify nodes/

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc
> +      trt_inputs++;
You may want to use absl::c_for_each to rewrite this.

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
> +  int j = 0;
Can you replace j with a more meaning variable name?

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/segment/segment.cc
> +          // We need to make sure that an identity that follows a variable is
s/identity that/ identity node/?

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    # TODO: dynamic engine / static engine?
s/TODO/TODO(lsugy)/

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    """Return the expected engines to build."""
Can you fix this?

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    # TODO: dynamic engine / static engine?
s/TODO/TODO(lsugy)/

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    """Return the expected engines to build."""
s/Return/Returns/

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    # TODO: dynamic engine / static engine?
s/TODO/TODO(lsugy)/

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    """Return the expected engines to build."""
s/Return/Returns/

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    # TODO: dynamic engine / static engine?
s/TODO/TODO(lsugy)/

2022-08-31 15:26 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +    """Return the expected engines to build."""
s/Return/Returns/

2022-09-07 16:22 UTC, bixia1 approved these changes

2022-09-07 16:49 UTC, bixia1 requested changes

2022-09-07 16:49 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/testdata/gen_tf_variablev2_copy_model.py
> +def GenerateModelWithVariableV2_1Var2Engines(tf_saved_model_dir):
There is a problem with the name of the function, 
let's s/_1/One/

P<exempt>setUp|tearDown|setUpModule|tearDownModule)|(?P<PascalCase>_?[A-Z][a-zA-Z0-9]*)|(?P<snake_case>_?[a-z][a-z0-9_]*))$' pattern [invalid-name]

2022-09-07 16:49 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +from tensorflow.python.platform import test
this line should goes before the current line 32

2022-09-07 16:49 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/variables_test.py
> +from tensorflow.python.saved_model import save, signature_constants
Need to use two import lines for this

Imports should be on separate lines;

2022-09-07 16:49 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/trt_convert_test.py
> +    self.assertEqual(len(engines), 2)
use assertLen instead

2022-09-07 16:49 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/trt_convert_test.py
> +    def input_fn():
s/input_fn/inputFn/ or similar, to use consistent naming conversion in the file

2022-09-07 16:49 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/testdata/gen_tf_variablev2_copy_model.py
> +import tensorflow as tf
import tensorflow is not allowed within tensorflow, import the module instead

2022-09-07 20:17 UTC, tfeher reviewed
Thanks @Nyrio for the PR. Overall it looks good to me, I just have one question for clarification.

2022-09-08 09:36 UTC, Nyrio commented on tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc
> +      } else if (input_node->type_string() == "Identity") {
If I remember correctly, the problem was that when an `Identity` node is an input of multiple nodes, some of which are not in the segment, it's not included in the segment, hence the need to copy.

2022-09-09 13:18 UTC, bixia1 approved these changes

2022-09-09 13:31 UTC, bixia1 requested changes

2022-09-09 13:31 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/testdata/gen_tf_variablev2_copy_model.py
> +def GenerateModelWithVariableV2_OneVarTwoEngines(tf_saved_model_dir):
Need to remove _ from the name to make this a camel case

2022-09-12 23:10 UTC, bixia1 approved these changes

2022-09-14 20:35 UTC, bixia1 requested changes
test fails, emailed log to author.

2022-09-20 09:55 UTC, Nyrio commented
@bixia1 I haven't received the test logs, can you please try to send them again?

2022-09-21 10:26 UTC, gbaned commented
Hi @Nyrio Can you please resolve conflicts? Thank you!

2022-09-22 16:59 UTC, Nyrio commented
Thanks @bixia1 for the test logs. I have fixed the test failures and solved conflicts.

2022-09-23 18:32 UTC, gbaned commented
Hi @Nyrio Can you please resolve conflicts? Thank you!

2022-09-27 23:40 UTC, bixia1 approved these changes

2022-09-27 23:42 UTC, bixia1 approved these changes

2022-09-28 21:03 UTC, bixia1 requested changes
emailed test failure log to author.

2022-09-28 21:03 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
> +  int num_inputs = calib_ctx->device_tensors_.size();
this variable is not used.

2022-09-29 10:34 UTC, Nyrio commented
@bixia1 Thanks for the test logs. I added the missing `@test_util.run_v2_only` flag to the new python test and removed the unused variable.

2022-09-29 16:35 UTC, bixia1 approved these changes

2022-10-03 15:19 UTC, bixia1 requested changes
still test failure, emailed log to author.

2022-10-05 15:40 UTC, Nyrio commented
@bixia1 Don't mind the first push. The second contains a fix for the failing tests.

2022-10-05 15:47 UTC, bixia1 approved these changes

2022-10-10 08:47 UTC, Nyrio commented
@bixia1 Can you please send me the test logs?

2022-10-12 15:41 UTC, bixia1 commented
> Reference

Resent the log.

2022-10-24 15:15 UTC, bixia1 approved these changes

2022-10-24 15:23 UTC, bixia1 commented
Please resolve conflicts.

2022-11-01 16:27 UTC, bixia1 approved these changes

2022-11-10 13:41 UTC, Nyrio commented
@bixia1 Can you please send me the logs of the internal CI build?

2023-03-15 18:18 UTC, poulsbo commented
This is failing on Windows with "One or more test dependencies are not in the pip package."

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/tf_sig_build_dockerfiles/devel.usertools/code_check_full.bats

@pjannaty Does this repro for your team?

```
No message!
(in test file /usertools/code_check_full.bats, line 210)
  `exit 1' failed
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow/tools/pip_package
Loading: 599 packages loaded
Loading: 601 packages loaded
Loading: 601 packages loaded
Loading: 0 packages loaded
Loading: 40 packages loaded
Loading: 40 packages loaded
Loading: 0 packages loaded
Loading: 1 packages loaded
Loading: 1 packages loaded
One or more test dependencies are not in the pip package.
If these test dependencies need to be in the TensorFlow pip package, please
add them to //tensorflow/tools/pip_package/BUILD. Otherwise, add the no_pip tag
to the test, or change code_check_full.bats in the SIG Build repository. That's
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/tf_sig_build_dockerfiles/devel.usertools/code_check_full.bats
Here are the affected tests:
For dependency //tensorflow/python/compiler/tensorrt/test:test_utils:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
//tensorflow/python/compiler/tensorrt/test:base_test_cpu
//tensorflow/python/compiler/tensorrt/test:base_test_gpu
//tensorflow/python/compiler/tensorrt/test:batch_matmul_test_cpu
//tensorflow/python/compiler/tensorrt/test:batch_matmul_test_gpu
//tensorflow/python/compiler/tensorrt/test:biasadd_matmul_test_cpu
//tensorflow/python/compiler/tensorrt/test:biasadd_matmul_test_gpu
//tensorflow/python/compiler/tensorrt/test:binary_tensor_weight_broadcast_test_cpu
//tensorflow/python/compiler/tensorrt/test:binary_tensor_weight_broadcast_test_gpu
//tensorflow/python/compiler/tensorrt/test:bool_test_cpu
//tensorflow/python/compiler/tensorrt/test:bool_test_gpu
//tensorflow/python/compiler/tensorrt/test:cast_test_cpu
//tensorflow/python/compiler/tensorrt/test:cast_test_gpu
//tensorflow/python/compiler/tensorrt/test:combined_nms_test_cpu
//tensorflow/python/compiler/tensorrt/test:combined_nms_test_gpu
//tensorflow/python/compiler/tensorrt/test:concatenation_test_cpu
//tensorflow/python/compiler/tensorrt/test:concatenation_test_gpu
//tensorflow/python/compiler/tensorrt/test:const_broadcast_test_cpu
//tensorflow/python/compiler/tensorrt/test:const_broadcast_test_gpu
//tensorflow/python/compiler/tensorrt/test:conv2d_test_cpu
//tensorflow/python/compiler/tensorrt/test:conv2d_test_gpu
//tensorflow/python/compiler/tensorrt/test:data_dependent_shape_test_cpu
//tensorflow/python/compiler/tensorrt/test:data_dependent_shape_test_gpu
//tensorflow/python/compiler/tensorrt/test:dynamic_input_shapes_test_cpu
//tensorflow/python/compiler/tensorrt/test:dynamic_input_shapes_test_gpu
//tensorflow/python/compiler/tensorrt/test:identity_output_test_cpu
//tensorflow/python/compiler/tensorrt/test:identity_output_test_gpu
//tensorflow/python/compiler/tensorrt/test:int32_test_cpu
//tensorflow/python/compiler/tensorrt/test:int32_test_gpu
//tensorflow/python/compiler/tensorrt/test:lru_cache_test_cpu
//tensorflow/python/compiler/tensorrt/test:lru_cache_test_gpu
//tensorflow/python/compiler/tensorrt/test:memory_alignment_test_cpu
//tensorflow/python/compiler/tensorrt/test:memory_alignment_test_gpu
//tensorflow/python/compiler/tensorrt/test:multi_connection_neighbor_engine_test_cpu
//tensorflow/python/compiler/tensorrt/test:multi_connection_neighbor_engine_test_gpu
//tensorflow/python/compiler/tensorrt/test:neighboring_engine_test_cpu
//tensorflow/python/compiler/tensorrt/test:neighboring_engine_test_gpu
//tensorflow/python/compiler/tensorrt/test:quantization_test_cpu
//tensorflow/python/compiler/tensorrt/test:quantization_test_gpu
//tensorflow/python/compiler/tensorrt/test:rank_two_test_cpu
//tensorflow/python/compiler/tensorrt/test:rank_two_test_gpu
//tensorflow/python/compiler/tensorrt/test:reshape_transpose_test_cpu
//tensorflow/python/compiler/tensorrt/test:reshape_transpose_test_gpu
//tensorflow/python/compiler/tensorrt/test:test_utils
//tensorflow/python/compiler/tensorrt/test:topk_test_cpu
//tensorflow/python/compiler/tensorrt/test:topk_test_gpu
//tensorflow/python/compiler/tensorrt/test:trt_engine_op_shape_test_cpu
//tensorflow/python/compiler/tensorrt/test:trt_engine_op_shape_test_gpu
//tensorflow/python/compiler/tensorrt/test:trt_mode_test_cpu
//tensorflow/python/compiler/tensorrt/test:trt_mode_test_gpu
//tensorflow/python/compiler/tensorrt/test:unary_test_cpu
//tensorflow/python/compiler/tensorrt/test:unary_test_gpu
//tensorflow/python/compiler/tensorrt/test:variables_test_cpu
//tensorflow/python/compiler/tensorrt/test:variables_test_gpu
//tensorflow/python/compiler/tensorrt/test:vgg_block_nchw_test_cpu
//tensorflow/python/compiler/tensorrt/test:vgg_block_nchw_test_gpu
//tensorflow/python/compiler/tensorrt/test:vgg_block_test_cpu
//tensorflow/python/compiler/tensorrt/test:vgg_block_test_gpu
Loading: 11 packages loaded
Loading: 11 packages loaded
```

2023-04-19 01:57 UTC, closed without merging