[oneDNN] Shape inference fix for int8 convolutions.
tensorflow/tensorflow pull request #56139
Opened 2022-05-17 16:30 UTC by Srini511

In current implementation of shape inference for convolution(fused with padding), padding dimensions are calculated only if explicit padding list is provided. For int8 convolutions (with fused paddings) we provide paddings through a padding list which is the same as explicit paddings but a different name. This PR includes padding list also into padding calculation if present.

2022-05-17 17:30 UTC, penpornk requested changes
Thank you for the PR!

Is `padding_list` only used in oneDNN ops (and vanilla TF ops that are placeholders for oneDNN ops)? Would it be possible to just change its name to `explicit_padding` to be consistent with other standard TF ops?

2022-05-17 17:30 UTC, penpornk commented on tensorflow/core/framework/common_shape_fns.cc
> +      explicit_paddings = p_list;
Please add comments explaining that fused int8 conv ops use this field to support explicit padding.

2022-05-17 21:09 UTC, Srini511 commented
> Thank you for the PR!
> 
> Is `padding_list` only used in oneDNN ops (and vanilla TF ops that are placeholders for oneDNN ops)? Would it be possible to just change its name to `explicit_padding` to be consistent with other standard TF ops?

Yes AFAIK it is used only in oneDNN int8 ops and the TF placeholders. Regarding naming, it would need changes to op signature, quantization tools like INC and possibly other places. I can discuss internally and let you know of the scope for that.
I have made the changes requested. Please take a look.

2022-07-21 22:24 UTC, penpornk approved these changes
Thank you very much for the changes and I'm so sorry for the delay!

2022-07-22 00:35 UTC, merged