Update TFL_MINIMUM_OS_VERSION
tensorflow/tensorflow pull request #56336
Opened 2022-06-02 16:58 UTC by sachinprasadhs

Updating the Update TFL_MINIMUM_OS_VERSION to 10.
Related issues: https://github.com/tensorflow/tensorflow/issues/55322, https://github.com/tensorflow/tensorflow/issues/56250

2022-06-10 16:20 UTC, gbaned commented
Hi @karimnosseir Can you please review this PR ? Thank you!

2022-07-21 23:05 UTC, yishuangP requested changes
Could you also update the ios.deployment_target in the following files? 
tensorflow/lite/ios/TensorFlowLiteC.podspec.template
tensorflow/lite/ios/TensorFlowLiteSelectTfOps.podspec

2022-07-26 23:49 UTC, yishuangP approved these changes

2022-08-03 18:13 UTC, rthadur approved these changes

2022-08-17 16:48 UTC, merged