Updating the expected behavior in TF doc
tensorflow/tensorflow pull request #56401
Opened 2022-06-08 10:52 UTC by sushreebarsa

As per the documentation, for target width and target height if the value is negative or zero, it is raising value error only for tf.image.resize_with_pad. It raises 'InvalidArgumentError' when a certain positive value is given for target height or width.  
Fixes #56333

2022-07-07 16:15 UTC, mihaimaruseac requested changes
Ideally, we'd instead change the implementation to return the valid error message in all cases instead of returning two types of errors for the same type of invalid call.

2022-07-07 16:15 UTC, mihaimaruseac commented on tensorflow/python/ops/image_ops_impl.py
> +
Remove additional empty line

2022-07-07 16:15 UTC, mihaimaruseac commented on tensorflow/python/ops/image_ops_impl.py
> +
Remove additional empty lines

2022-07-07 16:15 UTC, mihaimaruseac commented on tensorflow/python/ops/image_ops_impl.py
> +
```suggestion
```

2022-07-07 16:15 UTC, mihaimaruseac commented on tensorflow/python/ops/image_ops_impl.py
> +
```suggestion
```

2022-07-07 16:16 UTC, mihaimaruseac requested changes

2022-07-07 16:16 UTC, mihaimaruseac commented on tensorflow/python/ops/image_ops_impl.py
> +    InvalidArgumentError: if certain positive value<100, is given for target_width.
```suggestion
    InvalidArgumentError: if `target_width < 100`
```

Please also make sure that this is the right threshold, if we go via this route.

2022-07-20 10:01 UTC, gbaned commented
@sushreebarsa Can you please check @mihaimaruseac's comments and keep us posted ? Thank you!

2022-08-17 17:13 UTC, mihaimaruseac commented on tensorflow/python/ops/image_ops_impl.py
> +    InvalidArgumentError: if `target_width < 100`
Where does 100 come from?

2022-10-12 01:44 UTC, closed without merging