Allow greater version for protobuf and grpcio
tensorflow/tensorflow pull request #56464
Opened 2022-06-14 23:45 UTC by mautini

In the last version of Tensorflow, the required versions for protobuf and grpcio are defined as  

```
protobuf ~= 3.19.3
grpcio ~= 1.43.0
```

These requirements allow only bump of the patch version (according semantic versioning) and can lead to conflict with other lib that require more recent version of one of these lib.

This PR set the requirements more lenient by allowing bump to minor version (for example protobuf 3.20.0). It still restrict bump for the major version.

This behavior is more close to the requirements in tensorflow < 2.7 that was defined as 

```
protobuf >= 3.17.1
grpcio ~= 1.38.1
```

2022-06-15 15:51 UTC, mihaimaruseac requested changes
TF segfaults and cannot be build with protobuf >= 3.19. Any change here needs to also be done in the corresponding Bazel workspace

2022-07-20 15:03 UTC, mihaimaruseac commented
See also https://github.com/tensorflow/tensorflow/issues/56815

2022-07-27 18:09 UTC, mautini commented
Ok so I couldn't do anything to help right now? So I don't know if we should keep this pull request open or just close it.

2022-12-06 22:04 UTC, mihaimaruseac commented
Unfortunately nothing could be done until #53234 or `cc_shared_library` migration is fully done

2023-01-30 16:16 UTC, mautini commented
I think this commit do the job so we can close this PR : https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38

2023-01-30 18:11 UTC, mihaimaruseac commented
That is correct. Thank you.

Closing due to https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38

2023-01-30 18:11 UTC, closed without merging