[TF-TRT] Reactivate some old TF-TRT unittests. Now working correctly.
tensorflow/tensorflow pull request #56497
Opened 2022-06-17 21:40 UTC by DEKHTIARJonathan

This PR removes bypasses that were added to some failing unittests in the OSS build.

After some testing, turns out these unittest don't fail anymore. Hence I removed them

2022-06-17 21:40 UTC, DEKHTIARJonathan commented
@bixia1 for review

```
Target //tensorflow/python/compiler/tensorrt/test:base_test_gpu up-to-date:
  bazel-bin/tensorflow/python/compiler/tensorrt/test/base_test_gpu
INFO: Elapsed time: 277.803s, Critical Path: 267.90s
INFO: 5 processes: 4 internal, 1 local.
INFO: Build completed successfully, 5 total actions
//tensorflow/python/compiler/tensorrt/test:base_test_gpu                 PASSED in 265.3s

INFO: Build completed successfully, 5 total actions
```

2022-06-17 23:42 UTC, DEKHTIARJonathan commented
@bixia1 can you look into:
- b/165611343
- b/198501457
They both seem fixed. The unittests run just fine

2022-06-21 17:04 UTC, DEKHTIARJonathan commented
@bixia1 done. Can you please review ?

2022-06-22 17:42 UTC, bixia1 approved these changes

2022-06-27 15:20 UTC, bixia1 requested changes

2022-06-27 15:20 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/test/BUILD
> +load("//tensorflow/python/compiler/tensorrt:tensorrt.bzl", "tftrt_py_test", "TFTRT_PY_TEST_TAGS")
TFTRT_PY_TEST_TAGS is not used.

2022-06-27 15:20 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/tensorrt.bzl
> +    return kw[arg] if arg in kw else default
this is not used.

2022-06-27 15:20 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/tensorrt.bzl
> +def tftrt_py_test(*args, **kwargs):
Please add doc string to this function.

2022-06-28 16:20 UTC, DEKHTIARJonathan commented on tensorflow/python/compiler/tensorrt/test/BUILD
> +load("//tensorflow/python/compiler/tensorrt:tensorrt.bzl", "tftrt_py_test", "TFTRT_PY_TEST_TAGS")
Fixed

2022-06-28 16:20 UTC, DEKHTIARJonathan commented on tensorflow/python/compiler/tensorrt/tensorrt.bzl
> +    return kw[arg] if arg in kw else default
Fixed

2022-06-28 16:21 UTC, DEKHTIARJonathan commented on tensorflow/python/compiler/tensorrt/tensorrt.bzl
> +def tftrt_py_test(*args, **kwargs):
Fixed

2022-06-28 17:52 UTC, bixia1 approved these changes

2022-06-28 17:57 UTC, bixia1 requested changes

2022-06-29 15:52 UTC, DEKHTIARJonathan commented on tensorflow/python/compiler/tensorrt/tensorrt.bzl
> +    """Helper function providing a common base for Python TF-TRT Unittests."""
@bixia1 I can't "document" `*args` and `**kwargs` they are arbitrary arguments. By design they are design to allow anything to be passed.

Aside of this, virtually no `.bzl` provide a docstring, and clearly not argument-level docstring.
Examples:
- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl
- https://github.com/tensorflow/tensorflow/blob/master/third_party/tensorrt/tensorrt_configure.bzl

If you want me to add a docstring just tell me exactly what you want to be added, I don't see how to document this further

2022-07-01 18:50 UTC, bixia1 approved these changes

2022-07-01 19:27 UTC, bixia1 requested changes
There are test failure, will email log to author.

2022-07-08 16:22 UTC, gbaned commented
Hi @DEKHTIARJonathan/@bixia1 Any update on this PR? Please. Thank you!

2022-07-11 15:49 UTC, bixia1 commented
waiting for author to fix the test failure.

2022-08-03 10:10 UTC, gbaned commented
Hi @DEKHTIARJonathan Any update on this PR? Please. Thank you!

2022-08-10 19:47 UTC, DEKHTIARJonathan commented on tensorflow/python/compiler/tensorrt/tensorrt.bzl
> +    """Helper function providing a common base for Python TF-TRT Unittests."""
Fixed

2022-08-10 20:42 UTC, DEKHTIARJonathan commented
@bixia1 comments addressed. Please review

2022-08-11 15:26 UTC, bixia1 approved these changes

2022-08-24 16:49 UTC, gbaned commented
Hi @DEKHTIARJonathan Can you please resolve conflicts? Thank you!

2022-08-26 16:18 UTC, bixia1 requested changes
Please resolve conflicts.

2022-09-09 17:59 UTC, gbaned commented
@DEKHTIARJonathan Any update on this PR? Please. Thank you!

2022-09-23 18:25 UTC, gbaned commented
@DEKHTIARJonathan Any update on this PR? Please. Thank you!

2022-10-11 17:44 UTC, DEKHTIARJonathan commented
@bixia1 rebased and refactored. Please review

2022-10-11 18:13 UTC, bixia1 approved these changes

2022-10-18 18:33 UTC, DEKHTIARJonathan commented
@bixia1 : any reason why this PR can't be merged. Approved for 7+ days

2022-10-18 21:43 UTC, bixia1 commented
emailed you the error log again.

2022-10-19 15:05 UTC, bixia1 approved these changes

2022-10-19 16:05 UTC, bixia1 requested changes
there are still test failing. emailed log to author.

2022-11-07 18:33 UTC, gbaned commented
@DEKHTIARJonathan Any update on this PR? Please. Thank you!

2022-12-04 13:08 UTC, gbaned commented
@DEKHTIARJonathan Any update on this PR? Please. Thank you!

2022-12-13 10:43 UTC, gbaned commented
@DEKHTIARJonathan Any update on this PR? Please. Thank you!

2022-12-28 10:33 UTC, gbaned commented
@DEKHTIARJonathan Any update on this PR? Please. Thank you!

2023-03-21 18:38 UTC, gbaned commented
@DEKHTIARJonathan Any update on this PR? Please. Thank you!

2023-04-19 01:57 UTC, closed without merging