Fixes byte order for uint16 and bfloat variables based on endianness
tensorflow/tensorflow pull request #56601
Opened 2022-06-28 06:02 UTC by vibhutisawant

This PR fixes `//tensorflow/python/lib/core:bfloat16_test` test case on s390x arch.

Test case initially failed for s390x arch because the `little_endian_uint16` and `little_endian_bfloat` variables were defined with byte order as little-endian. Updating the byte order to Big Endian fixes this test case on s390x. Added an "if guard" to handle the byte order of these variables based on endianness.

2022-06-28 11:09 UTC, tilakrayal commented
@vibhutisawant,
Could you please sign CLA. Thank you!

2022-06-29 05:35 UTC, vibhutisawant commented
Hi @tilakrayal 
I have been covered under corporate CLA(IBM). I see the CLA check in the PR has passed. Please let me know if something is missing. Thanks

2022-07-13 10:35 UTC, vibhutisawant commented
Hi @mattdangerw, could you please take a look? Thanks!

2022-08-03 09:03 UTC, vibhutisawant commented
Hi @wangpengmit could you please have a look at this PR? Thanks!

2022-08-09 13:43 UTC, gbaned commented
Hi @cantonios Can you please review this PR ? Thank you!

2022-08-09 17:02 UTC, cantonios requested changes
There are several issues with this original test:
- The little-endian stuff is clearly wrong, everything should just be consistently in native order
- There are parts copied from the NextAfter test that shouldn't be there
- There's an unused `nan` definition that is overwritten

The entire test should read something like:
```
  def testCopySign(self, float_type):
    if float_type == float8_e4m3b11:
      self.skipTest("Not supported")  # Nans don't have payload.
    for nan_payload in list(range(1, 128)):
      with self.subTest(nan_payload):
        inf_bits = 0x7f80
        nan_bits = inf_bits | nan_payload

        nan = np.uint16(nan_bits).view(bfloat16)
        nan_with_sign = np.copysign(nan, bfloat16(-1))
        nan_with_sign_bits = nan_with_sign.view(np.uint16)
        np.testing.assert_equal(nan_bits | (1 << 15), nan_with_sign_bits)
```
Can you check that this modified test works on your machine and update the PR?

2022-08-09 17:02 UTC, cantonios commented on tensorflow/python/lib/core/bfloat16_test.py
> +          native_uint16 = np.dtype(np.uint16).newbyteorder("L")
... but it's unnecessary.  We should just be using native order.  See the other comment.

2022-08-10 10:59 UTC, vibhutisawant commented on tensorflow/python/lib/core/bfloat16_test.py
> +          native_uint16 = np.dtype(np.uint16).newbyteorder("L")
I have tested the above-modified patch on s390x arch and it works as expected. Will update the PR.

2022-08-10 14:27 UTC, vibhutisawant commented on tensorflow/python/lib/core/bfloat16_test.py
> +          native_uint16 = np.dtype(np.uint16).newbyteorder("L")
Hi @cantonios, I have updated the PR with the above changes. Could you please take a look? Thank you so much.

2022-08-10 15:08 UTC, cantonios approved these changes

2022-08-10 15:08 UTC, cantonios commented on tensorflow/python/lib/core/bfloat16_test.py
> +          native_uint16 = np.dtype(np.uint16).newbyteorder("L")
Great, thanks!

2022-08-12 16:34 UTC, merged