[TF:TRT] Refactor einsum converter to use IEinsumLayer
tensorflow/tensorflow pull request #56617
Opened 2022-06-29 07:12 UTC by tfeher

This PR refactors the Einsum converter to use IEinsumLayer which is available in TRT 8.2.

Using IEinsumLayer improves the performance and enables conversion of additional equation types.

Additionally the test of validation mode is improved:
 - The expected status of validation was not checked if the actual status was OK.
 - This is now corrected: the validation status is always checked.

2022-07-05 23:25 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc
> +// Helper class to reindex equations to contain only lowercase characters.
Would you please document these:
   Assumption on the input string, ReIndexer(eq), if there are such assumption.
   How do we reindex equations to contain only lowercase chars.

2022-07-05 23:25 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc
> +    }
Let's add a comment this code block
  // If lower(c) is not used in the equation, use it to replace c.

2022-07-05 23:25 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc
> +    for (char k = 'a'; k <= 'z'; k++) {
Let's add a comment for this code block:
// Otherwise, find the first available lower case to replace c.

2022-07-05 23:25 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc
> +    equation = MakeLowerCase(*eq);
Can you put a comment to explain why we need to rewrite the equation with lower cases?

2022-07-06 10:08 UTC, tfeher commented
Thanks @bixia1  for the first look! The PR is still draft, I am debugging a corner case in the unit test, I will re-enable all the tests once that is done. I will address the issues and I will ping you when it is ready for review!

2022-07-12 20:53 UTC, tfeher reviewed
Thanks @bixia1 for the review, I have addressed the issues so far. The PR is ready for review.

2022-07-13 16:46 UTC, bixia1 approved these changes

2022-07-19 17:43 UTC, bixia1 requested changes
Emailed test failure log to author.

2022-07-20 19:35 UTC, tfeher commented
As discussed offline with @bixia1, the reason for the failure was a modification of the validation checks. I have separated that change into #56843. 

The tests for this PR should be passing now. We can merge the current PR first, and continue with #56843 afterwards.

2022-07-20 21:40 UTC, bixia1 approved these changes

2022-07-21 14:50 UTC, merged