Fix crash during shutdown in distributed training
tensorflow/tensorflow pull request #56634
Opened 2022-06-30 10:17 UTC by Flamefire

Releasing and reaquiring the GIL during Python shutdown is not possible and leads to force termination.
Remove that.

Fixes #50853

2022-08-09 13:59 UTC, gbaned commented
Hi @mdanatg Can you please review this PR ? Thank you!

2022-10-07 17:46 UTC, mdanatg commented
@gbaned Sorry for the delay. I no longer have approval rights on the tensorflow repo...

2022-11-03 16:27 UTC, rainwoodman requested changes
Thanks for the fix. Could you add a comment in line 567 referring back to the bug for the reasons of not releasing the GIL for functions likely called on the exit path? 

There are many other places that may release GIL and may sit on the exit path. We recently encountered a deadlock that also tracks back to the release of GIL near exit, but the origin is from the dealloc of an extension type. I also know that freeing Tensor object releases GIL too, and not releasing GIL from that path could potentially become a performance regression.

My understanding is that there are changes in Python upstream (but I don't immediately recall the version 3.10?) that makes GIL use during exit safer in general. We haven't tried if it can solve the deadlock issue. I wonder if it is an option for you to try with a newer CPython version?

2022-11-22 13:44 UTC, Flamefire commented
@rainwoodman 
> Could you add a comment in line 567 referring back to the bug for the reasons of not releasing the GIL for functions likely called on the exit path?

Sorry for the delay, I added the requested comment and rebased onto current master.

2022-12-29 16:29 UTC, gbaned commented
Hi @rainwoodman Can you please review this PR ? Thank you!

2023-01-11 22:09 UTC, rainwoodman approved these changes

2023-01-11 22:09 UTC, rainwoodman commented
Thanks for the update. Sorry for the late approval. This almost missed my inboxes.

2023-01-18 13:19 UTC, merged