[NVIDIA TF] Revert TF32+NHWC changes
tensorflow/tensorflow pull request #56744
Opened 2022-07-12 22:02 UTC by kaixih

After some more extensive tests, we think we need to revert those PRs regarding the NHWC+TF32 changes:
https://github.com/tensorflow/tensorflow/pull/55761
https://github.com/tensorflow/tensorflow/pull/55806
https://github.com/tensorflow/tensorflow/pull/55920

During the tests, we noticed that in some cases the NCHW kernels are faster on Ampere. So, we think it is still a good practice to use NCHW by default for fp32/tf32 at this point.

cc. @nluehr @pjannaty

2022-07-14 17:44 UTC, pjannaty commented
Discussed offline the alternative approach of only reverting [55920](https://github.com/tensorflow/tensorflow/pull/55920), but decided to revert all three PRs to disallow the default NHWC usage for fp32/tf32 no matter in graph level ([55761](https://github.com/tensorflow/tensorflow/pull/55761)) or op level ([55806](https://github.com/tensorflow/tensorflow/pull/55806)).

2022-07-28 18:01 UTC, ezhulenev approved these changes

2022-08-05 18:08 UTC, reedwm requested changes

2022-08-05 18:08 UTC, reedwm commented on tensorflow/core/kernels/conv_ops_gpu.cc
>  }
You forgot to delete this `}`, causing build failures.

2022-08-08 09:32 UTC, gbaned commented
@kaixih Can you please check @reedwm's comments and keep us posted ? Thank you!

2022-08-08 21:28 UTC, kaixih commented
Fixed. Can you PTAL? @reedwm

2022-08-09 22:42 UTC, rthadur approved these changes

2022-08-16 19:41 UTC, kaixih commented
It seems this PR has been stuck there for a while after it got approved. Can someone help on this? @rthadur @reedwm

2022-08-16 21:03 UTC, rthadur commented
Hi @kaixih sorry for the delay , PR is failing internally with below error , can you please take a look 

```
`tensorflow/python/framework/ops.py", [line 7209]
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer "self_attention" "                 f"(type CachedAttention).

{{function_node __wrapped__Einsum_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Expected dimension 2 at axis 1 of the input shaped [12,3,2,6] but got dimension 3 [Op:Einsum]

Call arguments received by layer "self_attention" "                 f"(type CachedAttention):
  • query=tf.Tensor(shape=(12, 2, 12), dtype=float32)
  • value=tf.Tensor(shape=(12, 2, 12), dtype=float32)
  • key=None
  • attention_mask=tf.Tensor(shape=(12, 1, 2), dtype=float32)
  • cache={'key': 'tf.Tensor(shape=(12, 3, 2, 6), dtype=float32)', 'value': 'tf.Tensor(shape=(12, 3, 2, 6), dtype=float32)'}
  • decode_loop_step=None
  • return_attention_scores=False`
```

2022-08-16 22:25 UTC, reedwm commented
@kaixih let me know if you need more information than the error message above. If so I can work on getting an example to reproduce the error.

2022-08-17 04:22 UTC, kaixih commented
@rthadur Thanks for providing the log. But it seems it is unrelated to the changes of this PR.

Yes, I think I do need a repro example to dig into. @reedwm Can you help with this? Thanks.

2022-08-18 02:52 UTC, merged