Fix upstream rocm xla
tensorflow/tensorflow pull request #56779
Opened 2022-07-15 01:06 UTC by rahulbatra85

2022-07-15 12:50 UTC, cheshire requested changes

2022-07-15 21:45 UTC, rahulbatra85 commented on tensorflow/compiler/xla/service/gpu/runtime_intrinsics.cc
> +XLA_REGISTER_CUSTOM_CALL_TARGET_WITH_SYM(kXlaGpuAssertCustomCallTag,
Added a symbol, but had to merge this with another PR https://github.com/tensorflow/tensorflow/pull/56781 as both this PR and that has dependency on the new symbol

New PR is here https://github.com/tensorflow/tensorflow/pull/56793(merges 56781 and 56779)

2022-07-15 21:46 UTC, rahulbatra85 commented on tensorflow/compiler/xla/service/gpu/runtime_intrinsics.cc
> +XLA_REGISTER_CUSTOM_CALL_TARGET_WITH_SYM(kXlaGpuAssertCustomCallTag,
Will close this

2022-07-15 21:48 UTC, rahulbatra85 commented on tensorflow/compiler/xla/service/gpu/tests/gpu_atomic_test.cc
> +CHECK: atomicrmw fadd ptr addrspace(1) %[[ADDR:.*]], float %[[VALUE:.*]] syncscope("agent") seq_cst
This is a ROCm specific check. Also, it built fine on Nvidia platform

2022-07-18 17:19 UTC, rahulbatra85 commented
Duplicated here https://github.com/tensorflow/tensorflow/pull/56793

2022-07-18 17:19 UTC, closed without merging