Updates oneDNN version for AArch64 builds.
tensorflow/tensorflow pull request #56975
Opened 2022-08-01 22:02 UTC by nSircombe

Moves oneDNN version for AArch64 build from v2.6 to
70d1198de554e61081147c199d661df049233279

Includes fixes to matmul broadcase which resolves a number
of unit test failures - https://github.com/oneapi-src/oneDNN/pull/1380

Removes superfluous patches for oneDNN 2.6.

2022-08-02 05:45 UTC, nSircombe commented
Hi @penpornk,
This PR moves the oneDNN build forward to include a number of fixes on AArch64. This means we can remove a number of skipped tests from the CI/CD pipeline (those changes are also included in that patch). 
If this change look OK, please could we consider it for a cherry-pick onto the 2.10 release branch?

2022-08-02 17:59 UTC, penpornk approved these changes
Thank you for the PR! Let's get this merged into master first. I will try to cherry-pick this into 2.10 if things seem stable.

2022-08-02 19:05 UTC, nSircombe commented
That sounds good to me, thanks @penpornk.

2022-08-03 01:27 UTC, penpornk commented
@nSircombe Could you please help resolve the conflict? Thank you!

2022-08-03 05:41 UTC, nSircombe commented
Hi @penpornk, 
The conflict should be resolved now.

2022-08-03 05:42 UTC, gbaned approved these changes

2022-08-03 15:35 UTC, penpornk requested changes
Thank you for the update!

2022-08-03 15:35 UTC, penpornk commented on tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_pip.sh
> +    -//tensorflow/python/kernel_tests/control_flow:scan_ops_test_gpu \
These two lines are added by the latest merge commit, but they are not in master. Shouldn't they be under the `$TF_TEST_TARGETS` line instead?

2022-08-03 20:27 UTC, penpornk approved these changes
Thank you for the update!

2022-08-05 02:46 UTC, merged