[ROCm] gpu solvers support
tensorflow/tensorflow pull request #57102
Opened 2022-08-11 10:10 UTC by i-chaochen

1. three OPs (TrsmBatched, Trsv and Gesvd) support from rocm are added.
2. separate OPs between hip/rocSolver and rocBlas in rocm_solvers.cc with description, which is used to mix together and now it's similar to cuda_solvers.cc. This will benefit for adding new OPs in the future. 

/cc @cheshire

2022-08-11 16:26 UTC, cheshire approved these changes

2022-08-31 08:13 UTC, cheshire approved these changes

2022-08-31 08:23 UTC, cheshire requested changes

2022-08-31 08:23 UTC, cheshire commented on tensorflow/compiler/xla/mlir_hlo/tests/Dialect/lhlo/BUILD~merged
> +load("//tensorflow:tensorflow.bzl", "filegroup")
Does this change belong in this PR?

2022-08-31 14:18 UTC, i-chaochen commented on tensorflow/compiler/xla/mlir_hlo/tests/Dialect/lhlo/BUILD~merged
> +load("//tensorflow:tensorflow.bzl", "filegroup")
Nope

2022-09-01 10:32 UTC, merged