[TF-TRT]  Refactor TF-TRT to use OpConverterBase
tensorflow/tensorflow pull request #57114
Opened 2022-08-12 01:28 UTC by pavanimajety

This commit moves the Softmax TF-TRT conversion to use OpConverterBase classes. 

@tfeher @DEKHTIARJonathan @bixia1  Please review

2022-08-12 22:43 UTC, bixia1 commented
The dependent PR is merged, can you rebase?

2022-08-12 22:46 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/ops/softmax.cc
> +#if GOOGLE_CUDA && GOOGLE_TENSORRT
Please add license header, can copy and paste from another source file then change the year to 2022.

2022-08-12 22:46 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/ops/softmax.cc
> +    // Tensorflow SoftMax assumes applying softmax on the last dimension.
s/assumes applying/applies/

2022-08-19 22:31 UTC, bixia1 approved these changes

2022-08-22 17:10 UTC, bixia1 requested changes
compilation errors:
[third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:105](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc?l=105&ws=tap-prod-presubmit/207445590&snapshot=2):11: error: enumeration value 'kSOFTMAX' not handled in switch [-Werror,-Wswitch]
  switch (layer_type) {
          ^~~~~~~~~~
1 error generated.

[third_party/tensorflow/compiler/tf2tensorrt/convert/ops/softmax.cc:43](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/ops/softmax.cc?l=43&ws=tap-prod-presubmit/207445590&snapshot=2):17: error: unused variable 'node_def' [-Werror,-Wunused-variable]
    const auto &node_def = params.node_def;
                ^
1 error generated.

2022-08-24 16:03 UTC, bixia1 approved these changes

2022-08-24 16:27 UTC, gbaned commented
Hi @pavanimajety Can you please resolve conflicts? Thank you!

2022-08-24 19:10 UTC, bixia1 reviewed
Would you please squash the commits?

2022-08-25 19:36 UTC, bixia1 approved these changes

2022-08-25 20:18 UTC, merged