enabling VocabularyProcessor.transform to also return document length.
tensorflow/tensorflow pull request #5724
Opened 2016-11-20 01:36 UTC by abhitopia

Currently, `VocabularyProcessor.transform()` ( and `VocabularyProcessor.fit_transform()` ) do not return the sequence length of ( number of tokens in )  individual raw documents. sequence lengths are required when dealing with variable length sequences ( eg. like `dynamic_rnn` where we need to also pass the lengths of individual sequences).

After the changes in PR, both `fit_transform()` and `fit()` has following signature - 
- `VocabularyProcessor.fit_transform( raw_documents, return_docs_len=False, unused_y=None)`
- `VocabularyProcessor.transform( raw_documents, return_docs_len=False)`

Setting `return_docs_len=True` makes above function to also yield the number of token in individual documents.

2016-11-21 11:13 UTC, enizhibitsky commented
According to `fit_transform(X, y)` semantic, you should place your flag after `unused_y`.

2016-11-22 13:03 UTC, abhitopia commented
@enizhibitsky - Thanks for pointing out. Made the changes.

2016-11-23 19:31 UTC, abhitopia commented
@martinwicke , @ilblackdragon - Have you had a chance to look at it yet? It's a very minor patch.

2016-11-28 18:45 UTC, abhitopia commented
@martinwicke - Any comments on this?

2016-11-28 19:31 UTC, martinwicke commented
@ilblackdragon I suppose we're keeping VocabularyProcessor around for lack of an alternative, would you agree? In that case, I think this is sensible, but you know the code much better.

2016-11-29 11:25 UTC, abhitopia commented
@ilblackdragon - what do you think?

2016-12-04 23:51 UTC, abhitopia commented
@martinwicke , @ilblackdragon , @danmane - been a while, please someone review.

2016-12-08 13:14 UTC, abhitopia commented
@martinwicke - It seems that @ilblackdragon is unavailable, can you assign someone else please?

2016-12-08 21:33 UTC, martinwicke commented
Sorry, everybody's at NIPS.

2016-12-13 07:55 UTC, martinwicke requested changes
Small doc change, otherwise looks good to me.

2016-12-13 07:55 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/preprocessing/text.py
> +        Additional token count also returned is `return_docs_len= True`.
add backticks around pseudocode in brackets. Make the second sentence: "If `return_doc_len` is `True`, returns a tuple `(x, n_tokens)`, where x is the word-id matrix as before, and `n_tokens` is the number of tokens in the document."

2016-12-13 17:09 UTC, ilblackdragon commented
@abhitopia Thanks for the contribution. Just a question - what do you think about `return_docs_len` to be argument of the `VocabularyProcessor` constructor? As I would expect that if `fit` returns then `transform` should return as well. Also how are you passing this (x, doc_length) into Estimator? Probably quick example would be great.

@martinwicke Yes, there is no real alternative (even after we get feature_to_id op, we still need vocabulary generator).

2017-01-11 23:39 UTC, drpngx commented
@abhitopia could you address @ilblackdragon concerns?

2017-01-15 19:24 UTC, drpngx commented
Closing due to inactivity. Feel free to reopen when you're able to address review comments.

2017-01-15 19:24 UTC, closed without merging