[XLA] Allow to prefix fusion kernel name.
tensorflow/tensorflow pull request #57249
Opened 2022-08-19 18:46 UTC by nouiz

This split https://github.com/tensorflow/tensorflow/pull/57087 as required here:

https://github.com/tensorflow/tensorflow/pull/57087#discussion_r949344998

@cheshire

2022-08-19 18:52 UTC, cheshire requested changes

2022-08-19 18:52 UTC, cheshire commented on tensorflow/compiler/xla/service/hlo_instruction.h
> +      HloComputation* fusion_computation, std::string prefix = "");
Same below.

2022-08-19 18:52 UTC, cheshire commented on tensorflow/compiler/xla/service/gpu/horizontal_loop_fusion.cc
> +  explicit HorizontalLoopFusionImpl(HloComputation* computation, std::string prefix)
Nit: absl::string_view for parameters

2022-08-19 19:20 UTC, nouiz commented
Done for both. I found another place that need this.

2022-08-20 07:51 UTC, cheshire approved these changes

2022-08-22 12:57 UTC, merged