seq2seq tutorial example not working for python 3.4/3.5 (#5118)
tensorflow/tensorflow pull request #5743
Opened 2016-11-21 08:11 UTC by Invisibility

This is a fix for issue #5118

2016-11-22 02:46 UTC, caisq commented
Can you sign the CLA please, @Invisibility ?

2016-11-22 08:33 UTC, Invisibility commented
@caisq I did sign the Google Individual CLA (based on the instructions at https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) on Nov 20 with my github account name Invisibility. Let me know if I need to do anything extra.

2016-11-22 15:32 UTC, girving requested changes

2016-11-22 15:32 UTC, girving commented on tensorflow/models/rnn/translate/data_utils.py
> +          token_ids = sentence_to_token_ids(tf.compat.as_bytes(line), vocab, tokenizer,
Fix wrapping to 80 columns.

2016-11-24 00:35 UTC, girving approved these changes

2016-11-24 00:35 UTC, girving commented
Jenkins, test this please.

2016-11-24 22:29 UTC, gunan commented
Macos tests fixed. 
Jenkins, test this please.

2016-11-24 22:40 UTC, gunan commented
Jenkins, test this please.

2016-11-26 22:27 UTC, caisq commented
@tensorflow-jenkins , test this please.

2016-11-27 00:57 UTC, caisq commented
The failure of //tensorflow/core:gpu_tracer_test in the Linux GPU build is unrelated. Merging this PR now.

Thanks, @Invisibility

2016-11-27 00:58 UTC, merged