[TFTRT] Check supported precisions before build
tensorflow/tensorflow pull request #57591
Opened 2022-09-01 18:04 UTC by nvkevihu

Checks the platform's supported precisions prior to building each engine. If the selected precision mode is not supported, terminate the program with a detailed message.

2022-09-19 04:21 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
> +  // Check if platform supports enabled precision mode
Please add a period to the end of the comment.
s/enabled/the/ ?

2022-09-19 04:21 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/utils.py
> +def get_nvidia_gpu_desc_dict():
This routine is not used outside this module, right?
Let's make it internal in this case.

2022-09-19 04:21 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/utils.py
> +  """ This function determines if the current NVIDIA GPU platform supports the
A docstring should start with a one-line summary, see [here](https://google.github.io/styleguide/pyguide.html#381-docstrings)

2022-09-19 04:21 UTC, bixia1 commented on tensorflow/python/compiler/tensorrt/utils.py
> +  - INT8 = 6.1 || 7.0 || 7.2+
Please also document the argument and the exceptions.

2022-09-21 14:57 UTC, bixia1 approved these changes

2022-09-29 16:34 UTC, bixia1 requested changes

2022-09-29 16:34 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
> +    LOG(FATAL) << error_message;
The submit system doesn't like LOG(FATAL) anymore. It is suggested to LOG(ERROR) and then return an error status.

2022-10-14 19:15 UTC, gbaned commented
@nvkevihu Can you please check @bixia1's comments and resolve conflicts?. Thank you!

2022-10-21 16:09 UTC, gbaned commented
@nvkevihu Can you please resolve conflicts? Thank you!

2022-10-26 01:26 UTC, nvkevihu commented
Sorry for the delay, resolved conflicts and addressed comments.

2022-10-26 15:19 UTC, bixia1 approved these changes

2022-12-20 11:38 UTC, gbaned commented
Hi @bixia1 Can you please review this PR ? Thank you!

2022-12-26 11:35 UTC, gbaned commented
Hi @bixia1 Can you please review this PR ? Thank you!

2023-02-07 15:21 UTC, gbaned commented
Hi @poulsbo Can you please review this PR ? Thank you!

2023-02-07 15:36 UTC, poulsbo commented
@pjannaty
Hi Pooya, could you please review (or mark as reviewed by NVIDIA) this PR? If I review it here in Github, then I will need to a find a separate reviewer on the internal Google side, which will slow things down. It's best if I do the reviews on the Google side, and NVIDIA staff (yourself or Nathan representing NVIDIA) handle the Github side.

2023-02-14 06:26 UTC, pjannaty approved these changes, later dismissed
Approved based on multiple reviews and approvals by Bixia!

2023-03-03 23:34 UTC, poulsbo commented
I'm seeing a lot of leaks, apparently from `createInferBuilder_INTERNAL`, when testing on GPU.

@pjannaty does this repro on your side?

```
[  SKIPPED ] 4 tests, listed below:
[  SKIPPED ] ConverterTest.MaybeApplyQuantizationRanges
[  SKIPPED ] OpConvTestInstantiation/OpConverter_FP32_Test.ConvertQDQDynamicRangeMode/0
[  SKIPPED ] OpConvTestInstantiation/OpConverter_FP32_Test.ConvertQDQDynamicRangeMode/1
[  SKIPPED ] OpConvTestInstantiation/OpConverter_FP32_Test.ConvertQDQDynamicRangeMode/2
E0303 15:15:43.119625    9797 heap-profile-table.cc:410] RAW: Leak check _main_ detected leaks of 696520 bytes in 694 objects
E0303 15:15:43.120497    9797 heap-profile-table.cc:430] RAW: The 20 largest leaks:
E0303 15:15:43.215939    9797 heap-profile-table.cc:451] RAW: Leak of 28800 bytes in 9 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b64589 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _start

E0303 15:15:43.216113    9797 heap-profile-table.cc:451] RAW: Leak of 28800 bytes in 9 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b5b0a9 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _start

E0303 15:15:43.216294    9797 heap-profile-table.cc:451] RAW: Leak of 28800 bytes in 9 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b5afc9 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _start

E0303 15:15:43.216508    9797 heap-profile-table.cc:451] RAW: Leak of 28800 bytes in 9 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b64f49 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _start

E0303 15:15:43.216651    9797 heap-profile-table.cc:451] RAW: Leak of 28800 bytes in 9 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b63c49 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _start

E0303 15:15:43.216799    9797 heap-profile-table.cc:451] RAW: Leak of 28800 bytes in 9 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b65109 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _start

E0303 15:15:43.216942    9797 heap-profile-table.cc:451] RAW: Leak of 28800 bytes in 9 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b651e9 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _start

E0303 15:15:43.217087    9797 heap-profile-table.cc:451] RAW: Leak of 25600 bytes in 8 objects allocated from:
	@ 0x7f98b085dbe6 NewHook()
	@ 0x7f9897278828 absl::base_internal::MallocHook::InvokeNewHookSlow()
	@ 0x556381bfd2ca slow_alloc<>()
	@ 0x556374640260 createInferBuilder_INTERNAL
	@ 0x7f9b77b58677 tensorflow::tensorrt::convert::ParameterizedOpConverterTestBase::ParameterizedOpConverterTestBase()
	@ 0x7f9b77b64e69 testing::internal::ParameterizedTestFactory<>::CreateTest()
	@ 0x7f9b5b9a65d8 testing::TestInfo::Run()
	@ 0x7f9b5b9a74e5 testing::TestSuite::Run()
	@ 0x7f9b5b9b8214 testing::internal::UnitTestImpl::RunAllTests()
	@ 0x7f9b5b9b7241 testing::UnitTest::Run()
	@ 0x7f9b77b4b9a1 main
	@ 0x7f98930bd633 __libc_start_main
	@ 0x55637425d5ea [../sysdeps/x86_64/start.S:122](https://cs.corp.google.com/piper///depot/sysdeps/x86_64/start.S?l=122&ws=tap-presubmit-server/19104818&snapshot=2) _star [...]

2023-03-03 23:46 UTC, pjannaty commented
@DEKHTIARJonathan who is most familiar with this work and can check the leaks Alan mentioned above?

2023-03-21 15:30 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-04-19 14:48 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-05-05 09:24 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-06-23 05:42 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-07-19 06:56 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-08-18 10:23 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-09-25 08:50 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-10-13 08:39 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-10-27 08:52 UTC, gbaned commented
Hi @DEKHTIARJonathan / @pjannaty Any update on this PR? Please. Thank you!

2023-10-30 06:15 UTC, gbaned commented
Hi @nvkevihu, @DEKHTIARJonathan, @pjannaty  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you!

2023-10-30 06:15 UTC, closed without merging