Fix aligned alloc on C++14 compiler as it is only C++17
tensorflow/tensorflow pull request #57707
Opened 2022-09-15 13:46 UTC by ETKNeil

See #57706 but the gist is aligned_alloc was introduced in the std c11 but was fully implemented in C++17 however a C++14 might be C11 compliant without that feature (eg GCC 7.1.0)

I just forced the condition to be both std c11 and C++17 to ensure at 100% the feature is here and fall back to the less effective method otherwise.

2022-09-15 15:55 UTC, gbaned commented
@ETKNeil Can you please sign CLA. Thank you!

2022-09-16 07:20 UTC, EKTehtris commented
> @ETKNeil Can you please sign CLA. Thank you!

Mmh not sure how to do it with my noreply github email, they say to add it to the CLA group or something

2022-09-16 08:38 UTC, ETKNeil commented
Mmh not sure how to do it with my noreply github email, they say to add it to the CLA group or something

2022-12-29 04:52 UTC, mihaimaruseac requested changes
Without CLA we're not supposed to look at the changes at all

2023-03-21 19:04 UTC, gbaned commented
Hi @ETKNeil Any update on this PR? Please. Thank you!

2023-05-05 09:24 UTC, gbaned commented
Hi @ETKNeil Any update on this PR? Please. Thank you!

2023-06-01 05:19 UTC, gbaned commented
Hi @ETKNeil Any update on this PR? Please. Thank you!

2023-06-23 05:43 UTC, gbaned commented
Hi @ETKNeil Any update on this PR? Please. Thank you!

2023-06-25 14:17 UTC, mihaimaruseac approved these changes

2023-06-25 14:17 UTC, mihaimaruseac commented
Actually, closing since CLA is missing for so long and it's been in conflict.

2023-06-25 14:17 UTC, closed without merging