Fix typos and grammar/syntax in ops.td
tensorflow/tensorflow pull request #57799
Opened 2022-09-22 08:47 UTC by tilakrayal

Fixed typo in line 498 and 502

2022-09-27 07:37 UTC, gbaned approved these changes

2022-10-01 13:20 UTC, mihaimaruseac requested changes

2022-10-01 13:20 UTC, mihaimaruseac commented on tensorflow/core/ir/ops.td
> +    inputs for successor regions. Typically, this means the number of
Please keep `that` in the text.

2022-12-29 04:50 UTC, mihaimaruseac commented on tensorflow/core/ir/ops.td
> +    inputs for successor regions. Typically, this means the number of
```suggestion
    inputs for successor regions. Typically, this means that the number of
```

2022-12-29 04:51 UTC, mihaimaruseac approved these changes
This again is a fix for a single letter. Please avoid this in the future, collapse multiple fixes together

2022-12-30 01:12 UTC, merged