Fix crash in tf.nn.atrous_conv2d with large rate
tensorflow/tensorflow pull request #57854
Opened 2022-09-27 04:57 UTC by yongtang

This PR tries to address the issue raised in #46915 where
tf.nn.atrous_conv2d will crash when rate is larger than 2^31.

This PR fixes #46915.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2022-09-27 15:31 UTC, cantonios requested changes

2022-09-27 15:31 UTC, cantonios commented on tensorflow/python/kernel_tests/nn_ops/atrous_conv2d_test.py
> +    with self.session():
Does this needed the `run_deprecated_v1` and `with self.session()`?  We're trying to slowly update all these tests to run in V2 mode.

2022-09-28 06:21 UTC, yongtang commented
Thanks @cantonios for the review. The `@test_util.run_deprecated_v1` has been removed. Please let me know if there are any other issues needs to be addressed.

2022-09-28 15:21 UTC, cantonios approved these changes

2022-09-30 18:09 UTC, merged