Add Raises section to the documentation of tf.nn.max_pool and tf.nn.max_pool2d
tensorflow/tensorflow pull request #58039
Opened 2022-10-10 12:05 UTC by Ingkarat

Address issue[#57978](https://github.com/tensorflow/tensorflow/issues/57978). Add Raises section to the docstring of tf.nn.max_pool and tf.nn.max_pool2d.

For max_pool, raises ValueError if
- explicit padding is used with an input tensor of rank 5.
- explicit padding is used with data_format='NCHW_VECT_C'.

For max_pool2d, raises ValueError: If explicit padding is used with data_format='NCHW_VECT_C'.

2022-10-10 12:42 UTC, Ingkarat commented
For the CLA issue, it shows that there are 2 contributors possibly because the email set for git commits (non-gmail) and the email for CLA were different when creating this PR. I have changed the git email to match the CLA one but the issue still remains. I am not sure how to resolve this. Do I need to re-open the PR?

2022-10-11 01:54 UTC, mihaimaruseac requested changes
Valid, but needs proper CLA.

Try `git config --global user.name "your name"` and `git config --global user.email your.email@google.com` (skip `--global` and run the above in the TF clone if you want to only do this for TF repo). Then force push to this branch

2022-10-11 06:59 UTC, Ingkarat commented
@mihaimaruseac Thank you. I set the name and email but could not figure out how to push without making any changes and ended up creating a new empty commit. The new commit has a proper author's email and passes the CLA check, but the previous commit still fails.
Maybe I messed up somewhere. Is there a way to resolve this? Thank you again for your time.

2022-10-12 17:42 UTC, mihaimaruseac commented
Try this

```
git switch master
git pull --rebase
git switch -
git rebase -
git rebase -i HEAD~2
```

This will open a new editor with your 2 commits. Change them to be `edit`, save and exit. Then

```
git push -f
```

If this doesn't work, it might be easier to make a new PR.

2022-10-17 06:31 UTC, Ingkarat commented
@mihaimaruseac Thank you very much for the guidance. The CLA is now successful.

2022-10-17 16:34 UTC, mihaimaruseac approved these changes

2022-11-03 14:57 UTC, rohan100jain approved these changes

2022-12-28 09:58 UTC, gbaned approved these changes

2022-12-28 17:58 UTC, mihaimaruseac requested changes

2022-12-28 17:58 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_ops.py
> +
```suggestion

```

2022-12-28 17:58 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_ops.py
> +
```suggestion

```

2022-12-28 18:00 UTC, mihaimaruseac requested changes

2022-12-28 18:00 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_ops.py
> +  Raises:
```suggestion

  Raises:
```

2022-12-28 18:00 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_ops.py
> +  Raises:
```suggestion

  Raises:
```

2022-12-28 18:00 UTC, mihaimaruseac approved these changes

2022-12-28 19:19 UTC, merged