[AMD-ZENDNN] Code changes to support TF-Plugin for AMD CPU Inference
tensorflow/tensorflow pull request #58094
Opened 2022-10-14 10:23 UTC by aadwived

This pull request contains necessary/base changes for supporting TF-Plugin for AMD CPU Inference.

With this code change we introduce,
    - Functionality to enable AMD CPU optimizations by setting environment variable 'TF_ENABLE_ZENDNN_OPTS=1'
    - Zen layout pass to re-write supported ops with ZenOps

All these code changes are under AMD_ZENDNN flag which is enabled for linux builds only.

Authors:
    Aakar Dwivedi ( aakar.dwivedi@amd.com )
    Aditya Chatterjee ( aditya.chatterjee@amd.com )
    Arun Coimbatore Ramachandran ( aruncoimbatore.ramachandran@amd.com )
    Avinash-Chandra Pandey ( avinash-chandra.pandey@amd.com )
    Chandra Kumar Ramasamy ( chandrakumar.ramasamy@amd.com )
    Savan Anadani ( savan.anadani@amd.com )

Signed-off-by: Aakar Dwivedi <Aakar.Dwivedi@amd.com>

2022-10-14 10:28 UTC, cramasam commented
/cc @penpornk

2022-12-06 19:27 UTC, penpornk requested changes
Thank you for your PR and I'm so sorry for the late review!

2022-12-06 19:27 UTC, penpornk commented on tensorflow/core/util/BUILD
> +        "zen_util.h",
Please guard this with `if_zendnn`.

2022-12-06 19:27 UTC, penpornk commented on tensorflow/core/util/zen_util.h
> +  char *val = std::getenv(name);
Syscalls are expensive. We want to read the environment variable only once and cache the results for subsequent calls. Please follow the approach in `IsZenDnnDisabled()`.

2022-12-06 19:27 UTC, penpornk commented on tensorflow/core/util/port.h
> +bool IsZenDNNDisabled();
Nit: Camel case.
```suggestion
bool IsZenDnnDisabled();
```

2022-12-06 19:27 UTC, penpornk commented on tensorflow/core/util/zen_util.h
> +enum LogLevel {
May I ask why we can't use TF's existing logging framework?

2022-12-06 19:27 UTC, penpornk commented on tensorflow/core/common_runtime/BUILD
> +        ":zen_layout_pass",
Please wrap this with `if_zendnn`.

2022-12-06 19:27 UTC, penpornk commented on tensorflow/core/common_runtime/BUILD
> +    copts = tf_copts() + ["-fopenmp"],
Vanilla TF shouldn't use OpenMP. I don't think `zen_layout_pass` needs OpenMP so we can just remove it.
```suggestion
    copts = tf_copts(),
```

2022-12-29 11:02 UTC, gbaned commented
Hi @aadwived Can you please check @penpornk's comments and resolve conflicts?. Thank you!

2023-01-06 16:52 UTC, closed without merging