[ROCM] Fix gpu_atomic_test for ROCm
tensorflow/tensorflow pull request #58202
Opened 2022-10-20 21:20 UTC by rahulbatra85

Fixes test for ROCm platform

2022-10-24 08:11 UTC, cheshire requested changes
Can we unify two branches?

2022-10-24 14:18 UTC, rahulbatra85 commented
> Can we unify two branches?

@cheshire  Sorry, I am not following. Can you please explain which branches to unify?

2022-11-24 19:15 UTC, gbaned commented
Hi @cheshire Can you please review this PR ? Thank you!

2022-11-26 11:40 UTC, cheshire approved these changes

2022-11-29 07:58 UTC, merged