Sets `--experimental_link_static_libraries_once=true`.
tensorflow/tensorflow pull request #58209
Opened 2022-10-21 03:06 UTC by learning-to-play

This change ensures that no library is linked statically more than once. libtensorflow_framework.so is a dynamic dependency of _pywrap_tensorflow_internal.so. If a library is statically linked to both, Bazel complains and asks for the target to be exported from libtensorflow_framework.so. This change decreases TensorFlow Python package size.

2022-10-21 05:02 UTC, mihaimaruseac approved these changes

2022-10-21 23:13 UTC, nitins17 approved these changes, later dismissed

2022-10-22 01:30 UTC, mihaimaruseac requested changes

2022-10-22 01:30 UTC, mihaimaruseac commented on check.txt
> +Fixed-up wheel written to /tf/pkg/tf_nightly_cpu-2.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
This file needs to be removed

2022-10-22 01:30 UTC, mihaimaruseac commented on .bazelrc
> +# TF uses `cc_shared_library` targets, so it needs the experimental flag
Should we keep the TODO here?

2022-10-24 16:34 UTC, mihaimaruseac requested changes

2022-10-24 16:34 UTC, mihaimaruseac commented on .bazelrc
> +# TF uses `cc_shared_library` targets, so it needs the experimental flag
```suggestion
# TF uses `cc_shared_library` targets, so it needs the experimental flag
# TODO(rostam): Remove when `cc_shared_library` is enabled by default
```

2022-10-24 16:35 UTC, mihaimaruseac approved these changes

2023-01-04 10:26 UTC, gbaned commented
Hi @learning-to-play Can you please resolve conflicts? Thank you!

2023-01-09 06:23 UTC, learning-to-play commented
Hi @trevor-m, Would you like me to keep this PR? Or will you create a new PR for --`experimental_link_static_libraries_once=true`?

2023-01-10 20:50 UTC, trevor-m commented
> Hi @trevor-m, Would you like me to keep this PR? Or will you create a new PR for `--experimental_link_static_libraries_once=true`?

HI @learning-to-play, I think you can close this PR as long as the branch https://github.com/tensorflow/tensorflow-experimental_link_static_libraries_once is kept for my reference

2023-01-11 04:20 UTC, closed without merging