Add int8 and int16x8 support for the EXP operator
tensorflow/tensorflow pull request #58278
Opened 2022-10-24 09:57 UTC by Tessil

Hello,

This PR adds quantized int8 and int16 support for the EXP operator. It uses a lookup table to do so.

Thanks,
Thibaut

2022-10-24 14:34 UTC, abattery requested changes
Could you add e2e test cases under https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/testing/op_tests ?

2022-10-24 16:32 UTC, Tessil commented
Thanks for the review.

Aren't the changes in https://github.com/tensorflow/tensorflow/pull/58278/files#diff-49276b87644be533e959f64f5f3ad6dcd2bab42a2391c2b2d27c20d08ac6cdc5R29 sufficient for op_tests? It is similar to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/testing/op_tests/relu.py tests.

2022-10-25 04:46 UTC, abattery commented
@alankelly in the terms of quantized kernel wise, it looks okay to me.

Could you review this change as the TFLite kernel view point?

2022-11-24 19:38 UTC, gbaned commented
Hi @alankelly Can you please review this PR ? Thank you!

2022-12-06 09:04 UTC, alankelly approved these changes

2022-12-06 10:49 UTC, Tessil commented on tensorflow/lite/kernels/exp.cc
> +    LUTPopulate<int16_t>(input->params.scale, input->params.zero_point,
I merged the above zero-point check in the else if instead, hope it's alright so. Thanks.

2022-12-29 11:11 UTC, gbaned commented
Hi @alankelly Can you please review this PR ? Thank you!

2023-02-16 15:44 UTC, alankelly commented
Can you please fix the conflict and I will merge tomorrow?

2023-02-16 16:04 UTC, Tessil commented
@alankelly Thank you, I fixed the conflict.

2023-02-16 16:06 UTC, alankelly approved these changes

2023-02-16 16:08 UTC, alankelly commented
Thanks, started the merge. Reduce should also land today once the Americans wake up and approve.

2023-03-07 09:38 UTC, merged