[TFTRT]: Add graphdef visualization
tensorflow/tensorflow pull request #58327
Opened 2022-10-26 18:02 UTC by meena-at-work

Using the environment variable TF_TRT_GRAPH_DUMP_PATH, allow TFTRT to export the optimized TF graphdef in pbtxt format. This should help with debugging.

CC: @DEKHTIARJonathan @pjannaty @bixia1

2022-11-01 16:32 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc
> +  auto status = ConvertGraph(params_, optimized_item, nodes_to_preserve, cluster,
We don't use "auto" in this case. see [C++ style guide](https://google.github.io/styleguide/cppguide.html#Type_deduction)

2022-11-02 15:41 UTC, bixia1 approved these changes

2022-11-07 17:59 UTC, bixia1 requested changes

2022-11-07 17:59 UTC, bixia1 commented on tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc
> +    DumpGraphDefToFile(strings::StrCat("after_TRTOptimizer_tf_graph"),
Need to use absl::StrCat instead.

2022-11-24 21:37 UTC, gbaned commented
@meena-at-work Can you please check @bixia1's comments and keep us posted ? Thank you!

2022-11-28 15:33 UTC, pjannaty commented
@gbaned please see Meenakshi's change! Cheers!

2022-12-29 11:14 UTC, gbaned commented
Hi @bixia1 Can you please review this PR ? Thank you!

2023-03-29 21:55 UTC, DEKHTIARJonathan approved these changes

2024-04-26 07:21 UTC, gbaned commented
Hi @meena-at-work Can you please confirm if this PR is still valid? Thank you!

2024-05-25 01:49 UTC, closed without merging