stateful random ops, fix crash for empty output
tensorflow/tensorflow pull request #58336
Opened 2022-10-27 09:42 UTC by albertz

Fix #51803 for stateful random ops.

2022-11-26 11:38 UTC, cheshire requested changes
Is it possible to add a test?

2022-12-29 11:17 UTC, gbaned commented
Hi @albertz Can you please check @cheshire's comments and keep us posted ? Thank you!

2022-12-29 11:24 UTC, albertz commented
Yes I will try to do in the next week's.

2023-03-21 19:28 UTC, gbaned commented
Hi @albertz Any update on this PR? Please. Thank you!

2023-03-24 09:48 UTC, albertz commented
I'm not really familiar with the tests. How would I add a test which runs only with CUDA? Where would I add it?

2023-05-05 09:42 UTC, gbaned commented
Hi @cheshire Can you please assist on above comments from @albertz. Thank you!

2023-06-23 06:00 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2023-08-25 06:22 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2023-12-14 06:45 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2023-12-29 05:10 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2024-03-08 15:17 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2024-04-26 07:23 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2024-05-29 06:37 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2024-06-07 16:03 UTC, gbaned commented
Hi @cheshire Any update on this PR? Please. Thank you!

2024-07-09 07:02 UTC, keerthanakadiri commented
Hi @cheshire Any update on this PR? Please. Thank you!

2024-07-16 09:46 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2024-07-23 10:40 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2024-08-07 04:45 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2024-08-27 07:08 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2024-09-03 05:16 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2024-09-17 09:30 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2024-10-09 10:10 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2024-10-23 10:23 UTC, keerthanakadiri commented
Hi @cheshire , Any update on this PR? Please. Thank you!

2025-02-09 16:17 UTC, closed without merging

2025-02-09 19:42 UTC, albertz commented
Hello, why was there no response here?

2025-02-09 19:42 UTC, albertz commented
Please reopen this.

2025-02-10 14:17 UTC, mihaimaruseac commented
There was no test added after https://github.com/tensorflow/tensorflow/pull/58336#pullrequestreview-1194853762 so it looked like the PR was abandoned.

Please open a new one, including with tests.