[ROCm] xla_gpu_enable_cublaslst and matrix_ops_simple_test is cuda only
tensorflow/tensorflow pull request #58343
Opened 2022-10-27 15:55 UTC by i-chaochen

This new merged PR (https://github.com/tensorflow/tensorflow/pull/56761) only for cuda gpu so far. We hope it be more generical.

@cheshire

2022-11-02 10:28 UTC, i-chaochen commented
@cheshire gentle ping

2022-12-13 12:48 UTC, akuegel requested changes

2022-12-13 12:48 UTC, akuegel commented on tensorflow/compiler/xla/tests/matrix_ops_simple_test.cc
> +#if GOOGLE_CUDA
Maybe

```
#ifndef GOOGLE_CUDA
```
instead of

```
#if GOOGLE_CUDA
#else
```

2022-12-13 12:48 UTC, akuegel commented on tensorflow/compiler/xla/tests/dot_operation_test.cc
> +#if GOOGLE_CUDA
Maybe extract this to a variable:

```
bool enable_cublas_lt = false;
#if GOOGLE_CUDA
enable_cublas_lt = true;
#endif
execution_options_.mutable_debug_options()->set_xla_gpu_enable_cublaslt(enable_cublas_lt);
```

2022-12-13 12:48 UTC, akuegel commented on tensorflow/compiler/xla/tests/matrix_ops_simple_test.cc
> +#if GOOGLE_CUDA
Same here, #ifndef GOOGLE_CUDA

2022-12-13 12:48 UTC, akuegel commented on tensorflow/compiler/xla/tests/matrix_ops_simple_test.cc
> +#if GOOGLE_CUDA
Same here, #ifndef GOOGLE_CUDA

2022-12-13 12:48 UTC, akuegel commented on tensorflow/compiler/xla/tests/matrix_ops_simple_test.cc
> +#if GOOGLE_CUDA
Same here, #ifndef GOOGLE_CUDA

2022-12-14 12:00 UTC, i-chaochen commented
@akuegel Thanks a lot for the feedback. This is really helpful. 

All changes are made, please take another look.

2022-12-14 12:04 UTC, akuegel approved these changes

2022-12-14 13:02 UTC, merged