Add Tuple input and token support to all-gather and reduce-scatter.
tensorflow/tensorflow pull request #58377
Opened 2022-10-31 07:15 UTC by hjm-aws

2022-10-31 16:05 UTC, gbaned commented
@hjm-aws Can you please resolve conflicts? Thank you!

2022-11-02 10:02 UTC, gbaned commented
@hjm-aws Can you please sign CLA. Thank you!

2022-11-10 20:21 UTC, hjm-aws commented
> @hjm-aws Can you please sign CLA. Thank you!
Done. Thanks!

2022-11-24 22:39 UTC, gbaned commented
@hjm-aws It still shows CLA is pending, can you please sign CLA. Thank you!

2022-11-26 11:36 UTC, cheshire requested changes
Thanks a lot! Overall this makes sense, let me also check internally.

QQ: this is not decomposable, right? E.g. changes inside XLA could not be split from builder changes?

2022-11-26 11:36 UTC, cheshire commented on tensorflow/compiler/xla/client/xla_builder.cc
> +    std::vector<const Shape*> operand_shapes;
Could you also update documentation of semantics in operation_semantics.md?

2022-11-26 11:38 UTC, cheshire commented
Thanks, overall this looks like a very good change! Added @Kariddi and @blakehechtman for clarifications.

2022-11-29 15:39 UTC, jurahul commented on tensorflow/compiler/xla/service/hlo_verifier_test.cc
> +TEST_F(HloVerifierTest, ReduceScatterTwoTokens) {
I think there is some confusion here between tokens and tuples. I think the intent is to add tuple support, so we should remove any mention of tokens in test names or in the change description.

2022-11-29 17:18 UTC, jurahul requested changes

2022-11-29 17:18 UTC, jurahul commented on tensorflow/compiler/xla/client/xla_builder.cc
> +    if (operand_shape->IsTuple()) {
This looks like copy/pasted from all-reduce. Is it possible to factor it out into a helper function?

2022-11-29 17:18 UTC, jurahul commented on tensorflow/compiler/xla/client/xla_builder_test.cc
> +TEST_F(XlaBuilderTest, AllGatherWithToken) {
AllGatherWithTuple?

2022-11-29 17:18 UTC, jurahul commented on tensorflow/compiler/xla/client/xla_builder_test.cc
> +TEST_F(XlaBuilderTest, ReduceScatterWithToken) {
ReduceScatterWithTuple?

2022-11-29 17:18 UTC, jurahul commented on tensorflow/compiler/xla/service/hlo_verifier.cc
> +  // There can be one token in the input Tuple. The token is a scalar or
This is confusing IMO. Can we get clarification as to what is intent of the token input to all-gather? Also treating a scalar as a token is confusing.

2022-11-29 17:23 UTC, jurahul commented
Overall it seems this is attempting to add tuple support for all-gather and reduce-scatter as well as add a optional dummy token input to the all-gather, the purpose of which is unclear.

I think we should split this into 2 PRs, one for tuple support and discuss support for token types in all-gather separately before adding it.

2022-12-05 09:06 UTC, gbaned commented
@hjm-aws Can you please check @jurahul's comments and keep us posted ? Thank you!

2022-12-29 11:37 UTC, gbaned commented
@hjm-aws Any update on this PR? Please. Thank you!

2023-03-21 19:32 UTC, gbaned commented
@hjm-aws Any update on this PR? Please. Thank you!

2023-04-19 01:56 UTC, closed without merging

2023-09-22 04:29 UTC, jeffhataws commented
> Overall it seems this is attempting to add tuple support for all-gather and reduce-scatter as well as add a optional dummy token input to the all-gather, the purpose of which is unclear.
> 
> I think we should split this into 2 PRs, one for tuple support and discuss support for token types in all-gather separately before adding it.

@gbaned @jurahul , the revived PR on openxla is https://github.com/openxla/xla/pull/5740 .