Add int16x8 support for RSqrt operator
tensorflow/tensorflow pull request #58406
Opened 2022-11-01 14:22 UTC by SaoirseARM

Hello,

This PR adds int16x8 support for the RSQRT operator.

Thanks,
Saoirse

2022-11-24 21:04 UTC, gbaned commented
Hi @haozha111 Can you please review this PR ? Thank you!

2022-12-12 21:04 UTC, haozha111 approved these changes

2022-12-12 21:05 UTC, haozha111 commented
Adding @abattery on quantization related changes.

2023-03-08 14:24 UTC, gbaned commented
Hi @haozha111 Can you please review this PR ? Thank you!

2023-03-08 19:40 UTC, haozha111 approved these changes

2023-08-18 10:14 UTC, gbaned commented
Hi @SaoirseARM Can you please resolve conflicts? Thank you!

2023-08-23 08:05 UTC, gbaned commented
Hi @SaoirseARM Can you please resolve conflicts? Thank you!

2023-08-31 17:17 UTC, grantjensen commented on tensorflow/lite/testing/op_tests/elementwise.py
> -            "quant_16x8": [False],
Why is this case being deleted?

2023-09-04 07:57 UTC, gbaned commented
Hi @SaoirseARM Can you please check @grantjensen's comments and keep us posted ? Thank you!

2023-09-06 19:11 UTC, grantjensen requested changes
Looking at this closely, we actually should clean up this file now that rsqrt can support 16x8. If you look at [this](https://github.com/tensorflow/tensorflow/pull/60424), you'll see that we had to refactor elementwise.py bc we had an op (rsqrt) that supported allow_fully_quantize, but not 16x8. Now that it supports both, we can once again combine them. Linking below what this new file should be.
[elementwise_py.txt](https://github.com/tensorflow/tensorflow/files/12541515/elementwise_py.txt)

2023-09-26 23:14 UTC, grantjensen commented
Almost. Like I said, we can remove allow_quant_16x8. PTAL at the txt file I linked above and just use what I have there. It should work with minimal effort. If there is a reason why you are keeping allow_quant_16x8 please justify it.

2023-09-27 13:18 UTC, SaoirseARM commented
> Almost. Like I said, we can remove allow_quant_16x8. PTAL at the txt file I linked above and just use what I have there. It should work with minimal effort. If there is a reason why you are keeping allow_quant_16x8 please justify it.

Apologies, I misunderstood your comment. 
This should be fixed now.
Thanks 
- Saoirse

2023-09-27 17:22 UTC, grantjensen approved these changes

2023-09-27 17:23 UTC, grantjensen commented
No worries, my original message was a little confusing. We should be able to get your change merged shortly :)

2023-10-04 19:38 UTC, merged