Add load method to tf.Variable
tensorflow/tensorflow pull request #5860
Opened 2016-11-25 12:48 UTC by dm0

Allows loading new value into variable without adding new operations to the graph.

Sometimes it is convenient to just load new value into variable without adding new operations to the graph. For example one may want to load values into some weights from other model or model trained with other framework.

2016-11-26 02:21 UTC, caisq commented
Should the new method have unit-test coverage? @dm0

2016-11-26 17:18 UTC, dm0 commented
@caisq Probably yes. Is it correct place to add unit test to: tensorflow/python/kernel_tests/variable_ops_test.py?

2016-11-27 00:10 UTC, lukaszkaiser requested changes
This code looks good to me, but please add at least a simple unit test in python/kernel_tests/variables_test.py. Thanks!

2016-11-27 00:10 UTC, lukaszkaiser commented
I think python/kernel_tests/variables_test.py will be better. Thanks!

2016-11-28 16:18 UTC, lukaszkaiser requested changes
Let's change it so that we're loading sth different than what was there at first.

2016-11-28 16:18 UTC, lukaszkaiser commented on tensorflow/python/kernel_tests/variables_test.py
> +      var = tf.Variable(np.random.randn(5, 5))
Let's make it np.zeros first, and then load np.ones and check that it gets ones, would that be ok?

2016-11-28 18:54 UTC, dm0 commented on tensorflow/python/kernel_tests/variables_test.py
> +      var = tf.Variable(np.random.randn(5, 5))
No problem.

There is a chance that two random sequences will be the same but it is insignificant. Or am I missing something?

2016-11-28 20:52 UTC, lukaszkaiser approved these changes
Looks good, thanks!

2016-11-29 22:26 UTC, danmane commented
@tensorflow-jenkins Test this please.

2016-12-12 20:53 UTC, alexgorban commented
@tensorflow-jenkins Test this please.

2016-12-13 08:00 UTC, martinwicke commented
Failure is a flake. Thank you!

2016-12-13 08:00 UTC, merged