the priority of H2D
tensorflow/tensorflow pull request #58617
Opened 2022-11-19 12:53 UTC by zhaozheng09

Question：https://github.com/tensorflow/tensorflow/issues/58616
Modify:
We distinguish FeaturesAsyncH2D and ComputeH2D, and raise the priority of ComputeH2D and lower the priority of FeaturesAsyncH2D.
Result:
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/33950866/202851818-03031f51-a0df-4feb-a6b1-30203096a523.png">

2022-11-24 23:24 UTC, gbaned commented
@zhaozheng09 Can you please resolve conflicts? Thank you!

2022-11-25 02:57 UTC, zhaozheng09 commented
> @zhaozheng09 Can you please resolve conflicts? Thank you!

Done,

2022-12-24 03:57 UTC, zhaozheng09 commented
@gbaned Hi, Do we need this functionality?

2023-02-15 07:33 UTC, zhaozheng09 commented
@gbaned Hi, Do we need this feature? and @zhangyujing seems to have been offline for a long time

2023-03-21 11:23 UTC, gbaned commented
> what should I do now?

Hi @zhaozheng09 Sorry for the delay, nothing pending from your end now, it is awaiting for review. Thank you!

2023-03-21 11:23 UTC, gbaned commented
Hi @zhangyujing Can you please review this PR ? Thank you!

2023-03-24 15:40 UTC, cantonios requested changes
I don't know much about this code.  @reedwm any thoughts here?

2023-03-24 15:40 UTC, cantonios commented on tensorflow/core/common_runtime/gpu/gpu_util.cc
> +    }
nit: indentation is off here - please run through clang-format.

2023-03-27 19:34 UTC, reedwm commented
It looks like this PR does two independent things:
  1. Synchronize the H2D stream every time the GPU receives a total of N bytes from the host (N is determined by the `SyncSelfSizeOnce()` function, which is not declared/defined by this PR)
  2. In `RecvOutputsFromRendezvousAsync`, batch allocate all tensors instead of allocating each separately. I'm not familiar with `RecvOutputsFromRendezvousAsync` and when it is called, so I'm not sure what impact this has.

For (1), I'm not sure how this raises the priority of the H2D stream, and also I am not sure why we want to raise its priority. If we do want to raise the priority, I think setting priorities with `cudaStreamCreateWithPriority` would be a better approach. For (2), I'm not sure what the purpose is. @zhaozheng09 can you clarify?

2023-04-02 02:49 UTC, zhaozheng09 commented
> It looks like this PR does two independent things:
> 
> 1. Synchronize the H2D stream every time the GPU receives a total of N bytes from the host (N is determined by the `SyncSelfSizeOnce()` function, which is not declared/defined by this PR)
> 2. In `RecvOutputsFromRendezvousAsync`, batch allocate all tensors instead of allocating each separately. I'm not familiar with `RecvOutputsFromRendezvousAsync` and when it is called, so I'm not sure what impact this has.
> 
> For (1), I'm not sure how this raises the priority of the H2D stream, and also I am not sure why we want to raise its priority. If we do want to raise the priority, I think setting priorities with `cudaStreamCreateWithPriority` would be a better approach. For (2), I'm not sure what the purpose is. @zhaozheng09 can you clarify?

For(1): ```cudaStreamCreateWithPriority ``` is only affects the kernels, it has no effect for H2D/D2H;
For(2): I should write a simple example ...

2023-05-05 09:55 UTC, gbaned commented
Hi @reedwm Can you please take a look on the above [comment](https://github.com/tensorflow/tensorflow/pull/58617#issuecomment-1493206593) from @zhaozheng09. Thank you!

2023-06-23 06:33 UTC, gbaned commented
Hi @reedwm Any update on this PR? Please. Thank you!

2023-08-02 04:54 UTC, gbaned commented
Hi @reedwm Any update on this PR? Please. Thank you!

2023-08-25 06:25 UTC, gbaned commented
Hi @reedwm Any update on this PR? Please. Thank you!

2023-09-25 10:04 UTC, gbaned commented
Hi @reedwm Any update on this PR? Please. Thank you!

2023-12-14 06:53 UTC, gbaned commented
Hi @reedwm Any update on this PR? Please. Thank you!

2023-12-29 05:13 UTC, gbaned commented
Hi @reedwm Any update on this PR? Please. Thank you!

2024-01-19 06:27 UTC, gbaned commented
Hi @reedwm Any update on this PR? Please. Thank you!

2024-02-07 03:06 UTC, closed without merging