[XLA] Expose channel_id and use_global_device_ids of AllToAll in xla builder
tensorflow/tensorflow pull request #58626
Opened 2022-11-21 00:36 UTC by merrymercy

Similar to AllReduce and AllGather, AllToAll also supports `channel_id` and `use_global_device_ids`.
This PR exposes these options to the python API of XlaBuilder

2022-11-21 00:39 UTC, merrymercy commented
cc @cheshire

2022-11-22 10:03 UTC, cheshire requested changes
Is it possible to add tests?

2022-11-26 05:48 UTC, gbaned commented
Hi @merrymercy Can you please check @cheshire's comments and keep us posted ? Thank you!

2022-11-27 07:06 UTC, merrymercy commented
A test case is added

2022-12-17 23:43 UTC, closed without merging