enable i64 for cwise ops
tensorflow/tensorflow pull request #58717
Opened 2022-11-28 20:12 UTC by kushanam

Enabling experimental i64 bit indexing for cwise milr kernels
@frgossen

2022-12-08 09:10 UTC, frgossen requested changes
Nice! Can you clarify in the PR name / description that this adds i64-indexing support for *binary* kernels behind an experimental flag?

2022-12-08 09:10 UTC, frgossen commented on tensorflow/core/kernels/mlir_generated/BUILD
> +
nit: whitespace

2022-12-08 09:10 UTC, frgossen commented on tensorflow/core/kernels/mlir_generated/BUILD
> +
nit: whitespace

2022-12-14 19:12 UTC, kushanam commented on tensorflow/core/kernels/mlir_generated/BUILD
> +
> Nice! Can you clarify in the PR name / description that this adds i64-indexing support for _binary_ kernels behind an experimental flag?

done.

2022-12-14 19:25 UTC, kushanam commented on tensorflow/core/kernels/mlir_generated/BUILD
> +
done

2023-01-18 18:41 UTC, frgossen reviewed
Will add this kernels one by one to avoid merge conflict.

2023-02-15 06:48 UTC, gbaned commented
Hi @kushanam Can you please check @frgossen's comments and keep us posted ? Thank you!

2023-02-15 17:26 UTC, kushanam commented
> Hi @kushanam Can you please check @frgossen's comments and keep us posted ? Thank you!

Thank @gbaned. As pointed out by Frederik, the kernels will be added one by one. I want to leave this open for reference if you don't mind.

2023-04-03 20:39 UTC, kushanam commented
reopening the PR for further integrating kernels.

2023-04-12 16:11 UTC, kushanam commented
This will be split into chunk PRs for maintainability.

2023-04-12 16:11 UTC, closed without merging