Replace many calls to eval() with self.evaluate()
tensorflow/tensorflow pull request #58727
Opened 2022-11-29 10:18 UTC by dianjiaogit

In order to get tests running in the eager mode we need to remove invalid function calls such as eval(). This change is simply a search and replacement for tests where this was safe. As a result, a few more tests now work in eager mode.

2022-11-29 10:22 UTC, dianjiaogit commented
Sorry that I forgot to sign the Contributor License Agreement. Now I have signed it.

2022-11-30 15:37 UTC, rohan100jain commented
With these changes, is it possible to remove any of the run_deprecated_v1 annotations on tests?

2022-12-01 07:02 UTC, dianjiaogit commented
> With these changes, is it possible to remove any of the run_deprecated_v1 annotations on tests?

I have checked the test files I modified. The run_deprecated_v1 annotations listed below have been removed. 

https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/checkpoint/checkpoint_management_test.py#L100
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/framework/smart_cond_test.py#L34
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/framework/smart_cond_test.py#L44
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/kernel_tests/math_ops/clip_ops_test.py#L301
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/kernel_tests/math_ops/clip_ops_test.py#L323
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/kernel_tests/math_ops/clip_ops_test.py#L345
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/kernel_tests/math_ops/clip_ops_test.py#L403
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/kernel_tests/math_ops/clip_ops_test.py#L423
https://github.com/tensorflow/tensorflow/blob/109ac17309c151dd3106c03ccce8b0287fe74548/tensorflow/python/kernel_tests/math_ops/clip_ops_test.py#L443

2022-12-12 22:18 UTC, rohan100jain approved these changes

2022-12-15 11:46 UTC, akuegel requested changes

2022-12-15 11:46 UTC, akuegel commented on tensorflow/python/client/session_test.py
> +      v_val = vself.evaluate(v)
this is a typo, it should be
```
v_val = self.evaluate(v)
```

2022-12-15 11:46 UTC, akuegel commented on tensorflow/python/checkpoint/checkpoint_management_test.py
> -  @test_util.run_deprecated_v1
It seems this is still needed. We get an assertion error below otherwise:

self.assertEqual(self.evaluate(v0), 2.0)
AssertionError: 1.0 != 2.0

2022-12-23 15:05 UTC, akuegel approved these changes

2023-01-04 10:45 UTC, merged