Remove completed TODO bugs.
tensorflow/tensorflow pull request #58735
Opened 2022-11-29 23:22 UTC by sachinprasadhs

Removed completed TODO bugs to avoid confusion, which is marked as fixed internally.

2022-12-21 23:20 UTC, sirakiin approved these changes

2022-12-28 18:57 UTC, mihaimaruseac requested changes

2022-12-28 18:57 UTC, mihaimaruseac commented on tensorflow/lite/BUILD
> +        "no_windows",
```suggestion
```

If the bug is completed, enable the test again

2022-12-28 18:57 UTC, mihaimaruseac commented on tensorflow/lite/BUILD
> +        "nomsan",
```suggestion
```

If bug is fix, remove tag

2022-12-28 18:57 UTC, mihaimaruseac commented on tensorflow/lite/core/interpreter.cc
>  static_assert(sizeof(TfLiteFloat16) == sizeof(uint16_t),
Please keep this one. The need to move to this is still there, the bug was closed due to bankruptcy.

2022-12-29 05:06 UTC, mihaimaruseac requested changes

2022-12-29 05:06 UTC, mihaimaruseac commented on tensorflow/lite/BUILD
>      tags = [
```suggestion
```

2022-12-29 05:06 UTC, mihaimaruseac commented on tensorflow/lite/BUILD
>      ],
```suggestion
```

2022-12-29 05:07 UTC, mihaimaruseac approved these changes

2022-12-30 05:36 UTC, merged