Fix null dereference from sharding_util
tensorflow/tensorflow pull request #58912
Opened 2022-12-16 10:55 UTC by apach301

`Edge::DebugString` with null `src` is called from https://github.com/tensorflow/tensorflow/blob/60e879cfee1ed3601e8ee4923dda4dcc4e88deee/tensorflow/compiler/tf2xla/sharding_util.cc#L120

In `Edge::DebugString` it dereferences `src` and `dst` without any check.

2022-12-20 14:21 UTC, mihaimaruseac approved these changes

2022-12-21 21:40 UTC, rohan100jain reviewed
Would it be possible to add a test that exercises this?

2022-12-28 09:09 UTC, gbaned commented
Hi @apach301 Can you please check @rohan100jain's comments and keep us posted ? Thank you!

2022-12-28 18:37 UTC, mihaimaruseac requested changes
Blocking review on getting a test

2022-12-29 10:00 UTC, apach301 commented
> Would it be possible to add a test that exercises this?

Sorry for late answer, I'll try to add the test as soon as possible

2023-01-18 15:10 UTC, mihaimaruseac requested changes
I still don't see a test.

2023-01-19 20:22 UTC, apach301 commented
Add test for Edge::DebugString to //tensorflow/core/graph:graph_test

2023-03-21 20:08 UTC, gbaned commented
Hi @rohan100jain Can you please review this PR ? Thank you!

2023-04-04 14:04 UTC, SweetVishnya approved these changes
This PR should definitely be merged cause I've already accidentally submitted a duplicate PR #60224

2023-04-04 14:07 UTC, apach301 commented
@mihaimaruseac @rohan100jain 
Fixed bug and add unittest for this, Can you please review this?

2023-04-04 17:14 UTC, mihaimaruseac approved these changes

2023-04-10 17:24 UTC, merged