Add example
tensorflow/tensorflow pull request #58998
Opened 2022-12-25 15:07 UTC by shogohida

Signed-off-by: Shogo Hida <shogo.hida@gmail.com>

Fixes #58261 

Work in progress

2023-01-21 01:57 UTC, shogohida commented
I'm not sure if the changes I made are correct but I made this PR ready for review so that others can review

2023-01-30 19:06 UTC, swachhandl commented on tensorflow/core/kernels/rnn/gru_ops.cc
> +        ctx, ctx->allocate_output("g", TensorShape({batch_size, cell_size}),
IIUC, you're creating a new tensor and allocating memory here. I don't think that's needed or would fix the issue. I would imagine you'd have to add checks to the existing Tensors here. 

Please take a look at this PR, which is fixing something similar: https://github.com/tensorflow/tensorflow/pull/59477

2023-01-30 23:16 UTC, mihaimaruseac requested changes
`g_tensor` is not used at all

2023-02-01 11:23 UTC, diego-alayon commented
Unsubscribe

2023-02-16 19:30 UTC, mihaimaruseac commented
This has been suprseeded by internal code changes and also #59703

2023-02-16 19:30 UTC, closed without merging