Make Aarch64 not a legacy platform
tensorflow/tensorflow pull request #59213
Opened 2023-01-10 09:38 UTC by annop-w

This allows for MKL convolution primitives to always be cached on Aarch64.

2023-01-10 18:45 UTC, penpornk requested changes
Thank you for the PR!

2023-01-10 22:08 UTC, annop-w commented on tensorflow/core/util/mkl_util.h
> +#endif
Done. Thank you.

2023-01-11 12:27 UTC, penpornk approved these changes

2023-01-11 12:40 UTC, annop-w commented on tensorflow/core/util/mkl_util.h
> +#endif
Done.

2023-01-11 14:45 UTC, penpornk approved these changes
Thank you again for the changes!

2023-01-17 09:54 UTC, penpornk approved these changes
Not sure why this hasn't been merged. Reapproving again.

2023-01-17 14:14 UTC, penpornk commented
@annop-w Could you please help a take a look at the [Arm CI failure](https://github.com/tensorflow/tensorflow/actions/runs/3938039126)? Here is the [log](https://github.com/tensorflow/tensorflow/actions/runs/3938039126/jobs/6736273388) (or click here for [raw log file](https://pipelines.actions.githubusercontent.com/serviceHosts/a4c1c801-a9a8-4666-a73a-996f5c2479f7/_apis/pipelines/1/runs/57761/signedlogcontent/2?urlExpires=2023-01-17T14%3A12%3A33.8719264Z&urlSigningMethod=HMACV1&urlSignature=RBH2%2BfILPlzMOAq6kFQxtZ4Xx7sMtFqfdYiXG2SkjUM%3D)).

2023-01-17 17:48 UTC, annop-w commented
@penpornk Thanks for pointing that out. I'm investigating.

2023-01-23 16:07 UTC, annop-w commented
@penpornk I have been trying to reproduce the failure locally, but without success so far. Could we try running the CI pipeline once more ?

2023-01-23 16:20 UTC, penpornk commented
@annop-w Sure! I've triggered another run. You can see the job [here](https://github.com/tensorflow/tensorflow/actions/runs/3988056012/jobs/6839402805).

2023-01-23 17:00 UTC, annop-w commented
The ARM CI pipeline failed even before running the tests https://github.com/tensorflow/tensorflow/actions/runs/3988056012/jobs/6839402805#step:5:16929

2023-01-23 19:30 UTC, penpornk commented
@annop-w That's weird. I just triggered another rerun.

2023-01-23 21:22 UTC, annop-w commented
@penpornk Looks like the pipeline is broken. All red for other PRs with the same error.

2023-01-24 09:24 UTC, penpornk commented
@annop-w Sorry about that. I'm checking with @elfringham on the pipeline.

2023-01-24 10:12 UTC, elfringham commented
Pipeline fix in https://github.com/tensorflow/tensorflow/pull/59430

2023-01-25 16:30 UTC, penpornk approved these changes
Thank you for rebasing! Let's rerun the tests.

2023-01-27 18:07 UTC, penpornk commented
@annop-w The ARM CI got [23 test failures](https://github.com/tensorflow/tensorflow/actions/runs/4007933935/jobs/6881448921). The job before it only had [7 tests failed](https://github.com/tensorflow/tensorflow/actions/runs/4007920238/jobs/6881416173) so I think the rest is specific to this PR.

2023-01-27 20:58 UTC, annop-w commented
@penpornk Yes, I am able to reproduce the failures now. There is probably a bug on the oneDNN side, which got revealed after the `MklConvBwdInputPrimitive` is cached. I am still investigating. Thanks for pointing out.

2023-02-01 19:36 UTC, penpornk approved these changes
Thank you for the fixes! I'll probably wait until after the branch cut to merge this.

2023-02-07 16:14 UTC, merged