Fix possible buffer underflow in hlo_parser
tensorflow/tensorflow pull request #59282
Opened 2023-01-17 14:15 UTC by apach301

Possible buffer underflow if `nest_level` becomes negative.

This PR is part of https://github.com/tensorflow/tensorflow/pull/57892

Bug was found by [Svace static analyzer](https://www.ispras.ru/en/technologies/svace/) (more [info](https://svace.pages.ispras.ru/svace-website/en/)).

2023-01-18 11:22 UTC, cheshire commented
Could you add a test which crashes it?

2023-01-18 11:23 UTC, cheshire requested changes
Could you add a test?

2023-01-20 14:54 UTC, apach301 commented
> Could you add a test?

Done.
Without this fix there is an exception raised on calling `dimensions_.at()` with negative index.
![Selection_085](https://user-images.githubusercontent.com/13482580/213728506-11c62a57-9510-4252-af74-663a30c30427.png)

2023-01-20 15:47 UTC, cheshire approved these changes
Thanks a lot!

2023-01-23 18:06 UTC, merged