Suryanarayana y convert image dtype complex dtype
tensorflow/tensorflow pull request #59313
Opened 2023-01-19 11:11 UTC by SuryanarayanaY

At present the API tf.image.convert_image_dtype supports data types (for image and dtype) of uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32, float64, bfloat16 only.However passing complex data types like complex64,complex128 doesn't create error but outputs random(incorrect) results.
Hence raising this PR so that this API validate inputs for any complex dtypes and raise the Attribute Error.Please also refer to the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/bae13f4fb3a35afaa6be958bb8b2f273/tf-image-convert_image_dtype-testcase-58699.ipynb).
Request for review and needful.
Thank you!

2023-02-15 17:01 UTC, cantonios requested changes

2023-02-22 17:54 UTC, SuryanarayanaY commented on tensorflow/python/ops/image_ops_impl.py
> +  if dtype.is_complex or image.dtype.is_complex:
In this case adding the below code to the original code shall validate the image dtype.
```
if not image.dtype.is_floating and not image.dtype.is_integer:
    raise AttributeError('Image dtype must be either floating point or integer')
```
(Or)
 
To validate both image dtype and output dtype we can use single block as like below by deleting lines 2491 & 2492 from original code.

```
if (not dtype.is_floating and not dtype.is_integer) or (not image_dtype.is_floating and not image_dtype.is_integer):
        raise AttributeError('data type must be either floating point or integer')
```

Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/1eed84e157e6b1a29753b654f23fb21b/tf-image-convert_image_dtype-testcase-58699-_r2.ipynb).

2023-02-22 18:58 UTC, cantonios commented on tensorflow/python/ops/image_ops_impl.py
> +  if dtype.is_complex or image.dtype.is_complex:
Correct

2023-03-15 15:30 UTC, cantonios approved these changes

2023-03-15 22:18 UTC, merged