[oneDNN][Bug-fix] Add check for min-max tensors in quantized matmul OpKernel.
tensorflow/tensorflow pull request #59437
Opened 2023-01-24 23:22 UTC by mdfaijul

This PR fixes NPE (null-pointer exception error) on tensors relevant to quantized matmul OpKernel. Particularly, when an element is accessed with an index, this PR first checks if such index is valid or not.

2023-01-24 23:25 UTC, mdfaijul commented
@penpornk This PR has a fix on `tf.raw_ops.QuantizedMatMulWithBiasAndDequantize`. Please help reviewing this. Thanks!

2023-01-25 19:25 UTC, penpornk requested changes
Thank you very much for the quick fix!

2023-01-25 19:25 UTC, penpornk commented on tensorflow/core/kernels/mkl/mkl_qmatmul_op.cc
> +
Shouldn't this check be before lines 359-362?

2023-01-25 19:44 UTC, penpornk approved these changes

2023-01-25 19:44 UTC, penpornk commented on tensorflow/core/kernels/mkl/mkl_qmatmul_op.cc
> +
Oops. Please ignore my comment. I misread and thought they were in the same function.

2023-01-25 19:46 UTC, penpornk commented
[MacOS CPU Python3](https://source.cloud.google.com/results/invocations/709f8779-1cf0-4c10-a8cd-fc06ffcddd52/targets) failures seem unrelated to this PR:
```
clang++: error: no such file or directory: 'tensorflow/compiler/mlir/lite/sparsity/sparsify_model.cc'
clang++: error: no input files
```

2023-01-26 05:50 UTC, merged