ReLU Epilogue Fusion for FP8 GEMMs in XLA
tensorflow/tensorflow pull request #59616
Opened 2023-02-08 20:04 UTC by philipphack

Enables the epilogue fusion of ReLU activations for FP8 GEMMs.

2023-02-08 20:05 UTC, philipphack commented
CC @reedwm.

2023-02-22 19:54 UTC, reedwm requested changes

2023-02-22 19:54 UTC, reedwm commented on tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
> +                  GemmOrCublasLtMatmulMaybeF8(&existing_gemm).WithOneUser(),
Can you add a test for FP8 matmul with alpha set?

2023-02-22 22:04 UTC, reedwm approved these changes

2023-02-23 19:37 UTC, closed without merging