Update tensorboard 2.12.0 dependency
tensorflow/tensorflow pull request #59615
Opened 2023-02-08 19:54 UTC by vinila21

Re : Updating Tensorboard's protobuf

Updating the TB 2.12.0 dependency from TF side.

2023-02-08 20:13 UTC, nfelt commented
This can't be merged until we actually have published a 2.12 release of TensorBoard. We're working on it right now and it should be ready later today, but please do not merge this until we let you know it's ready.

2023-02-09 16:24 UTC, mihaimaruseac requested changes

2023-02-09 16:24 UTC, mihaimaruseac commented on tensorflow/tools/pip_package/setup.py
>                          'tb-nightly ~= 2.12.0.a'),
Since this is a PR on master, it should change nightly.

But as @nfelt said, this needs to wait until TB release

2023-02-09 22:47 UTC, mihaimaruseac requested changes
This is not needed as there is an internal change for it.

2023-02-09 22:47 UTC, closed without merging