support disable jit_scope op's gradients compile when disable scope op compile
tensorflow/tensorflow pull request #59629
Opened 2023-02-09 08:34 UTC by YangWorker

Add compile_gradients param for xla.experimental.jit_scope to support disable compile op's gradients ops.
In some scenarios, if op is dynamic shaped, the gradients op of it is dynamic shaped too.

2023-03-21 20:51 UTC, gbaned commented
Hi @cheshire Can you please review this PR ? Thank you!

2023-03-22 11:40 UTC, cheshire commented
@jlebar Could you take a look ? I think you were doing something similar with using jit_scope to control what exactly autoclustering is compiling.

2023-03-22 15:28 UTC, cheshire requested changes
Is it possible to add tests?

2023-05-05 10:26 UTC, gbaned commented
Hi @YangWorker Can you please check @cheshire's comments and resolve conflicts ? Thank you!

2023-06-01 05:15 UTC, gbaned commented
Hi @YangWorker Any update on this PR? Please. Thank you!

2023-06-23 07:30 UTC, gbaned commented
Hi @YangWorker Any update on this PR? Please. Thank you!

2023-08-25 08:40 UTC, gbaned commented
Hi @YangWorker Any update on this PR? Please. Thank you!

2023-09-24 01:48 UTC, closed without merging