Fix MapPeek crash when key is not a scaler
tensorflow/tensorflow pull request #59656
Opened 2023-02-12 16:33 UTC by yongtang

This PR tries to address the issue raised in #58271 where MapPeek
will crash when key is not a scaler.

This PR fixes #58271.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2023-02-13 16:32 UTC, cantonios requested changes

2023-02-13 16:32 UTC, cantonios commented on tensorflow/python/kernel_tests/data_structures/map_stage_op_test.py
> +    with self.session():
I don't think we need this `with self.session()`.  Can you remove if it still passes?

2023-02-13 18:19 UTC, mihaimaruseac commented
Also, please squash all commits, we don't need 3 commits for a check and a test.

2023-02-13 18:19 UTC, mihaimaruseac approved these changes

2023-02-13 19:47 UTC, yongtang commented
Thanks @cantonios. The PR has been updated with `with self.session():` removed. Let me know if this works (I see most of the other tests seems to have this)

2023-02-13 19:55 UTC, yongtang commented
Thanks @mihaimaruseac  The PR has been updated with commits merged.  Please take a look.

2023-02-13 19:57 UTC, yongtang commented
@mihaimaruseac  (In github there is an option in settings which allows the "squash merge" that can do the squash merge automatically when merge. This allows adjustments of try/revert tests in different sections while also keep the final commit history linear/clean.

Understand tensorflow has an internal merge system, though maybe something similar to "squash merge" can be considered as well?

_Below is a screenshot of the config in some other repos:_

-------

<img width="814" alt="screenshot" src="https://user-images.githubusercontent.com/6932348/218561562-4d8f417e-ae25-4f17-8f8b-37379863c978.png">

2023-02-13 21:53 UTC, mihaimaruseac commented
That would be ideal, but unfortunately it requires significant changes in Copybara, so instead we're suggesting squashes on PRs if we can. This is useful for vuln fixes as it is easier to cherrypick a squashed commit than 3 commits on a fix.

2023-02-13 21:53 UTC, mihaimaruseac approved these changes

2023-02-16 17:32 UTC, cantonios requested changes

2023-02-16 17:32 UTC, cantonios commented on tensorflow/python/kernel_tests/data_structures/map_stage_op_test.py
> +      self.evaluate(t)
This should be `self.evaluate(v)`

2023-02-16 21:24 UTC, cantonios approved these changes

2023-02-17 17:49 UTC, merged