Add checking on the quantized limits for tosa.clamp
tensorflow/tensorflow pull request #59708
Opened 2023-02-16 00:18 UTC by Jerry-Ge

The original request: https://github.com/tensorflow/tensorflow/pull/58288#discussion_r1013360726

This is the 1st patch for review. I will cleanup everything else after the 1st round of review. 

Jerry

2023-02-16 00:18 UTC, Jerry-Ge commented
cc @eric-k256 @rsuderman

2023-02-23 18:54 UTC, rsuderman requested changes

2023-02-23 18:54 UTC, rsuderman commented on tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
> +  if (dtype.isSigned()) {
Change the structure to:

```
if (dtype.isUnsigned()) {
  <do things>
 return;
}

<do other things>
```

It feels like a minor difference however integers are signed, unsigned, or signless. Signless integers we default to signed behavior.  We also avoid including the else if there can be an early return which reduces the number of blocks.
```

2023-02-24 00:36 UTC, Jerry-Ge commented
There is actually no implementation of the `dtype.isUnsigned()` [Reference](https://mlir.llvm.org/doxygen/classmlir_1_1quant_1_1QuantizedType.html) . Simply using getStorageTypeMin/Max for much cleaner implementation.

Jerry

2023-02-24 23:24 UTC, merged