VLOG Warnings for FP8 Custom Calls
tensorflow/tensorflow pull request #59768
Opened 2023-02-22 01:40 UTC by philipphack

Creates VLOG warnings when a GEMM directly or indirectly operating on FP8 operands is not pattern matched and rewritten into an FP8 Custom Call.

2023-02-22 01:41 UTC, philipphack commented
CC @reedwm.

2023-02-22 16:32 UTC, pjannaty commented on tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
> +    if (Match(instr, m::CustomCall({kCublasLtMatmulCallTarget},
Perhaps wrap this whole block with a `VLOG_IS_ON(1)`?

2023-02-23 00:10 UTC, reedwm requested changes

2023-02-25 02:00 UTC, reedwm approved these changes

2023-02-27 06:51 UTC, merged