Update devel.requirements.txt
tensorflow/tensorflow pull request #59795
Opened 2023-02-24 07:59 UTC by synandi

Changed protobuf ~= 3.20.1 to protobuf >= 3.20.3  since https://github.com/tensorflow/tensorflow/blob/20e0beaeebc1bd96c8eca40bed0e7b0d065d8e0b/tensorflow/tools/pip_package/setup.py#L100 has protobuf >= 3.20.3 in it and both versions should match.  This fixes https://github.com/tensorflow/tensorflow/issues/59774

2023-02-24 19:05 UTC, angerson approved these changes

2023-02-25 15:36 UTC, Neilblaze approved these changes

2023-02-26 00:23 UTC, mihaimaruseac requested changes
CI deps should be pinned to ensure reproducible builds. It is ok to update, but not to add a `>=` bound

2023-02-27 16:46 UTC, mihaimaruseac approved these changes

2023-03-02 19:20 UTC, merged