Correct checks for Tensor::SubSlice() and Tensor::Slice() method accordingly to documentation and SubBuffer() checks (reopened #59266)
tensorflow/tensorflow pull request #59819
Opened 2023-02-27 08:55 UTC by avoskoboinyk-lohika

This is a reopened https://github.com/tensorflow/tensorflow/pull/59266 with comment fixes applied.

2023-02-27 20:10 UTC, cantonios approved these changes

2023-06-02 20:14 UTC, cantonios commented
There are too many failures with this change.  It looks like we do rely on the assumption that taking a subslice past the end returns an empty slice.  Maybe removing the check on `start` will reduce the number of failures?  Otherwise we need to fix all the affected tests.

2023-06-02 20:14 UTC, cantonios requested changes
Address test failures

2023-06-23 07:35 UTC, gbaned commented
Hi @avoskoboinyk-lohika Any update on this PR? Please. Thank you!

2023-07-23 01:59 UTC, closed without merging