Fix endianness issues in arithmetic_optimizer_test.cc tests
tensorflow/tensorflow pull request #59851
Opened 2023-03-01 15:41 UTC by jonathan-albrecht-ibm

Some tensorflow/core/grappler/optimizers/arithmetic_optimizer_test.cc tests check for expected tensor content values that are in little-endian format. This commit adds supporting functions so that big-endian platforms will convert to little-endian before checking.

2023-04-25 18:58 UTC, jonathan-albrecht-ibm commented
@ezhulenev, friendly ping :) Would you have some time to review this PR? Thank you!

2023-05-05 10:59 UTC, gbaned commented
Hi @ezhulenev Can you please review this PR ? Thank you!

2023-05-05 22:46 UTC, ezhulenev approved these changes

2023-05-08 20:09 UTC, jonathan-albrecht-ibm commented
TFTR @ezhulenev!

2023-06-27 19:21 UTC, jonathan-albrecht-ibm commented
@ezhulenev @gbaned this PR has been approved for a while now. Is there something I need to do for it to be merged?

2023-07-07 14:58 UTC, gbaned commented
> @ezhulenev @gbaned this PR has been approved for a while now. Is there something I need to do for it to be merged?

Hi @jonathan-albrecht-ibm Sorry for the delay, this PR processing internally, nothing pending from you end. Thank you!

2023-08-04 05:36 UTC, gbaned commented
Here are the internal errors, @jonathan-albrecht-ibm can you please verify ? Thank you!

/tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc:150:56: error: no member named 'data' in 'absl::Cord'
  150 |   char* buff = const_cast<char*>((tp->tensor_content().data()));
      |                                   ~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.

tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc:150:56: error: no member named 'data' in 'absl::Cord'
  150 |   char* buff = const_cast<char*>((tp->tensor_content().data()));
      |                                   ~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.

2023-08-04 15:24 UTC, jonathan-albrecht-ibm commented
@gbaned thanks for providing the details. Is there somewhere I can see the logs with the internal errors above?

Not completely sure what's going on but it looks like `absl::Cord` is being used instead of `std::string` for the protobuf `tensor_content` field in this build? `tensor_content` has the protobuf type `bytes` which should be `std::string` in the c++ generated classes so not sure how this is happening. 

@gbaned @ezhulenev Any pointers on how to configure my local build to reproduce this error?

2023-08-18 10:11 UTC, gbaned commented
Hi @ezhulenev Can you please take a look on the above comment from @jonathan-albrecht-ibm. Thank you!

2023-08-24 04:48 UTC, gbaned commented
Hi @ezhulenev Any update on this PR? Please. Thank you!

2023-08-24 15:58 UTC, ezhulenev approved these changes

2023-08-28 12:48 UTC, jonathan-albrecht-ibm commented
@ezhulenev, @gbaned Not sure if something else changed but the MacOS build passed this time. The `Py+CPP Test Suite - Ubuntu CPU, Python 3.9` build failed though. I looked at the logs that I can access and it looks like the errors were due to timeouts IIUC.

Could someone with more access confirm?

2023-11-24 19:58 UTC, jonathan-albrecht-ibm commented
@gbaned just wanted to check on the status of this issue since the ready to pull label was removed. I don't have access to the internal CI. Are there any problems?

2024-01-01 22:08 UTC, jonathan-albrecht-ibm commented
@gbaned just wanted to check on the status of this issue again since the ready to pull label was removed. I don't have access to the internal CI. Are there any problems?

2024-05-28 06:42 UTC, gbaned approved these changes

2024-07-29 20:40 UTC, jonathan-albrecht-ibm commented
@gbaned @keerthanakadiri is there something preventing this PR from being merged?

2024-07-31 06:22 UTC, keerthanakadiri commented
> @gbaned @keerthanakadiri is there something preventing this PR from being merged?

Hi @ezhulenev , Can you please assist on the above comment  from [jonathan-albrecht-ibm](https://github.com/jonathan-albrecht-ibm) 
Thank you !

2024-09-24 12:09 UTC, jonathan-albrecht-ibm commented
@ezhulenev @gbaned @keerthanakadiri is there something preventing this PR from being merged?

2025-01-02 14:44 UTC, jonathan-albrecht-ibm commented
@ezhulenev @gbaned @keerthanakadiri I have rebased this PR to fix a conflict caused by the automated change of 'Status' -> 'absl::Status' from upstream master. Nothing else needed to be changed in this PR to resolve the conflict.

This PR has been ready to pull for a very long time. Could someone please merge it or let me know if there is something I need to do?

2025-01-02 16:43 UTC, mihaimaruseac approved these changes

2025-01-02 20:38 UTC, mihaimaruseac requested changes

2025-01-02 20:38 UTC, mihaimaruseac commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  char* buff = const_cast<char*>((tp->tensor_content().data()));
```suggestion
  char* buff = const_cast<char*>(std::string((tp->tensor_content()).data()));
```

I think we need to wrap this into a `std::string` constructor here, see https://github.com/tensorflow/tensorflow/blob/b77b79bcee488454292188cce47661ab854fe401/tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc#L187

Without this, we have several compile failures internally as the `tensor_content` output is not always a type that supports `.data()`.

2025-01-02 20:40 UTC, mihaimaruseac commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  char* buff = const_cast<char*>((tp->tensor_content().data()));
(repeating suggestion so I could apply it)

```suggestion
  char* buff = const_cast<char*>(std::string((tp->tensor_content()).data()));
```

2025-01-02 22:20 UTC, jonathan-albrecht-ibm commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  char* buff = const_cast<char*>((tp->tensor_content().data()));
Thanks @mihaimaruseac . Let me build and retest here and then I'll push the change.

2025-01-03 22:14 UTC, jonathan-albrecht-ibm commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  char* buff = const_cast<char*>((tp->tensor_content().data()));
@mihaimaruseac , I had to set the byte swapped TensorProto content back into the TensorProto since the buffer was getting a copy of the content but otherwise no other changes to your suggested change. I have tested it on amd64 and s390x linux.

2025-01-04 17:04 UTC, mihaimaruseac approved these changes
Thank you!

2025-01-04 17:05 UTC, mihaimaruseac commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  char* buff = const_cast<char*>((tp->tensor_content().data()));
Thank you! I missed the need to set the content back into the proto, but it makes sense.

2025-01-08 21:16 UTC, mihaimaruseac approved these changes

2025-01-08 21:18 UTC, mihaimaruseac requested changes

2025-01-08 21:18 UTC, mihaimaruseac commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  char* buff = const_cast<char*>(std::string(tp->tensor_content()).data());
Can you actually save the string to a variable, please? We're getting this internal error:

```
tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc:165:34: error: object backing the pointer will be destroyed at the end of the full-expression [-Werror,-Wdangling-gsl]
```

Looks like a temporary lifetime issue

2025-01-09 15:52 UTC, jonathan-albrecht-ibm commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  char* buff = const_cast<char*>(std::string(tp->tensor_content()).data());
Done. It simplifies setting the content back into the proto too.

Thanks for your help with the internal errors @mihaimaruseac!

2025-01-09 17:15 UTC, mihaimaruseac approved these changes
Thank you!

2025-01-09 17:56 UTC, mihaimaruseac commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  std:string content_str = std::string(tp->tensor_content());
```suggestion
  std::string content_str = std::string(tp->tensor_content());
```

Oh, this is a typo

2025-01-09 17:57 UTC, mihaimaruseac commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  std:string content_str = std::string(tp->tensor_content());
But it breaks internally as `std:` becomes an unused label and we compile with `-Werror`

2025-01-09 18:04 UTC, jonathan-albrecht-ibm commented on tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
> +  std:string content_str = std::string(tp->tensor_content());
🤦 done

2025-01-09 18:05 UTC, mihaimaruseac approved these changes

2025-01-09 18:33 UTC, mihaimaruseac commented
Thank you! This seems to make progress now, so it should merge in ~1hr if nothing else is broken

2025-01-09 19:57 UTC, merged

2025-01-09 20:00 UTC, jonathan-albrecht-ibm commented
@mihaimaruseac thanks for all your help, I really appreciate it!