Update "Hello World" Example Doc and Fix Broken Links
tensorflow/tensorflow pull request #59969
Opened 2023-03-13 17:13 UTC by pjpratik

This commit updates the "Hello World" example documentation in the TensorFlow Lite for Microcontrollers repository to use the latest version of the `evaluate_test.cc`. 

Additionally, the broken links in the example documentation have been fixed to ensure that users can access all the necessary resources. 

These changes make it easier for users to get started with tflite on microcontrollers and ensure that the example document is up-to-date.

 Merging this closes the issue #59959

2023-03-21 13:24 UTC, gbaned commented
Hi @sirakiin Can you please review this PR ? Thank you!

2023-03-30 18:50 UTC, gbaned commented
Hi @pjpratik Can you please resolve conflicts? Thank you!

2023-03-31 06:02 UTC, pjpratik commented
Hi @gbaned 

I have updated the conflicts.

Thanks.

2023-05-05 11:06 UTC, gbaned commented
Hi @sirakiin Can you please review this PR ? Thank you!

2023-06-15 08:41 UTC, gbaned commented
Hi @pjpratik Can you please resolve conflicts? Thank you!

2023-06-15 11:42 UTC, pjpratik commented
Hi @gbaned 

I have resolved the conflicts.

Thank you.

2023-07-17 06:28 UTC, gbaned commented
Hi @sirakiin Can you please review this PR ? Thank you!

2023-07-31 06:14 UTC, gbaned commented
Hi @sirakiin Can you please review this PR ? Thank you!

2023-09-01 06:00 UTC, gbaned commented
Hi @sirakiin Can you please review this PR ? Thank you!

2023-09-01 11:32 UTC, mihaimaruseac requested changes
I don't think this PR warrants merging, it's not correct.

2023-09-01 11:32 UTC, mihaimaruseac commented on tensorflow/lite/g3doc/microcontrollers/get_started_low_level.md
> +
```suggestion
```

Please don't add empty lines that are not needed

2023-09-01 11:32 UTC, mihaimaruseac commented on tensorflow/lite/g3doc/microcontrollers/get_started_low_level.md
> +  float y_true = sin(x);
This seems to be doing something totally different than the original

2023-10-22 19:40 UTC, mihaimaruseac commented
https://github.com/tensorflow/tensorflow/pull/59969/files#r1312915151 is still not resolved. If there won't be an update to that I'd suggest closing the PR instead

2023-10-26 15:33 UTC, pjpratik commented
Hi @mihaimaruseac @gbaned 

The Hello World example has been refactored with the commit https://github.com/tensorflow/tensorflow/commit/f263e19e227da0d325f15477f57a359291fc387c and broken links are fixed.

I think this PR can be closed.

Thanks.

2023-10-27 05:10 UTC, closed without merging