Initialise DNNClassifier with normalizer_fn
tensorflow/tensorflow pull request #6017
Opened 2016-12-01 16:57 UTC by Montmorency

For Contrib added option to pass normalizer_fn to DNNClassifier. This should automatically attach the normaliser to every layer in the deep neural network. Something like:
     m = tf.contrib.learn.DNNClassifier(model_dir         = model_dir,
                                                                feature_columns   = deep_columns,
                                                                dropout           = DROPOUT,
                                                                normalizer_fn     = tf.contrib.layers.batch_norm,
                                                                normalizer_params = normalizer_params...)
  
Modified dnn.py

2016-12-09 01:01 UTC, Montmorency commented
Hi All,
Just thought this might be a useful feature to have in the contrib/learn functionality. It looks like the batch_norm method in /layers can be attached straight forwardly to the layers in the dnn, along with all the batch_parameters that need to be passed along. The only pitfalls I can see are there need to be some clear warning about argument scoping, and making sure the is_training variable is set properly depending on whether the model is being fit or evaluated.

2016-12-13 17:24 UTC, ilblackdragon requested changes
Thanks for the contribution!

Can you also please add a few tests showing usage and testing parameters are passed correctly.

Thanks!

2016-12-13 17:24 UTC, ilblackdragon commented on tensorflow/contrib/learn/python/learn/estimators/dnn.py
> +#Importing batchnorm to be added to the DNN.
please don't add comments before imports. also we try to keep them sorted.

2016-12-13 17:24 UTC, ilblackdragon commented on tensorflow/contrib/learn/python/learn/estimators/dnn.py
> +#HL think we can add here the batch_norm.
I don't think this comment is needed (and in general one-line comments should have the same indentation as other code). 
Also please format the arguments the same way as others (e.g. no extra spaces).

2016-12-13 17:24 UTC, ilblackdragon commented on tensorflow/contrib/learn/python/learn/estimators/dnn.py
> +  num_ps_replicas   = params.get("num_ps_replicas", 0)
please no extra spaces.

2017-01-11 23:37 UTC, drpngx commented
@Montmorency sorry this fell through the cracks, could you pull rebase and push again?

2017-01-15 19:25 UTC, drpngx commented
Closing for now. Feel free to re-open once you have made changes to the code.

2017-01-15 19:25 UTC, closed without merging