Fix add.cc
tensorflow/tensorflow pull request #60230
Opened 2023-04-04 15:47 UTC by PaDarochek

The bug was found by Svace static analyzer:

1. params may be null because it is checked for null on https://github.com/tensorflow/tensorflow/blob/r2.12/tensorflow/lite/kernels/add.cc#L143
2. later it is zero-dereferenced by params->activation

cc @mihaimaruseac

2023-04-04 15:55 UTC, SweetVishnya approved these changes
LGTM

2023-04-04 17:11 UTC, mihaimaruseac commented
Please don't use "add file"/"update file"/"fix file"/etc. commit messages. These are hard to reason about when looking at the history of the file/repository. Instead, please write explanatory git commit messages.

The commit message is also the title of the PR if the PR has only one commit. It is thus twice important to have commit messages that are relevant, as PRs would be easier to understand and easier to analyze in search results.

For how to write good quality git commit messages, please consult https://cbea.ms/git-commit/

2023-04-04 17:13 UTC, mihaimaruseac requested changes
Not sure is that is a valid default activation to use. Maybe params should be checked to not be null when it is first used?

2023-04-05 14:08 UTC, PaDarochek commented
cc @mihaimaruseac 
Fixed `params` checking, renamed commit and PR

2023-04-05 16:06 UTC, mihaimaruseac approved these changes

2023-04-25 17:05 UTC, SweetVishnya commented
@gbaned, can we proceed with merging this?

2023-04-25 17:07 UTC, mihaimaruseac commented
Still needs to go via internal CI and review. See https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#typical-pull-request-workflow--, especially the diagram at the bottom

2023-05-04 19:23 UTC, merged