Update padding='SAME' in tf.image.ssim API
tensorflow/tensorflow pull request #60251
Opened 2023-04-06 06:59 UTC by SuryanarayanaY

Currently the API `tf.image.ssim` is using `padding='VALID'` internally. But with this padding the shape of the output is not matching with what documentation states. With `return_index_map=True` the output shape should be `broadcast(img1.shape[:-1], img2.shape[:-1])`. 

But with` padding='VALID'`, for input of shape `(16, 2106, 80, 1)` the current output shape is `(16, 2096, 70)` which is not matching with the expected output which should be `(16, 2106, 80)`. With `padding='SAME'` the output is matching to the desired output. 

Please refer to the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/d75ef4fcbd69b5211975fd4d29490084/59067_r1.ipynb) showcasing all the mentioned details.

2023-05-05 11:30 UTC, gbaned commented
Hi @cantonios Can you please review this PR ? Thank you!

2023-05-05 15:29 UTC, cantonios approved these changes

2023-05-09 17:07 UTC, cantonios requested changes
Many of the SSIM tests are now failing and need to be updated.

2023-06-01 07:10 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @cantonios's [comments](https://github.com/tensorflow/tensorflow/pull/60251#pullrequestreview-1419096529) ? Thank you!

2023-06-08 07:09 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2023-06-08 08:50 UTC, SuryanarayanaY commented
I need some information on which tests are failing.Shall we need to update the all the failed test cases ?  A test demo shall be appreciated.
 Are those tests listed here at i[mage_ops_test.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_test.py) ?

2023-06-21 03:49 UTC, gbaned commented
Hi @cantonios Can you please assist on above [comments](https://github.com/tensorflow/tensorflow/pull/60251#issuecomment-1582164124) from @SuryanarayanaY. Thank you!

2023-06-21 17:21 UTC, cantonios commented
`//tensorflow/python:image_ops_test_cpu` fails, for example.  Pretty much every existing test that actually uses ssim.

2023-06-28 09:00 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2023-07-12 05:51 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2023-07-14 05:48 UTC, SuryanarayanaY commented
Need some time to work on this.Thanks!

2023-08-19 01:45 UTC, closed without merging