Update boringssl to allow compilation in MacOS XCode 14.3
tensorflow/tensorflow pull request #60259
Opened 2023-04-06 15:35 UTC by feranick

Current version of boringssl pulled for TF 2.12.x does not compile with TF using XCode 14.3 due to an unused variable and an aggressive compiler flag (-Werror,-Wunused-but-set-variable) This patch adds links to an updated version of boringssl (used for TF Master), that fixes the issue. This fixes TF issue #60191

2023-05-12 13:54 UTC, mihaimaruseac requested changes
Please land this on master branch and then it can be cherrypicked to the release branches when doing a patch release

2023-05-31 14:47 UTC, closed without merging

2023-07-08 09:24 UTC, feranick commented
This has not been merged in the 2.12.1 release. Not sure why, but it should.

2023-07-08 14:37 UTC, mihaimaruseac commented
It did not land on master and was not cherrypicked. Too late now for 2.12.x series since @learning-to-play decided to only patch the last release, so now only 2.13 will get patches.

2023-07-12 15:55 UTC, feranick commented
I have a solution to my case. I found it, reported here, created a pull request, that was reviewed and accepted. The problem remains for whoever is trying to compile 2.12.x on MacOS. Patching guidelines are just that a guideline for a specific patch. but without that patch being included into any release (development or not), it becomes pointless. 

So this (resolved) bug report is the only place where one can find a solution, and manually apply the patch. I would expect more, at the very least list it in the "known issues" so there is some guidance. Again, I am fine as I found a solution myself, but frankly going to the trouble to solve it through the official channels only to find that it's considered irrelevant, doesn't really inspire any future effort on my part to contribute patches. 

Thank you for your help.