slim.learning.train and slim.evaluation.evaluation to handle OutOfRange gracefully
tensorflow/tensorflow pull request #6028
Opened 2016-12-01 21:09 UTC by alsrgv

While doing this fix, I noticed that some of the metric operations don't handle OutOfRange gracefully also.  

For example, streaming mean computation would update total value and count concurrently, possibly updating count before failing to update total value due to OutOfRange. 

I have added fixes for mean metrics, but I am not sure what other places might be handling OutOfRange incorrectly.

2016-12-14 18:58 UTC, sguada commented
Please update and resolve the conflicts. 

I think the functionality is welcome.

2016-12-20 03:55 UTC, alsrgv commented
@sguada thanks for feedback.  PR is updated.

2017-01-11 23:37 UTC, drpngx commented
@alsgrv sorry this fell through the cracks. Could you resolve changes and push again?

2017-01-12 00:56 UTC, alsrgv commented
@drpngx merged.

2017-01-15 19:26 UTC, drpngx commented
Looks like there's another conflict, could you push again?

2017-01-21 04:27 UTC, alsrgv commented
@drpngx, sure - resolved.

2017-01-23 18:36 UTC, drpngx requested changes
Some additional questions.

2017-01-23 18:36 UTC, drpngx commented on tensorflow/contrib/slim/python/slim/evaluation_test.py
> +    # Create Checkpoint and log directories
Punctuation please. Use "checkpoint" for consistency (not "Checkpoint").

2017-01-23 18:36 UTC, drpngx commented on tensorflow/contrib/slim/python/slim/evaluation_test.py
> +    # Save initialized variables to checkpoint directory
Punctuation.

2017-01-23 18:36 UTC, drpngx commented on tensorflow/contrib/slim/python/slim/learning.py
> +            logging.info('Caught OutOfRangeError. Stopping Training.')
It's probably a logging.error, although I'm not sure why you would want to catch that error and recover from it.

2017-01-23 18:36 UTC, drpngx commented on tensorflow/python/ops/metrics_impl.py
> +      update_total_op = state_ops.assign_add(total, math_ops.reduce_sum(values))
So technically, this doesn't ened to be inside the `control_dependencies`, right?

2017-01-23 18:36 UTC, drpngx commented on tensorflow/python/ops/metrics_impl.py
> +      update_count_op = state_ops.assign_add(count, num_values)
So this is for the else branch, above right? I think it's probably better placed there, because that's the one that introduces the race condition?

2017-01-23 18:36 UTC, drpngx commented on tensorflow/python/ops/metrics_impl.py
> +    with ops.control_dependencies([values]):
Same as above.

2017-01-23 18:50 UTC, alsrgv commented on tensorflow/contrib/slim/python/slim/evaluation_test.py
> +    # Save initialized variables to checkpoint directory
Fixed

2017-01-23 18:50 UTC, alsrgv commented on tensorflow/contrib/slim/python/slim/evaluation_test.py
> +    # Create Checkpoint and log directories
Fixed

2017-01-23 18:52 UTC, alsrgv commented on tensorflow/contrib/slim/python/slim/learning.py
> +            logging.info('Caught OutOfRangeError. Stopping Training.')
OutOfRangeError is thrown when epoch limit per tf.train.limit_epochs is reached.  In my opinion it should be condition to normally finish training.

2017-01-23 19:00 UTC, drpngx commented on tensorflow/contrib/slim/python/slim/learning.py
> +            logging.info('Caught OutOfRangeError. Stopping Training.')
Ack. Sigh. Thanks for the clarification. Perhaps a comment might help.

2017-01-23 19:11 UTC, alsrgv commented on tensorflow/contrib/slim/python/slim/learning.py
> +            logging.info('Caught OutOfRangeError. Stopping Training.')
Good point, added comment.

2017-01-23 19:11 UTC, alsrgv commented on tensorflow/python/ops/metrics_impl.py
> +      update_count_op = state_ops.assign_add(count, num_values)
Is this new change along the lines of what you're thinking?

2017-01-23 19:31 UTC, drpngx approved these changes

2017-01-23 19:32 UTC, drpngx commented
Jenkins, test this please.

2017-01-23 21:20 UTC, alsrgv commented
Looks like evaluation test failed, let me see what's going on.

2017-01-23 23:48 UTC, alsrgv commented
Jenkins, test this please.

2017-01-23 23:51 UTC, alsrgv commented
@drpngx, I had to put back this guard for both branches:

```
with ops.control_dependencies([values]):
  update_count_op = state_ops.assign_add(count, num_values)
```

This is because this operation doesn't seem to force evaluation of values:

```
math_ops.to_float(array_ops.size(values))
```

Thus, count get incremented while sum is unchanged due to OutOfRangeError.

2017-01-23 23:57 UTC, drpngx commented
Oh, got it. That's a bit of a gotcha.

Jenkins, test this please.

2017-01-24 01:54 UTC, alsrgv commented
Looks like it failed due to estimator_test timeout.  I checked another run, and it's pretty slow in general:
```
//tensorflow/contrib/learn:estimator_test                                PASSED in 243.6s
```

On my machine is takes ~70 seconds.  Could this be transient failure?

2017-01-24 01:57 UTC, drpngx commented
Yeah, it seems to happen in other builds.

2017-01-24 01:58 UTC, merged