[Pluggable Device] Add DEFAULT_DEVICE registrations for some ops.
tensorflow/tensorflow pull request #60310
Opened 2023-04-13 07:32 UTC by kulinseth

Adding some more registrations for commonly used ops to DEFAULT_DEVICE using CPU implementation.  
cc @penpornk

2023-04-26 12:45 UTC, penpornk requested changes
Ask discussed offline, all registrations in this PR had caused internal test failures and were reverted before, and the issues haven't been fixed yet. Please guard all device default registrations in this PR with macos ifdefs for now.

2023-04-27 15:02 UTC, kulinseth commented
> Ask discussed offline, all registrations in this PR had caused internal test failures and were reverted before, and the issues haven't been fixed yet. Please guard all device default registrations in this PR with macos ifdefs for now.

Thanks @penpornk , added them to be specific to macos.

2023-04-27 16:11 UTC, cantonios approved these changes

2023-04-27 16:34 UTC, penpornk requested changes

2023-04-27 19:35 UTC, merged

2023-04-27 19:38 UTC, penpornk commented
For the record: I had made the requested changes internally before merging the PR.

2023-04-27 20:48 UTC, kulinseth commented
> For the record: I had made the requested changes internally before merging the PR.

Thanks Penporn. Much appreciated.

2023-04-27 20:51 UTC, kulinseth commented on tensorflow/core/kernels/pack_op.cc
> +#if defined(PLUGGABLE_DEVICE_SUPPORTED_MACOS)
Yes, i was thinking of moving it to `op_kernel.h`. But I wasn't sure as there were other Macros replicated across .cc file.