[oneDNN v3.1] Enabled INT8 Conv op/fusions with oneDNN v3.1
tensorflow/tensorflow pull request #60376
Opened 2023-04-19 18:39 UTC by mahmoud-abuzaina

- This PR adds support for oneDNN v3.1 in QuantizedConvolution op/fusions.

- Main changes in oneDNN v3.0 for quantization API are 1) Scaling API; now scale needs to be set for each tensor. 2) Bias needs to be passed as float32.

- This PR is not changing common (non-oneDNN) TF code.

2023-05-05 11:48 UTC, gbaned commented
Hi @penpornk Can you please review this PR ? Thank you!

2023-07-12 06:04 UTC, gbaned commented
Hi @penpornk Can you please review this PR ? Thank you!

2023-07-12 17:01 UTC, penpornk requested changes
Thank you for the PR and sorry for the delay! I have minor comments.

2023-07-13 00:56 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_ops.cc
> +            {DNNL_ARG_ATTR_SCALES | DNNL_ARG_DST, *context_.dst_scale_mem});
Fixed.

2023-07-13 00:56 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_ops.cc
> +            {DNNL_ARG_ATTR_SCALES | DNNL_ARG_DST, *context_.dst_scale_mem});
Fixed.

2023-07-13 00:56 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_ops.cc
> +    // Re-scale bias if either of following 2 conditions are met:
Added.

2023-07-13 00:56 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_ops.cc
> +
Done.

2023-07-13 00:56 UTC, mahmoud-abuzaina commented on tensorflow/core/kernels/mkl/mkl_conv_ops.cc
> +                              conv_fwd_pd->bias_desc(), &scaled_bias_buf_);
Done.

2023-07-13 00:57 UTC, mahmoud-abuzaina commented
Thank you for reviewing the PR. I have addressed your comments.

2023-07-13 09:24 UTC, penpornk approved these changes
Thank you!

2023-07-14 08:59 UTC, merged