Standardize error messages from invalid shapes for Mkl MatMul and Bat…
tensorflow/tensorflow pull request #60388
Opened 2023-04-20 14:09 UTC by fadara01

This PR:
- fixes the failing test on Arm CI caused by #60355
- standardizes the use of In[0], In[1] instead of lhs, rhs in error messages

2023-04-20 19:18 UTC, penpornk requested changes
Thank you for the PR! Should the fix be guarded with `DNNL_AARCH64_USE_ACL`? Otherwise the x86 TF-oneDNN tests may break.

2023-04-21 15:48 UTC, nSircombe commented
Hi @penpornk,
For the test failure that https://github.com/tensorflow/tensorflow/pull/60355 introduced, the expected error return that's being tested is unchanged, and the error returned on x86, from `mkl_matmul_op.cc`, is unchanged. So the x86 test should be OK.
The changes this makes to the error reported by `mkl_batch_matmul_op.cc` (making it consistent with the same error from `mkl_matmul_op.cc`) don't appear to feature in any other tests. So I don't think there are any tests on x86 expecting the old error message from `mkl_batch_matmul_op.cc`.
So I think there's no need to guard the change.

2023-04-21 20:18 UTC, penpornk approved these changes
@nSircombe Thank you for the clarification! I was worried that there would be a test that explicitly use batchmatmul and would expect the old message, or that the message would conflict with vanilla BatchMatMul op. Did some quick checks and it seems there are no mkl_*_test that looks for the old message. And vanilla op already uses this new messaging. 

[Arm CI](https://github.com/tensorflow/tensorflow/actions/runs/4758081864) also passed now.

2023-04-21 20:48 UTC, merged

2023-04-21 21:07 UTC, nSircombe commented
That's great, thanks @penpornk.