Add dtype checks to Scatter ops to report error instead of core dump
tensorflow/tensorflow pull request #60452
Opened 2023-04-30 13:52 UTC by evanrang

Add dtype checks to Scatter ops(Assign*VariableOp, ResourceScatter*) to report error instead of core dump.
fix issues:
#60147 
#60121

2023-07-13 22:04 UTC, JW1992 commented on tensorflow/core/kernels/resource_variable_ops.cc
Thanks for the changes! Can you please also add a test for this?

2023-07-13 22:05 UTC, JW1992 reviewed
Thanks for the changes! Can you please also add a test for this?

2023-09-01 06:14 UTC, gbaned commented
Hi @evanrang Any update on this PR? Please. Thank you!

2023-09-12 15:51 UTC, cantonios requested changes
Can you add tests for these?

2023-09-27 08:19 UTC, gbaned commented
Hi @evanrang Any update on this PR? Please. Thank you!

2023-11-03 04:32 UTC, gbaned commented
Hi @evanrang I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you!

2023-11-03 04:32 UTC, closed without merging