fix CondContext.back_prop
tensorflow/tensorflow pull request #60477
Opened 2023-05-02 21:25 UTC by albertz

2023-05-02 21:37 UTC, cantonios requested changes
Please write a PR description.

2023-05-05 23:34 UTC, tomytsai1 commented
> Please write a PR description.

+1  
@albertz  the fix looks good to me. Just needs a clear description.

2023-05-05 23:39 UTC, albertz commented
I don't really know what kind of description you want here. I extended it.

2023-05-11 23:14 UTC, tomytsai1 approved these changes

2023-05-16 19:31 UTC, merged