[oneDNN v3.x] Update fused instance norm kernel to support oneDNN v3.x lib…
tensorflow/tensorflow pull request #60611
Opened 2023-05-17 00:02 UTC by yimeisun123

…rary

2023-05-30 17:49 UTC, yimeisun123 commented
I checked the logs, the failed test case is  
MLIR tests :: replace_cast_hacks_with_tf_xla_ops_large_constants.mlir
the changes in this PR doesn't touch code related to the above test case.

2023-07-13 14:15 UTC, penpornk requested changes
Thank you for the PR and sorry for the delay!

2023-07-14 06:27 UTC, yimeisun123 commented on tensorflow/core/kernels/mkl/mkl_fused_instance_norm_op.cc
> +  // wherase the 3.x version requires separate buffers for scale and shift
Updated, thank you!

2023-07-14 09:22 UTC, penpornk approved these changes
Thank you again for the PR!

2023-07-16 18:43 UTC, merged