Limit typing_extensions to less than 4.6.0 until it works
tensorflow/tensorflow pull request #60688
Opened 2023-05-24 09:43 UTC by elfringham

There is a unit test failure when run as a pip test with typing_extensions >= 4.6.0 so limit the installed version to below that until the issue is resolved.

See #60687

2023-05-25 14:14 UTC, elfringham commented
The ARM_CI tests are all failing due to this issue at the moment so it would be good if it could be addressed soon.
The failing checks, PyLint and Code Check, are pre-existing in the file so are not related to this PR.

2023-05-25 18:26 UTC, angerson approved these changes
Thanks!

2023-05-26 10:00 UTC, penpornk requested changes
Could you please fix the [Code Check - Changed Files](https://source.cloud.google.com/results/invocations/e6bc15a3-b742-4978-8c84-7ffdf8942850/targets/tensorflow%2Frel%2Fdocker%2Fgithub_presubmit%2Fcode_check_changed_files/log) Pylint error?
```
# Python formatting is recommended. Here are the pylint errors:
# =============================
# tensorflow/tools/pip_package/setup.py:96:0: C0301: Line too long (87/80) (line-too-long)
```

[PY+CPP Ubuntu GPU failure](https://source.cloud.google.com/results/invocations/b3499b2c-92b9-496c-8d49-aaee66979b79/log) and [MacOS CPU Python 3.9 failure](https://source.cloud.google.com/results/invocations/eaf463d7-07aa-42e2-bfba-9caa8ee18831/targets/tensorflow%2Frel%2Fmacos%2Fgithub_presubmit%2Fcpu_py39/log) seem unrelated.

2023-05-26 10:49 UTC, penpornk approved these changes
Since the Pylint error line is not the line changed in this PR, I think we can let it go for now, since this PR would be a cherrypick candidate. I'll add a comment to make pylint ignore that line separately after this.

2023-05-26 20:05 UTC, merged