Update tfl.mean legalization to match the new reference kernel behaviour
tensorflow/tensorflow pull request #60700
Opened 2023-05-24 23:08 UTC by psunn

This PR updates the quantized REDUCE_MEAN kernel to only use integers. This matches the TFLite reference model in a bit-exact way.
(The merged PR:https://github.com/tensorflow/tensorflow/pull/52014 updates the quantized REDUCE_MEAN kernel to only use integers)

2023-05-25 09:23 UTC, psunn commented
@Tessil FYI

2023-07-04 15:59 UTC, psunn commented
Hi @jpienaar and @rsuderman, please could you help to review when you have time.
Thank you!

2023-07-20 09:27 UTC, gbaned commented
Hi @jpienaar / @rsuderman Can you please review this PR ? Thank you!

2023-07-31 16:39 UTC, rsuderman requested changes
Could you add a test for these changes. Other than that the PR looks good.

2023-07-31 17:14 UTC, psunn commented
Force-pushed the PR feature branch to GitHub after resolving merge conflicts caused by rebasing.

2023-07-31 21:22 UTC, psunn commented on tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
> +                       output_zp, IsTFLDoubleRoundingMode(), true);
I have add comments on constant values.

2023-07-31 21:23 UTC, psunn commented
> Could you add a test for these changes. Other than that the PR looks good.

I have add new mlir test for quantized reduce_mean.

2023-08-03 03:54 UTC, merged