Update list_physical_devices and list_logical_devices Argument notes
tensorflow/tensorflow pull request #60824
Opened 2023-06-09 07:07 UTC by SuryanarayanaY

At present both the APIs `tf.config.list_physical_devices` and `tf.config.list_logical_devices` has an optional argument named `device_type` which takes a `string` as an argument. But When we pass a numeric value or strings other than expected('CPU' or 'GPU') both returns an empty list instead of raising the error.The behaviour is ok but this is not documented well.Hence I proposed a note for same.

Also the default value of the argument `device_type` is `None` but with default value both the APIs returns available physical/logical devices. This is not `intuitive` as for value `None` the APIs returning the respective devices. This may create some confusion among users. Hence I am adding the note of same to the documentation explicitly to avoid any confusion.

The issue discussed in #57153 .

2023-06-19 07:36 UTC, gbaned commented
Hi @kenfranko Can you please review this PR ? Thank you!

2023-06-20 10:43 UTC, drefcot17th approved these changes

2023-06-22 22:56 UTC, kenfranko requested changes

2023-06-22 22:56 UTC, kenfranko commented on tensorflow/python/framework/config.py
> +    'CPU' or 'GPU' it returns an empty list instead of raising error.
What about TPU? Better to say any supported device type such as 'CPU' rather than say only 'CPU' or 'GPU'.

2023-06-22 22:56 UTC, kenfranko commented on tensorflow/python/framework/config.py
> +    'CPU' or 'GPU' it returns an empty list instead of raising error.
Same change needed here.

2023-06-22 22:59 UTC, drefcot17th commented on tensorflow/python/framework/config.py
> +    'CPU' or 'GPU' it returns an empty list instead of raising error.
H

2023-07-20 06:49 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @kenfranko's [comments](https://github.com/tensorflow/tensorflow/pull/60824#discussion_r1239106026) and keep us posted? Thank you!

2023-08-03 23:36 UTC, kenfranko approved these changes

2023-08-04 00:26 UTC, merged