[ROCm] Support of hipblaslt
tensorflow/tensorflow pull request #60894
Opened 2023-06-16 07:03 UTC by ekuznetsov139

This PR:

* Enables detection of hipblaslt. Hooks it up in place of cublaslt when available. 

* Enables the _FusedMatMul op for ROCm and routes it to hipblaslt. 

* Fixes certain #includes due to their deprecation in ROCm 5.6.

2023-06-22 16:51 UTC, i-chaochen commented
@akuegel would you review our hipblas_lt PR, please? Thanks in advance!

2023-06-23 13:10 UTC, akuegel requested changes

2023-06-23 13:10 UTC, akuegel commented on tensorflow/compiler/xla/stream_executor/rocm/rocm_dnn.cc
> +void launchInplaceBiasActivation(hipStream_t stream, void* c_data, const void* bias_data, int activation_mode, uint64_t m, uint64_t n, int64_t ldc, float param);
There seem to be quite a lot of long lines in this file. Can you please reformat to lines of length <= 80?

2023-06-23 13:10 UTC, akuegel commented on tensorflow/compiler/xla/stream_executor/rocm/rocm_helpers.cu.cc
There seem to be quite a lot of long lines in this file. Can you please reformat to lines of length <= 80?

2023-06-29 11:17 UTC, akuegel commented
@ekuznetsov139 Not sure whether you saw my review comments? I got asked by @i-chaochen about this PR, but I think this now needs the changes from your side until I can approve it.

2023-06-29 12:07 UTC, i-chaochen commented
> @ekuznetsov139 Not sure whether you saw my review comments? I got asked by @i-chaochen about this PR, but I think this now needs the changes from your side until I can approve it.

Hi @akuegel  Thanks for the feedback. I am going to split this big PR to smaller ones and I will do the changes based on your feedback as well.

We're going to push it to XLA first. Thanks in advance!

2023-09-01 06:42 UTC, gbaned commented
Hi @ekuznetsov139 Can you please rebase your branch and resolve conflicts? Thank you!

2023-09-30 01:46 UTC, closed without merging