Updating tf.experimental.numpy.vander for N=0
tensorflow/tensorflow pull request #61079
Opened 2023-06-26 10:27 UTC by SuryanarayanaY

At present the API `tf.experimental.numpy.vande`r behaves differently compared to its Numpy variant `numpy.vander` when the argument value of `N=0` .

I think the behaviour of Numpy variant is correct.Current TF implementation broadcasts N to `N=shape(x)[0]` when either N=0 or N=None which is not correct. When N=0 there should not be any broadcasting which is equivalent to `numpy.vander` behaviour.Hence proposing the changes in code to get numpy behaviour.

Attached the gist for demo in same with and without the code changes and with the proposed change in code numpy behaviour can be achievable.

Fixes #60827

2023-06-26 16:03 UTC, cantonios requested changes
Can you add a test to verify the new behavior?

2023-06-26 16:03 UTC, cantonios commented on tensorflow/python/ops/numpy_ops/np_array_ops.py
> +  if N != 0:
For better clarity you should probably just use the simple if statement:
```
if N is None:
  N = x_shape[0]
```

2023-06-30 05:02 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @cantonios's [comments](https://github.com/tensorflow/tensorflow/pull/61079#pullrequestreview-1498899933) ? Thank you!

2023-07-04 06:23 UTC, SuryanarayanaY commented
Changes done as requested. Thanks!

2023-07-05 15:26 UTC, cantonios requested changes
Still awaiting a test for the new behavior

2023-07-24 06:41 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2023-08-09 18:11 UTC, cantonios approved these changes

2023-08-09 19:09 UTC, merged