[MHLO] let unfuse-batch-norm-inference produce bcast_mul+bcast_add
tensorflow/tensorflow pull request #61120
Opened 2023-06-29 08:11 UTC by qingyunqu

The code copied from `tensorflow/compiler/mlir/lite/stablehlo/transforms/unfuse_batch_norm_pass.cc`

2023-06-30 05:54 UTC, akuegel commented
@burmako It seems we have a duplicate UnfuseBatchNorm pass. Do you think that one of them can be removed? And which one is better to keep?

2023-08-23 09:45 UTC, gbaned commented
Hi @burmako Can you please review this PR ? Thank you!

2023-09-12 06:15 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2023-09-18 02:44 UTC, qingyunqu commented
> Hi @qingyunqu Can you please resolve conflicts? Thank you!

ok, I will resolve later.

2023-12-15 05:27 UTC, gbaned commented
Hi @GleasonK  Can you please review this PR ? Thank you!

2023-12-15 18:17 UTC, GleasonK requested changes
Changes LGTM, minor nit on variable casing. I agree that we should try to remove this duplication with `lite/`

2023-12-22 06:55 UTC, gbaned commented
Hi @qingyunqu Can you please check @GleasonK's comments and keep us posted? Thank you!

2023-12-29 06:20 UTC, gbaned commented
Hi @qingyunqu Any update on this PR? Please. Thank you!

2023-12-30 18:22 UTC, qingyunqu commented on third_party/xla/xla/mlir_hlo/mhlo/transforms/unfuse_batch_norm/unfuse_batch_norm.cc
> +  LogicalResult matchAndRewrite(mhlo::BatchNormInferenceOp bn_op,
Done.

2023-12-30 18:24 UTC, qingyunqu commented on third_party/xla/xla/mlir_hlo/mhlo/transforms/unfuse_batch_norm/unfuse_batch_norm.cc
> +    Value multiplier = rewriter.create<mhlo::AddOp>(
Yes, I migrate it because `mlir/lite/stablehlo/transforms/unfuse_batch_norm_pass.cc` can't use by consumer who only integrate `mlir-hlo` repo.

2024-01-19 07:08 UTC, gbaned commented
Hi @GleasonK Can you please review this PR ? Thank you!

2024-01-19 08:17 UTC, akuegel commented on third_party/xla/xla/mlir_hlo/mhlo/transforms/unfuse_batch_norm/unfuse_batch_norm.cc
> +    Value multiplier = rewriter.create<mhlo::AddOp>(
I think the question was that now that you copied the pass, can the other instance of the pass be removed?

2024-01-19 17:20 UTC, GleasonK approved these changes

2024-01-22 09:17 UTC, gbaned approved these changes

2024-02-02 05:10 UTC, gbaned approved these changes

2024-03-18 05:44 UTC, gbaned approved these changes

2024-04-10 05:32 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-04-25 15:45 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-05-02 08:07 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-05-18 01:59 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-05-29 06:10 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-06-05 08:22 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-06-18 07:23 UTC, gbaned commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-06-25 11:07 UTC, keerthanakadiri commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-07-05 07:17 UTC, keerthanakadiri commented
Hi @GleasonK Can you please resolve conflicts? Thank you!

2024-07-15 07:16 UTC, keerthanakadiri commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-07-22 08:55 UTC, keerthanakadiri commented
Hi @qingyunqu Can you please resolve conflicts? Thank you!

2024-09-03 01:57 UTC, closed without merging