Fix aligned alloc feature condition on C++14 compiler
tensorflow/tensorflow pull request #61176
Opened 2023-07-05 08:48 UTC by pjpratik

The updated condition will only compile if both C++17 and C11 compliance are met, guaranteeing that the aligned_alloc feature is available. 

Relevant closed PR #57707 

Fixes #57706

2023-07-14 06:02 UTC, gbaned commented
Hi @haozha111 Can you please review this PR ? Thank you!

2023-07-14 17:30 UTC, mihaimaruseac requested changes
This just adds to a comment, duplicating what is already there

2023-07-14 17:31 UTC, mihaimaruseac approved these changes
Oh, I see the `&&` part too.

2023-07-14 20:22 UTC, haozha111 approved these changes

2023-07-16 17:47 UTC, haozha111 approved these changes

2023-07-16 21:53 UTC, mihaimaruseac approved these changes

2023-07-26 17:24 UTC, mihaimaruseac commented on tensorflow/lite/core/interpreter_builder.cc
> +//(introduced in stdc11 but realized in C++17)
```suggestion
// (introduced in stdc11 but realized in C++17)
```

2023-07-26 17:24 UTC, mihaimaruseac commented on tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc
> +//(introduced in stdc11 but realized in C++17)
```suggestion
// (introduced in stdc11 but realized in C++17)
```

2023-07-26 17:24 UTC, mihaimaruseac approved these changes

2023-07-26 21:24 UTC, merged