[XLA:CPU]  Moving oneDNN threadpool wrapper to tsl
tensorflow/tensorflow pull request #61236
Opened 2023-07-10 23:51 UTC by agramesh1

This PR moves the oneDNN threadpool wrapper code under tsl, and uses tsl namesapce so it can also called from XLA code.  
Changes include
1)	Removed dependency on reading an TF environment flag for using calling thread. The code for reading the flag is removed and the env value is now passed into the constructor from TensorFlow.
2)	Pointer to the Eigen threadpool is directly passed to the constructor instead of getting it from OptKernelContext.
3)	Some additional changes for clarity and using oneDNN instead of mkl in variable and filenames.

2023-07-13 14:43 UTC, penpornk requested changes
Thank you very much for the PR, @agramesh1! The overall PR looks good to me. I have two minor comments.

2023-07-13 14:43 UTC, penpornk commented on tensorflow/core/kernels/mkl/mkl_avgpooling_op.cc
> +                                     ThreadPoolUseCallerThread());
Can we define an `EigenThreadPoolFromTfContext` macro or inline function in `mkl_util.h` (or somewhere convenient)? Then we can create the threadpool in one statement.
```suggestion
      tsl::OneDnnThreadPool eigen_tp(EigenThreadPoolFromTfContext(context),
                                     ThreadPoolUseCallerThread());
```

2023-07-15 16:11 UTC, agramesh1 commented
> Thank you very much for the PR, @agramesh1! The overall PR looks good to me. I have two minor comments.

@penpornk I made the changes. Please take a look at it.

2023-07-16 18:11 UTC, penpornk approved these changes
Thank you for the changes!

2023-07-17 11:51 UTC, merged