Update numpy version in setup.py
tensorflow/tensorflow pull request #61267
Opened 2023-07-13 07:19 UTC by SuryanarayanaY

Currently tf-nightly is not compatible with numpy <=1.22.* versions. Its working only with numpy versions >=1.23 . But `Required_packages` in `setup.py` file mentioned numpy>=1.22. Hence I am updating numpy to `numpy>=1.23`.

Attaching the [gist](https://colab.research.google.com/gist/SuryanarayanaY/64c4ee7346aaa0a0492f01662147e159/tf-nightly_with_numpy_compatibility.ipynb) also for reference to check the behaviour.

2023-07-13 16:21 UTC, mihaimaruseac commented
You need to update the requirements.txt files used in all CI too, they have to test with a numpy that matches what is in setup.py

2023-07-13 19:35 UTC, MarkDaoust commented
Thanks. `tf-nightly` is broken in Colab right now (workaround: `pip install -U numpy`). This will fix it.

@mihaimaruseac Here? https://github.com/tensorflow/tensorflow/blob/0ed8e904f4cb58826e2bd861ae508e38f49d3ea8/tensorflow/tools/tf_sig_build_dockerfiles/devel.requirements.txt#L13-L16

2023-07-13 19:37 UTC, mihaimaruseac commented
I think so, unclear what are the current files being used by hermetic Python and all CIs. Tagging @angerson and @vam-google to confirm.

2023-07-14 04:14 UTC, SuryanarayanaY commented
"I have found below requirements.txt files.

I can see numpy version as >=1.22 in requirements.in file.
https://github.com/tensorflow/tensorflow/blob/9fa5e774d4f86c2e41b04a6ac326578bdd516691/ci/official/requirements_updater/requirements.in#L1

Apart from this `requirements_lock_3_10.txt` and others (`requirements_lock_3_11.txt`, `requirements_lock_3_9.txt`, `requirements_lock_3_8.txt`) have numpy version set to 1.24.3 .

https://github.com/tensorflow/tensorflow/blob/9fa5e774d4f86c2e41b04a6ac326578bdd516691/requirements_lock_3_10.txt#L265

But here in `ci_build/release/requirements_common.txt` requirements mentioned as below.

https://github.com/tensorflow/tensorflow/blob/9fa5e774d4f86c2e41b04a6ac326578bdd516691/tensorflow/tools/ci_build/release/requirements_common.txt#L12-L13

Under Docker SIG build:
https://github.com/tensorflow/tensorflow/blob/aa7fbf11a7581009f08933273bde7a0bc2490aff/tensorflow/tools/tf_sig_build_dockerfiles/devel.requirements.txt#L15-L16

2023-07-14 13:26 UTC, MichaelHudgins commented
Thanks @SuryanarayanaY , i think those are the 4 primary locations,  and to my knowledge all should be updated to >= 1.23 given what you have said above.  Normally the requirements lock files would need recomputed but given they are already locked above that value it should be fine to leave as is.  If you can update the PR to include those today I can pull internal and make sure the requirement locks are fine, if not i will likely pull it in and adjust myself to fix the next build of tf-nightly.

2023-07-14 22:22 UTC, MichaelHudgins approved these changes

2023-07-14 22:32 UTC, MichaelHudgins approved these changes

2023-07-14 23:46 UTC, MichaelHudgins commented
I am going to hold this till Monday, @georgiyekkert pointed out that this upgrade seems required due to when we build tf-nightly we are using numpy headers from CI, so our nightly is packed with 1.24.3 headers no matter what user has installed on their machine.  

We will first try to modify and make 1.22 work again and discuss a 1.23 upgrade separately

2023-07-21 16:14 UTC, MarkDaoust commented
Looks like there's a conflict wth this commit: https://github.com/tensorflow/tensorflow/commit/d9962234b8a33eb3b351ce69498f1671a832b98a

2023-07-24 05:17 UTC, gbaned commented
Hi @SuryanarayanaY Can you please resolve conflicts? Thank you!

2023-07-25 16:46 UTC, mihaimaruseac requested changes

2023-07-25 16:46 UTC, mihaimaruseac commented on tensorflow/tools/tf_sig_build_dockerfiles/devel.requirements.txt
> +numpy >= 1.23
Please use `~=` since the CI deps need to be pinned

2023-07-25 16:46 UTC, mihaimaruseac commented on tensorflow/tools/ci_build/release/requirements_common.txt
> +numpy >= 1.23
Please use `~=` since the CI deps need to be pinned

2023-07-25 16:46 UTC, mihaimaruseac commented on tensorflow/tools/ci_build/release/requirements_common.txt
> +scipy ~= 1.10.1
We still have Python versions lower than 3.11. We need to support them

2023-07-25 16:46 UTC, mihaimaruseac commented on tensorflow/tools/tf_sig_build_dockerfiles/devel.requirements.txt
> +scipy ~= 1.10.1
Need to support Python < 3.11

2023-07-25 17:38 UTC, georgiyekkert commented
The issue should have been fixed in https://github.com/tensorflow/tensorflow/commit/2c5f35e7e23c3298babf2227ea0ae128d1e6fb8e
The requirements files you are changing are outdated and not used in the build any more. Please let me know if you still have any issues otherwise please close.

2023-07-25 17:42 UTC, mihaimaruseac commented
Perfect, then this can gen closed. Thanks @georgiyekkert

2023-07-25 17:42 UTC, closed without merging