return assert_shapes for debugging.assert_shapes
tensorflow/tensorflow pull request #61276
Opened 2023-07-13 22:30 UTC by sachinprasadhs

return assert_shapes for debugging.assert_shapes.
Fixes: https://github.com/tensorflow/tensorflow/issues/61163

2023-07-13 22:35 UTC, cantonios requested changes
Can you add a test for this?

2023-07-31 05:25 UTC, gbaned commented
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

2023-08-24 06:07 UTC, gbaned commented
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

2023-09-11 07:51 UTC, gbaned commented
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

2023-09-26 05:04 UTC, gbaned commented
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

2023-10-31 06:03 UTC, gbaned commented
Hi @sachinprasadhs Any update on this PR? Please. Thank you!

2023-11-10 11:13 UTC, cheshire approved these changes

2023-11-10 21:03 UTC, merged