Support for jit-ed block reorder on AArch64
tensorflow/tensorflow pull request #61296
Opened 2023-07-17 09:31 UTC by cfRod

Re-opening a new PR for commit https://github.com/tensorflow/tensorflow/pull/61123/commits/a071af0ca8a3ea1fe242094514507f649f3ab64e

2023-07-17 09:32 UTC, cfRod commented
@penpornk

2023-07-17 09:45 UTC, penpornk requested changes

2023-07-17 09:45 UTC, penpornk commented on tensorflow/workspace2.bzl
> +            "//third_party/mkl_dnn:onednn_reorder_padded.patch",
To be consistent to #61295,
```suggestion
            "//third_party/mkl_dnn:onednn_acl_reorder_padded.patch",
```

2023-07-18 14:45 UTC, penpornk requested changes
#61295 was merged. Could you please rebase? Thank you!

2023-07-18 15:48 UTC, penpornk approved these changes
Thank you! :)

2023-07-20 11:16 UTC, penpornk requested changes
Minor fixes please. (They are failing our internal checks.)

2023-07-20 11:16 UTC, penpornk commented on third_party/mkl_dnn/onednn_acl_reorder_update.patch
> ++    //every thread gets its own scratchpad space for each N
Nit:
```suggestion
+    // Every thread gets its own scratchpad space for each N
```

2023-07-20 11:16 UTC, penpornk commented on third_party/mkl_dnn/onednn_acl_reorder_update.patch
> ++    //reduction of intermediate compensation results to the final output
Nit:
```suggestion
+    // Reduction of intermediate compensation results to the final output
```

2023-07-20 12:18 UTC, cfRod commented
Done!

2023-07-21 10:53 UTC, penpornk approved these changes
Thank you! :)

2023-07-21 17:24 UTC, merged