Adding extra options to Kubernetes object generator for distributed example.
tensorflow/tensorflow pull request #6130
Opened 2016-12-06 22:12 UTC by elsonrodriguez

This enables multiple training clusters to be deployed in the same namespace.

2016-12-16 20:53 UTC, caisq requested changes

2016-12-16 20:53 UTC, caisq commented on tensorflow/tools/dist_test/scripts/k8s_tensorflow.py
> +def GenerateConfig(cluster_name,
Can you make this change backward compatible by letting cluster_name and creator be keyward arguments that have None values? So if some user doesn't want to explicitly set the arguments, they can just ignore them, and the pods, rcs and services will have the same naming pattern as before, i.e., without the prefixes like "cluster1-"?

2016-12-16 20:53 UTC, caisq commented on tensorflow/tools/dist_test/scripts/k8s_tensorflow.py
> +                      default=DEFAULT_CLUSTER_NAME,
Same as below. Can you please make it backward compatible? Let the default be an empty string, which GenerateConfig() can ignore, which leads to the same naming pattern as before. Thanks!

2016-12-17 00:19 UTC, jhseu commented
No opinion about whether to merge, but I think these scripts should be used purely for testing and not a demonstration of how to run distributed TF :)

2016-12-17 03:21 UTC, caisq commented
@jhseu Agreed. These scripts should be treated as they are, i.e., tests (they live in the folder called dist_test), not examples, even though some users might find bits and pieces of useful.

2016-12-20 00:22 UTC, jhseu commented
Closing for now as these changes aren't needed for testing. @caisq feel free to reopen if you disagree.

2016-12-20 00:22 UTC, closed without merging

2017-01-09 04:14 UTC, elsonrodriguez commented
@caisq @jhseu The hardcoding of the objects into the generator script is definitely a shortcoming, and the data is baked into the containers, but aside from that what are the other shortcomings of this test?

I ask because I'm totally new to tensorflow, and was trying to prototype a kubernetes third party resource to help developers quickly create training clusters: https://github.com/elsonrodriguez/tensorsets

What's a better script/test to base this type of automation on?