Update to CONTRIBUTING.md
tensorflow/tensorflow pull request #61597
Opened 2023-08-17 04:04 UTC by rivalavocado

2023-08-17 07:11 UTC, gbaned commented
Hi @rivalavocado Can you please resolve conflicts? Thank you!

2023-08-17 14:03 UTC, vijayasarathib commented on CONTRIBUTING.md
>  - If the PR didn't meet the validation criteria, we request for additional
could you modify this "doesn't" instead of past tense "didn't".

2023-08-17 14:03 UTC, vijayasarathib commented on CONTRIBUTING.md
> +- For valid PR, reviewer (person familiar with the code/functionality) checks if
Valid should be in lower case

2023-08-17 14:07 UTC, vijayasarathib commented on CONTRIBUTING.md
>  Changes to TensorFlow Python code should conform to
should be Changes to TensorFlow's Python code should conform to

2023-08-17 14:22 UTC, vijayasarathib reviewed
Hello,
I've reviewed the changes made in the CONTRIBUTING.md file and have some grammatical suggestions to enhance clarity and correctness. I have left the comme
1.  Original: "If the PR didn't meet the validation criteria..."
   Suggestion: Use present tense "doesn't" instead of past tense "didn't".
2.Original: "For Valid PR, reviewer..."
   Suggestion: "Valid" should be in lowercase and be "a valid".
 3. Original:Changes to TensorFlow Python code should conform to
    Suggestion: Changes to TensorFlow's Python code should conform to

2023-08-20 17:09 UTC, mihaimaruseac requested changes

2023-08-20 17:09 UTC, mihaimaruseac commented on CONTRIBUTING.md
> +![guidelines1](https://github.com/rivalavocado/tensorflow/assets/56943827/3fea1abf-e5bb-4747-be72-8f6449868b84)
Why change the image link?

2023-08-20 17:09 UTC, mihaimaruseac commented on CONTRIBUTING.md
> +[What is G3?](https://github.com/Xtra-Computing/G3)
What is this link doing here?

2023-09-25 05:17 UTC, gbaned commented
Hi @rivalavocado Can you please check @mihaimaruseac's comments and resolve conflicts?. Thank you!

2023-11-03 08:14 UTC, gbaned commented
Hi @rivalavocado Any update on this PR? Please. Thank you!

2023-12-15 06:34 UTC, gbaned commented
Hi @rivalavocado  I'm going to go ahead and close this PR, because it seems to have stalled. If you're still interested in pursing this (and responding to my comments), please feel free to reopen! Thank you for your contribution!

2023-12-15 06:34 UTC, closed without merging