Minor clarification for `Dataset.prefetch` docs
tensorflow/tensorflow pull request #61641
Opened 2023-08-19 01:01 UTC by matangover

I found the existing wording somewhat confusing ("XXX will prefetch two elements, while XXX will prefetch two elements"). The new wording makes the difference clearer.

2023-08-21 16:59 UTC, fionalang commented
Hi, I don't work on tf data so I don't think I'm the right reviewer for this PR, could you please find a different reviewer? Thanks!

2023-09-25 05:21 UTC, gbaned commented
Hi @aaudiber Can you please review this PR ? Thank you!

2023-11-03 14:59 UTC, wilsingosti requested changes
The existing comment explains the concept of element vs example. The proposed comment removes the concept of element. I would not make the change.

2023-11-04 23:39 UTC, matangover commented
@wilsingosti My proposed change does not remove the concept of elements. After my change, the note reads:

> Note: Like other `Dataset` methods, prefetch operates on the elements of the input dataset. It has no concept of examples vs. batches. `examples.prefetch(2)` will prefetch 2 examples, while `examples.batch(20).prefetch(2)` will prefetch 40 examples (2 batches, of 20 examples each).

Still includes the concept of elements, and in my opinion the wording is now clearer. However if you think the current wording is clearer please close my PR.

2023-11-05 03:48 UTC, wilsingosti commented
@matangover You are right. Your proposed change does not remove the concept of elements. However, I think the current wording fine and I would like to keep it. Thanks for contributing.

2023-11-05 03:48 UTC, closed without merging