Update args description of crop_to_bounding_box & pad_to_bounding_box
tensorflow/tensorflow pull request #61672
Opened 2023-08-22 16:48 UTC by SuryanarayanaY

Currently the documentation of the API `tf.image.crop_to_bounding_box` doesn't mentioning the acceptable dtypes of the arguments `offset_height, offset_width, target_height, target_width`. This API accepts only` tf.int32 Tensor` or a `integer`. For other dtypes its raising exception. Hence adding details of acceptable dtypes for these arguments for better clarity to the users.

Also Fixes #61644 .

Similarly `tf.image.pad_to_bounding_box` documentation also have the same arguments `offset_height, offset_width, target_height, target_width`. But these arguments accept `int32` and `int64`Tensors but not others.Hence added details of acceptable dtypes for these arguments for better clarity to the users.

2023-08-22 17:46 UTC, cantonios requested changes

2023-08-22 17:46 UTC, cantonios commented on tensorflow/python/ops/image_ops_impl.py
> +      of dtype int32 or int64.Can also a python integer.
Missing space before "Can".

2023-08-22 17:46 UTC, cantonios commented on tensorflow/python/ops/image_ops_impl.py
> +      of dtype int32 or int64.Can also a python integer.
Are you sure it's a 1-D tensor and not a 0-D tensor (i.e. a scalar)?  Here and throughout.

2023-08-22 17:46 UTC, cantonios commented on tensorflow/python/ops/image_ops_impl.py
> +    offset_width: Number of columns of zeros to add on the left.Must be
Missing space before "Must".

2023-08-23 07:30 UTC, SuryanarayanaY commented on tensorflow/python/ops/image_ops_impl.py
> +    offset_width: Number of columns of zeros to add on the left.Must be
Sure will add space at all required places.

2023-08-23 15:45 UTC, cantonios approved these changes

2023-08-23 17:18 UTC, merged