Run GPU tests on Windows with Bazel
tensorflow/tensorflow pull request #6187
Opened 2016-12-08 10:05 UTC by meteorcloudy

After this change, we can run:

CPU build + python tests: `tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh`
CPU C++ tests: `tensorflow/tools/ci_build/windows/cpu/bazel/run_cc_test_windows.sh`
GPU build + python tests: `tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh`
GPU C++ tests: `tensorflow/tools/ci_build/windows/gpu/bazel/run_cc_test_windows.sh`

2016-12-08 22:41 UTC, gunan requested changes

2016-12-08 22:41 UTC, gunan commented on tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
> +rm -f ./tensorflow-*.whl
same comment as in GPU script.
let's build the pip package into a new directory. and avoid rm -f here.

2016-12-09 13:14 UTC, meteorcloudy commented
I refactored all the scripts, please take a look again. :)

2016-12-09 18:53 UTC, gunan commented on tensorflow/tools/ci_build/windows/gpu/bazel/run_cc_test_windows.sh
> +slow_compiling_test="//tensorflow/core/kernels:eigen_backward_spatial_convolutions_test"
@mrry @guschmue @vit-stepanovs 
I assume we have the same problem for cmake?

2016-12-09 18:54 UTC, gunan approved these changes

2016-12-09 18:54 UTC, merged

2016-12-09 19:07 UTC, vit-stepanovs commented on tensorflow/tools/ci_build/windows/gpu/bazel/run_cc_test_windows.sh
> +slow_compiling_test="//tensorflow/core/kernels:eigen_backward_spatial_convolutions_test"
Yes, that particular test takes very long to build in CMake too.