[TOSA] Separate left shifting in SQUARED_DIFFERENCE to avoid precision loss
tensorflow/tensorflow pull request #61991
Opened 2023-09-27 15:22 UTC by Tessil

Hi,

This PR moves the left shifting in the `tfl.squared_difference` TFL -> TOSA legalization in a separate `tosa.rescale` to avoid any precision loss which could create non bit-exact results.

2023-10-05 06:37 UTC, gbaned commented
Hi @Tessil Can you please resolve conflicts? Thank you!

2023-10-20 12:09 UTC, Tessil commented
@gbaned Done, thanks.

2023-12-15 06:58 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2023-12-29 08:25 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-03-08 16:45 UTC, gbaned commented
Hi @rdzhabarov Can you please review this PR ? Thank you!

2024-04-26 08:51 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-06-07 16:24 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-07-09 07:25 UTC, keerthanakadiri commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-07-17 05:06 UTC, keerthanakadiri commented
Hi @jpienaar , Can you please review this PR ? Thank you!

2024-08-07 06:11 UTC, keerthanakadiri commented
Hi @jpienaar , Can you please review this PR ? Thank you!

2024-08-28 07:31 UTC, keerthanakadiri commented
Hi @jpienaar , Can you please review this PR ? Thank you!

2024-09-03 07:19 UTC, keerthanakadiri commented
Hi @jpienaar , Can you please review this PR ? Thank you!

2024-09-18 04:32 UTC, keerthanakadiri commented
Hi @jpienaar , Can you please review this PR ? Thank you!

2024-10-03 09:55 UTC, keerthanakadiri commented
Hi @jpienaar , Can you please review this PR ? Thank you!

2025-02-06 10:37 UTC, ekalda approved these changes
LGTM!

2025-02-06 18:14 UTC, leandron requested changes
@Tessil can you update this PR to solve the conflicts and then @ekalda to review it again, please?

2025-02-10 09:55 UTC, leandron commented
@mihaimaruseac I reopened a few of these TOSA related patches so that we can get them updated, reviewed and hopefully merged soon. (cc @jpienaar)

2025-03-26 10:08 UTC, Tessil commented
This is solved by https://github.com/tensorflow/tensorflow/commit/a3c37bce4f04befa1b15edf5cce108887a36aeb5 now.

Closing.

2025-03-26 10:09 UTC, closed without merging