Identify new ISA
tensorflow/tensorflow pull request #62084
Opened 2023-10-11 06:27 UTC by gaurides

This PR adds code to identify new instruction sets

2023-10-11 17:43 UTC, ezhulenev approved these changes

2023-10-13 18:02 UTC, gaurides commented
Hi @ezhulenev - Can you please share the failures in internal failures in feedback/copybara?

2023-12-01 21:45 UTC, cantonios requested changes

2023-12-01 21:45 UTC, cantonios commented on third_party/xla/third_party/tsl/tsl/platform/cpu_info.h
> +  AVX_NE_CONVERT = 46, // Instructions for faster bfloat16, float16 convert.
nit: these next two are missing a second space before the comment.

2023-12-01 22:53 UTC, cantonios approved these changes

2023-12-01 23:17 UTC, cantonios commented
Hmm... now that XLA/TSL has been separated out of TF, it looks like we're having issues because this is a cross-cutting change.

I think you need to create a separate PR on the XLA repo to add the TSL definitions.  Then once that's merged, remove that part from this PR and submit only the TF-only changes.

@jakeharmon8 is that correct?

2023-12-04 20:31 UTC, gaurides commented
> Hmm... now that XLA/TSL has been separated out of TF, it looks like we're having issues because this is a cross-cutting change.
> 
> I think you need to create a separate PR on the XLA repo to add the TSL definitions. Then once that's merged, remove that part from this PR and submit only the TF-only changes.
> 
> @jakeharmon8 is that correct?

ok, i will create XLA PR for those 2 files.

2023-12-06 02:58 UTC, gaurides commented
@cantonios - this is the openXLA PR - This PR is for ISA related changes in XLA part. Earlier they were part of this PR - https://github.com/openxla/xla/pull/7565

2023-12-14 17:43 UTC, gaurides commented
@cantonios - please let me know if I need to update/fix something for this PR. Thanks.

2023-12-14 18:29 UTC, cantonios approved these changes

2023-12-14 21:08 UTC, merged