Determine output shape for SplitV Op
tensorflow/tensorflow pull request #6212
Opened 2016-12-09 12:04 UTC by AnishShah

Fixes #6186 

I couldn't find any tests for SplitV in `array_ops_test.cc`. Is there any other file for SplitV test?

2016-12-12 06:48 UTC, AnishShah commented
Any review for this? I have used three same for loops to set output shape. Can anyone suggest better way to refactor this? Thanks! :)

2016-12-12 23:39 UTC, ekelsen commented on tensorflow/core/ops/array_ops.cc
> +        for (int i = 0; i < num_outputs; ++i) {
should check that the size of vec is indeed the number of outputs.

2016-12-12 23:41 UTC, ekelsen commented on tensorflow/core/ops/array_ops.cc
> +        for (int i =0; i < num_outputs; ++i) {
space after =

2016-12-12 23:42 UTC, ekelsen commented
added some comments, please also add a test that verifies the output shapes are indeed correct.

2016-12-13 01:20 UTC, martinwicke commented
Good question about tests though -- @ekelsen where do splitV tests live?

2016-12-13 01:36 UTC, ekelsen commented
The split_v tests live in kernel_tests/split_op_test.py.

2016-12-13 06:30 UTC, AnishShah commented on tensorflow/core/ops/array_ops.cc
> +        for (int i = 0; i < num_outputs; ++i) {
What should I do if both are not equal? `TF_RETURN_IF_ERROR` or I should not determine the shape?

2016-12-13 06:34 UTC, AnishShah commented on tensorflow/core/ops/array_ops.cc
> +        for (int i = 0; i < num_outputs; ++i) {
I think, it would be better to add `TF_RETURN_IF_ERROR`.

2016-12-13 07:17 UTC, AnishShah commented on tensorflow/core/ops/array_ops.cc
> +        for (int i = 0; i < num_outputs; ++i) {
Sorry, What I meant was should I throw an error if it is not equal?

2016-12-13 07:58 UTC, AnishShah commented
@ekelsen Updated the PR.. Please check.

2016-12-13 18:05 UTC, ekelsen requested changes
Additional error checking looks good.  Just some formatting issues in the new test.

2016-12-13 18:05 UTC, ekelsen commented on tensorflow/python/kernel_tests/split_op_test.py
> +  def testOutputShape(self):
Looks great, thank you, but the indentation is not consistent here with the rest of the file.  Please change to 2 spaces.

2016-12-13 18:59 UTC, AnishShah commented
@ekelsen Done!

2016-12-13 19:10 UTC, ekelsen approved these changes
LGTM, thank you for the contribution!

2016-12-14 04:54 UTC, AnishShah commented
We can run the tests now?

2016-12-14 08:21 UTC, martinwicke commented
Jenkins, test this please!

2016-12-14 09:32 UTC, martinwicke commented
split_op_test failed, please check.

2016-12-14 10:38 UTC, AnishShah commented
@martinwicke The tests are failing because `size_splits` in [this test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/split_op_test.py#L69) is a numpy array. If I cast it into a list, then it works properly. I'm not sure any it is failing because of my changes. Do you have any idea?

2016-12-14 10:49 UTC, AnishShah commented
@martinwicke The tests are failing because `size_splits` in [these tests](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/split_op_test.py#L69) are numpy array instead of list. If I type cast them into a list, then all the tests are passing. I'm not sure why my changes are causing this error. Do you have any idea about this? Please help. :)

This is the output of running tests.
```
............F tensorflow/core/framework/tensor.cc:487] Check failed: dtype() == expected_dtype (9 vs. 3)
```

2016-12-14 18:39 UTC, ekelsen commented on tensorflow/core/ops/array_ops.cc
> +        auto vec = size_splits->vec<int32>();
The problem is here - size_splits can be either of type int32 or int64 (see the signature), but this line assumes int32, which is what is causing the type mismatch.

2016-12-15 07:06 UTC, AnishShah commented
I have made the changes and the tests are passing. Can we run the tests again?

2016-12-15 08:01 UTC, AnishShah commented
The tests are failing after I rebased the branch. It is failing because of commit - a46b6d211eac423c72d3a57a177daf2f64db8642
Looking into it.

2016-12-15 08:57 UTC, AnishShah commented
Done! Please run the tests now.

2016-12-15 16:48 UTC, martinwicke commented
Jenkins, test this please!

2016-12-15 18:19 UTC, AnishShah commented
All checks have passed :)

2016-12-15 18:48 UTC, ekelsen commented
Thanks for the contribution Anish! Should get merged by someone with permission soon.

2016-12-15 22:48 UTC, merged