Python 3.12 tooling / CI support
tensorflow/tensorflow pull request #62155
Opened 2023-10-18 16:51 UTC by SamuelMarks

I saw 5f7f05a so I guess we're close to Python 3.12 support. Committing this up so I can see what passes/fails and fix accordingly.

2023-10-18 19:37 UTC, MichaelHudgins commented
@vladbelit could you PTAL

2023-10-19 13:47 UTC, MichaelHudgins requested changes

2023-10-19 13:47 UTC, MichaelHudgins commented on .github/workflows/arm-cd.yml
Please omit this file for now.

2023-10-19 14:20 UTC, vladbelit commented
We have a similar change going out soon (nightly jobs), though there are still a couple of details being hashed out with regards to CI

2023-11-03 09:31 UTC, gbaned commented
Hi @SamuelMarks Can you please rebase your branch and resolve conflicts? Thank you!

2023-11-03 13:13 UTC, vladbelit commented
This could probably be closed - the Linux x86/ARM 3.12 nightlies are up. They should soon be set to upload, once a few superficial test failures are resolved.
MacOS should be added soon as well.

2023-11-03 13:18 UTC, MichaelHudgins commented
Thanks for the PR @SamuelMarks but the internal effort landed and our continued development of the official directory would have needed this PR to change multiple times.

2023-11-03 13:18 UTC, closed without merging