[BugFix] : Update padding computation for TFL->TOSA for transpose_conv.
tensorflow/tensorflow pull request #62213
Opened 2023-10-24 16:23 UTC by sahas3

This change fixes the padding computation for translating `tfl.transpose_conv` to `tosa.transpose_conv2d` as per the padding definition change for the padding attribute in TOSA spec in https://git.mlplatform.org/tosa/specification.git/commit/?id=eda7b126d3914e9461cf014439b3571b9e6a9c41

For more info, please refer to the discussion in https://github.com/llvm/llvm-project/pull/68167

2023-11-03 09:32 UTC, gbaned commented
Hi @rsuderman, Can you please review this PR ? Thank you!

2023-12-29 08:41 UTC, gbaned commented
Hi @jpienaar, Can you please review this PR ? Thank you!

2024-02-09 08:31 UTC, gbaned commented
Hi @jpienaar, Can you please review this PR ? Thank you!

2024-03-07 08:04 UTC, gbaned commented
Hi @jpienaar, Can you please review this PR ? Thank you!

2024-04-26 08:57 UTC, gbaned commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-06-07 16:31 UTC, gbaned commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-07-09 07:30 UTC, keerthanakadiri commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-07-17 05:20 UTC, keerthanakadiri commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-08-07 09:51 UTC, keerthanakadiri commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-08-28 07:34 UTC, keerthanakadiri commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-09-03 09:58 UTC, keerthanakadiri commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-09-18 04:38 UTC, keerthanakadiri commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2024-10-10 08:45 UTC, keerthanakadiri commented
Hi @NatashaKnk, Can you please review this PR ? Thank you!

2025-04-11 16:15 UTC, leandron requested changes
@sahas3 can you rebase this PR again to solve the conflicts, please?

2025-04-12 20:46 UTC, sahas3 commented
> @sahas3 can you rebase this PR again to solve the conflicts, please?

Hi @leandron , looks like https://github.com/tensorflow/tensorflow/pull/61892 which is recently merged implemented the same change. So I am closing this PR. Thanks!

2025-04-12 20:46 UTC, closed without merging