Update accelerator_util.py
tensorflow/tensorflow pull request #62230
Opened 2023-10-25 18:41 UTC by gautam1858

1. Introduced an AcceleratorType class to define accelerator types for better clarity. 
2. Created an AcceleratorSystem class to encapsulate the accelerator system's functionality.
3.  Removed global variables and used instance variables within the AcceleratorSystem class. 
4. Simplified the code structure and made it more organized. 
5. Removed unnecessary repetitive checks and error handling. 
6. Improved docstrings and comments for better understanding. 
7. Reorganized the code for improved readability.

2023-10-27 15:45 UTC, rainwoodman commented
I think this PR is far away from being ready to be merged.

It is not clear of the merits of the changes, and the description is inconsistent with the actual changes;
for example all of the docstrings have been removed while the description claimed improvements in the docstring.

2023-10-27 15:48 UTC, rainwoodman requested changes
This PR clearly violated the codestyle, and appears buggy as it removed the API endpoints. A lot more work is needed to get it ready for merging, and it is not clear if these changes actually intend to bring any new functionality or fix any bugs.

2023-10-28 20:17 UTC, mihaimaruseac commented
Please don't use "add file"/"update file"/"fix file"/etc. commit messages. These are hard to reason about when looking at the history of the file/repository. Instead, please write explanatory git commit messages.

The commit message is also the title of the PR if the PR has only one commit. It is thus twice important to have commit messages that are relevant, as PRs would be easier to understand and easier to analyze in search results.

For how to write good quality git commit messages, please consult https://cbea.ms/git-commit/ 

We will automaticall close PRs by you if you don't take these suggestions into account

2023-10-28 20:19 UTC, mihaimaruseac requested changes
This looks like a spam change. Please consult CONTRIBUTORS file and don't send spam PRs.

This won't count for Hacktoberfest

2023-10-28 20:19 UTC, mihaimaruseac commented on tensorflow/dtensor/python/accelerator_util.py
> -# Copyright 2022 The TensorFlow Authors. All Rights Reserved.
Why did you remove the copyright?

2023-10-28 20:19 UTC, closed without merging

2023-10-28 20:19 UTC, mihaimaruseac commented
Closed as spam, 3 spam PRs already