Documentation of `tf.nn.depthwise_conv2d` Add limitation doc on strides
tensorflow/tensorflow pull request #62321
Opened 2023-11-04 07:50 UTC by rajveer43

2023-11-06 06:01 UTC, cantonios requested changes

2023-11-06 06:01 UTC, cantonios commented on tensorflow/python/ops/nn_impl.py
> +  Please note that if any value in `dilations` is greater than 1, we perform
Why this change?

2023-11-06 06:01 UTC, cantonios commented on tensorflow/python/ops/nn_impl.py
> +             [22., 32.]]]], dtype float32)
This is incorrect.

2023-11-06 06:01 UTC, cantonios commented on tensorflow/python/ops/nn_impl.py
> +             [ 6., 8.]],
Please revert formatting.

2023-11-06 06:01 UTC, cantonios commented on tensorflow/python/ops/nn_impl.py
> +      dimension of `input`. Must have `strides[0] = strides[3] = 1`, and for
This is already described above in the details section.  Do you really think it's necessary to have here too?

2023-11-06 06:34 UTC, rajveer43 commented
The issue mentioned that there is `strides` documentation is not proper

2023-11-07 16:22 UTC, cantonios commented
> The issue mentioned that there is `strides` documentation is not proper

Ah, I see, the documentation is a bit unclear in the above section.  Sure, you can fix that.  You'll need to update the PR though.

2023-11-07 16:24 UTC, cantonios requested changes

2023-11-07 16:24 UTC, cantonios commented on tensorflow/python/ops/nn_impl.py
> -      dimension of `input`. Must have `strides[0] = strides[3] = 1`, and for
You'll need to re-add something here, but you need to explicitly mention that _only_ equal strides are supported (I'm guessing only if `strides[0]` and `strides[3]` are 1?).  Do some testing to confirm, and fix where it's mentioned above as well.

2023-11-07 16:24 UTC, cantonios commented on tensorflow/python/ops/nn_impl.py
> -      dimension of `input`. Must have `strides[0] = strides[3] = 1`, and for
You'll need to re-add something here, but you need to explicitly mention that _only_ equal strides are supported (I'm guessing only if `strides[0]` and `strides[3]` are 1?).  Do some testing to confirm, and fix where it's mentioned above as well.

2023-11-09 07:24 UTC, rajveer43 commented
@cantonios, sure I will do some testing for it! and then add it

2023-12-15 07:19 UTC, gbaned commented
Hi @rajveer43 Any update on this PR? Please. Thank you!

2023-12-29 08:47 UTC, gbaned commented
Hi @rajveer43 Any update on this PR? Please. Thank you!

2024-01-28 01:48 UTC, closed without merging