Register complex dtypes for TruncateDiv Op
tensorflow/tensorflow pull request #62409
Opened 2023-11-16 07:21 UTC by SuryanarayanaY

As per documentation the Op `tf.truncatediv` should support `complex` dtypes also.

> Args
> --
> x | A Tensor. Must be one of the following types: bfloat16, half, float32, float64, uint8, int8, uint16, int16, int32, uint32, uint64, int64, complex64, complex128.

As per the `math_ops.cc` , `complex` dtypes also registered for this Op.

https://github.com/tensorflow/tensorflow/blob/e63d37e07b95e5c6e8a78794547fe317454edae7/tensorflow/core/ops/math_ops.cc#L521-L523

https://github.com/tensorflow/tensorflow/blob/e63d37e07b95e5c6e8a78794547fe317454edae7/tensorflow/core/ops/math_ops.cc#L392-L395

Hence adding the complex dtypes also to this Op registry.

2023-11-16 19:48 UTC, mihaimaruseac approved these changes, later dismissed

2024-01-04 18:21 UTC, cantonios requested changes

2024-01-04 18:21 UTC, cantonios commented on tensorflow/core/kernels/cwise_op_div.cc
> +          bfloat16, float, double, complex64, complex128);
Complex types are _not_ supported.  This breaks a bunch of stuff, and as you can see from the functor, is only supported by _real_ values.  Floor/truncation doesn't make much sense for complex inputs.

2024-01-04 18:28 UTC, SeeForTwo commented
> As per documentation the Op tf.truncatediv should support complex dtypes also.

Thank you for noticing this. Floor/truncate division isn't supported for complex types, so the documentation is wrong.

2024-03-07 08:15 UTC, gbaned commented
Hi @SuryanarayanaY As mentioned by reviewers in above comments, Floor/truncate division isn't supported for complex types. Hence closing this PR. Thank you!

2024-03-07 08:15 UTC, closed without merging