Changes to add bfloat16 support for image rotation
tensorflow/tensorflow pull request #62417
Opened 2023-11-17 17:52 UTC by jojivk73

These are changes to add bfloat16 for image rotation. With mixed bfloat16 precision, models that use image transformation would perform much better with image rotation in bfloat16.

2023-11-20 19:07 UTC, cantonios requested changes

2023-11-20 19:07 UTC, cantonios commented on tensorflow/python/ops/image_ops_test.py
> +class ImageProjectiveTransformVX(test_util.TensorFlowTestCase):
nit: you can remove `VX`, I don't think it adds anything.

2023-11-23 08:43 UTC, gbaned commented
Hi @jojivk73 Can you please check @cantonios's comments and keep us posted ? Thank you!

2023-12-09 00:07 UTC, jojivk73 commented
@gbaned @cantonios. Sorry for the delay. I updated the name for testcase.
Thanks

2023-12-15 17:38 UTC, cantonios approved these changes

2023-12-16 18:53 UTC, merged