[TOSA] add tests for legalization of quantized MUL,SUB,ADD operators with unequal ranks
tensorflow/tensorflow pull request #62453
Opened 2023-11-21 18:50 UTC by psunn

add LIT tests for legalization of quantized MUL,SUB,ADD operators with unequal ranks

2023-11-22 14:12 UTC, psunn commented
This PR is relative to https://github.com/tensorflow/tensorflow/pull/60753 and https://github.com/tensorflow/tensorflow/pull/62153

2023-12-15 07:27 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2023-12-29 08:55 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-02-09 08:37 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-03-07 08:17 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-06-07 16:36 UTC, gbaned commented
Hi @jpienaar Can you please review this PR ? Thank you!

2024-07-09 09:51 UTC, keerthanakadiri commented
Hi @jpienaar , Can you please review this PR ? Thank you!

2024-07-17 05:26 UTC, keerthanakadiri commented
Hi @jpienaar, Can you please review this PR ? Thank you!

2024-08-07 10:04 UTC, keerthanakadiri commented
Hi @jpienaar, Can you please review this PR ? Thank you!

2024-08-28 09:10 UTC, keerthanakadiri commented
Hi @jpienaar, Can you please review this PR ? Thank you!

2024-09-03 10:19 UTC, keerthanakadiri commented
Hi @jpienaar, Can you please review this PR ? Thank you!

2025-02-05 16:12 UTC, leandron requested changes
@psunn can you update this to solve the conflicts, so that we can review this again, please?

2025-02-10 09:54 UTC, leandron commented
@mihaimaruseac I reopened a few of these TOSA related patches so that we can get them updated, reviewed and hopefully merged soon. (cc @jpienaar)

2025-03-06 00:26 UTC, psunn commented
ran local LIT test results:

```
INFO: Analyzed 33 targets (1 packages loaded, 33375 targets configured).
INFO: Found 16 targets and 17 test targets...
INFO: Elapsed time: 2.960s, Critical Path: 0.15s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
//tensorflow/compiler/mlir/tosa/tests:convert-tfl-uint8.mlir.test (cached) PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:convert_metadata.mlir.test (cached) PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:fuse-bias-tf.mlir.test    (cached) PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:lower-complex-types.mlir.test (cached) PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:multi_add.mlir.test       (cached) PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:retain_call_once_funcs.mlir.test (cached) PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:strip-quant-types.mlir.test (cached) PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:strip_metadata.mlir.test  (cached) PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:tf-tfl-to-tosa-pipeline.mlir.test (cached) PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:tf-to-tosa-pipeline.mlir.test (cached) PASSED in 0.7s
//tensorflow/compiler/mlir/tosa/tests:tf-unequal-ranks.mlir.test (cached) PASSED in 0.3s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-dequantize_softmax.mlir.test (cached) PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-pipeline-filtered.mlir.test (cached) PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-pipeline.mlir.test (cached) PASSED in 3.0s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-stateful.mlir.test (cached) PASSED in 0.6s
//tensorflow/compiler/mlir/tosa/tests:tfl-unequal-ranks.mlir.test (cached) PASSED in 0.3s
//tensorflow/compiler/mlir/tosa/tests:verify_fully_converted.mlir.test (cached) PASSED in 0.5s

Executed 0 out of 17 tests: 17 tests pass.
```

2025-03-06 00:41 UTC, Jerry-Ge approved these changes
LGTM

2025-03-06 10:37 UTC, leandron approved these changes
LGTM, thanks @psunn for the PR and @Jerry-Ge for the review.

2025-03-06 10:37 UTC, merged