Register half and bfloat16 support for tf.truncatemod
tensorflow/tensorflow pull request #62502
Opened 2023-11-29 16:05 UTC by SuryanarayanaY

As per documentation of `tf.truncatemod` this Op should support `{int32, int64, bfloat16, half, float, double}` dtypes. But actually this Op not supporting `half` and `bfloat16` dtypes.

As per `math_ops.cc `this op registered for the dtypes below.

https://github.com/tensorflow/tensorflow/blob/74866075411bd9444246e16a79429b852e4db31c/tensorflow/core/ops/math_ops.cc#L622-L626.

But in kernel registry not found for `half` and `bfloat16` dtypes. Hence adding these types into register hoping `functor::fmod` can handle these dtypes.

2023-11-29 22:47 UTC, gaurides requested changes
Change to register kernel is fine. Can you please add tests for bfloat16 and half? 
Secondly, the same file registers kernel for "Mod" op and doesn't register for bfloat16 and half. Maybe you should consider registering Mod for bfloat16 and half too.

2023-12-15 08:33 UTC, gbaned commented
Hi @SuryanarayanaY Can you please check @gaurides's [comments](https://github.com/tensorflow/tensorflow/pull/62502#pullrequestreview-1756354941) ? Thank you!

2023-12-29 08:58 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2024-01-08 12:33 UTC, gbaned commented
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

2024-02-07 01:46 UTC, closed without merging