validate axis argument of tf.squeeze
tensorflow/tensorflow pull request #62507
Opened 2023-11-30 06:59 UTC by SuryanarayanaY

In current implementation of `tf.squeeze`, if we pass a tensor for `axis` argument it will raise error like below, which is not inferable.

`MemoryError: std::bad_alloc`

This is due to the reason that the `Squeeze` Op expects `axis` as a `list` and there is no check for this in C++ level. Hence I am adding a validation check at Python level itself.

Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/06d4e539682780b4326a4f75f654a29e/62504.ipynb#scrollTo=NeGfeG5Jnhfn) also for reference.

Might fix #62504.

2023-11-30 17:16 UTC, cantonios approved these changes

2023-12-28 06:15 UTC, prasannarajezzzy approved these changes

2024-03-18 17:44 UTC, cantonios requested changes

2024-03-18 17:44 UTC, cantonios commented on tensorflow/python/ops/array_ops.py
> +  if type(axis) != list:
it looks like sometimes in production it is a tuple.

2024-05-25 01:48 UTC, closed without merging