]oneDNN]: Added support for quantized types in Enter and Exit ops on CPU
tensorflow/tensorflow pull request #62619
Opened 2023-12-11 20:52 UTC by bhavani-subramanian

Fixes https://github.com/tensorflow/tensorflow/issues/61761.

TF removed support for quantized types in `Enter` and `Exit` ops for CPU from r2.13. This causes issues when quantizing models such as Transformer-MLPerf using [Intel(R) Neural Compressor](url).

An example workflow for using these ops is as follows:
`Const (float32) -> Identity -> Enter (float32) -> MatMul` would be quantized into
`Const (qint8) -> Enter (qint8) -> QuantizedMatMul`
Here, the `Const` node refers to the weights input of `MatMul`.

This PR fixes the above issue by adding back registrations for quantized types in `Enter` and `Exit` ops.

2023-12-29 09:03 UTC, gbaned commented
Hi @penpornk Can you please review this PR ? Thank you!

2024-01-23 19:38 UTC, cantonios requested changes
Is there a test you can add to ensure we maintain support on CPU?

2024-01-25 23:27 UTC, bhavani-subramanian commented
@cantonios Thanks for reviewing this PR. I have addressed your review comments. Please take a look.

2024-01-25 23:42 UTC, cantonios approved these changes

2024-01-26 16:31 UTC, merged