New Features for TFLite Delegates accuracy and correctness tools
tensorflow/tensorflow pull request #62937
Opened 2024-02-10 20:51 UTC by robert-kalmar

The new features are: 

- **Option to use reference and test model for the evaluation tools.** This supports the cases, where the delegate does not perform inline model compilation for target compute IP but requires model to be preprocessed in advance.  For instance the workflow with Ethos-U NPU - the model is converted by Arm Vela tool, which replaces part of the compute graph with custom nodes recognized by the particular delegate. To evaluate the accuracy in this case one needs to supply both the reference and converted (test) model. The reference to be used with reference inference and test model with delegate. 
-  **Add support for int32 input/output**

2024-02-15 15:52 UTC, qukhan approved these changes

2024-06-19 13:14 UTC, qukhan requested changes

2024-06-19 13:14 UTC, qukhan commented on tensorflow/lite/tools/evaluation/stages/inference_profiler_stage.h
>        : EvaluationStage(config) {}
When this constructor is called, the tool fails when trying to initialize the `reference_stage_`.

The error is:
```
E0618 02:09:57.517596    3384 tflite_inference_stage.cc:109] TfliteInferenceParams not provided
tensorflow/lite/tools/evaluation/stages/inference_profiler_stage_test.cc:67: Failure
```

Maybe you need to initialize the reference config as it is done [here][1]?

[1]: https://github.com/tensorflow/tensorflow/pull/62937/files#diff-8e9daef4424254eca5ebca48cddcb99b8c2b2ae16a80dd817d396edfe1b02a57L83-L91

2024-07-09 10:57 UTC, keerthanakadiri commented
Hi @qukhan , Any update on this PR ? Please. Thank you!

2024-07-09 11:10 UTC, keerthanakadiri commented
Hi @@qukhan , Any update on this PR ? Please. Thank you!

2024-07-17 05:47 UTC, keerthanakadiri commented
Hi @robert-kalmar,  Can you please look into the [comment](https://github.com/tensorflow/tensorflow/pull/62937#discussion_r1646184784) from @qukhan

2024-08-19 01:55 UTC, closed without merging