Fix checkfail in Dilation2DBackpropInput & Dilation2DBackpropFilter
tensorflow/tensorflow pull request #63077
Opened 2024-02-28 07:22 UTC by SuryanarayanaY

`tf.raw_ops.Dilation2DBackpropInput` aborts at `out_backprop.tensor<T, 4>()`, if `out_backprop` rank!=4, due to lack of  rank check. Same things happen with tf.raw_ops.Dilation2DBackpropFilter.

Hence adding rank check of `out_backprop` in `ParseSizes` function that should work for both APIs.

Reference issue #62951 .

2024-02-28 17:38 UTC, sagunb commented on tensorflow/core/kernels/dilation_ops.cc
> +
nit: please remove trailing space

2024-02-28 17:54 UTC, mihaimaruseac commented on tensorflow/core/kernels/dilation_ops.cc
> +
```suggestion

```

2024-03-06 17:27 UTC, sagunb approved these changes
Thank you for the changes!

2024-03-06 18:11 UTC, mihaimaruseac requested changes

2024-03-07 05:48 UTC, SuryanarayanaY commented on tensorflow/core/kernels/dilation_ops.cc
> +              errors::InvalidArgument("out_backprop must be 4-dimensional",
Sure.Done.

2024-03-07 16:49 UTC, mihaimaruseac approved these changes

2024-04-10 05:27 UTC, gbaned approved these changes

2024-07-18 21:05 UTC, merged

2024-07-18 22:03 UTC, reedwm commented
Note when merging, I had to move and duplicate the check into the DilationBackpropInputOp and DilationBackpropFilterOp op kernels, since the ParseSizes function the check was originally is is also called by the forward-pass DilationOp op kernel.