Fix Checkfail in raw_ops.DecodeAndCropJpeg
tensorflow/tensorflow pull request #63071
Opened 2024-02-27 14:24 UTC by SuryanarayanaY

The API `tf.raw_ops.DecodeAndCropJpeg` can lead to assertion failure with -ve values passed to `crop_window` argument. This is true for only debug builds but not with TF official release wheels.

Proposed a fix for this.May please review.

2024-02-28 17:37 UTC, sagunb requested changes
Thank you for the changes! Just a minor nit for c style guide adherence.

2024-02-28 18:04 UTC, SuryanarayanaY commented on tensorflow/core/ops/image_ops.cc
> +        if (0 > crop_window_vec(2) || 0 > crop_window_vec(3)){
@sagunb , Done the changes.Thanks!

2024-03-01 07:13 UTC, SuryanarayanaY commented
@sagunb , Done the changes as suggested. Thanks!

2024-03-06 17:28 UTC, sagunb approved these changes
Thank you for the changes!

2024-11-05 17:16 UTC, mihaimaruseac commented
Closing this PR as it fails too many internal tests

2024-11-05 17:16 UTC, closed without merging