Expose DataTypeSize as TF_DataTypeSize in C API
tensorflow/tensorflow pull request #6309
Opened 2016-12-14 10:32 UTC by tsee

DataTypeSize is a greatly useful utility function for allocating the
right amount of memory when using the C API for (dynamic) language
wrappers using an FFI.

2016-12-15 07:52 UTC, tsee commented
NB: This is my first pull request to tensorflow. If I missed something in some style guide or otherwise, please let me know. If there's something I can do to make it easier to merge (What's with the various checks? Are this automated?), same thing, feedback welcome and I'm happy to try to do the leg work.

2016-12-16 01:30 UTC, martinwicke commented
@josh11b can you take a look or designate someone who can reason sensibly about the C API?

2016-12-16 01:38 UTC, josh11b requested changes
I think this would be a good addition to the C API; just a few things to take care of before we can get this in.

2016-12-16 01:38 UTC, josh11b commented on tensorflow/c/c_api.cc
> +int TF_DataTypeSize(TF_DataType dt) { return tensorflow::DataTypeSize(static_cast<DataType>(dt)); }
Please format this with the return statement on its own line.  We keep our C++ files to < 80 chars per line.

2016-12-16 01:38 UTC, josh11b commented on tensorflow/c/c_api.h
> +// to the given TF_DataType enum value. Returns 0 on failure.
Document what it does for variable-length types (currently only string).

2016-12-16 01:38 UTC, josh11b commented on tensorflow/c/c_api_test.cc
> +            tensorflow::DataTypeSize(tensorflow::DT_DOUBLE));
Could include a few more tests here?  At least TF_STRING and something invalid.

2016-12-16 01:38 UTC, josh11b commented on tensorflow/c/c_api.h
>  // --------------------------------------------------------------------------
I wouldn't have a divider here -- this is closely related to the TF_DataType definition.

2016-12-17 22:39 UTC, tsee commented
I force re-pushed the commit with the edits that @josh11b recommended. Let me know if this is good as is.

For reference, I also have no issues with somebody pushing a modified commit under their name - I'm not in it for the glory and this is as trivial a change as it gets.

2016-12-18 17:30 UTC, josh11b commented on tensorflow/c/c_api_test.cc
> +  ASSERT_EQ(TF_DataTypeSize(TF_STRING), 21312311);
Why is this an ASSERT instead of an EXPECT, and what is with the strange 21312311 value?

2016-12-18 19:08 UTC, tsee commented on tensorflow/c/c_api_test.cc
> +  ASSERT_EQ(TF_DataTypeSize(TF_STRING), 21312311);
Oh boy, I'm really sorry. That was a quick debugging statement left in. My son started nagging when I just about finished, so I rushed things more than I should have. 

Re-pushed without the bogus assert. Apologies.

2016-12-18 22:07 UTC, josh11b approved these changes

2016-12-18 23:06 UTC, martinwicke commented
Jenkins, test this please.

2016-12-20 00:02 UTC, jhseu commented
Let's make this a size_t return type? To match the mentioned conventions:
`// * size_t is used to represent byte sizes of objects that are
//   materialized in the address space of the calling process.`

2016-12-20 00:04 UTC, jhseu commented
@asimshankar fyi

2016-12-21 13:10 UTC, tsee commented
Completely agreed on the size_t change. I'd kept it consistent with the C++ API for an ill-advised sense of consistency and in case I was missing some hidden reason why it would be int. Repushed the branch.

2016-12-21 13:18 UTC, jhseu commented
Jenkins, test this please

2016-12-21 16:43 UTC, merged