training.slot_creator: support for non-fully-defined shaped vars
tensorflow/tensorflow pull request #6435
Opened 2016-12-21 09:33 UTC by albertz

This is a possible solution for #5972.

With this patch, the `AdamOptimizer` (and other optimizers) can optimize variables with non-fully-defined shape which would raise an exception without the patch because `primary.get_shape().as_list()` does not work.

2017-01-15 19:36 UTC, drpngx commented
@keveman any cycles for this?

2017-01-24 18:05 UTC, keveman approved these changes
LGTM.

2017-01-24 18:07 UTC, drpngx commented
Jenkins, test this please.

2017-01-24 18:08 UTC, vrv commented
Shouldn't we have a test for this?

2017-01-24 18:17 UTC, drpngx requested changes

2017-01-24 18:17 UTC, drpngx commented on tensorflow/python/training/slot_creator.py
> +  slot = variable_scope.get_variable(scope, initializer=val, trainable=False,
As per @vrv we should add some tests.

2017-01-24 18:17 UTC, drpngx commented
Good point.

2017-01-31 21:55 UTC, rmlarsen commented
@albertz could you add a unit test as requested by the reviewers?

2017-02-13 20:06 UTC, vrv commented
Closing due to conflicts + lack of update, to keep our list of open PRs small so they all get attention.  Please feel free to update and we can reopen, or send a brand new PR once you've addressed these comments.

2017-02-13 20:06 UTC, closed without merging