Write rules to construct headers for jpeg-turbo using existing templates.
tensorflow/tensorflow pull request #6462
Opened 2016-12-22 21:20 UTC by gunan

Fixes #6442 
Test build:
http://ci.tensorflow.org/view/Experimental/job/exp-win-bzl/8/console

`Had to use a few hacks to get this fully working.
Bazel did not allow me to add a `dict` type with a selecctor.
It even did not let me use a selector in `expand_template`'s substitutions field.
So I expanded the selector in genrule to accomodate simd/nosimd differences.

I think I can also get rid of my `expand_template.bzl` , and use `expand_header_template` in `llvm.bzl`.
But I am not sure how nice cross 3p usage. Maybe I can create a folder `third_party/skylark` and pull the skylark rules we are defining to that folder. Or simply `third_party/common.bzl`
Please let me know which looks nicer.

2016-12-22 22:46 UTC, gunan commented
All regular tests seem to have passed.
In windows, build has succeeded, but due to prolonged red build, some test failures are there.

2016-12-23 00:22 UTC, jhseu commented on third_party/jpeg/expand_template.bzl
> +def expand_template_impl(ctx):
Can we put this file in //third_party? I actually need it for something too.

2016-12-23 02:49 UTC, gunan commented
Done, now the expand template macro is under third_party:common.bzl
PTAL.

2016-12-23 21:23 UTC, jart requested changes

2016-12-23 21:23 UTC, jart commented on third_party/llvm/llvm.bzl
> -expand_header_template = rule(
Don't you need a load() statement at the top of this file now?

2016-12-23 21:23 UTC, jart commented on third_party/common.bzl
> +expand_header_template = rule(
Any chance we can rename this `template_rule`?

2016-12-23 21:38 UTC, gunan commented on third_party/jpeg/jpeg.BUILD
> +load("@//third_party:common.bzl", "expand_header_template")
I guess on that one, we do not really have an alternative option?
I think one thing we can do is to define these in either tensorflow/tensorflow.bzl, or move this file to tensorflow/common.bzl?

2016-12-23 21:43 UTC, jart commented on third_party/jpeg/jpeg.BUILD
> +load("@//third_party:common.bzl", "expand_header_template")
It's currently not possible for other Bazel projects to depend on TensorFlow for other reasons, such as our ./configure being mandatory. So the way I see it, we can just add issue 1248 to our list of blockers. We can fix this later.

2016-12-23 21:45 UTC, gunan commented on third_party/jpeg/jpeg.BUILD
> +        ":windows": "cp $(locations :jconfigint_win) $(@D)/jconfigint.h",
Done.
One more thing, it turns out if I use "jconfigint_nowin.h" in srcs, I have to refer to it the same way here as I do in srcs.

2016-12-23 21:45 UTC, gunan commented on third_party/common.bzl
> +expand_header_template = rule(
do you mean s/expand_header_template/template_rule/ ?

2016-12-23 21:46 UTC, gunan commented on third_party/jpeg/jpeg.BUILD
> +        ":jconfigint_win",
Done

2016-12-23 21:46 UTC, gunan commented on third_party/jpeg/jpeg.BUILD
> +        ":windows": "cp $(locations :jconfigint_win) $(@D)/jconfigint.h",
Done

2016-12-23 21:49 UTC, gunan commented on third_party/llvm/llvm.bzl
> -expand_header_template = rule(
not this specific file, but llvm.BUILD uses expand_header_template, so I added a load statement there.

2016-12-23 21:53 UTC, gunan commented on third_party/common.bzl
> +        "template": attr.label(mandatory=True, allow_files=True, single_file=True),
Done

2016-12-23 22:06 UTC, gunan commented on third_party/jpeg/jpeg.BUILD
> +            "#define SIZEOF_SIZE_T 8\n" +
Done.
It modified the indentation which looks more consistent with python style.
So I am happy with what buildifier did.

2016-12-23 22:11 UTC, gunan commented on third_party/jpeg/jpeg.BUILD
> +jconfig_nowin_common_substitutions = {
Done.

2016-12-23 22:11 UTC, gunan commented on third_party/jpeg/jpeg.BUILD
> +load("@//third_party:common.bzl", "expand_header_template")
Acknowledged.
Do you want me to leave a comment here about that?

2016-12-23 22:12 UTC, gunan commented on third_party/common.bzl
> +expand_header_template = rule(
Ping!
Wanted to bump this one.

2016-12-23 23:42 UTC, jart commented on third_party/jpeg/jpeg.BUILD
> +load("@//third_party:common.bzl", "expand_header_template")
Probably not worthwhile. We both know what needs to be done. We'll do it as soon as we can.

2016-12-23 23:42 UTC, jart commented on third_party/common.bzl
> +expand_header_template = rule(
Yes.

2016-12-23 23:44 UTC, jart approved these changes

2016-12-24 05:08 UTC, gunan commented on third_party/common.bzl
> +expand_header_template = rule(
Done

2016-12-24 05:09 UTC, gunan commented
All changes done.
Pending test results to merge.

2016-12-24 08:58 UTC, merged