Update configure.py to support pre-release versions of clang
tensorflow/tensorflow pull request #64673
Opened 2024-03-28 13:57 UTC by maflcko

Since commit 055e421c4004b60588de2d728cc51cdd749dd350, pre-release versions of clang may no longer be supported, if they are built from the llvm git and include the "git" suffix in their version message.

In this case, `retrieve_clang_version` will return `None`, which will then abort the program:

```
Traceback (most recent call last):
  File "configure.py", line 1466, in <module>
    main()
  File "configure.py", line 1417, in main
    disable_clang_offsetof_extension(clang_version)
  File "configure.py", line 886, in disable_clang_offsetof_extension
    if int(clang_version.split('.')[0]) in (16, 17):
AttributeError: 'NoneType' object has no attribute 'split'
```

Fix this by falling back to an assumed version. That is, treat 18.0.0git as 18.0.0. The warning will still be printed.

For context, an example `clang --version` excerpt:

```
clang version 18.0.0git (https://github.com/llvm/llvm-project.git ea3a3b25b93664c8be750ac3cd550855dcd1848b)

2024-04-26 11:33 UTC, gbaned commented
Hi @kanglant Can you please review this PR ? Thank you!

2024-06-07 16:57 UTC, gbaned commented
Hi @kanglant Can you please review this PR ? Thank you!

2024-06-07 17:23 UTC, kanglant requested changes
`.split('git')` will return a list of substrings. If the string contains a version number formatted as `18.0.0git`, you should extract the version number from the element at index 0. Could you update and test this change locally to see if it works as expected?

2024-06-18 12:46 UTC, kanglant approved these changes

2024-06-28 22:47 UTC, merged