Adding support for Linux s390x
tensorflow/tensorflow pull request #6681
Opened 2017-01-06 06:33 UTC by namrata-ibm

Adding support for Linux s390x for TensorFlow

2017-01-06 07:18 UTC, gunan commented
Thank you for recreating the PR.
CLA looks good.
Jenkins, test this please.

2017-01-06 17:32 UTC, gunan commented
Windows cmake test failure might be an issue on jenkins executor.
Jenkins, test this please.

2017-01-06 19:28 UTC, gunan commented
https://ci.tensorflow.org/job/tensorflow-pr-win-cmake-py/704/console

This time it failed for real. Could you take a look?

2017-01-07 18:09 UTC, namrata-ibm commented
The error is '__BYTE_ORDER__' and '__ORDER_BIG_ENDIAN__' are undeclared identifiers. However @guschmue had already committed the fix for BYTE_ORDER on windows through [PR](https://github.com/tensorflow/tensorflow/pull/6102). 
@gushmue could you please have a look?

2017-01-07 18:21 UTC, namrata-ibm commented
Do i need to explicitly include `tensorflow/core/platform/cpu_info.h` in the files where I am using the BYTE_ORDER flag?

2017-01-07 21:26 UTC, gunan commented
To me it looks like you definitely need to include `tensorflow/core/platform/cpu_info.h`. You also need to add a BUILD dependency for the library which exposes this header file.

2017-01-09 18:29 UTC, drpngx requested changes

2017-01-09 18:29 UTC, drpngx commented on tensorflow/core/framework/bfloat16.cc
> +  if (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__) {
Here and everywhere: we should probably use #if.

2017-01-09 18:29 UTC, drpngx commented on tensorflow/core/framework/bfloat16.cc
> +    for (; size; p += 2, q++, size--) {
I know it was in the original code, but please correct the style:
`size != 0`

2017-01-09 18:29 UTC, drpngx commented on tensorflow/core/kernels/cast_op.h
> +    static_assert(::tensorflow::port::kLittleEndian, "");
Sorry, while we're at it, could we add an error message to the assert here?

2017-01-09 18:29 UTC, drpngx commented on tensorflow/python/framework/tensor_util_test.py
> +import sys
Do you need this?

2017-01-09 18:29 UTC, drpngx commented on tensorflow/python/kernel_tests/cast_op_test.py
> +import sys
I don't think you need this.

2017-01-10 05:34 UTC, namrata-ibm commented on tensorflow/core/framework/bfloat16.cc
> +  if (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__) {
ok, we will work on this change.

2017-01-10 05:35 UTC, namrata-ibm commented on tensorflow/core/framework/bfloat16.cc
> +  if (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__) {
ok, we will work on this change.

2017-01-10 05:37 UTC, namrata-ibm commented on tensorflow/python/framework/tensor_util_test.py
> +import sys
We need to import sys as we are using 'sys.byteorder' to detect endianness of underlying platform.

2017-01-10 05:37 UTC, namrata-ibm commented on tensorflow/python/framework/tensor_util_test.py
> +import sys
We need to import sys as we are using 'sys.byteorder' to detect endianness of underlying platform.

2017-01-10 05:38 UTC, namrata-ibm commented on tensorflow/python/kernel_tests/cast_op_test.py
> +import sys
We need to import sys as we are using 'sys.byteorder' to detect endianness of underlying platform.

2017-01-10 05:38 UTC, namrata-ibm commented on tensorflow/core/framework/bfloat16.cc
> +    for (; size; p += 2, q++, size--) {
ok

2017-01-10 05:39 UTC, namrata-ibm commented on tensorflow/core/kernels/cast_op.h
> +    static_assert(::tensorflow::port::kLittleEndian, "");
ok

2017-01-10 17:51 UTC, drpngx commented
Sounds good, will merge once the build is restored.

2017-01-10 17:52 UTC, drpngx commented
09:39:59          c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\tensorflow\core\framework\bfloat16.cc(23): error C2065: '__BYTE_ORDER__': undeclared identifier [C:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build\tf_core_framework.vcxproj]
09:39:59          c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\tensorflow\core\framework\bfloat16.cc(23): error C2065: '__ORDER_BIG_ENDIAN__': undeclared identifier [C:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build\tf_core_framework.vcxproj]
09:39:59          c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\tensorflow\core\framework\bfloat16.cc(37): error C2065: '__BYTE_ORDER__': undeclared identifier [C:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build\tf_core_framework.vcxproj]
09:39:59          c:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\tensorflow\core\framework\bfloat16.cc(37): error C2065: '__ORDER_BIG_ENDIAN__': undeclared identifier [C:\tf_jenkins\home\workspace\tensorflow-pr-win-cmake-py\cmake_build\tf_core_framework.vcxproj]

2017-01-11 09:58 UTC, namrata-ibm commented
@drpngx, I have made changes as per your feedback. 
@gunan, `cpu_info.h` has been included in all respective files and as a BUILD dependency. 
Could you request a build to verify?

2017-01-11 16:06 UTC, drpngx commented
Jenkins, test this please.

2017-01-11 16:16 UTC, drpngx commented
Please put the `cpu_info` alphabetically sorted in `tensorflow/core/BUILD`

2017-01-11 17:35 UTC, drpngx commented
Jenkins, test this please.

2017-01-11 20:04 UTC, merged