update Defun doc
tensorflow/tensorflow pull request #6835
Opened 2017-01-13 18:16 UTC by yaroslavvb

Fixes #6804

2017-01-13 18:21 UTC, drpngx approved these changes

2017-01-13 18:21 UTC, drpngx commented
Jenkins, test this please.

2017-01-13 19:26 UTC, zffchen requested changes
Thank you for the update, Yaralsav.

2017-01-13 19:26 UTC, zffchen78 commented on tensorflow/python/framework/function.py
> +  Definitions of function is frozen for the session after first session.run
How about

Definitions of functions are frozen in a graph as soon as the graph is used to create a session.
Therefore, nodes using the function must be created in the graph before the corresponding session
is created.  

Maybe then add an example.

2017-01-14 19:44 UTC, yaroslavvb commented on tensorflow/python/framework/function.py
> +  Definitions of function is frozen for the session after first session.run
That doesn't seem to match current behavior -- I can create a session, then create function node, and then issue first session.run and it works, still want me to change it to that?

2017-01-24 21:10 UTC, drpngx commented
We need to wait two weeks on that one, sorry about that.

2017-01-31 21:47 UTC, rmlarsen commented
@zffchen78 @drpngx Do you have additional comments? Can we merge this or are we still in the two week waiting period mentioned above?

2017-01-31 22:39 UTC, yaroslavvb commented
changed to the wording suggested by zf

2017-01-31 22:40 UTC, rmlarsen commented
Thanks @yaroslavvb. @zffchen78 can you take another look, please?

2017-02-10 09:45 UTC, zffchen approved these changes

2017-02-12 18:56 UTC, drpngx commented
Jenkins, test this please.

2017-02-12 23:47 UTC, merged