Updated  tensorflow/tensorflow/lite/python/lite.py with grammatical a…
tensorflow/tensorflow pull request #69756
Opened 2024-06-14 07:32 UTC by LakshmiKalaKadali

Updated  tensorflow/tensorflow/lite/python/lite.py with grammatical and typo corrections. The TFLiteConverter API link:https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter

2024-07-21 08:32 UTC, gbaned approved these changes

2024-07-21 14:05 UTC, mihaimaruseac requested changes

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

Please revert this edit. The format of `Returns:` is a description of the returned value, as a noun phrase. It should be read as "this function returns the converted data in serialized format", but with your edit it gets to "this function returns the converted data is in serialized format"

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

Same here

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format. Either a TFLite Flatbuffer or
```suggestion
      The converted data in serialized format, either a TFLite Flatbuffer or
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format. Either a TFLite Flatbuffer or
```suggestion
      The converted data in serialized format, either a TFLite Flatbuffer or
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format.
```suggestion
      The converted data in serialized format.
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format. Either a TFLite Flatbuffer or
```suggestion
      The converted data in serialized format, either a TFLite Flatbuffer or
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format. Either a TFLite Flatbuffer or
```suggestion
      The converted data in serialized format, either a TFLite Flatbuffer or
```

2024-07-21 14:05 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +      The converted data is in serialized format. Either a TFLite Flatbuffer or
```suggestion
      The converted data in serialized format, either a TFLite Flatbuffer or
```

2024-07-21 14:09 UTC, mihaimaruseac approved these changes

2024-07-26 01:18 UTC, mihaimaruseac requested changes

2024-07-26 01:18 UTC, mihaimaruseac commented on tensorflow/lite/python/lite.py
> +          "tf.int8 or tf.uint8. Currently `inference_type={}` and "
```suggestion
          "tf.int8 or tf.uint8. Currently, `inference_type={}` and "
```

Comma was correct here, removing it causes tests to fail

2024-07-26 01:20 UTC, mihaimaruseac approved these changes

2024-07-26 03:04 UTC, merged