enable hdfs support for windows
tensorflow/tensorflow pull request #6987
Opened 2017-01-20 22:47 UTC by guschmue

2017-01-21 01:14 UTC, caisq commented
@tensorflow-jenkins test this please

2017-01-21 01:20 UTC, mrry commented
Thanks for adding this, Guenther! The change looks good to me, assuming the tests pass.

I assume none of our automated tests use this because of the Hadoop distribution dependency. Have you confirmed that it works manually as expected?

2017-01-21 01:21 UTC, mrry approved these changes

2017-01-21 01:40 UTC, guschmue commented
yes, I tested this against hadoop 2.6.4 running on a linux box. 
Tried to read files for training as well as save() / restore() - worked all ok (actually cool that gfile works).
The biggest hurdle is that you need the hadoop binaries on the windows side and there is no good binary distribution.

2017-01-21 02:00 UTC, jhseu requested changes

2017-01-21 02:00 UTC, jhseu commented on tensorflow/core/platform/hadoop/hadoop_file_system.cc
> +#define LIBHDFS_DSO "hdfs.dll"
Nit: mind changing these to `const char* kLibHdfsDso = "..."`?

2017-01-21 03:22 UTC, guschmue commented on tensorflow/core/platform/hadoop/hadoop_file_system.cc
> +#define LIBHDFS_DSO "hdfs.dll"
sure, will do

2017-01-23 23:34 UTC, jhseu approved these changes

2017-01-24 01:18 UTC, caisq commented
@tensorflow-jenkins test this please

2017-01-24 17:22 UTC, caisq commented
The test timeout in "Linux CPU Tests (Python 3)" seems to be an unrelated flake. Merging the PR now.

2017-01-24 17:23 UTC, merged

2017-01-24 17:24 UTC, caisq commented
PR merged. Thanks, @guschmue and reviewers.

2017-02-07 06:38 UTC, snnn commented
Some notes for windows users:
1. jvm.dll need be in PATH dirs.
set PATH=%PATH%;%JAVA_HOME%\jre\bin\server

2.  Wildcards in Classpath do not work. This is a limitation of JNI. Please set classpath in this way:
hadoop classpath --jar c.jar
set CLASSPATH=c.jar

2017-02-09 15:16 UTC, guschmue commented
I think this is very helpful for people trying to setup hdfs on windows. Let me see if I can add this to the hdfs howto.

2017-02-10 02:37 UTC, snnn commented
@guschmue Sure. Please do it.