[TOSA] support tfl.batch_matmul with input broadcasting
tensorflow/tensorflow pull request #70679
Opened 2024-07-01 09:21 UTC by psunn

add support of unequal rank inputs with broadcasting in `TFL_BatchMatMulOp` lowering to `tosa.matmul`

example:
In the case of `batch_matmul` with broadcasting:
```
%0 = "tfl.batch_matmul"(%arg0, %arg1) {...} : (tensor<2x3x4x5x6xf32>, tensor<4x6x5xf32>) -> tensor<2x3x4x5x5xf32>
```

broadcast `tensor<4x6x5xf32>`  to `tensor<2x3x4x6x5xf32>` in 4 operations:
```
%0 = tosa.const_shape  {value = dense<[1, 1, 4, 6, 5]> : tensor<5xindex>} : () -> !tosa.shape<5>
%4 = "tosa.const"() <{value = dense<-0.000000e+00> : tensor<2x3x4x6x5xf32>}
%5 = tosa.reshape %arg1, %0 : (tensor<4x6x5xf32>, !tosa.shape<5>) -> tensor<1x1x4x6x5xf32>
%6 = tosa.add %5, %4 : (tensor<1x1x4x6x5xf32>, tensor<2x3x4x6x5xf32>) -> tensor<2x3x4x6x5xf32>
```

2024-07-03 05:32 UTC, keerthanakadiri commented
Hi @rdzhabarov Can you please review this PR? Thank you .

2024-07-23 06:13 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you .

2024-08-06 09:39 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you !

2024-08-20 06:07 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you !

2024-08-27 06:46 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you !

2024-09-03 11:30 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you !

2024-09-18 08:45 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you !

2024-10-09 06:15 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you !

2024-10-23 09:50 UTC, keerthanakadiri commented
Hi @rdzhabarov, Can you please review this PR? Thank you !

2025-02-05 15:42 UTC, leandron commented
@psunn can you update this to solve the conflicts, so that we can review this again, please?

2025-02-05 15:42 UTC, leandron requested changes
@psunn can you update this to solve the conflicts, so that we can review this again, please?

2025-02-10 06:47 UTC, keerthanakadiri commented
Hi @psunn, Can you please resolve the conflicts? Thank you!

2025-03-04 10:15 UTC, psunn commented
@keerthanakadiri 
I just updated this PR and resolved the conflicts, could you help to remove the `stale` lable? Thanks in advance.

2025-03-04 22:05 UTC, psunn commented
ran TOSA LIT tests locally:

```
INFO: Analyzed 33 targets (2 packages loaded, 33375 targets configured).
INFO: Found 16 targets and 17 test targets...
INFO: Elapsed time: 236.212s, Critical Path: 167.70s
INFO: 980 processes: 68 internal, 912 local.
INFO: Build completed successfully, 980 total actions
//tensorflow/compiler/mlir/tosa/tests:convert-tfl-uint8.mlir.test        PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:convert_metadata.mlir.test         PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:fuse-bias-tf.mlir.test             PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:lower-complex-types.mlir.test      PASSED in 0.6s
//tensorflow/compiler/mlir/tosa/tests:multi_add.mlir.test                PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:retain_call_once_funcs.mlir.test   PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:strip-quant-types.mlir.test        PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:strip_metadata.mlir.test           PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:tf-tfl-to-tosa-pipeline.mlir.test  PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:tf-to-tosa-pipeline.mlir.test      PASSED in 0.7s
//tensorflow/compiler/mlir/tosa/tests:tf-unequal-ranks.mlir.test         PASSED in 0.3s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-dequantize_softmax.mlir.test PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-pipeline-filtered.mlir.test PASSED in 0.5s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-pipeline.mlir.test     PASSED in 3.9s
//tensorflow/compiler/mlir/tosa/tests:tfl-to-tosa-stateful.mlir.test     PASSED in 0.6s
//tensorflow/compiler/mlir/tosa/tests:tfl-unequal-ranks.mlir.test        PASSED in 0.4s
//tensorflow/compiler/mlir/tosa/tests:verify_fully_converted.mlir.test   PASSED in 0.4s
```

2025-03-04 23:16 UTC, Jerry-Ge commented on tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
> +Value reshapeScalarTo1D(PatternRewriter& rewriter, Location loc, Value value);
why moved this function?

2025-03-04 23:45 UTC, Jerry-Ge approved these changes
overall looks good, minor question. 

Thanks for the PR!

2025-03-05 10:55 UTC, psunn commented on tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
> +Value reshapeScalarTo1D(PatternRewriter& rewriter, Location loc, Value value);
There was a merge conflict between `reshapeScalarTo1D` and `broadcastLowRankTensor`. It has been resolved by aligning the order of these two functions in both the source and header files.

2025-03-06 10:42 UTC, leandron approved these changes
LGTM, thanks @psunn for the PR and @Jerry-Ge for the reviews.

2025-03-06 10:43 UTC, merged