improved and fix bug of getting next batch in mnist
tensorflow/tensorflow pull request #7071
Opened 2017-01-25 19:12 UTC by LaurenLuoYun

The original codes do not consider the situation that when the batch_size > num_examples (even though it is not a common event, if happens, no new data will be input at all).

Actually, a fully epoch means that all examples have been applied once, however, the original codes do not show it. If the batch_size sets just a little bit larger than half of the example number, nearly half of the examples cannot be used in one epoch.

Also, I set the shuffle to be a input variable.

2017-01-30 19:35 UTC, rmlarsen requested changes

2017-01-30 19:35 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    if self._epochs_completed ==0 and start == 0 and shuffle:
Add space after ==

2017-01-30 19:35 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    if start+batch_size > self._num_examples:
add space around +

2017-01-30 19:35 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    if self._epochs_completed ==0 and start == 0 and shuffle:
This changes the semantics by shuffling before the first epoch. Is that intentional? Is it necessary?

2017-01-30 19:35 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +      self._index_in_epoch = batch_size-rest_num_examples
space around '-'

2017-01-30 19:35 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    """ Get next batch """
Get rid of leading and training space. Add period at end.

2017-01-30 19:35 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-01-31 07:19 UTC, LaurenLuoYun commented
@rmlarsen I've already normalized the format, thank you so much and pls check the new pr(43e7a40) again.

2017-01-31 07:24 UTC, LaurenLuoYun commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    """ Get next batch """
OK , fixed.

2017-01-31 07:24 UTC, LaurenLuoYun commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    if self._epochs_completed ==0 and start == 0 and shuffle:
OK , fixed.

2017-01-31 07:25 UTC, LaurenLuoYun commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    if self._epochs_completed ==0 and start == 0 and shuffle:
I think it necessary. If not necessary, the shuffle variable can be set to False.

2017-01-31 07:26 UTC, LaurenLuoYun commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +    if start+batch_size > self._num_examples:
OK , fixed.

2017-01-31 07:26 UTC, LaurenLuoYun commented on tensorflow/contrib/learn/python/learn/datasets/mnist.py
> +      self._index_in_epoch = batch_size-rest_num_examples
OK , fixed.

2017-01-31 07:30 UTC, LaurenLuoYun commented
@tensorflow-jenkins Follow by the agsignee's instruction, I've change some format of the code. Please test again . Thank you.

2017-01-31 21:34 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-01-31 21:36 UTC, rmlarsen commented
Thanks for the update. I'll merge this once the  tests pass.

2017-02-01 03:45 UTC, LaurenLuoYun commented
@rmlarsen the jenkins test shows that Windows Cmake Tests failure, but I do not fully understand the reason from the output console.

2017-02-01 17:46 UTC, rmlarsen approved these changes

2017-02-01 17:46 UTC, rmlarsen commented
The cmake error is unrelated. Thanks for the contribution. I'll merge it now.

2017-02-01 17:47 UTC, merged