Adding checks for broken bottleneck files
tensorflow/tensorflow pull request #7131
Opened 2017-01-29 10:11 UTC by rizasif

An exception is raised when a broken cached bottleneck files is read. Such a file can be created as a result of sudden system failure. 

This commit refers the issue #2296 (https://github.com/tensorflow/tensorflow/issues/2296). Although closed but the problem still persists. Please view comments by @rizasif92 at the end. The changes contain nothing but error handling.

2017-01-29 10:21 UTC, rizasif commented
I signed it!

2017-01-30 21:41 UTC, petewarden requested changes
Thanks @rizasif , I really appreciate you putting this fix together! Could I request a slightly different approach though? I would prefer to keep the get_or_create_bottleneck() function always returning a bottleneck.

To ensure that, we could move the section nested inside the `if not os.path.exists(bottleneck_path):` condition into a new function, `create_bottleneck_file`. Then we can call it from that condition, but also have a flag that catches float exceptions when reading and calls it in that case too. Here's some untested code to try and show what I mean:

```
  if not os.path.exists(bottleneck_path):
    create_bottleneck_file(...)
  did_hit_error = False
  try:
    bottleneck_values = [float(x) for x in bottleneck_string.split(',')]
  except:
    print("Invalid float found, recreating bottleneck")
    did_hit_error = True
  if did_hit_error:
    create_bottleneck_file(...)
    # Allow exceptions to propagate here, since they shouldn't happen after a fresh creation
    bottleneck_values = [float(x) for x in bottleneck_string.split(',')]
```
I'm hoping with this approach none of the other changes outside this function should be needed since the contract to always return a list of bottleneck values is preserved.

Does that make sense?

2017-01-31 13:36 UTC, rizasif commented
@petewarden I agree with your solution and was thinking to implement it. I have made the changes as suggested, and tested them as well; I am attaching a screenshot of the output. Kindly review and let me know if anything else is required.
Thank you :)

![capture](https://cloud.githubusercontent.com/assets/8410351/22466834/dae8d6f2-e7e3-11e6-978c-6ebe8fc2a617.PNG)

2017-02-01 10:45 UTC, petewarden requested changes
This looking great, thanks for the updates! I have a couple of minor comments, but once those are addressed this looks good to go in.

2017-02-01 10:45 UTC, petewarden commented on tensorflow/examples/image_retraining/retrain.py
> -      filenames.append(image_name)
I think we should put this line back?

2017-02-01 10:45 UTC, petewarden commented on tensorflow/examples/image_retraining/retrain.py
> -        ground_truth = np.zeros(class_count, dtype=np.float32)
Can we revert this change, since now the bottlenecks will never be None?

2017-02-01 11:18 UTC, rizasif commented
@petewarden done

2017-02-01 17:35 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-02-01 21:31 UTC, rmlarsen commented
@rizasif it looks like you added some 4 character indents, which breaks the sanity check. TF uses 2 character indents. Please fix.

2017-02-01 22:40 UTC, rizasif commented
Indentation changes made, kindly re-run the tests. Thanks :)

2017-02-02 06:07 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-02-02 06:09 UTC, rmlarsen commented
Thanks @rizasif. @petewarden can you take another look? If the logics right to you, approve and I'll get it merged.

2017-02-02 09:21 UTC, petewarden approved these changes
This looks great, thanks!

2017-02-02 10:51 UTC, rizasif commented
Did the tests pass? :/

2017-02-02 17:07 UTC, rmlarsen commented
@rizasif it looks like you still have some bad indents, e.g.

FAIL: Found 1 non-whitelited pylint errors:
tensorflow/examples/image_retraining/retrain.py:353: [E0001(syntax-error), ] unexpected indent

2017-02-02 17:46 UTC, rizasif commented
@rmlarsen the code seems to be working at my end; so we might have to do this a few more times to resolve these indentation issues. I hope this commit works fine. @tensorflow-jenkins please test :)

2017-02-03 17:28 UTC, rmlarsen commented
@rizasif Thanks :) 

@tensorflow-jenkins test this please

2017-02-03 18:41 UTC, merged

2017-02-03 18:41 UTC, rmlarsen commented
@rizasif thanks for the contribution!

2017-02-03 21:03 UTC, rizasif commented
Pleasure's all mine @rmlarsen 
Thank you so much for all the support. Hope to see you guys again. Take Care :)