Update proto library reference and make curl forward/backward compatible
tensorflow/tensorflow pull request #7165
Opened 2017-01-31 15:12 UTC by kchodorow

I'm working on fixing https://github.com/bazelbuild/bazel/issues/1681, which
will change the way Bazel organizes the execution root.  This has two
implications for tensorflow:

* The protobuf library needs to be updated to a version that works with
old/new versions of Bazel (older versions won't be able to find
external protos).
* The curl library needs to use ../curl as an include prefix in new
versions of Bazel and external/curl in old versions.

This patch should be forward/backward compatible.

2017-01-31 17:57 UTC, jart requested changes

2017-01-31 17:57 UTC, jart commented on tensorflow/workspace.bzl
> +def _curl_repo_impl(ctx):
Would it be possible to refactor this to use `temp_workaround_http_archive` in workspace.bzl?

2017-01-31 17:57 UTC, jart commented on tensorflow/workspace.bzl
> +  return Label("@foo//bar").workspace_root.startswith("../")
FYI: This function might need to be updated too: https://github.com/bazelbuild/rules_closure/blob/master/closure/private/defs.bzl#L135

2017-01-31 20:08 UTC, kchodorow commented on tensorflow/workspace.bzl
> +def _curl_repo_impl(ctx):
Done.

2017-01-31 20:08 UTC, kchodorow commented on tensorflow/workspace.bzl
> +  return Label("@foo//bar").workspace_root.startswith("../")
Good call.  I'll check that and let you know.  Added it to my tracking doc.

2017-02-01 17:26 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-02-01 17:27 UTC, rmlarsen commented
@jart is this good to go?

2017-02-01 18:27 UTC, kchodorow commented on tensorflow/workspace.bzl
> +  return Label("@foo//bar").workspace_root.startswith("../")
Created https://github.com/bazelbuild/rules_closure/pull/184 to fix this, btw.

2017-02-01 18:29 UTC, jart approved these changes

2017-02-01 18:29 UTC, jart commented
My name is Justine Tunney and I approve this pull request.

2017-02-02 06:17 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-02-02 16:37 UTC, kchodorow commented
I'm having trouble getting these tests to pass, even without my changes.  Is there anything in particular I need to set up to get, say, Linux CPU Tests working?  I've got a vanilla TF setup without my changes and I'm getting (for example, with `bazel test //tensorflow/contrib/factorization/examples:mnist`):

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kchodorow/.cache/bazel/_bazel_kchodorow/d39e1471d317a89f747169f52aae8653/execroot/clean_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/factorization/examples/mnist.runfiles/org_tensorflow/tensorflow/contrib/factorization/examples/mnist.py", line 36, in <module>
    import tensorflow as tf
  File "/home/kchodorow/.cache/bazel/_bazel_kchodorow/d39e1471d317a89f747169f52aae8653/execroot/clean_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/factorization/examples/mnist.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/kchodorow/.cache/bazel/_bazel_kchodorow/d39e1471d317a89f747169f52aae8653/execroot/clean_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/factorization/examples/mnist.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 124, in <module>
    from tensorflow.python.platform import test
  File "/home/kchodorow/.cache/bazel/_bazel_kchodorow/d39e1471d317a89f747169f52aae8653/execroot/clean_tensorflow/bazel-out/local-opt/bin/tensorflow/contrib/factorization/examples/mnist.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 83, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock
```

2017-02-02 17:30 UTC, rmlarsen commented
@kchodorow: I notice that this import is conditional on the version: 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/test.py#L82

Could this check be wrong?

2017-02-02 18:16 UTC, kchodorow commented
Ah, I didn't have mock installed!  `sudo pip install mock` made it pass.  Unfortunately, now it passes for me locally both with and without my change (gah!).  Is there a way to see the Bazel tests logs Jenkins generates (so I can see what, specifically, made these things fail)?

2017-02-02 19:00 UTC, rmlarsen commented
@kchodorow Click on "Console Output" link for the tests here:

https://ci.tensorflow.org/job/tensorflow-pull-requests-multijob/3566/

For the full log, click on the "Full Log" line at the top of the individual console output pages. They are very verbose, but searching for "Failure" usually does the trick.

2017-02-08 15:58 UTC, jart approved these changes

2017-02-08 16:11 UTC, jart commented
Mr. Jenkins test this please

2017-02-09 15:23 UTC, kchodorow commented
Okay, rebased my change on top of @jhseu's fix, so now it only updates the curl library.  Could you try triggering the Jenkins build again (hopefully for the last time)?

2017-02-09 18:50 UTC, jhseu commented
Jenkins, test this please

2017-02-09 20:19 UTC, kchodorow commented
Horay!!!!

2017-02-10 15:32 UTC, kchodorow commented
Friendly ping: could someone merge this in when you get a chance?

2017-02-11 09:16 UTC, merged