Catch dnn_hidden_units to avoid obsture error message
tensorflow/tensorflow pull request #7176
Opened 2017-02-01 02:39 UTC by terrytangyuan

Not providing `dnn_hidden_units` in for dnn linear combined model would cause the following error message that's not useful for users.

```
Type'NoneType' object is not iterable
```

2017-02-01 05:02 UTC, terrytangyuan commented
Test failure due to timeout. Will be fixed in #7180

2017-02-01 17:17 UTC, rmlarsen requested changes

2017-02-01 17:17 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py
> +        exports_to_keep=exports_to_keep)
Please add a newline at the end of the file.

2017-02-01 17:21 UTC, terrytangyuan commented
@rmlarsen Done. Thanks!

2017-02-01 17:24 UTC, rmlarsen commented on tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py
> +      raise ValueError(
Could you add a unit test for this?

2017-02-01 17:25 UTC, rmlarsen requested changes
Could you add a unit test for the new exception?

2017-02-02 03:29 UTC, terrytangyuan commented on tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py
> +      raise ValueError(
Good call. Added.

2017-02-02 06:01 UTC, rmlarsen approved these changes

2017-02-02 06:02 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-02-02 14:57 UTC, terrytangyuan commented
Seems like an irrelevant issue that Martin is fixing

2017-02-02 17:51 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-02-02 19:14 UTC, merged