[Tosa] Add support for legalizing scatter_nd
tensorflow/tensorflow pull request #72370
Opened 2024-07-23 15:35 UTC by lhutton1

This commit legalizes tf(l).scatter_nd to tosa.scatter in a similar approach to the existing gather_nd support. Specifically, inputs are rewritten to the expected formats by tosa.scatter and finally the output of tosa.scatter is reshaped to the expected output of scatter_nd.

tosa.scatter does not support duplicated indices while TF does. Therefore, we restrict legalization of scatter_nd to a constant indices tensor only and check that the provided indices are unique.

2024-07-30 06:17 UTC, keerthanakadiri commented
Hello @[rdzhabarov](https://github.com/rdzhabarov) , Can you please review this PR? Thank you !

2024-08-12 09:09 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2024-08-20 05:42 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2024-08-27 06:41 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2024-09-02 07:32 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2024-09-17 04:14 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2024-09-23 09:38 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2024-10-01 06:07 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2024-10-09 06:04 UTC, keerthanakadiri commented
Hi @rdzhabarov , Can you please review this PR? Thank you !

2025-02-05 15:39 UTC, leandron requested changes
@lhutton1 can you rebase and solve the conflicts on this PR so that we can review, please?

2025-02-10 06:44 UTC, keerthanakadiri commented
Hi @lhutton1, Can you please resolve the conflicts? Thank you!

2025-02-13 15:53 UTC, ekalda commented on tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
> +bool checkUniqueConstantScatterIndices(ShapedType indices_type,
I suppose "negative tests" are not a thing in TF, i.e. there wouldn't be a way to test that the logic in this function produces correct behaviour in the case of overlapping indices?

2025-02-26 22:31 UTC, Jerry-Ge commented
I did a local build and test. Hit the following errors. Need to rebase @lhutton1 

```
ERROR: /staging/tensorflow/tensorflow/compiler/mlir/tosa/BUILD:74:11: Compiling tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc failed: (Exit 1): clang failed: error executing command (from target //tensorflow/compiler/mlir/tosa:legalize_common) /usr/lib/llvm-14/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 ... (remaining 263 arguments skipped)
In file included from tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc:24:
In file included from ./tensorflow/compiler/mlir/tosa/transforms/legalize_common.h:21:
In file included from external/llvm-project/mlir/include/mlir/IR/PatternMatch.h:12:
external/llvm-project/mlir/include/mlir/IR/Builders.h:507:11: error: no matching member function for call to 'build'
    OpTy::build(*this, state, std::forward<Args>(args)...);
    ~~~~~~^~~~~
external/llvm-project/mlir/include/mlir/IR/ImplicitLocOpBuilder.h:67:23: note: in instantiation of function template specialization 'mlir::OpBuilder::create<mlir::tosa::ReshapeOp, mlir::Type &, mlir::Value &, mlir::detail::DenseArrayAttrImpl<int64_t> &>' requested here
    return OpBuilder::create<OpTy>(curLoc, std::forward<Args>(args)...);
                      ^
external/llvm-project/mlir/include/mlir/Dialect/Tosa/Utils/ConversionUtils.h:94:21: note: in instantiation of function template specialization 'mlir::ImplicitLocOpBuilder::create<mlir::tosa::ReshapeOp, mlir::Type &, mlir::Value &, mlir::detail::DenseArrayAttrImpl<int64_t> &>' requested here
  auto op = builder.create<TosaOp>(resultTy, args...);
                    ^
external/llvm-project/mlir/include/mlir/Dialect/Tosa/Utils/ConversionUtils.h:205:10: note: in instantiation of function template specialization 'mlir::tosa::(anonymous namespace)::createOpAndInferShape<mlir::tosa::ReshapeOp, mlir::Value &, mlir::detail::DenseArrayAttrImpl<int64_t> &>' requested here
  return createOpAndInferShape<TosaOp>(builder, resultTy, args...);
         ^
./tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h:226:10: note: in instantiation of function template specialization 'mlir::tosa::CreateOpAndInferShape<mlir::tosa::ReshapeOp, mlir::Value &, mlir::detail::DenseArrayAttrImpl<int64_t> &>' requested here
  return CreateOpAndInferShape<TosaOp>(builder, result_ty, args...);
```

2025-03-10 13:28 UTC, leandron commented
@lhutton1 friendly ping to update this PR.

2025-04-04 09:28 UTC, lhutton1 commented on tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
> +bool checkUniqueConstantScatterIndices(ShapedType indices_type,
added testcase

2025-04-07 08:31 UTC, lhutton1 commented
friendly ping for review

2025-04-07 18:19 UTC, Jerry-Ge commented on tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
> +  // DenseI64ArrayAttr indices_matrix_shape_attr = rewriter.getDenseI64ArrayAttr(
forgot to remove?

2025-04-07 18:22 UTC, Jerry-Ge reviewed
looks good, some minor comments.

2025-04-07 18:41 UTC, lhutton1 commented on tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
> +  // DenseI64ArrayAttr indices_matrix_shape_attr = rewriter.getDenseI64ArrayAttr(
done, thanks!

2025-04-07 18:42 UTC, Jerry-Ge approved these changes
LGTM, thanks for the PR

2025-04-08 08:34 UTC, leandron approved these changes
LGTM, thanks @lhutton1 and all for the reviews

2025-04-08 08:34 UTC, merged