Remove all Python unit test files from PIP package
tensorflow/tensorflow pull request #7252
Opened 2017-02-03 21:52 UTC by caisq

Chaser

2017-02-03 23:09 UTC, rmlarsen commented on tensorflow/tools/pip_package/build_pip_package.sh
> +  # rm -rf ${TMPDIR}
Cruft?

2017-02-03 23:56 UTC, gunan commented
It is possible due to recent issues pip tests are disabled in presubmits. Could you setup an experimental build and run any pip tests, @caisq ?

2017-02-04 02:44 UTC, caisq commented on tensorflow/tools/pip_package/build_pip_package.sh
> +  # rm -rf ${TMPDIR}
Fixed now.

2017-02-04 02:46 UTC, caisq commented
@gunan, I (kind of) did that already. See the original PR comment. But that particular build timed out at 90 minutes. I increased the timeout to 120 minutes and kicked off another one:

http://ci.tensorflow.org/view/Experimental/job/experimental-cais-linux-python35-pip/7/console

2017-02-04 04:19 UTC, caisq commented
To quantify the reduction in the PIP wheel file size (in bytes, for Python 3.5):
Before: 43691027
After: 43507664
About 180 kB (0.5% reduction).

Not as much as one would expect :)  But it gets rid of 175 unnecessary files and about 2.5 MB disk space when installed.

2017-02-04 05:41 UTC, gunan commented
Change mostly looks good.
Would this lead to any changes in public API?

2017-02-04 05:57 UTC, martinwicke commented
I am not a fan of how this is done -- can we instead put this exception into the build_pip_package rule? Otherwise we have another point at which to control what goes into the pip package -- we already have too many.

2017-02-04 05:58 UTC, martinwicke requested changes

2017-02-04 05:58 UTC, martinwicke commented on tensorflow/tools/pip_package/build_pip_package.sh
> +  rm -f $(find ./ -name '*_test.py')
I would much rather we adjust the dependencies of the build_pip_package rule instead. We already have too many point at which we control what goes into that package.

2017-02-04 20:57 UTC, caisq commented on tensorflow/tools/pip_package/build_pip_package.sh
> +  rm -f $(find ./ -name '*_test.py')
I agree this is not the most elegant. Let me work on this a little more.

2017-02-10 18:50 UTC, caisq commented
I'll close this for now. There is a related issue of unnecessary include header files in the pip package. I'll reopen the PR again when I have a more elegant fix for both issues.

2017-02-10 18:50 UTC, closed without merging