Added example usage in some functions of config.py
tensorflow/tensorflow pull request #72863
Opened 2024-07-31 05:35 UTC by LakshmiKalaKadali

Some example usage are added to the systemconfig.py: for get_lib(), get_build_info, get_include()

2024-08-06 09:14 UTC, keerthanakadiri approved these changes

2025-01-31 07:00 UTC, keerthanakadiri approved these changes

2025-01-31 16:24 UTC, mihaimaruseac requested changes

2025-01-31 16:24 UTC, mihaimaruseac commented on tensorflow/python/platform/sysconfig.py
> +  >>> print(tf.sysconfig.get_build_info())
Same

2025-01-31 16:24 UTC, mihaimaruseac commented on tensorflow/python/platform/sysconfig.py
> +  >>> print(tf.sysconfig.get_lib())
Same

2025-01-31 16:24 UTC, mihaimaruseac commented on tensorflow/python/platform/sysconfig.py
> +  >>> print(tf.sysconfig.get_include())
Without an output this is not testable.

2025-02-09 16:18 UTC, closed without merging