Example usage is created for tf.sets.size in sets_impl.py
tensorflow/tensorflow pull request #73149
Opened 2024-08-05 12:12 UTC by LakshmiKalaKadali

Example is provided for tf.sets.size in sets_impl.py

2024-08-06 19:14 UTC, sagunb approved these changes

2025-01-16 18:10 UTC, sagunb approved these changes

2025-01-16 19:19 UTC, mihaimaruseac requested changes

2025-01-16 19:19 UTC, mihaimaruseac commented on tensorflow/python/ops/sets_impl.py
> +Examples:
These need to be properly aligned

2025-01-16 19:20 UTC, mihaimaruseac commented on tensorflow/python/ops/sets_impl.py
> +```
Can you make this a doctest instead? All other examples in docstrings are on that format

2025-03-11 02:05 UTC, closed without merging