Clarify import_graph_def() places Ops into current default graph def
tensorflow/tensorflow pull request #7325
Opened 2017-02-07 09:33 UTC by samjabrahams

Small documentation tweak for `import_graph_def`, stemming from #7240. The documentation current says that the `GraphDef` is imported into "the graph". This change adds clarity as to which graph receives the imported operations.

CC: @martinwicke

2017-02-07 16:37 UTC, martinwicke requested changes

2017-02-07 16:37 UTC, martinwicke commented on tensorflow/python/framework/importer.py
> +  `Graph`.
Can you make this fit in 80 characters? I suggest either: 
- Remove the somewhat redundant 'Python' and 'TensorFlow'
or
- Put a full sentence about how the graph is added to the default graph into the main text for this function.

or both.

2017-02-07 19:06 UTC, samjabrahams commented
Los dos!

2017-02-07 19:14 UTC, martinwicke approved these changes

2017-02-07 19:14 UTC, martinwicke commented
Jenkins, test this please.

2017-02-08 01:19 UTC, merged

2017-02-08 01:22 UTC, martinwicke commented
Thanks!