changed example user op name to MyFact
tensorflow/tensorflow pull request #7351
Opened 2017-02-08 03:46 UTC by tntnatbry

Current example op defined in tensorflow/core/user_ops/fact.cc is causing a "AttributeError: 'module' object has no attribute 'fact'" error using the following BUILD file and python code under tensorflow/core/user_ops:

BUILD file:
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "fact.so",
    srcs = ["fact.cc"],
)

Python code:
import tensorflow as tf
fact_module = tf.load_op_library('fact.so')
with tf.Session():
  print(fact_module.fact().eval())

Is this due to "fact" possibly being a reserved keyword in tensorflow? If yes, this PR will fix this issue by calling the op as my_fact instead of fact.

If it makes sense, I can also add the BUILD file and this python driver code under tensorflow/core/user_ops

2017-02-09 22:32 UTC, vrv commented
It is entirely possible!  Please go ahead and play around with what works -- this is supposed to just be an example of how to define custom ops, so the name isn't that important  :)

2017-02-10 05:16 UTC, vrv commented
@jart should we have this test be written importing the module dependencies to avoid the hourglass dependency?   As an 'example' of how to load a custom op, using the tf namespace makes more sense to copy-paste, but I'd like to get your opinion first.

2017-02-10 05:19 UTC, tntnatbry commented
@vrv thanks!
Seems like I missed some steps while building this op yesterday, the default implementation is working fine. I have however added a python module file and a test case for this op, along with a BUILD file (following the style guide)

2017-02-10 05:30 UTC, vrv commented
Also adding @keveman as reviewer since I'm not sure whether it's intentional to have not had a BUILD file (do we want to encourage BUILD files to build custom ops, or recommend just using gcc/clang instead like we also mention on our 'adding an op' guide?)

2017-02-13 20:56 UTC, keveman commented
@tensorflow-jenkins test this please.

2017-02-13 20:57 UTC, keveman approved these changes
Looks good. Will merge after tests pass.

2017-02-15 01:04 UTC, vrv commented
@tensorflow-jenkins test this please

2017-02-15 02:21 UTC, vrv commented
sadly: ERROR: /workspace/tensorflow/BUILD:139:1: Target '//tensorflow/core/user_ops:all_files' is not visible from target '//tensorflow:all_opensource_files'. Check the visibility declaration of the former target if you think the dependency is legitimate.


@keveman what should they do?

2017-02-15 02:28 UTC, keveman commented on tensorflow/core/user_ops/BUILD
> +    visibility = ["//third_party/tensorflow:__subpackages__"],
This should be `visibility = ["//tensorflow:__subpackages__"],` ?

2017-02-15 02:55 UTC, tntnatbry commented on tensorflow/core/user_ops/BUILD
> +    visibility = ["//third_party/tensorflow:__subpackages__"],
@keveman Makes sense, updated the visibility.

2017-02-25 05:26 UTC, tntnatbry commented
Friendly ping! Can this be tested again?

2017-02-25 05:58 UTC, vrv requested changes
Just a few minor things first.

2017-02-25 05:58 UTC, vrv commented on tensorflow/core/user_ops/fact_op_test.py
> +import os.path
You can remove this I think

2017-02-25 05:58 UTC, vrv commented on tensorflow/core/user_ops/fact_op.py
> +import os.path
import os, not os.path

(we prefer to import modules, not methods)

2017-02-25 05:58 UTC, vrv commented on tensorflow/core/user_ops/fact_op_test.py
> +
can you add a linespace here?  (our internal linter likes to have two lines between top-level blocks)

2017-02-25 05:58 UTC, vrv commented on tensorflow/core/user_ops/fact_op_test.py
> +
(same here: a line space)

2017-02-28 02:26 UTC, tntnatbry commented on tensorflow/core/user_ops/fact_op_test.py
> +
added.

2017-02-28 02:26 UTC, tntnatbry commented on tensorflow/core/user_ops/fact_op_test.py
> +
added.

2017-02-28 02:26 UTC, tntnatbry commented on tensorflow/core/user_ops/fact_op_test.py
> +import os.path
thanks, this was redundant.

2017-02-28 02:26 UTC, tntnatbry commented on tensorflow/core/user_ops/fact_op.py
> +import os.path
done.

2017-02-28 02:28 UTC, tntnatbry commented
@vrv I have made the changes based on your review.

2017-02-28 02:29 UTC, vrv commented
@tensorflow-jenkins test this please

2017-03-06 22:43 UTC, vrv commented
@tensorflow-jenkins test this please

2017-03-07 18:13 UTC, dandelionmane commented
@tntnatbry looks the following are broken in py3:
//tensorflow/core/ops/compat:backwards_compatibility_test
//tensorflow/core/user_ops:fact_op_test  
/tensorflow/examples/adding_an_op:fact_test  

https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/3619/console

Please fix

2017-03-11 01:59 UTC, tntnatbry commented
@dandelionmane @vrv Looks like this op is already a registered op in the tensorflow core op library, as it is listed [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/compat/ops_history.v1.pbtxt#L6396). Defining this op as a custom user op instead is therefore failing the following tests, as tensorflow is unable to find it as a registered op anymore:

//tensorflow/core/ops/compat:backwards_compatibility_test
//tensorflow/examples/adding_an_op:fact_test

Also since a test case already exists for this op here: /tensorflow/examples/adding_an_op/fact_test.py, there is no need to add a second test case.

Should we therefore close this PR?

2017-03-11 04:01 UTC, vrv commented
That's one option -- the other option is to rename this example op to a different name so it doesn't clash, but I guess then the adding an op documentation would go stale.  I'm going to let @keveman decide what he wants to do here.

2017-03-22 05:09 UTC, martinwicke commented
I'm going to close this. If @keveman decides it's better to make the changes, we can.

2017-03-22 05:09 UTC, closed without merging