Change mismatched ref input error message
tensorflow/tensorflow pull request #7421
Opened 2017-02-10 17:36 UTC by iRapha

Closes @202

2017-02-10 22:58 UTC, mrry requested changes

2017-02-10 22:58 UTC, mrry commented on tensorflow/python/framework/op_def_library.py
> +                (op_type_name, input_name))
I think this error message could be misleading. Sure, `tf.Variable` is the most common "l-value input", but you can also pass the result of `tf.assign()` to another `tf.assign()` as the l-value, in order to chain updates.

How about instead making the error message:

"'%s' op requires that input '%s' be a mutable tensor (e.g a tf.Variable)"

2017-02-11 01:03 UTC, iRapha commented on tensorflow/python/framework/op_def_library.py
> +                (op_type_name, input_name))
Done!

2017-02-13 03:09 UTC, mrry approved these changes
LGTM!

2017-02-13 03:09 UTC, mrry commented
@tensorflow-jenkins  test this please.

2017-02-13 05:00 UTC, merged