The silu activation function is updated with example code and  in  tf.nn_impl.py
tensorflow/tensorflow pull request #74406
Opened 2024-08-23 11:07 UTC by LakshmiKalaKadali

2024-09-17 03:49 UTC, keerthanakadiri commented
Hi @wangpengmit, Can you please review this PR? Thank you !

2024-09-23 09:26 UTC, keerthanakadiri commented
Hi @wangpengmit, Can you please review this PR? Thank you !

2024-10-01 06:01 UTC, keerthanakadiri commented
Hi @wangpengmit, Can you please review this PR? Thank you !

2024-10-08 11:24 UTC, keerthanakadiri commented
Hi @wangpengmit, Can you please review this PR? Thank you !

2024-10-23 09:28 UTC, keerthanakadiri commented
Hi @wangpengmit, Can you please review this PR? Thank you !

2024-11-12 08:00 UTC, keerthanakadiri commented
Hi @MichaelHudgins ,Can you please review this PR? Thank you !

2025-01-31 16:23 UTC, mihaimaruseac requested changes

2025-01-31 16:23 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +  """Computes the Sigmoid Linear Unit(SiLU )or Swish activation function: `x * sigmoid(beta * x)`.
This line is too long. Please reword so that the formula becomes a new paragraph

2025-01-31 16:23 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +    The activation value. Has the same type as input
All/Most TF ops return outputs of the same type as main input. We should document only when that is not the case.

2025-01-31 16:23 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +    following data types: bfloat16, half, complex64, complex128
This needs to be indented according to the coding style

2025-02-17 07:53 UTC, LakshmiKalaKadali commented on tensorflow/python/ops/nn_impl.py
> +  """Computes the Sigmoid Linear Unit(SiLU )or Swish activation function: `x * sigmoid(beta * x)`.
Done Suggested changes

2025-02-17 07:54 UTC, LakshmiKalaKadali commented on tensorflow/python/ops/nn_impl.py
> +    The activation value. Has the same type as input
Yes, Reverted this updation

2025-02-17 07:54 UTC, LakshmiKalaKadali commented on tensorflow/python/ops/nn_impl.py
> +    following data types: bfloat16, half, complex64, complex128
Done

2025-02-17 15:05 UTC, mihaimaruseac requested changes

2025-02-17 15:05 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +  >>> print(silu_output)
You don't need the print, just write the expression directly.

2025-02-17 15:05 UTC, mihaimaruseac commented on tensorflow/python/ops/nn_impl.py
> +  is computed as follows `x * sigmoid(beta * x)`.
Docstrings are one short line and then more description in new paragraphs. Please reword.

2025-04-13 04:10 UTC, Ali1994Baker reviewed
Alishop

2025-05-05 07:53 UTC, keerthanakadiri commented
I'm going  ahead and closing this PR, because there seems to be no response for a long time. If you're still interested in pursuing this , please feel free to reopen!

2025-05-05 08:03 UTC, closed without merging