TFLearn Estimator Summary Writer Fix
tensorflow/tensorflow pull request #7555
Opened 2017-02-16 04:47 UTC by thesuperzapper

More info at #7554

2017-02-27 18:38 UTC, martinwicke requested changes
Thank you for this! Can you please add a test that exercises this new code?

2017-02-27 18:38 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/estimators/estimator.py
> +            isinstance(dictionary[key], float)):
Can you remove the extra whitespace here?

2017-02-27 18:38 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/estimators/estimator.py
> +              isinstance(dictionary[key], int)):
Is int even different from both of these?

2017-02-27 18:38 UTC, martinwicke commented on tensorflow/contrib/learn/python/learn/estimators/estimator.py
> +      logging.warn('Skipping summary for %s, must be a float, np.float32, np.int64, np.int32 or int.',
Here also, I don't think int can ever be neither int32, nor int64.

2017-03-07 09:08 UTC, thesuperzapper commented
Sorry for disappearing for a while, been super busy, but we really need to get this fixed. We need the int type because people can write their own MetricSpec's.

2017-03-07 09:08 UTC, thesuperzapper commented on tensorflow/contrib/learn/python/learn/estimators/estimator.py
> +            isinstance(dictionary[key], float)):
Yep

2017-03-07 23:38 UTC, dandelionmane commented
@thesuperzapper Please add a test as martinwicke requested.

2017-04-10 16:56 UTC, drpngx commented
@thesuperzapper feel free to add tests. Thanks!

2017-04-11 05:23 UTC, thesuperzapper commented
I am not 100% sure how to write test cases.

2017-04-14 18:23 UTC, martinwicke commented
You can look at the estimator_test.py file to see other tests.
We should have test cases that exercise these new code paths.

I'm a bit unclear what failure this addresses. I think the change is fine in general though.

Can you make the same change (and test) to tensorflow/python/estimators/estimator.py as well? The _write_dict_to_summary code looks the same.

2017-04-26 15:43 UTC, martinwicke commented
@thesuperzapper Ping?

2017-04-27 08:15 UTC, thesuperzapper commented
_Note: I added the same fix to `tensorflow/python/estimators/estimator.py`._

This pull request simply allows us to write int-type values in the summary file.

A side effect of this pull request will be **writing the value of 'global_step' at 'global_step'** -- a useless piece of information -- this is because 'global_step' is inside the ['eval_results'](https://github.com/tensorflow/tensorflow/blob/1a1527ab1fcffd94f692b1301fdbe87903ce7bdb/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L841) & ['dictionary'](https://github.com/tensorflow/tensorflow/blob/1a1527ab1fcffd94f692b1301fdbe87903ce7bdb/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L330) objects, (Which would not previously have been written by [`_write_dict_to_summary`](https://github.com/tensorflow/tensorflow/blob/1a1527ab1fcffd94f692b1301fdbe87903ce7bdb/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L316) because 'global_step' is an int type, as seen in #7554)

Therefore, we probably should remove the 'global_step' key from the 'eval_results' dictionary. (Or filter it in `_write_dict_to_summary`), otherwise 'global_step' by 'global_step' is displayed in TensorBoard. 

But also note that we return the 'eval_results' dictionary in [ `_evaluate_model`](https://github.com/tensorflow/tensorflow/blob/1a1527ab1fcffd94f692b1301fdbe87903ce7bdb/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L853). Therefore, I would like some advice on the best way of removing/filtering the 'global_step' key, so that we don't break this return, or refactor stuff unnecessarily.

2017-04-27 15:55 UTC, martinwicke commented
I think the right solution here is to filter global_step out inside _write_dict_to_summary. Nobody needs to see that graph, it's boring.

I still want a test. Without one, I guarantee that this will break sooner or later.

2017-05-02 01:04 UTC, vrv commented
another ping for @thesuperzapper !

2017-05-02 01:33 UTC, thesuperzapper commented
@vrv 
Sorry guys, I have been stupidly busy! I am still not sure how the testing framwork works.

Do I just add a function to the [estimator_test.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/estimator_test.py) file?

Also, do you think hard-coded filtering the `global_step` key inside [_write_dict_to_summary](https://github.com/tensorflow/tensorflow/blob/1a1527ab1fcffd94f692b1301fdbe87903ce7bdb/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L331) is good enough?

2017-05-02 01:35 UTC, vrv commented
Yes, a test to estimator_test.py would be the right place.

(I don't know about the 'global step' key filtering, punting to @martinwicke and @ispirmustafa )

2017-05-02 04:43 UTC, martinwicke commented
You can use the `tf.train.get_global_step` method to check whether a value you're about to write is the global step tensor.

2017-05-02 21:39 UTC, ispirmustafa commented
+1 for "filter global_step out inside _write_dict_to_summary"
You can do if before calling the _write_dict_to_summary.

2017-05-12 00:10 UTC, ispirmustafa requested changes
global step should be filtered out before calling this function.

2017-05-15 18:30 UTC, drpngx commented
@thesuperzapper any luck on this?

2017-05-15 23:53 UTC, thesuperzapper commented
I will look at this later today, but it's pretty much just making the current changes, and then stopping the writer from writing the global step.

2017-05-16 15:44 UTC, rmlarsen commented
@ispirmustafa @martinwicke could you take another look, please?

2017-05-16 15:50 UTC, ispirmustafa approved these changes

2017-05-16 17:21 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-05-16 18:12 UTC, merged