Fix `memcpy` call with null data in `SimpleDynamicBuffer`
tensorflow/tensorflow pull request #77167
Opened 2024-10-07 18:55 UTC by cdesouza-chromium

It is undefined to call `memcpy` with either source or destination being `nullptr`. `SimpleDynamicBuffer` missed checks for this, as there are many cases where an empty string is passed as a value, and as a result `memcpy` ends up being called with new, for case when `data_` is empty.

This change adds the necessary checks to avoid this issue.

2024-10-07 19:39 UTC, cdesouza-chromium commented
I don't think I have access to your CI, to be honest.

2024-10-15 09:01 UTC, keerthanakadiri commented
Hi @Ferev , Can you please review this PR? Thank you !

2024-10-23 16:32 UTC, fergushenderson approved these changes

2024-10-25 14:22 UTC, mihaimaruseac approved these changes
Thank you!

2024-10-25 16:42 UTC, fergushenderson commented on tensorflow/lite/string_util_test.cc
> +  ASSERT_EQ(buf.AddString(empty_string.data(), empty_string.len()), kTfLiteOk);
s/len/length/

2024-10-25 16:45 UTC, fergushenderson requested changes
There's a build error in the change to string_util_test.cc:

[tensorflow/lite/string_util_test.cc:242:61: error: no member named 'len' in 'std::string'
  242 |   ASSERT_EQ(buf.AddString(empty_string.data(), empty_string.len()), kTfLiteOk);
      |                                                ~~~~~~~~~~~~ ^

The fix is simple:
s/len/length/

2024-10-25 16:58 UTC, cdesouza-chromium commented
> There's a build error in the change to string_util_test.cc:
> 
> [tensorflow/lite/string_util_test.cc:242:61: error: no member named 'len' in 'std::string' 242 | ASSERT_EQ(buf.AddString(empty_string.data(), empty_string.len()), kTfLiteOk); | ~~~~~~~~~~~~ ^
> 
> The fix is simple: s/len/length/

Done.

2024-10-26 12:28 UTC, mihaimaruseac approved these changes

2024-10-30 03:04 UTC, cdesouza-chromium commented
Is there anything else missing for this CL?

2024-10-30 11:05 UTC, mihaimaruseac commented
It needs review on the internal system: https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

2024-10-30 17:02 UTC, fergushenderson approved these changes

2024-10-30 18:19 UTC, merged

2024-10-30 18:50 UTC, cdesouza-chromium commented
Yay, thanks everyone for the assistance getting this merged.

2024-10-30 20:10 UTC, mihaimaruseac commented
Welcome to TF and sorry it takes so long to get some PRs in