Add TF_CONTROL_SLOT to c_api
tensorflow/tensorflow pull request #7724
Opened 2017-02-21 04:10 UTC by malmaud

This lets users of `TF_ImportGraphDefOptionsAddInputMapping` remap control inputs without having to guess the magical value of the `kControlSlot` constant. 

cf #7508

2017-02-21 04:12 UTC, malmaud commented
I signed it!

2017-02-21 18:52 UTC, skye requested changes
@asimshankar can you also take a look since this changes the C API?

2017-02-21 18:52 UTC, skye commented on tensorflow/c/c_api.h
> +extern const int TF_CONTROL_SLOT;
Let's move this after the TF_Output definition.

2017-02-21 18:52 UTC, skye commented on tensorflow/c/c_api.cc
> +const int TF_CONTROL_SLOT = tensorflow::Graph::kControlSlot;
Likewise move this closer to the TF_Operation section (maybe after the TF_Session definition?)

2017-02-21 18:52 UTC, skye commented on tensorflow/c/c_api.h
> +// Set `src_index` to `TF_CONTROL_SLOT` to map a control input.
Change to: Set `src_index` and `dst.index` to `TF_CONTROL_SLOT`...

2017-02-22 16:25 UTC, skye commented
Actually, talking to @asimshankar offline, he came up with a different approach that seems more in line with the current API. Instead of exposing TF_CONTROL_SLOT, how about we add a new function instead:
```
TF_GraphImportGraphDefOptionsRemapControlDependency(
  TF_ImportGraphDefOptions* opts,
  const char* src_name,
  TF_Operation* dst);
```
This is similar to other parts of the API where we explicitly create functions for control dependencies (e.g. TF_AddControlInput, TF_ImportGraphDefOptionsAddControlDependency).

2017-02-22 16:34 UTC, malmaud commented
Makes sense to me. I'll code that up today.

2017-02-24 00:13 UTC, malmaud commented
OK, I took a shot at it.

2017-02-27 22:11 UTC, skye approved these changes
LGTM, thanks! @asimshankar do you have any comments before we submit?

2017-02-27 22:20 UTC, asimshankar commented
Looks good to me, thanks!

2017-03-03 04:57 UTC, caisq commented
@tensorflow-jenkins test this please

2017-03-03 20:21 UTC, merged

2017-03-03 20:22 UTC, caisq commented
@malmaud PR merged. Thank you for the contribution!

2017-03-03 20:36 UTC, malmaud commented
Thanks guys.