Fix symbol export of c api shared library
tensorflow/tensorflow pull request #77352
Opened 2024-10-09 10:08 UTC by jagiella

fixes #50940, #55624

2024-10-15 08:59 UTC, keerthanakadiri commented
Hi @Ferev, Can you please review this PR? Thank you !

2024-11-06 04:14 UTC, keerthanakadiri commented
Hi @Ferev, Can you please review this PR? Thank you !

2024-11-19 18:13 UTC, Linchenn commented
Hi @fergushenderson , I saw you have many contributions to these codes. Could you help review this PR? Thanks in advance!

2024-11-21 12:23 UTC, fergushenderson requested changes
This proposed patch creates a single shared library that includes both LiteRT (TF Lite) and the GPU delegate.  That is different to what we are doing for non-CMake build systems, which is to create two separate shared libraries, one with the LiteRT (TF Lite) C API and a separate one with the GPU delegate.

I think for consistency we should keep the set of libraries and the contents of each library the same regardless of the build system used.

See https://github.com/tensorflow/tensorflow/issues/55624#issuecomment-1106491140 for an alternative CMake approach using a separate library for the GPU delegate.

2024-11-21 16:54 UTC, jagiella commented
But the proposed patch does not change what is compiled into the shared library. It only changes which symbols are exposed to the linker. 

*Remaining questions:*
1. If seperate libraries for tflite and gpu delegate are prefered, why is the GPU delegate code compiled into the static tflite library (cmake target = tensorflow-lite) in the first place?

2. If seperate libraries for tflite and gpu delegate are prefered, shouldn't there be a cmake build configuration for building the GPU (and other) delegate libraries provided by the repository analogously to the tensorflowlite_c library?

2024-11-21 18:45 UTC, fergushenderson commented
> But the proposed patch does not change what is compiled into the shared library. It only changes which symbols are exposed to the linker.

Well, the "--whole-archive" flag will change what gets linked into the shared library.

> If seperate libraries for tflite and gpu delegate are prefered,

For our binary distributions on Android, we have separate Maven packages -- and hence also separate `.so` libraries -- for TFLite and the GPU delegate, both for regular TF Lite and also for TF Lite in Play services.  And we have a separate library target for the Bazel build.
<https://github.com/tensorflow/tensorflow/blob/0aa5275dd158353b6cbf2520830a44791f37abdd/tensorflow/lite/delegates/gpu/BUILD#L191>
I am also not aware of any _compelling_ reasons to prefer having a single shared library with both.  So for consistency, I do think it makes sense to have separate shared libraries with the CMake build too.  But I might be missing something... if so, please let me know.

> why is the GPU delegate code compiled into the static tflite library (cmake target = tensorflow-lite) in the first place?

That's a good question.  I don't know why it was done that way originally.

> If seperate libraries for tflite and gpu delegate are prefered, shouldn't there be a cmake build configuration for building the GPU (and other) delegate libraries provided by the repository analogously to the tensorflowlite_c library?

IMHO: Yes, that sounds right to me.

2024-11-22 08:57 UTC, jagiella commented
Although I very much agree with your concern of feature parity between the c++ and c library set(s), would you still consider including the patch in the meanwhile to provide access to the delegates for cmake users until a proper cmake route is established for building the standalone delegate libraries? :angel: 

For now, everything is laying in front of us, but is just not usable without every user willing to use it needing to create its own individual patch / solution by him/herself :smile: And thats kind of a pity

2024-11-22 10:26 UTC, fergushenderson commented
Can you use the prebuilt Maven packages, rather than building from sources?

2024-11-22 10:31 UTC, fergushenderson commented
Can you use the prebuilt Maven packages, rather than building from sources?

The GPU package should define symbols that are sufficient to allow you to use the GPU delegate, possibly with minor source code changes to your app in terms of exactly how you construct the GPU delegate object, depending on exactly which API you are using to do that currently.

2024-11-27 15:17 UTC, fergushenderson commented
> Although I very much agree with your concern of feature parity between the c++ and c library set(s), would you still consider including the patch in the meanwhile to provide access to the delegates for cmake users until a proper cmake route is established for building the standalone delegate libraries? 👼

Unfortunately I think doing that would not be a good idea, because once the GPU delegate symbols are exposed in the `tensorflowlite_c.so` library, people will start to write code that depends on those symbols, and then removing those symbols from that library would then become problematic because it would not be backwards compatible and would break that code.

2024-11-27 15:22 UTC, fergushenderson requested changes
This proposed patch creates a single shared library that includes both LiteRT (TF Lite) and the GPU delegate. That is different to what we are doing for non-CMake build systems, which is to create two separate shared libraries, one with the LiteRT (TF Lite) C API and a separate one with the GPU delegate.

I think for consistency we should keep the set of libraries and the contents of each library the same regardless of the build system used.

Even doing this as an interim temporary situation would be problematic,
because people would start to write code that depends on it, and then fixing it properly would break backwards compatibility.
See https://github.com/tensorflow/tensorflow/issues/55624#issuecomment-1106491140 for an alternative CMake approach using a separate library for the GPU delegate.

2024-11-27 20:19 UTC, jagiella commented
I fully understand the backward compatibility trap and agree that this is not desired, if seperate libraries are the way to go in the long run.

I just do not know how to build the delegate libraries. I couldn't find any documentation or tutorial on the matter. The comment https://github.com/tensorflow/tensorflow/issues/55624#issuecomment-1106491140 mentions how to use them, but not how to build them. Or am I missing something?

2024-11-27 21:13 UTC, fergushenderson commented
Have a look at the BUILD files, which contain the Bazel build rules.
In particular 
[delegates/gpu/BUILD line 191](https://github.com/tensorflow/tensorflow/blob/91d661ed50ef1de336cb04d34ae8391aecdceea5/tensorflow/lite/delegates/gpu/BUILD#L191)
is the rule for building the `.so` file that contains the GPU delegate.

Maybe even ask Gemini to translate that Bazel build rule to a CMake configuration?

2024-11-27 21:39 UTC, jagiella commented
but looking at the tensorflow/lite/CMakeLists.txt file for the tflite c++ library https://github.com/tensorflow/tensorflow/blob/91d661ed50ef1de336cb04d34ae8391aecdceea5/tensorflow/lite/CMakeLists.txt#L669 it contadicts what you stated before: It clearly adds the delegate source files to the tflite sources which are going to be compiled into one single libtensorflowlite.so.

So enabling GPU delegate support as described in the cmake build documentation https://android.googlesource.com/platform/external/tensorflow/+/6b511124eb0/tensorflow/lite/g3doc/guide/build_cmake.md#opencl-gpu-delegate, e.g.
```bash
cmake ../tensorflow_src/tensorflow/lite -DTFLITE_ENABLE_GPU=ON
```
will result in a tflite library with delegate support baked into the library without the need of an additional delegate plugin library.

2025-01-21 05:24 UTC, fergushenderson commented
I agree that things are currently not consistent between CMake and Bazel build systems.

But I think the proposed changes in this PR make things worse, rather than reducing this inconsistency. I think separate libraries for each delegate are preferable in the long run, rather than a single monolithic library.

And because this PR would expose new ABIs, backwards compatibility concerns would make it difficult to fix later.

So I don't think we should go ahead with this.
Instead, I think we should migrate the current CMake build support for a monolithic library with optional support for GPU delegate to instead use separate libraries.

2025-01-21 05:26 UTC, fergushenderson requested changes
See https://github.com/tensorflow/tensorflow/pull/77352#issuecomment-2603685545

2025-02-09 16:18 UTC, closed without merging