Improve dataset transformations: added logging, fixed imports, and op…
tensorflow/tensorflow pull request #77817
Opened 2024-10-13 06:50 UTC by sanowl

Added logging throughout dataset transformations for better debugging and traceability.
Improved error handling with detailed exception messages and logging in dataset transformations and iterators.
Fixed undefined variable issue by importing the missing tensor_util module.
Refactored code for readability and maintainability, including improvements to map_and_batch, dense_to_sparse_batch, and iterator classes.
Introduced EnhancedDatasetIterator to provide better logging and handling during dataset iteration.

2024-10-14 12:41 UTC, mihaimaruseac requested changes
Please only change what is relevant to the PR, not docstrings that should not change.

2024-10-14 12:41 UTC, mihaimaruseac commented on tensorflow/python/data/experimental/ops/batching.py
> +import tensorflow as tf
You cannot do this import while inside TF directory

2024-10-14 12:41 UTC, mihaimaruseac commented on tensorflow/python/data/experimental/ops/batching.py
> +    example_usage()
This doesn't belong here. This is a library file, so it should not have script/binary parts.

2024-10-14 12:41 UTC, mihaimaruseac commented on tensorflow/python/data/experimental/ops/batching.py
> +    Example:
Why are you changing the docstring so much? Why are you removing the examples?

2024-10-14 12:41 UTC, mihaimaruseac commented on tensorflow/python/data/experimental/ops/batching.py
> -@deprecation.deprecated(None, "Use `tf.data.Dataset.ragged_batch` instead.")
Why are you removing the deprecation?

2024-10-16 16:39 UTC, sanowl commented
yes sorry I will get on it been busy

2024-10-22 10:21 UTC, closed without merging

2024-10-23 11:50 UTC, mihaimaruseac commented
This is starting to look like a spam PR, so I marked it as such