upgrading oneDNN version to 3.6
tensorflow/tensorflow pull request #77927
Opened 2024-10-15 05:46 UTC by ashiqimranintel

This PR upgrades oneDNN version from v3.5 to v3.6, this PR has been tested on several models across different platforms including cascade-lake, sapphire-rapids, and granite-rapids

Several bug fixes have been resolved in this version. Details can be found here https://github.com/oneapi-src/oneDNN/releases

2024-10-15 11:20 UTC, mihaimaruseac approved these changes

2024-10-16 15:06 UTC, mihaimaruseac commented
There has been no change to the PR since my review yesterday, can I ask why was review requested again?

2024-10-16 15:06 UTC, mihaimaruseac approved these changes

2024-10-16 21:08 UTC, penpornk requested changes

2024-10-16 21:08 UTC, penpornk commented on third_party/mkl_dnn/mkldnn_v1.BUILD
> +    "#cmakedefine DNNL_GPU_VENDOR DNNL_VENDOR_${DNNL_GPU_VENDOR}": "#define DNNL_VENDOR_INTEL",
Nit:
```suggestion
    "#cmakedefine DNNL_GPU_VENDOR DNNL_VENDOR_${DNNL_GPU_VENDOR}": "#define DNNL_VENDOR_NONE",
```

2024-10-16 22:17 UTC, ashiqimranintel commented on third_party/mkl_dnn/mkldnn_v1.BUILD
> +    "#cmakedefine DNNL_GPU_VENDOR DNNL_VENDOR_${DNNL_GPU_VENDOR}": "#define DNNL_VENDOR_INTEL",
done

2024-10-16 22:40 UTC, mihaimaruseac approved these changes

2024-10-23 11:41 UTC, mihaimaruseac approved these changes

2024-10-23 11:41 UTC, mihaimaruseac commented
(you shouldn't have requested a new review, this was not changed since the last review)

2024-11-13 21:30 UTC, penpornk requested changes
Our CI failed to build ([log](https://btx.cloud.google.com/invocations/25204716-a51a-42e6-a82a-f265698e5fb3/log)).
```
...
external/onednn/src/common/logging.cpp:20:10: fatal error: 'common/spdlog/sinks/rotating_file_sink.h' file not found
   20 | #include "common/spdlog/sinks/rotating_file_sink.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
...
```

Please add the following to `_INCLUDE_LIST`:
```
    "src/common/spdlog",
    "src/common/spdlog/details",
    "src/common/spdlog/fmt",
    "src/common/spdlog/fmt/bundled",
    "src/common/spdlog/sinks",
```
and the following to `_TEXTUAL_HEADERS_LIST`:
```
    "src/common/spdlog/*.h",
    "src/common/spdlog/details/*.h",
    "src/common/spdlog/fmt/**/*.h",
    "src/common/spdlog/sinks/*.h",
```

2024-11-14 00:07 UTC, vpirogov commented
> Please add the following to `_INCLUDE_LIST`:
> 

These headers are related to an opt-in experimental feature [`DNNL_EXPERIMENTAL_LOGGING`](https://oneapi-src.github.io/oneDNN/dev_guide_experimental.html#onednn-experimental-logging), which should not be used by TensorFlow.

2024-11-14 01:22 UTC, penpornk requested changes
> > Please add the following to `_INCLUDE_LIST`:
> 
> These headers are related to an opt-in experimental feature [`DNNL_EXPERIMENTAL_LOGGING`](https://oneapi-src.github.io/oneDNN/dev_guide_experimental.html#onednn-experimental-logging), which should not be used by TensorFlow.

Thank you for the info! Then could you please remove the source files that includes these headers from the `srcs` list?

2024-11-15 19:12 UTC, dzarukin commented on third_party/mkl_dnn/mkldnn_v1.BUILD
> +    "#cmakedefine DNNL_SYCL_GENERIC": "#define DNNL_SYCL_GENERIC 1",
```suggestion
    "#cmakedefine DNNL_SYCL_GENERIC": "#define DNNL_SYCL_GENERIC",
```

2024-11-15 19:12 UTC, dzarukin commented on third_party/mkl_dnn/mkldnn_v1.BUILD
> +    "#cmakedefine DNNL_DISABLE_GPU_REF_KERNELS": "#define DNNL_DISABLE_GPU_REF_KERNELS 0",
```suggestion
    "#cmakedefine DNNL_DISABLE_GPU_REF_KERNELS": "#define DNNL_DISABLE_GPU_REF_KERNELS",
```

2024-11-20 16:43 UTC, ashiqimranintel commented
@penpornk , I added a new commit, could you restart the test? It seemed, it didn't trigger yet

2024-11-20 17:04 UTC, mihaimaruseac approved these changes

2024-11-21 01:06 UTC, mihaimaruseac approved these changes

2024-12-26 14:43 UTC, mihaimaruseac approved these changes

2025-01-06 14:05 UTC, penpornk commented
@ashiqimranintel Could you please help take a look at Linux x86 CPU CI failures? Here is the [log](https://btx.cloud.google.com/invocations/43a4dd35-900b-4a65-b751-35bd27d8013a/targets)

2025-01-21 18:31 UTC, gzmkl commented
@penpornk  I could reproduce the problem with TF tests.

2025-01-23 22:06 UTC, gzmkl commented
@penpornk Hi Penporn, my investigation found that oneDNN 3.6.2 contains bugs in brg_matmul implementation. oneDNN team now has a fix which partially addresses TensorFlow test failures (not ALL).   I will continue to work with oneDNN team to have a complete solution. 

So this PR and related XLA PR cannot go in.

2025-01-28 10:13 UTC, penpornk commented
@gzmkl Thank you for the heads up! I'll close this PR for the time being then. Please feel free to reopen when the fix is ready.

2025-01-28 10:13 UTC, closed without merging

2025-04-01 23:03 UTC, ashiqimranintel commented
@penpornk @mihaimaruseac https://github.com/tensorflow/tensorflow/pull/90388 can you review the new PR? Thanks