Fix typo in code logic of Conv3DTranspose()
tensorflow/tensorflow pull request #77968
Opened 2024-10-15 14:38 UTC by gaikwadrahul8

Hi, Team

It seems like there is typo error in the code logic of **Conv3DTranspose()** in the below line which is trying to combine padding values for **height** and **depth** dimensions so as far I know padding values should correspond to their respective dimensions in this case **depth** dimension not **height** so the padding calculation should only use the padding value relevant to the depth related padding values

I think it should be like below :
```
const int spatial_dim_1_padding_after =
      params.padding_values.depth + params.padding_values.depth_offset;
```

https://github.com/tensorflow/tensorflow/blob/d540fd62d027dbb86e9434f8c43802997c8ab29c/tensorflow/lite/kernels/internal/optimized/optimized_ops.h#L8220

If you've any suggestion or feedback or Am I missing something here please let me know ? Thank you

2024-10-23 06:42 UTC, keerthanakadiri commented
Hi @Ferev, Can you please review this PR? Thank you !

2024-10-23 14:47 UTC, fergushenderson commented
Can you please also add a regression test that will exercise this case?

2024-11-09 16:20 UTC, gaikwadrahul8 commented
Hi, @fergushenderson 

I apologize for the delayed response and thank you for your feedback, now I've added test cases If you've any suggestion or feedback or Am I missing something here please let me know ? Thank you

2024-11-11 09:51 UTC, fergushenderson commented
It looks like with your second commit, the following code snippet from the test is now duplicated. I think that would mean that those tests would unnecessarily get run twice?

```
INSTANTIATE_TEST_SUITE_P(Conv3dTransposeOpTest, Conv3dTransposeOpTest,
                         ::testing::Values(TestType::kConst,
                                           TestType::kDynamic));
```

2024-11-21 12:01 UTC, fergushenderson approved these changes

2024-11-21 14:35 UTC, fergushenderson requested changes
The new test has been inserted into the middle of an existing test.
The code is no longer syntactically correct.

One possible fix would be to move the newly inserted code in the *_test.cc file up six lines.

2024-11-22 09:59 UTC, gaikwadrahul8 commented
Hi, @fergushenderson 
Thank you for bringing my oversight to my attention. I inadvertently placed the new test cases within an existing test case. I have now made the necessary modifications as per your suggestion. I appreciate your understanding and support.

Thank you for your cooperation.

2024-11-22 14:27 UTC, mihaimaruseac approved these changes

2024-11-22 23:11 UTC, fergushenderson approved these changes

2024-12-30 23:31 UTC, fergushenderson commented
It looks like some of the newly added tests are failing, e.g. `tensorflow/lite/kernels:conv3d_transpose_test`:

```
[ RUN      ] Conv3dTransposeOpTest/Conv3dTransposeOpTest.PaddingDepthDimensionTest/0
ERROR: third_party/tensorflow/lite/kernels/conv3d_transpose.cc:110 unused_out_height != SizeOfDimension(input, 2) (3 != 2)
ERROR: Node number 0 (CONV_3D_TRANSPOSE) failed to prepare.
F1226 11:09:45.164343    6176 test_util.cc:291] Check failed: interpreter_->AllocateTensors() == kTfLiteOk Cannot allocate tensors
*** Check failure stack trace: ***
    @     0x7fb30154af1a  third_party/absl/log/internal/log_message.cc:555 absl::log_internal::LogMessage::PrepareToDie()
    @     0x7fb30154a810  third_party/absl/log/internal/log_message.cc:573 absl::log_internal::LogMessage::SendToLog()
    @     0x7fb30154969f  third_party/absl/log/internal/log_message.cc:489 absl::log_internal::LogMessage::Flush()
    @     0x7fb30154c069  third_party/absl/log/internal/log_message.cc:671 absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x7fb4004b1411  third_party/tensorflow/lite/kernels/test_util.cc:291 tflite::SingleOpModel::AllocateAndDelegate()
    @     0x7fb4004b28dc  third_party/tensorflow/lite/kernels/test_util.cc:382 tflite::SingleOpModel::BuildInterpreter()
    @     0x7fb4004b3c46  third_party/tensorflow/lite/kernels/test_util.cc:421 tflite::SingleOpModel::BuildInterpreter()
    @     0x7fb406fabc4b  third_party/tensorflow/lite/kernels/conv3d_transpose_test.cc:91 tflite::(anonymous namespace)::Conv3dTransposeOpModel::Conv3dTransposeOpModel()
    @     0x7fb406fbc9d9  third_party/tensorflow/lite/kernels/conv3d_transpose_test.cc:161 tflite::(anonymous namespace)::Conv3dTransposeOpTest_PaddingDepthDimensionTest_Test::TestBody()
    @     0x7fb369d8e5b0  third_party/googletest/googletest/src/gtest.cc:0 testing::Test::Run()
    @     0x7fb369d8fd93  third_party/googletest/googletest/src/gtest.cc:2883 testing::TestInfo::Run()
    @     0x7fb369d91db1  third_party/googletest/googletest/src/gtest.cc:3061 testing::TestSuite::Run()
    @     0x7fb369dab98c  third_party/googletest/googletest/src/gtest.cc:5994 testing::internal::UnitTestImpl::RunAllTests()
    @     0x7fb369daaf58  third_party/googletest/googletest/src/gtest.cc:0 testing::UnitTest::Run()
    @     0x7fb4069825dd  third_party/googletest/googletest/include/gtest/gtest.h:2349 main
    @     0x7fb2e52d63d4  __libc_start_main
    @     0x563694b637aa  ../sysdeps/x86_64/start.S:120 _start
*** SIGABRT received by PID 6176 (TID 6176) on cpu 114 from PID 6176; ***
```

and

`tensorflow/lite/delegates/utils/experimental/sample_stable_delegate:sample_stable_delegate_kernel_tests`:

```
F1226 11:13:01.677559    2677 test_util.h:989] Check failed: t No tensor with index 31751.
*** Check failure stack trace: ***
    @     0x7fe783245b8a  third_party/absl/log/internal/log_message.cc:555 absl::log_internal::LogMessage::PrepareToDie()
    @     0x7fe783245330  third_party/absl/log/internal/log_message.cc:573 absl::log_internal::LogMessage::SendToLog()
    @     0x7fe78324417f  third_party/absl/log/internal/log_message.cc:489 absl::log_internal::LogMessage::Flush()
    @     0x7fe783246e89  third_party/absl/log/internal/log_message.cc:671 absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x7fe888b1ec1f  ./third_party/tensorflow/lite/kernels/test_util.h:989 tflite::SingleOpModel::PopulateTensorImpl<>()
    @     0x7fe889ef278f  ./third_party/tensorflow/lite/kernels/test_util.h:703 tflite::(anonymous namespace)::Conv3dTransposeOpTest_PaddingValueDepthTestWithBias_Test::TestBody()
    @     0x7fe814988630  third_party/googletest/googletest/src/gtest.cc:0 testing::Test::Run()
    @     0x7fe814989e13  third_party/googletest/googletest/src/gtest.cc:2883 testing::TestInfo::Run()
    @     0x7fe81498be31  third_party/googletest/googletest/src/gtest.cc:3061 testing::TestSuite::Run()
    @     0x7fe8149a5cac  third_party/googletest/googletest/src/gtest.cc:5994 testing::internal::UnitTestImpl::RunAllTests()
    @     0x7fe8149a521d  third_party/googletest/googletest/src/gtest.cc:0 testing::UnitTest::Run()
    @     0x7fe890b5af67  third_party/googletest/googletest/include/gtest/gtest.h:2349 main
    @     0x7fe766a493d4  __libc_start_main
    @     0x5640d11edc2a  ../sysdeps/x86_64/start.S:120 _start
*** SIGABRT received by PID 2677 (TID 2677) on cpu 18 from PID 2677; ***
```

2024-12-30 23:33 UTC, fergushenderson requested changes
Please run the tests and fix any failing tests.

2025-01-31 02:00 UTC, closed without merging