Fix ImportError for TensorFlow Lite 2.17.0 on ARM Architecture
tensorflow/tensorflow pull request #78206
Opened 2024-10-18 18:11 UTC by saradha04

This PR resolves an ImportError in TensorFlow Lite 2.17.0 for ARMv7 architecture due to an undefined symbol in the tflite_runtime module.

Changes Made:

Cleaned the build environment.
Adjusted the build process for the ARMv7 target with Python 3.10.
Verified the generated wheel for necessary components.
Conducted import tests using a simple script (simpletest.py).
Issue Reference:
Addresses [Issue #75562](https://github.com/tensorflow/tensorflow/compare/master...saradha04:tensorflow:master?expand=1#75562) regarding import failure.

Testing:
Executed in GitHub Codespaces; confirmed functionality through import tests.

Additional Notes:
Feedback on build configuration and test results is welcome!

2024-10-21 05:30 UTC, keerthanakadiri commented
Hi @saradha04 , Can you please sign CLA , thank you !

2024-10-23 14:35 UTC, fergushenderson commented
What is the undefined symbol that is being fixed by this change?

(Undefined symbols can sometimes be caused by using the wrong Android min SDK level, so this might be a matter of setting the correct Android min SDK level?)

2024-12-10 05:37 UTC, keerthanakadiri commented
Hi @saradha04 , Can you please sign CLA , thank you !

2025-01-16 04:55 UTC, keerthanakadiri commented
Hi @saradha04 , Can you please sign CLA , thank you !

2025-01-16 19:34 UTC, mihaimaruseac requested changes
This does not do anything related to the PR description

2025-01-16 19:34 UTC, closed without merging