Added passing of kwargs to external optimizer minimize
tensorflow/tensorflow pull request #7923
Opened 2017-02-27 14:49 UTC by Karel-van-de-Plassche

I originally created this patch to track performance, but as it isn't an OP, you can't build timelines etc. Still it might be nice to have this interface.

2017-02-27 14:52 UTC, Karel-van-de-Plassche commented
I signed it!

2017-03-22 16:13 UTC, joshburkart requested changes
Looks good from my perspective

2017-03-22 16:13 UTC, joshburkart commented on tensorflow/contrib/opt/python/training/external_optimizer.py
> +      run_kwargs: kwargs to pass to session.run
Period after session.run please

2017-03-22 16:17 UTC, martinwicke approved these changes
Fixed formatting, ow good.

2017-03-22 16:17 UTC, martinwicke commented
Jenkins, test this please.

2017-03-22 16:54 UTC, martinwicke commented
Oddly, the test don't trigger. Trying again. 

Jenkins, test this please.

2017-03-22 16:55 UTC, martinwicke commented
better. Thanks Jenkins.

2017-03-22 17:33 UTC, merged