Fix integer overflow in range
tensorflow/tensorflow pull request #80133
Opened 2024-11-15 19:10 UTC by mattbahr

Fixes #64081

I modified the fixes from the rolled back PR's #77018 and #76252 to resolve an overflow that was identified by one of the new test cases. The issue was that in `ragged_range_op.cc`, `value` is incremented at the end of the loop logic, which results in a needless addition on the final iteration and creates the possibility for an overflow. This had no impact on the output of the operation and did not cause any of the tests to fail, but it was picked up by ASan.

https://github.com/tensorflow/tensorflow/blob/ec9e1531f0114662baef0f3985de5620b43d0d29/tensorflow/core/kernels/ragged_range_op.cc#L123-L126

I added a condition that only increments the value if there are more iterations to be completed.

2024-11-16 16:02 UTC, mihaimaruseac reviewed
I think this LGTMs, but let's also see if @cantonios sees any downsides on this patch

2024-12-03 14:50 UTC, mattbahr commented
@cantonios When you get the chance, would you mind taking a look at this review? Thanks!

2024-12-04 00:18 UTC, cantonios commented on tensorflow/core/kernels/sequence_ops.cc
> +                                  std::numeric_limits<int64_t>::max()));
Does it _actually_ need to be less than int64_t max, or could it be uint64_t max (i.e. no real limit)?

2024-12-09 14:57 UTC, cantonios requested changes
See question about limit.

2024-12-09 18:59 UTC, mattbahr commented
@cantonios Leaving the size unsigned can cause a signed integer overflow when it is passed to the AddDimWithStatus function.

https://github.com/tensorflow/tensorflow/blob/137b1e0e6890e8bad125911a325846db4ab05516/tensorflow/core/kernels/sequence_ops.cc#L109

This function expects type int64_t, and for a very large size will interpret it as negative.

https://github.com/tensorflow/tensorflow/blob/137b1e0e6890e8bad125911a325846db4ab05516/tensorflow/core/framework/tensor_shape.cc#L427-L433

2024-12-09 19:15 UTC, cantonios approved these changes

2024-12-10 17:20 UTC, merged