Fix typos in multiple documentation strings
tensorflow/tensorflow pull request #80998
Opened 2024-11-28 06:16 UTC by Venkat6871

Hi, Team
I observed few typos in the documentation strings and I have fixed those typos so please do the needful. Thank you.

2024-11-28 14:55 UTC, mihaimaruseac approved these changes

2024-12-03 07:14 UTC, keerthanakadiri commented
Hi @Venkat6871 , Can you please resolve the conflicts? Thank you!

2024-12-03 09:41 UTC, mihaimaruseac requested changes

2024-12-03 09:41 UTC, mihaimaruseac commented on tensorflow/python/distribute/sharded_variable.py
> +          'scater_xxx ops are not supported in Sharded Variable that does not '
```suggestion
          'scatter_xxx ops are not supported in Sharded Variable that does not '
```

2024-12-03 09:49 UTC, mihaimaruseac approved these changes
In the future, please send only one PR with all typos. This way, we don't have to solve merge conflicts which then result in just one single letter being changed after solving

2024-12-16 20:09 UTC, merged