native Cuda kernel for tf.dynamic_stitch op (reopened PR)
tensorflow/tensorflow pull request #8260
Opened 2017-03-10 03:20 UTC by MycChiu

I screwed up when squashing commits in #7764, so I started a clean pull request. @girving Please take a look at this, thank you. *(and I sincerely apologize for my horrible git-fu)*

2017-03-10 17:36 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op.cc
>      if (first_dim_size > 0) {
Can't this be `result_shape.num_elements() > 0` to exit early if other dimensions are zero too?

2017-03-10 18:11 UTC, girving requested changes
Please use a real commit message.

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op.cc
> +    OP_REQUIRES_OK(c, data_slice_ptrs.Init());
Presumably these get zero initialized, but I can't find where.  Can you confirm?

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op.cc
> +        indices_flat.Set(ptr_num, indices_vec(ind_num));
Needs the same error checking as in the CPU case.

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op_gpu.cu.cc
> +namespace {
Newline before `namespace {`.

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op_gpu.cu.cc
> +template <typename T>
Newline after `}  // namespace`.

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op.cc
> +        indices_flat.Set(ptr_num, indices_vec(ind_num));
Also needs to use `SubtleMustCopy` appropriately.

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op.cc
> +        indices_flat.Set(ptr_num, indices_vec(ind_num));
Wait, how is this correct at all?  What guarantee is there that `ptr_num < first_dim_size`?

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op_gpu.cu.cc
> +    output[output_id] = ldg(data_ptrs[slice_id] + slice_offset);
Should you use `ldg` for `output_indices[slice_id]` and `data_ptrs[slice_id]`?

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op_gpu.cu.cc
> +    const int grid_size = 60;
@zheng-xq What's the right thing to do here?

2017-03-10 18:11 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op.cc
> +struct LaunchDynamicStitchOp<GPUDevice, T> {
Upon further thought: the code doesn't seem to handle collisions correctly at all.  Am I reading this right?

2017-03-10 18:12 UTC, girving commented
I took a look.  For incremental changes, please leave the current commit as is and push new commits on top, *without* pulling in from master.

2017-03-14 05:57 UTC, MycChiu commented on tensorflow/core/kernels/dynamic_stitch_op.cc
> +        indices_flat.Set(ptr_num, indices_vec(ind_num));
Yes, I should actually just replace `ptr_num` with the value of `indices_vec(ind_num)`, so when collision happens the new index value will naturally overwrite the old one, which would be the same as how current implementation handles collisions, is my understanding correct? 

However, if we end up taking this approach, we would also need to account for missing indices on `indices_flat`. To do this, I plan on adding 1 to all the values of output index then subtract it back on the GPU kernel, so if the threads on CUDA kernel encounter a 0 on `output_id` they can just skip the read and write. 

Unfortunately, I think `CudaDeviceArrayOnHost` is not zero initialized, so I would need to do it manually. Is there a standard way to zero-initialize a temporary tensor? or do I just use normal for-loop to achieve this?

2017-03-14 05:57 UTC, MycChiu commented
@girving Thank you for the review! After reading your feedback, I realized that I totally omitted the cases where there are collisions in the output indices when I wrote the code, and since collisions never happened in my own use cases, I never caught this major flaw in my mind.

At first, I thought it would be hard to let GPU mimic how current CPU implementation handles collisions, but then I realized that some rather simple modifications to my current code would achieve the same effect.

I wrote the details under the relevant part of the code review, please take a look. I want to make sure the approach is right before I start modifying the code. Thank you very much!

2017-03-14 14:54 UTC, girving commented on tensorflow/core/kernels/dynamic_stitch_op.cc
> +        indices_flat.Set(ptr_num, indices_vec(ind_num));
No, that is a bad way to handle collisions.  It doesn't respect the documented semantics at all: the order of writes would be entirely random.  Also, it doesn't work if each output index corresponds to a slice with more than one element, and would require very slow atomic operations.

A better way would be to have a single array indexed by `first_dim_size` that's computed on the CPU with correct collision resolution.  In the case of no uninitialized entries in the output array (the common case), this array will be no larger than current arrays.

However, this whole approach of doing a large chunk of the work on CPU seems low quality at best.  I don't see any way around it given the collision requirements, though, and the current fake GPU implementation is probably strictly worse.  Unpleasant!

2017-04-10 17:07 UTC, drpngx commented
@girving what do you think of @MycChiu 's proposed approch in the last comment?

2017-04-10 17:52 UTC, girving commented
Apologies for missing the notifications earlier.  Looking now.

2017-04-10 17:53 UTC, girving commented
Oh, it looks like I already commented that the proposed adjustment didn't work.  @drpngx Do I have the flow right, or did I miss something new?

2017-04-10 18:10 UTC, drpngx commented
Oh, OK thanks @girving ! @MycChiu could you propose an alternative?

2017-04-26 16:02 UTC, martinwicke commented
ping @MycChiu

2017-05-02 01:05 UTC, vrv commented
Another ping for @MycChiu (it looks like they are not around lately).

2017-05-03 23:03 UTC, girving commented
I think we should close for now.

2017-05-03 23:03 UTC, closed without merging

2017-09-10 18:51 UTC, ahundt commented
for those that come across this see https://github.com/tensorflow/tensorflow/pull/11940 for a merged implementation