remove non-maintained tensorflow-io-gcs-filesystem dependency from pip_package
tensorflow/tensorflow pull request #82771
Opened 2024-12-11 20:38 UTC by nazimisik

this dependency has been causing a problem for more than a year without a solution, wheels are not built and it seems not very well maintained, if at all. tensorflow only depends on it for some optional purpose 

as seen by it's addition PR it's only enabled with a certain variable: https://github.com/tensorflow/tensorflow/pull/51460

yet community has been trying to find a solution for the problems it has been causing without a direct fix, it might be beneficial to get rid of this dependency for extended belief on tensorflow's multiplatform support and reliability

https://github.com/tensorflow/io/issues/2087
https://github.com/tensorflow/tensorflow/issues/56636
https://github.com/tensorflow/io/issues/1789
https://github.com/tensorflow/io/issues/2093
https://github.com/tensorflow/io/issues/2087
https://discuss.ai.google.dev/t/tensorflow-io-gcs-filesystem-with-windows/32191/3

2024-12-12 08:06 UTC, mihaimaruseac requested changes
Unfortunately, right now, this is needed as many tutorials use GCS.

The team is looking for a solution here, afaik.

2024-12-12 08:10 UTC, nazimisik commented
This would be okay if the depended library was correctly maintained but right now it brings lots of problems to real environments and we would at least like to see some plan to remediate this.

2024-12-12 08:19 UTC, nazimisik commented
same since 2023

https://github.com/tensorflow/io/issues/1789#issuecomment-1491355793

2025-01-23 16:24 UTC, Gornoka commented
Would a less extreme option be considered acceptable @mihaimaruseac.

I would see the following decent options:
* This dependency could be made an extra (as it is optional and nonexistence is handled), 
* get os dependent version requirements, as the `<=0.31.0` for windows, this way the normal install from the docs with pip would not break, tutorials with gcs would continue to work, and UV / poetry would not choke on this and could resolve to the fallback version. If you deem either of these solutions worthwhile i would be happy to create a pr.

2025-01-23 16:27 UTC, mihaimaruseac commented
I think making it an extra would work better.

The team is currently preparing for a new release of TF and they might reach a different decision too.

2025-02-20 07:07 UTC, nazimisik commented
rather keep it open

2025-02-20 13:07 UTC, mihaimaruseac commented
Not sure if @learning-to-play has seen this

2025-03-10 17:56 UTC, mihaimaruseac commented
This should now be fixed from TF side, with tensorflow-io-gcs-filesystem an optional dependency.

2025-03-10 17:56 UTC, closed without merging