Fixed a bug where inception layers had 2 3x3 conv kernels instead of …
tensorflow/tensorflow pull request #8295
Opened 2017-03-11 03:32 UTC by manjunaths

…one 3x3 and 5x5 kernel.

2017-03-11 04:17 UTC, caisq commented
@tensorflow-jenkins test this please

2017-03-22 06:54 UTC, martinwicke commented
Jenkins, test this please (flakes)

2017-03-23 03:27 UTC, sguada requested changes
This would break the current checkpoint.

2017-03-23 04:59 UTC, manjunaths commented
Please, Can I know what needs to be done next?

- Manju

On Mar 23, 2017 4:29 AM, "Sergio Guadarrama" <notifications@github.com>
wrote:

> *@sguada* requested changes on this pull request.
>
> This would break the current checkpoint.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/8295#pullrequestreview-28561832>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AANNNQnDvAdDL6Ko3a1oaT59DDwPf6HAks5roecCgaJpZM4MaFQS>
> .
>

2017-03-23 15:43 UTC, sguada commented
Maybe make the change including an extra parameter that changes the behavior, but maintains the previous behavior by default.

2017-04-10 17:08 UTC, drpngx commented
@manjunaths feel free to address.

2017-04-11 21:32 UTC, sguada commented
@manjunaths you would need to add an extra parameter to the network that keeps the old behavior by default, and that can be changed when needed.

2017-04-12 05:01 UTC, manjunaths commented
Hello @sguada ,

Thank you. I added a switch for this and left the original behavior as default. Can you review the code and see if it matches to the standards  or if anything more needs to be done ? I found one more issue addressing the same change issue #443. I think that can also be closed.

Thanks,
- Manju

2017-04-26 16:03 UTC, martinwicke commented
@sguada can you take a look at the changes?

2017-04-26 19:09 UTC, sguada requested changes
The idea if that use_5x5 filter is an argument of the functions, so you can pass it when calling.
It also would need a lot more documentation, specially about checkpoint not be compatible.

2017-04-28 15:55 UTC, drpngx commented
Jenkins, test this please.

2017-05-01 16:40 UTC, vrv commented
@tensorflow-jenkins test this please

2017-05-02 01:52 UTC, sguada commented
The changes have not been done.

2017-05-02 01:58 UTC, sguada requested changes

2017-05-02 01:58 UTC, sguada commented on tensorflow/contrib/slim/python/slim/nets/inception_v1.py
>        net, end_points = inception_v1_base(inputs, scope=scope)
Pass use_5x5 to inception_v1_base too.

2017-05-02 01:58 UTC, sguada commented on tensorflow/contrib/slim/python/slim/nets/inception_v1.py
> +filter_size = [3, 3]
Remove it.

2017-05-02 01:58 UTC, sguada commented on tensorflow/contrib/slim/python/slim/nets/inception_v1.py
> +filter_size_str=str(filter_size[0])+'x'+str(filter_size[1])
transform into a function that given filter_size returns the string.

2017-05-02 01:58 UTC, sguada commented on tensorflow/contrib/slim/python/slim/nets/inception_v1.py
>  def inception_v1_base(inputs, final_endpoint='Mixed_5c', scope='InceptionV1'):
Could you pass branch_2_filter_size as an argument? and use it inside.

2017-05-02 01:58 UTC, sguada commented on tensorflow/contrib/slim/python/slim/nets/inception_v1.py
> +                branch_2, 32, filter_size, scope='Conv2d_0b_'+filter_size_str)
use branch_2_filter_size and filter_size_str(branch_2_filter_size)

2017-05-04 21:43 UTC, vrv commented
@manjunaths any updates?

2017-05-05 01:21 UTC, manjunaths commented
Sorry, I have a personal emergency and am  unable to look at this for now.



On May 5, 2017 3:15 AM, "Vijay Vasudevan" <notifications@github.com> wrote:

@manjunaths <https://github.com/manjunaths> any updates?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/8295#issuecomment-299317701>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AANNNZ3pYyz2tvkM6HpyPSOGtsiKQEPPks5r2kbigaJpZM4MaFQS>
.

2017-05-05 01:25 UTC, vrv commented
I'm very sorry to hear that :(.  I hope things get better, and feel free to reopen a new PR if you are still able and interested.

2017-05-05 01:25 UTC, closed without merging