Add tf_keras installation and import statements to tf.autodiff.ForwardAccumulator example
tensorflow/tensorflow pull request #83318
Opened 2024-12-19 07:06 UTC by gaikwadrahul8

Hi, Team
I have added necessary installation and import statements to the example section [here](https://www.tensorflow.org/api_docs/python/tf/autodiff/ForwardAccumulator) to ensure the code runs correctly starting with TensorFlow 2.16, doing `pip install tensorflow` will install Keras 3 , then by default `from tensorflow import keras` ([tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras)) will be Keras 3.When you have TensorFlow >= 2.16 and [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) to stay on Keras 2 after upgrading to TensorFlow 2.16+, we can configure your TensorFlow installation so that [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) points to tf_keras. To achieve this:

- Make sure to install tf_keras. Note that TensorFlow does not install it by default.
- Export the environment variable TF_USE_LEGACY_KERAS=1.

 The following changes have been made as per [TensorFlow + Keras 2 backwards compatibility](https://keras.io/getting_started/):

- Added `pip install tf_keras` command to install the required package.
- Added import statements for `os`, `numpy`, and `tensorflow`
- Set the environment variable `TF_USE_LEGACY_KERAS to "1"` to ensure compatibility with legacy Keras.

These changes are reflected in the example section to provide a complete and functional code snippet for users. if you've any feedback or suggestions for these changes please feel free to let me know. Thank you.

Changes looks like below now :
```
>>> pip install tf_keras
>>> import os
>>> import numpy as np
>>> import tensorflow as tf
>>> os.environ["TF_USE_LEGACY_KERAS"] = "1"

>>> x = tf.constant([[2.0, 3.0], [1.0, 4.0]])
>>> targets = tf.constant([[1.], [-1.]])
>>> dense = tf.keras.layers.Dense(1)
>>> dense.build([None, 2])
>>> with tf.autodiff.ForwardAccumulator(
...    primals=dense.kernel,
...    tangents=tf.constant([[1.], [0.]])) as acc:
...   loss = tf.reduce_sum((dense(x) - targets) ** 2.)
>>> acc.jvp(loss)
<tf.Tensor: shape=(), dtype=float32, numpy=...>
```

2024-12-19 13:24 UTC, mihaimaruseac requested changes
We don't need these installs in the doctest examples. It is assumed the environment is already properly set up.

Otherwise, we'd need to repeat these instructions on all examples and then that would be too much repetition, too much noise, distracting from what the example should show.

Thank you for the PR, but we cannot take this.

2024-12-19 13:24 UTC, mihaimaruseac commented on tensorflow/python/eager/forwardprop.py
> +  >>> pip install tf_keras
This is not a line that can be executed in the Python interpreter

2024-12-19 13:24 UTC, closed without merging

2025-09-02 11:35 UTC, aiswaryasankar commented
**🔒 Entelligence AI Vulnerability Scanner**

✅ **No security vulnerabilities found!**

Your code passed our comprehensive security analysis.

📊 **Files Analyzed**: 1 files

---

2025-09-29 12:56 UTC, aiswaryasankar commented
**🔒 Entelligence AI Vulnerability Scanner**

❌ Security analysis failed: Security analysis failed: context deadline exceeded: This error is likely due to exceeding 'timeoutMs' — the total time a long running request (like process or directory watch) can be active. It can be modified by passing 'timeoutMs' when making the request. Use '0' to disable the timeout.

2025-09-29 13:28 UTC, mihaimaruseac commented
@aiswaryasankar this is spam and goes against TF's and GitHub's codes of conduct.