Fix crash of transpose
tensorflow/tensorflow pull request #83372
Opened 2024-12-20 02:42 UTC by cybersupersoap

This PR tries to address the issue raised in https://github.com/tensorflow/tensorflow/issues/76036 where `transpose` will crash when `perm` is assigned negative value. Based on a closed PR https://github.com/tensorflow/tensorflow/pull/63064

2024-12-25 13:17 UTC, cybersupersoap commented
Hi @rdzhabarov,  Could you please review my PR? Thank you!

2024-12-26 02:15 UTC, cybersupersoap commented
Hi @keerthanakadiri , Could you please review my PR? Thank you!

2025-01-11 02:44 UTC, cybersupersoap commented
Hi @sagunb, Could you please review my PR? Thank you!

2025-01-11 15:43 UTC, mihaimaruseac approved these changes
Thank you!

2025-01-29 16:05 UTC, mihaimaruseac requested changes
`//tensorflow/lite/testing:zip_test_transpose` is failing. Can you fix please?

2025-02-19 07:22 UTC, cybersupersoap commented
@mihaimaruseac Sorry for the late reply. I've changed the code to make it pass the tests. Could you please review it?

2025-02-19 13:26 UTC, mihaimaruseac approved these changes, later dismissed

2025-02-19 13:55 UTC, mihaimaruseac approved these changes

2025-02-24 18:49 UTC, merged