Tensorboard smoothing 1st order lag filter
tensorflow/tensorflow pull request #8363
Opened 2017-03-13 17:20 UTC by jyegerlehner

@dandelionmane  This is an alternative to [PR7891](https://github.com/tensorflow/tensorflow/pull/7891). 

It replaces the use of a moving average window with a simple first-order lag filter. It has a few advantages: 1) A bit less code. 2) It doesn't require visiting a potentially large number of values in the window to be averaged when computing each smoothed value. 3) The degree of smoothing doesn't change when you get near the end of the curve.

I left the changes in the html file so you could just run it without having to rebuild.

Here's what it does on the same data shown in the other PR.
![p_alt](https://cloud.githubusercontent.com/assets/2138320/23866631/64b05b3a-07e7-11e7-9fe8-24cd4668011c.png)

2017-03-15 01:29 UTC, teamdandelion requested changes
Overall, looks good! We actually used to have this smoothing (also known as exponentially weighted moving average), but we switched away from it because it was too biased near the start of the sequence (the first point implicitly has a very high weight). This was unfortunate because often with loss curves the first point is also an extreme outlier.

However, I'm working on another change that will filter out outlier data, when computing the y-scale domain, so the outlier won't matter as much visually, and that makes EMA a nice approach to smoothing.

2017-03-15 01:29 UTC, dandelionmane commented on tensorflow/tensorboard/components/vz_line_chart/vz-line-chart.ts
> +          }
I think it is cleaner as:

```
let last = data.length > 0 ? data[0].scalar : NaN;
data.forEach((d) => {
  if (!_.isFinite(last)) {
    d.smoothed = d.scalar;
  } else {
    d.smoothed = last * smoothingWeight + (1 - smoothingWeight) * d.scalar;
  }

  last = d.smoothed;
}

2017-03-16 10:23 UTC, jyegerlehner commented on tensorflow/tensorboard/components/vz_line_chart/vz-line-chart.ts
> +          }
Thanks; updated.

2017-03-16 10:36 UTC, jyegerlehner commented
There is another reason I think this kind of filtering is superior. The moving-average window filter currently implemented averages over a window centered on the current point, and so in general the "kernel radius" stretches forward to include future data, making it non-causal. In the common use case where you've got a training loss curve, you make a hyper-param or other change, and restart training, and then you want to compare how training progresses relative to the previous iteration. The previous iteration's loss curve you are comparing to stretches out into the future, which is reflected in its curve. However for the currently-executing training, the future loss values don't exist yet so you can't directly compare the latest smoothed curve values of the currently-executing training loss to that of the previous iterations. 

That problem doesn't apply with this kind of smoothing. In the case of this PR, the smoothed curves are always causal, so you can compare previous iterations' curves to the current iteration's curve at every point, right up to the most recent data. Sure, it has some lag, but the lag is the same for all the curves.

Hope that makes sense.

2017-03-22 07:05 UTC, martinwicke commented
@dandelionmane what's the plan with this and #7891?

2017-03-22 20:42 UTC, teamdandelion approved these changes

2017-03-22 20:43 UTC, dandelionmane commented
LGTM. Please fix the conflicts (you can just port the changes into the new tf-tensorboard.html) and then we'll merge.

2017-03-23 21:25 UTC, dandelionmane commented
Or you can just revert the conflicting file and wait for us to update it.

2017-03-23 22:48 UTC, jyegerlehner commented
OK thanks; I reverted html file.

2017-03-24 18:57 UTC, martinwicke commented
Jenkins, test this please.

2017-03-27 17:11 UTC, merged

2017-04-06 00:13 UTC, cancan101 commented
Not sure if this "issue" was introduced by this PR, but this seems odd to me:
![image](https://cloud.githubusercontent.com/assets/51059/24732034/1a9ebe26-1a3c-11e7-9399-f85c8cfea9ac.png)
The smoothed line (dark purple is not defined for the last N steps). If the implication is that smoothing cannot be calculated for these values, then I would argue the same should apply for the first N steps as well. 

Rather I would prefer smoothing to be defined all the way to the left and right with a reduced window (which is what I assume happens initially) on both sides.

2017-04-07 00:44 UTC, jyegerlehner commented
@cancan101 I checked and tf-tensorboard.html in 1.1 does not yet reflect the changes made in this PR (as of this writing), and that's the file that determines the behaviour one sees when running tensorboard. It would show up in the `resmoothDataset` method in tf-tensorboard.html which needs to be regenerated from the underlying .ts file that was changed as a part of this PR. There are instructions on how to do that somewhere under the tensorboard source subtree. 

The problem you show (I think) is one of the things this PR was meant to correct. 

A simple hack that may be easier than regenerating the `tf-tensorboard.html` properly, is to replace the `resmoothDataset` function in `tf-tensorboard.html` with the version of the function that's in  `tensorflow/tensorboard/components/vz_line_chart/vz-line-chart.ts `. At least I think that worked for me.