Adds f16 and bf16 type support for tfl.strided_slice, tfl.gather_nd, tfl.gather and tfl.less ops
tensorflow/tensorflow pull request #83717
Opened 2024-12-26 05:00 UTC by RahulSundarMCW

2024-12-26 06:31 UTC, amrinfathima-mcw commented
Hi @keerthanakadiri, can you please add @vamsimanchala as the reviewer for the PR? Thanks!

2025-02-02 18:03 UTC, vamsimanchala approved these changes

2025-02-10 16:56 UTC, vamsimanchala approved these changes

2025-02-19 18:57 UTC, vamsimanchala approved these changes

2025-03-18 21:14 UTC, vamsimanchala approved these changes, later dismissed

2025-03-19 10:46 UTC, qukhan requested changes

2025-03-20 07:09 UTC, mihaimaruseac approved these changes

2025-03-20 09:49 UTC, qukhan approved these changes

2025-03-20 13:42 UTC, merged