NADAM Optimizer
tensorflow/tensorflow pull request #8405
Opened 2017-03-14 18:31 UTC by louiehelm

Implements Nadam - a published variant of Adam Optimizer with Nestov momentum

Same basic algorithm used by the Nadam Optimizer in Keras (https://keras.io/optimizers/#nadam) but implemented from scratch by me for TF's dense / gpu kernels

Cites academic references for source algorithms

2017-03-14 18:48 UTC, girving commented
I'm not the right person to review this.  Maybe @lukaszkaiser?

2017-03-14 19:14 UTC, lukaszkaiser commented
Please do not add any C++ kernels. We're happy to add NAdam, but please make a python-only implementation and put it in contrib/opt, preferably subclassing AdamOptimizer. For an example, see the LazyAdam implemented in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/opt/python/training/lazy_adam_optimizer.py

2017-03-14 19:18 UTC, lukaszkaiser commented
To be clear: the reason for requesting a different implementation is maintenance. We cannot commit to maintaining and testing a separate C++ kernel for every paper that comes out -- that's why modular ops written in python are preferable, except if it's really not practical (e.g., much slower, but I doubt it will be the case here). Putting things in contrib first is necessary because we commit to core APIs so things need to get some use first, before they get moved to contrib.

2017-03-14 19:32 UTC, louiehelm commented
Thanks Lukasz! Can do.

2017-03-15 03:24 UTC, cancan101 commented
This closes: https://github.com/tensorflow/tensorflow/issues/7715

2017-03-18 01:33 UTC, louiehelm commented
@lukaszkaiser I re-implemented Nadam in pure python but it's a lot slower. Wish there was a way to accept the same amount of C++ that's used in all the other optimizers.

2017-03-18 01:39 UTC, lukaszkaiser commented
This is interesting. Could we pinpoint why it's slow? Maybe we can change the existing adam C++ kernels to accept some flags to make them more general? If we knew the exact reason, maybe we could make implementation of other optimizers fast as well. For example, there is LazyAdam in tf.contrib.opt, is it slow too?

2017-03-18 01:52 UTC, louiehelm commented
Yes, LazyAdam is slow as well.

2017-03-18 01:58 UTC, lukaszkaiser commented
We should make both fast, best if it can be done somehow together. Do you have an idea how that could be done?

2017-03-18 08:49 UTC, olesalscheider commented
A flag seems reasonable for Nadam. MomentumOptimizer also has a `use_nesterov` flag to use Nesterov Momentum.

But it would of course be good to know why the python implementation is slower. Can you profile it?

2017-03-18 10:28 UTC, louiehelm commented
The performance gap disappears when I enable XLA. I currently profile my code with XLA traces. What's a way I could detect this issue? TFDBG?

2017-03-18 23:40 UTC, gmbender commented
@louiehelm Both AdamOptimizer and LazyAdamOptimizer implement dense updates using C++ op kernels, and implement sparse updates using standard TensorFlow ops like gather() and scatter_update(). Furthermore, the code for handling dense updates is shared between both optimizers. So if you're seeing a slow-down going from Adam to LazyAdam, I suspect that it's for other reasons.

While LazyAdamOptimizer is several times faster than AdamOptimizer for my use-case (which involves training embedding matrices with sparse updates), I've noticed that my model training jobs get lower throughput with LazyAdam than they do with RMSProp or Adagrad. At peak throughput, my training jobs get around 1600 steps/second with Adagrad, 1550 steps/second with RMSProp, and 1250 steps/second with LazyAdam. Even with lower throughput, LazyAdam consumes more CPU on the parameter servers than Adagrad/RMSProp. It's possible that this is just because Adam is more compute-intensive than the other two algorithms (especially Adagrad). But the fact that Adagrad and RMSProp use C++ op kernels to handle sparse as well as dense updates might also have something to do with it.

I also suspect that the current implementation of Nadam is likely to get poor throughput for jobs that train sparse embedding matrices, for exactly the same reason that AdamOptimizer gets poor throughput. This part of the _apply_sparse() function is likely to be a bottleneck:
```
m_t = state_ops.assign(m, m * beta1_t,
                       use_locking=self._use_locking)
m_t = state_ops.scatter_add(m_t, grad.indices, (tp1 / tp) * m_scaled_g_values,
                            use_locking=self._use_locking)
```
The `assign` op will touch every single row of the embedding matrix, even if not all of the rows appear in the current batch of training examples. It's always possible to add a LazyNadamOptimizer subclass in the future, as we did with LazyAdam, but I wonder if there's a better solution.

2017-03-22 07:23 UTC, martinwicke commented
@louiehelm could you sign the CLA? We cannot otherwise proceed.

2017-03-22 18:06 UTC, louiehelm commented
@martinwicke are you gonna pull my code? :D

I can sign a CLA, but umich.edu's Google service is down right now. Don't suppose you go across campus and fix that for me??

2017-03-23 22:10 UTC, louiehelm commented
@googlebot I signed it!

2017-04-10 17:14 UTC, drpngx commented
@louiehelm could you respond to @gmbender concerns?

@lukaszkaiser other than that, does that look good?

2017-04-10 19:35 UTC, lukaszkaiser commented
I'd like to be sure that it implements sparse updates similar to LazyAdam, it's much faster for large vocabulary embedding. Other that it looks fine to me, happy to get this in.

2017-04-11 04:06 UTC, louiehelm commented
Patched m_t calculations as @gmbender suggested. Also patched v_t calculation and variable update below it since all 3 areas in LazyAdam are much more careful about not touching the whole matrix.

Should be ready to go.

2017-04-11 16:27 UTC, lukaszkaiser commented
Feels good to me. Someone with more C++ experience could review, or maybe it's fine.

2017-04-11 18:03 UTC, drpngx requested changes
I only looked at the C++

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +    //const T l_warmer = gamma(); //* (T(1)-T(0.5)*beta2_power());
remove

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +//    var.device(d) -= (m * alpha) / (v.sqrt() + epsilon());
remove

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +    var.device(d) -= ( ( (T(1) - gamma()) * m + gamma() * grad) * alpha )
no space before and after parens. Use clang-format if unsure.

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +    const T alpha2= Eigen::numext::sqrt(T(1) - beta2_power()*beta2()) /
Space before =

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +                    (T(1) - beta1_power());
Here and below: static_cast<T>(1) conforms to the style guide. Since you're using that a lot, you might want to define a static function for that.

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +  void operator()(const Device& d, typename TTypes<T>::Flat var,
Re-order the arguments so that the output appears last: var, m, v. (Same below)

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +
remove extra space

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +    auto locks = MaybeLockMutexesInOrder(ctx, use_exclusive_lock_, {0, 1, 2});
const

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +
remove extra space

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +    const Tensor& grad = ctx->input(10);
FYI, the numeric indexing (rather than by name) is somewhat deprecated. You have a lot of arguments here.

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +                                        var.shape().DebugString(), " ",
" vs " for readability. Here and below

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +
remove extra space

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +#endif
// TENSORFLOW_USE_SYCL

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +#endif
// GOOGLE_CUDA
(remember to put two spaces before)

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +    OP_REQUIRES(ctx, TensorShapeUtils::IsScalar(beta1_power.shape()),
Could we refactor so that we have less duplicated code? OP_REQUIRES(ctx, CheckScalarShape("beta1_power", beta1_power));

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +    OP_REQUIRES(ctx, var.shape().IsSameSize(m.shape()),
Same here, and marshal into the same validation function as RAdam

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops.cc
> +using CPUDevice = Eigen::ThreadPoolDevice;
remove this and move the first declaration all the way up

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/kernels/training_ops_gpu.cu.cc
> +                     ((gamma.constant(one) - gamma).reshape(single).broadcast(bcast) * m  +  (gamma).reshape(single).broadcast(bcast) * grad)
Fit in 80 chars

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/ops/training_ops.cc
> +
remove spaces

2017-04-11 18:03 UTC, drpngx commented on tensorflow/core/ops/training_ops.cc
> +  TF_RETURN_IF_ERROR(c->WithRank(c->input(9), 0, &unused));  // gamma
remove numeric indexing, use c->input("gamma")

2017-04-11 18:03 UTC, drpngx commented on tensorflow/python/training/adam.py
> +  [Dozat 2015]  “Incorporating Nesterov momentum into Adam,”
Use regular quotes

2017-04-11 20:25 UTC, drpngx commented
Thanks! Please address the rest of comments.

2017-04-11 21:18 UTC, louiehelm commented
@drpngx Thanks for your feedback.

As you see, I implemented all the proper formatting changes you suggested.

However the optimizers in TF (i.e., Adam, Adagrad, RMSProp, etc) all have the exact same "code-related" issues you're flagging my code for:

- argument ordering
- consts best practices
- argument indexing
- code-reuses + quote misuse in validation sections
- and GPU section formatting

If I implement any of your remaining suggestions in just my code, Nadam will be the only optimizer following these new conventions. I'd prefer not to make Nadam's conventions deviate from all the other optimizers.

Are you open to me re-factoring and modifying all the optimizers in Tensorflow to address your complaints with them?

How about we build, test, and pull this PR first with all the optimizers having uniform conventions for the moment.

I'm happy to help you address these remaining issues separately though. I'm also dissatisfied with how this C++ is organized. Let's flag all these deficiencies you've found (with all the C++ optimizers) in a separate Issue. Give me a shout on that thread and I'll come over and start working on a new branch to refactor all of TF's optimizers. Then I can submit a second PR for that.

2017-04-12 01:35 UTC, drpngx approved these changes

2017-04-12 01:36 UTC, drpngx commented
OK, sounds good to me.

Jenkins, test this please.

2017-04-12 01:43 UTC, drpngx commented
There are [lint errors](https://ci.tensorflow.org/job/tensorflow-pull-requests-sanity/3883/console):

```
tensorflow/python/training/adam.py:241: [E1003(bad-super-call), NadamOptimizer.__init__] Bad first argument 'AdamOptimizer' given to super()

tensorflow/python/training/adam.py:349: [E1003(bad-super-call), RadamOptimizer.__init__] Bad first argument 'AdamOptimizer' given to super()
```

2017-04-12 17:19 UTC, louiehelm commented
@drpngx Lint errors fixed

2017-04-12 18:16 UTC, drpngx commented
Jenkins, test this please.

2017-04-12 18:35 UTC, drpngx commented
Looks like there are some build errors.

```
11:18:41 tensorflow/core/kernels/training_ops.cc: In member function 'void tensorflow::functor::ApplyNadamNonCuda<Device, T>::operator()(const Device&, typename tensorflow::TTypes<T>::Flat, typename tensorflow::TTypes<T>::Flat, typename tensorflow::TTypes<T>::Flat, typename tensorflow::TTypes<T>::ConstScalar, typename tensorflow::TTypes<T>::ConstScalar, typename tensorflow::TTypes<T>::ConstScalar, typename tensorflow::TTypes<T>::ConstScalar, typename tensorflow::TTypes<T>::ConstScalar, typename tensorflow::TTypes<T>::ConstScalar, typename tensorflow::TTypes<T>::ConstFlat)':
11:18:41 tensorflow/core/kernels/training_ops.cc:305:34: error: 'alpha' was not declared in this scope
11:18:41      var.device(d) -= (m * lr() * alpha) / (v.sqrt() + epsilon());
```

2017-04-12 18:39 UTC, drpngx commented
Jenkins, test this please.

2017-04-12 19:39 UTC, merged

2017-04-13 13:43 UTC, caisq commented
This change seems to have caused api_compatibility_test failure. https://ci.tensorflow.org/view/Tensorflow%20Jenkins%20Monitored%20builds/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/456/consoleFull

```
ERROR:tensorflow:3 differences found between API and golden.
ERROR:tensorflow:Issue 1	: New object tensorflow.train.RadamOptimizer found (added).
ERROR:tensorflow:Issue 2	: Change detected in python object: tensorflow.train.
ERROR:tensorflow:Issue 3	: New object tensorflow.train.NadamOptimizer found (added).
F.
```

cc @martinwicke, @josh11b on how to proceed.

2017-04-13 15:52 UTC, martinwicke commented
We should revert this. I thought this was supposed to go into contrib/opt, which I think is the right spot, unless there's a strong reason to put it directly into core.

2017-04-13 15:58 UTC, drpngx commented
SG. Yes I missed this too 😯

On Apr 13, 2017 8:54 AM, "Martin Wicke" <notifications@github.com> wrote:

We should revert this. I thought this was supposed to go into contrib/opt,
which I think is the right spot, unless there's a strong reason to put it
directly into core.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/pull/8405#issuecomment-293936122>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AT_SbdHyX6G5dTsaaQKuahCtAnT9I8iNks5rvkUogaJpZM4Mc-v0>
.