Some minor optimizations for speeding up nearest neighbor resize.
tensorflow/tensorflow pull request #8444
Opened 2017-03-15 19:40 UTC by panmari

By removing loop over channels. Impact mainly visible for more than 3
channels. Numbers for benchmark with 6 channels:

Before:
Benchmark                                        Time(ns) Iterations
--------------------------------------------------------------------
BM_Resize_ResizeNearestNeighbor_cpu_10_499_499   53222200        100  280.7M items/s

After:
Benchmark                                        Time(ns) Iterations
--------------------------------------------------------------------
BM_Resize_ResizeNearestNeighbor_cpu_10_499_499   44504450        100  335.7M items/s

2017-03-15 22:04 UTC, jhseu commented on tensorflow/core/kernels/resize_nearest_neighbor_op.cc
> +          output_data_ptr = std::copy_n(input_yx_ptr, st.channels, output_data_ptr);
Just call memcpy instead?
```c++
memcpy(&output_data(b, y, x, 0), &input_data(b, in_y, in_x, 0), sizeof(T)*st.channels);
```

See here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/slice_op.cc#L154

2017-03-15 22:04 UTC, jhseu commented
Can you also add the BUILD rule for this benchmark? Doesn't seem to be there.

2017-03-15 22:26 UTC, jhseu commented
Alternatively, you can use std::copy_n there instead of memcpy too.

2017-03-15 22:32 UTC, jhseu commented
Two other things: can you also benchmark on GPU, and can you do best of 5 runs?

2017-03-16 19:23 UTC, panmari commented
My change doesn't touch any code that runs on GPU. Nevertheless, I ran the full benchmark 5 times on master and with this patched, see https://gist.github.com/panmari/4b495af0c383c26c1c50435d055c05a5. New version is consistently about 10% faster.

2017-03-20 19:04 UTC, panmari commented
Rebased on master.

2017-03-21 00:54 UTC, jhseu commented
There's a much simpler version that gets the performance benefit:
```c++
    for (int b = 0; b < st.batch_size; ++b) {
      for (int y = 0; y < st.out_height; ++y) {
        const int64 in_y =
            std::min(static_cast<int64>(floorf(y * st.height_scale)),
                     (st.in_height - 1));
        for (int x = 0; x < st.out_width; ++x) {
          const int64 in_x =
              std::min(static_cast<int64>(floorf(x * st.width_scale)),
                       (st.in_width - 1));
          std::copy_n(&input_data(b, in_y, in_x, 0), st.channels, &output_data(b, y, x, 0));
        }
      }
    }
```

2017-03-21 00:54 UTC, jhseu requested changes
See my comment above.

2017-03-21 20:36 UTC, panmari commented
Thanks for the hint! The simplified version you proposed gave very similar benchmark results, so I adapted my pull request accordingly.

2017-03-21 20:39 UTC, jhseu approved these changes

2017-03-21 20:39 UTC, jhseu commented
Jenkins, test this please

2017-03-22 07:28 UTC, merged