Move module-level comment out of _RNNCell class
tensorflow/tensorflow pull request #8458
Opened 2017-03-16 09:01 UTC by tgy

The _RNNCell class docstring contained a description of the module
itself. I moved it back to the module's docstring.
I also fixed a comment that wasn't correctly indented.

2017-03-16 16:09 UTC, jhseu commented
Perhaps the comment belongs in `tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py` instead?

2017-03-20 10:38 UTC, tgy commented
@jhseu what's the rationale behind the existence of both `tensorflow/python/ops/rnn_cell_impl.py` and `tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py`? why not merge them in a single file?

2017-03-21 00:22 UTC, jhseu commented
contrib specifies APIs that aren't stable yet. Some parts of the RNN API have stabilized, and others haven't.

2017-03-22 07:44 UTC, martinwicke requested changes

2017-03-22 07:44 UTC, martinwicke commented on tensorflow/python/ops/rnn_cell_impl.py
> +below and implement `__call__` with the following signature.
The text isn't quite right for a module docstring, and not quite right for a class docstring. Can you disentangle the two?

2017-03-22 09:48 UTC, tgy commented on tensorflow/python/ops/rnn_cell_impl.py
> +below and implement `__call__` with the following signature.
Done.

2017-03-22 16:22 UTC, martinwicke approved these changes

2017-03-22 16:23 UTC, martinwicke commented
Jenkins, test this please.

2017-03-22 16:28 UTC, merged

2017-03-23 09:17 UTC, tgy commented
Great! Maybe close this?

2017-03-23 16:14 UTC, martinwicke commented
It is merged already.