Checkpoints default values for RunConfig
tensorflow/tensorflow pull request #8488
Opened 2017-03-17 07:20 UTC by Immexxx

With save_checkpoints_secs having a default value (of 600), the call to RunConfig fails if only save_checkpoints_steps is passed. To address this, the value is defaulted only if both the parameters are None. In this new way, the call to RunConfig will not fail if only save_checkpoints_steps is passed

2017-03-17 18:27 UTC, ispirmustafa reviewed
If both of them None, that means user disables the saving. This change prevents that. Instead you can use a constant _USE_DEFAULT. if it's _USE_DEFAULT and not steps then set it to 600. if it's _USE_DEFAULT and steps then set it to None.

2017-03-17 18:28 UTC, ispirmustafa requested changes
If both of them None, that means user disables the saving. This change prevents that. Instead you can use a constant _USE_DEFAULT. if it's _USE_DEFAULT and not steps then set it to 600. if it's _USE_DEFAULT and steps then set it to None.

2017-03-17 21:26 UTC, ispirmustafa approved these changes
Thanks

2017-03-17 21:32 UTC, Immexxx commented
@ispirmustafa  - Thanks for the review

2017-03-22 15:30 UTC, martinwicke commented
Jenkins, test this please.

2017-03-22 15:59 UTC, martinwicke commented
Jenkins, test this please.

2017-03-22 16:20 UTC, martinwicke commented
Please fix the test failures. `_USE_DEFAULT` must be qualified (as `RunConfig._USE_DEFAULT`).

2017-03-24 18:45 UTC, Immexxx commented
@martinwicke Thanks. Will do

2017-03-26 00:54 UTC, martinwicke commented
Jenkins, test this please.

2017-03-27 17:10 UTC, merged