Fixed `needs_broadcasting` expression in tf.layers.normalization
tensorflow/tensorflow pull request #8537
Opened 2017-03-19 16:51 UTC by sugyan

in Python3, `range()` function doesn't create lists, so `[0, 1, 2] != range(4)[:-1]` always returns `True`.

2017-03-22 15:36 UTC, martinwicke commented
Thanks for this fix. Can you add a test that would have failed? Clearly this code isn't tested well.

2017-03-22 15:36 UTC, martinwicke requested changes
Please add a test for this behavior.

2017-03-23 17:01 UTC, sugyan commented
I am sorry for a miscellaneous pull-request with no test code.
I just pointed out a programming mistake.

I read the code and checked its behavior, but in `normalization.py`,` axis` in initializer is a single integer and `len(reduction_axes)` is always equal to `len(input_shape) - 1`, so the calculation results will be exactly the same regardless of the value of `needs_broadcast`...
I'm wondering if this variable is really necessary.

2017-03-24 00:11 UTC, martinwicke commented
Jenkins, test this please.

2017-03-24 18:22 UTC, martinwicke approved these changes

2017-03-24 18:22 UTC, martinwicke commented
Fine. This is a clear improvement. Thanks!

2017-03-24 18:22 UTC, merged