Clarify and correct Android Sections in WORKSPACE
tensorflow/tensorflow pull request #8689
Opened 2017-03-24 10:55 UTC by jubjamie

Build Tools version updated to latest version shipping with Android Studio.
Added some comments to clarify both this and NDK Level details that have been causing confusion.
Both of these have caused problems within Android studio so these edits should avoid the build tools error.

2017-03-24 10:59 UTC, jubjamie commented
I signed it!

2017-03-24 11:05 UTC, jubjamie commented
Added commit for build.gradle to match the build tools version change.

2017-03-24 18:55 UTC, petewarden commented
Andrew, can you take a look at this? Thanks!

2017-03-24 19:08 UTC, andrewharp requested changes
The build_tools_version also need to be updated in 
tensorflow/tools/ci_build/Dockerfile.android and tensorflow/contrib/android/cmake/build.gradle, thanks

2017-03-24 19:08 UTC, andrewharp commented on WORKSPACE
> +#Note that API level is not the same as NDK version.
Can you sink to the latest version please and move this line above the newly added NDK comment? It's also missing a space after the #

2017-03-24 19:08 UTC, andrewharp commented on WORKSPACE
> +#    #Check your build tools version. Android Studio is shipping with 25.0.2 currently.
Is this correct? I see 25.0.4 in Android Studio now.

In any case I would:
1 ) move the comment above the build_tools_version line
2) rephrase it to say "# Ensure that you have a matching version of build_tools installed, as the SDK default changes periodically."

2017-03-24 19:37 UTC, jubjamie commented on WORKSPACE
> +#Note that API level is not the same as NDK version.
Sync to the latest version of what sorry? Tf? 1.1?
I will look at your comments on Monday and I'll get back to it then. I can also make similar edits to the previously mentioned files too if you want?

2017-03-24 20:06 UTC, andrewharp commented on WORKSPACE
> +#Note that API level is not the same as NDK version.
Yes, TF master. I made some edits to this file internally to add comments here as well, and those changes have been pushed since you made your edits.

2017-03-27 08:52 UTC, jubjamie commented on WORKSPACE
> +#    #Check your build tools version. Android Studio is shipping with 25.0.2 currently.
After updating I only see 25.0.2 in AS within SDK manager and within my files on this ubuntu version of AS. I like your rephrasing as it allows for those differences.

2017-03-27 08:58 UTC, jubjamie commented on WORKSPACE
> +#Note that API level is not the same as NDK version.
I have made those changes.

2017-03-27 09:12 UTC, jubjamie commented
@andrewharp Those changes have been made however I am wondering whether it will break people's production environments? As a new starter with a fresh copy of android studio, I have one version of build_tools but others may still be on a previous version and this change may cause issues? This works both ways though as otherwise it breaks fresh builds on fresh android studio version. Although, curiously, you see a different build_tools_version to me and I've tried to update it! Thoughts?

2017-03-29 18:16 UTC, andrewharp commented on WORKSPACE
> +#    # This needs to be 14 or higher to compile TensorFlow. Note NDK version is not the API level.
s/Note/Note that/

2017-03-29 18:16 UTC, andrewharp commented on WORKSPACE
> +#    #Ensure that your build_tools_version (below) the SDK manager version as it updates periodicaly.
\# Ensure that you have the build_tools_version below installed in the SDK manager as it updates periodically.

2017-03-29 18:16 UTC, andrewharp commented on tensorflow/tools/ci_build/Dockerfile.android
> +#Build Tools Version liable to change.
missing space after #

2017-03-29 18:26 UTC, jubjamie reviewed
Changes reviewed and implemented.

2017-03-29 18:27 UTC, andrewharp commented on WORKSPACE
> +#    # This needs to be 14 or higher to compile TensorFlow. Note that NDK version is not the API level.
Sorry, this should be "Note that the NDK version is not the API level."

2017-03-29 18:28 UTC, andrewharp commented on WORKSPACE
> +#    # Ensure that you have the build_tools_version below installed in the SDK manager as it updates periodically.
line wrap at 80 characters

2017-03-29 18:32 UTC, jubjamie reviewed
Line Wrap implemented

2017-03-29 18:45 UTC, andrewharp commented on WORKSPACE
> +
extra blank line and missing "the"

2017-03-29 19:01 UTC, jubjamie reviewed
Requested changes made + new line for line wrapping.

2017-03-29 19:04 UTC, andrewharp approved these changes

2017-03-30 01:08 UTC, yifeif commented
@tensorflow-jenkins test this please

2017-03-30 10:19 UTC, jubjamie commented
Do I need to do anything to address the failed builds? I'm not sure they are failing and, considering how basic the changes were i'm not sure if there's anything I could do!
Thanks

2017-03-30 17:04 UTC, yifeif commented
@jubjamie thanks for asking. The failure looks like a flake. Running @tensorflow-jenkins test this please.

2017-03-30 17:07 UTC, jubjamie commented
@yifeif Hmmm ok i'll let Jenkins do his thing! Thanks

2017-03-30 17:20 UTC, yifeif commented
@tensorflow-jenkins test this please.

2017-03-30 18:04 UTC, merged