Fix doc for CTC_Greedy
tensorflow/tensorflow pull request #8690
Opened 2017-03-24 11:08 UTC by Garvys

The output is the minus the sum of the logits and the logprobs

2017-03-24 11:12 UTC, Garvys commented
I signed it!

2017-03-24 18:30 UTC, martinwicke requested changes

2017-03-24 18:30 UTC, martinwicke commented on tensorflow/python/ops/ctc_ops.py
> +        sequence found, minus the sum of the greatest logits.
This sentence seems to be missing something

2017-03-24 18:30 UTC, martinwicke commented
Jenkins, test this please.

2017-04-10 17:29 UTC, drpngx commented
@Garvys feel free to address the comments.

2017-04-25 15:45 UTC, martinwicke approved these changes

2017-04-25 15:45 UTC, martinwicke commented
Jenkins, test this please.

2017-04-25 17:36 UTC, drpngx commented
Ignoring flaky `queue_runner_test`.

2017-04-25 17:36 UTC, merged