Thread-safe implementations of MKL kernels and rerolling changes lost in previous merge
tensorflow/tensorflow pull request #8816
Opened 2017-03-29 18:47 UTC by jbobba

- Changes to mkl_matmul BUILD rule so it is built as part of the matmul kernel library
- Bug fixes to MKL kernels for thread-safety
- Adding a TF to MKL dimension ordering map to track dimension order of MKL tensors.
- Rerolling changes to MKL layout pass, mkl_util.h, nn_ops.cc and BUILD files that got lost with parallel merges

2017-03-29 19:04 UTC, yifeif commented
@jbobba thanks for the PR. Could you resolve the conflicts? @rmlarsen mind taking a look?

2017-03-29 22:42 UTC, martinwicke commented
I moved the if_mkl into tf_cc_test_mkl. So that part of the change shouldn't be necessary.

2017-03-29 23:09 UTC, jbobba commented
@martinwicke do you have that change coming in from a different branch or should I remove the if_mkl in this PR?

2017-03-29 23:30 UTC, jbobba commented
@martinwicke never mind. I checked the definition of tf_cc_test_mkl

2017-03-30 18:33 UTC, andydavis1 approved these changes

2017-03-31 17:04 UTC, jbobba commented
Can we start the tests on this?

2017-03-31 17:06 UTC, martinwicke commented
Jenkins, test this please.

2017-03-31 17:09 UTC, martinwicke requested changes

2017-03-31 17:09 UTC, martinwicke commented on tensorflow/core/kernels/BUILD
>      tf_kernel_library(
Could you make a tf_mkl_kernel_library and pull the if_mkl inside it? Buildozer has a bug which prevents us from inspecting/changing anything inside a top-level if, so pulling the if inside the new rule would make it a lot easier on our sync infra.

2017-03-31 17:09 UTC, martinwicke commented
One more thing related to the build.

2017-03-31 17:12 UTC, jbobba commented on tensorflow/core/kernels/BUILD
>      tf_kernel_library(
Will do.

2017-03-31 17:46 UTC, jbobba commented on tensorflow/core/kernels/BUILD
>      tf_kernel_library(
Can you rerun the tests?

2017-03-31 17:48 UTC, martinwicke commented
Jenkins, test this please!

2017-03-31 17:49 UTC, martinwicke approved these changes

2017-04-03 17:05 UTC, jbobba commented
Can we merge this in?

2017-04-03 17:08 UTC, merged