Windows: Fix cuda_configure.bzl for Bazel build
tensorflow/tensorflow pull request #8837
Opened 2017-03-30 11:40 UTC by meteorcloudy

1. Remove .bazelrc before creating it.
2. Add quote to environment variables
3. Return a dummpy value for gcc detection on Windows

@gunan @damienmg

2017-03-30 11:43 UTC, damienmg requested changes

2017-03-30 11:43 UTC, damienmg commented on configure
> +rm -f .bazelrc
Why remove it?

2017-03-30 11:48 UTC, meteorcloudy commented
This will help solve https://github.com/bazelbuild/bazel/issues/2753

2017-03-30 11:50 UTC, meteorcloudy commented on configure
> +rm -f .bazelrc
Otherwise, when you rerun ./configure, .bazelrc file will still contain the content produced by your last run, possibly with different env value.

2017-03-30 11:51 UTC, meteorcloudy commented on configure
> +rm -f .bazelrc
I am assuming ./configure is the only one who touchs .bazelrc, is that ok?

2017-03-30 11:56 UTC, damienmg commented
Since you have the sed_hyphen_i lines lower I think the assumption is that
it is not. We strip down the --action_env flag from the file instead of
deleting the file.

The user might do custom change to it.

On Thu, Mar 30, 2017 at 1:52 PM Yun Peng <notifications@github.com> wrote:

> *@meteorcloudy* commented on this pull request.
> ------------------------------
>
> In configure
> <https://github.com/tensorflow/tensorflow/pull/8837#discussion_r108905790>
> :
>
> > @@ -9,6 +9,7 @@ SOURCE_BASE_DIR=`pwd -P`
>  popd > /dev/null
>
>  # This file contains customized config settings.
> +rm -f .bazelrc
>
> I am assuming ./configure is the only one who touchs .bazelrc, is that ok?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/8837#discussion_r108905790>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADjHf_MoWrmYY0PzKYfPr7kV4Eq2Nq56ks5rq5eDgaJpZM4MuPNi>
> .
>

2017-03-30 12:38 UTC, meteorcloudy commented
@damienmg I see, but we didn't actually use `sed_hyphen_i` on `action_env`, now I added the code to strip the flags. Please take a look again.

2017-03-30 12:52 UTC, damienmg commented
https://github.com/tensorflow/tensorflow/pull/8637/files#diff-e2d5a00791bce9a01f99bc6fd613a39dR282

Apparently I missed that part when I rolled the change forward. You actually want to remove the action_env that you might set anywhere in that script unconditionally because if the user reconfigure he doesn't want to have stale entry in that file.

Maybe we should just do an "%import .action_env.bazelrc" and wipe that file out and put all the action env in it. That would simplify the sed code.

2017-03-30 13:32 UTC, meteorcloudy commented
Sounds good, where should I add the `%import .action_env.bazelrc` ?

2017-03-30 13:42 UTC, damienmg commented
top of the .bazelrc?

On Thu, Mar 30, 2017 at 3:34 PM Yun Peng <notifications@github.com> wrote:

> Sounds good, where should I add the %import .action_env.bazelrc ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/tensorflow/pull/8837#issuecomment-290411561>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADjHfzVndfighoFylkO3RzTiroBJZ6juks5rq69VgaJpZM4MuPNi>
> .
>

2017-03-30 17:08 UTC, meteorcloudy commented
@damienmg Thanks for the hint, I pushed another change for this.

2017-03-30 23:03 UTC, gunan commented
Jenkins, test this please.

2017-03-30 23:06 UTC, gunan commented on third_party/gpus/cuda_configure.bzl
> +    return "/usr/bin/dummycompiler"
Can we make this name like this, so users can understand what is going on if they use the wrong config to compile on windows?

Something like: `/use/--config x64_msvc_windows/instead`

2017-03-31 08:06 UTC, meteorcloudy commented on third_party/gpus/cuda_configure.bzl
> +    return "/usr/bin/dummycompiler"
Good idea, done!

2017-03-31 19:45 UTC, gunan commented
Change LGTM, Damien, any remaining comments?

2017-04-01 01:45 UTC, gunan approved these changes

2017-04-01 05:05 UTC, damienmg approved these changes

2017-04-01 05:20 UTC, gunan commented
I just added back bazel clean to configure script, so testing one more time to make sure.
Jenkins, test this please.

2017-04-01 06:14 UTC, merged