Introduce a new tool/function to visualize a pb model as requested by #8854
tensorflow/tensorflow pull request #8867
Opened 2017-03-31 11:46 UTC by jubjamie

Issue #8854 asked for a tool to easily visualize .pb models as graphs. I pointed out it was possible to do with Tensorboard so i've created a function to allow someone to pass a .pb model and a tensorboard log directory to then view the imported .pb graph.
I guess this is a temporary measure until a decision is made on creating something a bit more friendly.

Also, For some reason I think that this PR is including some previously merged commits and I don't know how to get rid of them on github! I thought i'd sync everything but i'm a bit rubbish at this. I guess those can be safely ignored. Thanks

2017-04-10 17:59 UTC, drpngx requested changes

2017-04-10 17:59 UTC, drpngx commented on tensorflow/python/tools/import_pb_to_tensorboard.py
> +def import_to_tensorboard(modeldir,logdir):
Could you make that a docstring?

2017-04-10 17:59 UTC, drpngx commented on tensorflow/python/tools/import_pb_to_tensorboard.py
> +# Created in response to issue #8854
remove this line

2017-04-10 17:59 UTC, drpngx commented on tensorflow/python/tools/import_pb_to_tensorboard.py
> +    model_filename =modeldir
add space after `=`.

2017-04-10 17:59 UTC, drpngx commented on tensorflow/python/tools/import_pb_to_tensorboard.py
> +  pbVisualWriter = tf.summary.FileWriter(logdir)
our style guide uses `pb_visual_writer`

2017-04-10 17:59 UTC, drpngx commented on tensorflow/python/tools/import_pb_to_tensorboard.py
> +# 	modeldir: The location of the .pb model to visualize
please explain at least one pb = protobuf

2017-04-12 11:06 UTC, jubjamie commented
@drpngx changes have been made. I'm unsure as to why my previous commits from a separate PR have ended up in here. Sorry for the delay in getting this out.

2017-04-26 22:56 UTC, dandelionmane commented
The change looks good to me. And, please make the comment into a docstring per @drpngx's request.

2017-04-26 23:00 UTC, jubjamie commented
Sorry what so you mean by docstring? Can you link an example?

2017-04-27 01:01 UTC, teamdandelion submitted a review, later dismissed
Looks good, please just make the comment into a docstring (https://www.python.org/dev/peps/pep-0257/)

2017-05-01 23:19 UTC, vrv commented
@dandelionmane @drpngx I made the changes for the user, PTAL

2017-05-01 23:26 UTC, drpngx approved these changes

2017-05-01 23:27 UTC, drpngx commented
Jenkins, test this please.

2017-05-02 00:29 UTC, merged