Allow SavedModelBuilder to overwrite existing folders
tensorflow/tensorflow pull request #8902
Opened 2017-04-02 03:46 UTC by alisidd

This adds the feature #8852 requested

2017-04-03 20:03 UTC, rohan100jain commented
Thanks for doing this!

2017-04-03 22:05 UTC, rajhans commented
thanks for adding this!

2017-04-03 22:13 UTC, alisidd commented
No problem! :)

2017-04-05 14:59 UTC, rohan100jain requested changes

2017-04-06 01:32 UTC, alisidd commented on tensorflow/python/saved_model/builder_impl.py
> +      overwrite: If `True` overwrites if a directory already exists
Done 👍

2017-04-06 01:53 UTC, rohan100jain approved these changes

2017-04-06 01:54 UTC, rohan100jain commented
@tensorflow-jenkins test this please

2017-04-06 04:30 UTC, merged

2017-04-06 20:29 UTC, martinwicke commented
Sorry, we have to revert this. It is breaking some tests we require (which were sadly not run yet).

2017-04-08 12:11 UTC, alisidd commented
@martinwicke Could you let me know what the problem was, so I could fix it?

2017-04-10 16:49 UTC, martinwicke commented
I'm sorry the initial advice was the other way around, but we had some more discussions about this and we're very certain that we do not want to make this easy. It's a bad idea (tm), take it from people who have lost lots of work to easy overwriting. 

You can always emulate the behavior by doing the delete_recursively manually, but that I would advise against. Ideally, timestamp your directories and symlink the latest.