set save_model_secs=60 in mnist_replica.py
tensorflow/tensorflow pull request #9040
Opened 2017-04-07 09:30 UTC by lvjiangzhao

This would make restoring from a checkpoint more easily. The default value for save_model_secs is 600 which is relatively too long for this tutorial example model.

2017-04-07 10:21 UTC, lvjiangzhao commented
I signed it!

2017-04-07 18:13 UTC, caisq requested changes

2017-04-07 18:13 UTC, caisq commented on tensorflow/tools/dist_test/python/mnist_replica.py
> +          save_model_secs=60,
This code here is for testing gRPC (distributed) sessions only. Can you explain why you need this change?

2017-04-07 18:21 UTC, caisq commented on tensorflow/tools/dist_test/python/mnist_replica.py
> +          save_model_secs=60,
Sorry - more clarification: I saw and understand your explanation above. But I don't understand why you need to change this testing code under tools/dist_test.

2017-04-10 04:03 UTC, caisq commented
Closing PR due to no author response. Feel free to re-open it if you'd like to work on it further.

2017-04-10 04:03 UTC, closed without merging

2017-04-10 04:20 UTC, lvjiangzhao commented on tensorflow/tools/dist_test/python/mnist_replica.py
> +          save_model_secs=60,
Sorry for the delay.  It's OK to close this because I was just trying to test some functions with this script out of it. :)