Implement atan2
tensorflow/tensorflow pull request #9276
Opened 2017-04-17 20:55 UTC by admcrae

This addresses #6095.

Since `atan2` is not implemented in Eigen, this is loosely based on the `rint` implementation. Suggestions are welcome.

2017-04-18 04:55 UTC, drpngx requested changes

2017-04-18 04:55 UTC, drpngx commented on tensorflow/core/ops/math_ops.cc
> +    .Input("y: T")
numpy uses x1, x2. It's ugly but we probably want to stay consistent.

2017-04-18 04:55 UTC, drpngx commented on tensorflow/core/kernels/cwise_ops.h
> +#if defined(__CUDACC__)
GOOGLE_CUDA

2017-04-18 04:56 UTC, drpngx commented
That will require and API review.

2017-04-18 16:44 UTC, admcrae commented
I've addressed your code comments (although I won't get a chance to test the GPU code myself until tomorrow).

2017-04-18 16:55 UTC, drpngx commented
Jenkins, test this please.

2017-04-18 16:58 UTC, drpngx commented
Could we add a test that checks random values, and also all special values listed here?
https://docs.scipy.org/doc/numpy/reference/generated/numpy.arctan2.html

Thanks

2017-04-18 18:51 UTC, admcrae commented
Done. Gradients for random arguments are rather flaky, unless I clip the inputs to be well away from zero. Perhaps this is because the gradients blow up near the origin. Curiously, I have to clip them more severely for float64 inputs, due to the stricter tolerance on the check.

2017-04-18 19:15 UTC, drpngx approved these changes

2017-04-18 19:15 UTC, drpngx commented
Jenkins, test this please.

2017-04-18 20:34 UTC, admcrae commented
Apparently `math.inf` doesn't exist in python 2. I've fixed that, but it doesn't explain the python 3 failure. How can I see the detailed log of the failure? I can't find it on the CI web interface.

2017-04-19 20:07 UTC, admcrae commented
FWIW, running bazel test --config=opt //tensorflow/python/kernel_tests:cwise_ops_test passes now (with my previous commit) for both python 2 and 3 on my local machine. Perhaps you could test it again?

2017-04-19 22:56 UTC, drpngx commented
You'll need to add an entry [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/api/golden/tensorflow.pbtxt#L635) to extend the public API.

Jenkins, test this please.

2017-04-20 12:57 UTC, admcrae commented
Done.

2017-04-20 16:14 UTC, drpngx commented
Jenkins, test this please.

2017-04-20 17:03 UTC, drpngx commented
@martinwicke this is an API change, WDYT?

2017-04-24 22:24 UTC, martinwicke requested changes
We looked at this and feel that we should follow the saner convention of y, x. Detailed comments inline.

2017-04-24 22:28 UTC, martinwicke requested changes

2017-04-24 22:28 UTC, martinwicke commented on tensorflow/core/ops/math_ops.cc
> +)doc");
After looking at the numpy docs and shivering, we decided it'll be best to stick with the time tested atan2(y,x) convention. Could you revise the docstring and arg names?

For reference: 
Python's math.atan2: https://docs.python.org/2/library/math.html
Numpy's arctan2: https://docs.scipy.org/doc/numpy/reference/generated/numpy.arctan2.html

2017-04-24 22:29 UTC, martinwicke commented
This is good from an API perspective after reverting to the `(y, x)` signature.

2017-04-25 14:34 UTC, admcrae commented
Done.

2017-04-26 23:08 UTC, martinwicke approved these changes

2017-04-26 23:08 UTC, martinwicke commented
Jenkins, test this please.

2017-04-27 00:38 UTC, martinwicke commented
Jenkins, test this please.

2017-04-27 01:43 UTC, drpngx commented
Fetch errors.

Jenkins, test this please.

2017-04-27 02:32 UTC, merged