Full set of changes to ISSUE_TEMPLATE.md
tensorflow/tensorflow pull request #9390
Opened 2017-04-23 05:43 UTC by nealwu

A few changes got missed in https://github.com/tensorflow/tensorflow/pull/9385, so I'm adding them back here.

2017-04-23 13:47 UTC, caisq approved these changes

2017-04-23 13:48 UTC, caisq commented on ISSUE_TEMPLATE.md
> +**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps indi
@nealwu In my previous PR, I added the line breaks to conform to the 80-char line width limit. I thought those are okay. Maybe there is some reason I didn't realize.

2017-04-23 16:48 UTC, drpngx requested changes

2017-04-23 16:48 UTC, drpngx commented on ISSUE_TEMPLATE.md
> +python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
That seems wrong?

2017-04-23 16:48 UTC, drpngx commented on ISSUE_TEMPLATE.md
> +Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a re
Should we revert this bit?

2017-04-23 16:48 UTC, drpngx commented on ISSUE_TEMPLATE.md
> +**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps indi
Should we revert this bit?

2017-04-24 19:42 UTC, nealwu commented on ISSUE_TEMPLATE.md
> +**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps indi
I see, we can set it up to conform to 80-character lines if that's what we want. I figured unwrapped lines would be good since GitHub will automatically wrap them for you at the issue width.

2017-04-24 19:43 UTC, nealwu commented on ISSUE_TEMPLATE.md
> +python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
The reasoning for this is that when users see this template, they will see the unformatted markdown and not the formatted version. I wanted to make it easier for them to copy-paste this command into their terminals without the shell tags.

2017-04-24 19:45 UTC, nealwu commented on ISSUE_TEMPLATE.md
> +**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps indi
For example, if you go to https://github.com/tensorflow/models/issues/new and click "Preview" you can see what it looks like. Even if I maximize Chrome, GitHub will limit the width to a reasonable amount.

2017-04-24 20:00 UTC, drpngx approved these changes
Ah, now I understand the formatting changes.

2017-04-24 20:01 UTC, merged

2017-04-24 20:04 UTC, nealwu commented
Thanks!