Allocation tracking of pre-tracked buffer returned in a tuple should increment the buffer by 2
tensorflow/tensorflow pull request #9408
Opened 2017-04-24 08:47 UTC by DavidNorman

A buffer not pre-tracked has its ref-count set to 2 when it is part of a tuple. A buffer
pre-tracked has its value increased by 1, whether it is part of a tuple or not.  This is
an error.

This fix increments a pre-tracked buffer by the amount of the 'initial_ref_count', which
is really the number of references that a buffer acquires as part of being returned (1 for
a single buffer, but 2 when it is part of a tuple).

2017-04-29 00:24 UTC, meheffernan requested changes
Thanks for the fix!

2017-04-29 00:24 UTC, meheffernan commented on tensorflow/compiler/xla/service/allocation_tracker.h
> +    CHECK_GT(ref_count_+inc, 0);
Assuming ref_count and inc are both non-negative, this CHECK_GT will only fail in the event of signed overflow which is undefined behavior so this CHECK can't be relied upon. How about replacing it with:

CHECK_GT(inc, 0);
CHECK_LT(ref_count_, INT_MAX - inc + 1);

2017-05-01 13:36 UTC, DavidNorman commented on tensorflow/compiler/xla/service/allocation_tracker.h
> +    CHECK_GT(ref_count_+inc, 0);
ok.  i was assuming that an overflow would result in a negative number. however your solution is nicer.  in practice i wouldn't expect a refcount to get anywhere close to MAX_INT

2017-05-01 20:52 UTC, meheffernan commented on tensorflow/compiler/xla/service/allocation_tracker.h
> +    CHECK_LT(ref_count_, INT_MAX-inc-1);
I think this should be:

CHECK_LT(ref_count_, INT_MAX - inc + 1);

or perhaps more clearly:

CHECK_LE(ref_count_, INT_MAX - inc);

Agreed that this is largely of theoretical interest as reference counts should never get close to INT_MAX :-)

2017-05-02 15:20 UTC, DavidNorman commented on tensorflow/compiler/xla/service/allocation_tracker.h
> +    CHECK_LT(ref_count_, INT_MAX-inc-1);
you're absolutely right - silly error

2017-05-02 17:07 UTC, meheffernan approved these changes
Looks good. Thanks!

2017-05-02 17:20 UTC, vrv commented
@tensorflow-jenkins test this please

2017-05-03 21:16 UTC, merged