Added options for linking to libraries that are present on system
tensorflow/tensorflow pull request #9615
Opened 2017-05-03 07:13 UTC by jzuern

Added options for linking dynamically to libraries that are present on local system, instead of downloading them (such as libpng, libjpeg, zlib, ...).
This reduces the file size of the shared library libtensorflow.so and adds some security since the libraries such as libpng, libjpeg may be updated independently, without having to rebuild them as part of a tensorflow build from source.

2017-05-03 17:11 UTC, jzuern commented
I signed it!

2017-05-16 00:33 UTC, jart commented
@martinwicke Do we know who the best person would be to review a nontrivial cmake build change? If I remember correctly, our friends at Microsoft are big stakeholders in this build?

2017-05-16 00:41 UTC, martinwicke commented
By default, @mrry could take a look.

2017-05-16 16:12 UTC, rmlarsen requested changes

2017-05-16 16:12 UTC, rmlarsen commented on tensorflow/contrib/cmake/CMakeLists.txt
> +option(tensorflow_BUILD_SHARED_LIB "Build TensorFlow as a shared library" ON)
Why change the default here?

I would think that we should leave all the defaults to reflect the previous behavior.

2017-06-26 18:24 UTC, drpngx requested changes

2017-06-26 18:24 UTC, drpngx commented on tensorflow/contrib/cmake/CMakeLists.txt
> +    )
Put everything on the same line.

2017-06-26 18:24 UTC, drpngx commented on tensorflow/contrib/cmake/CMakeLists.txt
> +
please remove these extra blank lines everywhere to conform with the current code.

2017-06-26 18:24 UTC, drpngx commented on tensorflow/contrib/cmake/CMakeLists.txt
> +  message(STATUS "use system zlib")
Capitalize message

2017-06-26 18:24 UTC, drpngx commented on tensorflow/contrib/cmake/CMakeLists.txt
> +else(tensorflow_USE_SYSTEM_ZLIB)
Basically this is all the same. Can we create a CMake macro or function?

2017-07-24 18:28 UTC, vrv commented
Ping for @jzuern  !

2017-08-09 17:39 UTC, rmlarsen commented
@jzuern when do you think you'll be able to finish this?

2017-08-22 00:23 UTC, jhseu commented
Hi @jzuern, this pull request hasn't been updated in a while. Closing it out as per our policy. Feel free to reopen if you'd like to update the change.

2017-08-22 00:23 UTC, closed without merging