Including batch_norm as the normalizer function by default, as mentioned in function description
tensorflow/tensorflow pull request #9652
Opened 2017-05-04 04:40 UTC by kwotsin

Changed the description error that includes `batch_norm_params`, which no longer exists, to `normalizer_fn`. `normalizer_fn = None` is changed to `normalizer_fn = batch_norm` by default, following what the original description says the function will do.

2017-05-04 22:04 UTC, fchollet requested changes

2017-05-04 22:04 UTC, fchollet commented on tensorflow/contrib/layers/python/layers/layers.py
> +    normalizer_fn=batch_norm,
This is meant to be None. Every other layer (in particular conv layers) defaults to None.

Such a change would also break many models.

2017-05-05 16:42 UTC, fchollet approved these changes

2017-05-06 16:14 UTC, drpngx commented
Jenkins, test this please.

2017-05-06 17:50 UTC, merged