Fix issue #9858.
tensorflow/tensorflow pull request #9876
Opened 2017-05-13 07:29 UTC by jiefangxuanyan

Added some byte swapping code to solve endianness problem.

2017-05-13 07:43 UTC, jiefangxuanyan commented
I signed it!

2017-05-15 17:29 UTC, rmlarsen requested changes

2017-05-15 17:29 UTC, rmlarsen commented on tensorflow/core/kernels/decode_raw_op.cc
> +      if (port::kLittleEndian != little_endian_) {
Instead if memcpy + byteswap, just use a custom copy loop for the big endian case, so you don't have to touch the data twice.

2017-05-18 04:11 UTC, jiefangxuanyan commented
@rmlarsen like this?

2017-05-18 20:12 UTC, rmlarsen approved these changes

2017-05-18 20:18 UTC, rmlarsen commented on tensorflow/core/kernels/decode_raw_op.cc
> +    } else {
Please add unit test(s) such that both branches are tested.

2017-05-18 20:18 UTC, rmlarsen requested changes
Please add unit test(s).

2017-05-19 16:38 UTC, rmlarsen requested changes
Please add a unit test.

2017-05-20 08:15 UTC, jiefangxuanyan commented
I added a test case for endianness. By the way, according to the documentation (https://www.tensorflow.org/versions/master/api_docs/python/tf/decode_raw), I think this op should behave consistently on platforms with different endianness, so I removed the endianness test in an existing test case. If the original behavior in that test case is expected, maybe you should make changes on the documentation.

2017-05-22 16:40 UTC, rmlarsen requested changes

2017-05-22 16:40 UTC, rmlarsen commented on tensorflow/python/kernel_tests/decode_raw_op_test.py
> +      result = decode_le.eval(feed_dict={in_bytes: ["\x01\x02\x03\x04"]})
Won't this depend on the endianness of the machine where this test is run? You can test the endianness of the machine here using the Python sys module, e.g.,
```
>>> import sys
>>> sys.byteorder
'little'
```

2017-05-23 06:23 UTC, jiefangxuanyan commented on tensorflow/python/kernel_tests/decode_raw_op_test.py
> +      result = decode_le.eval(feed_dict={in_bytes: ["\x01\x02\x03\x04"]})
It won't. This decode op gets same result on machines with different endianness, just like the way these machines receive data from the network. In fact, platform endianness is considered in the C++ code (`if (port::kLittleEndian == little_endian_)`) to ensure consistency. As I said before, the old platform-dependent behavior in this test is contradictionary with the documentation.

2017-05-23 16:30 UTC, rmlarsen approved these changes

2017-05-23 16:30 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-05-23 18:48 UTC, merged