Allow tensor as iou_threshold parameter to tf.image.non_max_suppression.
tensorflow/tensorflow pull request #9887
Opened 2017-05-14 03:51 UTC by xodus7

I have a use case where dynamically changing the iou_threshold parameter on a frozen graph is required. I'm not 100% positive this doesn't violate the backwards compatibility rules, and it does make the iou_threshold a required parameter. Feedback from the maintainers would be appreciated.

2017-05-15 17:15 UTC, rmlarsen commented
Since this changes the functionality of the op, I believe you have to do this by 

1) adding a new kernel named NonMaxSuppressionOpV2 
2) migrate all producers (e.g. Python wrappers) to use that kernel instead.

See this for more details:
https://www.tensorflow.org/programmers_guide/data_versions

2017-05-15 17:18 UTC, vrv commented
(Though you have to wait 3 weeks after checking in the new Op/OpKernel before changing the python code).

2017-05-16 06:31 UTC, xodus7 commented
Ok, I moved my changes into a new NonMaxSuppressionV2Op as suggested.

2017-05-16 15:57 UTC, rmlarsen requested changes
Looks good! Just one nit.

2017-05-16 15:57 UTC, rmlarsen commented on tensorflow/core/kernels/non_max_suppression_op.cc
> +static void DoNonMaxSuppressionOp(OpKernelContext* context,
Nit: Could you put this in anonymous namespace instead of making it static?

2017-05-17 00:16 UTC, xodus7 commented on tensorflow/core/kernels/non_max_suppression_op.cc
> +static void DoNonMaxSuppressionOp(OpKernelContext* context,
Done!

2017-05-17 03:18 UTC, rmlarsen approved these changes

2017-05-17 03:19 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-05-17 04:36 UTC, merged