Quantize conv2d transpose
tensorflow/tensorflow pull request #9924
Opened 2017-05-15 23:31 UTC by kumasento

This PR creates a new quantized kernel called `QuantizedDeconv2D`, which performs a deconvolution computation (also known as `conv2d_transpose` in TensorFlow) in a quantized mode.

The current progress of this new kernel includes:

1. A reference implementation of deconvolution
2. Two unit tests with small dimensions and different strides
3. Only `VALID` padding is allowed

Further guidance on this work is welcomed!

2017-06-26 18:45 UTC, drpngx commented
@andrewharp what do you think?

2017-07-24 18:44 UTC, petewarden reviewed
Thanks for putting this together, a very nice contribution! I've added some comments.

2017-07-24 18:44 UTC, petewarden commented on tensorflow/core/kernels/quantized_deconv_ops.cc
> +/* Copyright 2015 The TensorFlow Authors. All Rights Reserved.
Update to 2017

2017-07-24 18:44 UTC, petewarden commented on tensorflow/core/kernels/quantized_deconv_ops.cc
> +      // OP_REQUIRES(context, strides_[1] == 1,
Can you clarify whether this is still true? If not, remove the commented-out code, otherwise make it active.

2017-07-24 18:44 UTC, petewarden commented on tensorflow/core/ops/nn_ops.cc
> +    // TODO: Don't understand this shape handle funtion for now, will check later
Please copy the code from the Conv2DBackpropInput shape function here:
https://github.com/kumasento/tensorflow/blob/3d50e2ef0f823b3c2e7dc5070734fe418d4ce32b/tensorflow/core/ops/nn_ops.cc#L566

2017-07-24 18:44 UTC, petewarden commented on tensorflow/stream_executor/cuda/cuda_dnn.cc
> -#include "cuda/include/cudnn.h"
Is this change relevant to the PR?

2017-07-24 18:44 UTC, petewarden commented on tensorflow/tools/graph_transforms/quantize_nodes.cc
> +          LOG(INFO) << SummarizeNodeDef(float_node);
Is this change needed?

2017-07-24 18:44 UTC, petewarden commented on tensorflow/tools/graph_transforms/quantize_nodes.cc
> +       {},
Can you also add a simple test to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/quantize_nodes_test.cc#L315

2017-07-26 22:51 UTC, kumasento commented on tensorflow/core/kernels/quantized_deconv_ops.cc
> +/* Copyright 2015 The TensorFlow Authors. All Rights Reserved.
Done

2017-07-26 22:51 UTC, kumasento commented on tensorflow/core/ops/nn_ops.cc
> +    // TODO: Don't understand this shape handle funtion for now, will check later
Done

2017-07-26 22:51 UTC, kumasento commented on tensorflow/stream_executor/cuda/cuda_dnn.cc
> -#include "cuda/include/cudnn.h"
Done

2017-07-26 22:52 UTC, kumasento commented on tensorflow/tools/graph_transforms/quantize_nodes.cc
> +          LOG(INFO) << SummarizeNodeDef(float_node);
Done

2017-07-26 23:12 UTC, kumasento commented
@petewarden Hi Pete, thank you so much for your comments and review! I have fixed several of them and will come back later for the rest.

2017-08-09 17:36 UTC, rmlarsen commented
@petewarden could you take another look, please?

2017-09-17 02:05 UTC, drpngx commented
@petewarden any cycles to look at this? Feel free to assign someone else.

2017-09-26 21:05 UTC, sb2nov commented
@petewarden ping

2017-11-06 21:54 UTC, petewarden requested changes
Sorry for the very slow response on this. I've added some minor comments, but overall looks good, thanks.

2017-11-06 21:54 UTC, petewarden commented on tensorflow/core/ops/nn_ops.cc
> +  // .Attr("Tinput: numbertype")
Remove this commented-out code.

2017-11-06 21:54 UTC, petewarden commented on tensorflow/core/ops/nn_ops.cc
> +    // TF_RETURN_IF_ERROR(shape_inference::Conv2DShape(c));
Remove this commented-out code.

2017-11-06 21:54 UTC, petewarden commented on tensorflow/stream_executor/cuda/cuda_dnn.cc
> +#include "cuda/cudnn.h"
Can we revert the changes to this file entirely, since we're not expecting any alterations?

2017-11-09 15:13 UTC, kumasento commented
@petewarden Hi Pete, sorry for my late reply. Thank you for your kind comments. I resolved most of your issues mentioned previously.

There is only one thing left: you mentioned that I should implement a test in tensorflow/tools/graph_transforms/quantize_nodes.cc
I tried, but the problem is: there is no corresponding C++ implementation of `Conv2DTranspose`,
and what we have is `Conv2DBackpropInput`. So I think maybe it is a better idea to establish a clear mapping between `QuantizedConv2DTranspose` and `Conv2DBackpropInput` before writing the test. 

However, before I start to work on it, could you please help me with the following question:
Should I build `QuantizedConv2DTranspose` on a new `QuantizedConv2DBackpropInput` op and map that to `Conv2DBackpropInput`, or:
directly map `QuantizedConv2DTranspose` to `Conv2DBackpropInput`?

Thanks again for all your help.

2017-11-09 16:23 UTC, petewarden commented
Thanks for your flexibility on this!

> directly map QuantizedConv2DTranspose to Conv2DBackpropInput?

I think this approach is best.

2017-11-10 16:29 UTC, kumasento commented
@petewarden Hi, I just added a simple test regarding quantizing `Conv2DBackpropInput` to `QuantizedConv2DTranspose`. 
There is also a slight change in the quantize graph generation part, which can allow you convert a node to a quantized one with a custom node name, not just Quantized*.

Please let me know if you have further suggestions. Thanks!

2017-12-12 19:55 UTC, martinwicke commented
@petewarden can you take another look?

2017-12-27 02:22 UTC, drpngx commented
@petewarden any luck with this?

2018-01-17 13:02 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-06 07:43 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-02-20 19:40 UTC, tensorflowbutler commented
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-07 13:18 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-03-25 00:57 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-08 18:32 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-04-14 20:30 UTC, xiaocai00 commented
any luck with this one?

2018-04-29 18:31 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-14 19:00 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-29 19:03 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-05-30 15:09 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-14 18:48 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-06-29 18:54 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 75 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-14 18:38 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-07-29 18:32 UTC, tensorflowbutler commented
Nagging Assignee @petewarden: It has been 105 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

2018-08-13 22:40 UTC, petewarden commented
Sorry for the long delay on this PR. We're moving away from this approach for supporting quantization inside TensorFlow (all quantized ops now live in TF Lite), so unfortunately we'll need to close this request.

2018-08-13 22:40 UTC, closed without merging