fix a bug in ReductionOp
tensorflow/tensorflow pull request #9965
Opened 2017-05-17 09:17 UTC by snnn

2017-05-18 03:25 UTC, snnn commented
Indeed, this bug only affects 32 bits builds. Is there any one using 32-bits tensorflow?

2017-05-18 04:43 UTC, yaroslavvb commented
@samjabrahams are Raspberry Pi TF builds 32 bit by any chance?

2017-05-19 06:56 UTC, samjabrahams commented
@yaroslavvb yes- though unfortunately I won't be able to play around with the effect of this code for a week or two (traveling).

Is this the gist of the problem: casting between `size_t` and `int64` on 32-bit systems causes memory to not be freed/tracked properly? Just trying to make sure I'm following.

2017-05-19 07:17 UTC, snnn commented
The following code:

	#include <iostream>
	#include <stdint.h>

	void record_host_persistent_memory_allocation(int64_t size) {
		std::cout << size << std::endl;
	}
	int main() {
		size_t a = 3;
		record_host_persistent_memory_allocation(-a);
		return 0;
	}

output is "4294967293" on 32 bits build and "-3" on 64 bits build.

2017-05-19 07:34 UTC, samjabrahams commented
I'll take a looksy when I am near some hardware. I also need to double check exactly which flags are set when TensorFlow compiles.

2017-05-19 15:34 UTC, rmlarsen requested changes

2017-05-19 15:34 UTC, rmlarsen commented on tensorflow/core/kernels/reduction_ops_common.h
> +        ctx->record_host_temp_memory_size(-(int64)out.AllocatedBytes());
Please use C++ style casts, i.e. static_cast<int64>(foo).

2017-05-20 08:51 UTC, snnn commented on tensorflow/core/kernels/reduction_ops_common.h
> +        ctx->record_host_temp_memory_size(-(int64)out.AllocatedBytes());
@rmlarsen fixed.

2017-05-22 16:12 UTC, rmlarsen commented
@tensorflow-jenkins test this please

2017-05-22 18:06 UTC, rmlarsen approved these changes

2017-05-22 18:07 UTC, merged